CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afganistan');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Ahvenanmaa');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Alankomaat');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Alankomaiden Antillit');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albania');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Algeria');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Amerikan Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andorra');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Anguilla');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Antarktis');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigua ja Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Arabiemiirikunnat');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argentiina');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armenia');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'Ascension-saari');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Australia');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azerbaidžan');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahama');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrain');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladesh');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbados');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belgia');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benin');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Bhutan');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolivia');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosnia ja Hertsegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'Bouvet’nsaari');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brasilia');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Britannia');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Brittiläinen Intian valtameren alue');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Brittiläiset Neitsytsaaret');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgaria');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Caymansaaret');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'Ceuta ja Melilla');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Chile');
INSERT INTO `country` (`id`, `name`) VALUES ('CP', 'Clippertoninsaari');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Cookinsaaret');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Costa Rica');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'Diego Garcia');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Djibouti');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominica');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Dominikaaninen tasavalta');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ecuador');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Egypti');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'El Salvador');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritrea');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Espanja');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Etelä-Afrikka');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'Etelä-Georgia ja Eteläiset Sandwichsaaret');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Etelä-Korea');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Etiopia');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Falklandinsaaret');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fidži');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filippiinit');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Färsaaret');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabon');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Georgia');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ghana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Gibraltar');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Grönlanti');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Guadeloupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guam');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Guatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'Guernsey');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'Heard- ja McDonaldinsaaret');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'Hongkong – Kiinan e.h.a.');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Huippuvuoret ja Jan Mayen');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonesia');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Intia');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Irak');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iran');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irlanti');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Islanti');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Israel');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italia');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Itä-Timor');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Itävalta');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaika');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japani');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Jemen');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'Jersey');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordania');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Joulusaari');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambodža');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kamerun');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'Kanariansaaret');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Kap Verde');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazakstan');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenia');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Keski-Afrikan tasavalta');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Kiina');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirgisia');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolumbia');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Komorit');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Kongon demokraattinen tasavalta');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongon tasavalta');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'Kookossaaret');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Kreikka');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Kroatia');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kuuba');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuwait');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Kypros');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laos');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Latvia');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libanon');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberia');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libya');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Liechtenstein');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Liettua');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Luxemburg');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Länsi-Sahara');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Macao – Kiinan e.h.a.');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagaskar');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Makedonia');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Malediivit');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malesia');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'Mansaari');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Marokko');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Marshallinsaaret');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinique');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauritania');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Mauritius');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayotte');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Meksiko');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikronesian liittovaltio');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldova');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monaco');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongolia');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mosambik');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Myanmar [Burma]');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibia');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepal');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nicaragua');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Niger');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigeria');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Norfolkinsaari');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norja');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Norsunluurannikko');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Palestiina');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papua-Uusi-Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paraguay');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitcairn');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Pohjois-Korea');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Pohjois-Mariaanit');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portugali');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Puerto Rico');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Puola');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Päiväntasaajan Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Qatar');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Ranska');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Ranskan Guayana');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Ranskan Polynesia');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'Ranskan ulkopuoliset eteläiset alueet');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Réunion');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romania');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Ruanda');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Ruotsi');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Saint Helena');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Saint Kitts ja Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Saint Lucia');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Saint Vincent ja Grenadiinit');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'Saint-Barthélemy');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'Saint-Martin');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Saint-Pierre ja Miquelon');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Saksa');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Salomonsaaret');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Sambia');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'São Tomé ja Príncipe');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Saudi-Arabia');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegal');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Serbia');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Serbia ja Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seychellit');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sierra Leone');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapore');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Slovakia');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Slovenia');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somalia');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudan');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Suomi');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Surinam');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Sveitsi');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Swazimaa');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Syyria');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tadžikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tansania');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Tanska');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Thaimaa');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad ja Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Tšad');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Tšekki');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunisia');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Turkki');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Turks- ja Caicossaaret');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukraina');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'ulkomeri');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Unkari');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Uruguay');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Uusi-Kaledonia');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Uusi-Seelanti');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzbekistan');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Valko-Venäjä');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatikaani');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Venäjä');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vietnam');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Viro');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis ja Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Yhdysvallat');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Yhdysvaltain Neitsytsaaret');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'Yhdysvaltain pienet erillissaaret');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
