CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Afrika ya Kusini');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Ajentina');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua na Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Arabuni Saudi');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Barafu');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosnia na Herzegowina');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brazili');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Chadi');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominika');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekvado');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filipino');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Guinea ya Ikweta');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Hungaria');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Iraki');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamaika');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Jamhuri ya Afrika ya Kati');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Jamhuri ya Czech');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Jamhuri ya Dominikan');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Jibuti');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamerun');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kampuchea');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenya');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Kitonga');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolombia');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Korea ya Kaskazini');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Korea ya Kusini');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Kroatia');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luksemburg');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malasya');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Meksiko');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Misri');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monako');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Moroko');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Msumbiji');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Muugano wa Falme za Nchi za Kiarabu');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Muungano wa Nchi za Amerika');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepali');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikaragua');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papua Guinea Mpya');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paragwai');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Pwani ya Pembe');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Rasi Verde');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Saint Kitts na Nevis');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Saint Vincent na Grenadines');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sao Tome na Principe');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Serbiya da Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somali');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzania');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Timor ya Mashariki');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad na Tobago');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Uajemi');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Ubelgiji');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Uchina');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Udachi');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Udenmarki');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Ufaransa');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Uhabeshi');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Uhindi');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Uhispania');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Uholanzi');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Uingereza');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Uitaliani');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Ujapani');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Unorwe');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Ureno');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Urugwai');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Urusi');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Uswidi');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Uswisi');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Uturuki');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Uyahudi');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikano');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Visiwa vya Bahama');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Visiwa vya Komoro');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Visiwa vya Marshall');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Visiwa vya Shelisheli');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Visiwa vya Solomon');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Yemeni');
