CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AL', 'Àabɛnìa');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Àadzɛlìa');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Àdzɛ̀ntinà');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Adzɨmā kɨ ŋgùŋ kɨ Palɛsɨtɨnyia à kɨ Gazà kò');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Aelɨ̀lân');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Aesɨ̀lân');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Àfɨ̀ganìsɨ̀tân');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Afɨlekà ghɨ Emàm ghò');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Àlubà');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Àmɛlekan Samwà');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Àmɛnyìa');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Àndolà');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Àntigwà à Bàbudà');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Àŋgolà');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Àŋgwilà');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Àzɨbɛ̀dzân');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Bàbadòs');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bàhamàs');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bàlaen');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Baŋgɨ̀làdɛ̂');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Bɛɛdzwùm');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Bɛlàlûs');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Bɛ̀lezɨ̀');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bɛ̀mudà');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Bɛ̀nɨ̂ŋ');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Bɨ̀làzîi');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Bɨ̀lunè');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bòlevà');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosɨnyìa à Hɛ̀zɛ̀gòvinà');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Bòtɨ̀swǎnà');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Bùkinà Fasò');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Bùlundì');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bùugɛlìa');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Châ');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Chaenà');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Chɛ̂ Lèkpubèlè');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Chilè');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Chwɨlà fɨ Fakɨlàn');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Chwɨlà fɨ Mashà');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Chwɨlà fɨ Nufòʔ');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Chwɨlà fɨ Solomwɨ̀n');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Chwɨlà m̀ Màlǐanà mɨ̀ Ekùw mò');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Chwɨlà m̀ Vidzinyìa m̀ Bɨ̀letì mò');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Chwɨla n Tɨtê à Kaekùs');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Chwɨlà ŋ̀ Kaemàn');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Chwɨla ŋ̀ Kɛ̀b Vɛ̂ɛ');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Chwɨla ŋ̀ Kûʔ');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Dɛ̀mùkàlatì Lèkpubèlè è Kuŋgù');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Dɛnɨmà');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Dɨŋò kɨ dzughùnstòʔ kɨ Endìa kɨ Bɨ̀letì kò');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dòmenekà');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Dòmenekà Lèkpubèlè');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Dzàkpân');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Dzamanè');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Dzàmɛkà');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Dzibɨ̀latà');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Dzìbuwtì');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Dzodàn');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Dzɔɔdzìa');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Edzì');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekwadò');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Èkwɛ̀tolia Ginè');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Èlâkɨ̀');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Èlân');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Èletɨ̀là');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Endìa');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Èndòneshìa');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Ês Taemò');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Esàvadò');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Èsɨ̀tonyìa');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Etalè');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Ètyǒpìa');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Ezɨ̀lɛ̂');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Fàlâŋnsì');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Felèkpî');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fidzi');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Fɨnlàn');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Gaanà');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gàbûn');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambìa');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Gàyanà è Fàlâŋnsì');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Ginè');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Ginè Bìsawù');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Gɨ̀anyɨ');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Gɨ̀lenlân');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Gɨ̀lês');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Gɨ̀lɛnadà');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Gùyanà');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Gwadalukpɛ̀');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Gwam');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Gwàtɨ̀malà');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Hǎetì');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Hɔndulàs');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Hɔŋgàlè');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Kàlèdonyìa È fūghū');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kàmàlûŋ');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kàmbodìa');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanadà');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Katà');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kàzasɨ̀tân');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kèlèbati');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kìdzisɨ̀tân');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kɨnyà');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kòlombìa');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komolòs');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kòsɨ̀tà Lekà');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Kòwɛshìa');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Kpakìsɨ̀tân');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Kpakpua Ginè È fūghū');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Kpalàgwɛ̂');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Kpàlawù');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Kpanàma');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Kpɛlû');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Kpitɨ̀kalè');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Kpoleneshìa è Fàlâŋnsì');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Kpǒto Leko');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Kpulàn');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Kputuwgà');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Ku Dɨ̀vûa');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kuŋgù');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Kùulîa, Ekùw');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Kùulîa, Emàm');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kuuwbà');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kùwɛ̂');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Làebɛlìa');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Làtɨva');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Làwos');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Lebìa');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Letɨnshɨ̀n');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Lètwǎnyìa');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Lèyunyɔ̀ŋ');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Lɛbanè');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lɛ̀sotù');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Loshìa');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Lùmanyìa');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Lùwandà');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luzɨmbùʔ');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Maatà');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Màdàgasɨkà');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Màdivè');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Maekòlòneshìa');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Màlawì');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Malè');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Màlɛshìa');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Màtìnekì');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Màyotì');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Mbutàn');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mɛkɨzikù');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Mǐanmà');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Mɨ̀sɨ̀donyìa');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Mòlokò');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Mòodovà');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Mùleshwɨ̀s');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mùlètanyìa');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Mùnaku');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mùŋgolìa');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Mùŋtselà');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mùzàmbî');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Naedzà');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Nàmibìa');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nàwulù');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Nedàlân');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Nedàlân Antàe');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nɛkpâa');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikàlagwà');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niyu');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Noowɛ̂ɛ');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Saekpùlù');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Sàmowà');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'Sàn Màlenù');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sawo Tɔ̀me à Kpèlènsikpɛ̀');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Sawudi Alabi');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Sɛchɛ̀lɛ̀s');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Sɛɛbìa à Mùŋtànegùlù');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Sɛ̀n Èlenà');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Sɛ̀n Kî à Nevì');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Sɛ̀n Kpiyɛ̀ à Mikelɔŋ');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Sɛ̀n Lushìa');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Sɛ̀n Vinsɨ̀n à Gɨlenadi Ù tē');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Sɛ̀nɛ̀gâa');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Sɛnta Afɨlekan Lèkpobèlè');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Shǔazìlân');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Silîa');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Silìa lûŋ');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Siŋgàkpôo');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Sɨ̀kpɛ̂n');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sɨ̀le Laŋkà');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Sɨ̀lòvɨkɨ̀a');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Sɨ̀lòvɨnyìa');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Sòmalìa');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sùdân');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Suedɨ̀n');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Suezàlân');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Sulènamè');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tàanzanyìa');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tàdzikìsɨ̀tân');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Taelàn');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taewàn');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Teekì');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Tekɨmènèsɨ̀tân');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Tèlenedà à Tòbagù');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Tugù');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tùneshìa');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tuŋgà');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tuwkelawù');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuwvalùw');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'U. S. Chwɨlà fɨ Mbuʔmbu');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Umàn');
INSERT INTO "country" ("id", "name") VALUES ('US', 'USA');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Ùsɨ̀tɛ̀lɛlìa');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Usɨtɨ̀là');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vànǔatùw');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikàn Sɨ̀tɛ̂');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Vɛ̀nɛ̀zǔɛɛlà');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vìyɛnàm');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wales à Fùwtuwnà');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Yɛmɛ̀n');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Yùgandà');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Yùkɛ̀lɛ̂');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Yulùgwɛ̂');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Yùnaetɛ Alab ɛmelɛ̀');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Yùnaetɛ Kiŋdɔ̀m');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Yùzɨ̀bɛkìsɨ̀tân');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambìa');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Zìlân È fūghū');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zìmbagbɛ̀');
