CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afganistaan');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Afrik bŋ Worgo');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Ajerbayjaan');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Alaseri');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albanii');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Almaañ');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Anndoora');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anngiyaa');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Anngolaa');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antiguwaa e Barbudaa');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Antiiye Nederlanndeeje');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Arabii Sawdit');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Arjantiin');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armenii');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruuba');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamaas');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahreyn');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Banglaadees');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbadoos');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Belaruus');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Beliise');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Beljik');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benee');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Beresiil');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermudaa');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Boliwii');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnii Hersegowiin');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswaana');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgarii');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkibaa Faaso');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Burnaay');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burunndi');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Butaan');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Caad');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Cilii');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Danmark');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominika');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Dowla Waticaan');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Dowlaaji Dentuɗi Amerik');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Duuɗe Falkland');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Duuɗe Kap Weer');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Duuɗe Kaymaa');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Duuɗe Kecce Amerik');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'duuɗe kecce britanii');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Duuɗe Kuuk');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Duuɗe Mariyaana Rewo');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Duuɗe Marsaal');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Duuɗe Norfolk');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Duuɗe Solomon');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Duuɗe Turke e Keikoos');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Ecoppi');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Ejipt');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ekuwatoor');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'El Salwador');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Emiraat Araab Denntuɗe');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Enndo');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Enndonesii');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eriteree');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Espaañ');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estoni');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Farayse');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Fenland');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fijji');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipiin');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gaboo');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gammbi');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ganaa');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Garnaad');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Gerees');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Gine');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Gine-Bisaawo');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Ginee Ekuwaatoriyaal');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Giyaan');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Giyaan Farayse');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Gorwendland');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guwam');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Gwaadalup');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Gwaatemalaa');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haytii');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Iraak');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Iraan');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Irlannda');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Islannda');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Israa''iila');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Itali');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jamayka');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Jeorgii');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Jibraltaar');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Jibutii');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Jordani');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kambodso');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kameruun');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanadaa');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kasakstaan');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Kataar');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Keeriindi britaani to maayo enndo');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Keñaa');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kirgistaan');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribari');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Kodduwaar');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolombiya');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Komoor');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Konngo');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Koree Rewo');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Koree Worgo');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Korwasii');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kosta Rikaa');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kubaa');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuweyti');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Laamateeri Rentundi');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Lawoos');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesoto');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Letonii');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Libaa');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberiyaa');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libi');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Liksembuur');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Lincenstayn');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lituaanii');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Maali');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagaskaar');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malaawi');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maldiiwe');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malesii');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malte');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martinik');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Maruk');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayoot');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Meceduwaan');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Meksik');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikoronesii');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Miyamaar');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldawii');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monaakoo');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Monngolii');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Monseraat');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Moriis');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mosammbik');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Muritani');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibii');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nawuru');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Ndenndaandi Cek');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Ndenndaandi Demokaraasiire Konngo');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Ndenndaandi Santarafrik');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Ndenndanndi Dominika');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Nederlannda');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepaal');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Nijeer');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nijeriyaa');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikaraguwaa');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niuwe');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norwees');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Nuwel Kaledonii');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Nuwel Selannda');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Omaan');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Onnduraas');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Onngiri');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Ostaraalii');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Otiriis');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistaan');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palawu');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Palestiin Sisjordani e Gaasaa');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panamaa');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papuwaa Nuwel Gine');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguwaay');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peru');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitkern');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Polinesii Farayse');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Poloñ');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Porto Rikoo');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Purtugaal');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Rewiñoo');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Riisii');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Rumanii');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Ruwanndaa');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Sammbi');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samowa Amerik');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samowaa');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Sapoo');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Sawo Tome e Perensipe');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'See Maree');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'See Piyeer e Mikeloo');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'See Weesaa e Garnadiin');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegaal');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Sent Helen');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Sent Kits e Newis');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Sent Lusiyaa');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Seraa liyon');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Serbii e Montenegoroo');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seysel');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Siin');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Siipar');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Simbaabuwe');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Sinngapuur');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Siri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Sirii');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slowakii');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slowenii');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somalii');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudaan');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinaam');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Suweed');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Suwiis');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Swaasilannda');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tajikistaan');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tansanii');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Taylannda');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taywaan');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timoor Fuɗnaange');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Tirnidaad e Tobaago');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togoo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelaaw');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonngaa');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunisii');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Turkii');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turkmenistaan');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuwaluu');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukereen');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Unganndaa');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruguwaay');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Usbekistaan');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Walis e Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Wanuwaatuu');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Wenesuwelaa');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Wiyetnaam');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yemen');
