CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AO', 'అంగోలా');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'అంటార్కటికా');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'అజర్బైజాన్');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'అన్డోరా');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'అమెరికన్ సమోవా');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'అరుబా');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'అల్జీరియా');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'అల్బేనియా');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'ఆంగవిల్లా');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'ఆంటిగ్వా మరియు బార్బుడా');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'ఆఫ్ఘానిస్తాన్');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'ఆర్జెంటినా');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'ఆర్మేనియా');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'ఆలేండ్ దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'ఆస్ట్రియా');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'ఆస్ట్రేలియా');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'ఇండోనేషియా');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'ఇటలి');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'ఇథియోపియా');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'ఇరాక్');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'ఇరాన్');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'ఇస్రాయేల్');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'ఈక్వడోర్');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'ఈజిప్ట్');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'ఉజ్బెకిస్తాన్');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'ఉత్తర కొరియా');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'ఉత్తర మరియానా దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'ఉరుగువే');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'ఎక్వేటోరియాల్ గినియా');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'ఎరిట్రియా');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'ఎల్ సాల్వడోర్');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'ఎసెషన్ దీవి');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'ఎస్టోనియా');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'ఐర్ లాండ్');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'ఐల్ ఆఫ్ మాన్');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'ఐవరీ కోస్ట్');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'ఐస్లాండ్');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'ఒమాన్');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'ఒషేనియా బయటున్నవి');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'కంబోడియా');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'కజాఖస్తాన్');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'కతర్');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'కాంగో- కిన్షాసా');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'కాంగో- బ్రాజావిల్లి');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'కిరిబాటి');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'కిర్జిస్తాన్');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'కుక్ దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'కువైట్');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'కెనడా');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'కెన్యా');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'కెమరూన్');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'కేనరీ దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'కేప్ వెర్డే');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'కేమాన్ దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'కొమొరోస్');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'కొలంబియా');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'కోకోస్ దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'కోస్టారికా');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'క్యూబా');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'క్రిస్మస్ దీవి');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'క్రొత్త కాలెడోనియా');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'క్రోయేషియా');
INSERT INTO "country" ("id", "name") VALUES ('CP', 'క్లిప్పర్టన్ దీవి');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'గయానా');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'గాంబియా');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'గినియా');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'గినియా-బిస్సావ్');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'గేబన్');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'గ్రీన్లేండ్');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'గ్రీస్');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'గ్రెనెడా');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'గ్వాటిమాల');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'గ్వాడేలోప్');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'గ్వామ్');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'గ్వేర్నసే');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'ఘానా');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'ఙర్మని');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'చాద్');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'చిలి');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'చెక్ గణరాజ్యం');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'చైనా');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'చైనా యొక్క హాంగ్కాంగ్');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'జపాన్');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'జమైకా');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'జర్సి');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'జాంబియా');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'జార్జియా');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'జార్డాన్');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'జింబాబ్వే');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'జిబౌటి');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'జిబ్రాల్టార్');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'టర్కీ');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'టాంజానియా');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'టాజీకిస్తాన్');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'టిమోర్-లెస్టె');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'టువాలు');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'టైవాన్');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'టోంగా');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'టోకేలావ్');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'టోగో');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'ట్యునీషియా');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'ట్రినిడేడ్ మరియు టొబాగో');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'ట్రిస్టన్ డ కన్హా');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'డియాగో గార్సియా');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'డెన్మార్క్');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'డొమినికన్ గణ రాజ్యం');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'డోమెనిక');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'తుర్కమెస్తాన్');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'తుర్క్ మరియు కాలికోస్ దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'థాయ్ లాండ్');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'దక్షిణ ఆఫ్రికా రాజ్యం');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'దక్షిణ కొరియా');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'దక్షిణ జార్జియా మరియు దక్షిణ సాండ్విచ్ దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'నమీబియా');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'నారవే');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'నార్ఫాక్ దీవి');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'నికరాగువా');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'నియు');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'నేదర్లాండ్స్');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'నేదేర్లేండ్స్ అంటిల్లిస్');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'నేపాల్');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'నైజర్');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'నైజీరియా');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'నౌరు');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'న్యుజిలేండ్');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'పడమటి సహారా');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'పనామా');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'పలావు');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'పాకిస్తాన్');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'పాపువా న్యు గినియా');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'పాలిస్తినియాన్ ప్రాంతం');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'పిట్కెర్న్');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'పెరగువే');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'పెరూ');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'పోటోరికో');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'పోర్చుగల్');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'పోలాండ్');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'ఫాక్ లేండ్ దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'ఫారో దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'ఫిజి');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'ఫిన్లాండ్');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'ఫిలి పైన్స్');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'ఫ్రాన్స్‌');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'ఫ్రెంచ్ గియానా');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'ఫ్రెంచ్ దక్షిణ ప్రాంతాలు');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'ఫ్రెంచ్ పోలినిషియా');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'బర్మయుడా');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'బల్గేరియా');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'బహరేన్');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'బహామాస్');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'బాంగ్లాదేష్');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'బార్బడోస్');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'బాస్నియా మరియు హీర్జిగోవినా');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'బురుండి');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'బుర్కినా ఫాసో');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'బెనిన్');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'బెలారస్');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'బెలీజ్');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'బెల్జియం');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'బొలీవియా');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'బొవెట్ దీవి');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'బోట్స్వానా');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'బ్రజిల్');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'బ్రిటన్');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'బ్రిటిష్ భారతీయ ఓషన్ ప్రాంతం');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'బ్రిటిష్ వర్జిన్ దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'బ్రునై');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'భారత దేశం');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'భూటాన్');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'మంగోలియా');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'మధ్యమ ఆఫ్రికా రిపబ్లిక్');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'మలేషియా');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'మాకావ్ సార్ చైనా');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'మాడ్గాస్కార్');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'మాయొట్టి');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'మారిషస్');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'మార్టినిక్');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'మార్షల్ దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'మాలావి');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'మాలి');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'మాల్టా');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'మాల్దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'మెక్సికో');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'మేసెడోనియా');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'మైక్రోనేశియ');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'మొజాంబిక్');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'మొనాకో');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'మొరాక్కో');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'మోంటేనేగ్రో');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'మోంట్సేర్రాట్');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'మోల్ డోవ');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'మౌరిటేనియా');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'మ్యాన్మార్');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'యు.ఎస్. వర్జిన్ దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'యుక్రెన్');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'యుగాండా');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'యునైటెడ్ ఆరబ్ ఎమిరేట్స్');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'యురోపియన్ యునియన్');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'యెమెన్');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'రష్య');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'రియూనియన్');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'రోమానియా');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'ర్వాండా');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'లక్సంబర్గ్');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'లాట్వియ');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'లావోస్');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'లిక్టెస్టేన్');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'లిథుయేనియా');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'లిబియా');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'లెబనాన్');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'లెసోతో');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'లైబీరియా');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'వనౌటు');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'వాలిస్ మరియు ఫ్యుత్యునా');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'వియట్నాం');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'వెనుజువేలా');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'వేటికెన్');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'శ్రీలంక');
INSERT INTO "country" ("id", "name") VALUES ('US', 'సంయుక్త రాజ్య అమెరికా');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'సంయుక్త రాజ్య అమెరికా యునైటెడ్ స్టేట్స్ మైనర్ బయట ఉన్న దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'సమోవా');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'సర్బియా మరియు మంటెనీగ్రో');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'సాన్ మారినో');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'సావోటోమ్ మరియు ప్రిన్సిపే');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'సింగపూర్');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'సియెర్రా లియాన్');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'సిరియా');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'సీషెల్స్');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'సుడాన్');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'సురినామ్');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'సెంట్ కిట్ట్స్ మరియు నెవిస్');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'సెంట్ పియెర్ మరియు మికెలాన్');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'సెంట్ బర్తేలెమీ');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'సెంట్ మార్టిన్');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'సెంట్ లూసియా');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'సెంట్ విన్సెంట్ మరియు గ్రెనడీన్స్');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'సెంట్ హెలినా');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'సెనెగల్');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'సెర్బియా');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'సైప్రస్');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'సోమాలియా');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'సోలోమన్ దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'సౌదీ అరేబియా');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'స్పేన్');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'స్యూటా మరియు మెలిల్లా');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'స్లోవేకియా');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'స్లోవేనియా');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'స్వాజీలేండ్');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'స్వాల్బార్డ్ మరియు యాన్ మాయేన్');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'స్విట్జర్లేండ్');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'స్వీడన్');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'హన్గేరి');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'హెర్డ్ దీవి మరియు మాక్ డోనాల్డ్ దీవులు');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'హైటి');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'హోండోరాస్');
