CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afganistan');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Afrika e Jugut');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Algjeri');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andorrë');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angolë');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua e Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Arabia Saudite');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Argjentinë');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armeni');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Australi');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Austri');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azerbajxhan');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahrein');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Belgjikë');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Bjellorusi');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolivi');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosnja dhe Hercegovina');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botsvana');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brazili');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Bregu i Fildishtë');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brunej');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bullgari');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Butan');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Çad');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Danimarkë');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominikë');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Egjipt');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekuator');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Emiratet Arabe te Bashkuara');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritre');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Estoni');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Etiopi');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filipine');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finlandë');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fixhi');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Francë');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambi');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Ganë');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Greqi');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guajana');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatemalë');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Guine');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Guine Bisau');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Guineja Ekuatoriale');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gjabon');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Gjeorgji');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Gjermani');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Hungari');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Indi');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indonezi');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Irak');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Irlandë');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Islandë');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Ishujt Aland');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Ishujt Marshall');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Ishujt Solomon');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Itali');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Izrael');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japoni');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Jemen');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jordani');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kamboxhi');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamerun');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Kap Verde');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Katar');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazakistan');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenia');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Kili');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Kinë');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirgistan');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolumbi');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komore');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Koreja e Jugut');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Koreja e Veriut');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kosta Rika');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Kroaci');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kubë');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kuvajt');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesoto');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Letoni');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Liban');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberi');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libi');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Lihtënshtajn');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Lituani');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luksemburg');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagaskar');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malajzi');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malavi');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldivit');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Maltë');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Maqedoni');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Maroko');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mauritani');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Mbretëria e Bashkuar');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Meksikë');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikronezi');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldavi');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monako');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongoli');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mozambik');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibi');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nigeri');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikaragua');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Norvegji');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papua Guineja e Re');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguaj');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Poloni');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portugali');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Qipro');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Qiribati');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Republika Dominikanë');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Republika e Çekisë');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Republika Qendrore e Afrikës');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ruanda');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Rumani');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Rusi');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Saharaja Perëndimore');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Saint Kitts e Nevis');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Saint Vincent e Grenadinet');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sao Tome e Prinsipe');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Serbië en Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Siera Leone');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapor');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Siri');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Sishel');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Sllovaki');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Slloveni');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somali');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Spanjë');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Suedi');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Svazilandë');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Shqipëria');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Shtetet e Bashkuara të Amerikës');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Tajlandë');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Tajvan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzani');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Taxhikistan');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad e Tobago');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunisi');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Turqi');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukrainë');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruguaj');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikan');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Vendet e Ulëta');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezuelë');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Xhamajkë');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Xhibuti');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambi');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Zelanda e Re');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabve');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Zvicër');
