CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('US', 'Àdnà i Bilɔ̀ŋ bi Amerkà');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Àdnà i Bilɔ̀ŋ bi Arābìà');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Àdnà i Lɔ̂ŋ');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Àfgànìstâŋ');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Àfrǐkà Sɔ̀');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Àitì');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Àlbanìà');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Àlgerìà');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Àŋdɔ̂r');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Àŋgiyà');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Àŋgolà');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Àŋtigà ɓɔ Bàrbudà');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Àŋtîy ǹlɛ̀ndi');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Àrgàŋtinà');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Àrmenìà');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Àrubà');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Àzɛ̀rbajàŋ');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bàhamàs');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bàŋglàdɛ̂s');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bàraìn');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Bàrbadò');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Bèlarùs');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Bèlîs');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Bènɛ̂ŋ');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Bɛlgyùm');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bɛ̀rmudà');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Bìòn bi Falkland');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Bìòn bi Kaymàn');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Bìòn bi Kook');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Bìòn bi kɔnji bi Ŋgisì');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Bìòn bi kɔnji bi U.S.');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Bìòn bi Marcàl');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Bìòn bi Marìanà ŋ̀ɔmbɔk');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Bìòn bi Salōmò');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Bìòn bi Tûrks nì Kalkòs');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Bìtèk bi Ŋgisì i Tūyɛ Īndìà');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Bòdsùanà');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bòhnià Ɛrzègòvinà');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bòlivìà');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Bràsîl');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunei');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bùlgarìà');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Bùrkìnà Fasò');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Bùrundì');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Bùtân');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Câd');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Dànmârk');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dòmnîk');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Dòmnikà');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Ègîptò');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Èkwàtorìà');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Èrìtrěà');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Èstonìà');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Ètìopìà');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fiji');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Fìlìpîn');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Fìnlând');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gàbɔ̂ŋ');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gàmbià');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ganà');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Gèɔrgìà');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Gìlbràtâr');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Gìnê');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Gìne Bìsàô');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Gìne Èkwàtorìà');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Gìne ì Pàpu');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grènadà');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Grǐkyà');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Grǐnlànd');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Gùâm');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Gùyanà');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Gùyanà Pùlàsi');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Gwàdèlûp');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Gwàtèmalà');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Indìà');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indònèsià');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Ìrâk');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Ìrâŋ');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Ìrlând');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Ìslandìà');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Isràɛ̂l');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Ìtalìà');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jàmàikà');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Jamân');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Jìbutì');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Kabwɛ᷆r');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Kàlèdonìà Yɔ̀ndɔ');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kàmbodìà');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kàmɛ̀rûn');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kànadà');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Kàtâr');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kàzàkstâŋ');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenìà');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Kìlî');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Kinà');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Kiprò');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kìrgìzìstàŋ');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kìrìbatì');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kòŋgo');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Kòŋgo ìkɛŋi');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kòstà Rikà');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kòwêt');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kɔ̀lɔmbìà');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Kɔ̀mɔ̂r');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Kɔ̀re ì Ŋ̀ɔmbɔk');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Kɔ̀re ì Ŋ̀wɛ̀lmbɔk');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Kròasìà');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kubà');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Làdvià');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Làôs');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Lèbanòn');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesòtò');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Lìberìà');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libìà');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Ligstɛntàn');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lìtùanìà');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Lùgsàmbûr');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Màdàgàskâr');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Màlàwi');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Màldîf');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Màlɛ̀sìà');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Màli');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Maltà');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Màŋ mi Njɔ̂k');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Màrokò');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Màrtìnîk');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Màsèdonìà');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Màyɔ̂t');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mɛ̀gsîk');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mìkrònesìà');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldavìà');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Mònakò');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mòŋgolìà');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Mòrîs');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mòrìtanìà');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mòsàmbîk');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Mɔ̀ŋseràt');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myànmâr');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Nàmibìà');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nèpâl');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nerù');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nìgerìà');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Nìjɛ̂r');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nìkàragwà');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Nìuɛ̀');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Ǹlɛndi');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Nɔ̀rvegìà');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Nûmpubi Ɛlēnà');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Nûmpubi Kîts nì Nevìs');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Nûmpubi Lusì');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'Nûmpubi Māatìn');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Nûmpubi Petrò nì Mikèlôn');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Nûmpubi Vɛ̂ŋsâŋ nì grènàdîn');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Ŋ̀ɛm Afrīkà');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Òmân');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Òn i Nɔrfɔ̂k');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Òstralìà');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Òstrǐk');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Ɔ̀ŋduràs');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Ɔ̀ŋgriì');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pàkìstân');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Pàlaù');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Pàlɛ̀htinà Hyɔ̀ŋg nì Gazà');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Pànàma');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Pànya');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Pàràgwê');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Pèrû');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pìdkaìrn');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Pòlànd');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Pòlìnesìà Pùlàsi');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Pɔ̀rtò Rikò');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Pɔ̀tɔkì');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Pùlàsi / Fɛ̀lɛ̀nsi /');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Rèunyɔ̂ŋ');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Rùandà');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Rùmanìà');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Ruslànd');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Sàlvàdɔ̂r');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Sàmoà');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Sào Tòme ɓɔ Prɛ̀ŋcipè');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Sàudi Àrabìà');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Sènègâl');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Sèsɛ̂l');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Sɛ̀rbî nì Mɔ̀ntènegrò');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sièra Lèɔ̂n');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Sìlând Yɔ̀ndɔ');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Sìŋgàpûr');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Sirìà');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slòvakìà');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slòvanìà');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Sòmalìà');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Srìlaŋkà');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sùdâŋ');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Sùrinâm');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Sùwîs');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Swàzìlând');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Swedɛ̀n');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tàjìkìstaŋ');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tànzànià');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Taylànd');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Tàywân');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Tìmɔ̂r lìkòl');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Tògo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tòkèlaò');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tɔŋgà');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trìnidàd ɓɔ Tòbagò');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tùnisìà');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Tùrgmènìstân');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Tùrkây');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tùvàlù');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Ùgandà');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ùkrɛ̌n');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Ùrùgwêy');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Ùzbèkìstân');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vànùatù');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vàtìkâŋ');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Vènèzùelà');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vìɛ̀dnâm');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wàlîs nì Fùtunà');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yèmɛ̂n');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Yɔ̀rdanià');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zàmbià');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zìmbàbwê');
