CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AO', 'अङ्गोला');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'अजरबैजान');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'अन्टारतिका');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'अन्डोर्रा');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'अफ्गानिष्तान');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'अमेरिकी समोआ');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'अर्जेण्टिना');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'अलान्ड टापु');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'अल्जेरिया');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'अल्बानिया');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'अष्ट्रिया');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'अष्ट्रेलिया');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'आइज्ले अफ् म्यान');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'आइभोरी कोष्ट');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'आइरल्याण्ड');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'आइस्ल्याण्ड');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'आङ्गुइला');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'आरूबा');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'आर्मेनिया');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'इक्वडेर');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'इजिप्ट');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'इज्रायल');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'इटाली');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'इथोपिया');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'इन्डोनेशिया');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'इराक');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'इरान');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'इस्टोनिया');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'उज्बेकिस्तान');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'उत्तर कोरिया');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'उत्तरी मारिआना टापु');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'एन्टिगुआ र बारबुडा');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'एरित्रिया');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'एल् साल्भाडोर');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'ओमन');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'कटार');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'कम्बोडिया');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'काजाकस्थान');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'किरिबाटी');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'किर्गिस्थान');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'कुक टापु');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'कुवेत');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'केन्द्रीय अफ्रिकी गणतन्त्र');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'केन्या');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'केप भर्डे');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'केयमान टापु');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'कोकोस टापु');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'कोङ्गो - ब्राज्जाभिल्ले');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'कोङ्गो-किन्शासा');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'कोमोरोस');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'कोलोम्बिया');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'कोष्टारिका');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'क्यानाडा');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'क्यामेरून');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'क्युबा');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'क्रिष्टमस टापु');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'क्रोएशिया');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'गाम्विया');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'गावोन');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'गिनी');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'गिनी-बिसाउ');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'गुएर्नसे');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'गुयाना');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'गुवाम');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'ग्रिनल्याण्ड');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'ग्रिश');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'ग्रेनाडा');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'ग्वाटेमाला');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'ग्वाडेलुप');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'घाना');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'चाड');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'चिली');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'चीन');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'चेख गणतन्त्र');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'जमाइका');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'जर्मनी');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'जर्सी');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'जापान');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'जाम्बिया');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'जिब्राल्टार');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'जिम्बाबे');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'जोर्जिया');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'जोर्डन');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'टर्की');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'टुनिसिया');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'टोंगा');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'टोगो');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'डिजिबुटी');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'डेन्मार्क');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'डोमिनिकन गणतन्त्र');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'डोमिनिका');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'ताइवान');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'ताजिकिस्तान');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'तान्जानिया');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'तुभालु');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'तुर्क र काइकोस टापु');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'तुर्कमेनिस्तान');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'तोगो');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'त्रिनिडाड र तोबागो');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'थाइल्याण्ड');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'दक्षिण अफ्रिका');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'दक्षिण कोरिया');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'नयाँ कालेडोनिया');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'नर्वे');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'नाइजर');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'नाइजेरिया');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'नाउरू');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'नामिबिया');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'निकारागुवा');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'नियुइ');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'नेदरल्याण्ड्स');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'नेदरल्याण्ड्स एण्टिलिस');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'नेपाल');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'नोरफोल्क टापु');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'न्युजिल्याण्ड');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'पनामा');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'पपुआ न्यू गाइनिया');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'पलाउ');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'पश्चिमी साहारा');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'पाकिस्तान');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'पिटकाइर्न');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'पूर्वी टिमोर');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'पेरू');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'पोर्तुगल');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'पोल्याण्ड');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'प्यारागुये');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'प्यालेस्टनी भू-भाग');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'प्युर्टोरिको');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'फकल्याण्ड टापु');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'फारोर टापु');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'फिजी');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'फिन्ल्याण्ड');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'फिलिपिन्स');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'फ्रान्स');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'फ्रान्सेली गायना');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'फ्रान्सेली दक्षिणी क्षेत्र');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'फ्रान्सेली पोलिनेसिया');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'बङ्गलादेश');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'बर्किना फासो');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'बर्मुडा');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'बल्गेरिया');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'बहामास');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'बार्बाडोस');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'बाह्य ओसनिया');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'बाह्रेन');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'बुभेट टापु');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'बुरूण्डी');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'बेनिन');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'बेलायती भर्जिन टापु');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'बेलायती हिन्द महासागर क्षेत्र');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'बेलारूस');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'बेलिज');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'बेल्जियम');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'बोट्स्वाना');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'बोलिभिया');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'बोस्निया र हर्जगोभिनिया');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'ब्राजिल');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'ब्रुनाइ');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'भानुआतु');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'भारत');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'भिएतनाम');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'भुटान');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'भू-मध्यीय गिनी');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'भेटिकन');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'भेनेजुएला');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'मकावो चिनिँया स्वशासित क्षेत्र');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'मङ्गोलिया');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'मडागास्कर');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'मलेसिया');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'माइक्रोनेसिया');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'माउरिटस');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'माउरिटानिया');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'मायोट्ट');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'मार्टिनिक');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'मार्शल टापु');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'मालावी');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'माली');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'माल्टा');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'माल्डोभा');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'माल्दिभ्स');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'मेक्सिको');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'मोजाम्बिक');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'मोनाको');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'मोन्टसेर्राट');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'मोन्टेनेग्रो');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'मोरोक्को');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'म्याकेडोनिया');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'म्यान्मार');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'युक्रेन');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'युगाण्डा');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'युरूगुए');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'युरोपियन युनियन');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'येमेन');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'रवाण्डा');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'रियुनियन');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'रूस');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'रोमानिया');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'लक्जेमबर्ग');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'लाइबेरिया');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'लाओस');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'लाट्भिया');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'लिएखटेन्स्टाइन');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'लिथुअनिया');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'लिबिया');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'लेबनोन');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'लेसोथो');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'वालिस र फुटुना');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'श्रीलङ्का');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'सभाल्बार्ड र जान मायेन');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'संयुक्त अधिराज्य');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'संयुक्त अरब इमिराट्स');
INSERT INTO "country" ("id", "name") VALUES ('US', 'संयुक्त राज्य');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'संयुक्त राज्य अल्प बाह्य टापु');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'संयुक्त राज्य भर्जिन टापु');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'सर्बिया');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'साइप्रस');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'साउदी अरब');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'साओ टोमे र प्रिन्सिप');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'सान् मारिनो');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'सामोआ');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'सिएर्रा लिओन');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'सिङ्गापुर');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'सिरिया');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'सुडान');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'सुरिनेम');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'सेचेलेस');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'सेनेगाल');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'सेन्ट किट्स र नेभिस');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'सेन्ट पिर्रे र मिक्केलोन');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'सेन्ट बार्थालेमी');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'सेन्ट भिन्सेन्ट र ग्रेनाडिन्स');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'सेन्ट मार्टिन');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'सेन्ट लुसिया');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'सेन्ट हेलेना');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'सोमालिया');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'सोलोमोन टापु');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'स्पेन');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'स्लोभाकिया');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'स्लोभेनिया');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'स्वाजिल्याण्ड');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'स्विजरल्याण्ड');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'स्विडेन');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'हङकङ चिनिँया समाजवादी स्वायत्त क्षेत्र');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'हङ्गेरी');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'हन्डुरास');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'हर्ड टापु र म्याकडोनाल्ड टापु');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'हैटी');
