CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AT', 'ଅଷ୍ଟ୍ରିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'ଅଷ୍ଟ୍ରେଲିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'ଆଇବରୀ କୋଷ୍ଟ');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'ଆଇଲ୍ ଅଫ୍ ମୈନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'ଆଇସଲ୍ୟାଣ୍ଡ');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'ଆଉଟଲେଇଂ ଓସେନିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'ଆଙ୍ଗୁଇଲ୍ଲା');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'ଆଙ୍ଗୋଲା');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'ଆଜେରବାଇଜାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'ଆଣ୍ଟିଗୁଆ ଏବଂ ବାରବୁଦା');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'ଆଣ୍ଡୋରା');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'ଆଫାଗାନିସ୍ତାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'ଆମେରିକାନ୍ ସାମୋଆ');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'ଆୟରଲ୍ୟାଣ୍ଡ');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'ଆରୁବା');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'ଆର୍ଜେଣ୍ଟିନା');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'ଆର୍ଣ୍ଟକଟିକା');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'ଆର୍ମେନିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'ଆଲଜେରିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'ଆଲବାନିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'ଆଲାଣ୍ଡ ଆଇସଲ୍ୟାଣ୍ଡ');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'ଇକ୍ବାଟେରିଆଲ୍ ଗୁଇନିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'ଇକ୍ୱାଡୋର୍');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'ଇଜିପ୍ଟ');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'ଇଟାଲୀ');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'ଇଣ୍ଡୋନେସିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'ଇଥିଓପିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'ଇରାକ୍');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'ଇରାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'ଇରିଟ୍ରିୟା');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'ଇସ୍ରାଏଲ୍');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'ଉଗାଣ୍ଡା');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'ଉଜବେକିସ୍ଥାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'ଉତ୍ତର କୋରିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'ଉତ୍ତର ମାରିଆନା ଦ୍ବୀପପୁଞ୍ଜ');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'ଉରୁଗୁଏ');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'ଏଲ୍ ସାଲଭାଡୋର୍');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'ଏସ୍ତୋନିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'ଓମାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'କଙ୍ଗୋ-କିନସାସା');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'କଙ୍ଗୋ-ବ୍ରାଜିଭିଲ୍ଲେ');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'କତାର୍');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'କାଜାକାସ୍ଥାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'କାନାଡା');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'କାମେରୁନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'କାମୋରସ୍');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'କାମ୍ବୋଡିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'କିରିବାଟୀ');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'କିର୍ଗିଜିସ୍ଥାନ');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'କୁଏତ୍');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'କୁକ୍ ଆଇସଲ୍ୟାଣ୍ଡ');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'କେନିୟା');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'କେପ୍ ଭର୍ଦେ');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'କେମ୍ୟାନ୍ ଦ୍ବୀପପୁଞ୍ଜ');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'କୋକୋସ୍ ଆଇସଲ୍ୟାଣ୍ଡ');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'କୋଲମ୍ବିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'କୋଷ୍ଟା ରିକା');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'କ୍ରୋଆଟିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'କ୍ୱିବା');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'ଖ୍ରୀଷ୍ଟମାସ ଆଇଲ୍ୟାଣ୍ଡ');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'ଗାବୋନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'ଗାମ୍ବିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'ଗୁଆମ୍');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'ଗୁଇନା');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'ଗୁଇନିଆ-ବିସାଉ');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'ଗୁଏତମାଲା');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'ଗୁଏନେଆ');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'ଗୁଏରନେସି');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'ଗୌଡେଲୌପେ');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'ଗ୍ରୀନଲ୍ୟାଣ୍ଡ');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'ଗ୍ରୀସ୍');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'ଗ୍ରେନାଡା');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'ଘାନା');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'ଚାଦ୍');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'ଚିନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'ଚିଲ୍ଲୀ');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'ଚେକ୍ ସାଧାରଣତନ୍ତ୍ର');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'ଜର୍ଜିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'ଜର୍ମାନୀ');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'ଜର୍ସି');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'ଜାପାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'ଜାମାଇକା');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'ଜାମ୍ବିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'ଜିବ୍ରାଲ୍ଟର୍');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'ଜିମ୍ବାୱେ');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'ଜୋର୍ଡାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'ଟୁଭାଲୁ');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'ଟୋକେଲାଉ');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'ଟୋଗୋ');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'ଟୋଙ୍ଗା');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'ଡିବୌଟି');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'ଡେନମାର୍କ');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'ଡୋମିନକାନ୍ ପ୍ରଜାତନ୍ତ୍ର');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'ଡୋମିନାକା');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'ତାଇୱାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'ତାଜିକିସ୍ଥାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'ତାଞ୍ଜାନିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'ତୁନିସିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'ତୁର୍କମେନିସ୍ତାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'ତୁର୍କସ୍ ଏବଂ ସାଇକସ୍ ଦ୍ବୀପପୁଞ୍ଜ');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'ତୁର୍କୀ');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'ତ୍ରିନିଦାଦ୍ ଏବଂ ଟୋବାଗୋ');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'ଥାଇଲାଣ୍ଡ');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'ଦକ୍ଷିଣ ଆଫ୍ରିକା');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'ଦକ୍ଷିଣ କୋରିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'ଦକ୍ଷିଣ ଜର୍ଜିଆ ଏବଂ ଦକ୍ଷିଣ ସାଣ୍ଡୱିଚ୍ ଦ୍ବୀପପୁଞ୍ଜ');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'ନରଫ୍ଲକ୍ ଦ୍ବୀପ');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'ନରୱେ');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'ନାଇଜର୍');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'ନାଇଜେରିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'ନାଉରୁ');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'ନାମ୍ବିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'ନିଉ');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'ନିକାରାଗୁଆ');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'ନୂତନ କାଲେଡୋନିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'ନେଦରଲ୍ୟାଣ୍ଡ');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'ନେଦରଲ୍ୟାଣ୍ଡସ୍ ଆଣ୍ଟିଲିଜ୍');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'ନେପାଳ');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'ନ୍ୟୁଜିଲାଣ୍ଡ');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'ପପୁଆ ନ୍ୟୁ ଗୁଏନିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'ପର୍ତ୍ତୁଗାଲ୍');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'ପଶ୍ଚିମ ସାହାରା');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'ପାକିସ୍ତାନ');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'ପାନାମା');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'ପାରାଗୁଏ');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'ପାଲାଉ');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'ପାଲେସ୍ତେନିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'ପିଟକାଇରିନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'ପୁଏର୍ତ୍ତୋ ରିକୋ');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'ପୁର୍ବ ତିମୋର୍');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'ପେରୁ');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'ପୋଲାଣ୍ଡ');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'ଫରାସୀ ଦକ୍ଷିଣ କ୍ଷେତ୍ର');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'ଫଲ୍କଲ୍ୟାଣ୍ଡ ଦ୍ବୀପପୁଞ୍ଜ');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'ଫାରୋଇ ଦ୍ବୀପପୁଞ୍ଜ');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'ଫିଜି');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'ଫିନଲ୍ୟାଣ୍ଡ');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'ଫିଲିପାଇନସ୍');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'ଫ୍ରାନ୍ସ');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'ଫ୍ରେଞ୍ଚ ଗୁଇନା');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'ଫ୍ରେଞ୍ଚ ପଲିନେସିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'ବରମୁଡା');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'ବାଙ୍ଗଲାଦେଶ୍');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'ବାରବାଡୋସ୍');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'ବାହାମାସ୍');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'ବାହାରିନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'ବୁରୁନ୍ଦି');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'ବୁର୍କିନୋ ଫାସୋ');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'ବୁଲଗେରିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'ବେନିନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'ବେଲଜିୟମ୍');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'ବେଲାରୁଷ୍');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'ବେଲିଜ୍');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'ବୋଟସ୍ବାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'ବୋଲଭିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'ବୋସନିଆ ଏବଂ ହର୍ଜଗୋଭିନା');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'ବୌଭେଟ୍ ଆଇସଲ୍ୟାଣ୍ଡ');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'ବ୍ରାଜିଲ୍');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'ବ୍ରିଟିଶ୍ ଭର୍ଜିନ୍ ଦ୍ବୀପପୁଞ୍ଜ');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'ବ୍ରିଟିଶ୍ ଭାରତୀୟ ସାମୁଦ୍ରିକ କ୍ଷେତ୍ର');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'ବ୍ରିଟେନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'ବ୍ରୁନେଇ');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'ଭାଟିକାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'ଭାନୁଆତୁ');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'ଭାରତ');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'ଭିଏତନାମ୍');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'ଭୁଟାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'ଭେନଜୁଏଲା');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'ମଙ୍ଗୋଲିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'ମଣ୍ଟେଗ୍ରୋ');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'ମଣ୍ଟେସେରାଟ୍');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'ମଧ୍ୟ ଆଫ୍ରିକୀୟ ଗଣତନ୍ତ୍ର');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'ମାଇକ୍ରୋନେସିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'ମାଉରିଟାନିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'ମାକାଉ SAR ଚିନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'ମାଡାଗାସ୍କର୍');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'ମାୟୋଟେ');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'ମାର୍ଟିନିକ୍ୟୁ');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'ମାର୍ଶଲ୍ ଦ୍ବୀପପୁଞ୍ଜ');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'ମାଲଡୋଭା');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'ମାଲୱି');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'ମାଲେସିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'ମାଲ୍ଟା');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'ମାଳଦ୍ବୀପ');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'ମାଳୀ');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'ମାସେଡୋନିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'ମିୟାମାର୍');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'ମେକ୍ସିକୋ');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'ମୋଜାମ୍ବିକ୍ୟୁ');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'ମୋନାକୋ');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'ମୋରୋକ୍କୋ');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'ମୌରିସସ୍');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'ୟୁଏସ୍ ଭର୍ଜିନ୍ ଦ୍ବୀପପୁଞ୍ଜ');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'ଯୁକ୍ତ ରାଷ୍ଟ୍ର ଆମେରିକା');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'ୟୁକ୍ରାଇନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'ୟୁନାଇଟେଡ୍ ଷ୍ଟେଟସ୍ ମାଇନର୍ ଆଉଟଲେଇଂ ଦ୍ବୀପପୁଞ୍ଜ');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'ୟୁରୋପିଆନ୍ ୟୁନିଅନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'ୟେମେନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'ରାୱାଣ୍ଡା');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'ରିୟୁନିଅନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'ରୁଷିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'ରୋମାନିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'ଲକ୍ସେମବର୍ଗ');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'ଲାଓସ୍');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'ଲାଟଭିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'ଲିଚେସ୍ତିଆନାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'ଲିଥାଆନିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'ଲିବିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'ଲିବେରିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'ଲେବାନନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'ଲେସୋଥୋ');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'ୱାଲିସ୍ ଏବଂ ଫୁତୁନା');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'ଶ୍ରୀଲଙ୍କା');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'ସଂଯୁକ୍ତ ଆରବ ଏମିରେଟସ୍');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'ସର୍ବିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'ସର୍ବିଆ ଏବଂ ମଣ୍ଟେନଗ୍ରୋ');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'ସାଇପ୍ରସ୍');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'ସାଉଦି ଆରବିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'ସାଓ ଟୋମେ ଏବଂ ପ୍ରିନସିପି');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'ସାନ୍ ମାରିନୋ');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'ସାମୋଆ');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'ସାଲ୍ଭାର୍ଡ ଏବଂ ଜାନ୍ ମାୟୋନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'ସିଓରା ଲିଓନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'ସିଙ୍ଗାପୁର୍');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'ସିରିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'ସୁଦାନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'ସୁରିନାମ');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'ସେଚେଲସ୍');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'ସେଣ୍ଟ କିଟସ୍ ଏଣ୍ଡ ନେଭିସ୍');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'ସେଣ୍ଟ ପିଏରେ ଏବଂ ମିକ୍ବାଲୋନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'ସେଣ୍ଟ ବାର୍ଥେଲେମି');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'ସେଣ୍ଟ ଭିନସେଣ୍ଟ ଏବଂ ଦି ଗ୍ରେନାଡିସ୍');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'ସେଣ୍ଟ ମାର୍ଟିନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'ସେଣ୍ଟ ଲୁସିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'ସେଣ୍ଟ ହେଲେନା');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'ସେନେଗାଲ୍');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'ସୋମାଲିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'ସୋଲୋମନ୍ ଦ୍ବୀପପୁଞ୍ଜ');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'ସ୍ପେନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'ସ୍ବାଜିଲାଣ୍ଡ');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'ସ୍ବିଜରଲ୍ୟାଣ୍ଡ');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'ସ୍ଲୋଭାକିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'ସ୍ଲୋଭେନିଆ');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'ସ୍ୱେଡେନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'ହଂକଂ ବିଶେଷ ପ୍ରଶାସନିକ କ୍ଷେତ୍ର ଚୀନ୍');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'ହଙ୍ଗେରୀ');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'ହାଇତି');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'ହାର୍ଡ ଦ୍ବୀପପୁଞ୍ଜ ଏବଂ ମ୍ୟାକଡୋନାଲ୍ ଦ୍ବୀପପୁଞ୍ଜ');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'ହୋଣ୍ଡାରୁସ୍');
