CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'اٹلی');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'ارجنٹینا');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'اردن');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'اروبا');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'اریٹیریا');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'ازبکستان');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'استوائی گیانا');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'اسٹونیا');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'اسرائیل');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'اسکینسیئن آئلینڈ');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'افغانستان');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'ال سلواڈور');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'البانیہ');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'الجیریا');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'امریکہ سے باہر کے چھوٹے جزائز');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'امریکی ساموآ');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'امریکی ورجن آئلینڈز');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'انٹارکٹیکا');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'انٹیگوا اور باربودا');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'انڈورا');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'انڈونیشیا');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'انگولا');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'انگوئیلا');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'ایتھوپیا');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'ایران');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'ایکواڈور');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'آذربائجان');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'آرمینیا');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'آسٹریا');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'آسٹریلیا');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'آلینڈ آئلینڈز');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'آئرلینڈ');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'آئس لینڈ');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'آئل آف مین');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'باربادوس');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'بحرین');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'برازیلی');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'برٹش ورجن آئلینڈز');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'برطانوی ہندوستانی سمندری خطہ');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'برکینا فاسو');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'برمودا');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'برونڈی');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'برونئی');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'بلغاریہ');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'بنگلہ دیش');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'بوتسوانا');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'بوسنیا اور ہرزیگووینا');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'بولیویا');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'بؤویٹ آئلینڈ');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'بہاماس');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'بیرونی اوشیانیا');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'بیلاروس');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'بیلائز');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'بیلجیم');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'بینن');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'بھارت');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'بھوٹان');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'پاپوآ نیو گنی');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'پاکستان');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'پٹکائرن جزائر');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'پرتگال');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'پلاؤ');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'پنامہ');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'پولینڈ');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'پیراگوئے');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'پیرو');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'پیورٹو ریکو');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'تاجکستان');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'تائیوان');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'ترکس اور کیکاؤس جزائر');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'ترکمانستان');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'ترکی');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'ترینیداد اور ٹوباگو');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'تنزانیہ');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'تیمور لیسٹ');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'تیونیسیا');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'تھائی لینڈ');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'ٹرسٹن ڈا کیونہا');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'ٹوکیلاؤ');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'ٹوگو');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'ٹونگا');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'ٹووالو');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'جاپان');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'جارجیا');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'جبل الطارق');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'جبوتی');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'جرسی');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'جرمنی');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'جمائیکا');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'جنوبی افریقہ');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'جنوبی جارجیا اور جنوبی سینڈوچ جزائر');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'جنوبی کوریا');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'چاڈ');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'چلی');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'چیک جمہوریہ');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'چین');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'ڈائجو گارسیا');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'ڈنمارک');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'ڈومنیکا');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'ڈومنیکن جمہوریہ');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'روانڈا');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'روسی');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'رومانیا');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'ری یونین');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'ریاستہائے متحدہ');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'زامبیا');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'زمبابوے');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'ساموآ');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'سان مارینو');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'ساؤ ٹوم اور پرنسپے');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'سربیا');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'سری لنکا');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'سشلیز');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'سعودی عرب');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'سلطنت متحدہ');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'سلوواکیہ');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'سلووینیا');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'سنگاپور');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'سوازی لینڈ');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'سوالبرڈ اور جان ماین');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'سوڈان');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'سورینام');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'سولومن آئلینڈز');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'سوئٹزر لینڈ');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'سویڈن');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'سینٹ برتھلیمی');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'سینٹ پیئر اور میکلیئون');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'سینٹ کٹس اور نیویس');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'سینٹ لوسیا');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'سینٹ مارٹن');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'سینٹ ونسنٹ اور گرینیڈائنز');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'سینٹ ہیلینا');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'سینیگل');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'سیئر لیون');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'سیئوٹا اور میلیلا');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'شام');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'شمالی کوریا');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'شمالی ماریانا آئلینڈز');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'صومالیہ');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'عراق');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'عمان');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'غرناطہ');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'فاکلینڈ آئلینڈز');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'فجی');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'فرانس');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'فرانسیسی پولینیشیا');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'فرانسیسی جنوبی خطے');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'فروئی آئلینڈز');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'فرینچ گیانا');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'فلپائنی');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'فلسطینی خطے');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'فن لینڈ');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'قبرص');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'قزاخستان');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'قطر');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'کانگو - برازاویلے');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'کانگو - کنشاسا');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'کرسمس آئلینڈ');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'کرغزستان');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'کروشیا');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'کریباتی');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'کک آئلینڈز');
INSERT INTO `country` (`id`, `name`) VALUES ('CP', 'کلپّرٹن آئلینڈ');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'کمبوڈیا');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'کوٹ ڈی آئیوری');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'کوسٹا ریکا');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'کوکوس [کیلنگ] جزائر');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'کولمبیا');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'کوموروس');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'کویت');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'کیپ ورڈی');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'کیمرون');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'کیمین آئلینڈز');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'کینری آئلینڈز');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'کینیا');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'کینیڈا');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'کیوبا');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'گامبیا');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'گرین لینڈ');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'گنی');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'گنی بساؤ');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'گواٹے مالا');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'گواڈیلوپ');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'گوآم');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'گوئرنسی');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'گیانا');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'گیبون');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'گھانا');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'لاؤس');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'لائبیریا');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'لبنان');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'لتھوانیا');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'لٹویا');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'لگژمبرگ');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'لیبیا');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'لیسوتھو');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'لیشٹنسٹائن');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'مارٹینک');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'مارشل آئلینڈز');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'ماریشس');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'مالٹا');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'مالدووا');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'مالدیو');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'مالی');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'مائکرونیشیا');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'مایوٹ');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'متحدہ عرب امارات');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'مڈغاسکر');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'مراقش');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'مصر');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'مغربی صحارا');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'مقدونیہ');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'مکاؤ SAR چین');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'ملاوی');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'ملیشیا');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'منگولیا');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'موریطانیہ');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'موزمبیق');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'موناکو');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'مونٹسیراٹ');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'مونٹے نیگرو');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'میانمار [برما]');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'میکسیکو');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'نار فاک آئلینڈ');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'ناروے');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'نامیبیا');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'نائجر');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'نائجیریا');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'نکاراگووا');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'نؤرو');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'نیپال');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'نیدر لینڈز');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'نیدرلینڈز انٹیلیز');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'نیو کلیڈونیا');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'نیوزی ینڈ');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'نیئو');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'واٹیکن سٹی');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'وسط افریقی جمہوریہ');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'ویتنام');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'ویلیز اور فیوٹیونا');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'وینزوئیلا');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'وینوآٹو');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'ہانگ کانگ SAR چین');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'ہسپانیہ');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'ہنگری');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'ہونڈاروس');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'ہیتی');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'ہیئرڈ آئلینڈ اور میکڈونالڈ آئلینڈز');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'یمن');
INSERT INTO `country` (`id`, `name`) VALUES ('EU', 'یوروپی یونین');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'یوروگوئے');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'یوکرین');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'یوگانڈا');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'یونان');
