CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AE', 'Emiratos Árabes Unidos');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anguilha');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Arménia');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Antárctica');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Ilhas Alanda');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azerbeijão');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladeche');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burkina-Faso');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahrein');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benim');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Baamas');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botswana');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Bielorrússia');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Ilhas Cocos');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'República Democrática do Congo');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Congo-Brazzaville');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Ilha do Natal');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'República Checa');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Estónia');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Egipto');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Sara Ocidental');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Ilhas Falkland ou Malvinas');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Estados Federados da Micronésia');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Ilhas Faroé');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Gronelândia');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Guiné-Bissau');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Hong Kong - Região Administrativa Especial da China');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Irão');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Quénia');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Quirguizistão');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Saint Kitts e Nevis');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Cuaite');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Ilhas Caimão');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Cazaquistão');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laos, República Popular Democrática do');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Letónia');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Mónaco');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldávia, República da');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagáscar');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Macedónia, República da');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Macau - Região Administrativa Especial da China');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Ilhas Mariana do Norte');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Monserrate');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Maurícias');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malaui');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Nova Caledónia');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Ilha Norfolque');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Países Baixos');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papua Nova Guiné');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Polónia');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Território Palestiniano');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Qatar');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Roménia');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Seicheles');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapura');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Eslovénia');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Esvalbarda e Jan Mayen');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'São Marino');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Ilhas Turcas e Caicos');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tajiquistão');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Toquelau');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turquemenistão');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trindade e Tobago');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'Ilhas Minor Outlying (E.U.A)');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Usbequistão');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Ilhas Virgin E.U.A.');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vietname');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Iémen');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabwe');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andorra');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afeganistão');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antígua e Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albânia');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Antilhas Holandesas');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Argentina');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Samoa Americana');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Áustria');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Austrália');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bósnia-Herzegovina');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbados');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Bélgica');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulgária');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'São Bartolomeu');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermudas');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brunei');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolívia');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brasil');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Butão');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Ilha Bouvet');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belize');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Canadá');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'República Centro-Africana');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Suíça');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Costa do Marfim');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Ilhas Cook');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Chile');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'República dos Camarões');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'China');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Colômbia');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Costa Rica');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Sérvia e Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Cuba');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Cabo Verde');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Chipre');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Alemanha');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Djibuti');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Dinamarca');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominica');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'República Dominicana');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Argélia');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Equador');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritreia');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Espanha');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Etiópia');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finlândia');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fiji');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'França');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabão');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Reino Unido');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Granada');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Geórgia');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Guiana Francesa');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Guernsey');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Gana');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Gibraltar');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gâmbia');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Guiné');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadalupe');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Guiné Equatorial');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Grécia');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'Geórgia do Sul e Ilhas Sandwich do Sul');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatemala');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guiana');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Ilha Heard e Ilhas McDonald');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduras');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Croácia');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haiti');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Hungria');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indonésia');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Irlanda');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Israel');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Ilha de Man');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Índia');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Território Britânico do Oceano Índico');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Iraque');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Islândia');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Itália');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Jersey');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamaica');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jordânia');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japão');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Camboja');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Quiribati');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Comores');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Coreia do Norte');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Coreia do Sul');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Líbano');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Santa Lúcia');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Liechtenstein');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Libéria');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesoto');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Lituânia');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luxemburgo');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Líbia');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Marrocos');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'São Martinho');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Ilhas Marshall');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Mianmar');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongólia');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martinica');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mauritânia');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldivas');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'México');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malásia');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Moçambique');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namíbia');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Níger');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nigéria');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nicarágua');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Noruega');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepal');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Nova Zelândia');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Omã');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panamá');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Peru');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Polinésia Francesa');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filipinas');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Paquistão');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Saint Pierre e Miquelon');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitcairn');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Porto Rico');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portugal');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguai');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Reunião');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Sérvia');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Rússia');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ruanda');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Arábia Saudita');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Ilhas Salomão');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudão');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Suécia');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Santa Helena');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Eslováquia');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Serra Leoa');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegal');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somália');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Suriname');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'São Tomé e Príncipe');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'El Salvador');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Síria');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Suazilândia');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Chade');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Territórios Franceses do Sul');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Tailândia');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Timor Leste');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunísia');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Turquia');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taiwan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzânia');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ucrânia');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uganda');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Estados Unidos');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruguai');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vaticano');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'São Vicente e Granadinas');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezuela');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Ilhas Virgens Britânicas');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis e Futuna');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samoa');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayotte');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'África do Sul');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zâmbia');
INSERT INTO "country" ("id", "name") VALUES ('ZZ', 'Região desconhecida ou inválida');
