CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afghanistan');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albanien');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Algeriet');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Amerikansk Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andorra');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguilla');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Antarktis');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigua og Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Argentina');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armenien');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Ascensionøen');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Aserbajdsjan');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Australien');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamas');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahrain');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladesh');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbados');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Belgien');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belize');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benin');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermuda');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Bhutan');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolivia');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnien-Hercegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswana');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Bouvetø');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brasilien');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgarien');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Cambodja');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Cameroun');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Canada');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Caymanøerne');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Centralafrikanske Republik');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Ceuta og Melilla');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Chile');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'Clippertonøen');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Cocosøerne');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Colombia');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Comorerne');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Congo – Brazzaville');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Congo-Kinshasa');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Cook-øerne');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Costa Rica');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Cuba');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Cypern');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Danmark');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'De amerikanske jomfruøer');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'De britiske jomfruøer');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'De palæstinensiske områder');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Den Dominikanske Republik');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Det Britiske Territorium i Det Indiske Ocean');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Diego Garcia');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Djibouti');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominica');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ecuador');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Egypten');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'El Salvador');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Elfenbenskysten');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritrea');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estland');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiopien');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Falklandsøerne');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fiji-øerne');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filippinerne');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finland');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Forenede Arabiske Emirater');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Frankrig');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Fransk Guyana');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Fransk Polynesien');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Franske Besiddelser i Det Sydlige Indiske Ocean');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Færøerne');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabon');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambia');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Georgien');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ghana');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Gibraltar');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grenada');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Grækenland');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Grønland');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Guadeloupe');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guam');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Guatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Guernsey');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyana');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haiti');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'Heard- og McDonald-øerne');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Holland');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Hollandske Antiller');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Honduras');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Hviderusland');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Indien');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonesien');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Irak');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Iran');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Irland');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Island');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Isle of Man');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Israel');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Italien');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jamaica');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Japan');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Jersey');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Jordan');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Juleøen');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Kanariske øer');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Kap Verde');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kasakhstan');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenya');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Kina');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kirgisistan');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Kroatien');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuwait');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laos');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesotho');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Letland');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Libanon');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberia');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libyen');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Liechtenstein');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Litauen');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Luxembourg');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagaskar');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Makedonien');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawi');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malaysia');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maldiverne');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Marokko');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Marshalløerne');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martinique');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mauretanien');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Mauritius');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayotte');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mexico');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikronesiens Forenede Stater');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Mindre amerikanske oversøiske øer');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monaco');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongoliet');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Montenegro');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montserrat');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambique');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myanmar');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibia');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nauru');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepal');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'New Zealand');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nicaragua');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Niger');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nigeria');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niue');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Nordkorea');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Nordmarianerne');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Norfolk Island');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norge');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Ny Caledonien');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Oman');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistan');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papua Ny Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguay');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peru');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitcairn');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Polen');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portugal');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Puerto Rico');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Qatar');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Republikken Moldova');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Reunion');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Rumænien');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rusland');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Rwanda');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Saint Barthélemy');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Saint Kitts og Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Saint Lucia');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Saint Martin');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Saint Pierre og Miquelon');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Salomonøerne');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marino');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Sao Tome og Principe');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'SAR Hongkong');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'SAR Macao');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Saudi-Arabien');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Schweiz');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegal');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Serbien');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Serbien og Montenegro');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seychellerne');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sierra Leone');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapore');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovakiet');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slovenien');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somalia');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'South Georgia og De Sydlige Sandwichøer');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Spanien');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'St. Helena');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'St. Vincent og Grenadinerne');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Storbritannien');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudan');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinam');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Svalbard og Jan Mayen');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Sverige');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Swaziland');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Sydafrika');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Sydkorea');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Syrien');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tadsjikistan');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwan');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzania');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Tchad');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Thailand');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timor-Leste');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Tjekkiet');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidad og Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunesien');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turkmenistan');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Turks- og Caicosøerne');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Tyrkiet');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Tyskland');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukraine');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Ungarn');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruguay');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'USA');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Usbekistan');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatikanstaten');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuela');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Vestsahara');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietnam');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wallis og Futunaøerne');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'Ydre Oceanien');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yemen');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambia');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabwe');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Ækvatorialguinea');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Østrig');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Åland');
