CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afghanistan');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Afrika Atsimo');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albania');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Alemaina');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Alzeria');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andorra');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Angletera');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Anguilla');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antiga sy Barboda');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Aostralia');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Aotrisy');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Arabia saodita');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armenia');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Arobà');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Arzantina');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azerbaidjan');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamas');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrain');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladesy');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbady');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Belarosy');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belzika');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benin');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermioda');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Bhotana');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Biolgaria');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolivia');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Borkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Borondi');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosnia sy Herzegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botsoana');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brezila');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Côte d’Ivoire');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Danmarka');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Djiboti');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominika');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Ejypta');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ekoatera');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'El Salvador');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Emirà Arabo mitambatra');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritrea');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Espaina');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estonia');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Etazonia');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Ethiopia');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Faridranomasina indiana britanika');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fidji');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filipina');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finlandy');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Firenen\'i Vatikana');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Frantsa');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabon');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ghana');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Giné-Bisao');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Ginea');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Goadelopy');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Goatemalà');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenady');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Gresy');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Groenland');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guam');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Guinea Ekoatera');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Guyana frantsay');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Holanda');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Hondiorasy');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Hongria');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonezia');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Indy');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Irak');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iran');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irlandy');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Islandy');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Israely');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italia');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaïka');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japana');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordania');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambôdja');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kamerona');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Katar');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazakhstan');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kiobà');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kiordistan');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kôeity');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kôlômbia');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Kômaoro');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kôngô');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Korea Atsimo');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Korea Avaratra');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Kosta Rikà');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Kroasia');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laôs');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Larenion');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Letonia');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libana');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberia');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libya');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Lioksamboro');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Listenstein');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Litoania');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagasikara');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Makedonia');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malaizia');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malaoì');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldiva');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Maorisy');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Maoritania');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Marôka');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinika');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayôty');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Meksika');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikrônezia');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Môldavia');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Mônakô');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Môngôlia');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambika');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Myanmar');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibia');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Naorò');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepala');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Niger');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikaragoà');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Nioé');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nizeria');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Nôrvezy');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Nosy britanika virijiny');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Nosy Cap-Vert');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Nosy Falkand');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Nosy Kayman');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Nosy Kook');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Nosy Mariana Atsinanana');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Nosy Marshall');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Nosy Norfolk');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Nosy Salomona');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Nosy Turks sy Caïques');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Nosy Virijiny Etazonia');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Nouvelle-Calédonie');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Nouvelle-Zélande');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Oganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Okraina');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Orogoay');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Ozbekistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palao');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Palestina');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papouasie-Nouvelle-Guinée');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paragoay');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peroa');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitkairn');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Pôlôna');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Polynezia frantsay');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Pôrtiogala');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Pôrtô Rikô');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Repoblika Dominikanina');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Repoblika Ivon\'Afrika');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Repoblikan\'i Kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Repoblikan\'i Tseky');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Roanda');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romania');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Rosia');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Saint-Christophe-et-Niévès');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'Saint-Marin');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Saint-Pierre-et-Miquelon');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Saint-Vincent-et-les Grenadines');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Sainte-Hélène');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Sainte-Lucie');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Samoa amerikanina');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'São Tomé-et-Príncipe');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegal');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Serbia sy Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seyshela');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Shili');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sierra Leone');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Sina');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singaporo');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Slovakia');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Slovenia');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Soazilandy');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sodan');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Soedy');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Soisa');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somalia');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Sorinam');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Sypra');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Syria');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taioana');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tajikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzania');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Thailandy');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Timor Atsinanana');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelao');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tongà');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tonizia');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Torkia');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Torkmenistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tovalò');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad sy Tobagô');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Tsady');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanoatò');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezoelà');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vietnam');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Vondronosy karaiba holandey');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis sy Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Yemen');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Zeorzia');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Zibraltara');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbaboe');
