CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andóra');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Ʉtemi wa Kɨaráabu');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afuganisitáani');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigúua na Baribúuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Anguíila');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Alubánia');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Ariménia');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Antili ya Ʉholáanzi');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angóola');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Ajentíina');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Samóoa ya Amerɨ́ka');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Áusitiria');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Ausiteréelia');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Arúuba');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azabajáani');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bósinia');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Babadóosi');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangaladéeshi');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Ʉbeligíiji');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Bukinafáaso');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Buligaría');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Baharéeni');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burúundi');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Beníini');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Berimúuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Burunéei');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolívia');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brasíili');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Baháama');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Butáani');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botiswáana');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Belarúusi');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belíise');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kánada');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Jamuhúuri ya Kɨdemokurasía ya Kóongo');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Juhúuri ya Afɨrɨka ya katɨ katɨ');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kóongo');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Uswíisi');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Ivori Kositi');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Visíiwa vya Kúuku');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Chíile');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kamerúuni');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Chíina');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolómbia');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Kósita Rɨ́ɨka');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Sebíia na Montégiro');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kyúuba');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Kepuvéede');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Kupuróosi');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Jamuhúuri ya Chéeki');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Ʉjerumáani');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Jibúuti');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Denimaki');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Domínɨka');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Jamuhúuri ya Dominɨka');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Alijéria');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Íkwado');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estonía');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Mísiri');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eriterea');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Hisipánia');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Ʉhabéeshi');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Ufíini');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fíiji');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Visíiwa vya Fakulandi');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikironésia');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Ʉfaráansa');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabóoni');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Ʉɨngeréesa');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Girenáada');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Jójia');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Gwiyáana yʉ Ʉfaráansa');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Gáana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Jiburálita');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Giriniláandi');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gámbia');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Gíine');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Gwadelúupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Gíine Ikwéeta');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Ugiríki');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Gwatemáala');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Gwani');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Gíine Bisáau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyáana');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduráasi');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Koréshia');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haíiti');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Hungária');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonésia');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Ayaláandi');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Isiraéeli');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Índia');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Ɨsɨ yʉ Ʉɨngeréesa irivii ra Híindi');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Iráaki');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Ʉajéemi');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Aisiláandi');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Itália');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamáika');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jódani');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japáani');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kéenya');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirigisitáani');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambódia');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribáati');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Komóoro');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Mʉtakatíifu kitisi na Nevíisi');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Koréa yʉ ʉtʉrʉko');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Koréa ya Saame');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kʉwáiti');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Visíiwa vya Kayimani');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazakasitáani');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laóosi');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Lebanóoni');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Mʉtakatíifu Lusíia');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Lishentéeni');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Siriláanka');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liibéria');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesóoto');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Lisuánia');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Lasembáagi');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Lativia');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Líbia');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Moróoko');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monáako');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Molidóova');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Bukíini');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Visíiwa vya Marisháali');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Masedónia');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Máali');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Miáama');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongólia');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Visiwa vya Mariana vya Kaskazini');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Maritiníiki');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Moritánia');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Monteráati');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Málita');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Moríisi');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Modíivu');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Maláawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Mekisiko');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Maleísia');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Musumbíiji');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namíbia');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Kaledónia Ifya');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Níija');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Kisíiwa cha Nofifóoki');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Niijéria');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikarágʉa');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Ʉholáanzi');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norwe');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepáali');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Naúuru');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niúue');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Nyuzílandi');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Ómani');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panáama');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Péeru');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Polinésia yʉ Ʉfaráansa');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papúua');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Ufilipíino');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakisitáani');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Pólandi');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Mʉtakatíifu Peéteri na Mɨkaéeli');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Patikaírini');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Pwetorɨ́ɨko');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Mweemberera wa kʉmweeri wa Gáaza');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Ʉréeno');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Paláau');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paraguáai');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Katáari');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Reyunióoni');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romaníia');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Urúusi');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Rwáanda');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Saudíia Arabíia');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Visíiwa vya Solomóoni');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Shelishéeli');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudáani');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Uswíidi');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapoo');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Mʉtakatíifu Heléena');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Sulovénia');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Sulováakia');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Seraleóoni');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'Samaríino');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegáali');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somália');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Surináamu');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Sao Tóome na Pirinsipe');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Elisalivado');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Síria');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Ʉswáazi');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Visíiwa vya Turíiki na Kaíiko');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Cháadi');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Tóogo');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Táilandi');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tajikisitáani');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokeláau');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Timóori yi Itʉʉmba');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Uturukimenisitáani');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunísia');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tóonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Uturúuki');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Tiriníida ya Tobáago');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuváalu');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwáani');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Taansanía');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ʉkɨréeni');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Ʉgáanda');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Amerɨka');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Uruguáai');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Usibekisitáani');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatikáani');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Mʉtakatíifu Viséenti na Gernadíini');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuéela');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Visíiwa vya Vigíini vya Ʉɨngeréesa');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Visíiwa vya Vigíini vya Amerɨ́ka');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vietináamu');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuáatu');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Walíisi na Futúuna');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samóoa');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Yémeni');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayóote');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Afɨrɨka ya Saame');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Sámbia');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Simbáabwe');
