CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afiganisitá');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Afríka ya Súdi');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Alabi Sawuditɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Alemani');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Alibani');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Alizɛri');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Ameriki');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Amɛni');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andorɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Angɛlɛtɛ́lɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Angiyɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angóla');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antiga mpé Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Antiyɛ ya Olandɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Arizantinɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Ayiti');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azɛlɛbaizá');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamasɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrɛnɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barɛbadɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Beleziki');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belizɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bengalidɛsi');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Biligari');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Bisanga bya Kapevɛrɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Bisanga bya Kayíma');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Bisanga bya Kookɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Bisanga bya Maluni');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Bisanga bya Marianɛ ya nɔ́rdi');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Bisanga bya Marishalɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Bisanga bya Turki mpé Kaiko');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Bisanga bya Vierzi ya Ameriki');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Bisanga bya Vierzi ya Angɛlɛtɛ́lɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Bisanga Solomɔ');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolivi');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosini mpé Hezegovine');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brezílɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brineyi');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Bukina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Butáni');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Byelorisi');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Danɛmarike');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Domínike');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Dzibuti');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ekwatɛ́lɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Elitelɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Esanga Norfokɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Esipanye');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Esitoni');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Etsíopi');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Ezípite');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Falánsɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fidzi');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Filandɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filipinɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabɔ');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambi');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Gana');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Geleki');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Gelenadɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Ginɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Ginɛbisau');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Ginɛ́kwatɛ́lɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Giyane');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Giyanɛ ya Falánsɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Gowelande');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Gwadɛlupɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Gwamɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Gwatémala');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ikrɛni');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Índɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonezi');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Irâ');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Iraki');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irelandɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Irigwei');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Isilandɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Isirayelɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Itali');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Kaledoni ya sika');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambodza');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kamɛrune');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Katari');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazakisitá');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kiba');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kigizisitá');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolombi');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Komorɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Korɛ ya nɔ́rdi');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Korɛ ya súdi');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Kositarika');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Kotídivualɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Koweti');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Krowasi');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Lawosi');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Lenyo');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesoto');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Letoni');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Lɛmila alabo');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libá');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Libériya');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libí');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Likisambulu');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Lishɛteni');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Litwani');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Mabelé ya Angɛlɛtɛ́lɛ na mbú ya Indiya');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagasikari');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Madívɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malezi');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Malí');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malitɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Marokɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martiniki');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Masedwanɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayotɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Meksike');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikronezi');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Molidavi');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monako');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongolí');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Morisɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Moritani');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Mɔsera');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambíki');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibi');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepálɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikaragwa');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nizerya');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Nizɛrɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norivezɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Nyué');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Olandɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Ománɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Ondurasɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Ongili');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Ositáli');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Otilisi');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakisitá');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Palagwei');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Palɛsine');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papwazi Ginɛ ya sika');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Péru');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pikairni');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Polinezi ya Falánsɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Poloni');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Pɔtoriko');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Putúlugɛsi');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Repibiki demokratiki ya Kongó');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Repibiki Tsekɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Repibiki ya Afríka ya Káti');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Repibiki ya Domínikɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Risí');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romani');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Rwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Samoa ya Ameriki');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Sántu eleni');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Sántu krístofe mpé Nevɛ̀s');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Sántu lisi');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'Sántu Marinɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Sántu pététo mpé Mikelɔ');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Sántu vesá mpé Gelenadinɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Sao Tomé mpé Presipɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Savadɔrɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegalɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Serebi mpé Monténegro');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Sɛshɛlɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Siera Leonɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Síli');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Silovaki');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Siloveni');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Sinɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapurɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Sípɛlɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Sirí');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sirilanka');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somali');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudá');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Surinamɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Swazilandi');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Swédɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Swisɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Tailandɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwanin');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzani');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tazikisitá');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Tikɛménisitá');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Tiliki');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Timorɛ ya Moniɛlɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Tinidadɛ mpé Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tinizi');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Tsádi');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzibɛkisitá');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatiká');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venézuela');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Viyetinamɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Walisɛ mpé Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Yemɛnɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Zamaiki');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambi');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Zapɔ');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Zelandɛ ya sika');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Zibatalɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Zɔdani');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Zorzi');
