CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('IE', 'ᎠᎢᎴᏂᏗ');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'ᎠᎵᎻᏂᎠ');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'ᎠᎵᏇᏂᏯ');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'ᎠᎵᏥᎵᏯ');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'ᎠᎷᏆ');
INSERT INTO "country" ("id", "name") VALUES ('US', 'ᎠᎹᏰᏟ');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'ᎠᎺᎵᎧ ᏌᎼᎠ');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'ᎠᏂᎦᎸᏣ ᏆᎵᏂᏏᎠ');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'ᎠᏂᎦᎸᏥ ᎩᎠ');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'ᎠᏂᎩᎳ');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'ᎠᏂᎪᎳ');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'ᎠᏂᏈᎵᎩᏃ');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'ᎠᏂᏍᏆᏂᏱ');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'ᎠᏂᏙᎳ');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'ᎠᏂᏛᏥ');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'ᎠᏍᏟᏯ');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'ᎠᏏᎵᏆᏌᏂ');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'ᎠᏓᏍᏓᏴᎲᏍᎩ ᎤᎦᏚᏛ');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'ᎠᏥᎸᏉᏗ ᎮᎵᎾ');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'ᎠᏥᎸᏉᏗ ᏆᏕᎳᎻ');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'ᎠᏥᎸᏉᏗ ᏡᏡ');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'ᎠᏥᏂᏘᏂᎠ');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'ᎠᏫᎨᏂᏍᏖᏂ');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'ᎠᏰᏟ ᎾᎿ ᎨᏥᎸᏉᏗ ᎠᏂᏪᏌ ᎠᎴ ᎠᏂᏁᏫᏍ');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'ᎠᏰᏟ ᏧᎾᎵᎪᎯ ᎾᎿ ᎹᎢᏉᏂᏏᏯ');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'ᎡᎳᏗᏜ');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'ᎡᎵᏟᏯ');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'ᎡᏆᏙᎵ');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'ᎡᏆᏙᎵᎠᎵ ᎩᎢᏂ');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'ᎡᏍᏙᏂᏯ');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'ᎢᎬᎾᏕᎾ ᎢᏤᏳᏍᏗ');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'ᎢᎳᎩ');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'ᎢᎴᏂ');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'ᎢᏂᏙᏂᏍᏯ');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'ᎢᏅᏗᎾ');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'ᎢᏏᎵᏱ');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'ᎢᏤ ᎧᎵᏙᏂᎠᏂ');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'ᎢᏤ ᏏᎢᎴᏂᏗ');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'ᎢᏤᏍᏛᏱ');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'ᎢᏥᏈᎢ');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'ᎢᏬᎵ ᎾᎿ ᎠᎹᏳᎶᏗ');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'ᎣᎴᏅᏓ ᏚᎦᏚᏛ');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'ᎣᎺᏂ');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'ᎤᏍᏗ ᎤᎦᏚᏛ ᎾᎿ ᎠᏍᎦᏯ');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'ᎤᏪᏘ ᎠᎴ ᏆᏊᏓ');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'ᎦᎠᎾ');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'ᎦᎸᏥᏱ');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'ᎦᎹᏈᎢᎠ');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'ᎦᏉᏂ');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'ᎦᏯᎾ');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'ᎧᎵᏆᏘ');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'ᎧᎶᎡᏏᎠ');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'ᎧᎹᎷᏂ');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'ᎧᎹᏉᏗᎠᏂ');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'ᎧᏂᎪ');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'ᎧᏂᎪ [ᏍᎦᏚᎩ]');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'ᎧᏎᎧᏍᏕᏂ');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'ᎧᏔᎵ');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'ᎨᎢᎹᏂ ᏚᎦᏚᏛᎢ');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'ᎨᎾᏓ');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'ᎨᏂᏯ');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'ᎩᎵᏏᏲ');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'ᎩᎵᏣᎢᏍ');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'ᎪᎢᎯ');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'ᎪᎪᏍ [ᎩᎵᏂ] ᏚᎦᏚᏛ');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'ᎪᎸᎻᏈᎢᎠ');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'ᎪᎼᎳᏍ');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'ᎪᏍᏓ ᎵᎧ');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'ᎫᏆ');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'ᎫᏇ');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'ᎫᏇ-ᏈᏌᎤᏫ');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'ᎫᏪᎢᏘ');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'ᎬᎿᎨᏍᏛ ᎠᏰᏟ ᏍᎦᏚᎩ');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'ᎬᏂᏏ');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'ᎮᎢᏘ');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'ᎰᏂᎩ ᎪᏂᎩ');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'ᎲᏂᎦᎵ');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'ᎲᏗ ᎤᎦᏚᏛ ᎠᎴ ᎺᎩᏓᎾᎵᏗ ᏚᎦᏚᏛ');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'ᎳᏈᎵᏯ');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'ᎳᏘᏫᎠ');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'ᎴᎣᏍ');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'ᎴᏆᎾᏂ');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'ᎴᏐᏙ');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'ᎵᎦᏗᏂᏍᏓᏂ');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'ᎵᏈᏯ');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'ᎵᏗᏪᏂᎠ');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'ᎶᎹᏂᏯ');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'ᎶᏩᏂᏓ');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'ᎸᎧᏎᏋᎩ');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'ᎹᎧᎣ [ᎤᏓᏤᎵᏓ ᏧᏂᎸᏫᏍᏓᏁᏗ ᎢᎬᎾᏕᎾ] ᏣᎢ');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'ᎹᎳᏫ');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'ᎹᎴᏏᎢᎠ');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'ᎹᎵ');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'ᎹᎵᏔ');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'ᎹᎵᏗᏫᏍ');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'ᎹᎵᏙᏫᎠ');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'ᎹᎾᎪ');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'ᎹᏂᎪᎵᎠ');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'ᎹᏂᏘᏌᎳᏗ');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'ᎹᏌᎵ ᏚᎪᏚᏛ');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'ᎹᏏᏙᏂᎢᎠ');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'ᎹᏓᎦᏍᎧᎵ');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'ᎹᏘᎢᏯ');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'ᎹᏘᏂᎨ');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'ᎹᏯᎹᎵ');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'ᎼᎵᏏᎥᏍ');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'ᎼᎶᎪ');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'ᎼᏂᏔᏁᎦᎶ');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'ᎼᏎᎻᏇᎩ');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'ᎾᎻᏈᎢᏯ');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'ᎾᏍᎩ ᎤᏴᏢ ᏗᏜ ᎹᎵᎠᎾ ᏚᎦᏚᏛ');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'ᎾᏍᎩ ᏆᎭᎹᏍ');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'ᏁᏆᎵ');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'ᏁᏛᎳᏂ');
INSERT INTO "country" ("id", "name") VALUES ('CW', 'ᏂᎦᏓ ᎤᏂᎲ ᎾᎿ ᎫᎳᎨᎣ');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'ᏂᎧᎳᏆ');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'ᏂᏥᎵᏯ');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'ᏂᏳ');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'ᏃᎤᎷ');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'ᏃᎵᏬᎵᎩ ᎤᎦᏚᏛ');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'ᏃᏪ');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'ᏆᎩᏍᏖᏂ');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'ᏆᎭᎴᎢᏂ');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'ᏆᎳᏇᎢᏯ');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'ᏆᎴᎠᏫ');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'ᏆᎴᏍᏗᏂᎠᏂ ᏄᎬᏫᏳᏌᏕᎩ');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'ᏆᎻ');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'ᏆᎾᎹ');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'ᏆᏂᎢᏂ');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'ᏆᏂᎦᎵᏕᏍ');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'ᏆᏇ ᎢᏤ ᎩᏂ');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'ᏆᏇᏙᏍ');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'ᏆᏊᏓ');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'ᏆᏏᎵᎢ');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'ᏆᏣᏩᎾ');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'ᏇᎡᏙ ᎵᎢᎪ');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'ᏇᎳᎷᏍ');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'ᏇᎵᏍ');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'ᏇᎵᏥᎥᎻ');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'ᏇᎷ');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'ᏈᎧᎵᏂ ᎤᎦᏚᏛᎢ');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'ᏈᏗᏏ ᏴᏫᏯ ᎠᎺᏉ ᎢᎬᎾᏕᏅ');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'ᏉᎳᏂ');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'ᏉᎵᏫᎠ');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'ᏉᏏᏂᎠ ᎠᎴ ᎲᏤᎪᏫ');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'ᏉᏥᎦᎳ');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'ᏊᎵᎨᎵᎠ');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'ᏊᎾᎢ');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'ᏊᏔᏂ');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'ᏊᏪ ᎤᎦᏚᏛ');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'ᏋᎩᎾ ᏩᏐ');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'ᏋᎷᏂᏗ');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'ᏋᎾᏓ');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'ᏌᎢᏆᏍ');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'ᏌᎤᏗ ᎡᎴᏈᎠ');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'ᏌᏊ ᎢᏳᎾᎵᏍᏔᏅ ᎡᎳᏈ ᎢᎹᎵᏘᏏ');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'ᏍᎵ ᎳᏂᎧ');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'ᏍᎶᏩᎩᎠ');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'ᏍᎶᏫᏂᎠ');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'ᏍᏆᏂᏱ');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'ᏍᏫᏍ');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'ᏍᏫᏕᏂ');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'ᏎᏂᏘ ᏈᏓ ᎠᎴ ᎻᏇᎶᏂ');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'ᏏᎡᎳ ᎴᎣᏂ');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'ᏏᎡᏥᎵᏍ');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'ᏏᏂᎦᏉᎵ');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'ᏐᎶᎹᏂ ᏚᎦᏚᏛ');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'ᏑᏕᏂ');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'ᏒᏈᏯ');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'ᏓᎶᏂᎨᏍᏛ');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'ᏓᏂᏍᏓᏲᎯᎲ ᎤᎦᏚᏛ');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'ᏗᏂᎹᎦ');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'ᏙᎻᏂᎧ');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'ᏙᎻᏂᎧᏂ ᏍᎦᏚᎩ');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'ᏣᎠᏥᎢ');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'ᏣᎺᎢᎧ');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'ᏣᏩᏂᏏ');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'ᏤᎩ ᏍᎦᏚᎩ');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'ᏥᎵ');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'ᏥᏆᎵᏓ');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'ᏥᏊᏗ');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'ᏦᏓᏂ');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'ᏧᎦᏃᏮ ᎪᎵᎠ');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'ᏧᎦᏃᏮ ᏣᏥᏱ ᎠᎴ ᎾᏍᎩ ᏧᎦᏃᏮ ᎠᏍᏛᎭᏟ ᏚᎦᏚᏛ');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'ᏧᏁᏍᏓᎸ');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'ᏧᏁᏍᏓᎸᎯ');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'ᏧᏴᏢ ᎪᎵᎠ');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'ᏨᎵᏏ');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'ᏩᎩ ᎤᎦᏚᏛ');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'ᏩᏓᎷᏇ');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'ᏩᏔᎹᎳ');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'ᏪᎶ ᏚᎦᏚᏛ');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'ᏫᏂᎦᏙᎯ');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'ᏫᏥ');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'ᏲᎶ');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'ᏲᏂᎢ');
