CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('IE', 'අයර්ලන්තය');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'අයිස්ලන්තය');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'අරුබාව');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'අසර්බයිජානය');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'ආර්ජෙන්ටිනාව');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'ආර්මේනියාව');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'ඇන්ගුයිලාව');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'ඇන්ගෝලාව');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'ඇන්ටාක්ටිකාව');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'ඇන්ටිගුවා සහ බාබියුඩා');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'ඇන්ඩෝරාව');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'ඇමරිකානු වර්ජින් දූපත්');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'ඇමරිකානු සැමෝවාව');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'ඇල්ජීරියාව');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'ඇල්බේනියාව');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'ඇසෙන්ෂන් දිවයින');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'ඇෆ්ගනිස්ථානය');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'ඉක්වදෝරය');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'ඉතාලිය');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'ඉතියෝපියාව');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'ඉන්දියාව');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'ඉන්දුනීසියාව');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'ඉරාකය');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'ඉරානය');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'ඊජිප්තුව');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'ඊශ්‍රායලය');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'උතුරු කොරියාව');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'උස්බෙකිස්ථානය');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'එක්සත් අරාබි එමිර් රාජ්‍යය');
INSERT INTO "country" ("id", "name") VALUES ('US', 'එක්සත් ජනපදය');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'එක්සත් රාජධානිය');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'එරිත්‍රියාව');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'එල් සැල්වදෝරය');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'එස්තෝනියාව');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'ඔස්ට්‍රියාව');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'ඕමානය');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'ඕලන්ඩ් දූපත්');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'ඕස්ට්‍රේලියාව');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'කටාර්ය');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'කැනඩාව');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'කැමරූන්');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'කියුබාව');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'කුක් දූපත්');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'කුවේටය');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'කෙන්යාව');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'කොකෝස් දූපත්');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'කොළොම්බියාව');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'ගැබොන්');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'ගැම්බියාව');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'ගිණියාව');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'ග්‍රැනඩාව');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'ග්‍රීන්ලන්තය');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'ග්‍රීසිය');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'ඝානාව');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'චිලී');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'චීනය');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'ජපානය');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'ජර්මනිය');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'ජැමෙයිකාව');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'ජිබ්‍රෝල්ටාව');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'ජෝර්ජියාව');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'ජෝර්දානය');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'ටර්ක්ස් සහ කයිකොස් දූපත්');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'ටියුනීසියාව');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'ටුවාලූ');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'ටොකලාවු');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'ට්‍රිනිඩෑඩ් සහ ටොබැගෝ');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'ඩෙන්මාර්කය');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'තායිලන්තය');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'තායිවානය');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'තුර්කිය');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'තුර්ක්මෙනිස්ථානය');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'දකුණු අප්‍රිකාව');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'දකුණු කොරියාව');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'නයිජර්');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'නයිජීරියාව');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'නව කැලිඩෝනියාව');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'නවසීලන්තය');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'නාවුරු');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'නැමීබියාව');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'නිකරගුවාව');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'නියූ');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'නෙදර්ලන්ත ඇන්ටිලීසිය');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'නෙදර්ලන්තය');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'නේපාලය');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'නෝර්වේ');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'නෝෆෝක් දූපත');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'පලස්තීනය');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'පලාවු');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'පාකිස්තානය');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'පැනමා');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'පැපුවා නිව් ගිනියාව');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'පැරගුවේ');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'පිට්කෙය්න් දූපත්');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'පිලිපීනය');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'පෘතුගාලය');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'පේරු');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'පෝලන්තය');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'ප්‍රංශ ගයනාව');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'ප්‍රංශ පොලිනීසියාව');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'ප්‍රංශය');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'බංගලිදේශය');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'බටහිර සහරාව');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'බර්කිනා ෆාසෝ');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'බර්මියුඩා');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'බල්ගේරියාව');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'බහමාස්');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'බහරේන්');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'බාර්බඩෝස්');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'බුරුන්ඩි');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'බෲනායි');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'බෙනින්');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'බෙලරුස්');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'බෙලීස්');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'බෙල්ජියම');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'බොලීවියාව');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'බොස්ට්වානා');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'බොස්නියාව සහ හර්සගොවීනාව');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'බ්‍රසීලය');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'බ්‍රිතාන්‍ය ඉන්දීය සාගර ප්‍රාන්තය');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'බ්‍රිතාන්‍ය වර්ජින් දූපත්');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'භූතානය');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'මාර්ටිනික්');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'මාල දිවයින');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'මාලි');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'මැලේසියාව');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'මියන්මාරය');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'මුරුසිය');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'මෙක්සිකෝව');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'මොනාකෝව');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'මොන්ගෝලියාව');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'මොන්ඩිනීග්‍රෝ');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'මොන්සෙරාට්');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'මොරොක්කෝව');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'මොල්ඩෝවාව');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'මොසැම්බික්');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'මෝල්ටාව');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'යුක්රේනය');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'යුරෝපා සංගමය');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'යේමනය');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'රුමේනියාව');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'රුසියාව');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'ලයිබීරියාව');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'ලාඕසය');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'ලැට්වියාව');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'ලිතුවේනියාව');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'ලිබියාව');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'ලෙබනනය');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'වනුවාටු');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'වියට්නාමය');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'ශාන්ත ලුසියා');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'ශ්‍රී ලංකාව');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'සමක ගිනියාව');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'සයිප්‍රසය');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'සර්බියාව');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'සැමෝවා');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'සැම්බියාව');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'සිංගප්පූරුව');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'සිම්බාබ්වේ');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'සූඩානය');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'සෞදි අරාබිය');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'ස්පාඤ්ඤය');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'ස්ලෝවැකියාව');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'ස්ලෝවේනියාව');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'ස්විස්ටර්ලන්තය');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'ස්වීඩනය');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'හන්ගේරියාව');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'හයිටි');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'හාඩ් සහ මැක්ඩොනල්ඩ් දූපත්');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'හොංකොං චීන විශේෂ පරිපාලන කලාපය');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'හොන්ඩුරාස්');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'ෆැරෝ දූපත්');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'ෆින්ලන්තය');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'ෆීජී');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'ෆෝක්ලන්ත දූපත්');
