CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AR', 'آرژانتین');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'آروبا');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'آلبانی');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'آلمان');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'آنتیگوا و باربودا');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'آنتیل هلند');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'آندورا');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'آنگولا');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'آنگیل');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'اتحادیهٔ اروپا');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'اتریش');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'اتیوپی');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'اردن');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'ارمنستان');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'اروگوئه');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'اریتره');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'ازبکستان');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'اسپانیا');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'استرالیا');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'استونی');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'اسرائیل');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'اسلواکی');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'اسلوونی');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'اسوالبارد و جان‌ماین');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'افریقای جنوبی');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'افغانستان');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'اکوادور');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'الجزایر');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'السالوادور');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'امارات متحدهٔ عربی');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'اندونزی');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'اوکراین');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'اوگاندا');
INSERT INTO "country" ("id", "name") VALUES ('US', 'ایالات متحدهٔ امریکا');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'ایتالیا');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'ایران');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'ایرلند');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'ایسلند');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'باربادوس');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'باهاما');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'بحرین');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'بخش‌های دورافتادهٔ اقیانوسیه');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'برزیل');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'برمودا');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'برونئی');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'بریتانیا');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'بلژیک');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'بلغارستان');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'بلیز');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'بنگلادش');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'بنین');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'بوتان');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'بوتسوانا');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'بورکینافاسو');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'بوروندی');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'بوسنی و هرزگوین');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'بولیوی');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'بیلوروسی');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'پاپوا گینهٔ نو');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'پاراگوئه');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'پاکستان');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'پالائو');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'پاناما');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'پرتغال');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'پرو');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'پلی‌نزی فرانسه');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'پورتوریکو');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'تاجیکستان');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'تانزانیا');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'تایلند');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'تایوان');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'ترکمنستان');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'ترکیه');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'تریستان دا کونا');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'ترینیداد و توباگو');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'توکلائو');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'توگو');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'تونس');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'تونگا');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'تووالو');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'تیمور لسته');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'جامائیکا');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'جبل‌الطارق');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'جرزی');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'جزایر آسنسیون');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'جزایر آلاند');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'جزایر پیت‌کرن');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'جزایر ترک و کایکوس');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'جزایر سلیمان');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'جزایر فارو');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'جزایر فالکلند');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'جزایر قناری');
INSERT INTO "country" ("id", "name") VALUES ('CP', 'جزایر کلیپرتون');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'جزایر کوچک دورافتادهٔ ایالات متحده');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'جزایر کوک');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'جزایر کوکوس [کیلینگ]');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'جزایر کِیمن');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'جزایر مارشال');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'جزایر ماریانای شمالی');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'جزایر ویرجین ایالات متحده');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'جزایر ویرجین بریتانیا');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'جزیره بووت');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'جزیرهٔ کریسمس');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'جزیرهٔ من');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'جزیرهٔ نورفولک');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'جزیرهٔ هرد و جزایر مک‌دونالد');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'جمهوری آذربایجان');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'جمهوری افریقای مرکزی');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'جمهوری چک');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'جمهوری دومینیکن');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'جنوبگان');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'جورجیای جنوبی و جزایر ساندویچ جنوبی');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'جیبوتی');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'چاد');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'چین');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'دانمارک');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'دومینیک');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'دیه‌گو گارسیا');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'رواندا');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'روسیه');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'رومانی');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'ریونیون');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'زامبیا');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'زلاند نو');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'زیمبابوه');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'ژاپن');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'سائوتومه و پرینسیپه');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'ساحل عاج');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'ساموا');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'ساموای امریکا');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'سان‌مارینو');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'سبته و ملیله');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'سرزمین‌های فلسطینی');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'سری‌لانکا');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'سنت بارتیلمی');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'سنت پیر و میکلون');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'سنت کیتس و نویس');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'سنت لوسیا');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'سنت مارتین');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'سنت وینسنت و گرنادین');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'سنت هلن');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'سنگاپور');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'سنگال');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'سوازیلند');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'سوئد');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'سوئیس');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'سودان');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'سورینام');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'سوریه');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'سومالی');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'سیرالئون');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'سیشل');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'شیلی');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'صحرای غربی');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'صربستان');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'صربستان و مونته‌نگرو');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'عراق');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'عربستان سعودی');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'عمان');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'غنا');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'فرانسه');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'فنلاند');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'فیجی');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'فیلیپین');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'قبرس');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'قرقیزستان');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'قزاقستان');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'قطر');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'کاستاریکا');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'کالدونیای جدید');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'کامبوج');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'کامرون');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'کانادا');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'کرواسی');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'کرهٔ جنوبی');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'کرهٔ شمالی');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'کریباتی');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'کلمبیا');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'کنگو - برازویل');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'کنگو - کینشاسا');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'کنیا');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'کوبا');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'کومورو');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'کویت');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'کیپ‌ورد');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'گابون');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'گامبیا');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'گرانادا');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'گرجستان');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'گرنزی');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'گرینلند');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'گواتمالا');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'گوادلوپ');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'گوام');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'گویان');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'گویان فرانسه');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'گینه');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'گینهٔ استوایی');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'گینهٔ بیسائو');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'لائوس');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'لبنان');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'لتونی');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'لسوتو');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'لوکزامبورگ');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'لهستان');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'لیبریا');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'لیبی');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'لیتوانی');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'لیختن‌اشتاین');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'ماداگاسکار');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'مارتینیک');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'ماکائو، ناحیهٔ ویژهٔ حکومتی چین');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'مالاوی');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'مالت');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'مالدیو');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'مالزی');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'مالی');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'مایوت');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'مجارستان');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'مراکش');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'مستعمره‌های بریتانیا در اقیانوس هند');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'مستعمره‌های جنوبی فرانسه');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'مصر');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'مغولستان');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'مقدونیه');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'مکزیک');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'موریتانی');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'موریس');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'موزامبیک');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'مولداوی');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'موناکو');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'مونت‌سرات');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'مونته‌نگرو');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'میانمار [برمه]');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'میکرونزی');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'نائورو');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'نامیبیا');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'نپال');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'نروژ');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'نیجر');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'نیجریه');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'نیکاراگوئه');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'نیوئه');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'واتیکان');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'والیس و فیوتونا');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'وانواتو');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'ونزوئلا');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'ویتنام');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'هائیتی');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'هلند');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'هند');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'هندوراس');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'هنگ‌کنگ، ناحیهٔ ویژهٔ حکومتی چین');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'یمن');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'یونان');
