CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('QA', 'ཀ་ཏཱར།');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'ཀ་མེ་རུན།');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'ཀམ་བོ་ཌི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'ཀཱུག གླིང་ཕྲེན་རྒྱལ་ཁབ།');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'ཀི་རི་བཱ་ཏི།');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'ཀུ་ཝེད་རྒྱལ་ཁབ།');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'ཀུརོ་ཤི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'ཀོ་ཊེ་ཌི། ཨི་ཝོ་རེ།');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'ཀོ་རི་ཡ། ལྷོ་མ།');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'ཀོ་ལོམ་བི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'ཀོ་ས྄ཊ་རི་ཀ།');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'ཁ་ཛཱག་སྟཱན།');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'ཁིར་གིཛ་སྟཱན།');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'ཁེ་ན་ཌ།');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'ཁེ་མེན་གླིང་ཕྲན།');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'ཁེན་ཉི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'ཁྱུའུ་བ།');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'གེ་བཽན།');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'གྷ་ན།');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'གྷ་རི་ན་ཌ།');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'གྷམ་བི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'གྷི་ནི་ཡ་བིས྄་སོ།');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'གྷི་ནི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'གྷི་རཱི་སི།');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'གྷུ་ཡཱ་ན།');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'གྷོ་ཊེ་མ་ལ།');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'ཅི་ལི།');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'ཅཻག་སྤྱི་མཐུན་རྒྱལ་ཁབ།');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'ཅཻཌ།');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'ཇིབ་རཱལ་ཊར།');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'ཇོར་ཇི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'ཇོར་ཌན།');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'ཌེན་མཱརྐ།');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'ཌོ་མིན་ནི་ཀ།');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'ཌོ་མིནནི་ཀན་སྤྱི་མཐུན་རྒྱལ་ཁབ།');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'ཏུརཀི།');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'ཐུ་ཝ་ལུ།');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'དབྱིན་ཇི་');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'ན་མི་བི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'ནའི་ཇར།');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'ནཱའི་ཇི་རི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'ནི་ཀ་ར་གུ་ཨ།');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'ནིའུ་ཛི་ལན྄ཌ།');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'ནིའུ་ཝ།');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'ནུ་བ་ས་མོ་འ།');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'ནེ་ཐར་ལནྜ།');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'ནོར་ཝེ།');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'ནཽ་རུ།');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'པ་ནཱ་མ།');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'པ་པུ་ཨ། ནིའུ། གྷི་ནི།');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'པ་ལཽ།');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'པཀི་སྟཱན།');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'པཱ་ར་གེ།');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'པེ་རུ།');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'པོ་ལནྜ།');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'པོར་ཏུ་གྷལ།');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'ཕ་རཱན་སི།');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'ཕལྐ་ལནྜ་གླིང་ཕྲན།');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'ཕི་ཇི།');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'ཕི་ལི་པིནས྄།');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'ཕིན་ལན྄ཌ།');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'བ་རཱ་ཛིལ།');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'བངྒ་ལ་དེཤ།');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'བར་མུ་ཌ།');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'བར་ཡུལ་');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'བརཀི་ན། ཕསོ།');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'བཱརྦ་ཌོས྄།');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'བཱེ་ནིན།');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'བུ་རུ་ནེ།');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'བུ་རུན་ཌི།');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'བུལ་ག་རི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'བེ་ལིཛ།');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'བེ་ལུ་རུ་སུ།');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'བེལ་ཇི་ཡམ།');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'བོ་ལི་ཝིཡ།');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'བོཙ་ཝ་ན།');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'བོསྣི་ཡ་དང་ཧརྫོ་གོ་ཝི་ན།');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'བྷཱ་མས྄།');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'བྷཱ་རེན།');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'མ་དཱ་གྷསྐཱར།');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'མ་ལི།');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'མ་ལེ་ཤི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'མལ་ཊ།');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'མལ་དྭིབ།');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'མཱ་ལཱ་ཝི།');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'མཱར་ཤལ་གླིང་ཕྲེན།');
INSERT INTO "country" ("id", "name") VALUES ('ZZ', 'མིའི་ཤེས་རྟོགས་མ་བྱུང་བའི་ཁོར་ཡུག');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'མེ་ཀའོ།');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'མེཀ་སི་ཀོ།');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'མོ་ན་ཀོ།');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'མོ་ཛམ་བིག།');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'མོ་རོ་ཀྐོ།');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'མཽ་རི་ཏ་ནི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'མཽ་རིཤས྄།');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'ཛ་མེ་ཀ།');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'ཛམ་བི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'ཛི་བུ་ཏི།');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'ཛིམ་བྷཱ་བེ།');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'ཝ་ནུ་ཨ་ཐུ།');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'ཝེ་ཊི་ཀན།');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'ཝེ་ནི་ཛུའེ་ལ།');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'ཝེད་ནམ།');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'འཇར་མན་');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'འབར་མ།');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'འབྲུག་ཡུལ།');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'ཡུ་ཀརེན།');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'ཡུ་གན་ཌ།');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'ཡེ་མེན།');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'རི་པིན་');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'རུ་ཝན་ཌ།');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'རོ་མཱ་ནིཡ།');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'རྒྱ་གར་');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'རྒྱ་ནག');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'ལཀ་ཛམ་བོརྒ།');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'ལཏ་བི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'ལཱ་འོས།');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'ལི་ཐུ་ཨེ་ནི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'ལི་བི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'ལི་བེ་རི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'ལེ་སོ་ཐོ།');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'ལེག་ཏེན་ཚིན།');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'ལེབ་ནོན།');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'ལྷོ་ ཨཕྲི་ཀ།');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'ལྷོ་རྩེའི་མཐའ་གླིང་།');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'ཤྲཱི་ལང་ཀ།');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'ས་འོ་ཏོད་མད། དང༌། པ྄རིན་སི་པེ།');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'ས་ལཽ་ཝཀྱ།');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'ས་ལཽ་ཝེ་ནི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'སན་མེ་རི་ནོ།');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'སཱ་ཤཻལ།');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'སཱཡེ་པ་རས྄།');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'སི་པན།');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'སིངྒ་པུར།');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'སུ་དཱན།');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'སུ་རི་ནཱམ།');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'སེ་ནི་གྷལ།');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'སེ་ཡར་ར། ལིའོན།');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'སེནྚ། ཀིཊྚས྄། དང༌། ནེ་བིས྄།');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'སེནྚ། ཝིན་སན། དང༌། གྷིརིན་ཌིན།');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'སེནྚ། ལུ་ཤི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'སེནྚ། ཧེ་ལི་ན།');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'སེར་བི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'སོ་མཱལི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'སོ་ལོ་མོན། གླིང་ཕྲན་ཚོ་ཁག།');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'སོག་ཡུལ།');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'སཽ་དྷི་ཨ་རཱ་བི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'ཧངྒ་རི།');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'ཧེ་ཏི།');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'ཧོང་ཀོང༌།');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'ཧོན་དུ་རས྄།');
INSERT INTO "country" ("id", "name") VALUES ('US', 'ཨ་མེ་རི་ཀ་');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'ཨ་ཡར་ལནཌ།');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'ཨ་རབ། ཨི་མི་རཊ྄། ཆིག་སྒྲིལ་རྒྱལ་ཁབ།');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'ཨ་རུ་བ།');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'ཨ་ཨི་སི་ལནད།');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'ཨང་གུའི་ལ།');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'ཨང་གཽ་ལ།');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'ཨཕ་ག་ནི་སྟཱན།');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'ཨཛར་བཡེ་ཇན།');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'ཨར་ཇེན་ཊི་ན།');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'ཨར་མེ་ནི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'ཨལ་ཇི་རི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'ཨལ་བཱ་ནི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'ཨསྟྲི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'ཨསྟྲེ་ལི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'ཨི་ཀྲར་ལི་');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'ཨི་ཁྭ་ཌོར།');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'ཨི་ཇིབྚ།');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'ཨི་ཐིའོ་པི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'ཨི་ཛ྄་རེལ།');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'ཨི་རག།');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'ཨི་རཱན།');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'ཨིན་ཌོ་ནེ་ཤི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'ཨིསྟོ་ནི་ཡ།');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'ཨུ་རུ་གྷེ།');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'ཨུ་རུ་སུ་');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'ཨུཛ་བེ་ཀིསྟཱན།');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'ཨེ་རི་ཏྲེ་ཨ།');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'ཨེན་ཊི་གུ་དང་། བྷར་བུ་ཌ།');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'ཨེན་ཌོ་ར།');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'ཨེལ། སཱལ་ཝ་ཌོར།');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'ཨོ་མན།');
