#!/usr/bin/env php
<?php

/**
 * This file is part of the Country List project.
 *
 *  (c) Саша Стаменковић <umpirsky@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */


/**
 * Dumps country list to all formats in all languages.
 */

require_once __DIR__ . '/autoload.php';

use Symfony\Component\Filesystem\Filesystem;
use Umpirsky\Country\Dumper\Iterator as DumperIterator;
use Umpirsky\Country\Importer\Iterator as ImporterIterator;

$filesystem = new Filesystem();
$dumperIterator = new DumperIterator();
$importerIterator = new ImporterIterator();
$filesystem->mkdir($rootDir = sprintf('%s/country', __DIR__));
foreach ($importerIterator as $importer) {
    $filesystem->mkdir($importerDir = sprintf('%s/%s', $rootDir, $importer->getSource()));
    foreach ($importer->getLanguages() as $language) {
        $filesystem->mkdir($dumperDir = sprintf('%s/%s', $importerDir, $language));
        $countries = $importer->getCountries($language);
        foreach($dumperIterator as $dumper) {
            $file = sprintf('%s/country.%s', $dumperDir, $dumper->getFormat());
            $filesystem->touch($file);
            file_put_contents($file, $dumper->dump($countries));
        }
    }
}
