#!/usr/bin/env php
<?php

/**
 * This file is part of the Country List project.
 *
 *  (c) Саша Стаменковић <umpirsky@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */


/**
 * Dumps country list to all formats in all languages.
 */

require_once __DIR__ . '/autoload.php';

use Symfony\Component\Locale\Locale;
use Symfony\Component\Filesystem\Filesystem;
use Umpirsky\Country\Dumper\Iterator;

$locale = new Locale();
$filesystem = new Filesystem();
$dumperIterator = new Iterator();
$filesystem->mkdir($rootDir = sprintf('%s/country', __DIR__));
foreach ($locale->getLocales() as $language) {
    $filesystem->mkdir($dir = sprintf('%s/%s', $rootDir, $language));
    $countries = $locale->getDisplayCountries($language);
    foreach($dumperIterator as $dumper) {
        $file = sprintf('%s/country.%s', $dir, $dumper->getFormat());
        $filesystem->touch($file);
        file_put_contents($file, $dumper->dump($countries));
    }
}
