#!/usr/bin/env php
<?php

/**
 * This file is part of the Country List project.
 *
 *  (c) Саша Стаменковић <umpirsky@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Umpirsky\Country\Builder\Builder;

/**
 * Country list command line build interface.
 */

require_once __DIR__ . '/autoload.php';

$builder = new Builder(sprintf('%s/country', __DIR__));
$builder->run();
