CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'ሀንጋሪ');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'ሀይቲ');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'ህንድ');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'ሆንዱራስ');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'ሆንግ ኮንግ SAR ቻይና');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'ሉክሰምበርግ');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'ሊቢያ');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'ሊባኖስ');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'ሊቱዌኒያ');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'ሊችተንስታይን');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'ላትቪያ');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'ላኦስ');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'ላይቤሪያ');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'ሌሶቶ');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'ሚክሮኔዢያ');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'ማሊ');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'ማላዊ');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'ማሌዢያ');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'ማልታ');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'ማልዲቭስ');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'ማሩሸስ');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'ማርሻል አይላንድ');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'ማርቲኒክ');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'ማከዶኒያ');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'ማካኡSAR ቻይና');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'ማያንማር');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'ማዳጋስካር');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'ሜክሲኮ');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'ሜይኦቴ');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'ምስራቅ ቲሞር');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'ምዕራባዊ ሳህራ');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'ሞልዶቫ');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'ሞሪቴኒያ');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'ሞሮኮ');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'ሞናኮ');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'ሞንተኔግሮ');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'ሞንትሴራት');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'ሞንጎሊያ');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'ሞዛምቢክ');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'ሩዋንዳ');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'ሪዩኒየን');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'ራሺያ');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'ሮሜኒያ');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'ሰሎሞን ደሴት');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'ሰሜን ኮሪያ');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'ሰርቢያ');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'ሰርብያ');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'ሱማሌ');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'ሱሪናም');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'ሱዋዚላንድ');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'ሱዳን');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'ሲሪላንካ');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'ሲሪያ');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'ሲሼልስ');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'ሲንጋፖር');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'ሳሞአ');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'ሳን ማሪኖ');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'ሳኦ ቶሜ እና ፕሪንሲፔ');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'ሳውድአረቢያ');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'ሳይፕረስ');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'ሴራሊዮን');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'ሴኔጋል');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'ሴንት ሄለና');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'ሴንት ሉቺያ');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'ሴንት ማርቲን');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'ሴኡታና ሜሊላ');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'ስሎቫኪያ');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'ስሎቬኒያ');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'ስቫልባርድ እና ጃን ማየን');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'ስዊዘርላንድ');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'ስዊድን');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'ስፔን');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'ቅዱስ በርቴሎሜ');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'ቅዱስ ቪንሴንት እና ግሬናዲንስ');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'ቅዱስ ኪትስ እና ኔቪስ');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'ቅዱስ ፒዬር እና ሚኩኤሎን');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'ቡህታን');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'ቡልጌሪያ');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'ቡርኪና ፋሶ');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'ቡቬት ደሴት');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'ቢሳዎ');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'ባሃማስ');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'ባህሬን');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'ባርቤዶስ');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'ባንግላዲሽ');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'ቤሊዘ');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'ቤላሩስ');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'ቤልጄም');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'ቤርሙዳ');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'ቤኒን');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'ብሩኒ');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'ብሩንዲ');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'ብራዚል');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'ቦሊቪያ');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'ቦስኒያ እና ሄርዞጎቪኒያ');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'ቦትስዋና');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'ቫቲካን');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'ቫኑአቱ');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'ቬትናም');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'ቬንዙዌላ');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'ቱርክ');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'ቱርክሜኒስታን');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'ቱቫሉ');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'ቱኒዚያ');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'ታንዛኒያ');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'ታይላንድ');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'ታይዋን');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'ታጃኪስታን');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'ትሪስታን ዲ ኩንሃ');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'ትሪኒዳድ እና ቶባጎ');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'ቶንጋ');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'ቶክላው');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'ቶጐ');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'ቺሊ');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'ቻይና');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'ቻድ');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'ቼክ ሪፑብሊክ');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'ኒኡይ');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'ኒካራጓ');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'ኒው ካሌዶኒያ');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'ኒው ዚላንድ');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'ኒጀር');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'ናሚቢያ');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'ናኡሩ');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'ናይጄሪያ');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'ኔዘርላንድ');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'ኔዘርላንድስ አንቲልስ');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'ኔፓል');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'ኖርዌ');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'ኖርፎልክ ደሴት');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'አልባኒያ');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'አልጄሪያ');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'አሜሪካ');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'አሩባ');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'አርሜኒያ');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'አርጀንቲና');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'አሴንሽን ደሴት');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'አንቲጓ እና ባሩዳ');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'አንታርክቲካ');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'አንዶራ');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'አንጉኢላ');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'አንጐላ');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'አውስትሬሊያ');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'አውትላይንግ ኦሽንያ');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'አዘርባጃን');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'አየርላንድ');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'አይል ኦፍ ማን');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'አይስላንድ');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'አፍጋኒስታን');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'ኡራጓይ');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'ኢራቅ');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'ኢራን');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'ኢትዮጵያ');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'ኢንዶኔዢያ');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'ኢኳቶሪያል ጊኒ');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'ኢኳዶር');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'ኤል ሳልቫዶር');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'ኤርትራ');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'ኤስቶኒያ');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'እስራኤል');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'እንግሊዝ');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'ኦማን');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'ኦስትሪያ');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'ኩባ');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'ኩክ ደሴቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'ኪሪባቲ');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'ኪርጊስታን');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'ካሜሩን');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'ካምቦዲያ');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'ካናዳ');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'ካዛኪስታን');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'ካይማን ደሴቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'ኬንያ');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'ኬፕ ቬርዴ');
INSERT INTO `country` (`id`, `name`) VALUES ('CP', 'ክሊፐርቶን ደሴት');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'ክሮኤሽያ');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'ክዌት');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'ኮሎምቢያ');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'ኮሞሮስ');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'ኮስታ ሪካ');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'ኮት ዲቯር');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'ኮንጎ');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'ኮንጐ');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'ኮኮስ[ኬሊንግ] ደሴቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'ኳታር');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'ኽርድ ደሴቶችና ማክዶናልድ ደሴቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'ዋሊስ እና ፉቱና ደሴቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'ዚምቧቤ');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'ዛምቢያ');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'የመን');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'የመካከለኛው አፍሪካ ሪፐብሊክ');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'የሰሜናዊ ማሪያና ደሴቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'የብሪታኒያ ህንድ ውቂያኖስ ግዛት');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'የተባበሩት አረብ ኤምሬትስ');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'የቱርኮችና የካኢኮስ ደሴቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'የአላንድ ደሴቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'የአሜሪካ ሳሞአ');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'የአሜሪካ ቨርጂን ደሴቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('EU', 'የአውሮፓ ህብረት');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'የእንግሊዝ ድንግል ደሴቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'የካናሪ ደሴቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'የዩ ኤስ ጠረፍ ላይ ያሉ ደሴቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'የገና ደሴት');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'የፈረንሳይ ደቡባዊ ግዛቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'የፈረንሳይ ጉዊአና');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'የፈረንሳይ ፖሊኔዢያ');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'የፋሮ ደሴቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'የፍልስጤም ግዛት');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'የፎልክላንድ ደሴቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'ዩክሬን');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'ዩዝበኪስታን');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'ዩጋንዳ');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'ደቡብ አፍሪካ');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'ደቡብ ኮሪያ');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'ደቡብ ጆርጂያ እና የደቡብ ሳንድዊች ደሴቶች');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'ዲዬጎ ጋርሺያ');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'ዴንማርክ');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'ዶሚኒካ');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'ዶሚኒክ ሪፑብሊክ');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'ጀርመን');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'ጀርሲ');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'ጂቡቲ');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'ጃማይካ');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'ጃፓን');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'ጆርዳን');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'ጆርጂያ');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'ጉርነሲ');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'ጉዋም');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'ጉዋቲማላ');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'ጉዋደሉፕ');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'ጉያና');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'ጊብራልታር');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'ጊኒ');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'ጋምቢያ');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'ጋቦን');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'ጋና');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'ግሪንላንድ');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'ግሪክ');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'ግሬናዳ');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'ግብጽ');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'ጣሊያን');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'ፈረንሳይ');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'ፊሊፒንስ');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'ፊንላንድ');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'ፊጂ');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'ፒትካኢርን');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'ፓላው');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'ፓራጓይ');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'ፓናማ');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'ፓኪስታን');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'ፓፑዋ ኒው ጊኒ');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'ፔሩ');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'ፖላንድ');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'ፖርቱጋል');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'ፖርታ ሪኮ');
