CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afganistan');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Åland Islands');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albani');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Almagn');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Alzeri');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andor');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anguilla');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Antarctica');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua-ek-Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Antiy neerlande');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armeni');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'Ascension Island');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Ayti');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azerbaïdjan');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahamas');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahreïn');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Banglades');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbad');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Belaris');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Beliz');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Belzik');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benin');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermid');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bilgari');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolivi');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosni-Herzegovinn');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botswana');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Boutan');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Bouvet Island');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brezil');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brunei');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burkina Faso');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'Canary Islands');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'Ceuta and Melilla');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Christmas Island');
INSERT INTO "country" ("id", "name") VALUES ('CP', 'Clipperton Island');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Cocos [Keeling] Islands');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Costa Rica');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Côte d\'Ivoire');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Cuba');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Cyprus');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Dannmark');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'Diego Garcia');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Djibouti');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominik');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekwater');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Emira arab ini');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Erythre');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Estoni');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'European Union');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Faroe Islands');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fidji');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filipinn');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finland');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'French Southern Territories');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabon');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambi');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Ghana');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Gine');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Gine ekwatoryal');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Gine-Bisau');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Greenland');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenad');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Gres');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadloup');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatemala');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Guernsey');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guyana');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Gwiyann franse');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Heard Island and McDonald Islands');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduras');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Hong Kong SAR China');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ikrenn');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indonezi');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Irak');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Iran');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Irland');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Island');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Isle of Man');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Itali');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Izrael');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Jersey');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kambodj');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamerounn');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Kap-Ver');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Katar');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazakstan');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenya');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirghizistan');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolonbi');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komor');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Koweit');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Kroasi');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Lafrans');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Lakore-dinor');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Lakore-disid');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Lamerik');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laos');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Larabi Saoudit');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Larenion');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Larisi');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Larzantinn');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Lasinn');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Lasiri');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Laswed');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Laswis');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Lata Vatikan');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Lenn');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Lespagn');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Letiopi');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Letoni');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Lezipt');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lezoto');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Liban');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberia');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libi');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Liechtenstein');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Lil Norfolk');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Lituani');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Lostrali');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Lostris');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luxembourg');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Macau SAR China');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagaskar');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malawi');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldiv');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malezi');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malt');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Marok');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martinik');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Masedwann');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayot');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mexik');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikronezi');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldavi');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monako');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongoli');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Montsera');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Moris');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Moritani');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mozambik');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Myanmar');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibi');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepal');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nicaragua');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niowe');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Nizer');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nizeria');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Norvez');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Nouvel Zeland');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Nouvel-Kaledoni');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Oland');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Oman');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Ongri');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Ouganda');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'Outlying Oceania');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Ouzbekistan');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakistan');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papouazi-Nouvel-Gine');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguay');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Perou');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitcairn');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Polinezi franse');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Pologn');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portigal');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Porto Rico');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Repiblik Chek');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Repiblik demokratik Kongo');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Repiblik dominikin');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Repiblik Lafrik Santral');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Roumani');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Rwanda');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'Saint Barthélemy');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'Saint Martin');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Saint-Christophe-ek-Niévès');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'Saint-Marin');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Saint-Pierre-ek-Miquelon');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Saint-Vincent-ek-Grenadines');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Sainte-Hélène');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Sainte-Lucie');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Salvador');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samoa');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Samoa amerikin');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'São Tome-ek-Prínsip');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegal');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Serbi-ek-Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Serbia');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Sesel');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Shili');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Sid-Afrik');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Sierra Leone');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapour');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slovaki');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Sloveni');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somali');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Soudan');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'South Georgia and the South Sandwich Islands');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Surinam');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Svalbard and Jan Mayen');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Swaziland');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tadjikistan');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taiwan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzani');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Tchad');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Teritwar Britanik Losean Indien');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Teritwar Palestinn');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Thayland');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Timor oriantal');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tinizi');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Tirki');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinite-ek-Tobago');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'Tristan da Cunha');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turkmenistan');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'U.S. Minor Outlying Islands');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'United Kingdom');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruguay');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezuela');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vietnam');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis-ek-Futuna');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Western Sahara');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Yemenn');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Zamaik');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambi');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Zapon');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Zeorzi');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Zibraltar');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Zil Cook');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Zil Kayman');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Zil malwinn');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Zil Marshall');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Zil Maryann dinor');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Zil Salomon');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Zil Tirk ek Caïcos');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Zil vierz britanik');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Zil Vierz Lamerik');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabwe');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Zordani');
