CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('VI', 'ABŞ Virqin Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Aland Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albaniya');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Almaniya');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Amerika Birləşmiş Ştatları');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Amerika Samoası');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andorra');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anquila');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Antarktika');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antiqua və Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Arqentina');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'Avropa Birləşliyi');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Avstraliya');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Avstriya');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azərbaycan');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamalar');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahreyn');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Banqladeş');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbados');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Belarus');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Belçika');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Beliz');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benin');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermuda');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Birləşmiş Ərəb Emiratları');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Birləşmiş Krallıq');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Birləşmiş Ştatların uzaq adaları');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Boliviya');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bolqariya');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosniya və Herzokovina');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botsvana');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Bove Adası');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Braziliya');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Britaniya Virgin Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Britaniya-Hindistan Okeanik territoriyası');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Bruney');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Butan');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Cezayır');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Cənub Afrika');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Cənub Gürcüstan və Cənub Sandvilç Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Cənub Koreya');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Ciboti');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Cörsi');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Çad');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Çex respublikası');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Çile');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Çin');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Çristmas Adası');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Danemarka');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Dominik Respublikası');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominika');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Efiopiya');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ekvador');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Ekvator Qineya');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'El Salvador');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritreya');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Ermənistan');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estoniya');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Əfqənistan');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Faro Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Fələstin Bölqüsü');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fici');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipin');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finlandiya');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Folkland Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Fransa');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Fransız Cənub teritoriyası');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Fransız Quyanası');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Fransız Polineziya');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Gibraltar');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Görnsey');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Gürcüstan');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haiti');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Hindistan');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Hollandiya');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Hollandiya antilleri');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Honk Konq çina');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'Hörd və Makdonald Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Xorvatiya');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'İndoneziya');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'İrak');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'İran');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'İrlandiya');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'İslandiya');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'İspaniya');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'isveç');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'isveçriya');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'İtaliya');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'İvori Sahili');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'İzrail');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kambodiya');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kamerun');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanada');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Kape Verde');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Kayman Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazaxstan');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenya');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kırqızstan');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Kipr');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Kokos Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolumbiya');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Komoros');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Konqo - Brazavil');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Konqo - Kinşasa');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kosta Rika');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kuba');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Kuk Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuveyt');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Qabon');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Qambiya');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Qana');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Qatar');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Qərb Sahara');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Qonduras');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Qrenada');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Qrinland');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Quam');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Quyana');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Qvadalup');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Qvatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Qvineya');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Qvineya-Bisau');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laos');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Latviya');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Lebanon');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesoto');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberiya');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libya');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Lixtenşteyn');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Litva');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Lüksemburq');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Macaristan');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madaqaskar');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Makao Çina');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malavi');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malaysiya');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maldiv');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Man Adası');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Marşal Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martiniqu');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Masedoniya');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mavritaniya');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Mavritis');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayot');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mazambik');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Meksika');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikronesiya');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Misir');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldova');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monako');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Monqoliya');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Monteneqro');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montserat');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Morokko');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myanmar');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibiya');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nauru');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepal');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'nijer');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nijeriya');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikaraqua');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niye');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Norfolk Adası');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norvec');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Oman');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Orta Afrika respublikası');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Özbəkistan');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistan');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palav');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papua Yeni Qvineya');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraqvay');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peru');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitkarn');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Polşa');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portuqal');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Puerto Riko');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Reyunion');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Romaniya');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rusiya');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Rvanda');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marino');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Sao Tom və Prinsip');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Saudi Ərəbistan');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Seneqal');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Serbiya');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seyçels');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Seynt Bartelemey');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Seynt Elena');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Seynt Kits və Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Seynt Lusiya');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Seynt Martin');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Seynt Piyer və Mikelon');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Seynt Vinsent və Qrenada');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Sinqapur');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'siriya');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Siyera Leon');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovakiya');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Sloveniya');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Solomon Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somaliya');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'sudan');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'surinamə');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'svalbard və yan mayen');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'svazilənd');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Şərq Timor');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Şimal Koreya');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Şimal Mariana Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Şri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'tacikistan');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'tanzaniya');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'tayland');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'tayvan');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Toqo');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonqa');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidan və Tobaqo');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunisiya');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Türk və Kaykos Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Türkiya');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Türkmənistan');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukraina');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uqanda');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruqvay');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'Uzak Okeyaniya');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Ürdün');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Valis və Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatikan');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venesuela');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vyetnam');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Yamayka');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Yaponiya');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yemen');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Yeni Kaledoniya');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Yeni Zelandiya');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Yunanıstan');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambiya');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabve');
