CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AL', 'Abhaniya');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afigándesitaŋ');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Afirika Kɔi Leŋŋɛ Lɔ');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Áfíríka Lumaã Tɛ Boloe');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Agiriya');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Áisi Lumaã');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Ajɛŋtína');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Améniya');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Aŋdóra');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Aŋgíla');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Aŋgóla');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Aŋtígwa Ɓahabhuda');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Áre Lumaã');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Arubha');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Avorekoo');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azabhaijaŋ');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahámasi');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Bhabhedo');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bhangiladɛ̀shi');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Bhanísiláila');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bharɛŋ');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Bheliz');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Bhɛgiyɔŋ');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Bhɛlarusi');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bhɛmuda');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Bhɛni');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Bhokina Fáso');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bholiviya');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Bhosuwana');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bhɔgeriya');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bhɔsiniya');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Bhurazeli');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Bhurundi');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Bhurunɛĩ');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Bhutaŋ');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Chádi');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Cháína');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Chéli');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Chɛki Boloe');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Danimaha');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Domíiníka');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Domíiníka Ɓoloe');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Dúúnyá Tɛ Giini');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ɛ́kúwédɔ');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Ɛlɛ Sávádɔ');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Ɛritera');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Ɛsitóninya');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Fáháki Luma Tiŋŋɛ');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Félepiŋ');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Fɛŋsi');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Fɛŋsi Giwana');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Fɛŋsi Polinísiya');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fíji');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Fiŋlɛŋ');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabhɔŋ');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambiya');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Gana');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Gbeya Bahawɔ');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Gini');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Gini Bhisawo');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Gurinéda');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guwadelupe');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guwami');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guwatɛmala');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guyana');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Háiti');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Hɛlɛŋ');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Hɔndura');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Hɔ́ngare');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Índiya');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Índonisiya');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Iraki');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Iraŋ');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Ítali');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Ítiyópiya');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Jamáĩ');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamaika');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Jamba Kuwa Lumaã');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japaŋ');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Jengéesi Bhɛɛ Lɔ Musu Tiŋŋɛ');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Jengéesi Gbawoe Índiya Kɔiyɛ Lɔ');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Jibhurata');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Jibhuti');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jɔɔdaŋ');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Jɔɔjiya');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Kalidoninya Námaá');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kameruŋ');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kánáda');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kaŋbhodiya');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Kataha');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazasitaŋ');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Keemaŋ Tiŋŋɛ');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kénya');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Kepi Vɛdi Tiŋŋɛ');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kigisitaŋ');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribhati');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kiyubha');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Kódivówa');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Kóki Tiŋŋɛ');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komorosi');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kóngo');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Koresiya');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Koriya Kɔi Kaŋndɔ');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Koriya Kɔi Leŋŋɛ Lɔ');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kósíta Ríko');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Kɔi Kaŋndɔ Mariyana Tiŋŋɛ');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kɔlɔmbiya');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kuweti');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Lahabu');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Laibhiya');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Lativiya');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Lawosi');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Lebhanɔ');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Lebhiya');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lisóto');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Lituweninya');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Lusimbɔ');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagasita');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malawi');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malesiya');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Malidavi');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malita');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Masedoninya');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Masha Tiŋŋɛ');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Matiniki');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mavote');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mɛsíko');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikonisiya');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Míséla');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Miyamaha');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mozambiki');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Mɔlidova');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Mɔnako');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mɔngoliya');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Mɔreshɔ');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mɔretaninya');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Mɔroko');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Mɔserati');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Naĩja');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Naĩjiriya');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibiya');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepa');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Nidɔlɛŋ');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Nidɔlɛŋ Aŋtili');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikaraguwa');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niwe');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Noru');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Nɔfɔ Tiŋŋɛ');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Nɔɔwe');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Omaŋ');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Ɔ́situwa');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Ɔsituwéeliya');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakisitaŋ');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palesitininya Tele Jii Kɔiyɛ lá hĩ Gaza');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palo');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Panyɛĩ');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papuwa Gini Námaá');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paragɔe');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Pɛru');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitikɛŋ');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Piyuto Riko');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Pólɛŋ');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Poo');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Poo Bhɛɛ lɔ Musu Tiŋŋɛ');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Poo Sambowa');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Potokíi');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Rawunda');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Renyɔɔ̃');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Romininya');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Rɔshiya');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Saɛpurɔ');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samowa');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'Saŋ Marindo');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sawo Tombe ɓɛ a Gbawoe');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Seshɛɛ');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Sɛbiya ɓɛ Mɔŋteniguro');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Síingapoo');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Sinigaha');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Siŋ Hɛlina');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Siŋ Kisi ɓɛ́ Nevisi');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Siŋ Lusiya');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Siŋ Piiyɛ ɓɛ́ Mikelɔŋ');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Siŋ Viŋsi');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Síyaŋ');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somaliya');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudɛŋ');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Sulaimaãna Tiŋŋɛ');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Sulovakiya');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Suloveninya');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Suri Laŋka');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Surinambe');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Suwazi Lumaã');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Suweza Lumaã');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Suwidɛŋ');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Tai Lumaã');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taiwaŋ');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tajikisitaŋ');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Taŋzaninya');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Tele Ɓɔ́ Timɔɔ̃');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelo');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tɔnga');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Tɔ́ɔ́ki');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Tukimɛnisitaŋ');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Tukisi ɓɛ̀ Kaikóosi Tiŋŋɛ');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunisiya');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Turindeda ɓɛ́ Tobhego');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuválu');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuwátu');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikaŋ Ɓoloe');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Vɛnɛzuwela');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Viyanami');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Walísi');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Yemɛni');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Yubhɛkisitaŋ');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Yuganda');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Yukuréŋ');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Yunaitɛ Arabhi Ɛmire');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Yunaitɛ Kíŋdɔŋ');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Yuwegɔwe');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambiya');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Zilɛŋ Námaá');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabhuwe');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'ꔷꗿꘋꔻꗳꘋ');
