CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Австралия');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Австрия');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Азербайджан');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Аландски о-ви');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Албания');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Алжир');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Американско Самоа');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Ангола');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Ангуила');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Андора');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Антарктика');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Антигуа и Барбуда');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Аржентина');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Армения');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Аруба');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Афганистан');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Бангладеш');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Барбадос');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Бахами');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Бахрейн');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Беларус');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Белгия');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Белиз');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Бенин');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Бермуда');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Боливия');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Босна и Херцеговина');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Ботсуана');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Бразилия');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Британски Вирджински острони');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Британски територии в Индийския океан');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Бруней Дарусалам');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Бряг на слоновата кост');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Буркина Фасо');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Бурунди');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Бутан');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'България');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Вануату');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Венецуела');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Виетнам');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Габон');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Гамбия');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Гана');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Гваделупа');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Гватемала');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Гвиана');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Гвинея');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Гвинея-Бисау');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Германия');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Гибралтар');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Гренада');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Гренландия');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Грузия');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Гуам');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Гърция');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Дания');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Демократична република Конго');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Джибути');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Диего Гарсия');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Доминика');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Доминиканска република');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'Европейски съюз');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Египет');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Еквадор');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Екваториална Гвинея');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Ел Салвадор');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Еритрея');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Естония');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Етиопия');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Замбия');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Западна Сахара');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Зимбабве');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Израел');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Източен Тимор');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Индия');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Индонезия');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Ирак');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Иран, Ислямска република');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Ирландия');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Исландия');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Испания');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Италия');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Йемен');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Йордания');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Кабо Верде');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Казахстан');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Кайманови острови');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Камбоджа');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Камерун');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Канада');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Канарски острови');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Катар');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Кения');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Кипър');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Киргизстан');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Кирибати');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Китай');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Кокосови [Кийлинг] острови');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Колумбия');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Комори');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Конго');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Корея, Южна');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Коста Рика');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Куба');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Кувейт');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Латвия');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Лесото');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Либерия');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Либийска арабска джамахирия');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Ливан');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Литва');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Лихтенщайн');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Люксембург');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Мавритания');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Мавриций');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Мадагаскар');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Макао О.А.Р. на Китай');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Македония');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Малави');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Малайзия');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Малдиви');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Мали');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Малта');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Мароко');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Мартиника');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Маршалови острови');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Мейот');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Мексико');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Мианмар [Бирма]');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Микронезия, Обединени Щати');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Мозамбик');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Молдова, Република');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Монако');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Монголия');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Монсерат');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Намибия');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Народна демократична република Лаос');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Науру');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Непал');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Нигер');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Нигерия');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Никарагуа');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Ниуе');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Нова Зеландия');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Нова Каледония');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Норвегия');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'о. Гърнзи');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'о. Джързи');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Обединени арабски емирства');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Обединено кралство');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'Океания [QO]');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Оман');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Остров Буве');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Остров Възнесение');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'Остров Клипертон');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Остров Кристмас');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Остров Норфолк');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'Остров Хърд и Острови Макдоналд');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Острови Кук');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Острови Ман');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Острови Туркс и Кайкос');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Пакистан');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Палау');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Палестински територии');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Панама');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Папуа Нова Гвинея');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Парагвай');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Перу');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Питкайрн');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Полша');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Португалия');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Пуерто Рико');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Реюниън');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Руанда');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Румъния');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Руска федерация');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Самоа');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'Сан Марино');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Сао Томе и Принципе');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Саудитска Арабия');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'САЩ');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'САЩ - външни острови');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'САЩ, Вирджински острови');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Свалбард и Ян Майен');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Света Елена');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Свещено море [Ватиканска държава]');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Северна Корея');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Северни Мариански Острови');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Сейнт Бартоломей');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Сейнт Винсънт и Гренадини');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Сейнт Китс и Невис');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Сейнт Лусия');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Сейнт Мартин');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Сейшели');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Сен Пиер и Мигелон');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Сенегал');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Сеута и Мелия');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Сиера Леоне');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Сингапур');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Сирийска арабска република');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Словакия');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Словения');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Соломонови острови');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Сомалия');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Суазиленд');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Судан');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Суринам');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Сърбия');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Сърбия и Черна гора');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Таджикистан');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Тайван');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Тайланд');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Танзания');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Того');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Токелау');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Тонга');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Тринидад и Тобаго');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Тристан да Куня');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Тувалу');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Тунис');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Туркменистан');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Турция');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Уганда');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Узбекистан');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Украйна');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Унгария');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Уолис и Футуна');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Уругвай');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Фарьорски острови');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Фиджи');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Филипини');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Финландия');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Фолклендски острови');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Франция');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Френска Гвиана');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Френска Полинезия');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Френски южни територии');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Хаити');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Холандия');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Холандски Антили');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Хонг-Конг О.А.Р. на Китай');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Хондурас');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Хърватска');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Централноафриканска Република');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Чад');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Черна гора');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Чешка република');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Чили');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Швейцария');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Швеция');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Шри Ланка');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Южна Африка');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Южна Джорджия и Южни Сандвичеви Острови');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Ямайка');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Япония');
