CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afɣanistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Agemmaḍ Ugut d Ɣazza Ifilisṭiniyen');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Åland Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albanya');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Almanya');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Amur n Agaraw Uhindi Ubṛiṭani');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Anḍurra');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angula');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Angwilla');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Antarctica');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigwa d Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Antil Tihulanḍiyyin');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Arjuntin');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Arminya');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'Ascension Island');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Awank iɣrem n Vatikan');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azerbiǧan');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamas');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Baḥrayn');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladic');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbadus');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Belɣarya');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Beljika');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Bilarusya');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Biliz');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Binin');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Birmuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'Bouvet Island');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Bṛazil');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunay');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bulivya');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Fasu');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Busna-d-Hirsik');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Buṭan');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Butswana');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'Canary Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Ccili');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'Ceuta and Melilla');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Christmas Island');
INSERT INTO `country` (`id`, `name`) VALUES ('CP', 'Clipperton Island');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'Cocos [Keeling] Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Danmark');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'Diego Garcia');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Ḍuminika');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Dzayer');
INSERT INTO `country` (`id`, `name`) VALUES ('EU', 'European Union');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Ɛiraq');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Ɛumman');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Faroe Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fiji');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filippin');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finlanḍa');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Fṛansa');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'French Southern Territories');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabun');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambya');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Ǧibuti');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grinada');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Grinlanḍa');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'Guernsey');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Guyana Tafransist');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Gwadalup');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Gwam');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Gwatimala');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ɣana');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Ɣinya');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Ɣinya Tikwaṭur it');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Ɣinya-Bissaw');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Hayti');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'Heard Island and McDonald Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Henɣarya');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Hind');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Hinduras');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'Hong Kong SAR China');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Hulanḍa');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ikwaḍur');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Imarat Tiεrabin Tidduklin');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indunizya');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iran');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Iritrya');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irlanḍa');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Islanḍa');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'Isle of Man');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Israeil');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Isṭunya');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Iṭalya');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Ityupya');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Iwunak Idduklen n Amirika');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamayka');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'Jersey');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Jibralṭar');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Jjappun');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Jyurjya');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'kalidunya Tamaynut');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambudj');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kamerun');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazaxistan');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kinya');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirɣistan');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Krwatya');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'kuba');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kulumbya');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kungu');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Kurya Tugafat');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Kurya Tunẓult');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Kusṭa Rika');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuwwayt');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laws');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Libirya');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libya');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Lictencṭayn');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Liksumburg');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lisuṭu');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Liṭṭunya');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Litwanya');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Lubnan');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Macau SAR China');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madaɣacqar');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldiv');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malizya');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malṭa');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Manɣulya');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Maqdunya');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinik');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayuṭ');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Meṛṛuk');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikrunizya');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Miksik');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Miṣr');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Mulḍavya');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Munaku');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Muntsirra');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Muris');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Muritanya');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Muzambiq');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Myanmar');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibya');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nawru');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nijiria');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikaragwa');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nippal');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niwi');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Nnijer');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Nnurwij');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'Outlying Oceania');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palu');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papwa Ɣinya Tamaynut');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paragway');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Piru');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitkirn');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Pulinizya Tafransist');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Pulunya');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Purtuɣal');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Purturiku');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Qaṭar');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Qubrus');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Qumur');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Riyyunyun');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Ṛumanya');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Rusya');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Ruwwanḍa');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'Saint Barthélemy');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'Saint Martin');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Salvaḍur');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samwa');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Samwa Imirikaniyyin');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Sanɣafura');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'Sanmarinu');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Santehilin');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Santekits d Nivis');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Santelusya');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Santepyir d Mikelun');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Santevinsent d Grinadin');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Sawṭumi d Prinsip');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Sbanya');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Serbia');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Siralyun');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Ṣiṛbya d Muntinigru');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Sluvakya');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Sluvinya');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'South Georgia and the South Sandwich Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Srilanka');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Ssaεudiyya Taεrabt');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Ssewwid');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Ssicil');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Ṣṣin');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Ssiniɣal');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Ssudan');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Ṣṣumal');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Surinam');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Surya');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Svalbard and Jan Mayen');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Swazilanḍa');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Swisra');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Tafrikt Tunẓul');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Tagduda n Afrika Wammas');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Tagduda n Čik');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Tagduda n Ḍuminikan');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Tagduda Tadimuqraṭit n Kungu');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Tagelda Taddukelt');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Ṭaǧikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Taɣazut n Uszer');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Ṭanzanya');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Ṭaylanḍa');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Ṭaywan');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Tcad');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Tigzirin (Virgin) Tibṛiṭaniyin');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Tigzirin n Falkland');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Tigzirin n Iɣf Uzegzaw');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Tigzirin n Kayman');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Tigzirin n Kuk');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Tigzirin n Marcal');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Tigzirin n Maryana Tugafat');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Tigzirin n Salumun');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Tigzirin n Virjin n Iwunak Yedduklen');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Tigzirin Turkiyyin d Tikaykusin');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Tigzirt Nurfulk');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Timur Tagmuṭ');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad d Ṭubagu');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Ṭṭugu');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tuklu');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunes');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Ṭunga');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmanistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Turkya');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Ṭuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'U.S. Minor Outlying Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uɣanda');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukranya');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Urḍun');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Urugway');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Usṭralya');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Ustriyya');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzbakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanwatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Vinzwilla');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Viṭnam');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Walis d Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Western Sahara');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Yaman');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Yunan');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambya');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Zilanḍa Tamaynut');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwi');
