CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AO', 'अंगोला');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'अंटार्कटिका');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'अज़रबैजान');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'अफ़गानिस्तान');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'अमेरिकी समोआ');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'अरूबा');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'अर्जेंटीना');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'अल सल्वाडोर');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'अल्जीरिया');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'अल्बानिया');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'असेंशन द्वीप');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'आइल ऑफ़ मैन');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'आइसलैंड');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'आयरलैंड');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'आर्मेनिया');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'इंडोनेशिया');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'इक्वाडोर');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'इक्वेटोरियल गिनी');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'इटली');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'इथियोपिया');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'इराक');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'इरिट्रिया');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'इसराइल');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'ईरान');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'उज़्बेकिस्तान');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'उत्तर कोरिया');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'उत्तरी मारियाना द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'उरूग्वे');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'एंग्विला');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'एंटिगुआ और बरबुडा');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'एंडोरा');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'एलैंड द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'एस्टोनिया');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'ऑस्ट्रिया');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'ऑस्ट्रेलिया');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'ओमान');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'कंबोडिया');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'कज़ाखस्तान');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'क़तर');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'कनाडा');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'कांगो - किंशासा');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'कांगो – ब्राज़ाविल');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'किरिबाती');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'किर्गिज़स्तान');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'कुक द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'कुवैत');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'केन्या');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'केप वर्ड');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'केमैन द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'कैनेरी द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'कैमरून');
INSERT INTO [country] ([id], [name]) VALUES ('BQ', 'कैरिबियन नीदरलैंड');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'कोकोस (कीलिंग) द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'कोट डी आइवर');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'कोमोरोस');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'कोलंबिया');
INSERT INTO [country] ([id], [name]) VALUES ('XK', 'कोसोवो');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'कोस्टारिका');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'क्यूबा');
INSERT INTO [country] ([id], [name]) VALUES ('CW', 'क्यूरासाओ');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'क्रिसमस द्वीप');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'क्रोएशिया');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'गयाना');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'गर्नसी');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'गाम्बिया');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'गिनी');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'गिनी-बिसाउ');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'गुआम');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'गैबॉन');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'ग्रीनलैंड');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'ग्रेनाडा');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'ग्वाटेमाला');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'ग्वाडेलूप');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'घाना');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'चाड');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'चिली');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'चीन');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'चेक गणराज्य');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'जमैका');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'जर्मनी');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'जर्सी');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'जापान');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'ज़ाम्बिया');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'जिबूती');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'जिब्राल्टर');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'ज़िम्बाब्वे');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'जॉर्जिया');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'जॉर्डन');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'टोंगा');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'टोगो');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'ट्यूनीशिया');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'डिएगो गार्सिया');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'डेनमार्क');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'डोमिनिकन गणराज्य');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'डोमिनिका');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'तंज़ानिया');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'ताइवान');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'ताजिकिस्तान');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'तिमोर-लेस्त');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'तुर्क और कैकोज़ द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'तुर्कमेनिस्तान');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'तुर्की');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'तुवालू');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'तोकेलाउ');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'त्रिनिदाद और टोबैगो');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'त्रिस्टान डा कुना');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'थाईलैंड');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'दक्षिण अफ़्रीका');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'दक्षिण कोरिया');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'दक्षिण जॉर्जिया और दक्षिण सैंडविच द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('SS', 'दक्षिण सूडान');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'नाइजर');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'नाइजीरिया');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'नाउरु');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'नामीबिया');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'निकारागुआ');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'नीदरलैंड');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'नीयू');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'नेपाल');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'नॉरफ़ॉक द्वीप');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'नॉर्वे');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'न्यू कैलेडोनिया');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'न्यूज़ीलैंड');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'पनामा');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'पलाऊ');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'पश्चिमी सहारा');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'पाकिस्तान');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'पापुआ न्यू गिनी');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'पिटकैर्न द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'पुर्तगाल');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'पेराग्वे');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'पेरू');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'पोर्टो रिको');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'पोलैंड');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'फ़िजी');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'फ़िनलैंड');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'फ़िलिपींस');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'फ़िलिस्तीनी क्षेत्र');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'फ़ेरो द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'फ़ॉकलैंड द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'फ़्रांस');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'फ़्रांसीसी दक्षिणी क्षेत्र');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'फ़्रेंच गयाना');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'फ़्रेंच पोलिनेशिया');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'बरमूडा');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'बहरीन');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'बहामास');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'बांग्लादेश');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'बारबाडोस');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'बुरुंडी');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'बुर्किना फ़ासो');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'बुल्गारिया');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'बेनिन');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'बेलारूस');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'बेलीज़');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'बेल्जियम');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'बोत्स्वाना');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'बोलीविया');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'बोस्निया और हर्ज़ेगोविना');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'ब्राज़ील');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'ब्रिटिश वर्जिन द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'ब्रिटिश हिंद महासागरीय क्षेत्र');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'ब्रूनेई');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'भारत');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'भूटान');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'मंगोलिया');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'मकाऊ (विशेष प्रशासनिक क्षेत्र चीन)');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'मध्य अफ़्रीकी गणराज्य');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'मलावी');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'मलेशिया');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'माइक्रोनेशिया');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'मायोते');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'मार्टीनिक');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'मार्शल द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'मालदीव');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'माली');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'माल्टा');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'मिस्र');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'मेडागास्कर');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'मैक्सिको');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'मैसिडोनिया');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'मॉरिटानिया');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'मॉरिशस');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'मॉल्डोवा');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'मोंटसेरात');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'मोंटेनेग्रो');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'मोज़ांबिक');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'मोनाको');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'मोरक्को');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'म्यांमार (बर्मा)');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'यमन');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'युगांडा');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'यू.एस. आउटलाइंग द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'यू.एस. वर्जिन द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'यूक्रेन');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'यूनाइटेड किंगडम');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'यूनान');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'रवांडा');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'रियूनियन');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'रूस');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'रोमानिया');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'लग्ज़मबर्ग');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'लाइबेरिया');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'लाओस');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'लातविया');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'लिचेंस्टीन');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'लिथुआनिया');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'लीबिया');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'लेबनान');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'लेसोथो');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'वनुआतू');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'वालिस और फ़्यूचूना');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'वियतनाम');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'वेटिकन सिटी');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'वेनेज़ुएला');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'श्रीलंका');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'संयुक्त अरब अमीरात');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'संयुक्त राज्य');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'सऊदी अरब');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'समोआ');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'सर्बिया');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'साइप्रस');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'साओ टोम और प्रिंसिपे');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'सिंगापुर');
INSERT INTO [country] ([id], [name]) VALUES ('SX', 'सिंट मार्टिन');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'सिएरा लियोन');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'सीरिया');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'सूडान');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'सूरीनाम');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'सेंट किट्स और नेविस');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'सेंट पिएरे और मिक्वेलान');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'सेंट बार्थेलेमी');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'सेंट मार्टिन');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'सेंट लूसिया');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'सेंट विंसेंट और ग्रेनाडाइंस');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'सेंट हेलेना');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'सेउटा और मेलिला');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'सेनेगल');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'सेशेल्स');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'सैन मेरीनो');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'सोमालिया');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'सोलोमन द्वीपसमूह');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'स्पेन');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'स्लोवाकिया');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'स्लोवेनिया');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'स्वाज़ीलैंड');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'स्वालबार्ड और जान मायेन');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'स्विट्ज़रलैंड');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'स्वीडन');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'हंगरी');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'हाँग काँग (चीन विशेष प्रशासनिक क्षेत्र)');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'हैती');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'होंडूरास');
