CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AW', 'آروبا');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'أذربيجان');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'أرمينيا');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'أريتريا');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'أستراليا');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'أستونيا');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'أفغانستان');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'ألبانيا');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'ألمانيا');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'أنتيغوا وبربودا');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'أندورا');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'أنغولا');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'أنغويلا');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'أورغواي');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'أوزبكستان');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'أوغندا');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'أوقيانوسيا النائية');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'أوكرانيا');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'أيرلندا');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'أيسلندا');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'إثيوبيا');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'إسبانيا');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'إسرائيل');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'إيران');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'إيطاليا');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'الأرجنتين');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'الأردن');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'الإقليم البريطاني في المحيط الهندي');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'الإكوادور');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'الإمارات العربية المتحدة');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'الاتحاد الأوروبي');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'الباهاما');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'البحرين');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'البرازيل');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'البرتغال');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'البوسنة والهرسك');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'الجابون');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'الجبل الأسود');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'الجزائر');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'الدانمرك');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'الرأس الأخضر');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'السلفادور');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'السنغال');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'السودان');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'السويد');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'الصحراء الغربية');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'الصومال');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'الصين');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'العراق');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'الفاتيكان');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'الفيلبين');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'القطب الجنوبي');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'الكاميرون');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'الكونغو - برازافيل');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'الكونغو - كينشاسا');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'الكويت');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'المغرب');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'المقاطعات الجنوبية الفرنسية');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'المكسيك');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'المملكة العربية السعودية');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'المملكة المتحدة');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'النرويج');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'النمسا');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'النيجر');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'الهند');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'الولايات المتحدة الأمريكية');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'اليابان');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'اليمن');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'اليونان');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'اندونيسيا');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'بابوا غينيا الجديدة');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'باراغواي');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'باكستان');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'بالاو');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'بتسوانا');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'بربادوس');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'برمودا');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'بروناي');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'بلجيكا');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'بلغاريا');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'بليز');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'بنجلاديش');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'بنما');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'بنين');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'بوتان');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'بورتوريكو');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'بوركينا فاسو');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'بوروندي');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'بولندا');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'بوليفيا');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'بولينيزيا الفرنسية');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'بيرو');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'تانزانيا');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'تايلند');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'تايوان');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'تركمانستان');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'تركيا');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'تريستان دي كونها');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'ترينيداد وتوباغو');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'تشاد');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'توجو');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'توفالو');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'توكيلو');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'تونس');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'تونغا');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'تيمور الشرقية');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'جامايكا');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'جبل طارق');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'جزر أولان');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'جزر الأنتيل الهولندية');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'جزر الترك وجايكوس');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'جزر القمر');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'جزر الكايمن');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'جزر الكناري');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'جزر المارشال');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'جزر المالديف');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'جزر الولايات المتحدة البعيدة الصغيرة');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'جزر بيتكيرن');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'جزر سليمان');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'جزر فارو');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'جزر فرجين الأمريكية');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'جزر فرجين البريطانية');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'جزر فوكلاند');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'جزر كوك');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'جزر كوكوس');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'جزر ماريانا الشمالية');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'جزر والس وفوتونا');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'جزيرة أسينشيون');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'جزيرة الكريسماس');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'جزيرة بوفيه');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'جزيرة كليبيرتون');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'جزيرة مان');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'جزيرة نورفوك');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'جزيرة هيرد وجزر ماكدونالد');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'جمهورية أفريقيا الوسطى');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'جمهورية التشيك');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'جمهورية الدومينيك');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'جنوب أفريقيا');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'جوادلوب');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'جورجيا');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'جورجيا الجنوبية وجزر ساندويتش الجنوبية');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'جيبوتي');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'جيرسي');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'دومينيكا');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'دييغو غارسيا');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'رواندا');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'روسيا');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'روسيا البيضاء');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'رومانيا');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'روينيون');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'زامبيا');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'زيمبابوي');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'ساحل العاج');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'ساموا');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'ساموا الأمريكية');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'سان بارتليمي');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'سان مارينو');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'سانت بيير وميكولون');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'سانت فنسنت وغرنادين');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'سانت كيتس ونيفيس');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'سانت لوسيا');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'سانت مارتين');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'سانت هيلنا');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'ساو تومي وبرينسيبي');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'سريلانكا');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'سفالبارد وجان مايان');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'سلوفاكيا');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'سلوفينيا');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'سنغافورة');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'سوازيلاند');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'سوريا');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'سورينام');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'سويسرا');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'سيراليون');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'سيشل');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'سيوتا وميليلا');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'شيلي');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'صربيا');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'صربيا والجبل الأسود');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'طاجكستان');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'عُمان');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'غامبيا');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'غانا');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'غرينادا');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'غرينلاند');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'غواتيمالا');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'غوام');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'غويانا الفرنسية');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'غيانا');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'غيرنزي');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'غينيا');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'غينيا الاستوائية');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'غينيا بيساو');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'فانواتو');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'فرنسا');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'فلسطين');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'فنزويلا');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'فنلندا');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'فيتنام');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'فيجي');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'قبرص');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'قرغيزستان');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'قطر');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'كازاخستان');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'كاليدونيا الجديدة');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'كرواتيا');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'كمبوديا');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'كندا');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'كوبا');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'كوريا الجنوبية');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'كوريا الشمالية');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'كوستاريكا');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'كولومبيا');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'كيريباتي');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'كينيا');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'لاتفيا');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'لاوس');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'لبنان');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'لوكسمبورغ');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'ليبيا');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'ليبيريا');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'ليتوانيا');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'ليختنشتاين');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'ليسوتو');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'مارتينيك');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'مالطا');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'مالي');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'ماليزيا');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'مايوت');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'مدغشقر');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'مصر');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'مقدونيا');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'مكاو الصينية [منطقة إدارية خاصة]');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'ملاوي');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'منغوليا');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'موريتانيا');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'موريشيوس');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'موزمبيق');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'مولدافيا');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'موناكو');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'مونتسرات');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'ميانمار -بورما');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'ميكرونيزيا');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'ناميبيا');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'ناورو');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'نيبال');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'نيجيريا');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'نيكاراغوا');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'نيوزيلاندا');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'نيوي');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'هايتي');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'هندوراس');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'هنغاريا');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'هولندا');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'هونغ كونغ الصينية');
