CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ZZ', 'Unknown or Invalid Region');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'آئر لینڈ');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'آئس لینڈ');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'آذر بائجان');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'آر مینیا');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'آسٹریا');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'آسٹریلیا');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'ارجنٹینا');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'اردن');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'اریٹیریا');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'ازبکستان');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'استوائی گنی');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'اسرائیل');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'افغانستان');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'البانیا');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'الجیریا');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'امریکی ساموا');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'انٹار ٹکا');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'انٹیگوا اور باربودا');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'انڈونیشیا');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'انگولا');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'اٹلی');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'ایتھوپیا');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'ایران');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'ایسٹونیا');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'ایکواڈور');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'باھا ماس');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'بحرھند کا برٹش علاقہ');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'برازیل');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'برطانیہ');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'برنڈی');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'برکینا فاسو');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'بلغاریہ');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'بنگلا دیش');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'بوسنیا ہرزگوینا');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'بولیویا');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'بوٹسوانا');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'بھارت');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'بھوٹان');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'بیلا رس');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'بیلجئیم');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'بینن');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'تائیوان');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'تاجکستان');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'ترکمانستان');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'ترکی');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'تنزانیہ');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'تونگا');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'تھائی لینڈ');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'تیونس');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'جارجیا');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'جاپان');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'جرسی');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'جرمنی');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'جزائر فاک لینڈ');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'جزائر مارشل');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'جزائر ورجن، امریکہ');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'جزائر ورجن، برٹش');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'جزائر کوکوز');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'جزائر کُک');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'جزائر کیمن');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'جزائر کیکس اور ترکیّہ');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'جزائرسولمون');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'جزائرفارو');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'جزیرہ بووٹ');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'جزیرہ نارفولک');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'جزیرہ کرسمس');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'جزیرہ ہرڈ اور جزائر مکڈونلڈ');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'جمہوریہ وسطی افریقہ');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'جمہوریہ چیک');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'جنوبی افریقہ');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'جنوبی جارجیا اور جزائر جنوبی سینڈوچ');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'جنوبی فرانسیسی علاقہ جات');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'جنوبی کوریا');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'روانڈا');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'روس');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'رومانیہ');
INSERT INTO "country" ("id", "name") VALUES ('US', 'ریاست ہائے متحدہ امریکا');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'ریاست ہائے متحدہ اور بیرونی جزائر');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'زمبابوے');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'زیمبیا');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'ساموا');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'سان میرینو');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'سربیا اور مانٹینیگرو');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'سری لنکا');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'سعودی عرب');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'سلوانیہ');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'سلوواکیہ');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'سوئزر لینڈ');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'سوازی لینڈ');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'سورینام');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'سوڈان');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'سویڈن');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'سپین');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'سیرالیون');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'سیریا');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'سینٹ لوسیا');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'سینٹ پائرے اور میکویلون');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'سینٹ کٹس اور نیوس');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'سینٹ کیرن اور گریناڈائنز');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'سینٹ ھیلینا');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'سینیگال');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'سے شلز');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'شمالی ماریاناجزائر');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'شمالی کوریا');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'صوپالیہ');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'عراق');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'عمان');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'غیبون');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'فرانس');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'فرانسیسی پولینیسیا');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'فرانسیسی گی آنا');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'فلسطین');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'فلپائن');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'فن لینڈ');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'قبرص');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'قزاقستان');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'لاؤس');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'لائبیریا');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'لبنان');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'لتھوانیا');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'لٹوِیا');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'لکٹنسٹائن');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'لیبیا');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'لیسوتھو');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'مائکرونیزیا');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'مالدووا');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'مالی');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'ماکاؤ');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'متحدہ عرب امارات');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'مراکش');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'مشرقی تیمور');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'مصر');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'مغربی صحارا');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'مقدونیہ');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'ملائیشیا');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'ملاوی');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'منگولیا');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'موریطانیہ');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'موزنبیق');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'مڈغاسکر');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'میانمر');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'میکسیکو');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'نائیجر');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'نائیجیریا');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'ناروے');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'نمیبیا');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'نکاراگوا');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'نیدرلینڈ');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'نیدرلینڈز انٹیلیز');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'نیو کیلیڈونیا');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'نیوزی لینڈ');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'نیپال');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'والس اور فتونہ');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'وانواٹو');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'ویت نام');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'وینزولا');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'ویٹیکن سٹی');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'ٹرینیڈاڈ اور ٹوباگو');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'ٹوالو');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'ٹوکیلاؤ');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'ٹوگو');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'پاپوا نیو گنی');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'پاکستان');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'پرتگال');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'پولینڈ');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'پیراگوئے');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'پیرو');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'چاڈ');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'چلی');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'چین');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'ڈنمارک');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'ڈومینیکن ریپبلک');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'کانگو');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'کانگو، جمہوری ریاست');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'کرغستان');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'کروشیا');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'کمبوڈیا');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'کولمبیا');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'کوموروس');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'کِرباتی');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'کیمرون');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'کینیا');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'کینیڈا');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'کیوبا');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'گرنزی');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'گرین لینڈ');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'گنی');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'گنی بسائو');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'گھانا');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'گیمبیا');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'ہائٹی');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'ہنگری');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'ہوراگوئے');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'ہونڈوراس');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'یمن');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'یونان');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'یوکرائن');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'یوگنڈا');
