CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'afghanistaŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Afrika nekǝsǝŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'albaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'algeriya');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Amerika');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'andorra');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'anglofoŋ ma Indiya');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'anguiya');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'antiguan ne Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'argentiniya');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'armeniya');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'australiya');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'austriya');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'azerbaijaŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'bahamas');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'bahraiŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'bangladeshiya');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'barbadiya');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'belarussiya');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'belgika');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'beliziya');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'beniŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'bermudiya');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'boliviya');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'bosniya ne Herzegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'brazilya');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'bruniya');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'bulgariya');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'butaŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'centrafrika');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Daŋmark');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Djibouti');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominik');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ekwatǝr');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Espaŋiya');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estoniya');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Etiopia');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filipiŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Franssǝ');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gaboŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambiya');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Gana');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Georgiya');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Germaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenadǝ');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Guine');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Guine ma Bissao');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Gwam');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Gwatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Hungriya');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonesiya');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Irak');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iraŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italiya');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaika');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japaŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Kaledoniya mafuu');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'kambodiya');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'kameruŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'kap ma laŋne');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Katar');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'kayman ma laŋne');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazakstaŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirgizstaŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'kolombiya');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'komora');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'kook ma laŋne');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'kosta Rika');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'kroatiya');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kuba');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Letoniya');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libaŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberiya');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libiya');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Lichtǝnsteiŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Lituaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Macedoniya');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagaskar');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malaysiya');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldivǝ');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Marok');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinika');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauritaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayot');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Mexiko');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Micronesiya');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldoviya');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monako');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongoliya');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambika');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibiya');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigeriya');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikaragwa');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niwe');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Norfolk ma laŋne');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norvegǝ');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Omaŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistaŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papuasiya Guine mafuu');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paragwai');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitkairn');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Pologŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Porto Riko');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Russiya');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Rwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Saichel');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'samoa Amerika');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Sao Tome ne Principe');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegal');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'ser Anglofon ma laŋne');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'ser Ivoiriya');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Serbiya ne Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Sǝr amerika ma laŋne');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Sǝr Anglofoŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Sǝr Arabiya');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Sǝr Arabiya ma taini');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Sǝr Dominik ma lii');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Sǝr Egypt');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Sǝr Eritre');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Sǝr Fiji');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Sǝr Finland');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Sǝr Gibraltar');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Sǝr Grek');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Sǝr Groenland');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Sǝr Guine');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Sǝr Guyana ma Franssǝ');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Sǝr Gwadeloupǝ');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Sǝr Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Sǝr Helena');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Sǝr Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Sǝr Indǝ');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Sǝr Ireland');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Sǝr Island');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Sǝr Israel');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Sǝr Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Sǝr Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Sǝr Kongo ma dii ne zair');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Sǝr Kore fah sǝŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Sǝr Kore nekǝsǝŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Sǝr Kowait');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Sǝr Kristof ne Nievǝ');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sǝr Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Sǝr Laos');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Sǝr Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Sǝr Lucia');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Sǝr Luxemburg');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Sǝr ma kasǝŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Sǝr ma kasǝŋ ma laŋne');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Sǝr Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Sǝr Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Sǝr malouniya ma laŋne');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Sǝr Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Sǝr Maria ma laŋne');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'Sǝr Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Sǝr Marshall ma laŋne');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Sǝr Mauricǝ');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Sǝr Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Sǝr Myanmar');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Sǝr Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Sǝr Nepal');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Sǝr Niger');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Sǝr Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Sǝr Palestiniya');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Sǝr Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Sǝr Pǝtar ne Mikǝlon');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Sǝr Polynesiya ma Franssǝ');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Sǝr Portugal');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Sǝr Reunion');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Sǝr Salomon ma laŋne');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Sǝr Salvador');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Sǝr Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Sǝr Sued');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Sǝr Surinam');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Sǝr Swaziland');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Sǝr Swiss');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Sǝr Syek');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Sǝr Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Sǝr Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Sǝr Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Sǝr Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Sǝr Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Sǝr Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Sǝr Vietnam');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Sǝr Vinceŋ ne Grenadiŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sierra Leonǝ');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapur');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Slovakiya');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Sloveniya');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somaliya');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudaŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'syad');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'syili');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'syiŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Syipriya');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Syria');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Tailand');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwaŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tajikistaŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Timoriya');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinite ne Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunisiya');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Turkiya');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Turkiya ne kaicos ma laŋne');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenistaŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukraiŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Urugwai');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzbekistaŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vaticaŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis ne Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Yemeŋ');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambiya');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Zeland mafuu');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
