CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afghánistán');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Alandy');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albánie');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Alžírsko');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Americká Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Americké Panenské ostrovy');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andorra');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguilla');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Antarktida');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigua a Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Argentina');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Arménie');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Austrálie');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Ázerbájdžán');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamy');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahrajn');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladéš');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbados');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Belgie');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belize');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Bělorusko');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benin');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermudy');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Bhútán');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolívie');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosna a Hercegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswana');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Bouvetův ostrov');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brazílie');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Britské indickooceánské území');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Britské Panenské ostrovy');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunej');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulharsko');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Ceuta a Melilla');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'Clippertonův ostrov');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Cookovy ostrovy');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Čad');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Černá Hora');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Česká republika');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Čína');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Dánsko');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Diego Garcia');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominika');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Dominikánská republika');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Džibutsko');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Egypt');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ekvádor');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritrea');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estonsko');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiopie');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'Evropská unie');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Faerské ostrovy');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Falklandské ostrovy');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fidži');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipíny');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finsko');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Francie');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Francouzská Guyana');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Francouzská jižní teritoria');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Francouzská Polynésie');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabon');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambie');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ghana');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Gibraltar');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grenada');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Grónsko');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Gruzie');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Guadeloupe');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guam');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Guatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Guernsey');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyana');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haiti');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'Heardův ostrov a McDonaldovy ostrovy');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Honduras');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Hongkong - zvláštní administrativní oblast Číny');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Chile');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Chorvatsko');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Indie');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonésie');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Irák');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Írán');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Irsko');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Island');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Itálie');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Izrael');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jamajka');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Japonsko');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Jemen');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Jersey');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Jihoafrická republika');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Jižní Georgie a Jižní Sandwichovy ostrovy');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Jižní Korea');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Jordánsko');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Kajmanské ostrovy');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kambodža');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kamerun');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanada');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Kanárské ostrovy');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Kapverdy');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Katar');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazachstán');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Keňa');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Kokosové ostrovy');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolumbie');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Komory');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongo - Brazzaville');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Kongo - Kinshasa');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kostarika');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kuba');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuvajt');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Kypr');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kyrgyzstán');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laos');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesotho');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Libanon');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Libérie');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libye');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Lichtenštejnsko');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Litva');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Lotyšsko');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Lucembursko');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Macao - zvláštní administrativní oblast Číny');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagaskar');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Maďarsko');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Makedonie');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malajsie');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawi');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maledivy');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Maroko');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Marshallovy ostrovy');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martinik');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Mauricius');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mauritánie');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayotte');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Menší odlehlé ostrovy USA');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mexiko');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikronésie');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldavsko');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monako');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongolsko');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montserrat');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mosambik');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myanmar');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibie');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nauru');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Německo');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepál');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Niger');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nigérie');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikaragua');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niue');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Nizozemské Antily');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Nizozemsko');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Norfolk');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norsko');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Nová Kaledonie');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Nový Zéland');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Omán');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Ostrov Ascension');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Ostrov Man');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Ostrovy Turks a Caicos');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pákistán');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Palestinská území');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papua-Nová Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguay');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peru');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitcairnovy ostrovy');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Pobřeží slonoviny');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Polsko');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Portoriko');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portugalsko');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Rakousko');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Réunion');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Rovníková Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Rumunsko');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rusko');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Rwanda');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Řecko');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Salvador');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marino');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Saúdská Arábie');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegal');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Severní Korea');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Severní Mariany');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seychely');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sierra Leone');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapur');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovensko');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slovinsko');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somálsko');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Spojené arabské emiráty');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Spojené státy');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Srbsko');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Srbsko a Černá Hora');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Srí Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Středoafrická republika');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Súdán');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinam');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Svatá Helena');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Svatá Lucie');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Svatý Bartoloměj');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Svatý Kitts a Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Svatý Martin');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Svatý Pierre a Miquelon');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Svatý Tomáš');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Svatý Vincenc a Grenadiny');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Svazijsko');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Sýrie');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Šalamounovy ostrovy');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Španělsko');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Špicberky a Jan Mayen');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Švédsko');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Švýcarsko');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tádžikistán');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzanie');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Thajsko');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Tchaj-wan');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidad a Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunisko');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Turecko');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turkmenistán');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukrajina');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruguay');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Uzbekistán');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Vánoční ostrovy');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatikán');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Velká Británie');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuela');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietnam');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'Vnější Oceánie');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Východní Timor');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wallis a Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambie');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Západní Sahara');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabwe');
