CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'alang Nanci');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'alang Posniya');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'alang Pajey');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'alang Puwei');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'alang Switjrrant');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'alang Ipaw');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'alang Towjih');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'alang Posey');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'alang Inglis');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'alang Nanjiouya ni Nansanminji');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'alang Htee ni Mayktan');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'alang Krowtia');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'alang Intu');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'alang Inglis niq Intu');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'alang Itariya');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'alang Nihong');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'alang Mondineygrw');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'alang Srbia');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'alang Ruski');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'alang Snmarinow');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'alang Posey niq Nan');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'alang Amarika');
INSERT INTO [country] ([id], [name]) VALUES ('ZZ', 'ini klayi na alang ni');
