CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afganisztán');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Aland-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albánia');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Algéria');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'Amerikai Csendes-óceáni Szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Amerikai Szamoa');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Amerikai Virgin-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andorra');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Anguilla');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Antarktisz');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigua és Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argentína');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'Ascension-sziget');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Ausztrália');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Ausztria');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azerbajdzsán');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahama-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrein');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Banglades');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbados');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belgium');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benin');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Bhután');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolívia');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosznia-Hercegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'Bouvet-sziget');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brazília');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Brit Indiai-óceáni Terület');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Brit Virgin-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgária');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'Ceuta és Melilla');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Chile');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Ciprus');
INSERT INTO `country` (`id`, `name`) VALUES ('CP', 'Clipperton-sziget');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Comore-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Cook-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Costa Rica');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Csád');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Csehország');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Dánia');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'Dél Grúzia és a Déli Szendvics-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Dél-afrikai Köztársaság');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Dél-Korea');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'Diego Garcia');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominika');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Dominikai Köztársaság');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Dzsibuti');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ecuador');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Egyenlítői-Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Egyesült Államok');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Egyesült Arab Emirátus');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Egyesült Királyság');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Egyiptom');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Elefántcsontpart');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritrea');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Észak-Korea');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Északi Mariana-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Észtország');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Etiópia');
INSERT INTO `country` (`id`, `name`) VALUES ('EU', 'Európai Unió');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Falkland-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Fehéroroszország');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Feröer-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fidzsi');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finnország');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'Francia Déli Területek');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Francia Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Francia Polinézia');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Franciaország');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Fülöp-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabon');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ghána');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Gibraltár');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Görögország');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Grönland');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Grúzia');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Guadeloupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guam');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Guatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'Guernsey');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'Heard és McDonald Szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Holland Antillák');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Hollandia');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'Hongkong SAR Kína');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Horvátország');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'India');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonézia');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Irak');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Irán');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Írország');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Izland');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Izrael');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaica');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japán');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Jemen');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'Jersey');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordánia');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Kajmán-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambodzsa');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kamerun');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'Kanári-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Karácsony-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Katar');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazahsztán');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Kelet-Timor');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Kína');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirgizisztán');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'Kókusz-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolumbia');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongó - Brazzaville');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Kongó - Kinshasa');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Közép-afrikai Köztársaság');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kuba');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuvait');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'Külső-Óceánia');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laosz');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Lengyelország');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Lettország');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libanon');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Libéria');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Líbia');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Liechtenstein');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Litvánia');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Luxemburg');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Macedónia');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagaszkár');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Magyarország');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Makaó SAR Kína');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malajzia');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldív-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Málta');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'Man-sziget');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Marokkó');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Marshall-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinique');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauritánia');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Mauritius');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayotte');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Mexikó');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Mianmar [Burma]');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikronézia');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldova');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monaco');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongólia');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Montenegró');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambik');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namíbia');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Németország');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepál');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nicaragua');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Niger');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigéria');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Norfolk-sziget');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norvégia');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Nyugat-Szahara');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Olaszország');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Omán');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Oroszországi Föderáció');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Örményország');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakisztán');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Palesztin Terület');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Pápua Új-Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paraguay');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitcairn-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portugália');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Puerto Rico');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Reunion');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Románia');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Ruanda');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'Saint Barthélemy');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Saint Kitts és Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'Saint Martin');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Saint Pierre és Miquelon');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Saint Vincent és a Grenadine-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Salamon-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Salvador');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Santa Lucia');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Sao Tomé és Príncipe');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seychelle-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sierra Leone');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Spanyolország');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Spitzbergák és Jan Mayen-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Srí Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Suriname');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Svájc');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Svédország');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Szamoa');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Szaúd-Arábia');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Szenegál');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Szent Helena');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Szerbia');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Szerbia és Montenegró');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Szingapúr');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Szíria');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Szlovákia');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Szlovénia');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Szomália');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Szudán');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Szváziföld');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tadzsikisztán');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Tajvan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzánia');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Thaiföld');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Törökország');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad és Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunézia');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Turks- és Caicos-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Türkmenisztán');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Új-Kaledónia');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Új-Zéland');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukrajna');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Uruguay');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Üzbegisztán');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatikán');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vietnam');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis- és Futuna-szigetek');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambia');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Zöld-foki Köztársaság');
