CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Авганистан');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Азербејџан');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Аландска острва');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Албанија');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Алжир');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Америчка Самоа');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Ангвила');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Ангола');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Андора');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Антарктик');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Антигве и Барбуда');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Аргентина');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Арменија');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Аруба');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Аустралија');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Аустрија');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Бангладеш');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Барбадос');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Бахами');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Бахреин');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Белгија');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Белизе');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Белорусија');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Бенин');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Бермуда');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Божићна острва');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Боливија');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Босна и Херцеговина');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Боцвана');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Бразил');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Британска Девичанска Острва');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Британска територија у Индијском океану');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Брунеј');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Буве Острва');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Бугарска');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Буркина Фасо');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Бурунди');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Бутан');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Валис и Футуна Острва');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Вануату');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Ватикан');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Велика Британија');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Венецуела');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Вијетнам');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Габон');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Гамбија');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Гана');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Гваделупе');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Гвајана');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Гватемала');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Гвинеја');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Гвинеја-Бисао');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Гибралтар');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Гренада');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Гренланд');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Грузија');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Грчка');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Гуам');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Гурнси');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Данска');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Дијего Гарсија');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Доминика');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Доминиканска Република');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'Европска Унија');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Египат');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Еквадор');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Екваторијална Гвинеја');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Еритреја');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Естонија');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Етиопија');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Замбија');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Западна Сахара');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Зимбабве');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Израел');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Индија');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Индонезија');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Ирак');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Иран');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Ирска');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Исланд');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Источни Тимор');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Италија');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Јамајка');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Јапан');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Јемен');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Јордан');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Јужна Кореја');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Јужна Џорџија и Јужна Сендвич Острва');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Јужноафричка Република');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Казахстан');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Кајманска Острва');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Камбоџа');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Камерун');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Канада');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Канарска острва');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Капе Верде');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Катар');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Кенија');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Кина');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Кипар');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Киргизстан');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Кирибати');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Кокос (Келинг) Острва');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Колумбија');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Коморска Острва');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Конго - Бразавил');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Конго - Киншаса');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Костарика');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Куба');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Кувајт');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Кукова Острва');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Лаос');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Лесото');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Летонија');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Либан');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Либерија');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Либија');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Литванија');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Лихтенштајн');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Луксембург');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Мадагаскар');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Мађарска');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Мајоте');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Макао С. А. Р. Кина');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Македонија');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Малави');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Малдиви');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Малезија');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Мали');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Малта');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Мања удаљена острва САД');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Мароко');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Мартиник');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Маршалска Острва');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Мауританија');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Маурицијус');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Мексико');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Мијанмар [Бурма]');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Микронезија');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Мозамбик');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Молдавија');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Монако');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Монголија');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Монсерат');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Намибија');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Науру');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Немачка');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Непал');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Нигер');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Нигерија');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Никарагва');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Ниуе');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Нова Каледонија');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Нови Зеланд');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Норвешка');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Норфолк Острво');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Обала Слоноваче');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Оман');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'Остала океанија');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Острво Асенсион');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'Острво Клипертон');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Острво Ман');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Пакистан');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Палау');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Палестинске територије');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Панама');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Папуа Нова Гвинеја');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Парагвај');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Перу');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Питкерн');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Пољска');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Порто Рико');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Португал');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Реинион');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Руанда');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Румунија');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Русија');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'С.А.Д. Девичанска Острва');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Салвадор');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Самоа');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'Сан Марино');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Сао Томе и Принципе');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Саудијска Арабија');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Свазиленд');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Свалбард и Јанмајен Острва');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Света Јелена');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Свети Бартоломеј');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Северна Кореја');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Северна Маријанска Острва');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Сејшели');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Сен Пјер и Микелон');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Сенегал');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Сент Винсент и Гренадини');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Сент Китс и Невис');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Сент Луција');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Сент Мартин');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Сеута и Мелиља');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Сијера Леоне');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Сингапур');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Сирија');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Сједињене Америчке Државе');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Словачка');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Словенија');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Соломонска Острва');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Сомалија');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Србија');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Србија и Црна Гора');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Судан');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Суринам');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Тајван');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Тајланд');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Танзанија');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Таџикистан');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Того');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Токелау');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Тонга');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Тринидад и Тобаго');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Тристан да Куња');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Тувалу');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Тунис');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Туркменистан');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Туркс и Кајкос Острва');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Турска');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Уганда');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Узбекистан');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Уједињени Арапски Емирати');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Украјина');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Уругвај');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Фарска Острва');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Филипини');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Финска');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Фиџи');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Фокландска острва');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Француска');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Француска Гвајана');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Француска Полинезија');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Француске Јужне Територије');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Хаити');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'Херд и Мекдоналд Острва');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Холандија');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Холандски Антили');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Хонг Конг С. А. Р. Кина');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Хондурас');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Хрватска');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Централно Афричка Република');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Црна Гора');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Чад');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Чешка');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Чиле');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Џерси');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Џибути');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Швајцарска');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Шведска');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Шпанија');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Шри Ланка');
