CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AO', 'अंगोला');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'अँग्विला');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'अंटार्क्टिका');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'अँटिग्वा आणि बर्बुडा');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'अँडोरा');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'अझरबैजान');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'अफगाणिस्तान');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'अमेरिकन सामोआ');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'अरुबा');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'अर्जेंटिना');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'अल साल्वाडोर');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'अल्जीरिया');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'अल्बानिया');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'अ‍ॅलँड बेटे');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'अ‍ॅसेन्शियम बेट');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'आइसलँड');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'आउटलायिंग ओशनिया');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'आयर्लंड');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'आयव्हरी कोस्ट');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'आर्मेनिया');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'इंडोनेशिया');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'इक्वाडोर');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'इक्वेटोरियल गिनी');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'इजिप्त');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'इटली');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'इथिओपिया');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'इराक');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'इरिट्रिया');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'इस्त्राइल');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'इस्ले ऑफ मॅन');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'ईराण');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'उझबेकिस्तान');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'उत्तर कोरिया');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'उत्तरी मारियाना बेटे');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'उरुग्वे');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'एस्टोनिया');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'ऑस्ट्रिया');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'ऑस्ट्रेलिया');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'ओमान');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'कंबोडिया');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'कझाकस्तान');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'कतार');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'काँगो - किंशासा');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'काँगो - ब्राजाविले');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'किरगिझस्तान');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'किरीबाटी');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'कुक बेटे');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'कुवेत');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'कॅनडा');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'कॅनरी बेटे');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'कॅमेरून');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'केंद्रीय अफ्रिकी प्रजासत्ताक');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'केनिया');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'केप व्हर्डे');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'केमन बेटे');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'कोकोस बेटे');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'कोमोरोज');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'कोलम्बिया');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'कोस्टारिका');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'क्यूबा');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'क्रोएशिया');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'क्लिपरटोन बेट');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'ख्रिसमस बेट');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'गयाना');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'गाम्बिया');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'गिनी');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'गिनी-बिसाउ');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'गुआम');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'गॅबॉन');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'ग्रीनलंड');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'ग्रीस');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'ग्रेनेडा');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'ग्वाटेमाला');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'ग्वाडेलोउपे');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'ग्वेर्नसे');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'घाना');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'चाड');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'चिली');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'चीन');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'जपान');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'जमैका');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'जर्मनी');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'जर्सी');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'जिबौटी');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'जिब्राल्टर');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'जॉर्जिया');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'जॉर्डन');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'झाम्बिया');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'झिम्बाब्वे');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'झेक प्रजासत्ताक');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'टर्क्स आणि कैकोस बेटे');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'टांझानिया');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'टुवालु');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'टोंगा');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'टोगो');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'ट्यूनिशिया');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'ट्रिस्टन दा कन्हा');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'डेन्मार्क');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'डोमिनिकन प्रजासत्ताक');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'डोमिनिका');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'ताजिकिस्तान');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'तुर्कमेनिस्तान');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'तुर्की');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'तैवान');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'तोकेलाउ');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'त्रिनिदाद आणि टोबॅगो');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'थायलंड');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'दक्षिण अफ्रिका');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'दक्षिण कोरिया');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'दक्षिण जॉर्जिया आणि दक्षिण सँडविच बेटे');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'दिएगो गार्शिया');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'नऊरु');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'नमीबिया');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'नाइजर');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'नायजेरिया');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'निकाराग्वे');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'नीयू');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'नेदरलँड');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'नेदरलँड्‍स अँ‍टिल्स');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'नेपाळ');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'नॉरफॉक बेट');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'नॉर्वे');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'न्यू कॅलेडोनिया');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'न्यूझीलंड');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'पनामा');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'पराग्वे');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'पलाऊ');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'पश्चिम सहारा');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'पाकिस्तान');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'पापुआ न्यू गिनी');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'पिटकैर्न');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'पूर्व तिमोर');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'पॅलेस्टिनी प्रदेश');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'पेरू');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'पोर्टो रिको');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'पोर्तुगाल');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'पोलंड');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'फरोए बेटे');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'फिजी');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'फिनलंड');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'फिलीपिन्स');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'फॉकलंड बेटे');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'फ्रान्स');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'फ्रेंच गयाना');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'फ्रेंच दाक्षिणात्य प्रदेश');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'फ्रेंच पॉलिनेशिया');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'बर्मुडा');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'बल्गेरिया');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'बहामाज');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'बहारीन');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'बांग्लादेश');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'बार्बाडोस');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'बुरुंडी');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'बुर्किना फासो');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'बेनिन');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'बेलारूस');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'बेलिझे');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'बेल्जियम');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'बोउवेट बेट');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'बोट्सवाना');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'बोलिव्हिया');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'बोस्निया अणि हर्जेगोविना');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'ब्राझिल');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'ब्रिटन');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'ब्रिटिश इंडियन ओशन टेरीटरी');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'ब्रिटिश व्हर्जिन बेटे');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'ब्रुनेई');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'भारत');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'भूतान');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'मंगोलिया');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'मकाओ एसएआर चायना');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'मलावी');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'मलेशिया');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'मादागास्कर');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'मायक्रोनेशिया');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'मायोट्टे');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'मार्टिनिक');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'मार्शल बेटे');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'मालदीव्ज');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'माली');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'माल्टा');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'मॅसेडोनिया');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'मेक्सिको');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'मॉन्ट्सेराट');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'मॉरिटानिया');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'मॉरिशस');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'मोंटेनेग्रो');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'मोझाम्बिक');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'मोनॅको');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'मोरोक्को');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'मोल्डोव्हा');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'म्यानमार [ब्रह्मदेश]');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'युगांडा');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'युनाइटेड स्टेट्स माइनर आउटलाइंग बेटे');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'यू.एस. व्हर्जिन बेटे');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'यूक्रेन');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'यूरोपीय संघ');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'येमेन');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'रवांडा');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'रशिया');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'रियूनियन');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'रोमानिया');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'लक्झेंबर्ग');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'लाओस');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'लाट्‌विया');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'लायबेरिया');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'लिंचेनस्टाइन');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'लिथुआनिया');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'लिबिया');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'लेबानन');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'लेसोथो');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'वानौटु');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'वालिस आणि फ्यूचूना');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'व्हिएतनाम');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'व्हॅटिकन');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'व्हेनेझुएला');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'श्रीलंका');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'संयुक्त अरब अमीरात');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'संयुक्त राज्ये /अमेरिका');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'सर्बिया');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'सर्बिया आणि माँटेनेग्रो');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'साओ टोम आणि प्रिंसिपे');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'सामोआ');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'सायप्रस');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'सिंगापूर');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'सिएरा लिओन');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'सीरिया');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'सुदान');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'सुरिनाम');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'सॅन मरीनो');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'सेंट किट्स आणि नेव्हिस');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'सेंट पियरे आणि मिक्वेलोन');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'सेंट बार्थेलेमी');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'सेंट मार्टिन');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'सेंट ल्यूसिया');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'सेंट व्हिन्सेंट आणि ग्रेनडाइन्स');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'सेंट हेलेना');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'सेनेगल');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'सेशेल्स');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'सोमालिया');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'सोलोमन बेटे');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'सौदी अरब');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'स्पेन');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'स्यूटा आणि मेलिला');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'स्लोव्हाकिया');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'स्लोव्हेनिया');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'स्वाझिलँड');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'स्वालबर्ड आणि जान मायेन');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'स्वित्झर्लंड');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'स्वीडन');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'हंगेरी');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'हर्ड बेट आणि मैकडोनाल्ड बेट');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'हाँगकाँग एसएआर क्षेत्र चीन');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'हैती');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'होंडुराज्');
