CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andorrab');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'United Arab Emirates');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afghanistanni');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antiguab tsî Barbudab');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Anguillab');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albaniab');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armeniab');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Netherlands Antilles');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angolab');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argentinab');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Americab Samoab');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Austriab');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Australieb');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Arubab');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azerbaijanni');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosniab tsî Herzegovinab');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbados');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Banglades');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belgiummi');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Fasob');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgariab');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrain');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundib');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benins');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermudas');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Boliviab');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Braziliab');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamas');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Bhutans');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botswanab');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Belarus');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanadab');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Democratic Republic of the Congo');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Central African Republiki');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Congob');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Switzerlandi');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Ivoorkusi');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Cook Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Chilib');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Cameroonni');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Chinab');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Colombiab');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Costa Rica');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Serbiab tsî Montenegrob');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Cubab');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Cape Verde Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Cyprus');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Czech Republiki');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Duitslandi');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Djibouti');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Denmarki');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominicab');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Dominican Republic');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Algeriab');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ecuadori');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estoniab');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Egipteb');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritreab');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Spanieb');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Ethiopiab');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finlandi');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fijib');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Falkland Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Micronesia');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Frankreiki');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gaboni');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'United Kingdom');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Georgiab');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'French Guiana');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ghanab');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Gibraltar');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Greenland');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambiab');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Guineab');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Guadeloupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Equatorial Guineab');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Xrikelandi');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Guatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guam');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Croatiab');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Hongareieb');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonesiab');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irlandi');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Israeli');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Indiab');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Iraqi');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iranni');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Iceland');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italiab');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaicab');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordanni');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japanni');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenyab');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kyrgyzstanni');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Cambodiab');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Comoros');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Koreab, Noord');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Koreab, Suid');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuwaiti');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Cayman Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazakhstanni');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laos');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Lebanonni');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Saint Lucia');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Liechtensteinni');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sri Lankab');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberiab');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesothob');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Lithuaniab');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Luxembourgi');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Latvia');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libyab');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Morocco');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monaco');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldova');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagascari');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Marshall Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Macedoniab');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Malib');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Myanmar');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongolia');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinique');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauritania');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Mauritius');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldives');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawib');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Mexicob');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malaysiab');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambiki');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibiab');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'New Caledonia');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Nigeri');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Norfolk Island');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigerieb');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nicaraguab');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Netherlands');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Noorweeb');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepali');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'New Zealandi');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Perub');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'French Polynesia');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papua New Guineab');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Philippinni');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistanni');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Polandi');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Saint Pierre and Miquelon');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitcairn');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Puerto Rico');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Palestinian West Bank and Gaza');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portugali');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paraguaib');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Qatar');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Réunion');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romania');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Rasiab');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Rwandab');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Saudi Arabiab');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Solomon Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seychelles');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudanni');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Swedeb');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapore');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Saint Helena');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Slovenia');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Slovakia');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sierra Leone');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegali');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somaliab');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Suriname');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'São Tomé and Príncipe');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'El Salvadori');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Syriab');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Swazilandi');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Chadi');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togob');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Thailandi');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tajikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'East Timor');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunisiab');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Turkeieb');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzaniab');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukraine');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Ugandab');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Amerikab');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Uruguaib');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzbekistan');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatican State');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuelab');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'British Virgin Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'U.S. Virgin Islands');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vietnammi');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis and Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Yemen');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayotte');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Suid Afrikab');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambiab');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabweb');
