CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Afrika ya Súdi');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afuganisita');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Ajelbayidja');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Alabu Nsawudi');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Alemanu');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Alijantine');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Alijeri');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Alubani');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Ameni');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Ameriki');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andore');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Angeletele');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Angiye');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antiga ne Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Antiye wa Olande');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Ayiti');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamase');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrene');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barebade');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belejiki');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Bene');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Benguladeshi');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Biligari');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brineyi');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Bukinafaso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Butani');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Byelorisi');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Danemalaku');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Ditunga dya Afrika wa munkatshi');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Ditunga dya Tsheka');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Ditunga wa Duminiku');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Ditunga wa Kongu');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Djibuti');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Duminiku');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ekwatele');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Elitele');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Esitoni');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Etshiopi');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Filande');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fuji');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambi');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Gine Ekwatele');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Giyane wa Nfalanse');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Inde');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonezi');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Ira');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Iraki');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irelande');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Irigwei');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Isilande');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Isirayele');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Itali');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaiki');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japu');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Jibeletale');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jodani');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Joriji');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Kaledoni wa mumu');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambodza');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kamerune');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Katari');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazakusita');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kigizisita');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolombi');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Komoru');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongu');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Kore wa muulu');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Kore wa mwinshi');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Kositarika');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Kotedivuale');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Koweti');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Krowasi');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kuba');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Lawosi');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Lemila alabu');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Lenyo');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesoto');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Letoni');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Liba');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberiya');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libi');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Likisambulu');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Lishuteni');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Litwani');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Lutanda lua Kapevele');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Lutanda lua Kayima');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Lutanda lua Kookɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Lutanda lua Maluni');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Lutanda lua Mariane wa muulu');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Lutanda lua Marishale');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Lutanda lua Norfok');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Lutanda lua Solomu');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Lutanda lua Tuluki ne Kaiko');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Lutanda lua Vierzi wa Ameriki');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Lutanda lua Vierzi wa Angeletele');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Lutanda lwa Angeletele ku mbu wa Indiya');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagasikari');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Madive');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malezi');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malite');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Maroke');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martiniki');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Masedwane');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayote');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Mbolivi');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Mbosini ne Hezegovine');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Mbotswana');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Meksike');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikronezi');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Mnulezile');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Molidavi');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monaku');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongoli');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Morise');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Moritani');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambiki');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Mpoloni');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Mpotoriku');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Mputulugeshi');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Musera');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Mushidi');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Myamare');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibi');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepálɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Nfalanse');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Nfilipi');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Ngabu');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ngana');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Ngeleka');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Ngelenade');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Ngine');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Nginebisau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Ngiyane');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Ngowelande');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Ngwadelupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Ngwame');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Ngwatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Nijere');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nijerya');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikaragwa');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Noriveje');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Nsebi ne Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Nsipani');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Nvatika');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Nyue');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Olandɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Omane');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Ondurase');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Ongili');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Ositali');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Otilisi');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakisita');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Palagwei');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Palesine');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papwazi wa Nginɛ wa mumu');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pikairni');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Polinezi wa Nfalanse');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Risi');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romani');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Rwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Samoa wa Ameriki');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Santu eleni');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Santu krístofe ne Neves');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Santu lisi');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'Santu Marine');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Santu pététo ne Mikelu');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Santu vesa ne Ngelenadine');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Sao Tome ne Presipɛ');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Savadore');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegale');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seshele');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Shili');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Shine');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Shipele');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Siera Leone');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Silovaki');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Siloveni');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapure');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Siri');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sirilanka');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somali');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Suda');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Suriname');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Suwedi');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Swazilandi');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Swise');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwani');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzani');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Tayilanda');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tazikisita');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Timoru wa diboku');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Tinidade ne Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tinizi');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togu');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Tshadi');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Tukemenisita');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Tuluki');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukreni');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzibekisita');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Viyetiname');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Walise ne Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Yemenu');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambi');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Zelanda wa mumu');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
