CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('XK', 'Kosovo');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'ཀ་ཊར');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'ཀ་ནེ་རི་གླིང་ཚོམ');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'ཀ་ཛགས་སཏཱན');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'ཀམ་བྷོ་ཌི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('CW', 'ཀྱཱུར་ར་ཀོ');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'ཀྲོ་ཨེ་ཤ');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'ཀི་རི་བ་ཏི་མཚོ་གླིང');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'ཀིའུ་བྷ');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'ཀིར་གིས་སཏཱན');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'ཀུ་ཝེཊ');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'ཀུག་གླིང་ཚོམ');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'ཀེ་ན་ཌ');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'ཀེ་མ་རུན');
INSERT INTO [country] ([id], [name]) VALUES ('BQ', 'ཀེ་རི་བི་ཡེན་ནེ་དར་ལནཌས྄');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'ཀེན་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'ཀེཔ་བཱཌ');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'ཀོ་ཀོས་གླིང་ཚོམ');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'ཀོ་ཊེ་ ཌི་ཨི་ཝོ་རེ');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'ཀོ་མོ་རོས');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'ཀོ་ལོམ་བྷི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'ཀོང་གྷོ ཀིན་ཤ་ས');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'ཀོང་གྷོ བྷྲ་ཛ་བིལ');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'ཀོས་ཊ་རི་ཀ');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'ཁི་རིསྟ་མེས་མཚོ་གླིང');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'ཁེ་མེན་གླིང་ཚོམ');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'གྷ་ན');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'གྷ་བྷོན');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'གྷ་ཡ་ན');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'གྷི་ནི');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'གྷི་ནི་ བྷི་སཱའུ');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'གྷེམ་བི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'གྷོ་ཊ་མ་ལ');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'གིརིས྄');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'གིརཱིན་ལནཌ྄');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'གུ་འམ་ མཚོ་གླིང');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'གུ་ཨེརྣ་སི');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'གུའི་ཡ་ན་ ཕྲནས྄་མངའ་ཁོངས');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'གྲྀ་ན་ཌ');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'གོ་ཌེ་ལུ་པེ');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'ཅཱཌ');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'ཅི་ལི');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'ཅེཀ་ རི་པབ་ལིཀ');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'ཇ་པཱན');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'ཇཱ་མཻ་ཀ');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'ཇཱར་མ་ནི');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'ཇི་བྷུ་ཊི');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'ཇིབ་རཱལ་ཊར');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'ཇེར་སི');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'ཇོར་ཌན');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'ཇཽར་ཇཱ');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'ཊཱན་ཛཱ་ནི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'ཊཱའི་ཝཱན');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'ཊཱར་ཀི');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'ཊཱརཀ་མེནའི་སཏཱན');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'ཊི་ནི་ཌཱཌ་ ཨེནཌ་ ཊོ་བྷེ་གྷོ');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'ཊུ་ནི་ཤི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'ཊོ་གྷོ');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'ཊོང་གྷ');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'ཌི་ཡེ་གོ་གར་སིའོ');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'ཌེན་མཱཀ');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'ཌོ་མི་ནི་ཀ');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'ཌོ་མི་ནི་ཀཱན་ རི་པབ་ལིཀ');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'ཏ་ཇིག་གི་སཏཱན');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'ཏྲིས་ཏན་ད་ཀུན་ཧ');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'ཏི་་མོར་ལེ་ཨེསཊ');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'ཏུ་ཝ་ལུ');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'ཏུརྐས྄་ ཨེནཌ་ ཀ་ཀོས་གླིང་ཚོམ');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'ཏོ་ཀེ་ལའུ་ མཚོ་གླིང');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'ཐཱའི་ལེནཌ');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'ན་མི་བི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'ནའུ་རུ་');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'ནཱའི་ཇཱ');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'ནཱའི་ཇི་རི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'ནི་ཀྲ་ཝ་ག');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'ནི་ཨུ་ཨཻ');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'ནིའུ་ཀ་ལི་དོ་ནི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'ནིའུ་ཛི་ལེནཌ');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'ནུབ་ཕྱོགས་ ས་ཧཱ་ར');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'ནེ་དར་ལནཌས྄');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'ནོར་ཕོལཀ་མཚོ་གླིང༌');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'ནོར་ཝེ');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'པ་ཀི་སཏཱན');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'པ་ན་མ');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'པ་པུ་ ནིའུ་གི་ནི');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'པ་ར་གུ་ཝའི');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'པ་ལའུ');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'པིཊ་ཀེ་ཡེརན་གླིང་ཚོམ');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'པུ་འེར་ཊོ་རི་ཁོ');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'པེ་རུ');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'པེ་ལིསི་ཊི་ནི་ཡན་ཊེ་རི་ཐོ་རི');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'པོ་ལེནཌ');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'པོར་ཅུ་གཱལ');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'ཕྲནཅ་གི་ལྷོ་ཕྱོགས་མངའ་ཁོངས');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'ཕྲཱནས');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'ཕྲཱནས྄་ཀྱི་པོ་ལི་ནི་ཤི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'ཕལྐ་ལནྜ་གླིང་ཚོམ');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'ཕཱའེ་རོ་གླིང་ཚོམ');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'ཕི་ཇི');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'ཕི་ལི་པིནས');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'ཕིན་ལེནཌ');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'བ་ཊི་ཀཱན་ སི་ཊི');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'བངྒ་ལ་དེཤ');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'བྱང་ ཀོ་རི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'བྱང་ཕྱོགས་ཀྱི་མ་ར་ཡ་ན་གླིང་ཚོམ');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'བར་མུ་ཌ');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'བྲ་ཛིལ');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'བྲི་ཊིཤ་རྒྱ་གར་གྱི་རྒྱ་མཚོ་ས་ཁོངས');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'བལ་ཡུལ');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'བྷ་རེན');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'བྷ་ཧ་མས྄');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'བྷར་ཀི་ན་ ཕེ་སོ');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'བྷར་བེ་ཌོས');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'བྷྲུ་ནའི');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'བྷུ་རུན་ཌི');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'བྷེ་ནིན');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'བྷེ་ལི་བི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'བྷེ་ལིཛ');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'བྷེལ་ཇམ');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'བྷོཙ་ཝ་ན');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'བྷོས་ནི་ཡ་ ཨེནཌ་ ཧར་ཛི་གྷོ་བི་ན');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'བུལ་ག་རི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'བེ་ནི་ཛུ་ཝེ་ལ');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'བེཊ་ནཱམ');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'བེལ་ཨ་རུ་སུ');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'མ་དཱ་གེས་ཀར');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'མ་ལ་ཝི');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'མ་ལེ་ཤི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'མ་སེ་ཌོ་ནི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'མཀ་ཨའུ་ཅཱའི་ན');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'མའི་ཀྲོ་ནི་ཤི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'མར་ཤེལ་གླིང་ཚོམ');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'མཱ་ལི');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'མཱར་ཊི་ནིཀ');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'མཱལ་ཊ');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'མཱལ་དིབས');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'མི་ཡཱན་མར་ (བྷར་མ)');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'མེ་ཡོཊ');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'མེཀ་སི་ཀོ');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'མོ་ན་ཀོ');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'མོ་ཛམ་བྷིཀ');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'མོ་རི་ཊེ་ནི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'མོ་རི་ཤཱས');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'མོ་རོ་ཀོ');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'མོན་ཊི་ནེག་རོ');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'མོན་ས་རཊ');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'མོལ་དོ་བཱ');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'ཛམ་བྷི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'ཛིམ་བྷབ་ཝེ');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'ཝ་ནུ་ཨ་ཏུ');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'ཝརཇིན་གླིང་ཚོམ་ བྲཱི་ཊིཤ་མངའ་ཁོངས');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'ཝརཇིན་གླིང་ཚོམ་ ཡུ་ཨེས་ཨེ་མངའ་ཁོངས');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'ཝལ་ལིས྄་ ཨེནཌ་ ཕུ་ཏུ་ན་');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'འབྲུག');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'འཛམ་གླིང་ལྷོ་མཐའི་ཁྱགས་གླིང');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'ཡུ་ཀརེན');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'ཡུ་གྷན་ཌ');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'ཡུ་ནཱའི་ཊེཌ་ ཀིང་ཌམ');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'ཡུ་ནཱའི་ཊེཌ་ ཨ་རབ་ ཨེ་མེ་རེཊས');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'ཡུ་རུ་གུ་ཝའི');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'ཡུ་ཨེས་གྱི་མཐའ་མཚམས་མཚོ་གླིང་');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'ཡུ་ཨེས་ཨེ');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'ཡེ་མེན');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'རྒྱ་གར');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'རྒྱ་ནག');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'རུ་ཝན་ཌ');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'རེ་ཡུ་ནི་ཡོན');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'རོ་མེ་ནི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'ལག་ཛམ་བོརྒ');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'ལཊ་བི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'ལྷོ་ ཀོ་རི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'ལཱ་ཝོས');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'ལཱའི་བེ་རི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'ལི་ཐུ་ཝེ་ནི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'ལི་བི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'ལིཀ་ཏནས་ཏ་ཡིན');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'ལེ་བ་ནོན');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'ལཻ་སོ་ཐོ');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'ཤྲཱི་ལང་ཀ');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'ས་མོ་ཨ');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'ས་མོ་ཨ་ཡུ་ཨེས་ཨེ་མངའ་ཁོངས');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'སཝ་ ཊོ་མེ་ ཨེནཌ་ པྲྀན་སི་པེ');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'སྭཱལ་བྷརྡ་ ཨེནཌ་ ཇཱན་མ་ཡེན');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'སཱན་མ་རི་ནོ');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'སཱཝ་དི་ ཨ་རེ་བྷི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'སཱའི་པྲས');
INSERT INTO [country] ([id], [name]) VALUES ('SS', 'སཱའུཐ་ སུ་ཌཱན');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'སཱའུཐ་ ཨཕ་རི་ཀ');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'སཱའུཐ་ཇཽར་ཇཱ་ དང་ སཱའུཐ་སེནཌ྄་ཝིཅ་གླིང་ཚོམ');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'སཱར་བྷི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'སི་ར་ ལི་འོན');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'སི་རི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'སིང་ག་པོར');
INSERT INTO [country] ([id], [name]) VALUES ('SX', 'སིནཊ་ མཱར་ཊེན');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'སིནཊ་པི་ཡེར་ ཨེནཌ་ མིཀོ་ལེན');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'སུ་ཌཱན');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'སུ་ཝ་ཛི་ལེནཌ');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'སུ་ཝིཊ་ཛར་ལེནཌ');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'སུ་རི་ནཱམ');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'སུ་ལོ་བཱ་ཀི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'སུ་ལོ་བི་ནི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'སུའི་ཌེན');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'སེ་ནི་གྷལ');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'སེ་ཤཱལས');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'སེ་ཨུ་ཏ་ ཨེནཌ་ མེལ་ལི་ལ');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'སེན་ཊལ་ ཨཕ་རི་ཀཱན་ རི་པབ་ལིཀ');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'སེནཊ་ ཀིཊས་ དང་ ནེ་བིས');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'སེནཊ་ བར་ཐོ་ལོམ་མིའུ');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'སེནཊ་ མཱར་ཊིན');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'སེནཊ་ ལུ་སི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'སེནཊ་ ཧེ་ལི་ན');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'སེནཊ་ཝིན་སེནཌ྄ ཨེནཌ་ གི་རེ་ན་དིནས྄');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'སོ་མ་ལི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'སོ་ལོ་མོན་ གླིང་ཚོམ');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'སོག་པོ་ཡུལ');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'ཧཱང་གྷ་རི');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'ཧཱན་ཌུ་རཱས྄');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'ཧེ་ཊི');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'ཧོང་ཀོང་ཅཱའི་ན');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'ཨ་ཛར་བྷའི་ཇཱན');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'ཨ་ཡུལ་ ཨོཕ་ མཱན');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'ཨ་རུ་བཱ');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'ཨ་ལནཌ་གླིང་ཚོམ');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'ཨང་གྷོ་ལ');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'ཨང་གི་ལ');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'ཨན་ཊི་གུ་ཝ་ ཨེནཌ་ བྷར་བྷུ་ཌ');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'ཨཕ་གྷ་ནི་སཏཱན');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'ཨར་ཇེན་ཊི་ན');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'ཨར་མི་ནི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'ཨཱ་ཡ་ལེནཌ');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'ཨཱན་དོ་ར');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'ཨཱའིས་ལེནཌ');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'ཨཱལ་ཇི་རི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'ཨཱལ་བེ་ནི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'ཨཱོས་ཊྲི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'ཨཱོས་ཊྲེལ་ལི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'ཨི་ཇིབཊ');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'ཨི་ཊ་ལི');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'ཨི་ཐི་ཡོ་པི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'ཨི་རཱཀ');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'ཨི་རཱན');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'ཨིན་ཌོ་ནེ་ཤི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'ཨིས་པེན');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'ཨིས་ར་ཡེལ');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'ཨུ་རུ་སུ');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'ཨུས་བེག་གི་སཏཱན');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'ཨེ་ཀུ་ཊོ་རེལ་ གི་ནི');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'ཨེ་ཁྭ་ཌོར');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'ཨེ་རི་ཊྲེ་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'ཨེ་སེན་ཤུན་ཚོ་གླིང༌');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'ཨེལ་སལ་བ་ཌོར');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'ཨེས་ཊོ་ནི་ཡ');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'ཨོ་མཱན');
