CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Acerbaixán');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afganistán');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albania');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Alemaña');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andorra');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguila');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Antártida');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antiga e Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Antillas Holandesas');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Arabia Saudita');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armenia');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Arxelia');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Arxentina');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Australia');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Austria');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamas');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahrein');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladesh');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbados');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belice');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Bélxica');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benin');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermudas');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Bielorrusia');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolivia');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnia e Hercegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botsuana');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brasil');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunei');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgaria');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Bután');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Cabo Verde');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Cambodia');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Camerún');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Canadá');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Ceuta e Melilla');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Chad');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Chile');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'China');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Chipre');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Cidade do Vaticano');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Cimbabue');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Colombia');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Comores');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Congo');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Corea do Norte');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Corea do Sur');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Costa de Marfil');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Costa Rica');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Croacia');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Cuba');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Diego García');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Dinamarca');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominica');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ecuador');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'El Salvador');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Emiratos Árabes Unidos');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritrea');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Eslovaquia');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Eslovenia');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'España');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Estados Unidos de América');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estonia');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiopía');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Exipto');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipinas');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finlandia');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fixi');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Francia');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabón');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambia');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Gana');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Granada');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Grecia');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Grenlandia');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Guadalupe');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guam');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Guatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Guernsey');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Güiana');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Güiana Francesa');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Guinea Ecuatorial');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haití');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Honduras');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Hong Kong RAE de China');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Hungría');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Iemen');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Illa Bouvet');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Illa Christmas');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'Illa Clipperton');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Illa de Ascensión');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Illa de Man');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'Illa Heard e Illas McDonald');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Illa Norfolk');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Illas Aland');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Illas Caimán');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Illas Canarias');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Illas Cocos');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Illas Cook');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Illas Feroe');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Illas Malvinas');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Illas Marianas do norte');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Illas Marshall');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Illas Menores Distantes dos EUA.');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Illas Salomón');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Illas Turks e Caicos');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Illas Virxes Británicas');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Illas Virxes Estadounidenses');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'India');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonesia');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Irán');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Iraq');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Irlanda');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Islandia');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Israel');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Italia');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Jersey');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazakhstan');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuwait');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laos');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesotho');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Letonia');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Líbano');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberia');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libia');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Liechtenstein');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lituania');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Luxemburgo');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Macau RAE de China');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Macedonia');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagascar');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malaisia');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malaui');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maldivas');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Marrocos');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martinica');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Mauricio');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mauritania');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayotte');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'México');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Micronesia');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldova');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Mónaco');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongolia');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Montenegro');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montserrat');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambique');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myanmar');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibia');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nauru');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepal');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nicaragua');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niue');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Níxer');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nixeria');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Noruega');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Nova Caledonia');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Nova Celandia');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'Oceanía Distante');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Omán');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Países Baixos');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Palestina');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panamá');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papúa Nova Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Paquistán');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguai');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Perú');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitcairn');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Polinesia Francesa');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Polonia');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Porto Rico');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portugal');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Qatar');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Quenia');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Quirguicistán');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Reino Unido');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'República Africana Central');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'República Checa');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'República Democrática do Congo');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'República Dominicana');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Reunión');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Romanía');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Ruanda');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rusia');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Sahara Occidental');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samoa Americana');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'San Bartolomé');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'San Cristovo e Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marino');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'San Martiño');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'San Pedro e Miguelón');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'San Vicente e Granadinas');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Santa Helena');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Santa Lucía');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Santo Tomé e Príncipe');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seixeles');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegal');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Serbia');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Serbia e Montenegro');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Serra Leoa');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapur');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Siria');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somalia');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Suacilandia');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Sudáfrica');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudán');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Suecia');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Suíza');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinam');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Svalbard e Jan Mayen');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Tailandia');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwán');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzania');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Taxiquistán');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Territorio Británico do Océano Índico');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Territorios Franceses do Sul');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timor Leste');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trindade e Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Tristán da Cunha');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunisia');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turkmenistán');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Turquía');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ucraína');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'Unión Europea');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruguai');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Uzbekistán');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuela');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietnam');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wallis e Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Xamaica');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Xapón');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Xeorxia');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Xeorxia do Sur e Illas Sandwich');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Xibraltar');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Xibuti');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Xordania');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambia');
