CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Emetab Andorra');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Emetab kibagenge nebo arabuk');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Emetab Afghanistan');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Emetab Antigua ak Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Emetab Anguilla');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Emetab Albania');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Emetab Armenia');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Emetab Antile nebo Holand');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Emetab Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Emetab Argentina');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Emetab American Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Emetab Austria');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Emetab Australia');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Emetab Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Emetab Azerbaijan');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Emetab Bosnia ak Herzegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Emetab Barbados');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Emetab Bangladesh');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Emetab Belgium');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Emetab Burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Emetab Bulgaria');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Emetab Bahrain');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Emetab Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Emetab Benin');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Emetab Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Emetab Brunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Emetab Bolivia');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Emetab Brazil');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Emetab Bahamas');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Emetab Bhutan');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Emetab Botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Emetab Belarus');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Emetab Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Emetab Canada');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Emetab Congo - Kinshasa');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Emetab Afrika nebo Kwen');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Emetab Congo - Brazzaville');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Emetab Switzerland');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Emetab Côte d\'Ivoire');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Ikwembeyotab Cook');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Emetab Chile');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Emetab Cameroon');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Emetab China');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Emetab Colombia');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Emetab Costa Rica');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Emetab Serbia and Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Emetab Cuba');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Ikwembeyotab Cape Verde');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Emetab Cyprus');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Emetab Czech Republic');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Emetab Geruman');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Emetab Djibouti');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Emetab Denmark');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Emetab Dominica');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Emetab Dominican Republic');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Emetab Algeria');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Emetab Ecuador');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Emetab Estonia');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Emetab Misiri');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Emetab Eritrea');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Emetab Spain');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Emetab Ethiopia');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Emetab Finland');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Emetab Fiji');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Ikwembeyotab Falkland');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Emetab Micronesia');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Emetab France');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Emetab Gabon');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Emetab Kibagenge nebo Uingereza');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Emetab Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Emetab Georgia');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Emetab Guiana nebo Ufaransa');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Emetab Ghana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Emetab Gibraltar');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Emetab Greenland');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Emetab Gambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Emetab Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Emetab Guadeloupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Emetab Equatorial Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Emetab Greece');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Emetab Guatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Emetab Guam');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Emetab Guinea-Bissau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Emetab Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Emetab Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Emetab Croatia');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Emetab Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Emetab Hungary');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Emetab Indonesia');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Emetab Ireland');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Emetab Israel');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Emetab India');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Kebebertab araraitab indian Ocean nebo Uingeresa');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Emetab Iraq');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Emetab Iran');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Emetab Iceland');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Emetab Italy');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Emetab Jamaica');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Emetab Jordan');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Emetab Japan');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Emetab Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Emetab Kyrgyzstan');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Emetab Cambodia');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Emetab Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Emetab Comoros');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Emetab Saint Kitts  ak  Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Emetab Korea nebo murot katam');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Emetab korea nebo murot tai');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Emetab Kuwait');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Ikwembeyotab Cayman');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Emetab Kazakhstan');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Emetab Laos');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Emetab Lebanon');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Emetab Lucia Ne');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Emetab Liechtenstein');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Emetab Sri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Emetab Liberia');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Emetab Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Emetab Lithuania');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Emetab Luxembourg');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Emetab Latvia');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Emetab Libya');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Emetab Morocco');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Emetab Monaco');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Emetab Moldova');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Emetab Madagascar');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Ikwembeiyotab Marshall');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Emetab Macedonia');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Emetab Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Emetab Myanmar');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Emetab Mongolia');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Ikwembeiyotab Mariana nebo murot katam');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Emetab Martinique');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Emetab Mauritania');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Emetab Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Emetab Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Emetab Mauritius');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Emetab Maldives');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Emetab Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Emetab Mexico');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Emetab Malaysia');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Emetab Mozambique');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Emetab Namibia');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Emetab New Caledonia');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Emetab niger');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Ikwembeiyotab Norfork');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Emetab Nigeria');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Emetab Nicaragua');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Emetab Holand');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Emetab Norway');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Emetab Nepal');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Emetab Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Emetab Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Emetab New Zealand');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Emetab Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Emetab Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Emetab Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Emetab Polynesia nebo ufaransa');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Emetab Papua New Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Emetab Philippines');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Emetab Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Emetab Poland');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Emetab Peter Ne titil  ak Miquelon');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Emetab Pitcairn');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Emetab Puerto Rico');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Emetab Palestine');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Emetab Portugal');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Emetab Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Emetab Paraguay');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Emetab Qatar');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Emetab Réunion');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Emetab Romania');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Emetab Russia');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Emetab Rwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Emetab Saudi Arabia');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Ikwembeiyotab Solomon');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Emetab Seychelles');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Emetab Sudan');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Emetab Sweden');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Emetab Singapore');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Emetab Helena Ne tilil');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Emetab Slovenia');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Emetab Slovakia');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Emetab Sierra Leone');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'Emetab San Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Emetab Senegal');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Emetab Somalia');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Emetab Suriname');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Emetab São Tomé and Príncipe');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Emetab El Salvador');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Emetab Syria');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Emetab Swaziland');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Ikwembeiyotab Turks ak  Caicos');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Emetab Chad');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Emetab Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Emetab Thailand');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Emetab Tajikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Emetab Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Emetab Timor nebo Murot tai');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Emetab Turkmenistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Emetab Tunisia');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Emetab Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Emetab Turkey');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Emetab Trinidad ak Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Emetab Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Emetab Taiwan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Emetab Tanzania');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Emetab Ukrainie');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Emetab Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Emetab amerika');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Emetab Uruguay');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Emetab Uzibekistani');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Emetab Vatican');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Emetab Vincent netilil ak Grenadines');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Emetab Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Ikwembeyotab British Virgin');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Ikwemweiyotab Amerika');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Emetab Vietnam');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Emetab Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Emetab Walis ak Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Emetab Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Emetab Yemen');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Emetab Mayotte');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Emetab Afrika nebo Murot tai');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Emetab Zambia');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Emetab Zimbabwe');
