CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afaganisitani');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Alibaniya');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Aligerya');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Amerika');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andora');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Angwila');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigwa ne Barabuda');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Arameniya');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Arigentina');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Awusitureliya');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Awusituriya');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Ayalandi');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Ayisirandi');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azerebayijaani');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Baareeni');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahamasi');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangaladesi');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barabadosi');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Belarusi');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belize');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benini');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Beremuda');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Bizanga by\'eSolomooni');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Bizinga by\'e Kepu Veredi');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Bizinga by\'eCago');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Bizinga by\'eFalikalandi');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Bizinga by\'eKomoro');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Bizinga by\'eMalidive');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Bizinga by\'eTaaka ne Kayikosi');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Bizinga bya Antile eby\'abaHolandi');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Bizinga bya Firipino');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Bizinga bya Kkuki');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Bizinga bya Mariso');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Bizinga bya Mariyana eby\'omumambuka');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Bizinga bya Virigini eby\'Amerika');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Bizinga ebya Kayimaani');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Bizinga ebya Virigini ebitwalibwa Bungereza');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Boliviya');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botiswana');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Boziniya Hezegovina');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Bubirigi');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Budaaki');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Bufalansa');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Bugereeki/Buyonaani');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulugariya');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Bungereza');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Buraziiri');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burukina Faso');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Burunayi');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Butaani');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Buyindi');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Caadi');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Cayina');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Cile');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Cuba');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Denimaaka');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominika');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekwado');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'El salivado');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Emireeti');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritureya');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Esitoniya');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Esyopya');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fiji');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finilandi');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gaboni');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambya');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Gana');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Gayana');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Gayana ey\'oku ekweta');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Giburalita');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Gini');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Gini-Bisawu');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Gurenada');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Gurenelandi');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Guyana enfalansa');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Gwadalupe');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Gwamu');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Gwatemala');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Gyogya');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Hangare');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Hayiti');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Holandi');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Hundurasi');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamayika');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japani');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Jjibuti');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Kaledonya mupya');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kambodya');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kameruuni');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Kataa');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazakisitaani');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenya');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirigizisitaani');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Kizinga ky\'eNorofoko');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolombya');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Kongo - Zayire');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Koreya ey\'omumambuka');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Koreya ey\'omumaserengeta');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kosita Rika');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Kote Divwa');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Kurowesya');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kuweti');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Lasa');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Lativya');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Lawosi');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Lebanoni');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesoso');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Leyunyoni');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberya');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libya');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Licitensitayini');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Lipubulika eya Senturafiriki');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Lipubulika ya Ceeka');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Lipubulika ya Dominika');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Lisuwenya');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Lomaniya');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Lukisembaaga');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagasika');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malawi');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malezya');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malita');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Maritiniiki');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Masedoniya');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Mawulisyasi');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mawulitenya');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayotte');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mekisiko');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikuronezya');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Misiri');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Molodova');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monako');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongoliya');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Monteseraati');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Moroko');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mozambiiki');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Myanima');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibiya');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nawuru');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nayijerya');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepalo');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Nije');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikaraguwa');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niyuwe');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Niyuziirandi');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Nowe');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Omaani');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakisitaani');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palawu');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palesitayini');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papwa Nyugini');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paragwayi');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Peru');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitikeeni');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Polandi');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Polinesiya enfalansa');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Potoriko');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Potugaali');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Rwanda');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samowa');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Samowa omumerika');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'Sanimarino');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sanitome ne Purincipe');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Sawudarebya - Buwarabu');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Sawusafirika');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegaalo');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Senti Herena');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Senti Kitisi ne Nevisi');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Senti Luciya');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Senti Piyere ne Mikeloni');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Senti Vinsenti ne Gurendadiini');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Seribya ne Monteneguro');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Sesere');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapowa');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Sipeyini');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Sipuriya');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sirilanka');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Siriya');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Sirovakya');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Sirovenya');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Siyeralewone');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somaliya');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudaani');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Surinaamu');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Swazirandi');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Swideni');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Switizirandi');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tajikisitaani');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Takimenesitaani');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzaniya');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Tayirandi');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Tayiwani');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Timowa');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelawu');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Ttake');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunisya');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Turindaadi ne Tobago');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanawuwatu');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikaani');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venzwera');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vyetinaamu');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Walisi ne Futuna');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Wurugwayi');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Wuzibekisitaani');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Yemeni');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Yindonezya');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Yiraaka');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Yiraani');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Yisirayeri');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Yitale');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Yorodani');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Yuganda');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Yukurayine');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambya');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabwe');
