CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afghanistan');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Africa del Sud');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albania');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Algeria');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Antarctica');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigua e Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Antillas nederlandese');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Arabia Saudita');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Argentina');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armenia');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Australia');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Austria');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azerbaidzhan');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamas');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladesh');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Belgica');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benin');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Bhutan');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Bielorussia');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Birmania/Myanmar');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolivia');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnia e Herzegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswana');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brasil');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgaria');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Cambodgia');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Camerun');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Canada');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Chile');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'China');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Colombia');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Comoros');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Congo');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Corea del Nord');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Corea del Sud');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Croatia');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Cuba');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Cypro');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Danmark');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ecuador');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Egypto');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Emiratos Arabe Unite');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritrea');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Espania');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estonia');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Ethiopia');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finlandia');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Francia');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabon');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambia');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Georgia');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Germania');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ghana');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Grecia');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Groenlandia');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Guinea equatorial');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Guyana francese');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haiti');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Honduras');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Hungaria');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'India');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonesia');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Insula Norfolk');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Insula de Bouvet');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Insula de Natal');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Insulas Cook');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Insulas Feroe');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Insulas Marianna del Nord');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Insulas Marshall');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Insulas Solomon');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Insulas Turcos e Caicos');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Insulas de Caiman');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Irak');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Iran');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Irlanda');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Islanda');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Israel');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Italia');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Japon');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Jordania');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazakhstan');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenya');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kirghizistan');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesotho');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Lettonia');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Libano');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberia');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libya');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Liechtenstein');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lituania');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Macedonia');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagascar');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawi');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malaysia');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Marocco');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mauritania');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mexico');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Micronesia');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldavia');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongolia');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambique');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibia');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Nederlandia');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepal');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nicaragua');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Niger');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nigeria');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norvegia');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Nove Caledonia');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Nove Zelanda');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Oman');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistan');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papua Nove Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguay');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peru');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Philippinas');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Polonia');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Polynesia francese');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portugal');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Regno Unite');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Republica African Central');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Republica Dominican');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Republica Tchec');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Romania');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Ruanda');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Sahara occidental');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samoa american');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marino');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Sancte Christophoro e Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Sancte Lucia');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Sancte Vincente e le Grenadinas');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegal');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seychelles');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sierra Leone');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovachia');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slovenia');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somalia');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Statos Unite');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudan');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Suissa');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Suriname');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Svedia');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Swazilandia');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Syria');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tadzhikistan');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwan');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzania');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Tchad');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Territorio oceanic britanno-indian');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Territorios meridional francese');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Thailandia');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timor del Est');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidad e Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunisia');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Turchia');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turkmenistan');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukraina');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruguay');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Uzbekistan');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuela');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yemen');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambia');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabwe');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'tonga');
