CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'אוגנדה');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'אוזבקיסטן');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'אוסטריה');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'אוסטרליה');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'אוקיאניה פרושה');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'אוקראינה');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'אורוגוואי');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'אזרביג׳ן');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'איחוד האמירויות הערביות');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'איטליה');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'איי אלנד');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'איי בהאמה');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'איי בובה');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'איי הבתולה האמריקניים');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'איי הבתולה הבריטיים');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'איי הרד ואיי מקדונלנד');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'איי ווליס ופוטונה');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'איי טורקס וקאיקוס');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'איי כריסטמס');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'איי מריאנה הצפוניים');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'איי מרשל');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'איי נורפוק');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'איי סיישל');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'איי פארו');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'איי פוקלנד');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'איי קוק');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'איי קוקוס');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'איי קיימן');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'איי שלמה');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'איים קטנים שלחוף ארצות הברית');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'אינדונזיה');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'איסלנד');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'איראן');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'אירלנד');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'אל סלבדור');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'אלבניה');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'אלג׳יריה');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'אנגולה');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'אנגילה');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'אנדורה');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'אנטארקטיקה');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'אנטיגואה וברבודה');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'אנטילים הולנדיים');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'אסטוניה');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'אפגניסטן');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'אקוודור');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'ארגנטינה');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'ארובה');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'אריתראה');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'ארמניה');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'ארצות הברית');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'אתיופיה');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'בהוטן');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'בוטסוואנה');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'בולגריה');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'בוליביה');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'בוסניה והרצגובינה');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'בורונדי');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'בורקינה פאסו');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'בחריין');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'בלארוס');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'בלגיה');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'בליז');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'בנגלדש');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'בנין');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'ברבדוס');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'ברוניי');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'ברזיל');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'בריטניה');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'ברמודה');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'ג׳ורג׳יה הדרומית ואיי סנדוויץ׳ הדרומיים');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'ג׳יבוטי');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'ג׳מייקה');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'ג׳רסי');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'גאבון');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'גאורגיה');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'גאנה');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'גואטמלה');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'גואם');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'גוואדלופ');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'גיאנה');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'גיאנה הצרפתית');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'גיברלטר');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'גיניאה');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'גיניאה המשוונית');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'גיניאה-ביסאו');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'גמביה');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'גרינלנד');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'גרמניה');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'גרנדה');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'גרנסי');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'דומיניקה');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'דייגו גרסיה');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'דנמרק');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'דרום אפריקה');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'דרום קוריאה');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'האי אסנשן');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'האי מאן');
INSERT INTO `country` (`id`, `name`) VALUES ('CP', 'האי קליפרטון');
INSERT INTO `country` (`id`, `name`) VALUES ('EU', 'האיחוד האירופי');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'האיטי');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'האיים הקנריים');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'הודו');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'הוותיקן');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'הולנד');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'הונג קונג - מחוז מנהלי מיוחד של סין');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'הונגריה');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'הונדורס');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'הרפובליקה הדומיניקנית');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'הרפובליקה של מרכז אפריקה');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'השטחים הפלסטיניים');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'וייטנאם');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'ונואטו');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'ונצואלה');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'זימבאבווה');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'זמביה');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'חוף השנהב');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'טג׳יקיסטן');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'טובלו');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'טוגו');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'טונגה');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'טוקלאו');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'טורקיה');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'טורקמניסטן');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'טייוואן');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'טנזניה');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'טריטוריה בריטית באוקיאנוס ההודי');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'טריטוריות דרומיות של צרפת');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'טרינידד וטובגו');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'טריסטן דה קונה');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'יוון');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'יפן');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'ירדן');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'ישראל');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'כווית');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'כף ורדה');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'לאוס');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'לבנון');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'לוב');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'לוקסמבורג');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'לטביה');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'ליבריה');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'ליטא');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'ליכטנשטיין');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'לסוטו');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'מאוריטניה');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'מאוריציוס');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'מאיוט');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'מאלי');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'מדגסקר');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'מוזמביק');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'מולדובה');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'מונגוליה');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'מונטנגרו');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'מונסראט');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'מונקו');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'מזרח טימור');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'מייאנמאר');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'מיקרונזיה');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'מלאווי');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'מלדיבים');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'מלזיה');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'מלטה');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'מצרים');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'מקאו - מחוז מנהלי מיוחד של סין');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'מקדוניה');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'מקסיקו');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'מרוקו');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'מרטיניק');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'נאורו');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'נורווגיה');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'ניגריה');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'ניו זילנד');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'ניווה');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'ניז׳ר');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'ניקרגואה');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'נמיביה');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'נפאל');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'סאו טומה ופרינסיפה');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'סאוטה ומלייה');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'סהרה המערבית');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'סודן');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'סווזילנד');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'סוולבארד וז׳אן מאיין');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'סומליה');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'סוריה');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'סורינם');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'סיירה לאונה');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'סין');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'סינגפור');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'סלובניה');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'סלובקיה');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'סמואה');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'סמואה האמריקנית');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'סן מרינו');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'סנגל');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'סנט ברתולומיאו');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'סנט הלנה');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'סנט וינסנט והגרנדינים');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'סנט לוסיה');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'סנט מרטין');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'סנט פייר ומיקלון');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'סנט קיטס ונוויס');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'ספרד');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'סרביה');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'סרביה ומונטנגרו');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'סרי לנקה');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'עומאן');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'עיראק');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'ערב הסעודית');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'פאלאו');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'פולין');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'פולינזיה הצרפתית');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'פורטו ריקו');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'פורטוגל');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'פיג׳י');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'פיטקרן');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'פיליפינים');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'פינלנד');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'פנמה');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'פפואה גיניאה החדשה');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'פקיסטן');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'פרגוואי');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'פרו');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'צ׳אד');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'צ׳ילה');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'צ׳כיה');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'צפון קוריאה');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'צרפת');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'קובה');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'קולומביה');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'קומורוס');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'קונגו - ברזאויל');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'קונגו - קינשאסה');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'קוסטה ריקה');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'קזחסטן');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'קטאר');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'קירגיזסטן');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'קיריבאטי');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'קלדוניה החדשה');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'קמבודיה');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'קמרון');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'קנדה');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'קניה');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'קפריסין');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'קרואטיה');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'ראוניון');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'רואנדה');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'רומניה');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'רוסיה');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'שוודיה');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'שווייץ');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'תאילנד');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'תוניסיה');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'תימן');
