CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY("id"));

INSERT INTO "country" ("id", "name") VALUES ('AC', 'Ascension Island');
INSERT INTO "country" ("id", "name") VALUES ('AD', '𐐈𐑌𐐼𐐱𐑉𐐲');
INSERT INTO "country" ("id", "name") VALUES ('AE', '𐐏𐐭𐑌𐐴𐐼𐐮𐐼 𐐇𐑉𐐲𐐺 𐐇𐑋𐐲𐑉𐐩𐐻𐑅');
INSERT INTO "country" ("id", "name") VALUES ('AF', '𐐈𐑁𐑀𐐰𐑌𐐲𐑅𐐻𐐰𐑌');
INSERT INTO "country" ("id", "name") VALUES ('AG', '𐐈𐑌𐐻𐐨𐑀𐐶𐐲 𐐰𐑌𐐼 𐐒𐐪𐑉𐐺𐐷𐐭𐐼𐐲');
INSERT INTO "country" ("id", "name") VALUES ('AI', '𐐈𐑍𐑀𐐶𐐮𐑊𐐲');
INSERT INTO "country" ("id", "name") VALUES ('AL', '𐐈𐑊𐐺𐐩𐑌𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('AM', '𐐂𐑉𐑋𐐨𐑌𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('AN', '𐐤𐐯𐑄𐐲𐑉𐑊𐐲𐑌𐐼𐑆 𐐈𐑌𐐻𐐮𐑊𐐨𐑆');
INSERT INTO "country" ("id", "name") VALUES ('AO', '𐐈𐑌𐑀𐐬𐑊𐐲');
INSERT INTO "country" ("id", "name") VALUES ('AQ', '𐐈𐑌𐐻𐐪𐑉𐐿𐐻𐐮𐐿𐐲');
INSERT INTO "country" ("id", "name") VALUES ('AR', '𐐂𐑉𐐾𐐲𐑌𐐻𐐨𐑌𐐲');
INSERT INTO "country" ("id", "name") VALUES ('AS', '𐐊𐑋𐐯𐑉𐐲𐐿𐐲𐑌 𐐝𐐲𐑋𐐬𐐲');
INSERT INTO "country" ("id", "name") VALUES ('AT', '𐐉𐑅𐐻𐑉𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('AU', '𐐉𐑅𐐻𐑉𐐩𐑊𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('AW', '𐐊𐑉𐐭𐐺𐐲');
INSERT INTO "country" ("id", "name") VALUES ('AX', '𐐈𐑊𐐰𐑌𐐼 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('AZ', '𐐈𐑆𐐲𐑉𐐺𐐴𐑈𐐪𐑌');
INSERT INTO "country" ("id", "name") VALUES ('BA', '𐐒𐐱𐑆𐑌𐐨𐐲 𐐰𐑌𐐼 𐐐𐐲𐑉𐐻𐑅𐐲𐑀𐐬𐑂𐐨𐑌𐐲');
INSERT INTO "country" ("id", "name") VALUES ('BB', '𐐒𐐪𐑉𐐺𐐩𐐼𐐬𐑅');
INSERT INTO "country" ("id", "name") VALUES ('BD', '𐐒𐐪𐑍𐑀𐑊𐐲𐐼𐐯𐑇');
INSERT INTO "country" ("id", "name") VALUES ('BE', '𐐒𐐯𐑊𐐾𐐲𐑋');
INSERT INTO "country" ("id", "name") VALUES ('BF', '𐐒𐐲𐑉𐐿𐐩𐑌𐐲 𐐙𐐰𐑅𐐬');
INSERT INTO "country" ("id", "name") VALUES ('BG', '𐐒𐐲𐑊𐑀𐐯𐑉𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('BH', '𐐒𐐪𐑉𐐩𐑌');
INSERT INTO "country" ("id", "name") VALUES ('BI', '𐐒𐐲𐑉𐐳𐑌𐐼𐐨');
INSERT INTO "country" ("id", "name") VALUES ('BJ', '𐐒𐐲𐑌𐐨𐑌');
INSERT INTO "country" ("id", "name") VALUES ('BL', '𐐝𐐩𐑌𐐻 𐐒𐐪𐑉𐐻𐐩𐑊𐐲𐑋𐐨');
INSERT INTO "country" ("id", "name") VALUES ('BM', '𐐒𐐲𐑉𐑋𐐷𐐭𐐼𐐲');
INSERT INTO "country" ("id", "name") VALUES ('BN', '𐐒𐑉𐐭𐑌𐐴');
INSERT INTO "country" ("id", "name") VALUES ('BO', '𐐒𐐬𐑊𐐮𐑂𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('BQ', '𐐒𐑉𐐮𐐼𐐮𐑇 𐐈𐑌𐐻𐐪𐑉𐐿𐐻𐐮𐐿 𐐓𐐯𐑉𐐲𐐻𐐱𐑉𐐨');
INSERT INTO "country" ("id", "name") VALUES ('BR', '𐐒𐑉𐐲𐑆𐐮𐑊');
INSERT INTO "country" ("id", "name") VALUES ('BS', '𐐒𐐲𐐸𐐪𐑋𐐲𐑅');
INSERT INTO "country" ("id", "name") VALUES ('BT', '𐐒𐐭𐐻𐐪𐑌');
INSERT INTO "country" ("id", "name") VALUES ('BV', '𐐒𐐭𐑂𐐩 𐐌𐑊𐐲𐑌𐐼');
INSERT INTO "country" ("id", "name") VALUES ('BW', '𐐒𐐪𐐻𐑅𐐶𐐪𐑌𐐲');
INSERT INTO "country" ("id", "name") VALUES ('BY', '𐐒𐐯𐑊𐐲𐑉𐐭𐑅');
INSERT INTO "country" ("id", "name") VALUES ('BZ', '𐐒𐐲𐑊𐐨𐑆');
INSERT INTO "country" ("id", "name") VALUES ('CA', '𐐗𐐰𐑌𐐲𐐼𐐲');
INSERT INTO "country" ("id", "name") VALUES ('CC', '𐐗𐐬𐐿𐐬𐑆 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('CD', '𐐗𐐪𐑍𐑀𐐬 - 𐐗𐐲𐑌𐑇𐐪𐑅𐐲');
INSERT INTO "country" ("id", "name") VALUES ('CF', '𐐝𐐯𐑌𐐻𐑉𐐲𐑊 𐐈𐑁𐑉𐐲𐐿𐐲𐑌 𐐡𐐨𐐹𐐲𐐺𐑊𐐮𐐿');
INSERT INTO "country" ("id", "name") VALUES ('CG', '𐐗𐐪𐑍𐑀𐐬 - 𐐒𐑉𐐪𐑆𐐲𐑂𐐮𐑊');
INSERT INTO "country" ("id", "name") VALUES ('CH', '𐐝𐐶𐐮𐐻𐑅𐐲𐑉𐑊𐐲𐑌𐐼');
INSERT INTO "country" ("id", "name") VALUES ('CI', '𐐌𐑂𐑉𐐨 𐐗𐐬𐑅𐐻');
INSERT INTO "country" ("id", "name") VALUES ('CK', '𐐗𐐳𐐿 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('CL', '𐐕𐐨𐑊𐐩');
INSERT INTO "country" ("id", "name") VALUES ('CM', '𐐗𐐰𐑋𐐲𐑉𐐭𐑌');
INSERT INTO "country" ("id", "name") VALUES ('CN', '𐐕𐐴𐑌𐐲');
INSERT INTO "country" ("id", "name") VALUES ('CO', '𐐗𐐲𐑊𐐲𐑋𐐺𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('CP', 'Clipperton Island');
INSERT INTO "country" ("id", "name") VALUES ('CR', '𐐗𐐱𐑅𐐻𐐲 𐐡𐐨𐐿𐐲');
INSERT INTO "country" ("id", "name") VALUES ('CS', '𐐝𐐲𐑉𐐺𐐨𐐲 𐐰𐑌𐐼 𐐣𐐪𐑌𐐲𐑌𐐨𐑀𐑉𐐬');
INSERT INTO "country" ("id", "name") VALUES ('CT', '𐐗𐐰𐑌𐐻𐐪𐑌 𐐰𐑌𐐼 𐐇𐑌𐐼𐐲𐑉𐐺𐐯𐑉𐐨 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('CU', '𐐗𐐷𐐭𐐺𐐲');
INSERT INTO "country" ("id", "name") VALUES ('CV', '𐐗𐐩𐐹 𐐚𐐯𐑉𐐼𐐨');
INSERT INTO "country" ("id", "name") VALUES ('CX', '𐐗𐑉𐐮𐑅𐑋𐐲𐑅 𐐌𐑊𐐲𐑌𐐼');
INSERT INTO "country" ("id", "name") VALUES ('CY', '𐐝𐐴𐐹𐑉𐐲𐑅');
INSERT INTO "country" ("id", "name") VALUES ('CZ', '𐐕𐐯𐐿 𐐡𐐨𐐹𐐲𐐺𐑊𐐮𐐿');
INSERT INTO "country" ("id", "name") VALUES ('DD', '𐐀𐑅𐐻 𐐖𐐲𐑉𐑋𐐲𐑌𐐨');
INSERT INTO "country" ("id", "name") VALUES ('DE', '𐐖𐐲𐑉𐑋𐐲𐑌𐐨');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'Diego Garcia');
INSERT INTO "country" ("id", "name") VALUES ('DJ', '𐐖𐐲𐐺𐐭𐐼𐐨');
INSERT INTO "country" ("id", "name") VALUES ('DK', '𐐔𐐯𐑌𐑋𐐪𐑉𐐿');
INSERT INTO "country" ("id", "name") VALUES ('DM', '𐐔𐐪𐑋𐐲𐑌𐐨𐐿𐐲');
INSERT INTO "country" ("id", "name") VALUES ('DO', '𐐔𐐲𐑋𐐮𐑌𐐲𐐿𐐲𐑌 𐐡𐐨𐐹𐐲𐐺𐑊𐐮𐐿');
INSERT INTO "country" ("id", "name") VALUES ('DZ', '𐐈𐑊𐐾𐐮𐑉𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'Ceuta and Melilla');
INSERT INTO "country" ("id", "name") VALUES ('EC', '𐐇𐐿𐐶𐐲𐐼𐐱𐑉');
INSERT INTO "country" ("id", "name") VALUES ('EE', '𐐇𐑅𐐻𐐬𐑌𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('EG', '𐐀𐐾𐐲𐐹𐐻');
INSERT INTO "country" ("id", "name") VALUES ('EH', '𐐎𐐯𐑅𐐻𐐲𐑉𐑌 𐐝𐐲𐐸𐐱𐑉𐐲');
INSERT INTO "country" ("id", "name") VALUES ('ER', '𐐇𐑉𐐮𐐻𐑉𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('ES', '𐐝𐐹𐐩𐑌');
INSERT INTO "country" ("id", "name") VALUES ('ET', '𐐀𐑃𐐨𐐬𐐹𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('EU', '𐐏𐐲𐑉𐐲𐐹𐐨𐐲𐑌 𐐏𐐭𐑌𐐷𐐲𐑌');
INSERT INTO "country" ("id", "name") VALUES ('FI', '𐐙𐐮𐑌𐑊𐐲𐑌𐐼');
INSERT INTO "country" ("id", "name") VALUES ('FJ', '𐐙𐐨𐐾𐐨');
INSERT INTO "country" ("id", "name") VALUES ('FK', '𐐙𐐪𐑊𐐿𐑊𐐲𐑌𐐼 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('FM', '𐐣𐐴𐐿𐑉𐐲𐑌𐐨𐑈𐐲');
INSERT INTO "country" ("id", "name") VALUES ('FO', '𐐙𐐯𐑉𐐬 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('FQ', '𐐙𐑉𐐯𐑌𐐽 𐐝𐐲𐑄𐐲𐑉𐑌 𐐰𐑌𐐼 𐐈𐑌𐐻𐐪𐑉𐐿𐐻𐐮𐐿 𐐓𐐯𐑉𐐲𐐻𐐱𐑉𐐨𐑆');
INSERT INTO "country" ("id", "name") VALUES ('FR', '𐐙𐑉𐐰𐑌𐑅');
INSERT INTO "country" ("id", "name") VALUES ('FX', '𐐣𐐯𐐻𐑉𐐲𐐹𐐪𐑊𐐲𐐻𐐲𐑌 𐐙𐑉𐐰𐑌𐑅');
INSERT INTO "country" ("id", "name") VALUES ('GA', '𐐘𐐲𐐺𐐪𐑌');
INSERT INTO "country" ("id", "name") VALUES ('GB', '𐐏𐐭𐑌𐐴𐐻𐐲𐐼 𐐗𐐨𐑍𐐼𐐲𐑋');
INSERT INTO "country" ("id", "name") VALUES ('GD', '𐐘𐑉𐐲𐑌𐐩𐐼𐐲');
INSERT INTO "country" ("id", "name") VALUES ('GE', '𐐖𐐱𐑉𐐾𐐲');
INSERT INTO "country" ("id", "name") VALUES ('GF', '𐐙𐑉𐐯𐑌𐐽 𐐘𐐨𐐪𐑌𐐲');
INSERT INTO "country" ("id", "name") VALUES ('GG', '𐐘𐐲𐑉𐑌𐑆𐐨');
INSERT INTO "country" ("id", "name") VALUES ('GH', '𐐘𐐪𐑌𐐲');
INSERT INTO "country" ("id", "name") VALUES ('GI', '𐐖𐐲𐐺𐑉𐐱𐑊𐐻𐐲𐑉');
INSERT INTO "country" ("id", "name") VALUES ('GL', '𐐘𐑉𐐨𐑌𐑊𐐲𐑌𐐼');
INSERT INTO "country" ("id", "name") VALUES ('GM', '𐐘𐐰𐑋𐐺𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('GN', '𐐘𐐮𐑌𐐨');
INSERT INTO "country" ("id", "name") VALUES ('GP', '𐐘𐐶𐐪𐐼𐐲𐑊𐐭𐐹');
INSERT INTO "country" ("id", "name") VALUES ('GQ', '𐐇𐐿𐐶𐐲𐐻𐐱𐑉𐐨𐐲𐑊 𐐘𐐮𐑌𐐨');
INSERT INTO "country" ("id", "name") VALUES ('GR', '𐐘𐑉𐐨𐑅');
INSERT INTO "country" ("id", "name") VALUES ('GS', '𐐝𐐵𐑃 𐐖𐐱𐑉𐐾𐐲 𐐰𐑌𐐼 𐑄 𐐝𐐵𐑃 𐐝𐐰𐑌𐐼𐐶𐐮𐐽 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('GT', '𐐘𐐶𐐪𐐼𐐲𐑋𐐪𐑊𐐲');
INSERT INTO "country" ("id", "name") VALUES ('GU', '𐐘𐐶𐐪𐑋');
INSERT INTO "country" ("id", "name") VALUES ('GW', '𐐘𐐮𐑌𐐨-𐐒𐐮𐑅𐐵');
INSERT INTO "country" ("id", "name") VALUES ('GY', '𐐘𐐴𐐰𐑌𐐲');
INSERT INTO "country" ("id", "name") VALUES ('HK', '𐐐𐐬𐑍 𐐗𐐬𐑍 𐐝𐐈𐐡 𐐕𐐴𐑌𐐲');
INSERT INTO "country" ("id", "name") VALUES ('HM', '𐐐𐐲𐑉𐐼 𐐌𐑊𐐲𐑌𐐼 𐐰𐑌𐐼 𐐣𐐿𐐔𐐱𐑌𐐲𐑊𐐼 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('HN', '𐐐𐐪𐑌𐐼𐐭𐑉𐐲𐑅');
INSERT INTO "country" ("id", "name") VALUES ('HR', '𐐗𐑉𐐬𐐩𐑇𐐲');
INSERT INTO "country" ("id", "name") VALUES ('HT', '𐐐𐐩𐐻𐐨');
INSERT INTO "country" ("id", "name") VALUES ('HU', '𐐐𐐲𐑍𐑀𐐲𐑉𐐨');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'Canary Islands');
INSERT INTO "country" ("id", "name") VALUES ('ID', '𐐆𐑌𐐼𐐲𐑌𐐨𐑈𐐲');
INSERT INTO "country" ("id", "name") VALUES ('IE', '𐐌𐑉𐑊𐐲𐑌𐐼');
INSERT INTO "country" ("id", "name") VALUES ('IL', '𐐆𐑆𐑉𐐨𐐲𐑊');
INSERT INTO "country" ("id", "name") VALUES ('IM', '𐐌𐐲𐑊 𐐲𐑁 𐐣𐐰𐑌');
INSERT INTO "country" ("id", "name") VALUES ('IN', '𐐆𐑌𐐼𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('IO', '𐐒𐑉𐐮𐐼𐐮𐑇 𐐆𐑌𐐼𐐨𐐲𐑌 𐐄𐑇𐐲𐑌 𐐓𐐯𐑉𐐲𐐻𐐱𐑉𐐨');
INSERT INTO "country" ("id", "name") VALUES ('IQ', '𐐆𐑉𐐰𐐿');
INSERT INTO "country" ("id", "name") VALUES ('IR', '𐐆𐑉𐐪𐑌');
INSERT INTO "country" ("id", "name") VALUES ('IS', '𐐌𐑅𐑊𐐲𐑌𐐼');
INSERT INTO "country" ("id", "name") VALUES ('IT', '𐐆𐐻𐐲𐑊𐐨');
INSERT INTO "country" ("id", "name") VALUES ('JE', '𐐖𐐲𐑉𐑆𐐨');
INSERT INTO "country" ("id", "name") VALUES ('JM', '𐐖𐐲𐑋𐐩𐐿𐐲');
INSERT INTO "country" ("id", "name") VALUES ('JO', '𐐖𐐱𐑉𐐼𐐲𐑌');
INSERT INTO "country" ("id", "name") VALUES ('JP', '𐐖𐐲𐐹𐐰𐑌');
INSERT INTO "country" ("id", "name") VALUES ('JT', '𐐖𐐪𐑌𐑅𐐻𐐲𐑌 𐐌𐑊𐐲𐑌𐐼');
INSERT INTO "country" ("id", "name") VALUES ('KE', '𐐗𐐯𐑌𐐷𐐲');
INSERT INTO "country" ("id", "name") VALUES ('KG', '𐐗𐐮𐑉𐑀𐐲𐑅𐐻𐐰𐑌');
INSERT INTO "country" ("id", "name") VALUES ('KH', '𐐗𐐰𐑋𐐺𐐬𐐼𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('KI', '𐐗𐐮𐑉𐐲𐐺𐐪𐐻𐐨');
INSERT INTO "country" ("id", "name") VALUES ('KM', '𐐗𐐪𐑋𐐲𐑉𐐬𐑆');
INSERT INTO "country" ("id", "name") VALUES ('KN', '𐐝𐐩𐑌𐐻 𐐗𐐮𐐻𐑅 𐐰𐑌𐐼 𐐤𐐨𐑂𐐮𐑅');
INSERT INTO "country" ("id", "name") VALUES ('KP', '𐐤𐐱𐑉𐑃 𐐗𐐲𐑉𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('KR', '𐐝𐐵𐑃 𐐗𐐲𐑉𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('KW', '𐐗𐐲𐐶𐐩𐐻');
INSERT INTO "country" ("id", "name") VALUES ('KY', '𐐗𐐩𐑋𐐲𐑌 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('KZ', '𐐗𐐲𐑆𐐪𐐿𐑅𐐻𐐪𐑌');
INSERT INTO "country" ("id", "name") VALUES ('LA', '𐐢𐐪𐐬𐑅');
INSERT INTO "country" ("id", "name") VALUES ('LB', '𐐢𐐯𐐺𐐲𐑌𐐪𐑌');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Saint Lucia');
INSERT INTO "country" ("id", "name") VALUES ('LI', '𐐢𐐮𐐿𐐻𐐲𐑌𐑅𐐻𐐴𐑌');
INSERT INTO "country" ("id", "name") VALUES ('LK', '𐐟𐑉𐐨 𐐢𐐰𐑍𐐿𐐲');
INSERT INTO "country" ("id", "name") VALUES ('LR', '𐐢𐐴𐐺𐐮𐑉𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('LS', '𐐢𐐲𐑅𐐬𐑃𐐬');
INSERT INTO "country" ("id", "name") VALUES ('LT', '𐐢𐐮𐑃𐐲𐐶𐐩𐑌𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('LU', '𐐢𐐲𐐿𐑅𐐲𐑋𐐺𐐲𐑉𐑀');
INSERT INTO "country" ("id", "name") VALUES ('LV', '𐐢𐐰𐐻𐑂𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('LY', '𐐢𐐮𐐺𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('MA', '𐐣𐐲𐑉𐐪𐐿𐐬');
INSERT INTO "country" ("id", "name") VALUES ('MC', '𐐣𐐪𐑌𐐲𐐿𐐬');
INSERT INTO "country" ("id", "name") VALUES ('MD', '𐐣𐐱𐑊𐐼𐐬𐑂𐐲');
INSERT INTO "country" ("id", "name") VALUES ('ME', '𐐣𐐪𐑌𐐲𐑌𐐨𐑀𐑉𐐬');
INSERT INTO "country" ("id", "name") VALUES ('MF', '𐐝𐐩𐑌𐐻 𐐣𐐪𐑉𐐻𐑌');
INSERT INTO "country" ("id", "name") VALUES ('MG', '𐐣𐐰𐐼𐐲𐑀𐐰𐑅𐐿𐐲𐑉');
INSERT INTO "country" ("id", "name") VALUES ('MH', '𐐣𐐪𐑉𐑇𐐲𐑊 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('MI', '𐐣𐐮𐐼𐐶𐐩 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('MK', '𐐣𐐰𐑅𐐲𐐼𐐬𐑌𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('ML', '𐐣𐐪𐑊𐐨');
INSERT INTO "country" ("id", "name") VALUES ('MM', '𐐣𐐨𐐲𐑌𐑋𐐪𐑉');
INSERT INTO "country" ("id", "name") VALUES ('MN', '𐐣𐐪𐑍𐑀𐐬𐑊𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('MO', '𐐣𐐲𐐿𐐵 𐐝𐐈𐐡 𐐕𐐴𐑌𐐲');
INSERT INTO "country" ("id", "name") VALUES ('MP', '𐐤𐐱𐑉𐑄𐐲𐑉𐑌 𐐣𐐰𐑉𐐨𐐱𐑌𐐲 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('MQ', '𐐣𐐪𐑉𐐻𐑌𐐨𐐿');
INSERT INTO "country" ("id", "name") VALUES ('MR', '𐐣𐐱𐑉𐐲𐐻𐐩𐑌𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('MS', '𐐣𐐪𐑌𐐻𐑅𐐲𐑉𐐪𐐻');
INSERT INTO "country" ("id", "name") VALUES ('MT', '𐐣𐐱𐑊𐐻𐐲');
INSERT INTO "country" ("id", "name") VALUES ('MU', '𐐣𐐱𐑉𐐮𐑇𐐲𐑅');
INSERT INTO "country" ("id", "name") VALUES ('MV', '𐐣𐐪𐑊𐐼𐐨𐑂𐑆');
INSERT INTO "country" ("id", "name") VALUES ('MW', '𐐣𐐲𐑊𐐪𐐶𐐨');
INSERT INTO "country" ("id", "name") VALUES ('MX', '𐐣𐐯𐐿𐑅𐐲𐐿𐐬');
INSERT INTO "country" ("id", "name") VALUES ('MY', '𐐣𐐲𐑊𐐩𐑈𐐲');
INSERT INTO "country" ("id", "name") VALUES ('MZ', '𐐣𐐬𐑆𐐰𐑋𐐺𐐨𐐿');
INSERT INTO "country" ("id", "name") VALUES ('NA', '𐐤𐐲𐑋𐐮𐐺𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('NC', '𐐤𐐭 𐐗𐐰𐑊𐐲𐐼𐐬𐑌𐐷𐐲');
INSERT INTO "country" ("id", "name") VALUES ('NE', '𐐤𐐴𐐾𐐲𐑉');
INSERT INTO "country" ("id", "name") VALUES ('NF', '𐐤𐐱𐑉𐑁𐐲𐐿 𐐌𐑊𐐲𐑌𐐼');
INSERT INTO "country" ("id", "name") VALUES ('NG', '𐐤𐐴𐐾𐐮𐑉𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('NI', '𐐤𐐮𐐿𐐲𐑉𐐪𐑀𐐶𐐲');
INSERT INTO "country" ("id", "name") VALUES ('NL', '𐐤𐐯𐑄𐐲𐑉𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('NO', '𐐤𐐱𐑉𐐶𐐩');
INSERT INTO "country" ("id", "name") VALUES ('NP', '𐐤𐐩𐐹𐐪𐑊');
INSERT INTO "country" ("id", "name") VALUES ('NQ', '𐐔𐑉𐐱𐑌𐐮𐑍 𐐣𐐱𐐼 𐐢𐐰𐑌𐐼');
INSERT INTO "country" ("id", "name") VALUES ('NR', '𐐤𐐪𐐭𐑉𐐭');
INSERT INTO "country" ("id", "name") VALUES ('NT', '𐐤𐐭𐐻𐑉𐐲𐑊 𐐞𐐬𐑌');
INSERT INTO "country" ("id", "name") VALUES ('NU', '𐐤𐐷𐐭𐐩');
INSERT INTO "country" ("id", "name") VALUES ('NZ', '𐐤𐐭 𐐞𐐨𐑊𐐲𐑌𐐼');
INSERT INTO "country" ("id", "name") VALUES ('OM', '𐐄𐑋𐐲𐑌');
INSERT INTO "country" ("id", "name") VALUES ('PA', '𐐑𐐰𐑌𐐲𐑋𐐪');
INSERT INTO "country" ("id", "name") VALUES ('PC', '𐐑𐐲𐑅𐐮𐑁𐐮𐐿 𐐌𐑊𐐲𐑌𐐼𐑆 𐐓𐑉𐐲𐑅𐐻 𐐓𐐯𐑉𐐲𐐻𐐱𐑉𐐨');
INSERT INTO "country" ("id", "name") VALUES ('PE', '𐐑𐐲𐑉𐐭');
INSERT INTO "country" ("id", "name") VALUES ('PF', '𐐙𐑉𐐯𐑌𐐽 𐐑𐐪𐑊𐐲𐑌𐐨𐑈𐐲');
INSERT INTO "country" ("id", "name") VALUES ('PG', '𐐑𐐰𐐹𐐷𐐳𐐲 𐐤𐐭 𐐘𐐮𐑌𐐨');
INSERT INTO "country" ("id", "name") VALUES ('PH', '𐐙𐐮𐑊𐐲𐐹𐐨𐑌𐑆');
INSERT INTO "country" ("id", "name") VALUES ('PK', '𐐑𐐰𐐿𐐲𐑅𐐻𐐰𐑌');
INSERT INTO "country" ("id", "name") VALUES ('PL', '𐐑𐐬𐑊𐐲𐑌𐐼');
INSERT INTO "country" ("id", "name") VALUES ('PM', '𐐝𐐩𐑌𐐻 𐐑𐐨𐐯𐑉 𐐰𐑌𐐼 𐐣𐐨𐐿𐐲𐑊𐐪𐑌');
INSERT INTO "country" ("id", "name") VALUES ('PN', '𐐑𐐮𐐻𐐿𐐯𐑉𐑌');
INSERT INTO "country" ("id", "name") VALUES ('PR', '𐐑𐐶𐐯𐑉𐐻𐐬 𐐡𐐨𐐿𐐬');
INSERT INTO "country" ("id", "name") VALUES ('PS', '𐐑𐐰𐑊𐐲𐑅𐐻𐐮𐑌𐐨𐐲𐑌 𐐓𐐯𐑉𐐲𐐻𐐱𐑉𐐨');
INSERT INTO "country" ("id", "name") VALUES ('PT', '𐐑𐐱𐑉𐐽𐐲𐑀𐐲𐑊');
INSERT INTO "country" ("id", "name") VALUES ('PU', '𐐏.𐐝. 𐐣𐐮𐑅𐐲𐑊𐐩𐑌𐐨𐐲𐑅 𐐑𐐲𐑅𐐮𐑁𐐮𐐿 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('PW', '𐐑𐐲𐑊𐐵');
INSERT INTO "country" ("id", "name") VALUES ('PY', '𐐑𐐯𐑉𐐲𐑀𐐶𐐴');
INSERT INTO "country" ("id", "name") VALUES ('PZ', '𐐑𐐰𐑌𐐲𐑋𐐪 𐐗𐐲𐑌𐐰𐑊 𐐞𐐬𐑌');
INSERT INTO "country" ("id", "name") VALUES ('QA', '𐐗𐐲𐐻𐐪𐑉');
INSERT INTO "country" ("id", "name") VALUES ('QO', '𐐍𐐻𐑊𐐴𐐮𐑍 𐐄𐑇𐐨𐐰𐑌𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('RE', '𐐡𐐨𐐷𐐭𐑌𐐷𐐲𐑌');
INSERT INTO "country" ("id", "name") VALUES ('RO', '𐐡𐐬𐑋𐐩𐑌𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('RS', '𐐝𐐲𐑉𐐺𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('RU', '𐐡𐐲𐑇𐐲');
INSERT INTO "country" ("id", "name") VALUES ('RW', '𐐡𐐲𐐶𐐪𐑌𐐼𐐲');
INSERT INTO "country" ("id", "name") VALUES ('SA', '𐐝𐐵𐐼𐐨 𐐊𐑉𐐩𐐺𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('SB', '𐐝𐐪𐑊𐐲𐑋𐐲𐑌 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('SC', '𐐝𐐩𐑇𐐯𐑊𐑆');
INSERT INTO "country" ("id", "name") VALUES ('SD', '𐐝𐐭𐐼𐐰𐑌');
INSERT INTO "country" ("id", "name") VALUES ('SE', '𐐝𐐶𐐨𐐼𐑌');
INSERT INTO "country" ("id", "name") VALUES ('SG', '𐐝𐐮𐑍𐐲𐐹𐐱𐑉');
INSERT INTO "country" ("id", "name") VALUES ('SH', '𐐝𐐩𐑌𐐻 𐐐𐐯𐑊𐐲𐑌𐐲');
INSERT INTO "country" ("id", "name") VALUES ('SI', '𐐝𐑊𐐬𐑂𐐨𐑌𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('SJ', '𐐝𐑂𐐪𐑊𐐺𐐪𐑉𐐼 𐐰𐑌𐐼 𐐖𐐰𐑌 𐐣𐐴𐐲𐑌');
INSERT INTO "country" ("id", "name") VALUES ('SK', '𐐝𐑊𐐬𐑂𐐪𐐿𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('SL', '𐐝𐐨𐐯𐑉𐐲 𐐢𐐨𐐬𐑌');
INSERT INTO "country" ("id", "name") VALUES ('SM', '𐐝𐐪𐑌 𐐣𐐲𐑉𐐨𐑌𐐬');
INSERT INTO "country" ("id", "name") VALUES ('SN', '𐐝𐐯𐑌𐐲𐑀𐐱𐑊');
INSERT INTO "country" ("id", "name") VALUES ('SO', '𐐝𐐲𐑋𐐪𐑊𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('SR', '𐐝𐐭𐑉𐐲𐑌𐐪𐑋');
INSERT INTO "country" ("id", "name") VALUES ('ST', '𐐝𐐵 𐐓𐐬𐑋 𐐰𐑌𐐼 𐐑𐑉𐐮𐑌𐐽𐐮𐐹𐐩');
INSERT INTO "country" ("id", "name") VALUES ('SU', '𐐏𐐭𐑌𐐷𐐲𐑌 𐐲𐑂 𐐝𐐬𐑂𐐨𐐯𐐻 𐐝𐐬𐑇𐐲𐑊𐐮𐑅𐐻 𐐡𐐨𐐹𐐲𐐺𐑊𐐮𐐿𐑅');
INSERT INTO "country" ("id", "name") VALUES ('SV', '𐐇𐑊 𐐝𐐰𐑊𐑂𐐲𐐼𐐱𐑉');
INSERT INTO "country" ("id", "name") VALUES ('SY', '𐐝𐐮𐑉𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('SZ', '𐐝𐐶𐐪𐑆𐐨𐑊𐐰𐑌𐐼');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'Tristan da Cunha');
INSERT INTO "country" ("id", "name") VALUES ('TC', '𐐓𐐲𐑉𐐿𐑅 𐐰𐑌𐐼 𐐗𐐴𐐿𐐬𐑆 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('TD', '𐐕𐐰𐐼');
INSERT INTO "country" ("id", "name") VALUES ('TF', '𐐙𐑉𐐯𐑌𐐽 𐐝𐐲𐑄𐐲𐑉𐑌 𐐓𐐯𐑉𐐲𐐻𐐱𐑉𐐨𐑆');
INSERT INTO "country" ("id", "name") VALUES ('TG', '𐐓𐐬𐑀𐐬');
INSERT INTO "country" ("id", "name") VALUES ('TH', '𐐓𐐴𐑊𐐰𐑌𐐼');
INSERT INTO "country" ("id", "name") VALUES ('TJ', '𐐓𐐲𐐾𐐨𐐿𐐲𐑅𐐻𐐰𐑌');
INSERT INTO "country" ("id", "name") VALUES ('TK', '𐐓𐐬𐐿𐐯𐑊𐐵');
INSERT INTO "country" ("id", "name") VALUES ('TL', '𐐀𐑅𐐻 𐐓𐐨𐑋𐐱𐑉');
INSERT INTO "country" ("id", "name") VALUES ('TM', '𐐓𐐲𐑉𐐿𐑋𐐯𐑌𐐲𐑅𐐻𐐰𐑌');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunisia');
INSERT INTO "country" ("id", "name") VALUES ('TO', '𐐓𐐪𐑍𐑀𐐲');
INSERT INTO "country" ("id", "name") VALUES ('TR', '𐐓𐐲𐑉𐐿𐐨');
INSERT INTO "country" ("id", "name") VALUES ('TT', '𐐓𐑉𐐮𐑌𐐮𐐼𐐰𐐼 𐐰𐑌𐐼 𐐓𐐲𐐺𐐩𐑀𐐬');
INSERT INTO "country" ("id", "name") VALUES ('TV', '𐐓𐐲𐑂𐐪𐑊𐐭');
INSERT INTO "country" ("id", "name") VALUES ('TW', '𐐓𐐴𐐶𐐪𐑌');
INSERT INTO "country" ("id", "name") VALUES ('TZ', '𐐓𐐰𐑌𐑆𐐲𐑌𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukraine');
INSERT INTO "country" ("id", "name") VALUES ('UG', '𐐏𐐭𐑀𐐰𐑌𐐼𐐲');
INSERT INTO "country" ("id", "name") VALUES ('UM', '𐐏𐐭𐑌𐐰𐐮𐐻𐐲𐐼 𐐝𐐻𐐩𐐻𐑅 𐐣𐐴𐑌𐐬𐑉 𐐍𐐻𐑊𐐴𐐨𐑍 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('US', '𐐏𐐭𐑌𐐴𐐻𐐲𐐼 𐐝𐐻𐐩𐐻𐑅');
INSERT INTO "country" ("id", "name") VALUES ('UY', '𐐏𐐳𐑉𐐲𐑀𐐶𐐴');
INSERT INTO "country" ("id", "name") VALUES ('UZ', '𐐅𐑆𐐺𐐯𐐿𐐲𐑅𐐻𐐰𐑌');
INSERT INTO "country" ("id", "name") VALUES ('VA', '𐐚𐐰𐐼𐐲𐐿𐐲𐑌');
INSERT INTO "country" ("id", "name") VALUES ('VC', '𐐝𐐩𐑌𐐻 𐐚𐐮𐑌𐑅𐐲𐑌𐐻 𐐰𐑌𐐼 𐑄 𐐘𐑉𐐯𐑌𐐲𐐼𐐨𐑌𐑆');
INSERT INTO "country" ("id", "name") VALUES ('VD', '𐐤𐐱𐑉𐑃 𐐚𐐨𐐯𐐻𐑌𐐪𐑋');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezuela');
INSERT INTO "country" ("id", "name") VALUES ('VG', '𐐒𐑉𐐮𐐼𐐮𐑇 𐐚𐐲𐑉𐐾𐐲𐑌 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('VI', '𐐏.𐐝. 𐐚𐐲𐑉𐐾𐐲𐑌 𐐌𐑊𐐲𐑌𐐼𐑆');
INSERT INTO "country" ("id", "name") VALUES ('VN', '𐐚𐐨𐐯𐐻𐑌𐐪𐑋');
INSERT INTO "country" ("id", "name") VALUES ('VU', '𐐚𐐪𐑌𐐳𐐪𐐼𐐭');
INSERT INTO "country" ("id", "name") VALUES ('WF', '𐐎𐐪𐑊𐐮𐑅 𐐰𐑌𐐼 𐐙𐐭𐐻𐐭𐑌𐐲');
INSERT INTO "country" ("id", "name") VALUES ('WK', '𐐎𐐩𐐿 𐐌𐑊𐐲𐑌𐐼');
INSERT INTO "country" ("id", "name") VALUES ('WS', '𐐝𐐲𐑋𐐬𐐲');
INSERT INTO "country" ("id", "name") VALUES ('YD', '𐐑𐐨𐐹𐐲𐑊𐑆 𐐔𐐯𐑋𐐲𐐿𐑉𐐰𐐼𐐮𐐿 𐐡𐐨𐐹𐐲𐐺𐑊𐐮𐐿 𐐲𐑂 𐐏𐐯𐑋𐐲𐑌');
INSERT INTO "country" ("id", "name") VALUES ('YE', '𐐏𐐯𐑋𐐲𐑌');
INSERT INTO "country" ("id", "name") VALUES ('YT', '𐐣𐐪𐐷𐐱𐐻');
INSERT INTO "country" ("id", "name") VALUES ('ZA', '𐐝𐐵𐑃 𐐈𐑁𐑉𐐲𐐿𐐲');
INSERT INTO "country" ("id", "name") VALUES ('ZM', '𐐞𐐰𐑋𐐺𐐨𐐲');
INSERT INTO "country" ("id", "name") VALUES ('ZW', '𐐞𐐮𐑋𐐺𐐪𐐺𐐶𐐩');
INSERT INTO "country" ("id", "name") VALUES ('ZZ', '𐐊𐑌𐐬𐑌 𐐬𐑉 𐐆𐑌𐑂𐐰𐑊𐐮𐐼 𐐡𐐨𐐾𐐲𐑌');
