<?php return array (
  'NZ' => 'Aotearoa',
  'GB' => 'Aupuni Mōʻī Hui Pū ʻIa',
  'GR' => 'Helene',
  'NL' => 'Hōlani',
  'JP' => 'Iāpana',
  'CA' => 'Kanakā',
  'DE' => 'Kelemānia',
  'DK' => 'Kenemaka',
  'ES' => 'Kepania',
  'CN' => 'Kina',
  'RU' => 'Lūkia',
  'MX' => 'Mekiko',
  'AU' => 'Nūhōlani',
  'FR' => 'Palani',
  'US' => 'ʻAmelika Hui Pū ʻIa',
  'IE' => 'ʻIlelani',
  'IL' => 'ʻIseraʻela',
  'PH' => 'ʻĀina Pilipino',
  'IT' => 'ʻĪkālia',
  'IN' => 'ʻĪnia',
);
