CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY("id"));

INSERT INTO "country" ("id", "name") VALUES ('AD', 'ⴰⵏⴷⵓⵔⴰ');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'ⵍⵉⵎⴰⵔⴰⵜ');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'ⴰⴼⵖⴰⵏⵉⵙⵜⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'ⴰⵏⵜⵉⴳⴰ ⴷ ⴱⵔⴱⵓⴷⴰ');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'ⴰⵏⴳⵉⵍⴰ');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'ⴰⵍⴱⴰⵏⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'ⴰⵔⵎⵉⵏⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'ⴰⵏⵜⵉⵢ ⵏ ⵀⵓⵍⴰⵏⴷⴰ');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'ⴰⵏⴳⵓⵍⴰ');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'ⴰⵔⵊⴰⵏⵜⵉⵏ');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'ⵙⴰⵎⵡⴰ ⵜⴰⵎⵉⵔⵉⴽⴰⵏⵉⵜ');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'ⵏⵏⵎⵙⴰ');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'ⵓⵙⵜⵔⴰⵍⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'ⴰⵔⵓⴱⴰ');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'ⴰⴷⵔⴰⴱⵉⵊⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'ⴱⵓⵙⵏⴰ ⴷ ⵀⵉⵔⵙⵉⴽ');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'ⴱⴰⵔⴱⴰⴷ');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'ⴱⴰⵏⴳⵍⴰⴷⵉⵛ');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'ⴱⵍⵊⵉⴽⴰ');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'ⴱⵓⵔⴽⵉⵏⴰ ⴼⴰⵙⵓ');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'ⴱⵍⵖⴰⵔⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'ⴱⵃⵔⴰⵢⵏ');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'ⴱⵓⵔⵓⵏⴷⵉ');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'ⴱⵉⵏⵉⵏ');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'ⴱⵔⵎⵓⴷⴰ');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'ⴱⵔⵓⵏⵉ');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'ⴱⵓⵍⵉⴼⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'ⴱⵔⴰⵣⵉⵍ');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'ⴱⴰⵀⴰⵎⴰⵙ');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'ⴱⵀⵓⵜⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'ⴱⵓⵜⵙⵡⴰⵏⴰ');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'ⴱⵉⵍⴰⵔⵓⵙⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'ⴱⵉⵍⵉⵣ');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'ⴽⴰⵏⴰⴷⴰ');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⵜⴰⴷⵉⵎⵓⵇⵔⴰⵜⵉⵜ ⵏ ⴽⵓⵏⴳⵓ');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⵜⴰⵏⴰⵎⵎⴰⵙⵜ ⵏ ⵉⴼⵔⵉⵇⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'ⴽⵓⵏⴳⵓ');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'ⵙⵡⵉⵙⵔⴰ');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'ⴽⵓⵜ ⴷⵉⴼⵡⴰⵔ');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⴽⵓⴽ');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'ⵛⵛⵉⵍⵉ');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'ⴽⴰⵎⵉⵔⵓⵏ');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'ⵛⵛⵉⵏⵡⴰ');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'ⴽⵓⵍⵓⵎⴱⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'ⴽⵓⵙⵜⴰ ⵔⵉⴽⴰ');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'ⵙⵉⵔⴱⵢⴰ ⴷ ⵎⵓⵏⵜⵉⵏⵉⴳⵔⵓ');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'ⴽⵓⴱⴰ');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⴽⴰⴱⴱⵉⵔⴷⵉ');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'ⵇⵓⴱⵔⵓⵙ');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⵜⴰⵜⵛⵉⴽⵉⵜ');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'ⴰⵍⵎⴰⵏⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'ⴷⵊⵉⴱⵓⵜⵉ');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'ⴷⴰⵏⵎⴰⵔⴽ');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'ⴷⵓⵎⵉⵏⵉⴽ');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'ⵜⴰⴳⴷⵓⴷⴰⵏⵜ ⵜⴰⴷⵓⵎⵉⵏⵉⴽⵜ');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'ⴷⵣⴰⵢⵔ');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'ⵉⴽⵡⴰⴷⵓⵔ');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'ⵉⵙⵜⵓⵏⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'ⵎⵉⵚⵕ');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'ⵉⵔⵉⵜⵉⵔⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'ⵙⴱⴰⵏⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'ⵉⵜⵢⵓⴱⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'ⴼⵉⵍⵍⴰⵏⴷⴰ');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'ⴼⵉⴷⵊⵉ');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵎⴰⵍⴰⵡⵉ');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'ⵎⵉⴽⵔⵓⵏⵉⵣⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'ⴼⵔⴰⵏⵙⴰ');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'ⴳⴰⴱⵓⵏ');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'ⵜⴰⴳⵍⴷⵉⵜ ⵉⵎⵓⵏⵏ');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'ⵖⵔⵏⴰⵟⴰ');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'ⵊⵓⵔⵊⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'ⴳⵡⵉⵢⴰⵏ ⵜⴰⴼⵔⴰⵏⵙⵉⵙⵜ');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'ⵖⴰⵏⴰ');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'ⴰⴷⵔⴰⵔ ⵏ ⵟⴰⵕⵉⵇ');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'ⴳⵔⵉⵍⴰⵏⴷ');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'ⴳⴰⵎⴱⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'ⵖⵉⵏⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'ⴳⵡⴰⴷⴰⵍⵓⴱ');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'ⵖⵉⵏⵢⴰ ⵏ ⵉⴽⵡⴰⴷⵓⵔ');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'ⵍⵢⵓⵏⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'ⴳⵡⴰⵜⵉⵎⴰⵍⴰ');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'ⴳⵡⴰⵎ');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'ⵖⵉⵏⵢⴰ ⴱⵉⵙⴰⵡ');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'ⴳⵡⵉⵢⴰⵏⴰ');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'ⵀⵓⵏⴷⵓⵔⴰⵙ');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'ⴽⵔⵡⴰⵜⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'ⵀⴰⵢⵜⵉ');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'ⵀⵏⵖⴰⵔⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'ⴰⵏⴷⵓⵏⵉⵙⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'ⵉⵔⵍⴰⵏⴷⴰ');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'ⵉⵙⵔⴰⵢⵉⵍ');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'ⵍⵀⵉⵏⴷ');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'ⵜⴰⵎⵏⴰⴹⵜ ⵜⴰⵏⴳⵍⵉⵣⵉⵜ ⵏ ⵓⴳⴰⵔⵓ ⴰⵀⵉⵏⴷⵉ');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'ⵍⵄⵉⵔⴰⵇ');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'ⵉⵔⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'ⵉⵙⵍⴰⵏⴷ');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'ⵉⵟⴰⵍⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'ⵊⴰⵎⴰⵢⴽⴰ');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'ⵍⵓⵔⴷⵓⵏ');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'ⵍⵢⴰⴱⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'ⴽⵉⵏⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'ⴽⵉⵔⵖⵉⵣⵉⵙⵜⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'ⴽⴰⵎⴱⵓⴷⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'ⴽⵉⵔⵉⴱⴰⵜⵉ');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'ⵇⵓⵎⵓⵔ');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'ⵙⴰⵏⴽⵔⵉⵙ ⴷ ⵏⵉⴼⵉⵙ');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'ⴽⵓⵔⵢⴰ ⵏ ⵉⵥⵥⵍⵎⴹ');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'ⴽⵓⵔⵢⴰ ⵏ ⵉⴼⴼⵓⵙ');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'ⵍⴽⵡⵉⵜ');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⴽⴰⵢⵎⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'ⴽⴰⵣⴰⵅⵙⵜⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'ⵍⴰⵡⵙ');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'ⵍⵓⴱⵏⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'ⵙⴰⵏⵜⵍⵓⵙⵉ');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'ⵍⵉⴽⵉⵏⵛⵜⴰⵢⵏ');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'ⵙⵔⵉⵍⴰⵏⴽⴰ');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'ⵍⵉⴱⵉⵔⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'ⵍⵉⵚⵓⵟⵓ');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'ⵍⵉⵜⵡⴰⵏⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'ⵍⵓⴽⵙⴰⵏⴱⵓⵔⴳ');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'ⵍⴰⵜⴼⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'ⵍⵉⴱⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'ⵍⵎⵖⵔⵉⴱ');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'ⵎⵓⵏⴰⴽⵓ');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'ⵎⵓⵍⴷⵓⴼⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'ⵎⴰⴷⴰⵖⴰⵛⵇⴰⵔ');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵎⴰⵔⵛⴰⵍ');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'ⵎⴰⵙⵉⴷⵓⵏⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'ⵎⴰⵍⵉ');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'ⵎⵢⴰⵏⵎⴰⵔ');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'ⵎⵏⵖⵓⵍⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵎⴰⵔⵢⴰⵏ ⵏ ⵉⵥⵥⵍⵎⴹ');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'ⵎⴰⵔⵜⵉⵏⵉⴽ');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'ⵎⵓⵕⵉⵟⴰⵏⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'ⵎⵓⵏⵙⵉⵔⴰⵜ');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'ⵎⴰⵍⵟⴰ');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'ⵎⵓⵔⵉⵙ');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'ⵎⴰⵍⴷⵉⴼ');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'ⵎⴰⵍⴰⵡⵉ');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'ⵎⵉⴽⵙⵉⴽ');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'ⵎⴰⵍⵉⵣⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'ⵎⵓⵣⵏⴱⵉⵇ');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'ⵏⴰⵎⵉⴱⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'ⴽⴰⵍⵉⴷⵓⵏⵢⴰ ⵜⴰⵎⴰⵢⵏⵓⵜ');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'ⵏⵏⵉⵊⵉⵔ');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵏⵓⵔⴼⵓⵍⴽ');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'ⵏⵉⵊⵉⵔⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'ⵏⵉⴽⴰⵔⴰⴳⵡⴰ');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'ⵀⵓⵍⴰⵏⴷⴰ');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'ⵏⵏⵔⵡⵉⵊ');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'ⵏⵉⴱⴰⵍ');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'ⵏⴰⵡⵔⵓ');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'ⵏⵉⵡⵉ');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'ⵏⵢⵓⵣⵉⵍⴰⵏⴷⴰ');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'ⵄⵓⵎⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'ⴱⴰⵏⴰⵎⴰ');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'ⴱⵉⵔⵓ');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'ⴱⵓⵍⵉⵏⵉⵣⵢⴰ ⵜⴰⴼⵔⴰⵏⵙⵉⵙⵜ');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'ⴱⴰⴱⵡⴰ ⵖⵉⵏⵢⴰ ⵜⴰⵎⴰⵢⵏⵓⵜ');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'ⴼⵉⵍⵉⴱⴱⵉⵏ');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'ⴱⴰⴽⵉⵙⵜⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'ⴱⵓⵍⵓⵏⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'ⵙⴰⵏⴱⵢⵉⵔ ⴷ ⵎⵉⴽⵍⵓⵏ');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'ⴱⵉⵜⴽⴰⵢⵔⵏ');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'ⴱⵓⵔⵜⵓ ⵔⵉⴽⵓ');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'ⴰⴳⵎⵎⴰⴹ ⵏ ⵜⴰⴳⵓⵜ ⴷ ⵖⵣⵣⴰ');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'ⴱⵕⵟⵇⵉⵣ');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'ⴱⴰⵍⴰⵡ');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'ⴱⴰⵔⴰⴳⵡⴰⵢ');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'ⵇⴰⵜⴰⵔ');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'ⵔⵉⵢⵓⵏⵢⵓⵏ');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'ⵔⵓⵎⴰⵏⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'ⵔⵓⵙⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'ⵔⵡⴰⵏⴷⴰ');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'ⵙⵙⴰⵄⵓⴷⵉⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵙⴰⵍⵓⵎⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'ⵙⵙⵉⵛⵉⵍ');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'ⵙⵙⵓⴷⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'ⵙⵙⵡⵉⴷ');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'ⵙⵏⵖⴰⴼⵓⵔⴰ');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'ⵙⴰⵏⵜⵉⵍⵉⵏ');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'ⵙⵍⵓⴼⵉⵏⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'ⵙⵍⵓⴼⴰⴽⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'ⵙⵙⵉⵔⴰⵍⵢⵓⵏ');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'ⵙⴰⵏⵎⴰⵔⵉⵏⵓ');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'ⵙⵙⵉⵏⵉⴳⴰⵍ');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'ⵚⵚⵓⵎⴰⵍ');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'ⵙⵓⵔⵉⵏⴰⵎ');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'ⵙⴰⵡⵟⵓⵎⵉ ⴷ ⴱⵔⴰⵏⵙⵉⴱ');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'ⵙⴰⵍⴼⴰⴷⵓⵔ');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'ⵙⵓⵔⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'ⵙⵡⴰⵣⵉⵍⴰⵏⴷⴰ');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'ⵜⵉⴳⵣⵉⵔⵉⵏ ⵏ ⵜⵓⵔⴽⵢⴰ ⴷ ⴽⴰⵢⴽ');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'ⵜⵛⴰⴷ');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'ⵟⵓⴳⵓ');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'ⵟⴰⵢⵍⴰⵏⴷ');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'ⵜⴰⴷⵊⴰⴽⵉⵙⵜⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'ⵟⵓⴽⵍⴰⵡ');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'ⵜⵉⵎⵓⵔ ⵏ ⵍⵇⴱⵍⵜ');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'ⵜⵓⵔⴽⵎⴰⵏⵙⵜⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'ⵜⵓⵏⵙ');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'ⵟⵓⵏⴳⴰ');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'ⵜⵓⵔⴽⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'ⵜⵔⵉⵏⵉⴷⴰⴷ ⴷ ⵟⵓⴱⴰⴳⵓ');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'ⵜⵓⴼⴰⵍⵓ');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'ⵟⴰⵢⵡⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'ⵟⴰⵏⵥⴰⵏⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'ⵓⴽⵔⴰⵏⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'ⵓⵖⴰⵏⴷⴰ');
INSERT INTO "country" ("id", "name") VALUES ('US', 'ⵉⵡⵓⵏⴰⴽ ⵎⵓⵏⵏⵉⵏ ⵏ ⵎⵉⵔⵉⴽⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'ⵓⵔⵓⴳⵡⴰⵢ');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'ⵓⵣⴱⴰⴽⵉⵙⵜⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'ⴰⵡⴰⵏⴽ ⵏ ⴼⴰⵜⵉⴽⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'ⵙⴰⵏⴼⴰⵏⵙⴰⵏ ⴷ ⴳⵔⵉⵏⴰⴷⵉⵏ');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'ⴼⵉⵏⵣⵡⵉⵍⴰ');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'ⵜⵉⴳⵣⵉⵔⵉⵏ ⵜⵉⵎⴳⴰⴷ ⵏ ⵏⵏⴳⵍⵉⵣ');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'ⵜⵉⴳⵣⵉⵔⵉⵏ ⵜⵉⵎⴳⴰⴷ ⵏ ⵉⵡⵓⵏⴰⴽ ⵎⵓⵏⵏⵉⵏ');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'ⴼⵉⵜⵏⴰⵎ');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'ⴼⴰⵏⵡⴰⵟⵓ');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'ⵡⴰⵍⵉⵙ ⴷ ⴼⵓⵜⵓⵏⴰ');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'ⵙⴰⵎⵡⴰ');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'ⵢⴰⵎⴰⵏ');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'ⵎⴰⵢⵓⵟ');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'ⴰⴼⵔⵉⵇⵢⴰ ⵏ ⵉⴼⴼⵓⵙ');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'ⵣⴰⵎⴱⵢⴰ');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'ⵣⵉⵎⴱⴰⴱⵡⵉ');
