CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afuganistani');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Ajentina');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albania');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Aljeria');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Amerika');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andora');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anguila');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua ne Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armenia');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Arubha');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Australia');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Austria');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azabajani');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahama');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahareni');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladeshi');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbados');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Belarusi');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belize');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Beljium');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benini');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermuda');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Bhutani');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolivia');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botswana');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Boznia ne Herzegovina');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brazil');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Bukinafaso');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulgaria');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Burunei');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Central African Republic');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Chadi');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Chile');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'China');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Chitsuwa cheNorfolk');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Cuba');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Cyprus');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Czech Republic');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Democratic Republic of the Congo');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Denmark');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Djibouti');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominica');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Dominican Republic');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'East Timor');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ecuador');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Egypt');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'El Salvador');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritrea');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Estonia');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Etiopia');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fiji');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finland');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'France');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'French Guiana');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'French Polynesia');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabon');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambia');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Georgia');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Germany');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Ghana');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Gibraltar');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Greece');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Greenland');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenada');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadeloupe');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatemala');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Guinea');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Guinea-Bissau');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guyana');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haiti');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduras');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Hungary');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Iceland');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'India');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indonesia');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Iran');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Iraq');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Ireland');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Italy');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Ivory Coast');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Izuraeri');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamaica');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japan');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jordan');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kambodia');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kameruni');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazakhstan');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenya');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolombia');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komoro');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Korasia');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Korea, North');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Korea, South');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kostarika');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kuwait');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kyrgyzstan');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laos');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Latvia');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Lebanon');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesotho');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberia');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libya');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Liechtenstein');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Lithuania');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luxembourg');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Macedonia');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagascar');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malawi');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malaysia');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldives');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martinique');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mauritania');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Mauritius');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayotte');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mexico');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Micronesia');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldova');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monaco');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongolia');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Montserrat');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Morocco');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mozambique');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Myanmar');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibia');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepal');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Netherlands');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Netherlands Antilles');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'New Caledonia');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'New Zealand');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nicaragua');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Niger');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nigeria');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Norway');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Oman');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakistan');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papua New Guinea');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguay');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Peru');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Philippines');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitcairn');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Poland');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portugal');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Puerto Rico');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Qatar');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Réunion');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Romania');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Russia');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Rwanda');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Saint Helena');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Saint Lucia');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Saint Pierre and Miquelon');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samoa');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Samoa ye Amerika');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'San Marino');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'São Tomé and Príncipe');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Saudi Arabia');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegal');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Serbia and Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Seychelles');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Sierra Leone');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapore');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slovakia');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Slovenia');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somalia');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'South Africa');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Spain');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudan');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Suriname');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Swaziland');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Sweden');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Switzerland');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Syria');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taiwan');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tajikistan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzania');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Thailand');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunisia');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Turkey');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turkmenistan');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uganda');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukraine');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'United Arab Emirates');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'United Kingdom');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruguay');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Uzbekistan');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatican State');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezuela');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vietnam');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis and Futuna');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Yemen');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambia');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabwe');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Zvitsuwa zvaSolomon');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Zvitsuwa zveAmerika');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Zvitsuwa zveCape Verde');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Zvitsuwa zveCayman');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Zvitsuwa zveCook');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Zvitsuwa zveFalklands');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Zvitsuwa zveHingirandi');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Zvitsuwa zvekumaodzanyemba eMariana');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Zvitsuwa zveMarshall');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Zvitsuwa zveTurk neCaico');
