CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AD', 'Orílẹ́ède Ààndórà');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Orílẹ́ède Ààngólà');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Orílẹ́ède Ààngúlílà');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Orílẹ́ède Ààntígúà àti Báríbúdà');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Orílẹ́ède Àfùgànístánì');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Orílẹ́ède Agentínà');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Orílẹ́ède Ailandi');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Orílẹ́ède Àlùbàníánì');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Orílẹ́ède Àlùgèríánì');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Orílẹ́ède Améníà');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Orílẹ́ède Àrin gùngun Áfíríkà');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Orílẹ́ède Ariwa Afirika');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Orílẹ́ède Ariwa Kọria');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Orílẹ́ède Árúbà');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Orílẹ́ède Asẹ́bájánì');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Orílẹ́ède Asítíríà');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Orílẹ́ède Ástràlìá');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Orílẹ́ède Aṣilandi');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Orílẹ́ède Bábádósì');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Orílẹ́ède Bàhámásì');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Orílẹ́ède Bángáládésì');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Orílẹ́ède Báránì');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Orílẹ́ède Bàràsílì');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Orílẹ́ède Bégíọ́mù');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Orílẹ́ède Bélárúsì');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Orílẹ́ède Bèlísẹ̀');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Orílẹ́ède Bémúdà');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Orílẹ́ède Bẹ̀nẹ̀');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Orílẹ́ède Bọ̀lífíyà');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Orílẹ́ède Bọ̀síníà àti Ẹtisẹgófínà');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Orílẹ́ède Bọ̀tìsúwánà');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Orílẹ́ède Búrúnẹ́lì');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Orílẹ́ède Bútánì');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Orílẹ́ède Bùùgáríà');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Orílẹ́ède Bùùkíná Fasò');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Orílẹ́ède Bùùrúndì');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Orílẹ́ède Dẹ́mákì');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Orílẹ́ède Díbọ́ótì');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Orílẹ́ède Dòmíníkà');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Orilẹ́ède Dòmíníkánì');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Orílẹ́ède Égípítì');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Orílẹ́ède Ekuádò');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Orílẹ́ède Ekutoria Gini');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Orílẹ́ède Eritira');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Orílẹ́ède Esitonia');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Orílẹ́ède Etikun Fagini ti Amẹrika');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Orílẹ́ède Etíkun Fágínì ti ìlú Bírítísì');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Orílẹ́ède Etikun Fakalandi');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Orílẹ́ède Etikun Guusu Mariana');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Orílẹ́ède Etíkun Índíánì ti Ìlú Bírítísì');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Orílẹ́ède Etikun Máṣali');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Orílẹ́ède Etikun Nọ́úfókì');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Orílẹ́ède Etikun Solomoni');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Orílẹ́ède Etíokun Kámánì');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Orílẹ́ède Etíokun Kápé féndè');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Orílẹ́ède Etíokun Kùúkù');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Orílẹ́ède Etopia');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Orílẹ́ède Ẹẹsáfádò');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Orílẹ́ède Ẹmirate ti Awọn Arabu');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Orílẹ́ède Faniatu');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Orílẹ́ède Faranse');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Orílẹ́ède Fatikani');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Orílẹ́ède Fẹnẹṣuẹla');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Orílẹ́ède Fẹtinami');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Orílẹ́ède Fiji');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Orílẹ́ède Filandi');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Orílẹ́ède filipini');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Orílẹ́ède Firenṣi Guana');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Orílẹ́ède Firenṣi Polinesia');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Orílẹ́ède Fisẹnnti ati Genadina');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Orílẹ́ède Gabon');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Orílẹ́ède Gadelope');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Orílẹ́ède Gambia');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Orílẹ́ède Gana');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Orílẹ́ède Gemani');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Orílẹ́ède Genada');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Orílẹ́ède Gene');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Orílẹ́ède Gene-Busau');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Orílẹ́ède Gerelandi');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Orílẹ́ède Geriisi');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Orílẹ́ède Gibaratara');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Orílẹ́ède Gọgia');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Orílẹ́ède Guamu');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Orílẹ́ède Guatemala');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Orílẹ́ède Guusu Kọria');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Orílẹ́ède Guyana');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Orílẹ́ède Haati');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Orílẹ́ède Hẹlena');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Orílẹ́ède Hondurasi');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Orílẹ́ède Hungari');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Orílẹ́ède ÌlàOòrùn Tímọ̀');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Orílẹ́ède India');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Orílẹ́ède Indonesia');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Orílẹ́ède Iraki');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Orílẹ́ède Irani');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Orílẹ́ède Iserẹli');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Orílẹ́ède Italiyi');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Orílẹ́ède Iwọorun Pakisitian ati Gaṣa');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Orílẹ́ède Jamaika');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Orílẹ́ède Japani');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Orílẹ́ède Jọdani');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Orílẹ́ède Kaledonia Titun');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Orílẹ́ède Kamerúúnì');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Orílẹ́ède Kàmùbódíà');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Orílẹ́ède Kánádà');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Orílẹ́ède Kaṣaṣatani');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Orílẹ́ède Kenya');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Orílẹ́ède Kiiti ati Neefi');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Orílẹ́ède Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Orílẹ́ède Kòlómíbìa');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Orílẹ́ède Kòmòrósì');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Orilẹ́ède Kóngò');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Orílẹ́ède Kóngò');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Orílẹ́ède Kòróátíà');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Orílẹ́ède Kota');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Orílẹ́ède Kóútè forà');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Orílẹ́ède Kúbà');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Orílẹ́ède Kuriṣisitani');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Orílẹ́ède Kúrúsì');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Orílẹ́ède Kuusita Ríkà');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Orílẹ́ède Kuweti');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Orílẹ́ède Laberia');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Orílẹ́ède Laosi');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Orílẹ́ède Latifia');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Orílẹ́ède Lebanoni');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Orílẹ́ède Lesoto');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Orílẹ́ède Lẹṣitẹnisiteni');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Orílẹ́ède Libiya');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Orílẹ́ède Lituania');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Orílẹ́ède Lusemogi');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Orílẹ́ède Luṣia');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Orílẹ́ède Madasika');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Orílẹ́ède Makoronesia');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Orílẹ́ède Maladifi');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Orílẹ́ède Malasia');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Orílẹ́ède Malata');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Orílẹ́ède Malawi');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Orílẹ́ède Mali');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Orílẹ́ède Manamari');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Orílẹ́ède Maritania');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Orílẹ́ède Maritiusi');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Orílẹ́ède Masidonia');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Orílẹ́ède Matinikuwi');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Orílẹ́ède Mayote');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Orílẹ́ède Mesiko');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Orílẹ́ède Modofia');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Orílẹ́ède Mogolia');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Orílẹ́ède Monako');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Orílẹ́ède Moroko');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Orílẹ́ède Moṣamibiku');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Orílẹ́ède Motserati');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Orílẹ́ède Nàìjá');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Orílẹ́ède Nàìjíríà');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Orílẹ́ède Namibia');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Orílẹ́ède Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Orílẹ́ède Nedalandi');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Orílẹ́ède Nedalandi ti Antelisi');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Orílẹ́ède Nepa');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Orílẹ́ède NIkaragua');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Orílẹ́ède Niue');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Orílẹ́ède Nọọwii');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Orílẹ́ède Nruguayi');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Orílẹ́ède Nṣibẹkisitani');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Orílẹ́ède Omobabirin');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Orílẹ́ède Orilẹede Amerika');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Orílẹ́ède Ọọma');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Orílẹ́ède Paalu');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Orílẹ́ède Paapu ti Giini');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Orílẹ́ède Pakisitan');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Orílẹ́ède Panama');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Orílẹ́ède Paraguye');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Orílẹ́ède Peru');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Orílẹ́ède Pẹẹri ati mikuloni');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Orílẹ́ède Pikarini');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Orílẹ́ède Polandi');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Orílẹ́ède Pọto Riko');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Orílẹ́ède Pọtugi');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Orílẹ́ède Riuniyan');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Orílẹ́ède Romaniya');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Orílẹ́ède Rọṣia');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Orílẹ́ède Ruwanda');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Orílẹ́ède Samọ');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'Orílẹ́ède Sani Marino');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Orílẹ́ède Sao tomi ati piriiṣipi');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Orílẹ́ède Saṣiland');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Orílẹ́ède Saudi Arabia');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Orílẹ́ède seṣẹlẹsi');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Orílẹ́ède sẹbia ati Mọtinegoro');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Orílẹ́ède Sẹnẹga');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Orílẹ́ède Silofakia');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Orílẹ́ède Silofania');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Orílẹ́ède Singapo');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Orílẹ́ède Sipani');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Orílẹ́ède Siri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Orílẹ́ède Siria');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Orílẹ́ède Siria looni');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Orílẹ́ède Somalia');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Orílẹ́ède Sudani');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Orílẹ́ède Surinami');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Orílẹ́ède Swidini');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Orílẹ́ède switiṣilandi');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Orílẹ́ède ṣààdì');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Orílẹ́ède ṣáínà');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Orílẹ́ède ṣamibia');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Orílẹ́ède ṣẹ́ẹ́kì');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Orílẹ́ède ṣilandi Titun');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Orílẹ́ède ṣílè');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Orílẹ́ède ṣimibabe');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Orílẹ́ède Tailandi');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Orílẹ́ède Taiwani');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Orílẹ́ède Takisitani');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Orílẹ́ède Tanṣania');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Orílẹ́ède Tirinida ati Tobaga');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Orílẹ́ède Togo');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Orílẹ́ède Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Orílẹ́ède Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Orílẹ́ède Tọọki');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Orílẹ́ède Tọọki ati Etikun Kakọsi');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Orílẹ́ède Tọọkimenisita');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Orílẹ́ède Tufalu');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Orílẹ́ède Tuniṣia');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Orílẹ́ède Uganda');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Orílẹ́ède Ukarini');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Orílẹ́ède Wali ati futuna');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Orílẹ́ède yemeni');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Sámóánì ti Orílẹ́ède Àméríkà');
