CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anikuila');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Anitikua mo Palaputa');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Falanisē');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finilani');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fisi');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Haʻamoa');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Haʻamoa fakaʻamelika');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Holani');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Hongi Kongi SAR Siaina');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honitulasi');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Kalisi');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Kamipia');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Kana');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Kelenatā');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenia');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kilipasi');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Kuami');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Kuenisī');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Kuiana');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kānata');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Kōlea tonga');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Kōloa tokelau');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Laipelia');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesoto');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Luanitā');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Lūsia');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malaui');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malita');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Maulitiusi');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mekesikō');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikolonisia');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Motu Kilisimasi');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Motu Mani');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Motu Nōfoliki');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Motu Puveti');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Moʻungaselati');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Naisilia');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namipia');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Naulu');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Niu Kaletonia');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niuē');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Noauē');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Nuʻusila');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Pahama');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakisitani');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Palāsili');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panamā');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papuaniukini');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Pelesiume');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Pelise');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Pilitānia');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitikeni');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Polinisia fakafalanisē');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Potisiuana');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Potu fonua moana ʻInitia fakapilitānia');
INSERT INTO "country" ("id", "name") VALUES ('ZZ', 'Potu fonua taʻeʻiloa pe hala');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Potu fonua tonga fakafalanisē');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Potukali');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Puleʻanga fakataha ʻAmelika');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Selusī');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Sepeni');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Siaina');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Siamane');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Siapani');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Simipapue');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapula');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Sipalālitā');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Suisilani');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Suēteni');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sīloni');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Tilinitati mo Topako');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Toake');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Tominika');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tūvalu');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikani');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'ʻAealani');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'ʻAfelika tonga');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'ʻAnetātika');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'ʻAositelēlia');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'ʻInitia');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'ʻIsileli');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'ʻIsipite');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'ʻOtumotu Heati mo Makitonali');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'ʻOtumotu Kuki');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'ʻOtumotu Maliana tokelau');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'ʻOtumotu Māsolo');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'ʻOtumotu Seiseli');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'ʻOtumotu Siosia-tonga mo Saniuisi-tonga');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'ʻOtumotu Solomone');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'ʻOtumotu Vilikini fakapilitānia');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'ʻOtumotu Vilikini fakaʻamelika');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'ʻOtumotu siʻi ʻo ʻAmelika');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'ʻUvea mo Futuna');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'ʻĪtali');
