CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY("id"));

INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andoora');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Laaraw Imaarawey Margantey');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afgaanistan');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua nda Barbuuda');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Angiiya');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albaani');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armeeni');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Hollandu Antiiyey Laboo');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angoola');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Argentine');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Ameriki Samoa');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Otriši');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Ostraali');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruuba');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azerbaayijaŋ');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosni nda Herzegovine');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbaados');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladeši');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Belgiiki');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burkina faso');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulgaari');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahareen');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Beniŋ');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermuda');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Bruunee');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Boolivi');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Breezil');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahamas');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Buutaŋ');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botswaana');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Biloriši');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Beliizi');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanaada');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Kongoo demookaratiki laboo');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Centraafriki koyra');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongoo');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Swisu');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Kudwar');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Kuuk gungey');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Šiili');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kameruun');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Šiin');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolombi');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kosta rika');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Serbi nda Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kuuba');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Kapuver gungey');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Šiipur');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Cek labo');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Almaaɲe');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Jibuuti');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Danemark');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Doominiki');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Doominiki laboo');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Alžeeri');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekwateer');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Estooni');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Misra');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritree');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Espaaɲe');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Ecioopi');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finlandu');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fiji');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Kalkan gungey');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikronezi');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Faransi');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gaabon');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Albaasalaama Marganta');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenaada');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Gorgi');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Faransi Guyaan');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Gaana');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Gibraltar');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Grinland');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambi');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Gine');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Gwadeluup');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Ginee Ekwatorial');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Greece');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Gwatemaala');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Gine-Bisso');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guyaane');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduras');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Krwaasi');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haiti');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Hungaari');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indoneezi');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Irlandu');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Israyel');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Indu laboo');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Britiši Indu teekoo laama');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Iraak');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Iraan');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Ayceland');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Itaali');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamaayik');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Urdun');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Jaapoŋ');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Keeniya');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kyrgyzstan');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kamboogi');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribaati');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komoor');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Seŋ Kitts nda Nevis');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Kooree, Gurma');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Kooree, Hawsa');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kuweet');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Kayman gungey');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kaazakstan');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laawos');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Lubnaan');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Seŋ Lussia');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Liechtenstein');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Srilanka');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberia');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Leesoto');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Lituaani');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luxembourg');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Letooni');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Liibi');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Maarok');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monako');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldovi');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagascar');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Maršal gungey');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Maacedooni');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Maali');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Maynamar');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongooli');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Mariana Gurma Gungey');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martiniiki');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mooritaani');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Montserrat');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Mooris gungey');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldiivu');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malaawi');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mexiki');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Maleezi');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mozambik');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Naamibi');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Kaaledooni Taagaa');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Nižer');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Norfolk Gungoo');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Naajiriia');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikaragwa');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Hollandu');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Norveej');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Neepal');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Zeelandu Taaga');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Omaan');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Peeru');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Faransi Polineezi');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papua Ginee Taaga');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filipine');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Paakistan');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Poloɲe');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Seŋ Piyer nda Mikelon');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitikarin');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Porto Riko');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palestine Dangay nda Gaaza');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portugaal');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palu');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguwey');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Kataar');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Reenioŋ');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Rumaani');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Iriši laboo');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Rwanda');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Saudiya');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Solomon Gungey');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Seešel');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Suudaŋ');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Sweede');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapur');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Seŋ Helena');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Sloveeni');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slovaaki');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Seera Leon');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'San Marino');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegal');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somaali');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Surinaam');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sao Tome nda Prinsipe');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Salvador laboo');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Suuria');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Swaziland');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Turk nda Kayikos Gungey');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Caadu');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Taayiland');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Taažikistan');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Timoor hawsa');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turkmenistaŋ');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunizi');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Turki');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad nda Tobaago');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taayiwan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzaani');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukreen');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uganda');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Ameriki Laabu Margantey');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruguwey');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Uzbeekistan');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vaatikan Laama');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Seŋvinsaŋ nda Grenadine');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Veneezuyeela');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Britiši Virgin gungey');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Ameerik Virgin Gungey');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vietnaam');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanautu');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis nda Futuna');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samoa');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Yaman');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayooti');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Hawsa Afriki Laboo');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambi');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabwe');
