CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Afilika Kusini');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afuganisitani');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Ajentina');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Alijeliya');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Alimeniya');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aluba');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Alubaniya');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andola');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguilla');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Anitiguya ni Balubuda');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Anitili sa Uholansi');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Asabajani');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Awusitilaliya');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Awusitiliya');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Ayalandi');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Ayisilendi');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Babadosi');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahaleni');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahama');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangiladeshi');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Belalusi');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Belimuda');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belise');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benini');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Boliviya');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosiniya ni Hesegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botiswana');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Bukinafaso');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Bukini');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Bulasili');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Buligaliya');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Bulundi');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Buluneyi');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Butani');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Denimaki');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominika');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ekwado');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Elisavado');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Elitileya');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Esitoniya');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Figunguli fya Fokolendi');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Figunguli fya Kooki');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Figunguli fya Maliyana ifya luvala lwa Kunyamande');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Figunguli fya Solomoni');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Figunguli fya Tuliki ni Kaiko');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Figunguli fya Viliginiya ifya Malekani');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Figunguli ifya Kayimayi');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Figunguli ifya Malishali');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Figunguli ifya Viliginiya ifya Uwingelesa');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fiji');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipino');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gaboni');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambiya');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Gilenada');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Gilinilandi');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Gine');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Ginebisawu');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Ginekweta');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyana');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Gwadelupe');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Gwamu');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Gwatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Gwiyana ya Wufalansa');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Hayiti');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Hisipaniya');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Hondulasi');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Hungaliya');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Ilaki');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Indiya');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonesiya');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Isilaeli');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Italiya');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jamaika');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Jamuhuli ya Afilika ya Pakhati');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Jamuhuli ya Dominika');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Jamuhuli ya Kidemokilasiya ya Kongo');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Jamuhuli ya Sheki');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Japani');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Jibulalita');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Jibuti');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Jojiya');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kambodiya');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kameruni');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanada');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kasakisitani');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Katali');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenya');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Kepuvede');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Khana');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kilibati');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kiligisisitani');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Kodivaya');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Kolasiya');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Koleya ya Kusini');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Koleya ya luvala lwa Kunyamande');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolombiya');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Komolo');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongo');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kositalika');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kuba');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Kupilosi');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuwaiti');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Lasembagi');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Lativiya');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Layosi');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Lebanoni');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesoto');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Libeliya');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libiya');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Lisheniteni');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Litwaniya');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Liyunioni');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Lomaniya');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Lwanda');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawi');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Malekani');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malesiya');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malita');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Malitiniki');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Masedoniya');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayote');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mekisiko');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikilonesiya');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Misili');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Modivu');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Molidova');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Molisi');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Molitaniya');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Moloko');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monako');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongoliya');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Monitiselati');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Munjema gwa Kusikha nu Luvala lwa Gasa lwa Palesit');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Musumbiji');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Muyama');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibiya');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nawulu');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepali');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Nijeli');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nijeliya');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikalagwa');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niwue');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Nolwe');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Nyukaledoniya');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Nyusilendi');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Omani');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakisitani');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Palagwayi');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palawu');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papuwa');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Pelu');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitikailini');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Polandi');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Polinesiya ya Wufalansa');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Pwetoliko');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'Samalino');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Sambiya');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoya');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samoya ya Malekani');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Santahelena');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Santakitisi ni Nevisi');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Santalusiya');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Santapieli ni Mikeloni');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Santavisenti na Gilenadini');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Sawudi');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Sayo Tome ni Pilinikipe');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Selibiya ni Montenegilo');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegali');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Shadi');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Shelisheli');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Shigunguli sha Nolifoki');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Shile');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Shina');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Siela Liyoni');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sililanka');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Siliya');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Silovakiya');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Siloveniya');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Simbabwe');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapoo');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somaliya');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudani');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Sulinamu');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Tailandi');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwani');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tajikisitani');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tansaniya');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Tilinidadi ni Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timoli ya kunena');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelawu');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Tulukimenisitani');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunisiya');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Ubeligiji');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Uhabeshi');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Ulugwayi');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Uluvala lwa Uwingelesa ku Bahali ya Hindi');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Usibekisitani');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Uswasi');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Uswidi');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Uswisi');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Utuluki');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Uwajemi');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Uwingelesa');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatikani');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venesuela');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietinamu');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Walisi ni Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Wufalansa');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Wufini');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Wugiliki');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Wuholansi');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Wujelumani');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Wuleno');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Wulusi');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Wutwa wa shiyalabu');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yemeni');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Yolodani');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Yukileini');
