CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('BY', 'A’ Bhealaruis');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'A’ Bheilg');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'A’ Bheilìs');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'A’ Bheiniseala');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'A’ Bhulgair');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'A’ Chairtbheil');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'A’ Chongo - Brazzaville');
INSERT INTO [country] ([id], [name]) VALUES ('XK', 'A’ Chosobho');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'A’ Chròthais');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'A’ Ghaimbia');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'A’ Ghearmailt');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'A’ Ghraonlann');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'A’ Ghreug');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'A’ Mhasadon');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'A’ Mholdobha');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'A’ Phoblachd Dhoiminiceach');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'A’ Phòlainn');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'A’ Phortagail');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afghanastàn');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Afraga a Deas');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Aildiria');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Aintìoga is Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Airmeinia');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albàinia');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Am Monadh Neagrach');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'An Antartaig');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'An Argantain');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'An Ceap Uaine');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'An Danmhairg');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'An Eadailt');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'An Eaman');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'An Eastoin');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'An Eilbheis');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'An Èiphit');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'An Fhionnlann');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'An Fhraing');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'An Itiop');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'An Laitbhe');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'An Liotuain');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'An Namaib');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'An Nirribhidh');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'An Ostair');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'An Rìoghachd Aonaichte');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'An Ruis');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'An Salbhador');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'An Spàinn');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'An t-Seàd');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'An t-Seapan');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'An t-Sèirb');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'An t-Sile');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'An t-Sìn');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'An t-Sìombab');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'An t-Slòbhac');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'An t-Slòbhain');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'An t-Suain');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'An Tansan');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'An Tuirc');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'An Ucràin');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'An Ungair');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andorra');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angòla');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguilla');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Aràibia nan Sabhd');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Arùba');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Asarbaideàn');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Astràilia');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bachrain');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladais');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbados');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bearmùda');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Beinin');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Bhiet-Nam');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Boilibhia');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosna agus Hearsagobhana');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botsuana');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Braisil');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brùnaigh');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Buirciona Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundaidh');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Butàn');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Cailleann Nuadh');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Camarun');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Cambuidea');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Canada');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Casachstàn');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Catar');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Cathair na Bhatacain');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Ceinia');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Ceuta agus Melilla');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Cìopras');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Cìorgastan');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Ciribeas');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Coirèa a Deas');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Coirèa a Tuath');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Coloimbia');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Comoros');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Congo - Kinshasa');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Costa Rìcea');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Côte d’Ivoire');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Cùba');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Cuibhèit');
INSERT INTO [country] ([id], [name]) VALUES ('CW', 'Curaçao');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Deàrsaidh');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Diameuga');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Diego Garcia');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Diobraltar');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Diobùtaidh');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Doiminicea');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Dùthaich nam Mongol');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Dùthaich nan Suasaidh');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Dùthaich nan Tàidh');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Eacuador');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eartra');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Eilean Mhanainn');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Eilean na Deasgabhalach');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Eilean na Nollaig');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Eilean Naomh Eilidh');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Eilean Norfolk');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Eilean Peit a’ Chàirn');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Eileanan Aimeireagach na Maighdinn');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Eileanan Breatannach na Maighdinn');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Eileanan Cook');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Eileanan Mharshall');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Eileanan Sholaimh');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Èirinn');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fìdi');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabon');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Gàna');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Geàrnsaidh');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Gini');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Gini Mheadhan-Chriosach');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Gini Nuadh Phaputhach');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Gini-Bioso');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Greanàda');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Guadalup');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guam');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Guatamala');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guidheàna');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Guidheàna na Frainge');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haidhti');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Hondùras');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Hong Kong SAR na Sìne');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Innis Tìle');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Ioràc');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Ioràn');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Iòrdan');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Iosrael');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Làthos');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Leabanon');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Leasoto');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Libèir');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libia');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Lichtenstein');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Lugsamburg');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Macàthu SAR na Sìne');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagasgar');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Màili');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Mairtinic');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malabhaidh');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malaidhsea');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayotte');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Meagsago');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Meanbh-Eileanan Iomallach nan Stàitean Aonaichte');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Miànmar (Burma)');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monaco');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montsarat');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Moratàinea');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Moroco');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mòsaimbic');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Na h-Eileanan Åland');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Na h-Eileanan Bhathama');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Na h-Eileanan Caimean');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Na h-Eileanan Canàrach');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Na h-Eileanan Cocos (Keeling)');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Na h-Eileanan Fàclannach');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Na h-Eileanan Fàro');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Na h-Eileanan Filipineach');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Na h-Eileanan Mairianach a Tuath');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Na h-Eileanan Mhaladaibh');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Na h-Eileanan Mhoiriseas');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Na h-Eileanan Sheiseall');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Na h-Eileanan Turcach is Caiceo');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Na h-Innd Innse');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Na h-Innseachan');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Na h-Iomaratan Arabach Aonaichte');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Na Meanbh-Eileanan');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Na Ranntairean Palastaineach');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Na Stàitean Aonaichte');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Na Tìrean Ìsle');
INSERT INTO [country] ([id], [name]) VALUES ('BQ', 'Na Tìrean Ìsle Caraibeach');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nabhru');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Naomh Bhionsant agus Eileanan Greanadach');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Naomh Crìstean is Nibheis');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Naomh Lùisea');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Naomh Màrtainn');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Neapàl');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Nìgeir');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nigèiria');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Niocaragua');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niue');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Omàn');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pagastàn');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palabh');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguaidh');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Pearù');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Poblachd Meadhan Afraga');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Poblachd na Seice');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Poilinèis na Frainge');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Porto Rìceo');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Ranntair Breatannach Cuan nan Innseachan');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Ranntairean a Deas na Frainge');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Réunion');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Romàinia');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Rubhanda');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Sàimbia');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Saint Barthélemy');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Saint Pierre agus Miquelon');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samotha');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samotha na h-Aimeireaga');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marino');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'São Tomé agus Príncipe');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Sathara an Iar');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Sealainn Nuadh');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Seanagal');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Seòrsea a Deas is na h-Eileanan Sandwich a Deas');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Siarra Leòmhann');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singeapòr');
INSERT INTO [country] ([id], [name]) VALUES ('SX', 'Sint Maarten');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Siridhea');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somàilia');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sri Lanca');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudàn');
INSERT INTO [country] ([id], [name]) VALUES ('SS', 'Sudàn a Deas');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Suranam');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Svalbard agus Jan Mayen');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taidh-Bhàn');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Taidigeastàn');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timor-Leste');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trianaid agus Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tubhalu');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tuinisea');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turcmanastàn');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Uallas agus Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruguaidh');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Usbagastàn');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
