CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afuganisitani');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Afurika y''Epfo');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Alijeriya');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Alubaniya');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Amazinga y''Isugi y''Abanyamerika');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Amazinga ya Filipine');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Amazinga ya Mariyana ryo mu majaruguru');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Amazinga ya Reyiniyo');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Amazinga ya Salumoni');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Amazinga ya Seyisheli');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Amazinga ya Turkisi na Cayikosi');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andora');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Angwila');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigwa na Baribuda');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Antiye y''Abaholandi');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Arabiya Sawudite');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Arijantine');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Arumeniya');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Ayisilandi');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azerubayijani');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamasi');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahareyini');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangaladeshi');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barubadosi');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Belausi');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belize');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Bene');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Berimuda');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Birimaniya');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Boliviya');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosiniya na Herigozevine');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswana');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Buligariya');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Burezili');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burukina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Buruneyi');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Butani');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Cadi');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Danimariki');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominika');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ekwateri');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Eli Saluvatori');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Elitereya');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Esitoniya');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiyopiya');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fiji');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finilandi');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabo');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambiya');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Gana');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Gerenada');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Gineya Bisawu');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Gineya Ekwatoriyali');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Guneya');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Gurunilandi');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyane');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Gwadelupe');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Gwamu');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Gwatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Gwayana y''Abafaransa');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Hayiti');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Hisipaniya');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Hondurasi');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Hungariya');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Ibirwa by''isugi by''Abongereza');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Ibirwa bya Kapuveri');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Ibirwa bya Keyimani');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ikerene');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indoneziya');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Intara y''Ubwongereza yo mu birwa by''Abahindi');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Iraki');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Irani');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Irigwe');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Irilandi');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Isiraheli');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Izinga rya Filikilandi');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Izinga rya Komore');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Izinga rya Kuku');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Izinga rya Marishari');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Izinga rya Morise');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'izinga rya Norufoluke');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Izinga rya Shipure');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jamayika');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Jeworujiya');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Jibuti');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Juburalitari');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kamboje');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kameruni');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanada');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Katari');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazakisitani');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenya');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kiba');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kirigisitani');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolombiya');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongo');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Koreya y''amajaruguru');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Koreya y''amajepfo');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Korowasiya');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kositarika');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Kotedivuware');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Koweti');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Lativa');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Layosi');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesoto');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Leta Zunze Ubumwe z''Abarabu');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Leta Zunze Ubumwe za Amerika');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Libani');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberiya');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libiya');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Lishyitenshitayini');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lituwaniya');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Lukusamburu');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagasikari');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawi');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Maleziya');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malita');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Maritiniki');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Maroke');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Masedoniya');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayote');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Migizike');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikoroniziya');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Misiri');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Moludave');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moludavi');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monako');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongoliya');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Monteserati');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Moritaniya');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambiki');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibiya');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nawuru');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepali');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Nijeri');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nijeriya');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikaragwa');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Niyukaledoniya');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niyuwe');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Noruveji');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Nuvelizelandi');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Omani');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Ositaraliya');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Otirishe');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakisitani');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palawu');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Palesitina Wesitibanka na Gaza');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papuwa Niyugineya');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paragwe');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peru');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitikeyirini');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Polineziya y''Abafaransa');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Polonye');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Porutugali');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Puwetoriko');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Repubulika Iharanira Demokarasi ya Kongo');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Repubulika ya Ceke');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Repubulika ya Dominika');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Repubulika ya Santarafurika');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Rumaniya');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samowa');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samowa nyamerika');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'Sanimarino');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Sawotome na Perensipe');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Sehelene');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Sekitsi na Nevisi');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Selusiya');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Sempiyeri na Mikeloni');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegali');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Seribiya na Montenegoro');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Sevensa na Gerenadine');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Shili');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Silovakiya');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Siloveniya');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapuru');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sirilanka');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Siriya');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Siyeralewone');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somaliya');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudani');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Suriname');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Suwazilandi');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Suwedi');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tajikisitani');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzaniya');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Tayilandi');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Tayiwani');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timoru y''iburasirazuba');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Tirinidadi na Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelawu');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tuniziya');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Turukiya');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turukumenisitani');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'u Rwanda');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Ububiligi');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Ubudage');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Ubufaransa');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Ubugande');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Ubugereki');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Ubuhindi');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Ubuholandi');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Uburundi');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Uburusiya');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Ubushinwa');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Ubusuwisi');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Ubutaliyani');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Ubuyapani');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Ubwongereza');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Umurwa wa Vatikani');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Uzubekisitani');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuwatu');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuwela');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Viyetinamu');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Walisi na Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yemeni');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Yorudaniya');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambiya');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabwe');
