CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andorradu');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'United Arab Emiratesdu');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afghanistadu');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigua kplɛ Barbudadukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguilladu');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albaniadu');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armeniadu');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Nedalands Antilisdu');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angoladu');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Argentinadu');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Amerika Samoadu');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Austriadu');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Australiadu');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Arubadu');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azerbaigyandu');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnia kplɛ Herzegovinadukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbadosdu');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladesidu');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Belgiumdu');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Fasodu');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgaridu');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahraindu');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundidu');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benindu');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermudadu');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Bruneidu');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Boliviadu');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brazildu');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamasdu');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Bhutandu');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswanadu');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Belarusdu');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belizidu');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanadadu');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Kongo Demokratik Repɔblikdu');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Sentral Afrikan Republikdu');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongodu');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Switzerland-du');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Kote d''ivoiredu');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Kook Ailandsdukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Tsilidu');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kamerundu');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Tsinadu');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolombiadu');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kosta Rikadu');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Serbia kplɛ Montenegrodukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'kubadu');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Kape Verde Ailandsdukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Syprusdu');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Tsek Repɔblikdu');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Germanidu');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Dzibutidu');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Denmarkdu');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominikadu');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Dominika Repɔblikdu');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Algeriadu');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ekuadɔdu');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estoniadu');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Egyptdu');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritreadu');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Spaindu');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiopiadu');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finland-du');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fidzidu');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Falklanɖ Ailandsdukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikronesiadu');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Fransdu');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabɔndu');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'United Kingdomdu');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grenadadu');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Georgiadu');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Frentsi Guianadu');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ghanadu');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Gibraltadu');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Greenland-du');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambiadu');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Guinidu');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Guadelupedu');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Ekuatorial Ginidu');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Greesidu');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Guatemayadu');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guamdu');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Gini-Bisaodu');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyanadu');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Hondurasdu');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Kroashiadu');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haitidu');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Hungaridu');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonesiadu');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Ireland-du');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Izraldu');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Inɖiadu');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'British India Oshiin Territorydu');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Irakdu');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Irandu');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Aiselanddu');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Italidu');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Gyamaikadu');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Gyɔdandu');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Gyapandu');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenyadu');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kyrgyzstandu');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kambodiadu');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribatidu');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Komorosdu');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Saint Kitis kplɛ Nevisdukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'North Koreadu');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'South Koreadu');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuwaitdu');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Kayman Ailandsdukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazakstandu');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laosdu');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Lebanɔndu');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Saint Lusiadu');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Litsensteindu');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sri Lankadu');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberiadu');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lɛsotodu');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lituaniadu');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Luxembɔgdu');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Latviadu');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libyadu');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Morokodu');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monakodu');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldovadu');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagaskadu');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Marshal Aislandsdu');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Masedoniadu');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Malidu');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myanmardu');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongoliadu');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Norh Mariana Ailandukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martinikidu');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mɔritaniadu');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montserratdu');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Maltadu');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Mɔritiusdu');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maldivisdu');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawidu');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mesikodu');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malaysiadu');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambikidu');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibiadu');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'New Kaledoniadu');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Nigerdu');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Norfolk Ailanddu');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nigeriadu');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikaraguadu');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Nedalandsdu');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norwaydu');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepaldu');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Naurudu');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niuedu');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'New Zealand-du');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Omandu');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panamadu');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Perudu');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Frentsi Polynesiadu');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papua New Guineadu');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Philipinsdu');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistandu');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Polandu');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Saint Pierre kplɛ Mikelɔndukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitkairndu');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Puerto Rikodu');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Palestinia West Bank kplɛ Gazadukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portugaldu');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palaudu');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguadu');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Katadu');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Reuniondu');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Romaniadu');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Russiadu');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Rwandadu');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Saudi Arabiadu');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Solomon Ailandukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seyshɛlsdu');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudandu');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Swedendu');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapɔrdu');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Saint Helenadu');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Sloveniadu');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovakiadu');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sierra Leonedu');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marinodu');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegaldu');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somaliadu');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinamedu');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Sao Tome kplɛ Prinsipidukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'El Savadɔdu');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Syriadu');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Swaziland-du');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Turks kplɛ kaikos Islandsdukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Tsad-du');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togodu');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Thailand-du');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Taghikistandu');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelaudu');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'East Timordu');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turkmenistandu');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunisiadu');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tongadu');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Turkeedu');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidad kplɛ Tobagodukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvaludu');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwandu');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzaniadu');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukrainedu');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Ugandadu');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'USA-dukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruguaydu');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Uzbekistandu');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatikan Statedu');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Saint Vinsent kplɛ Grenadinisdukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezueladu');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'British Virgin Islandsdukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'U.S Virgin Islandsdukɔwo');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietnamdu');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatudu');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wallis kplɛ Futunadu');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoadu');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yemendu');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayotidu');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'South Afrikadu');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambiadu');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabwedu');
