CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afghanistan');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Ägypten');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Alandinseln');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albanien');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Algerien');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'Amerikanisch-Ozeanien');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Amerikanisch-Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Amerikanische Jungferninseln');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andorra');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Anguilla');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Antarktis');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigua und Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Äquatorialguinea');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argentinien');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armenien');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'Ascension');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Aserbaidschan');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Äthiopien');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'Äußeres Ozeanien');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Australien');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamas');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrain');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladesch');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbados');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Belarus');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belgien');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benin');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Bhutan');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolivien');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosnien und Herzegowina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botsuana');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'Bouvetinsel');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brasilien');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Britische Jungferninseln');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Britisches Territorium im Indischen Ozean');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgarien');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'Ceuta und Melilla');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Chile');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'China');
INSERT INTO `country` (`id`, `name`) VALUES ('CP', 'Clipperton-Insel');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Cookinseln');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Costa Rica');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Côte d’Ivoire');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Dänemark');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Demokratische Volksrepublik Korea');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Deutschland');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'Diego Garcia');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominica');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Dominikanische Republik');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Dschibuti');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ecuador');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'El Salvador');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritrea');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estland');
INSERT INTO `country` (`id`, `name`) VALUES ('EU', 'Europäische Union');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Falklandinseln');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Färöer');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fidschi');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finnland');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Frankreich');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Französisch-Guayana');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Französisch-Polynesien');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'Französische Süd- und Antarktisgebiete');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabun');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Georgien');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ghana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Gibraltar');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Griechenland');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Grönland');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Guadeloupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guam');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Guatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'Guernsey');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'Heard- und McDonald-Inseln');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Indien');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonesien');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Irak');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iran');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irland');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Island');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'Isle of Man');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Israel');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italien');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaika');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japan');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Jemen');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'Jersey');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordanien');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Kaimaninseln');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambodscha');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kamerun');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'Kanarische Inseln');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Kap Verde');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kasachstan');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Katar');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenia');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirgisistan');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'Kokosinseln');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolumbien');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Komoren');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongo-Brazzaville');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Kongo-Kinshasa');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Kroatien');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kuba');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuwait');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laos');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Lettland');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libanon');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberia');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libyen');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Liechtenstein');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Litauen');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Luxemburg');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagaskar');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malaysia');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Malediven');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Marokko');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Marshallinseln');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinique');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauretanien');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Mauritius');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayotte');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Mazedonien');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Mexiko');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikronesien');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monaco');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongolei');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mosambik');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Myanmar');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibia');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepal');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Neukaledonien');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Neuseeland');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nicaragua');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Niederlande');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Niederländische Antillen');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Niger');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigeria');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Nördliche Marianen');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Norfolkinsel');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norwegen');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Österreich');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Osttimor');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Palästinensische Autonomiegebiete');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papua-Neuguinea');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paraguay');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Philippinen');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitcairn');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Polen');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portugal');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Puerto Rico');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Republik Korea');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Republik Moldau');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Réunion');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Ruanda');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Rumänien');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Russische Föderation');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Salomonen');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Sambia');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'São Tomé und Príncipe');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Saudi-Arabien');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Schweden');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Schweiz');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegal');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Serbien');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Serbien und Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seychellen');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sierra Leone');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Simbabwe');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapur');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Slowakei');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Slowenien');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somalia');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'Sonderverwaltungszone Hongkong');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Sonderverwaltungszone Macao');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Spanien');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'St. Barthélemy');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'St. Helena');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'St. Kitts und Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'St. Lucia');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'St. Martin');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'St. Pierre und Miquelon');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'St. Vincent und die Grenadinen');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Südafrika');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudan');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'Südgeorgien und die Südlichen Sandwichinseln');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Suriname');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Svalbard und Jan Mayen');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Swasiland');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Syrien');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tadschikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tansania');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Thailand');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad und Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Tschad');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Tschechische Republik');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunesien');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Türkei');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Turks- und Caicosinseln');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukraine');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Ungarn');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Uruguay');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Usbekistan');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatikanstadt');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Vereinigte Arabische Emirate');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Vereinigte Staaten');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Vereinigtes Königreich');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vietnam');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis und Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Weihnachtsinsel');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Westsahara');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Zentralafrikanische Republik');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Zypern');
