CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Undura');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Tigeldunin Yedduklen Taɛrabin');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afɣanistan');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Untiga d Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Ungiya');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Lalbani');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Arminya');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Antilles n Tmura-Yessakesren');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Ungula');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Arjuntin');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samwa Tamarikanit');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Ustriya');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Ustrali');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azrabijan');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Busna d Hersek');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbadus');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladac');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Belǧik');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Fasu');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgari');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Baḥrin');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burandi');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Binin');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermuda');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Bruney');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bulivi');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brizil');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamas');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Bhutan');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Bustwana');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Bilarus');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Biliz');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanada');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Tigduda Tagdudant n Kungu');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Tigduda n Tefriqt Talemmast');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kungu');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Swis');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Kuṭ Divwar');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Tigzirin n Kuk');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Cili');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kamirun');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Lacin');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kulumbi');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kusta Rika');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Sirbya d Muntinigru');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kuba');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Tigzirin n yixef azegzaw');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Cipr');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Čček');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Lalman');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Ǧibuti');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Denmark');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Duminik');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Tigduda Taduminikit');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Lezzayer');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ikwaṭur');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Istunya');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Maṣr');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Iritiria');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Spanya');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Utyupi');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finlund');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fiji');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Tigzirin n Falkland');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikrunizya');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Fransa');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabun');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Tagelda Yedduklen');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grunad');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Jiyurji');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Ɣana tafransist');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ɣana');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Jibraltar');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Grunland');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambya');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Ɣinya');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Gwadalupi');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Ɣinya Tasebgast');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Lagris');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Gwatimala');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Gwam');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Ɣinya-Bisaw');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guwana');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Hunduras');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Kerwasya');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Hayti');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Hungri');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indunizi');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Lirlund');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Izrayil');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Lhend');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Akal Aglizi deg Ugaraw Ahendi');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Lɛiraq');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Iran');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Island');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Ṭelyan');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jamyika');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Lajurdani');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Jappu');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kinya');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kirigistan');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Cambudya');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Kumur');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'San Kits d Nivis');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Kurya, Ufella');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Kurya, Wadda');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuwayt');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Tigzirin n Kamyan');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazaxistan');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laws');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Lubnan');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'San Lučya');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Layctenstan');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Libirya');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lizuṭu');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Liṭwanya');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Luksamburg');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Latvia');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libya');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Lmerruk');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Munaku');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Muldabi');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madaɣecqer');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Tigzirin n Marcal');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Masidwan');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myanmar');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mungulya');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Tigzirin n Maryan Ufella');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martinik');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Muriṭanya');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Munsirat');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malṭ');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Muris');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maldib');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawi');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Meksik');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malizya');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Muzembiq');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibya');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Kalidunya Tamaynut');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Nijer');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Tigzirin Tinawfukin');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nijirya');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikaragwa');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Timura-Yessakesren');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Nurvij');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nipal');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nuru');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niwi');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Ziland Tamaynut');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Ɛuman');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panam');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Piru');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Pulunizi tafransist');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Ɣinya Tamaynut Tapaput');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipin');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistan');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Pulund');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'San Pyar d Miklun');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitkarin');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Purtu Riku');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Falisṭin d Ɣezza');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Purtugal');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palu');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paragway');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Qaṭar');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Timlilit');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Rumani');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rrus');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Ruwanda');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Suɛudiya Taɛrabt');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Tigzirin n Sulumun');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seycel');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudan');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Swid');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singafur');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Sant Ilina');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Sluvinya');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Sluvakya');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sira Lyun');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marinu');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Sinigal');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Ṣumal');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinam');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Saw Tumi d Pransip');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Salvadur');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Surya');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Swazilund');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Ṭurk d Tegzirin n Kaykus');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Čad');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Ṭugu');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Ṭayland');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tajikistan');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Ṭuklu');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Tumur Asamar');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Ṭurkmanistan');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunes');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Ṭunga');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Ṭurk');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Ṭrindad d Ṭubagu');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Ṭuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Ṭaywan');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Ṭanzanya');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukran');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uɣanda');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'WDM');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Urugway');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Uzbaxistan');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Awanek n Vatikan');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'San Vansu d Grunadin');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venzwila');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Tigzirin Tiverjiniyin Tigliziyin');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'W.D. Tigzirin n Virginya');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vyeṭnam');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanwatu');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wallis d Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samwa');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Lyamen');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayuṭ');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Tafriqt Wadda');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambya');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabwi');
