CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afghanistan');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Ålân');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albanië');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Algerije');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Amerikaansk Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Amerikaanske Maagdeneilannen');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andorra');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Anguilla');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Antarctica');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigua en Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argentinië');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armenië');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'Ascension');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Australië');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azerbeidzjan');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahama’s');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrein');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladesh');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbados');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'België');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benin');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Bhutan');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolivia');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosnië en Herzegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brazilië');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Britse Gebieden yn de Indyske Oseaan');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Britse Maagdeneilannen');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgarije');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Cambodja');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Canada');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Caymaneilannen');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'Ceuta en Melilla');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Chili');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Comoren');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Congo-Brazzaville');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Congo-Kinshasa');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Cookeilannen');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Costa Rica');
INSERT INTO `country` (`id`, `name`) VALUES ('CW', 'Curaçao');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Denemarken');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'Diego Garcia');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Djibouti');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominika');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Dominikaanske Republyk');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Dútslân');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'East-Timor');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Eastenryk');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ecuador');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Egypte');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'El Salvador');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Equatoriaal-Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritrea');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estlân');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Ethiopië');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Faeröer');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Falklâneilannen');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Ferienigde Staten');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fiji');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filipijnen');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finlân');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Frankrijk');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Frans-Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Frans-Polynesië');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'Franse Gebieden in de zuidelijke Indyske Oseaan');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabon');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Georgië');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ghana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Gibraltar');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Grienlân');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Grikelân');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Guadeloupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guam');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Guatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'Guernsey');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Guinee');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Guinee-Bissau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haïti');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Hongarije');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'Hongkong SAR van Sina');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Ierlân');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'India');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Irak');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iran');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'Isle of Man');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Israël');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italië');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Ivoorkust');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaica');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japan');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Jemen');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'Jersey');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordanië');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Kaapverdië');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kameroen');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'Kanaryske Eilânnen');
INSERT INTO `country` (`id`, `name`) VALUES ('BQ', 'Karibysk Nederlân');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazachstan');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenia');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirgizië');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Koeweit');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'Kokosilanen');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolombia');
INSERT INTO `country` (`id`, `name`) VALUES ('XK', 'Kosovo');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Kroatië');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Krysteilan');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kuba');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laos');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Letlân');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libanon');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberia');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libië');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Liechtenstein');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Litouwen');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Luxemburg');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'Lyts ôflizzen eilannen fan de Ferienigde Staten');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Macao SAR van Sina');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Macedonië');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madeiaskar');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldiven');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Maleisië');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Marokko');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Marshalleilannen');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinique');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauritanië');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Mauritius');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayotte');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Mexico');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Micronesië');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldavië');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monaco');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongolië');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambique');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Myanmar (Birma)');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibië');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Nederlân');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepal');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nicaragua');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Niger');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigeria');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Nij-Caledonië');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Nij-Seelân');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Noard-Korea');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Noardlike Marianeneilannen');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Noarwegen');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Norfolkeilân');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Oeganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Oekraïne');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Oezbekistan');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Palestynske gebieten');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papoea-Nij-Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paraguay');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitcairneilannen');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Polen');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portugal');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Puerto Rico');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Qatar');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Réunion');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Roemenië');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Ruslân');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Rwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'Saint Barthélemy');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Saint Kitts en Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Saint Lucia');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Saint Vincent en de Grenadines');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'Saint-Martin');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Saint-Pierre en Miquelon');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Salomonseilannen');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Sao Tomé en Principe');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Saoedi-Arabië');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegal');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Servië');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seychellen');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sierra Leone');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Sina');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapore');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Sint-Helena');
INSERT INTO `country` (`id`, `name`) VALUES ('SX', 'Sint-Maarten');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Sintraal-Afrikaanske Republyk');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Slovenië');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Slowakije');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Soedan');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somalië');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Spanje');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Spitsbergen en Jan Mayen');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Sûd-Afrika');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'Sûd-Georgia en Sûdlike Sandwicheilannen');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Sûd-Korea');
INSERT INTO `country` (`id`, `name`) VALUES ('SS', 'Sûd-Soedan');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Suriname');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Swazilân');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Switserlân');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Syprus');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Syrië');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tadzjikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzania');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Thailân');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad en Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Tsjaad');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Tsjechje');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunesië');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Turkije');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Turks- en Caicoseilannen');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Uruguay');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vaticaanstêd');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Verenigd Koninkrijk');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Verenigde Arabyske Emiraten');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vietnam');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis en Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Westelijke Sahara');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Wit-Ruslân');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Yndonesië');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Yslân');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambia');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Zweden');
