CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Австралія');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Австрія');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Азербайджан');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Аландські острови');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Албанія');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Алжир');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Американське Самоа');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Ангілья');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Ангола');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Андорра');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Антарктида');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Антигуа і Барбуда');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Аргентина');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Аруба');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Афганістан');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Багами');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Бангладеш');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Барбадос');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Бахрейн');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Беліз');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Бельгія');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Бенін');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Бермуди');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Білорусь');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Болгарія');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Болівія');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Боснія і Герцоговина');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Ботсвана');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Бразилія');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Британські території Індійського океану');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Бруней');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Буркіна-Фасо');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Бурунді');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Бутан');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Вʼєтнам');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Вануату');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Ватикан');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Великобританія');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Венесуела');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Віддалені Острови США');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Віргінські острови Британії');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Віргінські острови США');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Вірменія');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Габон');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Гаїті');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Гайана');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Гамбія');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Гана');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Гваделупа');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Гватемала');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Гвінея');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Гвінея-Біссау');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Гернсі');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Гібралтар');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Гондурас');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Гонконґ О.А.Р. Китаю');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Гренада');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Гренландія');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Греція');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Грузія');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Гуам');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Данія');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Джерсі');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Джібуті');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Дієґо-Ґарсія');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Домінік');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Домініканська Республіка');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Еквадор');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Екваторіальна Гвінея');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Еритрея');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Естонія');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Ефіопія');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'Європейський Союз');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Єгипет');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Ємен');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Замбія');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Західна Сахара');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Зімбабве');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Ізраїль');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Індія');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Індонезія');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'Інша Океанія');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Ірак');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Іран');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Ірландія');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Ісландія');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Іспанія');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Італія');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Йорданія');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Кабо-Верде');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Казахстан');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Кайманові острови');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Камбоджа');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Камерун');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Канада');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Канарські острови');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Катар');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Кенія');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Киргизстан');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Китай');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Кіпр');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Кірибаті');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Кокосові острови');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Колумбія');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Коморські Острови');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Конґо - Браззавіль');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Конґо - Кіншаса');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Коста-Рика');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Кот д’Івуар');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Куба');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Кувейт');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Лаос');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Латвія');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Лесото');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Литва');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Ліберія');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Ліван');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Лівія');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Ліхтенштейн');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Люксембург');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Мʼянма [Бірма]');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Маврикій');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Мавританія');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Мадагаскар');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Майот');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Макао О.А.Р. Китаю');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Македонія');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Малаві');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Малайзія');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Малі');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Мальдіви');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Мальта');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Марокко');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Мартиніка');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Маршаллові Острови');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Мексика');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Мікронезія');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Мозамбік');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Молдова');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Монако');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Монголія');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Монсеррат');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Намібія');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Науру');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Непал');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Нігер');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Нігерія');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Нідерланди');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Нідерландські Антильські Острови');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Нікарагуа');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Німеччина');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Нія');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Нова Зеландія');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Нова Каледонія');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Норвегія');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Обʼєднані Арабські Емірати');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Оман');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Острів Буве');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Острів Вознесіння');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'Острів Кліппертон');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Острів Мен');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Острів Норфолк');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Острів Різдва');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Острів Святого Бартоломея');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Острів Святого Мартіна');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Острів Святої Єлени');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Острови Кука');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Острови Піткерн');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Острови Свальбард та Ян-Маєн');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'Острови Херд і Мак-Дональд');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Пакистан');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Палау');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Палестина');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Панама');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Папуа Нова Гвінея');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'ПАР');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Парагвай');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Перу');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Південна Джорджія та Південні Сандвічеві Острови');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Південна Корея');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Північна Корея');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Північні Маріанські Острови');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Польща');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Португалія');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Пуерто-Ріко');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Реюньйон');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Росія');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Руанда');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Румунія');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Сальвадор');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Самоа');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'Сан-Марино');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Сан-Томе і Прінсіпі');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Саудівська Аравія');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Свазіленд');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Сейшели');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Сен-Пʼєр і Мікелон');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Сенегал');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Сент-Вінсент і Гренадини');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Сент-Кітс і Невіс');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Сент-Люсія');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Сербія');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Сербія та Чорногорія');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Сеута і Мелілья');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Сирія');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Сінгапур');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Словакія');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Словенія');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Соломонові Острови');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Сомалі');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Судан');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Суринам');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'США');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Сьєрра-Леоне');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Таджикистан');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Таїланд');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Тайвань');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Танзанія');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Теркс і Кайкос');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Тімор-Лешті');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Того');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Токелау');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Тонга');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Тринідад і Тобаго');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Трістан-да-Кунья');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Тувалу');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Туніс');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Туреччина');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Туркменистан');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Уганда');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Угорщина');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Узбекистан');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Україна');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Уолліс і Футуна');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Уругвай');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Фарерські острови');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Фіджі');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Філіппіни');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Фінляндія');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Фолклендські острови');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Франція');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Французька Гвіана');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Французька Полінезія');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Французькі Південні Території');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Хорватія');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Центральноафриканська Республіка');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Чад');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Чеська республіка');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Чилі');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Чорногорія');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Швейцарія');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Швеція');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Шрі-Ланка');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Ямайка');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Японія');
