CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afganistan');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albania');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Alemanha');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andòrra');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguilla');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angòla');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Antartica');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigua e Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Arabia Saudita');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Argentina');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Argeria');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armènia');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Austràlia');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azerbaijan');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamas');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahrain');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladesh');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbados');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Belau');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Belgica');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belize');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benin');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermuda');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Bielorussia');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Birmania');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bolgària');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolívia');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Botan');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswana');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brasil');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunei');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bòsnia e Ercegovina');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Cambòja');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Cameron');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Canadà');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Cap Verd');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Cazacstan');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Chad');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Chile');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'China');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Chipre');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Colómbia');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Comòros');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Corèa del Nòrd');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Corèa del Sud');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Croàcia');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Cuba');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Còngo - Brazzaville');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Còngo - Kinshasa');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Còsta Rica');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Còsta d''Evòri');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Danemarc');
INSERT INTO [country] ([id], [name]) VALUES ('ZZ', 'Desconegut o Region invalida');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Egipte');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Eqüator');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritrèa');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Espanha');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Estats Units');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estònia');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiopia');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fiji');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finlàndia');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'França');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabon');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Guiana francesa');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Guinèa Eqüatoriala');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Isla Bouvet');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Islas Caiman');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Israèl');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Itàlia');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Japon');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Jiboti');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libia');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Lo Salvador');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Marròc');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mauritània');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Moçambic');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Mónegue');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peró');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portugal');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Reiaume Unit');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Republica Centraficana');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Republica chèca');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Republica dominicana');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Russia');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samòa americana');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Soïssa');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Súria');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timòr Èst');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ucràina');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Veneçuèla');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietnam');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Àustria');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Índia');
