CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afganistan');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Åland-eilande');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albanië');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Algerië');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Amerikaans Samoa');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andorra');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anguilla');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Antarktika');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua en Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Argentinië');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armenië');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'Ascension-eiland');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Aserbeidjan');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Australië');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahamas');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahrein');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladesj');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbados');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'België');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belize');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benin');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermuda');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Bhoetan');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Boerkina Fasso');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolivië');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosnië en Herzegowina');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botswana');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Bouveteiland');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brasilië');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Britse Indiese Oseaan Gebied');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Britse Maagde-eilande');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Broenei');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulgarye');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'Ceuta en Melilla');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Chili');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Ciprus');
INSERT INTO "country" ("id", "name") VALUES ('CP', 'Clipperton-eiland');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Cocos- [Keeling] eilande');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Comore');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Cookeilande');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Costa Rica');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Demokratiese Republiek van die Kongo');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Denemarke');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'Diego Garcia');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Djiboeti');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominika');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Dominikaanse Republiek');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Duitsland');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ecuador');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Egipte');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Eiland Man');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Ekwatoriaal-Guinee');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritrea');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Estland');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Ethiopië');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'Europese Unie');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Falklandeilande');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Faroëreilande');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fidji');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filippyne');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finland');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Frankryk');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Frans-Guyana');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Frans-Polinesië');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Franse Suidelike Gebiede');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gaboen');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambië');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Georgië');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Ghana');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Gibraltar');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenada');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Griekeland');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Groenland');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Groot-Brittanje');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadeloupe');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatemala');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Guernsey');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Guinee');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Guinee-Bissau');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guyana');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haïti');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Heard-eiland en McDonald-eilande');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduras');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Hongarye');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Hongkong');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Ierland');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Indië');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indonesië');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Irak');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Iran');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Israel');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Italië');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Ivoorkus');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamaika');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japan');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Jemen');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Jersey');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jordanië');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Kaaimanseilande');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Kaap Verde');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kambodja');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kameroen');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'Kanarie-eilande');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kasakstan');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Katar');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenia');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Kerseiland');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirgisië');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Koeweit');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolombië');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Kroasië');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kuba');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laos');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesotho');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Letland');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Libanon');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberië');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libië');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Liechtenstein');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Litaue');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luxemburg');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Macau SAR China');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Macedonië');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagaskar');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malawi');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maledive');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Maleisië');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Marokko');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Marshall-eilande');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martinique');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Mauritius');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayotte');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Meksiko');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Mianmar');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikronesië');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldova');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monaco');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongolië');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Montserrat');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mosambiek');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mouritanië');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibië');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Naoeroe');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Nederland');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Nederlands-Antille');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepal');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nicaragua');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Nieu-Kaledonië');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Nieu-Seeland');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Niger');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nigerië');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Noord-Korea');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Noordelike Marianaeilande');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Noorweë');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Norfolk-eiland');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Oekraine');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Oesbekistan');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Oman');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'Omliggende Oseanië');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Oos-Timor');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Oostenryk');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakistan');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palestina');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papoea Nieu-Guinee');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguay');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Peru');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitcairn');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Pole');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portugal');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Puerto Rico');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Réunion');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Roemenië');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Rusland');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Rwanda');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Saint Kitts en Nevis');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Saint Vincent en die Grenadine');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Salvador');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samoa');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'San Marino');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sao Tome en Principe');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Saoedi-Arabië');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegal');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Sentraal-Afrikaanse Republiek');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Serwië');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Serwië en Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Seychelle');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Sierra Leone');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapoer');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'Sint Barthélemy');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Sint Helena');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Sint Lucia');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'Sint Martin');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Sint-Pierre en Miquelon');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Sirië');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Sjina');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slowakye');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Slowenië');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Soedan');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Solomon Eilande');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somalië');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Spanje');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Suid-Afrika');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'Suid-Georgië en die Suid-Sandwich-eilande');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Suid-Korea');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Suriname');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Svalbard en Jan Mayen');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Swaziland');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Swede');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Switserland');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tadjikistan');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taiwan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzanië');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Thailand');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Tjeggiese Republiek');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad en Tobago');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'Tristan da Cunha');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Tsjaad');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunisië');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turkmenië');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Turks en Caicos Eilande');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Turkye');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uganda');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruguay');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'V.S. Maagde-eilande');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikaan');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezuela');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Verenigde Arabiese Emirate');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Verenigde State van Amerika');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Viëtnam');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'VS klein omliggende eilande');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis en Futuna');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Wes-Sahara');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Wit-Rusland');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Ysland');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambië');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabwe');
