CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afganistanas');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Airija');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Alandų Salos');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albanija');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Alžyras');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Amerikos Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andora');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Angilija');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Antarktida');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigva ir Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Argentina');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armėnija');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Australija');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Austrija');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azerbaidžanas');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamos');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahreinas');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Baltarusija');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladešas');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbadosas');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Belgija');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belizas');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Beninas');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermuda');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Bisau Gvinėja');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolivija');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnija ir Hercegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botsvana');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brazilija');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunėjus');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgarija');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Fasas');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundis');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Butanas');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Centrinės Afrikos Respublika');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Čadas');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Čekija');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Čilė');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Dangun Žengimo sala');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Danija');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Didžioji Britanija');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Didžiosios Britanijos Mergelių Salos');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Diego Garsija');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominika');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Dominikos Respublika');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Dramblio Kaulo Krantas');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Džersis');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Džibutis');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Egiptas');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ekvadoras');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritrėja');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estija');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiopija');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Farerų Salos');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fidžis');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipinai');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Folklando Salos');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabonas');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Gajana');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambija');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Gana');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Gernsis');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Gibraltaras');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Graikija');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grenada');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Grenlandija');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Gruzija');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guamas');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Gvadelupa');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Gvatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Gvinėja');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haitis');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Hondūras');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Indija');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Indijos Vandenyno Britų Sritis');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonezija');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Ypatingasis Administracinis Kinijos Regionas Honkongas');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Ypatingasis Administracinis Kinijos Regionas Makao');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Irakas');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Iranas');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Islandija');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Ispanija');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Italija');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Izraelis');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jamaika');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Japonija');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Jemenas');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Jordanija');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Jungtinės Valstijos');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Jungtiniai Arabų Emyratai');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Jungtinių Valstijų Mažosios Tolimosios Salos');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Jungtinių Valstijų Mergelių Salos');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Juodkalnija');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Kaimanų Salos');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Kalėdų Sala');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kambodža');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kamerūnas');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanada');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Kanarų salos');
INSERT INTO [country] ([id], [name]) VALUES ('BQ', 'Karibų Nyderlandai');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Kataras');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazachstanas');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenija');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Kinija');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Kipras');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kirgizija');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribatis');
INSERT INTO [country] ([id], [name]) VALUES ('CW', 'Kiurasao');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Kokosų (Kilingo) Salos');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolumbija');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Komorai');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongas-Brazavilis');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Kongas-Kinšasa');
INSERT INTO [country] ([id], [name]) VALUES ('XK', 'Kosovas');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kosta Rika');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Kroatija');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kuba');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Kuko Salos');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuveitas');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laosas');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Latvija');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Lenkija');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesotas');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Libanas');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberija');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libija');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Lichtenšteinas');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lietuva');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Liuksemburgas');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagaskaras');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Majotas');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Makedonija');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malaizija');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malavis');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maldyvai');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Malis');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Marianos Šiaurinės Salos');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Marokas');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Maršalo Salos');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martinika');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Mauricijus');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mauritanija');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Meksika');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Meno Sala');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Mianmaras (Birma)');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikronezija');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldova');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monakas');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongolija');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montseratas');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambikas');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibija');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Naujoji Kaledonija');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Naujoji Zelandija');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nauru');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepalas');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Nyderlandai');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nigerija');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Nigeris');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikaragva');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niujė');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Norfolko sala');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norvegija');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Omanas');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistanas');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Palestinos teritorija');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papua Naujoji Gvinėja');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paragvajus');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peru');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Pietų Afrika');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Pietų Džordžija ir Pietų Sandvičo salos');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Pietų Korėja');
INSERT INTO [country] ([id], [name]) VALUES ('SS', 'Pietų Sudanas');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitkernas');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portugalija');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Prancūzija');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Prancūzijos Gviana');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Prancūzijos Pietų sritys');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Prancūzų Polinezija');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Puerto Rikas');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Pusiaujo Gvinėja');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Reunjonas');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Rytų Timoras');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Ruanda');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Rumunija');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rusija');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Saliamono Salos');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Salvadoras');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marinas');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'San Tomė ir Prinsipė');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Saudo Arabija');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seišeliai');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Sen Bartelemi');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Sen Martenas');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Sen Pjeras ir Mikelonas');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegalas');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Sent Kitsas ir Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Serbija');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Seuta ir Melila');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Siera Leonė');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapūras');
INSERT INTO [country] ([id], [name]) VALUES ('SX', 'Sint Martenas');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Sirija');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovakija');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slovėnija');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somalis');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudanas');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Suomija');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinamas');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Svalbardas ir Janas Majenas');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Svazilandas');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Šiaurės Korėja');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Šri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Šv. Elenos Sala');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Švedija');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Šveicarija');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Šventasis Vincentas ir Grenadinai');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Šventoji Liucija');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tadžikija');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Tailandas');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taivanas');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzanija');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Terkso ir Kaikoso Salos');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togas');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidadas ir Tobagas');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Tristanas da Kunja');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunisas');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Turkija');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turkmėnistanas');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukraina');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Urugvajus');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Uzbekistanas');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Vakarų Sachara');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatikano Miesto Valstybė');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venesuela');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Vengrija');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietnamas');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Vokietija');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Volisas ir Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambija');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabvė');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Žaliasis Kyšulys');
