CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ER', 'ꔀꔸꔳꕟ');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'ꔆꔷꔘ');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'ꔋꕩ ꕒꕌꖺ ꕸꖃꔀ');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'ꔎꔒ ꗃ ꔳꗞꖻ');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'ꔒꔫꕩ');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'ꔒꕑꗟꘋ');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'ꔓꗠꖻ');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'ꔖꗼꔷ');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'ꔚꔷ');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'ꔛꔟꔻ ꔤꔺꕩ ꗛꔤꘂ ꕗꕴꔀ ꕮ');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'ꔛꔟꔻ ꗩꗡ ꗏ ꖷꖬ ꔳꘋꗣ');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'ꔛꗨꗢ');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'ꔝꘈꘋ');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'ꔞꔀꕮꘋ ꔳꘋꗣ');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'ꔞꔪ ꗲꔵ ꔳꘋꗣ');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'ꔞꕰ');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'ꔤꔳꖎꔪꕩ');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'ꔤꔺꕩ');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'ꔤꕚꔷ');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'ꔤꕟꕃ');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'ꔤꕟꘋ');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'ꔤꖆꕇꔻꕩ');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'ꔪꔳꕪꕆ');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'ꔪꖳꕿ ꔸꖏ');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'ꔱꔒꔪꘋ');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'ꔱꔤꕀ');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'ꔱꘋ ꖨꕮꕊ');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'ꔷꖇꕿ');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'ꔷꖤꔃꕇꕰ');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'ꔷꗿꘋꔻꗳꘋ');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'ꔻꕇꕭꕌ');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'ꔻꕩꘋ');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'ꔻꕬꕶꕱ');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'ꔻꖃꔍꕇꕰ');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'ꔻꖃꕙꕃꕩ');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'ꔻꘋ ꔪꘂ ꗪ ꕆꔞꗏꘋ');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'ꔻꘋ ꔲꘋꔻꘋ ꗪ ꖶꔓꕯꔵꘋ ꖸ');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'ꔻꘋ ꕃꔳꔻ ꗪ ꔕꔲꔻ');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'ꔻꘋ ꖨꔻꕩ');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'ꔻꘋ ꗥꔷꕯ');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'ꔽꔤ ꖨꕮ ꕯꕮꕊ');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'ꔽꕓꖜꔃ');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'ꕀꖜꔳ');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'ꕀꖜꕟꕚ');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'ꕃꔸꕑꔳ');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'ꕃꕅꔻꕚꘋ');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'ꕃꖳꕑ');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'ꕅꔤꕇ');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'ꕅꔤꕇ ꔫꕢꕴ');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'ꕆꔖꕞ');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'ꕆꕩꘋꕮ');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'ꕆꖏꕇꔻꕩ');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'ꕇꕐꔷ');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'ꕇꕪꕟꖶꕎ');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'ꕉꔓ ꖨꕮꕊ');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'ꕉꔤꔻ ꖨꕮꕊ');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'ꕉꔱꔸꕪ ꗛꔤ ꔒꘋꗣ ꗏ ꕸꖃꔀ');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'ꕉꔱꔸꕪ ꗳ ꗳ ꕸꖃꔀ');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'ꕉꔱꕭꔕꔻꕚꘋ');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'ꕉꔷꔠꔸꕩ');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'ꕉꔷꕑꕇꕩ');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'ꕉꕄꕞ');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'ꕉꕆꕯ');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'ꕉꕤꕑꔤꕧꘋ');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'ꕉꖆꕟ');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'ꕉꖐꕞ');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'ꕉꖩꕑ');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'ꕉꘀꘋꔳꕯ');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'ꕉꘋꔳꖶꕎ ꗪ ꕑꖜꕜ');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'ꕌꔤꔳ');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'ꕎꔷꔻ ꗪ ꖢꖤꕯ');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'ꕐꔒꔻꔳꕯ ꔎꔒ ꕀꔤ ꗛꔤ ꕞ ꗱ ꗪ ꕭꕌꕤ');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'ꕐꕃꔻꕚꘋ');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'ꕐꕟꗝꔀ');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'ꕐꕯꕮ');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'ꕐꖃ');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'ꕐꖛꕎ ꕅꔤꕇ ꕯꕮꕊ');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'ꕐꘊꔧ');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'ꕑꔆꖁꔻ');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'ꕑꕅꕞꗵꔼ');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'ꕑꕇꔻꕞꔤꕞ');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'ꕑꕌꕮꔻ');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'ꕑꗸꘋ');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'ꕘꔷꕃ ꖨꕮ ꔳꘋꗣ');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'ꕙꔳꕪꘋ ꕸꖃꔀ');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'ꕙꖸꕎꖤ');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'ꕚꔤ ꖨꕮꕊ');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'ꕚꔤꕎꘋ');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'ꕚꕀꕃꔻꕚꘋ');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'ꕚꖣꖨ');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'ꕚꘋꕤꕇꕰ');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'ꕜꕇꕮꕃ');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'ꕞꔤꔫꕩ');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'ꕞꔳꔲꕩ');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'ꕞꕌꖝ ꕸꖃꔀ');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'ꕞꕴꔻ');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'ꕟꖙꕡ');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'ꕢꕴ ꕿꔈ ꗪ ꕉ ꕮꔧ ꕗꕴꔀ');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'ꕢꕹꖙꕉ');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'ꕢꗡꖛꗐꔻ');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'ꕤꔭꕩ');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'ꕦꔤꕯ');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'ꕦꔵ');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'ꕧꕓ ꖴꕎ ꖨꕮꕊ');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'ꕧꕮꔧ');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'ꕧꕮꔧꕪ');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'ꕪꔈꖩꘋ');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'ꕪꔷꖁꕇꕰ ꕯꕮꕊ');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'ꕪꕚꕌ');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'ꕪꕤꔻꕚꘋ');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'ꕪꕯꕜ');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'ꕪꕹꔵꕩ');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'ꕭꔭꕩ');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'ꕭꕌꕯ');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'ꕭꕷꘋ');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'ꕮꔒꔻꕩ');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'ꕮꔖꖁꕇꕰ');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'ꕮꔳꕇꕃ');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'ꕮꔷ');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'ꕮꔷꕜꔍ');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'ꕮꔸꖆ ꕢꘋ');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'ꕮꕊꕚ');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'ꕮꕊꕣ ꔳꘋꗣ');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'ꕮꕜꕭꔻꕪ');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'ꕮꕞꕌꔨ');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'ꕮꗚꔎ');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'ꕯꔤꕀꔸꕩ');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'ꕯꔤꕧ');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'ꕯꕆꔫꕩ');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'ꕱꕮꘋ');
INSERT INTO "country" ("id", "name") VALUES ('US', 'ꕶꕱ');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'ꕶꕱ ꕢꕹꕎ');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'ꕶꕱ ꗩꗡ ꗏ ꖷꖬ ꔳꘋꗣ');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'ꕶꕿꕃꔤ ꕸꖃꔀ');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'ꕶꗷꘋ');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'ꕷꔷꔲꕩ');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'ꕷꔻꕇꕰ ꗪ ꗥꕤꖑꔲꕯ');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'ꕷꕃꕯ ꕘꖇ');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'ꕷꖬꕎꕯ');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'ꕹꕤꔭꕃ');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'ꕿꔞꖃ');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'ꕿꖑ');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'ꖁꕆꕇꕪ');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'ꖁꕆꕇꕪꘋ ꕸꕱꔀ');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'ꖄꕆꕇꕰ');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'ꖆꖩ');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'ꖇꕮꔷꕩ');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'ꖏꔓꔻꕩ');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'ꖏꔳ ꕾꕎ');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'ꖏꔸꕩ ꗛꔤ ꔒꘋꗣ ꗏ');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'ꖏꔸꕩ ꗛꔤ ꕪꘋꗒ');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'ꖏꔻꕚ ꔸꕪ');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'ꖏꕃ ꔳꘋꗣ');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'ꖏꕹꖄꔻ');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'ꖏꖐ');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'ꖏꖐ ꗵꗞꖴꕟꔎ ꕸꖃꔀ');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'ꖒꔷꖁꕙ');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'ꖕꕯꔤꗳ');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'ꖜꕚꘋ');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'ꖜꕟꔘꔀ');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'ꖜꖩꔺ');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'ꖜꖩꘉꔧ');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'ꖢꕟꘋꔻ');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'ꖤꔸꔕꕜ ꗪ ꕿꔆꖑ');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'ꖤꕇꔻꕩ');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'ꖦꕰꕊ ꗳ ꕅꔤꕇ');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'ꖬꔃꕤ ꖨꕮꕊ');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'ꖬꔨꗵꘋ');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'ꖬꔸ ꕞꘋꕪ');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'ꖬꔸꕯꔈ');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'ꖬꕎꔽ ꖨꕮꕊ');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'ꖬꕞꔤꕮꕊꕯ ꔳꘋꗣ');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'ꖬꗵꘋ');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'ꖳꔓꗝꔀ');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'ꖳꕭꕡ');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'ꖳꕯꔤꗳ ꕉꕟꔬ ꗡꕆꔓꔻ');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'ꖳꖴꔓꘋ');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'ꖳꗩꕃꔻꕚꘋ');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'ꖴꔃꔳ');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'ꖶꕎꔎꕮꕞ');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'ꖶꕎꔐꖨꔅ');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'ꖶꕎꕆ');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'ꖶꕟꕯꕜ');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'ꖶꕩꕯ');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'ꖸꔃꔤ');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'ꖺꔻꖤꕎ');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'ꖺꖬꖤꔃꔷꕩ');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'ꖽꖫꕟ');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'ꖽꘋꕭꔓ');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'ꗂꔠꔸꕩ');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'ꗋꕬ');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'ꗋꖺꕃ');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'ꗋꖺꕃꔻ ꗪ ꕪꔤꖏꔻ ꔳꘋꗣ');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'ꗋꖺꕃꕮꕇꔻꕚꘋ');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'ꗏꔻꘋꗂꖺ');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'ꗐꖺꔻꕩ');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'ꗘꖺꕀꕩ');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'ꗘꖺꗵꘋ');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'ꗛꔤ ꕪꘋꗒ ꕮꔸꕩꕯ ꔳꘋꗣ');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'ꗛꗏꔭꕩ');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'ꗞꔓꔎꕇꕰ');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'ꗞꔓꗔ');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'ꗞꕟꖏ');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'ꗞꕯꖏ');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'ꗞꖐꔷꕩ');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'ꗞꘋꔖꕟꔳ');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'ꗟꖺꔃ');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'ꗟꖺꗉ ꔳꘋꗣ');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'ꗡꔻꕿꕇꕰ');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'ꗡꖴꔃꗍ');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'ꗡꗷ ꕢꔍꗍꖺ');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'ꗥꗷꘋ');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'ꗨꗡꖩ');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'ꗩꕀꗚꘋ');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'ꗩꕇꘋ');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'ꗩꕞꖩꔻ');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'ꗩꖷꕜ');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'ꗱꘋꔻ ꕶꔷꕇꔻꕩ');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'ꗱꘋꔻ ꖶꕎꕯ');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'ꗲꕇꖮꔃꕞ');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'ꗿꕃ ꕸꖃꔀ');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'ꘈꔻꖏ');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'ꘉꕜ ꖨꕮꕊ');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'ꘉꕜ ꖨꕮꕊ ꕉꘋꔳꔷ');
