CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Afrika du Sulu');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Alujeria');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italia');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paragwai');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Ualbania');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Uandora');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Uayalandi');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Uazabajani');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Ubelin');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Ubukini');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Uchadi');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Ucheki');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Uchile');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Uchina');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Udenimaka');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Udominika');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Ufaransa');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Ufaransa yo Gwaya');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Ufaransa yo Potina');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Ufiji');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Ufilipino');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Ufini');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Ufugustani');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Ugaboni');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Ugambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ugana');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Ugine');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Uginebisau');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Ugrenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Ugrinlandi');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Uguyana');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Ugwadelupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Ugwam');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Ugwatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Uhabeshi');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Uhaiti');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Uhindini');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Uhispania');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Uhondurasi');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Uhungaria');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Uisraeli');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Ujamaika');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Ujapani');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Ujibralta');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Ujibuti');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Ujikistani');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Ujojia');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Ukambodia');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Ukanada');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Ukatari');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Ukazakistani');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Ukenya');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Ukodiva');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Ukolombia');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Ukomoro');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Ukongo');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Ukorasia');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Ukorea Kaskazini');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Ukorea Kusini');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Ukuba');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Ukuprosi');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Ulativia');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Ulebanoni');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Ulesoto');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Uliberia');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Ulibya');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Umalawi');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Umantegro');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Umarekani');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Umasedonia');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Umisiri');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Umozambiki');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Undonesia');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Unijeri');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Unijeria');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Unorwe');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Uomani');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Upakistani');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Upanama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Upapua');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Uperuu');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Upitkairni');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Upolandi');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Upwetoriko');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Uriterea');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Uriyunioni');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Uromania');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Urundi');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Urwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Usalavado');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'Usamarino');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Usamoa');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Usamoa ya Marekani');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Usantahelena');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Usantakitzi na Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Usantalusia');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Usantapieri na Mikeloni');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Usantavisenti na Grenadini');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Usao Tome na Principe');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Usaudi');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Usembaji');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Usenegali');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Ushelisheli');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Ushenteni');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Usiera Leoni');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Usingapoo');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Usiria');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Usirilanka');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Uslovakia');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Uslovenia');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Usomalia');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Usudani');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Usurinamu');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Uswazi');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Uswidi');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Uswisi');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Utailandi');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Utanzania');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Utimo Mashariki');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Utogo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Utokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Utonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Utrinidad na Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Utuki');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Utunisia');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Uturukimenistani');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Utuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Utwania');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Uvanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Uvatikani');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Uvenezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Uvietinamu');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Uwalis na Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Uyemeni');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Uyordani');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Uzambia');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Uzimbabwe');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Wiraki');
