CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afghanistan');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albanien');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Algeriet');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Amerikanska Jungfruöarna');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Amerikanska Samoa');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andorra');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anguilla');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Antarktis');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua och Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Argentina');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armenien');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'Ascension');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Australien');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azerbajdzjan');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahamas');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahrain');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladesh');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbados');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Belgien');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belize');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benin');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermuda');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Bhutan');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolivia');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosnien och Hercegovina');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botswana');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Bouvetön');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brasilien');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Brittiska Indiska oceanöarna');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Brittiska Jungfruöarna');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brunei');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulgarien');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burkina Faso');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Caymanöarna');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Centralafrikanska republiken');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'Ceuta och Melilla');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Chile');
INSERT INTO "country" ("id", "name") VALUES ('CP', 'Clippertonön');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Colombia');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Cooköarna');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Costa Rica');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Cypern');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Danmark');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'Diego Garcia');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Djibouti');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominica');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Dominikanska republiken');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ecuador');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Egypten');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Ekvatorialguinea');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'El Salvador');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Elfenbenskusten');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritrea');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Estland');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Etiopien');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'Europeiska unionen');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Falklandsöarna');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fiji');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filippinerna');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finland');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Frankrike');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Franska Guyana');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Franska Polynesien');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Franska Sydterritorierna');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Färöarna');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Förenade Arabemiraten');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabon');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambia');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Georgien');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Ghana');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Gibraltar');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Grekland');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenada');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Grönland');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadeloupe');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatemala');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Guernsey');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Guinea');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Guinea-Bissau');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guyana');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haiti');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Heard- och McDonaldöarna');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduras');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Hongkong (S.A.R. Kina)');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Indien');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indonesien');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Irak');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Iran');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Irland');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Island');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Isle of Man');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Israel');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Italien');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamaica');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japan');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Jemen');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Jersey');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jordanien');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Julön');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kambodja');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamerun');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'Kanarieöarna');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Kap Verde');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazakstan');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenya');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Kina');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirgizistan');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Kokosöarna');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komorerna');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongo-Brazzaville');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Kongo-Kinshasa');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Kroatien');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kuba');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kuwait');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laos');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesotho');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Lettland');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Libanon');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberia');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libyen');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Liechtenstein');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Litauen');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luxemburg');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Macao (S.A.R. Kina)');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagaskar');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Makedonien');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malawi');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malaysia');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldiverna');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Marocko');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Marshallöarna');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martinique');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mauretanien');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Mauritius');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayotte');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mexiko');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikronesien');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Moçambique');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldavien');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monaco');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongoliet');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Montserrat');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Myanmar');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibia');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Nederländerna');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Nederländska Antillerna');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepal');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nicaragua');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Niger');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nigeria');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Nordkorea');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Nordmarianerna');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Norfolkön');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Norge');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Nya Kaledonien');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Nya Zeeland');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Oman');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakistan');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palestinska territoriet');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papua Nya Guinea');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguay');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Peru');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitcairn');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Polen');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portugal');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Puerto Rico');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Qatar');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Réunion');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Rumänien');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Rwanda');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Ryssland');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'S:t Barthélemy');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'S:t Helena');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'S:t Kitts och Nevis');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'S:t Lucia');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'S:t Martin');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'S:t Pierre och Miquelon');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'S:t Vincent och Grenadinerna');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Salomonöarna');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samoa');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'San Marino');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'São Tomé och Príncipe');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Saudiarabien');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Schweiz');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegal');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Serbien');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Serbien och Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Seychellerna');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Sierra Leone');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapore');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slovakien');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Slovenien');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somalia');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Spanien');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Storbritannien');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudan');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Surinam');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Svalbard och Jan Mayen');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Sverige');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Swaziland');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Sydafrika');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'Sydgeorgien och Sydsandwichöarna');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Sydkorea');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Syrien');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tadzjikistan');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taiwan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzania');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Tchad');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Thailand');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Tjeckien');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad och Tobago');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'Tristan da Cunha');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunisien');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Turkiet');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turkmenistan');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Turks- och Caicosöarna');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Tyskland');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uganda');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukraina');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Ungern');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruguay');
INSERT INTO "country" ("id", "name") VALUES ('US', 'USA');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'USA:s yttre öar');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Uzbekistan');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikanstaten');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezuela');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vietnam');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Vitryssland');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Västsahara');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis- och Futunaöarna');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'Yttre öar i Oceanien');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambia');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabwe');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Åland');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Österrike');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Östtimor');
