CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'ऍन्डोरा');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'संयुक्त अरब अमीरात');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'अफ़ग़ानिस्तान');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'एन्टिगुआ एवं बारबूडा');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'एंगीला');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'अल्बानिया');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'आर्मेनिया');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'नीदरलैंड्स एंटिलीज़');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'अंगोला');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'अंटार्कटिका');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'अर्जेण्टिना');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'अमरिकी समोआ');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'ऑस्ट्रिया');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'ऑस्ट्रेलिया');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'अरूबा');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'आलाँड द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'अज़रबैजान');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'बोसनिया हर्ज़ेगोविना');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'बारबाडोस');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'बंगलादेश');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'बेल्जियम');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'बुर्किना फासो');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'बल्गैरिया');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'बहरैन');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'बुरुंडी');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'बेनेँ');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'सेँ बार्थेलेमी');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'बरमूडा');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'ब्रूनइ');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'बोलीविया');
INSERT INTO `country` (`id`, `name`) VALUES ('BQ', 'ब्रीटीश अंटार्टीका क्षेत्र');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'ब्राज़ील');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'बहामा');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'भूटान');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'बुवे द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'बोत्स्वाना');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'बेलारूस');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'बेलिज़');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'कैनाडा');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'कोकोस द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'कॉंगो  किनशासा');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'सेंट्रल अफ्रीकन रिपब्लिक');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'कॉंगो ब्राज़्ज़ावील');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'स्वित्ज़रलैंड');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'आईवरी कोस्ट');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'कुक द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'चिली');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'कोमेरान');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'चीन');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'कोलम्बिया');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'कोस्टारीका');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'सर्बिया एवं मॉण्टेनेग्रो');
INSERT INTO `country` (`id`, `name`) VALUES ('CT', 'कैन्टन एवं ऐन्डरबरी द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'क्यूबा');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'कैप वेर्दे');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'क्रिस्मस द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'साइप्रस');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'चेक गणराज्य');
INSERT INTO `country` (`id`, `name`) VALUES ('DD', 'ईस्ट जर्मनी');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'जर्मनी');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'द्जिबूती');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'डेनमार्क');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'डोमिनिका');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'डोमिनिकन गणराज्य');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'अल्जीरिया');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'एक्वाडोर');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'एस्टोनिया');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'मिस्र');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'पश्चिमी सहारा');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'एरिट्रिया');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'स्पेन');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'इथिओपिया');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'फिनलैंड');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'फिजी');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'फ़ॉल्कलैंड द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'माइक्रोनेशिया');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'फरो द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('FQ', 'फ्रांसीससी दक्षिणी एवं अँटार्टीकी क्षेत्र');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'फ्राँस');
INSERT INTO `country` (`id`, `name`) VALUES ('FX', 'मैट्रोपोलिटन फ्राँस');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'गैबॉन');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'ब्रितन');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'ग्रेनडा');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'जॉर्जिया');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'फ्राँसीसी गिआना');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'गेर्नसे');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'घाना');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'जिब्राल्टर');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'ग्रीनलैण्ड');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'गाम्बिया');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'गिनी');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'ग्वादलुप');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'इक्वेटोरियल गिनी');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'ग्रीस');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'दक्षिण जोर्जिया एवं दक्षिण सैंडवीच द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'गोतेदाला');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'गुआम');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'गीनी-बिसाउ');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'गुयाना');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'हाँगकाँग विशेष प्रशासनिक क्षेत्र चीन');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'हर्ड द्वीप एवं मैकडोनॉल्ड द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'हौण्डूरास');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'क्रोएशिया');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'हाइती');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'हंगरी');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'इंडोनेशिया');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'आयरलैंड');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'इस्राइल');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'आईल ऑफ़ मैन');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'भारत');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'ब्रिटिश हिंद महासागरिय क्षेत्र');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'ईराक़');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'ईरान');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'आइसलैंड');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'इटली');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'जर्सी');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'जमाइका');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'जॉर्डन');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'जापान');
INSERT INTO `country` (`id`, `name`) VALUES ('JT', 'जौन्स्टन द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'केन्या');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'किर्गिज़');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'कम्बोडिया');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'किरिबाती');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'कोमोरोज़');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'सेंट किट्स एवं नेविस');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'उत्तर कोरिया');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'दक्षिण कोरिया');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'कुवैत');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'केमैन द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'कज़ाखस्तान');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'लाओस');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'लेबनोन');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'सेंट लूसिया');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'लिक्टैनस्टाईन');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'श्री लँका');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'लाइबेरिया');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'लसोथो');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'लिथुआनिया');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'लक्समबर्ग');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'लाट्वीया');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'लीबिया');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'मोरोक्को');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'मोनाको');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'मोल्डेविया');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'मोंटेनेग्रो');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'सेँ मार्टेँ');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'मदागास्कर');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'मार्शल द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('MI', 'मीडवे द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'मैसेडोनिया');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'माली');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'म्यानमार');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'मंगोलिया');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'मकाओ विशेष प्रशासनिक क्षेत्र (चीन)');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'उत्तरी मारियाना द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'मार्टीनिक');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'मॉरिटेनिया');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'मॉंसेरा');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'माल्टा');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'मॉरिस');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'मालदीव');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'मलावी');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'मैक्सिको');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'मलेशिया');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'मोज़ाम्बिक');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'नामीबिया');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'न्यू कैलेडोनिया');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'नाइजेर');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'नॉरफ़ॉक द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'नाइजीरिया');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'निकारागुआ');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'नेदरलैण्ड');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'नॉर्वे');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'नेपाल');
INSERT INTO `country` (`id`, `name`) VALUES ('NQ', 'द्रॉनींग मौड़ द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'नाउरू');
INSERT INTO `country` (`id`, `name`) VALUES ('NT', 'न्युट्रल क्षेत्र');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'नीयूए');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'न्यूज़ीलैंड');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'ओमान');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'पनामा');
INSERT INTO `country` (`id`, `name`) VALUES ('PC', 'पैसीफीक द्वीप ट्रस्ट क्षेत्र');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'पेरू');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'फ्राँसीसी पॉलिनीशिया');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'पापुआ न्यू गिनी');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'फिलीपिन्स');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'पाकिस्तान');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'पोलैण्ड');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'सेँ पीएर एवं मि‍केलॉं');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'पिटकेर्न');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'पुएर्टो रीको');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'फ़िलिस्तीन');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'पुर्तगाल');
INSERT INTO `country` (`id`, `name`) VALUES ('PU', 'यु एस के विवीध पैसीफीक द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'पलाऊ');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'पारागुए');
INSERT INTO `country` (`id`, `name`) VALUES ('PZ', 'पनामा कनाल ज़ोन');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'क़तार');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'बाहरिय ओशेआनिया');
INSERT INTO `country` (`id`, `name`) VALUES ('QU', 'यूरोपीय संघ');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'रेयूनियॉं');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'रोमानिया');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'सर्बिया');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'रूस');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'रूआण्डा');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'सऊदी अरब');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'सॉलोमन द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'सेशेल्स');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'सूदान');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'स्वीडन');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'सिंगापुर');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'सेण्‍ट हेलेना');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'स्लोवेनिया');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'स्वाल्बार्ड एवं यान मायेन');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'स्लोवाकिया');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'सियेरा लेओन');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'सैन मरीनो');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'सेनेगाल');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'सोमालिया');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'सुरिनाम');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'साउँ-तोमे एवं प्रिंसिप');
INSERT INTO `country` (`id`, `name`) VALUES ('SU', 'यु.एस.एस.आर');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'ऍल साल्वाडोर');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'सीरिया');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'स्वाज़ीलैंड');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'तुर्की एवं कैकोज़ द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'चाड');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'फ्राँसीसी उत्तरी क्षेत्रों');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'टोगो');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'थाइलैण्ड');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'ताजिकिस्तान');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'टोकेलौ');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'पूर्वी तिमोर');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'तुर्कमेनीस्तान');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'त्युनिशिया');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'टॉंगा');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'तुर्की');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'ट्रिनिडाड एवं टोबैगो');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'तुवालु');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'ताइवान');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'तंज़ानिया');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'यूक्रेन');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'युगाँडा');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'युनाइटेड स्टेट्स के छोटे बाहरिय द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'संयुक्त राज्य अमरिका');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'युरूगुए');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'उज़बेकिस्तान');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'वैटिकन');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'सेंट विंसंट एवं दी ग्रनाडीन्स्');
INSERT INTO `country` (`id`, `name`) VALUES ('VD', 'ऊत्तर वियतनाम');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'वेनेज़ुएला');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'ब्रिटिश वर्जीन आईलंड्स');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'यु.एस. वर्जीन आईलंड्स');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'वियतनाम');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'वानाऊटु');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'वॉलेस एवं फ़्यूचूना');
INSERT INTO `country` (`id`, `name`) VALUES ('WK', 'वेक द्वीप');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'समोआ');
INSERT INTO `country` (`id`, `name`) VALUES ('YD', 'यमनी गनराज्य');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'यमन');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'मैयौट');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'दक्षिण अफ्रीका');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'ज़ाम्बिया');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'ज़ीम्बाब्वे');
INSERT INTO `country` (`id`, `name`) VALUES ('ZZ', 'अज्ञात या अवैध प्रदेश');
