CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Affganistan');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albania');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Algeria');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andorra');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguilla');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Antarctica');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigwa a Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armenia');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Awstralia');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Awstria');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azerbaijan');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahrain');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladesh');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbados');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Belarws');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belize');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benin');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermwda');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Bhwtan');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolifia');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnia a Herzegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswana');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brasil');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunei');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bwlgaria');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Caledonia Newydd');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Cambodia');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Canada');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Cape Verde');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Cenia');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Chad');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Chile');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Cirgistan');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Ciwba');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Colombia');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Comoros');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Congo');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Costa Rica');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Coweit');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Croatia');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Cyprus');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Côte d’Ivoire');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'De Affrica');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'De Corea');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Denmarc');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Djibouti');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominica');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ecwador');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'El Salfador');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Emiraethau Arabaidd Unedig');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritrea');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estonia');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Ethiopia');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Ffrainc');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Fietnam');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fiji');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabon');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambia');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Georgia');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ghana');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Giana Ffrengig');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Gibraltar');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Gini');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Gini Gyhydeddol');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Gogledd Corea');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Gorllewin Sahara');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grenada');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Guadeloupe');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guam');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Guatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyana');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Gweriniaeth Canol Affrica');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Gweriniaeth Ddemocrataidd y Congo');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Gweriniaeth Tsiec');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Gwlad Belg');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Gwlad Groeg');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Gwlad Pwyl');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Gwlad Thai');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Gwlad yr Iâ');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haiti');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Hondwras');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Hong Kong S.A.R., Tseina');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Hwngari');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'India');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonesia');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Irac');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Iran');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Israel');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Iwerddon');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jamaica');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazakhstan');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laos');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Latfia');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesotho');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Libanus');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberia');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libia');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Liechtenstein');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lithwania');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Lwcsembwrg');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Macao S.A.R., Tseina');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Macedonia');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagascar');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawi');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malaysia');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maldives');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martinique');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Mawrisiws');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mawritania');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayotte');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mecsico');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Micronesia');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldofa');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monaco');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongolia');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montserrat');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Moroco');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambique');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myanmar');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Mân Ynysoedd Pellenig yr Unol Daleithiau');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibia');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nawrw');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepal');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nicaragwa');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Niger');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nigeria');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niue');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norwy');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Oman');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pacistan');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papua Gini Newydd');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguay');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Perw');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Philipinau');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitcairn');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Polynesia Ffrainc');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portiwgal');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Prydain Fawr');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Puerto Rico');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Qatar');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Rwanda');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Rwmania');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rwsia');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Réunion');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Saint Helena');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Saint Kitts a Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Saint Lucia');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Saint Pierre a Miquelon');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Saint Vincent a’r Grenadines');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Sambia');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samoa Americanaidd');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marino');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Sao Tome a Principe');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Sawdi-Arabia');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Sbaen');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Seland Newydd');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegal');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seychelles');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Siapan');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sierra Leone');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Simbabwe');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapore');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slofacia');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slofenia');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somalia');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Svalbard a Jan Mayen');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Swaziland');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Sweden');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Swrinam');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Syria');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwan');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tajicistan');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tansanïa');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timor-Leste');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Tiriogaeth Cefnfor India Prydain');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Tiriogaeth Palesteina');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Tiriogaethau Ffrengig y De');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tiwnisia');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidad a Thobago');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Tseina');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Twfalw');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Twrci');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Tyrcmenistan');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruguay');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuela');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wallis a Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Wcráin');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Wsbecistan');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Y Bahamas');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Y Camerŵn');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Y Fatican');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Y Ffindir');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Y Swdan');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Y Swistir');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Y Weriniaeth Ddominicaidd');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yemen');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Ynys Bouvet');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'Ynys Heard ac Ynysoedd McDonald');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Ynys Manaw');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Ynys Norfolk');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Ynys y Nadolig');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Ynysoedd Aland');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Ynysoedd Americanaidd y Wyryf');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Ynysoedd Caribî yr Iseldiroedd');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Ynysoedd Cayman');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Ynysoedd Cocos (Keeling)');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Ynysoedd Cook');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Ynysoedd De Georgia a De Sandwich');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Ynysoedd Ffaröe');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Ynysoedd Gogledd Mariana');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Ynysoedd Marshall');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Ynysoedd Prydeinig y Wyryf');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Ynysoedd Solomon');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Ynysoedd Turks a Caicos');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Ynysoedd y Falkland');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Yr Aifft');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Yr Almaen');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Yr Ariannin');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Yr Eidal');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Yr Iorddonen');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Yr Iseldiroedd');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Yr Unol Daleithiau');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Yr Ynys Las');
