CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albanïi');
INSERT INTO "country" ("id", "name") VALUES ('US', 'ÂLeaa-Ôko tî Amerika');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Alzerïi');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andôro');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angoläa');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Angûîla');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antîgua na Barbûda');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Antîyi tî Holânde');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Arâbo Emirâti Ôko');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armenïi');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Arûba');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Arzantîna');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Âzôâ Viîrîggo tî Anglëe');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'âzûâ Kûku');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Âzûâ Märïâni tî Banga');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Âzûâ Märshâl');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Âzûâ Ngundë, Kaimäni');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Azûâ tî Kâpo-Vêre');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Âzûâ tî Mälüîni');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Âzûâ Turku na Kaîki');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Âzûâ Virîgo tî Amerîka');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahâmasa');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahrâina');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barabâda');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Belarüsi');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Bêleze, Belezîki');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belîzi');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benëen');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bengladêshi');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Beremûda');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolivïi');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosnïi na Herzegovînni');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botswana');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brezîli');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brunêi');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulugarïi');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burkina Faso');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundïi');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Butäan');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Danemêrke');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Dibutùii');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dömïnîka');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekuatëre');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Ênnde');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Ênndonezïi');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritrëe');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Espânye');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Estonïi');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Etiopïi');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Faganïta, Afganïstäan');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Farânzi');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Fëlânde');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fidyïi');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filipîni');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Finî Kaledonïi');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Finî Zelânde');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gaböon');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambïi');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Ganäa');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Gayâna');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Gerêsi');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Ginëe');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Ginëe tî Ekuatëre');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Gninëe-Bisau');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Gorolânde');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenâda');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadelûpu');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guâm');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatêmälä');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Güyâni tî farânzi');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haitïi');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Holände');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduräsi');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Hongirùii');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Iräan');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Irâki');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Irlânde');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Islânde');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Israëli');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Italùii');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kämbôzi');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamerûne');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Kâmitâ');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanadäa');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Katära');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazakisitäan');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenyäa');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirigizitùaan');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Kôdivüära');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Ködörögbïä--Ôko');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Ködörösêse tî Bêafrîka');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Ködörösêse tî Dominîka');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Ködörösêse tî Ngunuhalëzo tî kongö');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Ködörösêse tî Tyêki');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolombïi');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Kömôro');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongö');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Korëe tî Banga');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Korëe tî Mbongo');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kôsta Rîka');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Köwêti');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Kroasïi');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kubäa');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesôtho');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Letëe tî Vatikäan');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Letonùii');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberïa');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libïi');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Libùaan');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Liechtenstein,');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Lituanïi');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Lùaôsi');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Lugzambûru');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagaskära');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malawïi');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldîva');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malezïi');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Malïi');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Mâlta');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Marôko');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Märtïnîki');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Maseduäni');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mäyôte');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Mbongo-Afrîka');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mekisîki');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikronezïi');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldavùii');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monaköo');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongolïi');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Monserâte');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Mörîsi');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Moritanïi');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mözämbîka');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Myämâra');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibùii');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nëpâli');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikaragua');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Nizëre');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nizerïa');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Nörvêzi');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Omâni');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Ostralïi, Sotralïi');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Otrîsi');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakistäan');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papû Finî Ginëe, Papuazïi');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguëe');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Perüu');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitikêrni');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Polinezïi tî farânzi');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Pölôni');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Porto Rîko');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Pörtugäle, Ködörö Pûra');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Reinïon');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ruandäa');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Rumanïi');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Rusïi');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Salvadöro');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Samöa tî Amerîka');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samoäa');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sâô Tömê na Prinsîpe');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Saûdi Arabïi');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Sên-Krïstôfo-na-Nevîsi');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'Sên-Marëen');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Sên-Pyêre na Mikelöon');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Sên-Vensäan na âGrenadîni');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegäle');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Sênt-Helêna');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Sênt-Lisïi');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Serbïi na Möntënegröo');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Sêse tî Anglëe na Ngûyämä tî Ênnde');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Sêse tî Palestîni');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Sëyshêle');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Shilïi');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Shîna');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Sierä-Leône');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Sïngäpûru');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Sîpri');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sirî-Lanka');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Sirïi');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Solovakïi');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Solovenïi');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somalïi');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudäan');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Suêde');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Sûîsi');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Surinäm');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Swäzïlânde');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Taazikiistäan');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Tailânde');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Tâiwâni');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzanïi');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Timôro tî Tö');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togö');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinitùee na Tobagö');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunizïi');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turkumenistäan');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Turukïi');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tüvalü');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Tyâde');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Ugandäa');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukrêni');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruguëe');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Uzbekistäan');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatü');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezueläa');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vietnäm');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Walîsi na Futuna');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Yëmêni');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Zamaîka');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Zâmani');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambïi');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Zapöon');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Zerebaidyäan, Azerbaidyäan,');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Zibraltära, Zibaratära');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbäbwe');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Zordanïi');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Zorzïi');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Zûâ Nôrfôlko');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Zûâ Salomöon');
