CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY("id"));

INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andora');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Emiradus Arabi Unidu');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afeganistãu');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua i Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Angila');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albania');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armenia');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Antilhas Olandeza');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Arjentina');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Samoa Merkanu');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Austria');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Australia');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azerbaijãu');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosnia-Erzegovina');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbadus');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladexi');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Béljika');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burkina Fasu');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulgaria');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Barain');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benin');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermudas');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brunei');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolivia');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brazil');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Baamas');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Butãu');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botsuana');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Belarus');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belizi');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanadá');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Republika Dimokratika di Kongu');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Republika Sentru-Afrikanu');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongu');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Suisa');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Kosta di Marfin');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Ilhas Kuk');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Xili');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamarõis');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Xina');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kulombia');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kosta Rika');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Servia i Montinegru');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kuba');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Kabu Verdi');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Xipri');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Republika Txeka');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Alimanha');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Djibuti');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Dinamarka');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominika');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Repúblika Dominikana');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Arjelia');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekuador');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Stonia');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Ejitu');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Iritreia');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Spanha');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Itiopia');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finlandia');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fidji');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Ilhas Malvinas');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikronezia');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Fransa');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabãu');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Reinu Unidu');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Granada');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Jiorjia');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Giana Franseza');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Gana');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Jibraltar');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Gronelandia');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambia');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Gine');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadalupi');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Gine Ekuatorial');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Gresia');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatimala');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Gine-Bisau');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Giana');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Onduras');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Kroasia');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Aiti');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Ungria');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indonezia');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Irlanda');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Israel');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'India');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Ilhas Britanika di Indiku');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Iraki');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Iron');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Islandia');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Italia');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamaika');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jordania');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japãu');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenia');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirgiston');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kambodja');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Kamoris');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Sãu Kristovãu i Nevis');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Koreia di Norti');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Koreia di Sul');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kueiti');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Ilhas Kaimãu');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazakistãu');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laus');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Libanu');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Santa Lúsia');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Lixenstain');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberia');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lezotu');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Lituania');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luxemburgu');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Letonia');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libia');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Marokus');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monaku');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldavia');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagaskar');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Ilhas Marxal');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Masidonia');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Mianmar');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongolia');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Ilhas Marianas di Norti');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martinika');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mauritania');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Monserat');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Ilhas Maurisia');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldivas');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malaui');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mexiku');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malazia');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Musambiki');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibia');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Nova Kalidonia');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Nijer');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Ilhas Norfolk');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nijeria');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikaragua');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Olanda');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Noruega');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepal');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Nova Zilandia');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Oman');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Peru');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Polinezia Franseza');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papua-Nova Gine');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filipinas');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakistãu');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Pulonia');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'San Piere i Mikelon');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pirkairn');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Portu Riku');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palistina');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Purtugal');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguai');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Katar');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Runion');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Romenia');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Rúsia');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ruanda');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Arabia Saudita');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Ilhas Salumon');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Seixelis');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudãu');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Suesia');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapura');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Santa Ilena');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Slovenia');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slovakia');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Sera Lioa');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'San Marinu');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegal');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Sumalia');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Surinami');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sãu Tume i Prinsipi');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'El Salvador');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Siria');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Suazilándia');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Ilhas Turkas i Kaikus');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Txadi');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togu');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Tailandia');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tadjikistãu');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Timor Lesti');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turkumenistãu');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunizia');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Turkia');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad i Tobagu');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taiuan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzania');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukrania');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uganda');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Stadus Unidos di Merka');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruguai');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Uzbekistãu');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikanu');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Sãu Bisenti i Granadinas');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Vinizuea');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Ilhas Virjens Britanikas');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Ilhas Virjens Merkanu');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vietnam');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Ualis i Futuna');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samoa');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Iemen');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Maiote');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Afrika di Sul');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambia');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabui');
