CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('SA', 'A-rập Xê-út');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Ác-hen-ti-na');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Ác-mê-ni-a');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Ai Cập');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Ai-déc-bai-gian');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Ai-len');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Ai-xơ-len');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'An-ba-ni');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'An-giê-ri');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'An-ti-gu-a và Ba-bu-đa');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andorra');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anguilla');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Áo');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Áp-ga-ni-xtan');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Ăng-gô-la');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Ấn Độ');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Ba Lan');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Ba-ha-ma');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Ba-ren');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Bác-ba-đốt');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Bắc Triều Tiên');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Băng Đảo');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Băng-la-đét');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermuda');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Bê-la-rút');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Bê-li-xê');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Bê-nanh');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Bỉ');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Bồ Đào Nha');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bô-li-vi-a');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bô-xni-a Héc-xê-gô-vi-na');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Bốt-xoa-na');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Bờ Biển Ngà');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Bra-xin');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Bru-nây');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Bu-run-đi');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Bu-tan (Bhutan)');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bun-ga-ri');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Buốc-ki-na Pha-xô');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Ca-mơ-run');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Ca-na-đa');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Ca-ta');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'Các đảo nhỏ xa trung tâm thuộc Mỹ');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Các Tiểu Vương quốc A-rập Thống nhất');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Campuchia');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Cáp-ve');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'Ceuta và Melilla');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Chi-lê');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Cô-lôm-bi-a');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Cô-mô');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Cô-oét');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Cộng hoà dân chủ Côngô');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Cộng hoà Đô-mi-ni-ca');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Cộng hòa Séc');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Cộng hòa Trung Phi');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Công-gô');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Cốt-xta Ri-ca');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Crô-a-ti-a');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Cu Ba');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Cư-rơ-gư-xtan');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Dăm-bi-a');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'Diego Garcia');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Dim-ba-bu-ê');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominica');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Đài Loan');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Đan Mạch');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'Đảo Ascension');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Đảo Bouvet (Na Uy)');
INSERT INTO "country" ("id", "name") VALUES ('CP', 'Đảo Clipperton');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Đảo Giáng Sinh');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Đảo Gu-am');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Đảo Heard và Quần đảo McDonald');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Đảo Man');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Đảo Norfolk');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Đảo Somoa thuộc Mỹ');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Đảo Virgin, thuộc Anh');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Đặc khu hành chính Hồng Kông thuộc CHND Trung Hoa');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Đặc khu hành chính Macao thuộc CHND Trung Hoa');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Đông Ti-mo');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Đức');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'E-xtô-ni-a');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'En-san-va-đo');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ê-cu-a-đo');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Ê-ri-tơ-rê-a');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Ê-ti-ô-pi-a');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Ga-bông');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Găm-bi-a');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Gha-na');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Ghi-nê');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Ghi-nê Bít-xao');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Ghi-nê Xích-đạo');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Gi-bu-ti');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Gibraltar');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Gióc-đa-ni');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Goa-tê-ma-la');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grê-na-đa');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Gru-di-a');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadeloupe');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Guernsey');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guy-a-na');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Hà Lan');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Ha-i-ti');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Ha-mai-ca');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Hàn Quốc');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Hoa Kỳ');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Hôn-đu-rát');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Hung-ga-ri');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Hy Lạp');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'I-ran');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'I-rắc');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'I-xra-en');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Jersey');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Ka-dắc-xtan');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kê-ni-a');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Ki-ri-ba-ti');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Lãnh thổ Palestine');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Lào');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Lát-vi-a');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lê-xô-thô');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Li-băng');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Li-bê-ri-a');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Li-bi');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Li-tu-a-ni-a');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Lich-ten-xtên');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'Liên Minh Châu Âu');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Lúc-xăm-bua');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Ma-đa-gát-xca');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Ma-la-uy');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Ma-lay-xi-a');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Ma-li');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Ma-rốc');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Ma-xê-đô-ni-a');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Man-đi-vơ');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Man-ta');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mê-hi-cô');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Mi-an-ma');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mi-crô-nê-xi-a');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Montserrat');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mô-dăm-bích');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Mô-na-cô');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mô-ri-ta-ni');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Mô-ri-xơ');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Môn-đô-va');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mông Cổ');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Na Uy');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Nam Cực');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Nam Dương');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Nam Phi');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Nam-mi-bi-a');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'New Caledonia');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nê-pan');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Nga');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Nhật Bản');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Ni-ca-ra-goa');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Ni-giê');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Ni-giê-ri-a');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Niu Di-lân');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Ô-man');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pa-ki-xtan');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Pa-na-ma');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Pa-pu-a Niu Ghi-nê');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Pa-ra-goay');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Pê-ru');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Pháp');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Phần Lan');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Phi-gi');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Phi-lip-pin');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Polynesia thuộc Pháp');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Puerto Rico');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Quần đảo Aland');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Quần Đảo Bắc Mariana');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'Quần đảo Canary');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Quần Đảo Cayman');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Quần đảo Cocos');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Quần Đảo Cook');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Quần Đảo Falkland');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Quần Đảo Faroe');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Quần đảo Mác-san');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'Quần đảo Nam Georgia và Nam Sandwich');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Quần đảo Pitcairn');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Quần Đảo Turk và Caicos');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Quần đảo Virgin, Mỹ');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Quần đảo Xô-lô-mông');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Quiana thuộc Pháp');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ru-an-đa');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Ru-ma-ni');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Saint Helena');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Saint Pierre và Miquelon');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Sát');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Séc-bia');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Síp');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Svalbard và Jan Mayen');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tan-da-ni-a');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tát-gi-ki-xtan');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Tây Ấn Hà Lan');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Tây Ban Nha');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Tây Sahara');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Thái Lan');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Thổ Nhĩ Kỳ');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Thuộc địa Anh tại Ấn Độ Dương');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Thuộc Địa Nam của Pháp');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Thụy Điển');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Thụy Sĩ');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Tô-gô');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tông-ga');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Tri-ni-đát và Tô-ba-gô');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'Tristan da Cunha');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Trung Quốc');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tu-va-lu');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Tuốc-mê-ni-xtan');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tuy-ni-di');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'U-crai-na');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'U-dơ-bê-ki-xtan');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'U-gan-đa');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'U-ru-goay');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Úc');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Va-nu-a-tu');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Va-ti-căng');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Vê-nê-zu-ê-la');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Việt Nam');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'Vùng xa xôi thuộc Châu Đại Dương');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Vương quốc Anh');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis và Futuna');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Xa-moa');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Xan Lu-xi');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'Xan Ma-ri-nô');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Xan Vin-xen và Grê-na-din');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Xan-kít và Nê-vi');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Xao Tô-mê và Prin-xi-pê');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Xây-sen');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Xéc-bi');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Xê-nê-gan');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Xi-ê-ra Lê-ôn');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Xi-ri');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Xin-ga-po');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Xlô-va-ki-a');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Xlô-ven-ni-a');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Xoa-di-len');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Xô-ma-li');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Xri Lan-ca');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Xu-đăng');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Xu-ri-nam');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Ý');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Y-ê-men');
