CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afghanistan');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Alamagn');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albania');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Aljeria');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andorra');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguilla');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Antarktika');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigua ha Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Antilhez Nederlandat');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Aod an Olifant');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Aostralia');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Aostria');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Arabia Saoudat');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Arcʼhantina');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armenia');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azerbaidjan');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamas');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahrein');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladesh');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbados');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Belarus');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Belgia');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belize');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benin');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermuda');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Bhoutan');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolivia');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnia ha Herzegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswana');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brazil');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunei');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgaria');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Ceuta ha Melilla');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Chile');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Costa Rica');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Danmark');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Diego Garcia');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Djibouti');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominica');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Douaroù aostral Frañs');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ecuador');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Egipt');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Emirelezhioù Arab Unanet');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Enez Ascension');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Enez Bouvet');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Enez Christmas');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'Enez Clipperton');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Enez Norfolk');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Enez Pitcairn');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Enez Vanav');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritrea');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estonia');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiopia');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fidji');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipinez');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finland');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Frañs');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabon');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambia');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ghana');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Ginea');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Ginea ar Cʼheheder');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Ginea-Bissau');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grenada');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Gres');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Greunland');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guam');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Guatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyana');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Gwadeloup');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Gwernenez');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Gwiana cʼhall');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haiti');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Honduras');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Hong Kong RMD Sina');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Hungaria');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'India');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonezia');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Inizi Åland');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Inizi Cayman');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Inizi Cook');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Inizi diabell ar Stadoù-Unanet');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Inizi Faero');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Inizi Falkland');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Inizi Georgia ar Su hag Inizi Sandwich ar Su');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Inizi Gwercʼh ar Stadoù-Unanet');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Inizi Gwercʼh Breizh-Veur');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'Inizi Heard ha McDonald');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Inizi Kanariez');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Inizi Kokoz');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Inizi Mariana an Norzh');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Inizi Marshall');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Inizi Turks ha Caicos');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Iran');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Iraq');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Island');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Israel');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Italia');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Iwerzhon');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Izelvroioù');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jamaika');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Japan');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Jerzenez');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Jibraltar');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Jordania');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Jorjia');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Kab Glas');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Kaledonia Nevez');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kambodja');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kameroun');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanada');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazakstan');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenya');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Kiprenez');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolombia');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Komorez');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongo - Brazzaville');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Kongo - Kinshasa');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Korea an Norzh');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Korea ar Su');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Koweit');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Kroatia');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kuba');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laos');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Latvia');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesotho');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Liban');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberia');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libia');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Liechtenstein');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lituania');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Luksembourg');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Macau RMD Sina');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagaskar');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Makedonia');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawi');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malaysia');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maldivez');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Maouritania');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Maroko');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martinik');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayotte');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mecʼhiko');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikronezia');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldova');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monaco');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongolia');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Montenegro');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montserrat');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Moris');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambik');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myanmar [Birmania]');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibia');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nauru');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepal');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nicaragua');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Niger');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nigeria');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niue');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norvegia');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Oman');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'Oseania diabell');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Ouganda');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Ouzbekistan');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistan');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panamá');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papoua Ginea-Nevez');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguay');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Perou');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Polinezia cʼhall');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Polonia');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portugal');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Puerto Rico');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Qatar');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Republik Dominikan');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Republik Kreizafrikan');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Republik Tchek');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Reünion');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Rouantelezh-Unanet');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Roumania');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rusia');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Rwanda');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Sahara ar Cʼhornôg');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Saint Barthélemy');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Saint Helena');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Saint Kitts ha Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Saint Lucia');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Saint Martin');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Salomon');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Salvador');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samoa Amerikan');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marino');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Sant Visant hag ar Grenadinez');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Sant-Pêr-ha-Mikelon');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'São Tomé ha Príncipe');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Sechelez');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegal');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Serbia');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sierra Leone');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Sina');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapour');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Siria');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovakia');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slovenia');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somalia');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Soudan');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Spagn');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Stadoù-Unanet');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Suafrika');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Suis');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinam');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Svalbard');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Sveden');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Swaziland');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tadjikistan');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwan');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzania');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Tchad');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Thailand');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timor-Leste');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Tiriad breizhveurat Meurvor Indez');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Tiriadoù Palestina');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidad ha Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunizia');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Turkia');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turkmenistan');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukraina');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'Unaniezh Europa');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruguay');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatikan');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuela');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Viêt Nam');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wallis ha Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yemen');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambia');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Zeland-Nevez');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabwe');
