CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('MO', 'ARE China de Macáu');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'ARE China de Ḥong Kong');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afganistán');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albania');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Alemania');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andorra');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguila');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigua y Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Arabia Saudita');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armenia');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Arxelia');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Arxentina');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Australia');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Austria');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azerbaixán');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladex');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbados');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Baḥréin');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belize');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benín');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Bielorrusia');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolivia');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnia y Herzegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botsuana');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brasil');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunéi');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgaria');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Fasu');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Bután');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Bélxica');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Cabu Verde');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Camboya');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Camerún');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Canadá');
INSERT INTO [country] ([id], [name]) VALUES ('BQ', 'Caribe neerlandés');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Ceuta y Melilla');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Chad');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Chequia');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Chile');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'China');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Ciudá del Vaticanu');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Colombia');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Congu - Brazzaville');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Congu - Kinxasa');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Corea del Norte');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Corea del Sur');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Costa Rica');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Costa de Marfil');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Croacia');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Cuba');
INSERT INTO [country] ([id], [name]) VALUES ('CW', 'Curaçao');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Diego Garcia');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Dinamarca');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominica');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ecuador');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'El Níxer');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'El Salvador');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Emiratos Árabes Xuníos');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritrea');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Eslovaquia');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Eslovenia');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'España');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Estaos Xuníos');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estonia');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiopía');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Exiptu');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Falkland Islands');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipines');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finlandia');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Francia');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabón');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambia');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ghana');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Granada');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Grecia');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Groenlandia');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Guadalupe');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guam');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Guatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Guernsey');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Guinea Ecuatorial');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Guinea-Bisáu');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyana');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Guyana Francesa');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haití');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Hondures');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Hungría');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'India');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonesia');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Iraq');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Irlanda');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Irán');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Islandia');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Islla Ascensión');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Islla Bouvet');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Islla Christmas');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'Islla Clipperton');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Islla Norfolk');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Islla de Man');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'Islla Ḥeard ya Islles McDonald');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Islles Aland');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Islles Caimán');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Islles Canaries');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Islles Cocos (Keeling)');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Islles Cook');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Islles Feroe');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Islles Fixi');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Islles Marianes del Norte');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Islles Marshall');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Islles Perifériques Menores de los EE.XX.');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Islles Pitcairn');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Islles Salomón');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Islles Turques y Caicos');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Islles Vírxenes Americanes');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Islles Vírxenes Britániques');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Islles Xeorxa del Sur y Sandwich del Sur');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Israel');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Italia');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Jersey');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazakstán');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenia');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kirguistán');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuwait');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'L''Antártida');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'La Martinica');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laos');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Les Bahames');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Les Bermudes');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Les Comores');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Les Maldives');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Les Seixeles');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesothu');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Letonia');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberia');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libia');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Liechtenstein');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lituania');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Luxemburgu');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Líbanu');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Macedonia');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagascar');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malasia');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malaui');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Malí');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Marruecos');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Mauriciu');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mauritania');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayotte');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Micronesia');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldavia');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongolia');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Montenegru');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montserrat');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambique');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myanmar (Birmania)');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Méxicu');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Mónacu');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibia');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nauru');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepal');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nicaragua');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niue');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nixeria');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Noruega');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Nueva Caledonia');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Nueva Zelanda');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Omán');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistan');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Palestina');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Paláu');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panamá');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papúa Nueva Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguay');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Países Baxos');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Perú');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Polinesia Francesa');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Polonia');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portugal');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Puertu Ricu');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Qatar');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Reinu Xuníu');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'República Centroafricana');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'República Dominicana');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Reunión');
INSERT INTO [country] ([id], [name]) VALUES ('ZZ', 'Rexón desconocida');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Ruanda');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Rumanía');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rusia');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Saint Kitts y Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Saint Martin');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Saint Pierre y Miquelon');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samoa Americana');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'San Bartolomé');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marín');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'San Vicente y les Granadines');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Santa Lena');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Santa Llucía');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Santu Tomé y Príncipe');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegal');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Serbia');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sierra Lleona');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapur');
INSERT INTO [country] ([id], [name]) VALUES ('SX', 'Sint Maarten');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Siria');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somalia');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Suazilandia');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Sudáfrica');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudán');
INSERT INTO [country] ([id], [name]) VALUES ('SS', 'Sudán del Sur');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Suecia');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Suiza');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinam');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Svalbard ya Islla Jan Mayen');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Sáḥara Occidental');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Tailandia');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwán');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzania');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Taxiquistán');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Territoriu Británicu del Océanu Índicu');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Tierres Australes Franceses');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timor Oriental');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togu');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokeláu');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidá y Tobagu');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Tristán da Cunha');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunicia');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turkmenistán');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Turquía');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ucraína');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruguay');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Uzbequistán');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuela');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietnam');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wallis y Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Xamaica');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Xapón');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Xeorxa');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Xibraltar');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Xibuti');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Xipre');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Xordania');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yemen');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambia');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabue');
