CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andora');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Falme cia Kiarabu');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afuganistani');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigua na Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguilla');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Alubania');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armenia');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Antili cia Holandi');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Ajentina');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samoa ya Amerika');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Austiria');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Austrĩlia');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azebaijani');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnia na Hezegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Babadosi');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangiradeshi');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Beronjiamu');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Bukinafaso');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgaria');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Baharini');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benini');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bamuda');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunei');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolivia');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brazilu');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamasi');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Butani');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswana');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Belarusi');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belize');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanada');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Nthĩ ya Kidemokrasĩ ya Kongo');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Nthĩ ya Afrika gatĩgatĩ');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongo');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Swizilandi');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Kodivaa');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Aĩrandi cia Cook');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Chile');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kameruni');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'China');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolombia');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kostarika');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Sabia na Montenegoro');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kiuba');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Kepuvede');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Caipurasi');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Nthĩ ya Cheki');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Njamanĩ');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Jibuti');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Denimaki');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominika');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Nthĩ ya Dominika');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Angiria');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ekwado');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estonia');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Misiri');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritrea');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Spĩni');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Ithiopia');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finilandi');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fiji');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Aĩrandi cia Falklandi');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikronesia');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Fransi');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gaboni');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Ngeretha');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grenada');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Jojia');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Gwiyana ya Fransi');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ghana');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Ngĩbrata');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Ngirinilandi');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambia');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Gine');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Gwadelupe');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Gine ya Iquita');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Ngiriki');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Gwatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Gwam');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Ginebisau');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyana');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Hondurasi');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Koroashia');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haiti');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Hangarĩ');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonesia');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Aelandi');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Isiraeli');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'India');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Nthĩ cia Ngeretha gatagatĩ ka ĩria ria Hindi');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Iraki');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Irani');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Aisilandi');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Italĩ');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jamaika');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Jorondani');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Japani');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenya');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kirigizistani');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kambodia');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Komoro');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Santakitzi na Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Korea Nothi');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Korea Saũthi');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuwĩ ti');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Aĩrandi cia Kayman');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazakistani');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laosi');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Lebanoni');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Santalusia');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Lishenteni');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sirilanka');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberia');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesotho');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lithuania');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Luxembogu');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Lativia');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Lĩbia');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Moroko');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monako');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldova');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagasika');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Aĩrandi cia Marshal');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Macedonia');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myanima');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongolia');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Aĩrandi cia Mariana ya nothi');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martiniki');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mauritania');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montserrati');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Maurĩtiasi');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Modivu');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawi');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mexiko');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malĩsia');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambiki');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibia');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Kalendoia Ĩnjeru');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Nija');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Aĩrandi cia Norfok');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nijeria');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikaragwa');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Holandi');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norwi');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepali');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nauru');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niue');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Niuzilandi');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Omani');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peru');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Polinesia ya Fransi');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papua');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipino');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistani');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Polandi');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Santapieri na Mikeloni');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitkairni');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Pwetoriko');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Rũtere rwa Westi banki na Gaza cia Palestina');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Potogo');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paragwai');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Kata');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Riyunioni');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Romania');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rashia');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Rwanda');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Saudi');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Airandi Cia  Solomon');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Shelisheli');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudani');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Swideni');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapoo');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Santahelena');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slovenia');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovakia');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Siera Leoni');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'Samarino');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senego');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somalia');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinamu');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Sao Tome na Principe');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Elsavado');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Siria');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Swazilandi');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Aĩrandi cia Takĩ na Kaiko');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Chadi');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Thaĩlandi');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tajikistani');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timori ya Isti');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Tukumenistani');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunisia');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Takĩ');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidad na Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwani');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzania');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukirĩni');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Amerika');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Urugwĩ');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Uzibekistani');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatikani');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Santavisenti na Grenadini');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuela');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Aĩrandi cia Virgin cia Ngeretha');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Aĩrandi cia  Virgin cia Amerika');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietinamu');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Walis na Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yemeni');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayotte');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Afrika ya Southi');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambia');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabwe');
