CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AU', 'ავსტრალია');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'ავსტრია');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'ავღანეთი');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'აზერბაიჯანი');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'ალანდის კუნძულები');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'ალბანეთი');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'ალჟირი');
INSERT INTO "country" ("id", "name") VALUES ('US', 'ამერიკის შეერთებული შტატები');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'ამერიკული სამოა');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'ანგვილა');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'ანგოლა');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'ანდორა');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'ანტარქტიკა');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'ანტიგუა და ბარბუდა');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'არაბეთის გაერთიანებული ემირატები');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'არგენტინა');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'არუბა');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'აღმოსავლეთი ტიმორი');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'ახალი ზელანდია');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'ახალი კალედონია');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'ბანგლადეში');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'ბარბადოსი');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'ბაჰამის კუნძულები');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'ბაჰრეინი');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'ბელგია');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'ბელიზი');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'ბელორუსია');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'ბენინი');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'ბერმუდა');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'ბოლივია');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'ბოსნია და ჰერცეგოვინა');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'ბოტსვანა');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'ბრაზილია');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'ბრიტანული ტერიტორია ინდოეთის ოკეანეში');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'ბრუნეი');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'ბუვეს კუნძული');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'ბულგარეთი');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'ბურკინა-ფასო');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'ბურუნდი');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'ბუტანი');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'გაბონი');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'გაიანა');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'გამბია');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'განა');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'გერმანია');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'გვადელუპე');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'გვატემალა');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'გვინეა');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'გვინეა-ბისაუ');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'გიბრალტარი');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'გრენადა');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'გრენლანდია');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'გუამი');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'დანია');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'დასავლეთი საჰარა');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'დაშორებული ოკეანია');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'დიდი ბრიტანეთი');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'დომინიკა');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'დომინიკანის რესპუბლიკა');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'ეგვიპტე');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'ევროკავშირი');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'ეთიოპია');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'ეკვადორი');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'ეკვატორული გვინეა');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'ერაყი');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'ერიტრეა');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'ესპანეთი');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'ესტონეთი');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'ვალისი და ფუტუნა');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'ვანუატუ');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'ვატიკანი');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'ვენესუელა');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'ვიეტნამი');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'ზამბია');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'ზიმბაბვე');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'თურქეთი');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'თურქმენეთი');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'იამაიკა');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'იაპონია');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'იემენი');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'ინდოეთი');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'ინდონეზია');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'იორდანია');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'ირანი');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'ირლანდია');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'ისლანდია');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'ისრაელი');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'იტალია');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'კაბო-ვერდე');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'კაიმანის კუნძულები');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'კამბოჯა');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'კამერუნი');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'კანადა');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'კატარი');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'კენია');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'კვიპროსი');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'კირიბატი');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'კოლუმბია');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'კომორის კუნძულები');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'კონგო');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'კონგო - კინშასა');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'კოსტა-რიკა');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'კუბა');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'კუვეიტი');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'კუკის კუნძულები');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'ლაოსი');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'ლატვია');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'ლესოთო');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'ლიბანი');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'ლიბერია');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'ლიბია');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'ლიტვა');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'ლიხტენშტაინი');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'ლუქსემბურგი');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'მადაგასკარი');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'მავრიკია');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'მავრიტანია');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'მაკაო');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'მაკედონია');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'მალავი');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'მალაიზია');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'მალდივის კუნძულები');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'მალი');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'მალტა');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'მანის კუნძული');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'მაროკო');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'მარტინიკი');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'მარშალის კუნძულები');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'მექსიკა');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'მიანმარი');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'მიკრონეზია');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'მოზამბიკი');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'მოლდოვა');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'მონაკო');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'მონსერატი');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'მონტენეგრო');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'მონღოლეთი');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'ნამიბია');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'ნაურუ');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'ნეპალი');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'ნიგერი');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'ნიგერია');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'ნიდერლანდები');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'ნიდერლანდების ანტილები');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'ნიკარაგუა');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'ნორვეგია');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'ნორფოლკის კუნძული');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'ომანი');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'პაკისტანი');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'პალაუ');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'პალესტინის ტერიტორია');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'პანამა');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'პაპუა-ახალი გვინეა');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'პარაგვაი');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'პერუ');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'პოლონეთი');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'პორტუგალია');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'პუერტო რიკო');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'რეიუნიონი');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'რუანდა');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'რუმინეთი');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'რუსეთი');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'საბერძნეთი');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'სალვადორი');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'სამოა');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'სამხრეთ აფრიკა');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'სამხრეთი კორეა');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'სამხრეთი ჯორჯია და სამხრეთ სენდვიჩის კუნძულები');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'სან-მარინო');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'საო-ტომე და პრინსიპი');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'საუდის არაბეთი');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'საფრანგეთი');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'საქართველო');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'სეიშელის კუნძულები');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'სენეგალი');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'სენტ-ვინსენტი და გრენადინები');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'სენტ-კიტსი და ნევისი');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'სენტ-ლუსია');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'სენტ-პიერი და მიქელონი');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'სერბია');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'სერბია და მონტენეგრო');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'სვაზილენდი');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'სიერა-ლეონე');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'სინგაპური');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'სირია');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'სლოვაკეთი');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'სლოვენია');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'სოლომონის კუნძულები');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'სომალი');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'სომხეთი');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'სპილოს ძვლის სანაპირო');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'სუდანი');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'სურინამი');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'ტაივანი');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'ტაილანდი');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'ტანზანია');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'ტაჯიკეთი');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'ტოგო');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'ტონგა');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'ტრინიდადი და ტობაგო');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'ტუვალუ');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'ტუნისი');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'უგანდა');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'უზბეკეთი');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'უკრაინა');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'უნგრეთი');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'ურუგვაი');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'ფალკლენდის კუნძულები');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'ფაროს კუნძულები');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'ფილიპინები');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'ფინეთი');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'ფიჯი');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'ფრანგული პოლინეზია');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'ფრანგული სამხრეთის ტერიტორიები');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'ყაზახეთი');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'ყირგიზეთი');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'შეერთებული შტატების მცირე დაშორებული კუნძულები');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'შვეიცარია');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'შვეცია');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'შობის კუნძული');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'შრი-ლანკა');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'ჩადი');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'ჩეხეთის რესპუბლიკა');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'ჩილე');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'ჩინეთი');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'ჩრდილოეთი კორეა');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'ცენტრალური აფრიკის რესპუბლიკა');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'წმინდა ელენეს კუნძული');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'ჯერსი');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'ჯიბუტი');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'ჰაიტი');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'ჰერდის კუნძული და მაკდონალდის კუნძულები');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'ჰონგ კონგი');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'ჰონდურასი');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'ჰორვატია');
