CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afghanistan');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Ålánda');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albánia');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Algeria');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Amerihká ovttastuvvan stáhtat');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Amerihká Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andorra');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguilla');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Antárktis');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigua ja Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'AOS Virgin-sullot');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Argentina');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armenia');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Ascension');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Aserbaižan');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Austrália');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamas');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahrain');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladesh');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbados');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Belgia');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belize');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benin');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermuda');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Bhutan');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolivia');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnia-Hercegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswana');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brasil');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Brittania Virgin-sullot');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunei');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgária');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Burma');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('BQ', 'Caribbean Netherlands');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Cayman-sullot');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Čeahkka');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Ceuta ja Melilla');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Čiile');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Cocos-sullot');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Cook-sullot');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Costa Rica');
INSERT INTO [country] ([id], [name]) VALUES ('CW', 'Curaçao');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Dánmárku');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Davvi-Korea');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Davvi-Mariánat');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Davvisudan');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Diego Garcia');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Djibouti');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominica');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Dominikána dásseváldi');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Duiska');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Durka');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ecuador');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Egypta');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Ekvatoriála Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'El Salvador');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Elfenbenariddu');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritrea');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estlánda');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiopia');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Falklandsullot');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Fearsullot');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fijisullot');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filippiinnat');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Frankriika');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Frankriikka Guayana');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Frankriikka Polynesia');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Frankriikka Saint Martin');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'French Southern Territories');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabon');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gámbia');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Gaska-Afrihká dásseváldi');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Georgia');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ghana');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Gibraltar');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Greika');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grenada');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Guadeloupe');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guam');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Guatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Guernsey');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyana');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haiti');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Honduras');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Hongkong');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'India');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonesia');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Irak');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Iran');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Irlánda');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Islánda');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Israel');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Itália');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jamaica');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Japána');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Jemen');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Jersey');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Jordánia');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Juovllat-sullot');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Kalaallit Nunaat');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kambodža');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kamerun');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanáda');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Kanáriasullot');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Kap Verde');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kasakstan');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenia');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Kiinná');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kirgisistan');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolombia');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Komoros');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongo-Brazzaville');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Kongo-Kinshasa');
INSERT INTO [country] ([id], [name]) VALUES ('XK', 'Kosovo');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Kroátia');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kuba');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuwait');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Kypros');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laos');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Látvia');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesotho');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Libanon');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberia');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libya');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Liechtenstein');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lietuva');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Lulli Georgia ja Lulli Sandwich-sullot');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Luxembourg');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagaskar');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Makáo');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Makedonia');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawi');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Malediivvat');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malesia');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Málta');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Mann-sullot');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Marokko');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Marshallsullot');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martinique');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Mátta-Afrihká');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Mátta-Korea');
INSERT INTO [country] ([id], [name]) VALUES ('SS', 'Máttasudan');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mauretánia');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Mauritius');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayotte');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Meksiko');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikronesia');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldávia');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monaco');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongolia');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Montenegro');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montserrat');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mosambik');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibia');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nauru');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepal');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nicaragua');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Niger');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nigeria');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niue');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Norfolksullot');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norga');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Nuorta-Timor');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Nuortariika');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Oarje-Sahára');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Ođđa-Kaledonia');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Ođđa-Selánda');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Oman');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Ovttastuvvan Arábaemiráhtat');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistan');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Palestina');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papua-Ođđa-Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguay');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peru');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitcairn');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Polen');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portugála');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Puerto Rico');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Qatar');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Réunion');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Románia');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Ruošša');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Ruoŧŧa');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Rwanda');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Saint Barthélemy');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Saint Helena');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Saint Kitts ja Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Saint Lucia');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Saint Pierre ja Miquelon');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Saint Vincent ja Grenadine');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Salomon-sullot');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marino');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'São Tomé ja Príncipe');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Saudi-Arábia');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegal');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Serbia');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seychellsullot');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sierra Leone');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapore');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovákia');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slovenia');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somália');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Spánia');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Stuorra-Británnia');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Suopma');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinam');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Svalbárda ja Jan Mayen');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Svazieana');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Šveica');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Syria');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwan');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzánia');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tažikistan');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Tčad');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Thaieana');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidad ja Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunisia');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turkmenistan');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Turks ja Caicos-sullot');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'U.S. Outlying Islands');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukraina');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Ungár');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruguay');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Usbekistan');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatikána');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuela');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietnam');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Vilges-Ruošša');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Vuolleeatnamat');
INSERT INTO [country] ([id], [name]) VALUES ('SX', 'Vuolleeatnamat Saint Martin');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wallis ja Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambia');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabwe');
