CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afganistan');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albània');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Alemanya');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Algèria');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andorra');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Anguilla');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Antàrtida');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigua i Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Antilles Neerlandeses');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Aràbia Saudita');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argentina');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armènia');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Austràlia');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Àustria');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azerbaidjan');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahames');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrain');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangla Desh');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbados');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Bèlgica');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benín');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermudes');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Bhutan');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Bielorússia');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolívia');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bòsnia i Hercegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brasil');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgària');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Cambodja');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Camerun');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Canadà');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Cap Verd');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'Ceuta i Melilla');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Colòmbia');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Comores');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Congo - Brazzaville');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Congo - Kinshasa');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Corea del Nord');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Corea del Sud');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Costa d’Ivori');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Costa Rica');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Croàcia');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Cuba');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'Diego Garcia');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Dinamarca');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Djibouti');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominica');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Egipte');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'El Salvador');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Equador');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritrea');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Eslovàquia');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Eslovènia');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Espanya');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Estats Units');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estònia');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Etiòpia');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fiji');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filipines');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finlàndia');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'França');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabon');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gàmbia');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Geòrgia');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ghana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Gibraltar');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Grècia');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Grenlàndia');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Guadeloupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Guaiana Francesa');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guam');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Guatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'Guernsey');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Guinea Bissau');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Guinea Equatorial');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haití');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Hondures');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Hongria');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Iemen');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'Illa Bouvet');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Illa Christmas');
INSERT INTO `country` (`id`, `name`) VALUES ('CP', 'Illa Clipperton');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'Illa de l\'Ascensió');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Illa de la Reunió');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'Illa de Man');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'Illa Heard i Illes McDonald');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Illa Norfolk');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Illes Åland');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Illes Caiman');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'Illes Canàries');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'Illes Cocos');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Illes Cook');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Illes Fèroe');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'Illes Geòrgia del Sud i Sandwich del Sud');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Illes Malvines');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Illes Mariannes del Nord');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Illes Marshall');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'Illes Perifèriques Menors dels EUA');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Illes Pitcairn');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Illes Salomó');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Illes Turks i Caicos');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Illes Verges Britàniques');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Illes Verges Nord-americanes');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Índia');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonèsia');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iran');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Iraq');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irlanda');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Islàndia');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Israel');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Itàlia');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaica');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japó');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'Jersey');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordània');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazakhstan');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirguizistan');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuwait');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laos');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Letònia');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Líban');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Libèria');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Líbia');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Liechtenstein');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Lituània');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Luxemburg');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Macedònia');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagascar');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malàisia');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldives');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Marroc');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinica');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Maurici');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauritània');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayotte');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Mèxic');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Micronèsia');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Moçambic');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldàvia');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Mònaco');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongòlia');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Myanmar [Birmània]');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namíbia');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepal');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nicaragua');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Níger');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigèria');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Noruega');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Nova Caledònia');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Nova Zelanda');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Països Baixos');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Palestina');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panamà');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papua Nova Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paraguai');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Perú');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Polinèsia Francesa');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Polònia');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portugal');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Puerto Rico');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Qatar');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'Regió administrativa especial xinesa de Hong Kong');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Regió administrativa especial xinesa de Macau');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Regne Unit');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'República Centreafricana');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'República de Sud-àfrica');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'República Dominicana');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'República Txeca');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romania');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Rússia');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Rwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Sàhara Occidental');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'Saint Barthélemy');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Saint Christopher i Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Saint Helena');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Saint Lucia');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'Saint Martin');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Saint Pierre i Miquelon');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Saint Vincent i les Grenadines');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Samoa Americana');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'São Tomé i Príncipe');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegal');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Sèrbia');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Sèrbia i Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seychelles');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sierra Leone');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapur');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Síria');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somàlia');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudan');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Suècia');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Suïssa');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Surinam');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Svalbard i Jan Mayen');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Swazilàndia');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tadjikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Tailàndia');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzània');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Territori Britànic de l\'Oceà Índic');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'Territoris allunyats d\'Oceania');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'Territoris Francesos del Sud');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Timor Oriental');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinitat i Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'Tristão da Cunha');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunísia');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Turquia');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Txad');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ucraïna');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Unió dels Emirats Àrabs');
INSERT INTO `country` (`id`, `name`) VALUES ('EU', 'Unió Europea');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Uruguai');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzbekistan');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vaticà');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Veneçuela');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vietnam');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis i Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Xile');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Xina');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Xipre');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zàmbia');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
