CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('VI', 'ABŞ Vircin Adaları');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Aland Adaları');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albaniya');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Almaniya');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Amerika Birləşmiş Ştatları');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Amerika Samoası');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andorra');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Angila');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Anqola');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Antarktika');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antiqua və Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Argentina');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Avstraliya');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Avstriya');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azərbaycan');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Baham Adaları');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Banqladeş');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbados');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Belarus');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Beliz');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Belçika');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benin');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermuda');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Birləşmiş Krallıq');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'Birləşmiş Ştatlar Uzaq Adalar');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Birləşmiş Ərəb Əmirlikləri');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Boliviya');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bolqariya');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosniya və Hersoqovina');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botsvana');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Braziliya');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Britaniya Hind Okeanı Ərazisi');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Britaniya Vircin Adaları');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Bruney');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burkina Faso');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Butan');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Buve Adası');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bəhreyn');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Cersi');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Cibuti');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Cənub Afrika');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'Cənubi Corciya və Cənubi Sendviç Adaları');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Cənubi Koreya');
INSERT INTO "country" ("id", "name") VALUES ('SS', 'Cənubi Sudan');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Danimarka');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'Dieqo Qarsiya');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominika');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Dominikan Respublikası');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Efiopiya');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekvador');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Ekvatorial Qvineya');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritreya');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Ermənistan');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Estoniya');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Farer Adaları');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fici');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Fil Dişi Sahili');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filippin');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finlandiya');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Folklend Adaları');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Fransa');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Fransa Cənub Əraziləri');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Fransız Polineziyası');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Fransız Qviyanası');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Fələstin Əraziləri');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Gernsey');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Gibraltar');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Gürcüstan');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haiti');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Herd və Mak Donald Adaları');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Hindistan');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Hollandiya antilleri');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduras');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Honq Konq Xüsusi İnzibati Ərazi Çin');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kamboca');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamerun');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'Kanar Adaları');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Kape Verde');
INSERT INTO "country" ("id", "name") VALUES ('BQ', 'Karib Niderlandı');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Kayman Adaları');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Keniya');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Kipr');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('CP', 'Klipperton Adası');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Kokos Adaları');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolumbiya');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komor Adaları');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Konqo - Brazzavil');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Konqo - Kinşasa');
INSERT INTO "country" ("id", "name") VALUES ('XK', 'Kosovo');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kosta Rika');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kuba');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Kuk Adaları');
INSERT INTO "country" ("id", "name") VALUES ('CW', 'Kurasao');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Küveyt');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laos');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Latviya');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesoto');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberiya');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Litva');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Livan');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Liviya');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Lixtenşteyn');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Lüksemburq');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Macarıstan');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madaqaskar');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Makao Xüsusi İnzibati Ərazi Çin');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Makedoniya');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malavi');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malayziya');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldiv Adaları');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martinik');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Marşal Adaları');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Mavriki');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mavritaniya');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayot');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Meksika');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Men Adası');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikroneziya');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Milad Adası');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Misir');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldova');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monako');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Monqoliya');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Monserat');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Monteneqro');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mozambik');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Myanma');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Müqəddəs Yelena');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Mərakeş');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Mərkəzi Afrika Respublikası');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibiya');
INSERT INTO "country" ("id", "name") VALUES ('ZZ', 'Naməlum Region');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepal');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Niderland');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Niger');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nigeriya');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikaraqua');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Norfolk Adası');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Norveç');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Oman');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakistan');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papua Yeni Qvineya');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraqvay');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Peru');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitkern Adaları');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Polşa');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portuqal');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Puerto Riko');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Qabon');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Qambiya');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Qana');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Qatar');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Qazaxıstan');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Qrenada');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Qrenlandiya');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Quam');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Qvadelupa');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Qvatemala');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Qvineya');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Qvineya-Bisau');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Qviyana');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Qırğızıstan');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Qərbi Sahara');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Reunion');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ruanda');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Rumıniya');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Rusiya');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Salvador');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samoa');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'San Bartolomey');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'San Kits və Nevis');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'San Lüsiya');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'San Marino');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'San Martin');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'San Pier və Mikelon');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'San Vinsent və Qrenada');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sao Tome və Prinsip');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Seneqal');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Serbiya');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'Seuta və Melilya');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Seyşel Adaları');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Siera Leon');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Sinqapur');
INSERT INTO "country" ("id", "name") VALUES ('SX', 'Sint Maarten');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slovakiya');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Sloveniya');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Solomon Adaları');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somali');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudan');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Surinam');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Suriya');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Svalbard və Yan Mayen');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Svazilend');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Səudiyyə Ərəbistanı');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tacikistan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzaniya');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Tayland');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Tayvan');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonqa');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Toqo');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad və Tobaqo');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'Tristan da Kunya');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunis');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Turks və Kaikos Adaları');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Türkiya');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Türkmənistan');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukrayna');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Uolis və Futuna');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uqanda');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruqvay');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikan');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venesuela');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vyetnam');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Xorvatiya');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Yamayka');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Yaponiya');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Yeni Kaledoniya');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Yeni Zelandiya');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Yunanıstan');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'Yüksəliş Adası');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Yəmən');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambiya');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabve');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Çad');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Çexiya');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Çili');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Çin');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Özbəkistan');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'İndoneziya');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'İordaniya');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'İran');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'İraq');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'İrlandiya');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'İslandiya');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'İspaniya');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'İsrail');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'İsveç');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'İsveçrə');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'İtaliya');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Şimali Koreya');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Şimali Mariana Adaları');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Şri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Şərqi Timor');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Əfqanıstan');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Əlcəzair');
