CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anikuila');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Anitikua mo Palaputa');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Falanisē');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Falanise Kuiana');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipaini');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finilani');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fisi');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Haʻamoa');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Haʻamoa ʻAmelika');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haiti');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Hangakalia');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Hōlani');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Hongi Kongi SAR Siaina');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Honitulasi');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'ʻAealani');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'ʻAfikānisitani');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'ʻAfilika tonga');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'ʻAisilani');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'ʻAisilia');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'ʻAlepea Fakatahataha');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'ʻAlipania');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'ʻAlupa');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'ʻĀminia');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'ʻAnitātika');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'ʻAositelēlia');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'ʻAositulia');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'ʻAsapaisani');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'ʻAsenitina');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'ʻEkueta Kini');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'ʻEkuetoa');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'ʻEle Salavatoa');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'ʻElitulia');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'ʻEnikola');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'ʻEnitola');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'ʻEsitōnia');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'ʻInitia');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'ʻInitonēsia');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'ʻIsileli');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'ʻIsipite');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'ʻĪtali');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'ʻItiōpea');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'ʻIukanitā');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'ʻIukuleini');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'ʻIulaaki');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'ʻIulaani');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'ʻIulope fakatahataha');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'ʻOmani');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'ʻOsenia Mamaʻo');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'ʻOtumotu Felou');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'ʻOtumotu Fokuleni');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'ʻOtumotu Heati mo Makitonali');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'ʻOtumotu ʻAlani');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'ʻOtumotu Kaneli');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'ʻOtumotu Keimeni');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'ʻOtumotu Koko');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'ʻOtumotu Kuki');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'ʻOtumotu Maliana tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'ʻOtumotu Māsolo');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'ʻOtumotu Pitikeni');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'ʻOtumotu Seiseli');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'ʻOtumotu siʻi ʻo ʻAmelika');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'ʻOtumotu Siosia-tonga mo Saniuisi-tonga');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'ʻOtumotu Solomone');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'ʻOtumotu Teki mo Keikosi');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'ʻOtumotu Vilikini fakaʻamelika');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'ʻOtumotu Vilikini fakapilitānia');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'ʻUlukuei');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'ʻUsipekitēni');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'ʻUvea mo Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Iemeni');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Kalisi');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Kamipia');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Kana');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kānata');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Kaponi');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kasakiteni');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Katā');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kekisiteni');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Kelenatā');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kemaluni');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kemipōtia');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenia');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kilipasi');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Kini');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Kini-Pisau');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kiupa');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Kōlea tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Kōlea tonga');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolomipia');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Komolosi');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Kongo - Kinisasa');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongo - Palasavila');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kosita Lika');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Kuamu');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Kuatalupe');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Kuatamala');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kueiti');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Kuenisī');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Kuiana');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Kulinileni');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Kuloisia');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Laipelia');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Lakisimipeki');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Lativia');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Lau');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Lekitenisaini');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Lepanoni');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesoto');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lifiuenia');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Liʻiunioni');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Lipapilika ʻAfilika Lotoloto');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Lipapilika Seki');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Lipapilika Tominika');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Lipia');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Lomēnia');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Luanitā');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Lūsia');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Makau SAR Siaina');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Malativisi');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malaui');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malēsia');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Māli');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malita');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Manako');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Masitōnia');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Matafonua ʻAivili');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Matakasika');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Mateniki');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Maulitenia');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Maulitiusi');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Meioti');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mekisikou');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikolonisia');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Moʻungaselati');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Molako');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Molotova');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongokōlia');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Monitenikalo');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mosenipiki');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Motu ʻAsenisini');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'Motu Kilipatoni');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Motu Kilisimasi');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Motu Mani');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Motu Nōfoliki');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Motu Puveti');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Muiʻi Veti');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Naisia');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Naisilia');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namipia');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Naulu');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepali');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Netaleni ʻEnitilisi');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikalakua');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Niu Kaletōnia');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niuē');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Noauē');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Nuʻusila');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Pahama');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pākisitani');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Palakuei');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Palāsili');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Paleini');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panamā');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Pāpeitosi');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papuaniukini');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Pekano Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Pelaniti');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Pelelusi');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Pelesiume');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Pelise');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Pelū');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Pema');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Pēmuta');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Pengilātesi');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Penini');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Pilitānia');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Pokalia');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Poleni');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Polinisia fakafalanisē');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Polīvia');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Posinia mo Hesikōvinia');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Potisiuana');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Potu fonua moana ʻInitia fakapilitānia');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Potu fonua tonga fakafalanisē');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Potu Palesitaine');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Potukali');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Pueto Liko');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Puleʻanga fakatahataha ʻAmelika');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Pulunei');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Pūtani');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Sahala fakahihifo');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Saipalesi');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Samaika');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Sao Tome mo Pilinisipe');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Saute ʻAlepea');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Seini Helena');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Seini Kitisi mo Nevisi');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Seini Lusia');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Seini Matini');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Seini Pafelemi');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Seini Piea mo Mikaloni');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Seini Viniseni mo Kulenatini');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Selusī');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Semipia');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'Seni Malino');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senikalo');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Sēpia');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Seti');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Siaina');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Siamane');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Siapani');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Siela Lione');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Silangikā');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Sili');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Sīlia');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Silōvakia');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Silōvenia');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Simipapuei');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapoa');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Sipalālitā');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Sipeini');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Siputi');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Siuta mo Melila');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Sivolopaati mo Seni Meini');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Soatane');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Sōmalia');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Sōsia');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Suasileni');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Suēteni');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Suisilani');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Sulinami');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sūteni');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Taileni');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiuani');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tasikitani');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Tekimenisiteni');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Tenimaʻake');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tenisania');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Tieko Kāsia');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Tilinitati mo Topako');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timoa Hahake');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Toake');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Toko');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Tominika');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Tulisiteni ta Kunuha');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunīsia');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tūvalu');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatikani');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venisuela');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietinemi');
