CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('VI', 'ABD Virgin Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afganistan');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Aland Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Almanya');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Amerika Birleşik Devletleri');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Amerika Birleşik Devletleri Küçük Dış Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Amerikan Samoası');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andorra');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguilla');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Antarktika');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigua ve Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Arjantin');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Arnavutluk');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Ascension Adası');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'Avrupa Birliği');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Avustralya');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Avusturya');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azerbaycan');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamalar');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahreyn');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladeş');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbados');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Batı Sahara');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Belçika');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belize');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benin');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermuda');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Beyaz Rusya');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Birleşik Arap Emirlikleri');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Birleşik Krallık');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolivya');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosna Hersek');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botsvana');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Bouvet Adası');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brezilya');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunei');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgaristan');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Butan');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Cape Verde');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Cayman Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Cebelitarık');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Ceuta ve Melilla');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Cezayir');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Christmas Adası');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Cibuti');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'Clipperton Adası');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Cocos Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Cook Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Çad');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Çek Cumhuriyeti');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Çin');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Danimarka');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Diego Garcia');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Dominik Cumhuriyeti');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominika');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ekvador');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Ekvator Ginesi');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'El Salvador');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Endonezya');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritre');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Ermenistan');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estonya');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiyopya');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Falkland Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Faroe Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Fas');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fiji');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Fildişi Sahili');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipinler');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Filistin Bölgesi');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finlandiya');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Fransa');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Fransız Guyanası');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Fransız Güney Bölgeleri');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Fransız Polinezyası');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabon');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambiya');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Gana');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Gine');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Gine-Bissau');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grenada');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Grönland');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Guadalupe');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guam');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Guatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Guernsey');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyana');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Güney Afrika');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Güney Georgia ve Güney Sandwich Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Güney Kıbrıs Rum Kesimi');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Güney Kore');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Gürcistan');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haiti');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'Heard Adası ve McDonald Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Hırvatistan');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Hindistan');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Hollanda');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Hollanda Antilleri');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Honduras');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Hong Kong SAR - Çin');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Irak');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'İngiliz Hint Okyanusu Bölgesi');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'İngiliz Virgin Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'İran');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'İrlanda');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'İspanya');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'İsrail');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'İsveç');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'İsviçre');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'İtalya');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'İzlanda');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jamaika');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Japonya');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Jersey');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kamboçya');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kamerun');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanada');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Kanarya Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Karadağ');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Katar');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazakistan');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenya');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kırgızistan');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolombiya');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Komorlar');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongo - Brazavil');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Kongo - Kinşasa');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kosta Rika');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuveyt');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Kuzey Kore');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Kuzey Mariana Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Küba');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laos');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesoto');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Letonya');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberya');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libya');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Liechtenstein');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Litvanya');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Lübnan');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Lüksemburg');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Macaristan');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagaskar');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Makao SAR - Çin');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Makedonya');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malavi');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maldivler');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malezya');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Man Adası');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Marshall Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martinik');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Mauritius');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayotte');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Meksika');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Mısır');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikronezya Federal Eyaletleri');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Moğolistan');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldova');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monako');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montserrat');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Moritanya');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambik');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myanmar');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibya');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nauru');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepal');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Nijer');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nijerya');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikaragua');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niue');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Norfolk Adası');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norveç');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Orta Afrika Cumhuriyeti');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Özbekistan');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistan');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papua Yeni Gine');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguay');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peru');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitcairn');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Polonya');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portekiz');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Porto Riko');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Reunion');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Romanya');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Ruanda');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rusya');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Saint Barthelemy');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Saint Helena');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Saint Kitts ve Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Saint Lucia');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Saint Martin');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Saint Pierre ve Miquelon');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Saint Vincent ve Grenadinler');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marino');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Sao Tome ve Principe');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegal');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seyşeller');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Sırbistan');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Sırbistan-Karadağ');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sierra Leone');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapur');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovakya');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slovenya');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Solomon Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somali');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudan');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinam');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Suriye');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Suudi Arabistan');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Svalbard ve Jan Mayen Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Svaziland');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Şili');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tacikistan');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzanya');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Tayland');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Tayvan');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timor-Leste');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidad ve Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunus');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Turks ve Caicos Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Türkiye');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Türkmenistan');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukrayna');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Umman');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruguay');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'Uzak Okyanusya');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Ürdün');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatikan');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuela');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietnam');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wallis ve Futuna Adaları');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yemen');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Yeni Kaledonya');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Yeni Zelanda');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Yunanistan');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambiya');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabve');
