CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Ả Rập Xê-út');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afghanistan');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Ai Cập');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Ai-len');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albani');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Algeria');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andorra');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Anguilla');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigua và Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Áo');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argentina');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armenia');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azerbaijan');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Ấn Độ');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Ba Lan');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamas');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrain');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladesh');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbados');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Belarus');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benin');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Bhutan');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Bỉ');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolivia');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosnia và Herzegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Bồ Đào Nha');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Bờ Biển Ngà');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brazil');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bungari');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('BQ', 'Ca-ri-bê Hà Lan');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'Các đảo nhỏ xa t.tâm thuộc Mỹ');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Các Tiểu V.quốc Ả Rập T.nhất');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Cameroon');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Campuchia');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Canada');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Cape Verde');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'Ceuta và Melilla');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Chad');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Chile');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Colombia');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Comoros');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Congo - Brazzaville');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Congo - Kinshasa');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Costa Rica');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Cô-oét');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Cộng hòa Dominica');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Cộng hòa Séc');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Cộng hòa Trung Phi');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Croatia');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Cuba');
INSERT INTO `country` (`id`, `name`) VALUES ('CW', 'Curaçao');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'Diego Garcia');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Djibouti');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominica');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Đài Loan');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Đan Mạch');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'Đảo Ascension');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Đảo Giáng Sinh');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'Đảo Man');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Đảo Norfolk');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Đảo Somoa thuộc Mỹ');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'Đặc khu hành chính Hồng Kông - Trung Quốc');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Đặc khu hành chính Macao - Trung Quốc');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Đông Timor');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Đức');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ecuador');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'El Salvador');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritrea');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estonia');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Ethiopia');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fiji');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabon');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Georgia');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ghana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Gibraltar');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Greenland');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Guadeloupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guam');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Guatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'Guernsey');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Guiana thuộc Pháp');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Guinea Xích Đạo');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Hà Lan');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Hàn Quốc');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Hoa Kỳ');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Hungari');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Hy Lạp');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'I-rắc');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Iceland');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonesia');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iran');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Israel');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaica');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'Jersey');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordan');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazakhstan');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('XK', 'Kosovo');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'Lãnh thổ miền nam nước Pháp');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Lãnh thổ Palestine');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Lào');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Latvia');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Li-băng');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Li-bi');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberia');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Liechtenstein');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Lít-va');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Luxembourg');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Ma-rốc');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Macedonia');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagascar');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malaysia');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldives');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinique');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauritania');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Mauritius');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayotte');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Mexico');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Micronesia');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldova');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monaco');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambique');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mông Cổ');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Myanmar (Miến Điện)');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Na Uy');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Nam Cực');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Nam Phi');
INSERT INTO `country` (`id`, `name`) VALUES ('SS', 'Nam Sudan');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibia');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepal');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'New Caledonia');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'New Zealand');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Nga');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Nhật Bản');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nicaragua');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Niger');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigeria');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papua New Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paraguay');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Pháp');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Phần Lan');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Philippin');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Polynesia thuộc Pháp');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Puerto Rico');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Qatar');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Quần đảo Åland');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Quần đảo Bắc Mariana');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'Quần đảo Canary');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Quần đảo Cayman');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'Quần đảo Cocos (Keeling)');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Quần đảo Cook');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Quần đảo Falkland');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Quần đảo Faroe');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Quần đảo Marshall');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'Quần đảo Nam Georgia và Nam Sandwich');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Quần đảo Pitcairn');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Quần đảo Solomon');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Quần đảo Turk và Caicos');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Quần đảo Virgin thuộc Anh');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Quần đảo Virgin thuộc Mỹ');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Réunion');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romania');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Rwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'Saint Barthélemy');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Saint Helena');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Saint Kitts và Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Saint Lucia');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'Saint Martin');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Saint Pierre và Miquelon');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Saint Vincent và Grenadines');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'São Tomé và Príncipe');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegal');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Serbia');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seychelles');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sierra Leone');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapore');
INSERT INTO `country` (`id`, `name`) VALUES ('SX', 'Sint Maarten');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Síp');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Slovakia');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Slovenia');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somali');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudan');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Suriname');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Svalbard và Jan Mayen');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Swaziland');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Syria');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tajikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzania');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Tây Ban Nha');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Tây Sahara');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Thái Lan');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Thành Vatican');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Thổ Nhĩ Kỳ');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Thuộc địa Anh tại Ấn Độ Dương');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Thụy Điển');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Thụy Sĩ');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Triều Tiên');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad và Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Trung Quốc');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunisia');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Úc');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukraina');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Uruguay');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzbekistan');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Việt Nam');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Vương quốc Anh');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis và Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Ý');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Yemen');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambia');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
