CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andora');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Amahanga ga Buharabu ageeteereine');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afuganistani');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Angiguwa na Babuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Angwira');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Arubania');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Arimeniya');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Antiri za Hoorandi');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angora');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Arigentina');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Samowa ya Ameerika');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Osituria');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Ositureeriya');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azabagyani');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Boziniya na Hezegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Babadosi');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangaradeshi');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Bubirigi');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Bokina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Burugariya');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahareni');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benini');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Berimuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Burunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Boriiviya');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Buraziiri');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahama');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Butani');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Bararusi');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Berize');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Demokoratika Ripaaburika ya Kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Eihanga rya Rwagati ya Afirika');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Swisi');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Aivore Kositi');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Ebizinga bya Kuuku');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Chile');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kameruuni');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'China');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Korombiya');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Kositarika');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Saabiya na Monteneguro');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Cuba');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Ebizinga bya Kepuvade');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Saipurasi');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Ripaaburika ya Zeeki');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Bugirimaani');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Gyibuti');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Deenimaaka');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominika');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Ripaaburika ya Dominica');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Arigyeriya');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ikweda');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Esitoniya');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Misiri');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eriteriya');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Sipeyini');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Ethiyopiya');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Bufini');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Figyi');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Ebizinga bya Faakilanda');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikironesiya');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Bufaransa');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabooni');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Bungyereza');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Gurenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Gyogiya');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Guyana ya Bufaransa');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Gana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Giburaata');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Guriinirandi');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambiya');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Gine');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Gwaderupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Guni');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Guriisi');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Gwatemara');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Gwamu');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Ginebisau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Hondurasi');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Korasiya');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Hangare');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indoneeziya');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irerandi');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Isirairi');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Indiya');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Iraaka');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iraani');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Aisilandi');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Itare');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Gyamaika');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Yorudaani');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Gyapaani');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirigizistani');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambodiya');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Koromo');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Senti Kittis na Nevisi');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Koreya Amatemba');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Koreya Amashuuma');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuweiti');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Ebizinga bya Kayimani');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazakisitani');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Layosi');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Lebanoni');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Senti Rusiya');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Lishenteni');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Siriranka');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberiya');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Lithuania');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Lakizembaaga');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Latviya');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libya');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Morocco');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monaco');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moridova');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagasika');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Ebizinga bya Marshaa');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Masedoonia');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mari');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Myanamar');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongoria');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Ebizinga by\'amatemba ga Mariana');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinique');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauriteeniya');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrati');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Marita');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Maurishiasi');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maridives');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Marawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Mexico');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'marayizia');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambique');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibiya');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Niukaredonia');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Naigya');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Ekizinga Norifoko');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Naigyeriya');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikaragwa');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Hoorandi');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Noorwe');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepo');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Niuzirandi');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Omaani');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Polinesia ya Bufaransa');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papua');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Firipino');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakisitaani');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Poorandi');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Senti Piyerre na Mikweron');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitkaini');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Pwetoriko');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', '');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Pocugo');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palaawu');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paragwai');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Kata');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Riyuniyoni');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Rrasha');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Rwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Saudi Areebiya');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Ebizinga bya Surimaani');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Shesheresi');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudani');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Swideni');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapo');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Senti Herena');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Sirovaaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Sirovaakiya');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sirra Riyooni');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'Samarino');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senego');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somaariya');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Surinaamu');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Sawo Tome na Purinsipo');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Eri Salivado');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Siriya');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Swazirandi');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Ebizinga bya Buturuki na Kaiko');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Chadi');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Tairandi');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tajikisitani');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokerawu');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Burugweizooba bwa Timori');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turukimenisitani');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunizia');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Buturuki /Take');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Turinidad na Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvaru');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Tayiwaani');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzania');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukureini');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Amerika');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Urugwai');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzibekisitani');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatikani');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Senti Vinsent na Gurenadini');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuwera');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Ebizinga bya Virigini ebya Bungyereza');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Ebizinga bya Virigini ebya Amerika');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Viyetinaamu');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Warris na Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samowa');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Yemeni');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayote');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Sausi Afirika');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambia');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
