CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afghanistan');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albania');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Algerie');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Amerikansk Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andorra');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Anguilla');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Antarktis');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigua og Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argentina');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armenia');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'Ascension');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Aserbajdsjan');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Australia');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamas');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrain');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladesh');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbados');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belgia');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benin');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Bhutan');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolivia');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosnia-Hercegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brasil');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Britiske territorier i Indiahavet');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgaria');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Canada');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Caymanøyene');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'Ceuta og Melilla');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Chile');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Christmasøya');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Colombia');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Cookøyene');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Costa Rica');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Cuba');
INSERT INTO `country` (`id`, `name`) VALUES ('CW', 'Curaçao');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Danmark');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'De amerikanske jomfruøyene');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'De britiske jomfruøyene');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'De forente arabiske emirater');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'De franske sørterritorier');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Den dominikanske republikk');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Den sentralafrikanske republikk');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Det palestinske området');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'Diego Garcia');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Djibouti');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominica');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ecuador');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Egypt');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Ekvatorial-Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'El Salvador');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Elfenbenskysten');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritrea');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estland');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Etiopia');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Falklandsøyene');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fiji');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filippinene');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finland');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Frankrike');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Fransk Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Fransk Polynesia');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Færøyene');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabon');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Georgia');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ghana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Gibraltar');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Grønland');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Guadeloupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guam');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Guatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'Guernsey');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Hellas');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'Hongkong S.A.R. Kina');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Hviterussland');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'India');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonesia');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Irak');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iran');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irland');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Island');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Israel');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italia');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaica');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japan');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Jemen');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'Jersey');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordan');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambodsja');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kamerun');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'Kanariøyene');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Kapp Verde');
INSERT INTO `country` (`id`, `name`) VALUES ('BQ', 'Karibisk Nederland');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kasakhstan');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Kina');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirgisistan');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'Kokosøyene');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Komorene');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongo-Brazzaville');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Kongo-Kinshasa');
INSERT INTO `country` (`id`, `name`) VALUES ('XK', 'Kosovo');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Kroatia');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuwait');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Kypros');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laos');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Latvia');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libanon');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberia');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libya');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Liechtenstein');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Litauen');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Luxemburg');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Macao S.A.R. Kina');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagaskar');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Makedonia');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malaysia');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldivene');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'Man');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Marokko');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Marshalløyene');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinique');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauritania');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Mauritius');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayotte');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Mexico');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikronesiaføderasjonen');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldova');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monaco');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongolia');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mosambik');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Myanmar (Burma)');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibia');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Nederland');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepal');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'New Zealand');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nicaragua');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Niger');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigeria');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Nord-Korea');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Nord-Marianene');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Norfolkøya');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norge');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Ny-Caledonia');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papua Ny-Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paraguay');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitcairn');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Polen');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portugal');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Puerto Rico');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Qatar');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Réunion');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romania');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Russland');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Rwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'Saint-Barthélemy');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'Saint-Martin');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Salomonøyene');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'São Tomé og Príncipe');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Saudi-Arabia');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegal');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Serbia');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seychellene');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sierra Leone');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapore');
INSERT INTO `country` (`id`, `name`) VALUES ('SX', 'Sint Maarten');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Slovakia');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Slovenia');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somalia');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Spania');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'St. Helena');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'St. Kitts og Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'St. Lucia');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'St. Pierre og Miquelon');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'St. Vincent og Grenadinene');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Storbritannia');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudan');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Surinam');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Svalbard og Jan Mayen');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Sveits');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Sverige');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Swaziland');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Syria');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Sør-Afrika');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'Sør-Georgia og Sør-Sandwichøyene');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Sør-Korea');
INSERT INTO `country` (`id`, `name`) VALUES ('SS', 'Sør-Sudan');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tadsjikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzania');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Thailand');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad og Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Tsjad');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Tsjekkia');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunisia');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Turks- og Caicosøyene');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Tyrkia');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Tyskland');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukraina');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Ungarn');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Uruguay');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'USA');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'USAs ytre øyer');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Usbekistan');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatikanstaten');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Vest-Sahara');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vietnam');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis og Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambia');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Øst-Timor');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Østerrike');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Åland');
