CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afaganistan');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Afirka Ta Kudu');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Aibari Kwas');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Aisalan');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Aljeriya');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Amurka');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andora');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Angila');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigwa da Barbuba');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Antiya Na Holan');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Arjantiniya');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armeniya');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Ayalan');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azarbaijan');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamas');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Baharan');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangiladas');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Banuwatu');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbadas');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Barmuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Baswana');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Batikan');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Belarus');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belgiyom');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Beliz');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Benezuwela');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Binin');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Birazil');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Birtaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Biyetinam');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolibiya');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosniya Harzagobina');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgariya');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Burma, Miyamar');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Burune');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Butan');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Cadi');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Caina, Sin');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Cayile');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Danmark');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominika');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ekwador');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'El Salbador');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritireya');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estoniya');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Faransa');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fiji');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filipin');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finlan');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Folinesiya Ta Faransa');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabon');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambiya');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Gana');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Gini');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Gini Bisau');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Gini Ta Faransa');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Gini Ta Ikwaita');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Girka');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Girnada');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Grinlan');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Gwadaluf');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Gwam');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Gwatamala');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Habasha');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Haɗaɗɗiyar Daular Larabawa');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Holan');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Hungari');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Indiya');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indunusiya');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Iraƙi');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iran');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italiya');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Izira\'ila');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaika');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Jamhuriyar Afirka Ta Tsakiya');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Jamhuriyar Cak');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Jamhuriyar Dimokuraɗiyyar Kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Jamhuriyar Dominika');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Jamus');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japan');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Jibaraltar');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Jibuti');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Jiwarjiya');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordan');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Kaledoniya Sabuwa');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kamaru');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambodiya');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirgizistan');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolambiya');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Koreya Ta Arewa');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Koreya Ta Kudu');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Kurowaishiya');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Kwamoras');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Kwasta Rika');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Kwatar');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kwiyat');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kyuba');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Ƙasar Makka');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Labanan');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Laberiya');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'latibiya');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Lawas');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesoto');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libiya');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Licansitan');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Lituweniya');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Lukusambur');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagaskar');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Makasiko');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malaisiya');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldibi');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Maldoba');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mangoliya');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Manserati');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Maroko');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinik');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Masar, Misira');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Masedoniya');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayoti');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikuronesiya');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monako');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Moritaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Moritus');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambik');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Najeriya');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibiya');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nefal');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Nijar');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikaraguwa');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niyu');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norwe');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Nuzilan');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Ostareliya');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Ostiriya');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Palasɗinu');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papuwa Nugini');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paragai');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitakarin');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Polan');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Porto Riko');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portugal');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Rasha');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Rawuniyan');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Ruwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Saishal');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Salewo');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samowa');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Samowa Ta Amurka');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'San Binsan Da Girnadin');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'San Helena');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'San Kiti Da Nebis');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'San Lusiya');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'San Piyar Da Mikelan');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Sarbiya Da Mantanegiro');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Sawo Tome Da Paransip');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Sifurus');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapur');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Sinigal');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Sipen');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Siri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somaliya');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudan');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Sulobakiya');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Sulobeniya');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Suriname');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Suwazilan');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Suwedan');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Suwizalan');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Sham, Siriya');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Tailan');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwan');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tajikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Takelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tanga');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Timor Ta Gabas');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Tirinidad Da Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tubalu');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunisiya');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Turkis Da Tsibiran Kaikwas');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Turkiyya');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkumenistan');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Tsibiran Birjin Ta Amurka');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Tsibiran Falkilan');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Tsibiran Kaiman');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Tsibiran Kap Barde');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Tsibiran Kuku');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Tsibiran Mariyana Na Arewa');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Tsibiran Marshal');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Tsibiran Salaman');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Tsibirin Birjin Na Birtaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Tsibirin Narfalk');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzubekistan');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Walis Da Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Yamal');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Yankin Birtaniya Na Tekun Indiya');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Yuganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Yukaran');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Yurugai');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambiya');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabuwe');
