CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andorra');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Veräinigti Arabischi Emiräät');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afganischtan');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua und Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anguilla');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albaanie');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armeenie');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Niderländischi Antille');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angoola');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Antarktis');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Argentiinie');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Amerikaanisch-Samoa');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Ööschtriich');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Auschtraalie');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Aaland-Insle');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Aserbäidschan');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosnie und Herzegowina');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbados');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladesch');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Belgie');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burkina Faaso');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulgaarie');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bachräin');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benin');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'St. Barthelemi');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermuuda');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brunäi Tarussalam');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Boliivie');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brasilie');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahaamas');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Bhutan');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Bouvet-Insle');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botswana');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Wiissrussland');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belize');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Kokos-Insle');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Temokraatischi Republik Kongo');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Zentraalafrikaanischi Republik');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Schwiiz');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Elfebäiküschte');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Cook-Insle');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Tschile');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamerun');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Chiina');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolumbie');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Coschta Rica');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Särbie und Monteneegro');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kuba');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Kap Verde');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Wienachts-Insle');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Tsüpere');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Tschechischi Republik');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Tüütschland');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Tschibuuti');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Tänemark');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Tominica');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Tominikaanischi Republik');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Algeerie');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ecuador');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Eestland');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Ägüpte');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Weschtsahara');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Äritreea');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Schpanie');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Äzioopie');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finnland');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fitschi');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Falkland-Insle');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikroneesie');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Färöer');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Frankriich');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabun');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Veräinigts Chönigriich');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenada');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Geoorgie');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Französisch-Guäjaana');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Gäärnsi');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Gaana');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Gibraltar');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Gröönland');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambia');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Gineea');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadälup');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Äquatoriaalgineea');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Griecheland');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'Süüdgeorgie und d’süüdlichi Sändwitsch-Insle');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatemaala');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Gineea-Bissau');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guäjaana');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Sonderverwaltigszone Hongkong');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Höörd- und MäcDonald-Insle');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduras');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Kroaazie');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haiti');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Ungarn');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indoneesie');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Irland');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Israel');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Insle vo Män');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Indie');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Britischs Territoorium im Indische Oozean');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Iraak');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Iraan');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Iisland');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Itaalie');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Dschörsi');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Dschamäika');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jordaanie');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japan');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Keenia');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirgiisischtan');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kambodscha');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribaati');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komoore');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'St. Kitts und Niuwis');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Demokraatischi Volksrepublik Koreea');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Republik Koreea');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kuwäit');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Käimän-Insle');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kasachschtan');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laaos');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Libanon');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Sankta Lutschiia');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Liächteschtäi');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Schri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Libeeria');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesooto');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Littaue');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luxemburg');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Lettland');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Lüübie');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Marokko');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monaco');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Republik Moldau');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Monteneegro');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'St. Martin');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagaschkar');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Marshallinsle');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Mazedoonie');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Maali');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Müanmar');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongolei');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Sonderverwaltigszone Macao');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Nördlichi Mariaane');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martinigg');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mauretaanie');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Moosörrat');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Mauriizius');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Malediiwe');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malaawi');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mexiko');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malaisia');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mosambik');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namiibia');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Nöikaledoonie');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Niger');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Norfolk-Insle');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nigeeria');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nicaraagua');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Niderland');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Norweege');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Neepal');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Nöiseeland');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Omaan');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Peru');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Französisch-Polineesie');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papua-Neuguinea');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Philippiine');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakischtan');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Poole');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'St. Pierr und Miggelo');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitggäärn');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Puerto Riggo');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Paläschtinänsischi Gebiet');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portugal');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguai');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Ggatar');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Reünioon');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Rumäänie');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Särbie');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Russischi Föderazioon');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ruanda');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Saudi-Araabie');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Salomoone');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Seischälle');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudan');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Schweede');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapuur');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'St. Helena');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Sloweenie');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Svalbard und Jaan Määie');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slowakäi');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Sierra Leoone');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'San Mariino');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegal');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somaalia');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Surinam');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sao Tome und Prinssipe');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'El Salvador');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Süürie');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Swasiland');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Törks- und Gaiggos-Insle');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Tschad');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Französischi Süüd- und Antarktisgebiet');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Toogo');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Thailand');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tadschikischtan');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Oschttimor');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turkmeenischtan');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tuneesie');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Türggei');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad und Tobaago');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taiwan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tansaniia');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukraiine');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uganda');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'Amerikanisch-Ozeaanie');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Veräinigti Schtaate');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruguay');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Uschbeekischtan');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikanstadt');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Sankt Wässä und d’Grönadiine');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezueela');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Britischi Jungfere-Insle');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Amerikaanischi Jungfere-Insle');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Wietnam');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Wanuatu');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis und Futuuna');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samooa');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Jeeme');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Majott');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Süüdafrika');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Sambia');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Simbabwe');
INSERT INTO "country" ("id", "name") VALUES ('ZZ', 'Unbekannti oder ungültigi Regioon');
