CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afganistan');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Afrika Erdiko Errepublika');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Aland Uharteak');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albania');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Alemania');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Aljeria');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Amerikar Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Ameriketako Estatu Batuak');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andorra');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Angila');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Antartika');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigua eta Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Arabiar Emirrerri Batuak');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argentina');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armenia');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'Ascension Uhartea');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Australia');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Austria');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azerbaijan');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamak');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrain');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladesh');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbados');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belgika');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benin');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Bhutan');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Bielorrusia');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Birjina uharte amerikarrak');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Birjina uharte britainiarrak');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Birmania');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Boli Kosta');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolibia');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosnia-Herzegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'Bouvet Uhartea');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brasil');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgaria');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Cabo Verde');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'Ceuta eta Melilla');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Christmas uhartea');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'Cocos uharteak');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Cook uharteak');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Costa Rica');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Danimarka');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Djibuti');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominika');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Dominikar Errepublika');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Egipto');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Ekialdeko Timor');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ekuador');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Ekuatore Ginea');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'El Salvador');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritrea');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Erresuma Batua');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Errumania');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Errusia');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Eslovakia');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Eslovenia');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Espainia');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'Estatu Batuetatik urruti dauden uharte txikiak');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estonia');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Etiopia');
INSERT INTO `country` (`id`, `name`) VALUES ('EU', 'Europar Batasuna');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Faroe Uharteak');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fiji');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filipinak');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finlandia');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Frantzia');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'Frantziaren Lurralde Australak');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabon');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Georgia');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ghana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Gibraltar');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Ginea');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Ginea-Bissau');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Grezia');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Groenlandia');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Guadalupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guam');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Guatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'Guernsey');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Guyana Frantsesa');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'Heard eta McDonald Uharteak');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Hego Korea');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Hegoafrika');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'Hegoaldeko Georgia eta Hegoaldeko Sandwich uharteak');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Herbehereak');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Holandarren Antillak');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Hungaria');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'India');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Indiako Ozeanoko Britainiar Lurraldea');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonesia');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Ipar Korea');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Iparraldeko Mariana uharteak');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Irak');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iran');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irlanda');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Islandia');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Israel');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italia');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaika');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japonia');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'Jersey');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordania');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Kaiman Uharteak');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Kaledonia Berria');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kamerun');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'Kanariak');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kanbodia');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Katar');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazakhstan');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenia');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirgizistan');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolonbia');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Komoreak');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Kongoko Errepublika Demokratikoa');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Kroazia');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kuba');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuwait');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laos');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Letonia');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libano');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberia');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libia');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Liechtenstein');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Lituania');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Luxenburgo');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagaskar');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Makau');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malasia');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldivak');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Malvinak');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'Man uhartea');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Maroko');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Marshall uharteak');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinika');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauritania');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Maurizio');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayotte');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Mazedonia');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Mendebaldeko Sahara');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Mexiko');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikronesia');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldavia');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monako');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongolia');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambike');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'Mugaz kanpoko Ozeania');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibia');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepal');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Niger');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigeria');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikaragua');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Norfolk uhartea');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norvegia');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Palestina');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papua Ginea Berria');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paraguai');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitcairn uharteak');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Polinesia Frantsesa');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Polonia');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portugal');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Puerto Rico');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Reunion');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Ruanda');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Saint Helena');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Saint Kitts eta Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'Saint Martin');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Saint Vincent eta Grenadinak');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Saint-Pierre eta Mikelune');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Salomon uharteak');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'San Bartolome');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Santa Luzia');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Sao Tome eta Principe');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Saudi Arabia');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegal');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Serbia');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Serbia eta Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seychelleak');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sierra Leona');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapur');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Siria');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somalia');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudan');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Suedia');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Suitza');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Surinam');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Svalbard eta Jan Mayen uharteak');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Swazilandia');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tadjikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Tailandia');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzania');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad eta Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunisia');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Turk eta Caicos uharteak');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Turkia');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Txad');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Txekiar errepublika');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Txile');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Txina');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukraina');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Uruguai');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzbekistan');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatikano Hiria');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vietnam');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis eta Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Yemen');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambia');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Zeelanda Berria');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Zipre');
