CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'অস্ট্রিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'অস্ট্রেলিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'অ্যাসসেনশন আইল্যান্ড');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'আইভরি কোস্ট');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'আইসলণ্ড');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'আউটলাইনিং ওসানিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'আজারবাইজান');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'আফগানিস্তান');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'আমেরিকান সামোয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'আয়ার্লণ্ড');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'আরুবা');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'আর্জেণ্টাইনা');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'আর্মেনিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'আলব্যানিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'আলান্ড দ্বীপপুঞ্জ');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'ইউক্রেইন');
INSERT INTO `country` (`id`, `name`) VALUES ('EU', 'ইউরোপীয় ইউনিয়ন');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'ইকুয়েডর');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'ইতালী');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'ইন্দোনেশিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'ইফিওপিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'ইমেন');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'ইরাক');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'ইরান');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'ইরিত্রিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'ইস্রায়েল');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'উগান্ডা');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'উজ্বেকিস্থান');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'উত্তর কোরিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'উত্তরাঞ্চলীয় মারিয়ানা দ্বীপপুঞ্জ');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'উরুগোয়ে');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'এন্টার্কটিকা');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'এন্টিগুয়া ও বারবুডা');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'এল সালভেদর');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'এলজিরিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'এস্তোনিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'এ্যাঙ্গুইলা');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'এ্যাঙ্গোলা');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'এ্যান্ডোরা');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'ওমান');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'ওয়ালিস ও ফুটুনা');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'কঙ্গো');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'কঙ্গো - কিনসাসা');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'কমোরোস');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'কাজাকস্থান');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'কাতার');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'কানাডা');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'কাম্বোজ');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'কিউবা');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'কিরিবাতি');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'কির্গিজিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'কুউটা এবং মেলিলা');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'কুক দ্বীপপুঞ্জ');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'কুয়েত');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'কেনিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'কেপভার্দে');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'কেম্যান দ্বীপপুঞ্জ');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'কোকোস দ্বীপপুঞ্জ');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'কোলোম্বিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'কোস্টারিকা');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'ক্যানারি দ্বীপপুঞ্জ');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'ক্যামেরুন');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'ক্রিসমাস দ্বীপ');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'ক্রোয়েশিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('CP', 'ক্লিপারটন আইল্যান্ড');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'গাম্বিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'গিনি');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'গিনি-বিসাউ');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'গিয়ানা');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'গুয়াদেলৌপ');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'গুয়াম');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'গোয়াটিমালা');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'গ্যাবন');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'গ্রাঞ্জি');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'গ্রীনল্যান্ড');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'গ্রীস্');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'গ্রেটবৃটেন');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'গ্রেনাডা');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'ঘানা');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'চাদ');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'চিলি');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'চীন');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'চেক প্রজাতন্ত্র');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'জর্জিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'জর্ডন');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'জাপান');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'জাম্বিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'জার্মানি');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'জার্সি');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'জিবুতি');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'জিব্রাল্টার');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'জিম্বাবুয়ে');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'জ্যামেকা');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'টিউনিস্');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'টুভালু');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'টোকেলাউ');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'টোগো');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'টোঙ্গা');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'ট্রিস্টান ডা কুনা');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'ডেনমার্ক');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'ডোমিনিকা');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'ডোমেনিকান প্রজাতন্ত্র');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'তাইওয়ান');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'তাজিকস্থান');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'তাঞ্জানিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'তুরস্ক');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'তুর্কমেনিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'তুর্কস ও কাইকোস দ্বীপপুঞ্জ');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'ত্রিনিনাদ ও টোব্যাগো');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'থাই');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'দক্ষিণ আফ্রিকা');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'দক্ষিণ কোরিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'দক্ষিণ জর্জিয়া ও দক্ষিণ স্যান্ডউইচ দ্বীপপুঞ');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'দিয়েগো গার্সিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'নরওয়ে');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'নাইজার');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'নাইজেরিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'নাউরু');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'নামিবিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'নিউ ক্যালেডোনিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'নিউ জিলণ্ড');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'নিউয়ে');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'নিকারাগুয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'নিরক্ষীয় গিনি');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'নিরফোক দ্বীপ');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'নেদারল্যান্ডস এ্যান্টিলিস');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'নেপাল');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'পর্তুগাল');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'পশ্চিমী সাহারা');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'পাকিস্তান');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'পানামা');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'পাপুয়া নিউ গিনি');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'পালাউ');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'পিটকেয়ার্ন');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'পিরু');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'পুয়ের্টোরিকো');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'পূর্ব-তিমুর');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'পোল্যাণ্ড');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'প্যারাগোয়ে');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'ফকল্যান্ড দ্বীপপুঞ্জ');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'ফরাসী গায়ানা');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'ফরাসী দক্ষিণাঞ্চল');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'ফরাসী পলিনেশিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'ফিজি');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'ফিন্ল্যাণ্ড');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'ফিলিপাইন');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'ফিলিস্তিন অঞ্চল');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'ফ্যারও দ্বীপপুঞ্জ');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'ফ্রান্স');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'বতসোয়ানা');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'বসনিয়া ও হার্জেগোভিনা');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'বাংলাদেশ');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'বারবাদোস');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'বারমুডা');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'বাহরাইন');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'বাহামা দ্বীপপুঞ্জ');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'বুরকিনা ফাসো');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'বুরুন্ডি');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'বুলগেরিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'বেনিন');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'বেলজিয়াম');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'বেলিয');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'বেলোরুশিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'বোভেট দ্বীপ');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'বোলিভিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'ব্রাজিল');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'ব্রিটিশ ভারত মহাসাগরীয় অঞ্চল');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'ব্রিটিশ ভার্জিন দ্বীপপুঞ্জ');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'ব্রুনেই');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'ভানুয়াটু');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'ভারত');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'ভিয়েতনাম');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'ভুটান');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'ভেনেজুয়েলা');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'ভ্যাটিকান সিটি');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'মক্সিকো');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'মঙ্গোলিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'মধ্য আফ্রিকান প্রজাতন্ত্র');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'মন্টসেরাট');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'মন্টিনিগ্রো');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'মরিতানিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'মরিশাস');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'মাইক্রোনেশিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'মাদাগাস্কার');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'মায়ানমার');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'মায়োত্তে');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'মার্কিন ভার্জিন দ্বীপপুঞ্জ');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'মার্কিন যুক্তরাষ্ট্র');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'মার্টিনিক');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'মার্শাল দ্বীপপুঞ্জ');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'মালদ্বীপ');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'মালাউই');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'মালি');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'মাল্টা');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'মাল্যাশিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'মিশর');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'মোজাম্বিক');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'মোনাকো');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'মোরক্কো');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'মোল্দাভিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'ম্যাকাও এসএআর চীনা');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'ম্যানদ্বীপ');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'ম্যাসাডোনিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'যুক্তরাষ্ট্রের ক্ষুদ্র ও পার্শ্ববর্তী দ্বীপপুঞ্জ');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'রাশিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'রিইউনিয়ন');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'রুমানিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'রুয়ান্ডা');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'লাইবেরিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'লাওস');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'লাক্সেমবার্গ');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'লাত্ভিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'লিচেনস্টেইন');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'লিত্ভা');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'লিবিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'লেবানন');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'লেসোথো');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'শ্রীলঙ্কা');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'শ্লোভাকিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'সংযুক্ত আরব আমিরাত');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'সলোমন দ্বীপপুঞ্জ');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'সাইপ্রাস');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'সাউদি আরব');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'সাওটোমা ও প্রিন্সিপি');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'সান মারিনো');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'সামোয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'সারবিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'সারবিয়ান এবং মন্টেনিগ্রো');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'সিঙ্গাপুর');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'সিয়েরালিওন');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'সিরিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'সিসিলি');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'সুইজর্লণ্ড');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'সুইডেন');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'সুদান');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'সুরিনাম');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'সেনেগাল');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'সেন্ট কিটস ও নেভিস');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'সেন্ট পিয়ের ও মিকুয়েলন');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'সেন্ট বারথেলিমি');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'সেন্ট ভিনসেন্ট ও দ্যা গ্রেনাডিনস');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'সেন্ট মার্টিন');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'সেন্ট লুসিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'সেন্ট হেলেনা');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'সোমালি');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'সোয়াজিল্যান্ড');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'স্পেন');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'স্বালবার্ড ও জান মেয়েন');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'স্লোভানিয়া');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'হংকং এসএআর চীনা');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'হণ্ডুরাস');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'হলণ্ড');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'হাইতি');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'হাঙ্গেরি');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'হার্ড দ্বীপ এবং ম্যাকডোনাল্ড দ্বীপপুঞ্জ');
