CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'Aßension');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andorra');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Vereinschte Arrabesche Emmirate');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afjaanistahn');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigwa un Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Anggwilla');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albaanije');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Arrmeenije');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Nederlängsche Antille');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angjoola');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Södpol');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Ajjentiinije');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Ammerikaanesch Sammoha');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Öösterisch');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Austraalije');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Ohland-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Asserbaidschahn');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Boßnije');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Ensel Barbados');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladesch');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Bellje');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Bukkinna-Faase');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulljaarije');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bachrain');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benin');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'de Zint Battälmi-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermudas');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolliivije');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brasilije');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamas');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Buttaan');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'Buvee-Ensel');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Bozwaana');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Wießrußland');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kannada');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'Kokkos-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Konggo-Kinshasa');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Zetraalaffrikanesche Republik');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Konggo (Brassavill)');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Schweiz');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Älfebeijn-Köß');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Kuuk-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Schiile');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kammeruhn');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Schiina');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolumbije');
INSERT INTO `country` (`id`, `name`) VALUES ('CP', 'Klipperton-Ensel');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Kostarika');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kuba');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Kapvärdesche Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Weihnaachs-Ensel');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Züppere');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Tschäschei');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Doütschland');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'Diego-Garcia-Ensel');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Dschibutti');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Dänemark');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominnika');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Dommenekaanesche Reppublik');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Alljeerije');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'Ze\'uta un Meliija');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Äkwador');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Äßland');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Äjüpte');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Wäß-Sahara');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Äritreja');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Schpaanije');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Ättijoopije');
INSERT INTO `country` (`id`, `name`) VALUES ('EU', 'Eurppäesche Unijon');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finnland');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fischei-Endelle');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Falkland-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikroneesije');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Färrör-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Frankrisch');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Jabuhn');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Jruußbrettannije');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Jrenaada');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Jeorrjije');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Franzüüsesch Jujaana');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'Jöönsei');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Jaana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Jibralltaa');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Jröhnland');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Jambija');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Jinneha');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Juadelupp');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Äquatorial Jineeja');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Jriescheland');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'Söd-Jeorjie un de södlijje Botteramms-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Juwatemaala');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Juham');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Jinneha_Bißau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Jujaana');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'Hong-Kong');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'de Heart Ensel un de McDonal-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Krowazije');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Ha\'itti');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Unjann');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'Kannaresche Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indoneesije');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irrland');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Ißraäl');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'Ensel Män');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Indije');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Brettesche Besezunge em indesche Oozejahn');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Irak');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Persije');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Ißland');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Itaalije');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'Jööseh');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jammaika');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordaanija');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japan');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Keenija');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirrjiisije');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambodscha');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Kommoore');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Zimt Kitts un Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Nood-Koreja');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Söd-Koreja');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuweit');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Kaiman-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kassakstahn');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'La\'os');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libbannon');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Zint-Lutscha-Ensel');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Lischtestein');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Libeerija');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesooto');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Lizzaue');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Luxembursch');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Lätland');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libbija');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Marokko');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monakko');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldaavije');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Monteneejro');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'Sint-Määtes-Ensel');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Maddajaska');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Machschall-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Mazedoonije');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Maali');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Birma');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongjolei');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Makau');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'de nöödlijje Marijanne-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Machtinik');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mautitaanije');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Mongßerrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Maurizijus');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Mallediive');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Mexico');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malaisije');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mosambik');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namiibije');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Neuschottland');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Nijer');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Noofok-Ensel');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nikaraagua');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikaraaguwa');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Nederläng');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norrweeje');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepall');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Neuseeland');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Pannama');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Perruh');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Franzüüsesch Pollineesije');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papuwa Neujineeja');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Fillipiine');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistahn');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Pole');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Zint Pjäär un Mikelong');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitkärn-Ensel');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Pochtoriko');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Palästina');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Pochtojall');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Pallau');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Parraguwai');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Kataa');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'Ozejaanije ußerhallef');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Rehunjohn');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romäänije');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Serbije');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Rußland');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Ruanda');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Saudi Arraabije');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'de Solomone-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seischälle');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudan');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Schweede');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singjapuur');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Sint-Hellena-Ensel');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'ßloveenije');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'de Enselle Svalbard un Jan Mayen');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'ßlovakei');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sjärra Lejone');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San-Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Sennejall');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somaalije');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Sürinamm');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Zint Tommeh un Printschipe');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Äl Slavadoor');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Sürije');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'ßwaasiland');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'Tristan da Cunja');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Turks un Kaikos Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Tschad');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'Franzüüsesche Södsee-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Toojo');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Tailand');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tadschikistahn');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Oß-Timor');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenistahn');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tuneesije');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tongga');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Türkei');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad un Tobääjo');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tansanija');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukra\'iine');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Ujanda');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'De Vereineschte Schtaate vun Amärrika ier klein Enselsche ußerhallef');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Vereineschte Schtaate vun Ammärrika');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Urruguwai');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Ußbeekistahn');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vattikahn');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Zint Vinzänz un de Jrenadines-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Brettesche Juffer-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Ammärrikahnesche Juffer-Enselle');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vijätnamm');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis un Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Sammoha');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Jämmen');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Majott');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Södaffrika');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Sambija');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Simbabwe');
INSERT INTO `country` (`id`, `name`) VALUES ('ZZ', 'Jääjend onbikannt');
