CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afganujo');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albanujo');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Alĝerio');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andoro');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angolo');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Angvilo');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Antarkto');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigvo-Barbudo');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argentino');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armenujo');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Arubo');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Aŭstralio');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Aŭstrujo');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azerbajĝano');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamoj');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladeŝo');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbado');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Barejno');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Belaŭo');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belgujo');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belizo');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Belorusujo');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benino');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermudoj');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Bocvano');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolivio');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosnio-Hercegovino');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brazilo');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Brita Hindoceana Teritorio');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Britaj Virgulininsuloj');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunejo');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgarujo');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkino');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundo');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Butano');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Centr-Afrika Respubliko');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Ĉado');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Ĉeĥujo');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Ĉilio');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Ĉinujo');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Danujo');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Domingo');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominiko');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Ebur-Bordo');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Egipto');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ekvadoro');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Ekvatora Gvineo');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritreo');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estonujo');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Etiopujo');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Ferooj');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fiĝoj');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filipinoj');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finnlando');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Franca Gviano');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Franca Polinezio');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Francujo');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabono');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambio');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ganao');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Germanujo');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Grekujo');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenado');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Gronlando');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Gujano');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Gvadelupo');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Gvamo');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Gvatemalo');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Gvineo');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Gvineo-Bisaŭo');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Ĝibraltaro');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Ĝibutio');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haitio');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'Herda kaj Makdonaldaj Insuloj');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Hindujo');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Hispanujo');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduro');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Hungarujo');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonezio');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Irako');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Irano');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irlando');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Islando');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Israelo');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italujo');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamajko');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japanujo');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Jemeno');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordanio');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Kabo-Verdo');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kamboĝo');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kameruno');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanado');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Kartvelujo');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Kataro');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazaĥstano');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Kejmanoj');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenjo');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Kipro');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirgizistano');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribato');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolombio');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Komoroj');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongolo');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Kostariko');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Kroatujo');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kubo');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Kukinsuloj');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuvajto');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laoso');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Latvujo');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesoto');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libano');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberio');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libio');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Liĥtenŝtejno');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Litovujo');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Luksemburgo');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagaskaro');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Majoto');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Makedonujo');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malajzio');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malavio');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldivoj');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Malio');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malto');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Maroko');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Marŝaloj');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martiniko');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Maŭricio');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Maŭritanujo');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Meksiko');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikronezio');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Mjanmao');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldavujo');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monako');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongolujo');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambiko');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibio');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauro');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Nederlandaj Antiloj');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Nederlando');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepalo');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Niĝerio');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Niĝero');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikaragvo');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niuo');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Nord-Koreo');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Nord-Marianoj');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Norfolkinsulo');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norvegujo');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Nov-Kaledonio');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Nov-Zelando');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Okcidenta Saharo');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Omano');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistano');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panamo');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papuo-Nov-Gvineo');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paragvajo');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peruo');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitkarna Insulo');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Pollando');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portugalujo');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Puerto-Riko');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Reunio');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Ruando');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Rumanujo');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Rusujo');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Salomonoj');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Salvadoro');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoo');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San-Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Sao-Tomeo kaj Principeo');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Saŭda Arabujo');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Sejŝeloj');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegalo');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Sent-Heleno');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Sent-Kristofo kaj Neviso');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Sent-Lucio');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Sent-Piero kaj Mikelono');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Sent-Vincento kaj la Grenadinoj');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Siera-Leono');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapuro');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Sirio');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Slovakujo');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Slovenujo');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somalujo');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sri-Lanko');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Sud-Afriko');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'Sud-Georgio kaj Sud-Sandviĉinsuloj');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Sud-Koreo');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudano');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Surinamo');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Svalbardo kaj Jan-Majen-insulo');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Svazilando');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Svedujo');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Svisujo');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Taĝikujo');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Tajlando');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Tajvano');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzanio');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togolo');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tongo');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidado kaj Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunizio');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenujo');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Turkujo');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalo');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Ugando');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukrajno');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Unuiĝinta Reĝlando');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Unuiĝintaj Arabaj Emirlandos');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Urugvajo');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'Usonaj malgrandaj insuloj');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Usonaj Virgulininsuloj');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Usono');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzbekujo');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Valiso kaj Futuno');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatuo');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatikano');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuelo');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vjetnamo');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambio');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabvo');
