CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY("id"));

INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andora');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Falme dha Kiarabu');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afuganistani');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua na Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anguilla');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albania');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armenia');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Antili za Uholandhi');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Ajentina');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Thamoa ya Marekani');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Authtria');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Authtralia');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Adhabajani');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bothnia na Hedhegovina');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Babadothi');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladeshi');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Ubelgiji');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Bukinafatho');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulgaria');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahareni');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benini');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermuda');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brunei');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brazili');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahama');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Butani');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botthwana');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Belaruthi');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belidhe');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Jamhuri ya Kidemokrathia ya Kongo');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Jamhuri ya Afrika ya Kati');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Uthwithi');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Kodivaa');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Vithiwa vya Cook');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Chile');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kameruni');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'China');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolombia');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kothtarika');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Therbia na Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kuba');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Kepuvede');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Kuprothi');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Jamhuri ya Cheki');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Ujerumani');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Jibuti');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Denmaki');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominika');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Jamhuri ya Dominika');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Aljeria');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekwado');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Ethtonia');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Mithri');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritrea');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Hithpania');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Uhabeshi');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Ufini');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fiji');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Vithiwa vya Falkland');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikronethia');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Ufarantha');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gaboni');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Uingeredha');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenada');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Jojia');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Gwiyana ya Ufarantha');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Ghana');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Jibralta');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Grinlandi');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambia');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Gine');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Gwadelupe');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Ginekweta');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Ugiriki');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Gwatemala');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Gwam');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Ginebisau');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guyana');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Hondurathi');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Korathia');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haiti');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Hungaria');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indonethia');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Ayalandi');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Ithraeli');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'India');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Ieneo la Uingeredha katika Bahari Hindi');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Iraki');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Uajemi');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Aithlandi');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Italia');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamaika');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Yordani');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japani');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenya');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirigizithtani');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kambodia');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komoro');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Thantakitdhi na Nevith');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Korea Kathkazini');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Korea Kuthini');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kuwaiti');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Vithiwa vya Kayman');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazakithtani');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laothi');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Lebanoni');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Thantaluthia');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Lishenteni');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Thirilanka');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberia');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lethoto');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Litwania');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Lathembagi');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Lativia');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libya');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Moroko');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monako');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldova');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Bukini');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Vithiwa vya Marshal');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Mathedonia');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Myama');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongolia');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Vithiwa vya Mariana vya Kathkazini');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martiniki');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Moritania');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Monttherrati');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Morithi');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Modivu');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malawi');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mekthiko');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malethia');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mthumbiji');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibia');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Nyukaledonia');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Nijeri');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Kithiwa cha Norfok');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nijeria');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikaragwa');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Uholandhi');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Norwe');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepali');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Nyudhilandi');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Omani');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Peru');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Polinesia ya Ufarantha');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papua');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filipino');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakithtani');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Polandi');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Thantapieri na Mikeloni');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitkairni');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Pwetoriko');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palestina');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Ureno');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paragwai');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Katari');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Riyunioni');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Romania');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Uruthi');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Rwanda');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Thaudi');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Vithiwa vya Tholomon');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Shelisheli');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Thudani');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Uthwidi');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Thingapoo');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Thantahelena');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Thlovenia');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Tholvakia');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Thiera Leoni');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'Thamarino');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Thenegali');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Thomalia');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Thurinamu');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Thao Tome na Principe');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Elsavado');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Thiria');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Uthwadhi');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Vithiwa vya Turki na Kaiko');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Chadi');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Tailandi');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tajikithtani');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Timori ya Mashariki');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turukimenithtani');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunithia');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Uturuki');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad na Tobago');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taiwani');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tadhania');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uganda');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Marekani');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Urugwai');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Udhibekithtani');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikani');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Thantavithenti na Grenadini');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezuela');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Vithiwa vya Virgin vya Uingeredha');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Vithiwa vya Virgin vya Marekani');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vietinamu');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Walith na Futuna');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Thamoa');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Yemeni');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayotte');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Afrika Kuthini');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Dhambia');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Dhimbabwe');
