CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Австралия');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Австрия');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Азербайжан');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'АКШнын сырткы аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Аланд аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Албания');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Алжир');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Америка Кошмо Штаттары');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Америка Самоасы');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Ангола');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Ангуила');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Андорра');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Антарктика');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Антигуа жана Барбуда');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Аргентина');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Армения');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Аруба');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Ассеншин аралы');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Афганистан');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Багам аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Бангладеш');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Барбадос');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Батыш Сахара');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Бахрейн');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Беларусь');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Белиз');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Бельгия');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Бенин');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Бермуд аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Бириккен Араб Эмираттары');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Болгария');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Боливия');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Борбордук Африка Республикасы');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Босния жана Герцеговина');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Ботсвана');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Бразилия');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Британиянын Индия океанындагы аймагы');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Бруней');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Буркина-Фасо');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Бурунди');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Бутан');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Вануату');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Ватикан');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Венгрия');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Венесуэла');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Виргин аралдары (АКШ)');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Виргин аралдары (Британия)');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Вьетнам');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Габон');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Гаити');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Гайана');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Гамбия');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Гана');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Гваделупа');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Гватемала');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Гвиана (Франция)');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Гвинея');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Гвинея-Бисау');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Германия');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Гернси');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Гибралтар');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Гондурас');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Гонконг Кытай ААА');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Гренада');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Гренландия');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Греция');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Грузия');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Гуам');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Дания');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Джибути');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Диего Гарсия');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Доминика');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Доминика Республикасы');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Египет');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Жаӊы Зеландия');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Жаӊы Каледония');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Жерси');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Замбия');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Зимбабве');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Израиль');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Индия');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Индонезия');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Иордания');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Ирак');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Иран');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Ирландия');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Исландия');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Испания');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Италия');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Йемен');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Казакстан');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Кайман Аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Камбоджа');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Камерун');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Канада');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Канар аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Капе Верде');
INSERT INTO [country] ([id], [name]) VALUES ('BQ', 'Кариб Нидерланддары');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Катар');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Кения');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Кипр');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Кирибати');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Кокос (Килиӊ) аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Колумбия');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Коморос');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Конго-Браззавил');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Конго-Киншаса');
INSERT INTO [country] ([id], [name]) VALUES ('XK', 'Косово');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Коста-Рика');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Кот-д’Ивуар');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Крисмас аралы');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Куба');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Кувейт');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Кук аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Кыргызстан');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Кытай');
INSERT INTO [country] ([id], [name]) VALUES ('CW', 'Кюрасао');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Лаос');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Латвия');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Лесото');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Либерия');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Ливан');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Ливия');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Литва');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Лихтенштейн');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Люксембург');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Маврикий');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Мавритания');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Мадагаскар');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Майотта');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Макау Кытай ААА');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Македония');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Малави');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Малайзия');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Малдив аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Мали');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Мальта');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Марокко');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Мартиника');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Маршалл аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Мексика');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Микронезия');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Мозамбик');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Молдова');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Монако');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Монголия');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Монсеррат');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Мьянма (Бирма)');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Мэн аралы');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Намибия');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Науру');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Непал');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Нигер');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Нигерия');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Нидерланддар');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Никарагуа');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Ниуэ');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Норвегия');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Норфолк аралы');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Оман');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Өзбекстан');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Пакистан');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Палау');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Палестина аймактары');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Панама');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Папуа Жаңы-Гвинея');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Парагвай');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Перу');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Питкэрн аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Польша');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Португалия');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Пуэрто-Рико');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Реюнион');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Россия');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Руанда');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Румыния');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Самоа');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'Сан Марино');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Сан-Томе жана Принсипи');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Сауд Арабиясы');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Свазиленд');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Свалбард жана Жан Майен');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Сейшелдер');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Сен-Пьер жана Микелон');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Сенегал');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Сент Бартелеми');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Сент-Винсент жана Гренадиналар');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Сент-Китс жана Невис');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Сент-Люсия');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Сент-Мартин');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Сербия');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Сеута жана Мелилла');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Сингапур');
INSERT INTO [country] ([id], [name]) VALUES ('SX', 'Синт Маартен');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Сирия');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Словакия');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Словения');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Соломон аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Сомали');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Судан');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Суринаме');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Сьерра-Леоне');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Тажикстан');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Таиланд');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Тайвань');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Танзания');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Тимор-Лесте');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Того');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Токелау');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Тонга');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Тринидад жана Тобаго');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Тристан да Кунья');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Тувалу');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Тунис');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Түндүк Корея');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Түндүк Мариана аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Түркия');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Түркмөнстан');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Түркс жана Кайкос аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Түштүк Африка Республикасы');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Түштүк Жоржия жана Түштүк Сэндвич аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Түштүк Корея');
INSERT INTO [country] ([id], [name]) VALUES ('SS', 'Түштүк Судан');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Уганда');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Украина');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Улуу Британия');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Уоллис жана Футуна');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Уругвай');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Фарер аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Фиджи');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Филлипин');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Финляндия');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Фолклэнд аралдары');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Франция');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Франциянын Түштүктөгү аймактары');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Француз Полинезиясы');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Хорватия');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Чад');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Черногория');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Чехия');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Чили');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Швейцария');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Швеция');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Шри-Ланка');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Ыйык Елена');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Эквадор');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Экваториалдык Гвинея');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Эл Салвадор');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Эритрея');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Эстония');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Эфиопия');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Ямайка');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Япония');
