CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'andura');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'limarat');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'afɣanistan');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'antiga d brbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'angila');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'albanya');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'arminya');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'antiy n hulanda');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'angula');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'arjantin');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'samwa tamirikanit');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'nnmsa');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'ustralya');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'adrabijan');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'busna d hirsik');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'barbad');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'bangladic');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'bljika');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'burkina fasu');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'blɣara');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'bḥrayn');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'binin');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'brmuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'bruni');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'bulibya');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'brazil');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'bahamas');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'bhutan');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'butswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'bilarusya');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'biliz');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'tagdudant tadimukratit n Kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'tagdudant tanammast n ifriqya');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'kungu');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'swisra');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'kut difwar');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'tigzirin n kuk');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'ccili');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'kamirun');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'ccinwa');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'culumbya');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'kusta rika');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'sirbya d muntinigru');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'kuba');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'tigzirin n kabbirdi');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'qubrus');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'tagdudant tatcikit');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'almanya');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'djibuti');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'danmark');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'duminik');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'tagdudant taduminikt');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'dzayr');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'ikwadur');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'istunya');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'miṣṛ');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'iritirya');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'sbanya');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'ityubya');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'fillanda');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'fidji');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'tigzirin n malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'mikrunizya');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'fransa');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'gabun');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'tagldit imunn');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'ɣrnaṭa');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'jurjya');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'gwiyan tafransist');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'ɣana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'adrar n ṭaṛiq');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'griland');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'gambya');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'ɣinya');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'gwadalub');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'ɣinya n ikwadur');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'lyunan');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'gwatimala');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'gwam');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'ɣinya bisaw');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'gwiyana');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'hunduras');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'krwatya');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'hayti');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'hnɣarya');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'andunisya');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'irlanda');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'israyil');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'lhind');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'tamnaḍt tanglizit n ugaru ahindi');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'lɛiraq');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'iran');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'island');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'iṭalya');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'jamayka');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'lurdun');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'lyaban');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'kinya');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'kirɣizistan');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'kambudya');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'cumur');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'sankris d nifis');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'kurya n iẓẓlmḍ');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'kurya n iffus');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'lkwit');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'tigzirin n kayman');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'kazaxstan');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'laws');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'lubnan');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'santlusi');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'likinctayn');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'srilanka');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'libirya');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'liṣuṭu');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'litwanya');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'luksanburg');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'latfya');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'libya');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'lmɣrib');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'munaku');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'muldufya');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'madaɣacqar');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'tigzirin n marcal');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'masidunya');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'myanmar');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'mnɣulya');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'tigzirin n maryan n iẓẓlmḍ');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'martinik');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'muṛiṭanya');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'munsirat');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'malṭa');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'muris');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'maldif');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'miksik');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'malizya');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'muznbiq');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'namibya');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'kalidunya tamaynut');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'nnijir');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'tigzirin n nurfulk');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'nijirya');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'nikaragwa');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'hulanda');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'nnrwij');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'nibal');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'nawru');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'niwi');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'nyuzilanda');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'ɛuman');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'banama');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'biru');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'bulinizya tafransist');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'babwa ɣinya tamaynut');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'filibbin');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'bakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'bulunya');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'sanbyir d miklun');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'bitkayrn');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'burtu riku');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'agmmaḍ n tagut d ɣzza');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'bṛṭqiz');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'balaw');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'baragway');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'qatar');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'riyunyun');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'rumanya');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'rusya');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'rwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'ssaɛudiya');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'tigzirin n saluman');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'ssicil');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'ssudan');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'sswid');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'snɣafura');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'santilin');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'slufinya');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'slufakya');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'ssiralyun');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'sanmarinu');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'ssinigal');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'ṣṣumal');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'surinam');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'sawṭumi d bransib');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'salfadur');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'surya');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'swazilanda');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'tigzirin n turkya d kayk');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'tcad');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'ṭugu');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'ṭayland');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'tadjakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'ṭuklaw');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'timur n lqblt');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'turkmanstan');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'tuns');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'ṭunga');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'turkya');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'trinidad d ṭubagu');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'tufalu');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'ṭaywan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'ṭanẓanya');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'ukranya');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'uɣanda');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'iwunak munnin n mirikan');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'urugway');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'uzbakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'awank n fatikan');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'sanfansan d grinadin');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'finzwila');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'tigzirin timgad n nngliz');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'tigzirin timgad n iwunak munnin');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'fitnam');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'fanwaṭu');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'walis d futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'samwa');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'yaman');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'mayuṭ');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'afriqya n iffus');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'zambya');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'zimbabwi');
