CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afganistan');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Alandsko otočje');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albanija');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Alžirija');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Ameriška Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Ameriški Deviški otoki');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andora');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Angvila');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Antarktika');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigva in Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Argentina');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armenija');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Avstralija');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Avstrija');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azerbajdžan');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahami');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahrajn');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladeš');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbados');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Belgija');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belize');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Belorusija');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benin');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermudi');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Bocvana');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bolgarija');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolivija');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosna in Hercegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Bouvetov otok');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Božični otok');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brazilija');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Britanski Deviški otoki');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Britansko ozemlje v Indijskem oceanu');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunej');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Butan');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Centralnoafriška republika');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Ceuta in Melilla');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Ciper');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Cookovo otočje');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Čad');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Češka');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Čile');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Črna gora');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Danska');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Demokratična republika Kongo');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Diego Garcia');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominika');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Dominikanska republika');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Druga ameriška ozemlja v Tihem oceanu');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Džibuti');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Egipt');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ekvador');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Ekvatorialna Gvineja');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritreja');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estonija');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiopija');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'Evropska unija');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Falklandski otoki');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Ferski otoki');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fidži');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipini');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finska');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Francija');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Francoska Gvajana');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Francoska Polinezija');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Francosko južno ozemlje');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabon');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambija');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Gana');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Gibraltar');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Grčija');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grenada');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Grenlandija');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Gruzija');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guam');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Guernsey');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Gvadalupe');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Gvajana');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Gvatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Gvineja');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Gvineja Bissau');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haiti');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Honduras');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Hrvaška');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Indija');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonezija');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Irak');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Iran');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Irska');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Islandija');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Italija');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Izrael');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jamajka');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Japonska');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Jemen');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Jersey');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Jordanija');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Južna Georgia in Južni Sandwichevi otoki');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Južna Koreja');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Južnoafriška republika');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Kajmanski otoki');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kambodža');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kamerun');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanada');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Kanarski otoki');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Katar');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazahstan');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenija');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kirgizistan');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Kitajska');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Kokosovi otoki');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolumbija');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Komori');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongo - Brazzaville');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kostarika');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kuba');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuvajt');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laos');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Latvija');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesoto');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Libanon');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberija');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libija');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Lihtenštajn');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Litva');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Luksemburg');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagaskar');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Madžarska');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Makedonija');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malavi');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maldivi');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malezija');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Maroko');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Marshallovi otoki');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martinik');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Mauritius');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mavretanija');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayotte');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mehika');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikronezija');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Mjanmar [Burma]');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldavija');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monako');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongolija');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montserrat');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambik');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibija');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nauru');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Nemčija');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepal');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Niger');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nigerija');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikaragva');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niue');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Nizozemska');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Nizozemski Antili');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Norfolški otok');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norveška');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Nova Kaledonija');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Nova Zelandija');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Oman');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'Ostala oceanija');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Otočji Turks in Caicos');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Otok Ascension');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'Otok Clipperton');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'Otok Heard in otočje McDonald');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Otok Man');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistan');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Palestinsko ozemlje');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papua Nova Gvineja');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paragvaj');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peru');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitcairn');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Poljska');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Portoriko');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portugalska');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Posebno administrativno območje LR Kitajske Hong Kong');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Posebno administrativno območje LR Kitajske Macao');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Reunion');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Romunija');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Ruanda');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rusija');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Saint Barthelemy');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Saint Kitts in Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Saint Lucia');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Saint Martin');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Saint Pierre in Miquelon');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Saint Vincent in Grenadine');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Salomonovi otoki');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Salvador');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marino');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Sao Tome in Principe');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Saudova Arabija');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Sejšeli');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegal');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Severna Koreja');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Severni Marianski otoki');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sierra Leone');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapur');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Sirija');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Slonokoščena obala');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovaška');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slovenija');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somalija');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Srbija');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Srbija in Črna gora');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudan');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinam');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Svalbard in Jan Mayen');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Svazi');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Sveta Helena');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Španija');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Šrilanka');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Švedska');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Švica');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tadžikistan');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Tajska');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Tajvan');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzanija');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidad in Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunizija');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Turčija');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turkmenistan');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukrajina');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Urugvaj');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Uzbekistan');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatikan');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Velika Britanija');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuela');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietnam');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Vzhodni Timor');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wallis in Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Zahodna Sahara');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambija');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Združene države Amerike');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Združeni arabski emirati');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Zelenortski otoki');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabve');
