CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andola');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Dimiliki dya Vakulungwa va Chalabu');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afuganistani');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigua na Balbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Angwila');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albania');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Almenia');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Antili za Uholanzi');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Adyentina');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samoa ya Malekani');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Austlia');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Austlalia');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aluba');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azabadyani');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnia na Hezegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Babadosi');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladeshi');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Ubelgidi');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Buchinafaso');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgalia');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahaleni');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Bulundi');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benini');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Belmuda');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Blunei');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolivia');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Blazili');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahama');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Butani');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswana');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Belalusi');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belize');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanada');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Jamuhuli ya Chidemoklasia ya kuKongo');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Jamuhuli ya Afilika ya Paching''ati');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongo');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Uswisi');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Kodivaa');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Chisiwa cha Cook');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Chile');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kameluni');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'China');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolombia');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kostalika');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Selbia na Monteneglo');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kuba');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Kepuvede');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Kuplosi');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Jamuhuli ya Chechi');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Udyerumani');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Dyibuti');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Denmaki');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominika');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Jamuhuli ya Dominika');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Aljelia');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ekwado');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estonia');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Misli');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Elitilea');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Hispania');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Uhabeshi');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Ufini');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fiji');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Chisiwa cha Falkland');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikilonesia');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Ufalansa');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gaboni');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Nngalesa');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Glenada');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Dyodya');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Gwiyana ya Ufalansa');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ghana');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Diblalta');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Glinlandi');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambia');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Gine');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Gwadelupe');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Ginekweta');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Ugilichi');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Gwatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Gwam');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Ginebisau');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyana');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Hondulasi');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Kolasia');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haiti');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Hungalia');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonesia');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Ayalandi');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Islaeli');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'India');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Lieneo lyaki Nngalesa Nbahali ya Hindi');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Ilaki');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Uadyemi');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Aislandi');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Italia');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Dyamaika');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Yordani');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Dyapani');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenya');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kiligizistani');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kambodia');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kilibati');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Komolo');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Santakitzi na Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Kolea Kasikazini');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Kolea Kusini');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuwaiti');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Chisiwa cha Kemen');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazachistani');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laosi');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Lebanoni');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Santalusia');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Lishenteni');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sililanka');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Libelia');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesoto');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Litwania');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Lasembagi');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Lativia');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libya');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Moloko');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monako');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldova');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Bukini');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Chisiwa cha Malushal');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Masedonia');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myama');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongolia');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Chisiwa cha Marian cha Kasikazini');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Malitiniki');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Molitania');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Monselati');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Molisi');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Modivu');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawi');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Meksiko');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malesia');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Msumbiji');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibia');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Nyukaledonia');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Nidyeli');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Chisiwa cha Nolufok');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nidyelia');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikalagwa');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Uholanzi');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norwe');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepali');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Naulu');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niue');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Nyuzilandi');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Omani');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Pelu');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Polinesia ya Ufalansa');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papua');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipino');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistani');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Polandi');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Santapieli na Mikeloni');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitikeluni');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Pwetoliko');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Nchingu wa Magalibi wa Mpanda wa kuGaza wa kuPales');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Uleno');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Palagwai');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Katali');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Liyunioni');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Lomania');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Ulusi');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Lwanda');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Saudia');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Chisiwa cha Solomon');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Shelisheli');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudani');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Uswidi');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapoo');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Santahelena');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slovenia');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovakia');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Siela Leoni');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'Samalino');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegali');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somalia');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Sulinamu');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Saotome na Prinsipe');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Elsavado');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Silia');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Uswazi');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Chisiwa cha Tuluchi na Kaiko');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Chadi');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Tailandi');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tadikistani');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timoli ya Mashaliki');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Tuluchimenistani');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunisia');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Utuluchi');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Tilinidad na Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwani');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzania');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Uklaini');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Malekani');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Ulugwai');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Uzibechistani');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatikani');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Santavisenti na Glenadini');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuela');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Chisiwa Chivihi cha Wingalesa');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Chisiwa Chivihi cha Malekani');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietinamu');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Walis na Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yemeni');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Maole');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Afilika Kusini');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambia');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabwe');
