CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('SS', 'Gúúsù Sudan');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Orilɛ́ède Dòmíníkánì');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Orilɛ́ède Kóngò');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Orílɛ́ède Agentínà');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Orílɛ́ède Ailandi');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Orílɛ́ède Améníà');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Orílɛ́ède Ariwa Afirika');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Orílɛ́ède Ariwa Kɔria');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Orílɛ́ède Ashilandi');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Orílɛ́ède Asítíríà');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Orílɛ́ède Asɛ́bájánì');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Orílɛ́ède Bàhámásì');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Orílɛ́ède Bàràsílì');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Orílɛ́ède Bábádósì');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Orílɛ́ède Bángáládésì');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Orílɛ́ède Báránì');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Orílɛ́ède Bèlísɛ̀');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Orílɛ́ède Bégíɔ́mù');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Orílɛ́ède Bélárúsì');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Orílɛ́ède Bémúdà');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Orílɛ́ède Bùùgáríà');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Orílɛ́ède Bùùkíná Fasò');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Orílɛ́ède Bùùrúndì');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Orílɛ́ède Búrúnɛ́lì');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Orílɛ́ède Bútánì');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Orílɛ́ède Bɔ̀lífíyà');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Orílɛ́ède Bɔ̀síníà àti Ɛtisɛgófínà');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Orílɛ́ède Bɔ̀tìsúwánà');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Orílɛ́ède Bɛ̀nɛ̀');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Orílɛ́ède Díbɔ́ótì');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Orílɛ́ède Dòmíníkà');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Orílɛ́ède Dɛ́mákì');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Orílɛ́ède Ekutoria Gini');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Orílɛ́ède Ekuádò');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Orílɛ́ède Eritira');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Orílɛ́ède Esitonia');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Orílɛ́ède Etikun Fagini ti Amɛrika');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Orílɛ́ède Etikun Fakalandi');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Orílɛ́ède Etikun Guusu Mariana');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Orílɛ́ède Etikun Máshali');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Orílɛ́ède Etikun Nɔ́úfókì');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Orílɛ́ède Etikun Solomoni');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Orílɛ́ède Etopia');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Orílɛ́ède Etíkun Fágínì ti ìlú Bírítísì');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Orílɛ́ède Etíkun Índíánì ti Ìlú Bírítísì');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Orílɛ́ède Etíokun Kámánì');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Orílɛ́ède Etíokun Kápé féndè');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Orílɛ́ède Etíokun Kùúkù');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Orílɛ́ède Faniatu');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Orílɛ́ède Faranse');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Orílɛ́ède Fatikani');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Orílɛ́ède Fiji');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Orílɛ́ède Filandi');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Orílɛ́ède Firenshi Guana');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Orílɛ́ède Firenshi Polinesia');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Orílɛ́ède Fisɛnnti ati Genadina');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Orílɛ́ède Fɛnɛshuɛla');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Orílɛ́ède Fɛtinami');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Orílɛ́ède Gabon');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Orílɛ́ède Gadelope');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Orílɛ́ède Gambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Orílɛ́ède Gana');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Orílɛ́ède Gemani');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Orílɛ́ède Genada');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Orílɛ́ède Gene');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Orílɛ́ède Gene-Busau');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Orílɛ́ède Gerelandi');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Orílɛ́ède Geriisi');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Orílɛ́ède Gibaratara');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Orílɛ́ède Guamu');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Orílɛ́ède Guatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Orílɛ́ède Guusu Kɔria');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Orílɛ́ède Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Orílɛ́ède Gɔgia');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Orílɛ́ède Haati');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Orílɛ́ède Hondurasi');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Orílɛ́ède Hungari');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Orílɛ́ède Hɛlena');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Orílɛ́ède India');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Orílɛ́ède Indonesia');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Orílɛ́ède Iraki');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Orílɛ́ède Irani');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Orílɛ́ède Iserɛli');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Orílɛ́ède Italiyi');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Orílɛ́ède Iwɔorun Pakisitian ati Gasha');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Orílɛ́ède Jamaika');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Orílɛ́ède Japani');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Orílɛ́ède Jɔdani');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Orílɛ́ède Kaledonia Titun');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Orílɛ́ède Kamerúúnì');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Orílɛ́ède Kashashatani');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Orílɛ́ède Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Orílɛ́ède Kiiti ati Neefi');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Orílɛ́ède Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Orílɛ́ède Kota');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Orílɛ́ède Kurishisitani');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Orílɛ́ède Kuusita Ríkà');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Orílɛ́ède Kuweti');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Orílɛ́ède Kàmùbódíà');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Orílɛ́ède Kánádà');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Orílɛ́ède Kòlómíbìa');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Orílɛ́ède Kòmòrósì');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Orílɛ́ède Kòróátíà');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Orílɛ́ède Kóngò');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Orílɛ́ède Kóútè forà');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Orílɛ́ède Kúbà');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Orílɛ́ède Kúrúsì');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Orílɛ́ède Laberia');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Orílɛ́ède Laosi');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Orílɛ́ède Latifia');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Orílɛ́ède Lebanoni');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Orílɛ́ède Lesoto');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Orílɛ́ède Libiya');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Orílɛ́ède Lituania');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Orílɛ́ède Lusemogi');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Orílɛ́ède Lushia');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Orílɛ́ède Lɛshitɛnisiteni');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Orílɛ́ède Madasika');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Orílɛ́ède Makoronesia');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Orílɛ́ède Maladifi');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Orílɛ́ède Malasia');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Orílɛ́ède Malata');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Orílɛ́ède Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Orílɛ́ède Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Orílɛ́ède Manamari');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Orílɛ́ède Maritania');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Orílɛ́ède Maritiusi');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Orílɛ́ède Masidonia');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Orílɛ́ède Matinikuwi');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Orílɛ́ède Mayote');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Orílɛ́ède Mesiko');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Orílɛ́ède Modofia');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Orílɛ́ède Mogolia');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Orílɛ́ède Monako');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Orílɛ́ède Moroko');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Orílɛ́ède Moshamibiku');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Orílɛ́ède Motserati');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Orílɛ́ède NIkaragua');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Orílɛ́ède Namibia');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Orílɛ́ède Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Orílɛ́ède Nedalandi');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Orílɛ́ède Nedalandi ti Antelisi');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Orílɛ́ède Nepa');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Orílɛ́ède Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Orílɛ́ède Nruguayi');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Orílɛ́ède Nshibɛkisitani');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Orílɛ́ède Nàìjá');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Orílɛ́ède Nàìjíríà');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Orílɛ́ède Nɔɔwii');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Orílɛ́ède Omobabirin');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Orílɛ́ède Orilɛede Amerika');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Orílɛ́ède Paalu');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Orílɛ́ède Paapu ti Giini');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Orílɛ́ède Pakisitan');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Orílɛ́ède Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Orílɛ́ède Paraguye');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Orílɛ́ède Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Orílɛ́ède Pikarini');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Orílɛ́ède Polandi');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Orílɛ́ède Pɔto Riko');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Orílɛ́ède Pɔtugi');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Orílɛ́ède Pɛɛri ati mikuloni');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Orílɛ́ède Riuniyan');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Orílɛ́ède Romaniya');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Orílɛ́ède Ruwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Orílɛ́ède Rɔshia');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Orílɛ́ède Samɔ');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'Orílɛ́ède Sani Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Orílɛ́ède Sao tomi ati piriishipi');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Orílɛ́ède Sashiland');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Orílɛ́ède Saudi Arabia');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Orílɛ́ède Silofakia');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Orílɛ́ède Silofania');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Orílɛ́ède Singapo');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Orílɛ́ède Sipani');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Orílɛ́ède Siri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Orílɛ́ède Siria');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Orílɛ́ède Siria looni');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Orílɛ́ède Somalia');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Orílɛ́ède Sudani');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Orílɛ́ède Surinami');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Orílɛ́ède Swidini');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Orílɛ́ède Sɛnɛga');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Orílɛ́ède Tailandi');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Orílɛ́ède Taiwani');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Orílɛ́ède Takisitani');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Orílɛ́ède Tanshania');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Orílɛ́ède Tirinida ati Tobaga');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Orílɛ́ède Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Orílɛ́ède Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Orílɛ́ède Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Orílɛ́ède Tufalu');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Orílɛ́ède Tunishia');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Orílɛ́ède Tɔɔki');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Orílɛ́ède Tɔɔki ati Etikun Kakɔsi');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Orílɛ́ède Tɔɔkimenisita');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Orílɛ́ède Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Orílɛ́ède Ukarini');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Orílɛ́ède Wali ati futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Orílɛ́ède filipini');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Orílɛ́ède seshɛlɛsi');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Orílɛ́ède shamibia');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Orílɛ́ède shilandi Titun');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Orílɛ́ède shimibabe');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Orílɛ́ède shààdì');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Orílɛ́ède sháínà');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Orílɛ́ède shílè');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Orílɛ́ède shɛ́ɛ́kì');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Orílɛ́ède switishilandi');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Orílɛ́ède yemeni');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Orílɛ́ède Àfùgànístánì');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Orílɛ́ède Àlùbàníánì');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Orílɛ́ède Àlùgèríánì');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Orílɛ́ède Àrin gùngun Áfíríkà');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Orílɛ́ède Ààndórà');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Orílɛ́ède Ààngólà');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Orílɛ́ède Ààngúlílà');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Orílɛ́ède Ààntígúà àti Báríbúdà');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Orílɛ́ède Árúbà');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Orílɛ́ède Ástràlìá');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Orílɛ́ède Égípítì');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Orílɛ́ède ÌlàOòrùn Tímɔ̀');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Orílɛ́ède Ɔɔma');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Orílɛ́ède Ɛmirate ti Awɔn Arabu');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Orílɛ́ède Ɛɛsáfádò');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Sámóánì ti Orílɛ́ède Àméríkà');
