CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afganistan');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albania');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Algieria');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andora');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Anguilla');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Antarktyka');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigua i Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Antyle Holenderskie');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Arabia Saudyjska');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argentyna');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armenia');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Australia');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Austria');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azerbejdżan');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamy');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrajn');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladesz');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbados');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belgia');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benin');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermudy');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Bhutan');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Białoruś');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Birma');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Boliwia');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bośnia i Hercegowina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brazylia');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Brytyjskie Wyspy Dziewicze');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bułgaria');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'Ceuta i Melilla');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Chile');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Chiny');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Chorwacja');
INSERT INTO `country` (`id`, `name`) VALUES ('CP', 'Clipperton');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Cypr');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Czad');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Czarnogóra');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Czechy');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'Dalekie Wyspy Mniejsze Stanów Zjednoczonych');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Dania');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Demokratyczna Republika Konga');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'Diego Garcia');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominika');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Dżibuti');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Egipt');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ekwador');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Erytrea');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estonia');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Etiopia');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Falklandy');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Federalne Stany Mikronezji');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fidżi');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filipiny');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finlandia');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Francja');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'Francuskie Terytoria Południowe');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabon');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'Georgia Południowa i Sandwich Południowy');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ghana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Gibraltar');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Grecja');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Grenlandia');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Gruzja');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guam');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Gujana');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Gujana Francuska');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Gwadelupa');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Gwatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Gwinea');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Gwinea Bissau');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Gwinea Równikowa');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Hiszpania');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Holandia');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'Hongkong SAR');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Indie');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonezja');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Irak');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iran');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irlandia');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Islandia');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Izrael');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamajka');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japonia');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Jemen');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordania');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Kajmany');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambodża');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kamerun');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Katar');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazachstan');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenia');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirgistan');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolumbia');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Komory');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Korea Południowa');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Korea Północna');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Kostaryka');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kuba');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuwejt');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laos');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Liban');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberia');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libia');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Liechtenstein');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Litwa');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Luksemburg');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Łotwa');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Macedonia');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagaskar');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Majotta');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Makau SAR');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Malediwy');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malezja');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Mariany Północne');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Maroko');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martynika');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauretania');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Mauritius');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Meksyk');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Mołdawia');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monako');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongolia');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambik');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibia');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepal');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Niemcy');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Niger');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigeria');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikaragua');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Norfolk');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norwegia');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Nowa Kaledonia');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Nowa Zelandia');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'Oceania inne');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papua Nowa Gwinea');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paragwaj');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitcairn');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Polinezja Francuska');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Polska');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Portoryko');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portugalia');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Republika Dominikańska');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Republika Południowej Afryki');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Republika Środkowoafrykańska');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Republika Zielonego Przylądka');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Reunion');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Rosja');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Rumunia');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Rwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Sahara Zachodnia');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'Saint Barthélemy');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Saint Kitts i Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Saint Lucia');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Saint Vincent i Grenadyny');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Saint-Pierre i Miquelon');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Salwador');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Samoa Amerykańskie');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegal');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Serbia');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Serbia i Czarnogóra');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seszele');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sierra Leone');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapur');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'Sint Maarten');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Słowacja');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Słowenia');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somalia');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Stany Zjednoczone');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Suazi');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudan');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Surinam');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Svalbard i Jan Mayen');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Syria');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Szwajcaria');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Szwecja');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tadżykistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Tajlandia');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Tajwan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzania');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Terytoria Palestyńskie');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Terytorium Brytyjskie Oceanu Indyjskiego');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Timor Wschodni');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trynidad i Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunezja');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Turcja');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Turks i Caicos');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukraina');
INSERT INTO `country` (`id`, `name`) VALUES ('EU', 'Unia Europejska');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Urugwaj');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzbekistan');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis i Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Watykan');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Wenezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Węgry');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Wielka Brytania');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Wietnam');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Włochy');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Wybrzeże Kości Słoniowej');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'Wyspa Bouveta');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Wyspa Bożego Narodzenia');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'Wyspa Guernsey');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'Wyspa Jersey');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'Wyspa Man');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Wyspa Świętej Heleny');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'Wyspa Wniebowstąpienia');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Wyspy Alandzkie');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Wyspy Cooka');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Wyspy Dziewicze Stanów Zjednoczonych');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'Wyspy Heard i McDonalda');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'Wyspy Kanaryjskie');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'Wyspy Kokosowe');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Wyspy Marshalla');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Wyspy Owcze');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Wyspy Salomona');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Wyspy Świętego Tomasza i Książęca');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambia');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Zjednoczone Emiraty Arabskie');
