CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afganistan');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albania');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Algeria');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Amerikanska Sámoa');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andorra');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anguilla');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Antarktis');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua og Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Argentina');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armenia');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Aserbajdsjan');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Avstralia');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahamas');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahrain');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladesj');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbados');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Belgia');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belis');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benin');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermuda');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolivia');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosnia-Hersegovina');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botsvana');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Bouvetoy');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brasilia');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Bretsku Indiahavsoyggjar');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brunei');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulgaria');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burkina Faso');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Burma');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Butan');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Caymanoyggjar');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Cooksoyggjar');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Danmørk');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Djibouti');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Domingo lýðveldið');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominika');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Egyptaland');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekvador');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Ekvator Guinea');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'El Salvador');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritrea');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Estland');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Etiopia');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Eystur Timor');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Eysturríki');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Falklandsoyggjar');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fiji');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filipsoyggjar');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finnland');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Frakland');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Fransk Gujana');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Franska Polynesia');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Fílabeinsstrondin');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Føroyar');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabon');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambia');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Georgia');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Ghana');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Gibraltar');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenada');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Grikkaland');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Grønhøvdaoyggjarnar');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Grønland');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadeloupe');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatemala');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Guernsey');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Guinea');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Guinea Bissau');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Gujana');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haiti');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Heard- og McDonald-oyggjar');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduras');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Hongkong');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Hvítarussland');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'India');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indonesia');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Irak');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Iran');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Italia');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jameika');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japan');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Jemen');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Jersey');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jordan');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Jólaoyggjin');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kambodja');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamerun');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kasakstan');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Katar');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Kekkia');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenja');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Kili');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Kina');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirgisia');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Kjad');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Kokosoyggjar');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolombia');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komorooyggjarnar');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Kongo-Kinshasa');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kosta Rika');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Kroatia');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kuba');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kuvait');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Kýpros');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laos');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesoto');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Lettland');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Libanon');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberia');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libya');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Liktenstein');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Litava');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luksemborg');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagaskar');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Makao');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Makedónia');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malavi');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldivuoyggjarnar');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Maleisia');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Mann');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Marokko');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Marshalloyggjarnar');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martinique');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayotte');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Meksiko');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikronesia');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Miðafrikalýðveldið');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldova');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monako');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongolia');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Montserrat');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mosambik');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Móritania');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Móritius');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibia');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepal');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Niger');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nigeria');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikaragua');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Niðurlendsku Antilloyggjar');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Niðurlond');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Noreg');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Norfolkoy');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Norður-Korea');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Norðurmarianoyggjar');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Ný Sæland');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Ný-Kaledonia');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Oman');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakistan');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palestinskt territorium');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papua Nýguinea');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguei');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Perú');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitcairn');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portugal');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Puerto Rico');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Pólland');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ruanda');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Rumenia');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Russland');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Réunion');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'Saint Barthélemy');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Saint Helena');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Saint Kitts og Nevis');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Saint Lusia');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'Saint Martin');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Saint Vinsent og Grenadinoyggjar');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Saint-Pierre og Miquelon');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Sambandsríki Amerika');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Sambandsríki Amerikas Jómfrúoyggjar');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Sambia');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Sameindu Emirríkini');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'San Marino');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sao Tome og Prinsipi');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Saudi-Arábia');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegal');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Serbia');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Seyskelloyggjarnar');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Sierra Leone');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Simbabvi');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapor');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slovakia');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Slovenia');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somalia');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Spania');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Stóra Bretland');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Stóra Bretlands Jómfrúoyggjar');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudan');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Surinam');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Suður-Korea');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Suðurafrika');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'Suðurgeorgia');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Svalbard og Jan Mayen');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Svasiland');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Sveis');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Svøríki');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Syria');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Sálomonoyggjarnar');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Sámoa');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tadsjikistan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tansania');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Teiland');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Teivan');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad og Tobago');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunesia');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Turkaland');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turkmenistan');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Turks- og Caicosoyggjar');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Týskland');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uganda');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukreina');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Ungarn');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruguei');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Usbekistan');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikan');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venesuela');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Vestursahara');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vietnam');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis og Futuna');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Áland');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Írland');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Ísland');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Ísrael');
