CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afghanistan');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albania');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Algeria');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andorra');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Anguilla');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Antartide');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigua e Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Antille Olandesi');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Arabia Saudita');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argentina');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armenia');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Australia');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Austria');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azerbaigian');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamas');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrein');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladesh');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbados');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belgio');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benin');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Bhutan');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Bielorussia');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolivia');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosnia Erzegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brasile');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgaria');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Cambogia');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Camerun');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Canada');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Capo Verde');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'Ceuta e Melilla');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Ciad');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Cile');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Cina');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Cipro');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Colombia');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Comore');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Congo');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Corea del Nord');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Corea del Sud');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Costa d’Avorio');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Costa Rica');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Croazia');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Cuba');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Danimarca');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'Diego Garcia');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominica');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ecuador');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Egitto');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'El Salvador');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Emirati Arabi Uniti');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritrea');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estonia');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Etiopia');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Federazione Russa');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Figi');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filippine');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finlandia');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Francia');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabon');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Georgia');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'Georgia del Sud e Isole Sandwich del Sud');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Germania');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ghana');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Giamaica');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Giappone');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Gibilterra');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Gibuti');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Giordania');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Grecia');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Groenlandia');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Guadalupa');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guam');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Guatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'Guernsey');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Guiana Francese');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Guinea Equatoriale');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'India');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonesia');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iran');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Iraq');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irlanda');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Islanda');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'Isola Bouvet');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'Isola di Ascensione');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Isola di Christmas');
INSERT INTO `country` (`id`, `name`) VALUES ('CP', 'Isola di Clipperton');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'Isola di Man');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Isola Norfolk');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Isole Aland');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'Isole Canarie');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Isole Cayman');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'Isole Cocos');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Isole Cook');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Isole Falkland');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Isole Faroe');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'Isole Heard ed Isole McDonald');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Isole Marianne Settentrionali');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Isole Marshall');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'Isole Minori lontane dagli Stati Uniti');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Isole Solomon');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Isole Turks e Caicos');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Isole Vergini Americane');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Isole Vergini Britanniche');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Israele');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italia');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'Jersey');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirghizistan');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuwait');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laos');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Lettonia');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libano');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberia');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libia');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Liechtenstein');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Lituania');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Lussemburgo');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagascar');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldive');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malesia');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Marocco');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinica');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauritania');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Mauritius');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayotte');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Messico');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Micronesia');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldavia');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monaco');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongolia');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambico');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Myanmar');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibia');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepal');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nicaragua');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Niger');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigeria');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norvegia');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Nuova Caledonia');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Nuova Zelanda');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'Oceania lontana');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Paesi Bassi');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papua Nuova Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paraguay');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Perù');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitcairn');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Polinesia Francese');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Polonia');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portogallo');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Portorico');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Qatar');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'Regione Amministrativa Speciale di Hong Kong della Repubblica Popolare Cinese');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Regione Amministrativa Speciale di Macao della Repubblica Popolare Cinese');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Regno Unito');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Repubblica Ceca');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Repubblica Centrafricana');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Repubblica Democratica del Congo');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Repubblica di Macedonia');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Repubblica Dominicana');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Réunion');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romania');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Ruanda');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Sahara Occidentale');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Saint Kitts e Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Saint Lucia');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'Saint Martin');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Saint Pierre e Miquelon');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Saint Vincent e Grenadines');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Samoa Americane');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'San Bartolomeo');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Sant’Elena');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Sao Tomé e Príncipe');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegal');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Serbia');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Serbia e Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seychelles');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sierra Leone');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapore');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Siria');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Slovacchia');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Slovenia');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somalia');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Spagna');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Stati Uniti');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Sudafrica');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudan');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Suriname');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Svalbard e Jan Mayen');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Svezia');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Svizzera');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Swaziland');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tagikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Tailandia');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzania');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'Territori australi francesi');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Territori palestinesi');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Territorio Britannico dell’Oceano Indiano');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Timor Est');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad e Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunisia');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Turchia');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ucraina');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Ungheria');
INSERT INTO `country` (`id`, `name`) VALUES ('EU', 'Unione Europea');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Uruguay');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzbekistan');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vaticano');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vietnam');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis e Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Yemen');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambia');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
