CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AX', 'Alandska ostrva');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albanija');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Alžir');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Američka Samoa');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andora');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Angvila');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Antarktika');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigva i Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Argentina');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armenija');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Australija');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Austrija');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Avganistan');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azerbejdžan');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahami');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahrein');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladeš');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbados');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Belgija');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belise');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Belorusija');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benin');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermuda');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Bocvana');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolivija');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosna i Hercegovina');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Božićna Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brazil');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Britanska Devičanska Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Britansko Indijska Okeanska Teritorija');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brunej');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bugarska');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burkina Faso');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Butan');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Buve Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Centralno Afrička Republika');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Crna Gora');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Čad');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Češka');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Čile');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Danska');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Demokratska Republika Kongo');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominika');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Dominikanska Republika');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Džersi');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Džibuti');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Egipat');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekvador');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Ekvatorijalna Gvineja');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritreja');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Estonija');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Etiopija');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'Evropska unija');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Farska Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fidži');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filipini');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finska');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Folklandska Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Francuska');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Francuska Gvajana');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Francuska Polinezija');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Francuske Južne Teritorije');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabon');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambija');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Gana');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Gibraltar');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Grčka');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenada');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Grenland');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Gruzija');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Gurnsi');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Gvadelupe');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Gvajana');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Gvatemala');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Gvineja');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Gvineja-Bisao');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haiti');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Herd i Mekdonald Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Holandija');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Holandski Antili');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduras');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Hong Kong (S. A. R. Kina)');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Hrvatska');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Indija');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indonezija');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Irak');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Iran');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Irska');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Island');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Italija');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Izrael');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamajka');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japan');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Jemen');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jordan');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'Južna Džordžija i Južna Sendvič Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Južna Koreja');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Južnoafrička Republika');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Kajmanska Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kambodža');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamerun');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Kape Verde');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Katar');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazahstan');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenija');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Kina');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Kipar');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirgizstan');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Kokos (Keling) Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolumbija');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komorska Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kostarika');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kuba');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Kukova Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kuvajt');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laos');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesoto');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Letonija');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Liban');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberija');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libija');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Lihtenštajn');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Litvanija');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luksemburg');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagaskar');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Mađarska');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Majote');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Makao (S. A. R. Kina)');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Makedonija');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malavi');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldivi');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malezija');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'Manja Udaljena Ostrva SAD');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Maroko');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Maršalska Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martinik');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Mauricius');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mauritanija');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Meksiko');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Mijanmar');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikronezija');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldavija');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monako');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongolija');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Monserat');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mozambik');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibija');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Nemačka');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepal');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Niger');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nigerija');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikaragva');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Norfolk Ostrvo');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Norveška');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Nova Kaledonija');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Novi Zeland');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Obala Slonovače');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Oman');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'Ostala okeanija');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Ostrvo Man');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakistan');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palestinska Teritorija');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papua Nova Gvineja');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paragvaj');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Peru');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitcairn');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Poljska');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Porto Riko');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portugal');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Rejunion');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ruanda');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Rumunija');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Rusija');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'S.A.D. Devičanska Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Salvador');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samoa');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'San Marino');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sao Tome i Principe');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Saudijska Arabija');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Sejšeli');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Sen Pjer i Mikelon');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegal');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Sent Kits i Nevis');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Sent Lucija');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Sent Vinsent i Grenadini');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Severna Koreja');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Severna Marijanska Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Sijera Leone');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapur');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Sirija');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Sjedinjene Američke Države');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slovačka');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Slovenija');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Solomonska Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somalija');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Srbija');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Srbija i Crna Gora');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudan');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Surinam');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'Sv. Bartolomej');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'Sv. Martin');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Svalbard i Janmajen Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Svazilend');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Sveta Jelena');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Španija');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Šri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Švajcarska');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Švedska');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tadžikistan');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Tajland');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Tajvan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzanija');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Timor Leste');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad i Tobago');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunis');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turkmenistan');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Turks i Kajkos Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Turska');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uganda');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Ujedinjeni Arapski Emirati');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukrajina');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Urugvaj');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Uzbekistan');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Valis i Futuna Ostrva');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikan');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Velika Britanija');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venecuela');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vijetnam');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambija');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Zapadna Sahara');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabve');
