CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afganistan');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Alandské ostrovy');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albánsko');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Alžírsko');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Americká Samoa');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andorra');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anguilla');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Antarctica');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua a Barbados');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Argentína');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Arménsko');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Austrália');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azerbajdžan');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahamy');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahrajn');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladéš');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbados');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Belgicko');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belize');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benin');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermudy');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Bielorusko');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolívia');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosna a Hercegovina');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botswana');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Bouvetov ostrov');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brazília');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Britské panenské ostrovy');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Britské územie v Indickom oceáne');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brunej');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulharsko');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burkina Faso');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Bután');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'Ceuta a Melilla');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Cookove ostrovy');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Cyprus');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Čad');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Česká republika');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Čierna Hora');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Čile');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Čína');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Dánsko');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'Diego Garcia');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominika');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Dominikánska republika');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Džibuti');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Egypt');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekvádor');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritrea');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Estónsko');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Etiópia');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'Európska únia');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Faerské ostrovy');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Falklandské ostrovy');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fidži');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filipíny');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Fínsko');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Francúzska Guayana');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Francúzska Polynézia');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Francúzske južné územia');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Francúzsko');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabon');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambia');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Ghana');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Gibraltár');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Grécko');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenada');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Grónsko');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Gruzínsko');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadeloupe');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatemala');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guayana');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Guernsey');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Guinea');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Guinea-Bissau');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haiti');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Heardove ostrovy a McDonaldove ostrovy');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Holandské Antily');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Holandsko');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduras');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Hongkong S.A.R. Číny');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Chorvátsko');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'India');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indonézia');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Irak');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Irán');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Írsko');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Island');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Izrael');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamajka');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japonsko');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Jemen');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Jersey');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jordánsko');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Južná Afrika');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'Južná Georgia a Južné Sandwichove ostrovy');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Kajmanské ostrovy');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kambodža');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamerun');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'Kanárske ostrovy');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Kapverdy');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Katar');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazachstan');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Keňa');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirgizsko');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Kokosové ostrovy');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolumbia');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komory');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Konžská demokratická republika');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Kórejská ľudovodemokratická republika');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Kórejská republika');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kostarika');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kuba');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kuvajt');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laoská ľudovodemokratická republika');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesotho');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Libanon');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Libéria');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Lichtenštajnsko');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Litva');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Lotyšsko');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luxembursko');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Lýbijská arabská džamahírija');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Macedónsko');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagaskar');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Maďarsko');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Makao S.A.R. Číny');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malajzia');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malawi');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldivy');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Maroko');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Marshallove ostrovy');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martinik');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Maurícius');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mauritánia');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayotte');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'Menšie odľahlé ostrovy USA');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mexiko');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikronézia');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Mjanmarsko');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldavsko');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monako');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongolsko');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Montserrat');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mozambik');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namíbia');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Nemecko');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepál');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Niger');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nigéria');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikaragua');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Norfolkov ostrov');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Nórsko');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Nová Kaledónia');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Nový Zéland');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Omán');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'Ostrov Ascensión');
INSERT INTO "country" ("id", "name") VALUES ('CP', 'Ostrov Clipperton');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Ostrov Man');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakistan');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palestínske územie');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Panenské ostrovy - USA');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papua Nová Guinea');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguaj');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Peru');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitcairnove ostrovy');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Pobrežie Slonoviny');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Poľsko');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Portoriko');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portugalsko');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Rakúsko');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Reunion');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Rovníková Guinea');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Rumunsko');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Ruská federácia');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Rwanda');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Saint Kitts a Nevis');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Saint Pierre a Miquelon');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Salvador');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samoa');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'San Maríno');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Saudská Arábia');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegal');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Severné Mariány');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Seychelské ostrovy');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Sierra Leone');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapur');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slovenská republika');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Slovinsko');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somálsko');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Spojené arabské emiráty');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Spojené kráľovstvo');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Spojené štáty');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Srbsko');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Srbsko a Čierna Hora');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Srí Lanka');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Stredoafrická republika');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudán');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Surinam');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Svazijsko');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Svätá Helena');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Svätá Lucia');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'Svätý Bartolomej');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'Svätý Martin');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Svätý Tomáš a Princove ostrovy');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Svätý Vincent a Grenadíny');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Sýrska arabská republika');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Šalamúnove ostrovy');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Španielsko');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Špicbergy a Jan Mayen');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Švajčiarsko');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Švédsko');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tadžikistan');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Tajwan');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Taliansko');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzánia');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Thajsko');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'Tichomorie - ostatné');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad a Tobago');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'Tristan da Cunha');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunisko');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Turecko');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turkménsko');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Turks a Caicos');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uganda');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukrajina');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruguaj');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Uzbekistan');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikán');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezuela');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Vianočný ostrov');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vietnam');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Východný Timor');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis a Futuna');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambia');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Západná Sahara');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabwe');
