CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AD', 'اندورا');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'امارات متحدهٔ عربی');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'انتیگوا و باربودا');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'البانیا');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'انگولا');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'ارجنتاین');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'آسترالیا');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'بوسنیا و هرزه‌گوینا');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'بنگله‌دیش');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'بلجیم');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'بلغاریا');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'برونی');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'بولیویا');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'برازیل');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'بهاماس');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'روسیهٔ سفید');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'جمهوری دموکراتیک کانگو');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'افریقای مرکزی');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'کانگو');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'سویس');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'چلی');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'کولمبیا');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'کاستریکا');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'کیوبا');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'دنمارک');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'اکوادور');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'استونیا');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'اریتریا');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'هسپانیه');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'ایتوپیا');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'فنلند');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'میکرونزیا');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'گرینادا');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'گینیا');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'گینیا استوایی');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'گواتیمالا');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'گینیا بیسائو');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'گیانا');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'هاندوراس');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'کروشیا');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'هایتی');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'اندونیزیا');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'آیرلند');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'آیسلند');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'جاپان');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'کینیا');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'قرغزستان');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'کمپوچیا');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'کومور');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'سنت کیتس و نیویس');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'کوریای شمالی');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'کوریای جنوبی');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'سریلانکا');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'لیسوتو');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'لتوانیا');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'لاتویا');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'لیبیا');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'مادغاسکر');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'منگولیا');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'موریتانیا');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'مالتا');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'مکسیکو');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'مالیزیا');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'موزمبیق');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'نیجریا');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'نیکاراگوا');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'هالند');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'ناروی');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'نیپال');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'زیلاند جدید');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'پانامه');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'پیرو');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'پاپوا نیو گینیا');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'پولند');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'پرتگال');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'پاراگوای');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'رومانیا');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'روآندا');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'جزایر سلومون');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'سویدن');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'سینگاپور');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'سلونیا');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'سلواکیا');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'سیرالیون');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'سینیگال');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'سومالیه');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'سائو تومه و پرینسیپ');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'السلوادور');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'تاجکستان');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'اکراین');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'ایالات متحدهٔ امریکا');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'یوروگوای');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'سنت وینسنت و گرینادین');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'ونزویلا');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'ساموآ');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'زیمبابوی');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'افغانستان');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'آنگیل');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'ارمنستان');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'آنتیل هلند');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'جنوبگان');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'ساموای امریکا');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'اتریش');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'آروبا');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'جزایر آلاند');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'جمهوری آذربایجان');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'باربادوس');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'بورکینافاسو');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'بحرین');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'بوروندی');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'بنین');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'سنت بارتلیمی');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'برمودا');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'بوتان');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'جزیرهٔ بووت');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'بوتسوانا');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'بلیز');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'کانادا');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'جزایر کوکوس');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'ساحل عاج');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'جزایر کوک');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'کامرون');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'چین');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'صربستان و مونته‌نگرو');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'کیپ ورد');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'جزیرهٔ کریسمس');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'قبرس');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'جمهوری چک');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'آلمان');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'جیبوتی');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'دومینیک');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'جمهوری دومینیکن');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'الجزایر');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'مصر');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'صحرای غربی');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'فیجی');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'جزایر فالکلند');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'جزایر فارو');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'فرانسه');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'گابون');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'بریتانیا');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'گرجستان');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'گویان فرانسه');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'گرنزی');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'غنا');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'جبل‌الطارق');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'گروئنلند');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'گامبیا');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'گوادلوپ');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'یونان');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'جورجیای جنوبی و جزایر ساندویچ جنوبی');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'گوام');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'هنگ‌کنگ، ناحیهٔ ویژهٔ حکومتی چین');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'جزیرهٔ هرد و جزایر مک‌دونالد');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'مجارستان');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'اسرائیل');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'جزیرهٔ مان');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'هند');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'مستعمره‌های بریتانیا در اقیانوس هند');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'عراق');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'ایران');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'ایتالیا');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'جرسی');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'جامائیکا');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'اردن');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'کیریباتی');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'کویت');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'جزایر کِیمن');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'قزاقستان');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'لائوس');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'لبنان');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'سنت لوسیا');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'لیختن‌اشتاین');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'لیبریا');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'لوکزامبورگ');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'مراکش');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'موناکو');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'مولداوی');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'مونته‌نگرو');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'سنت مارتین');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'جزایر مارشال');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'مقدونیه');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'مالی');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'میانمار');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'ماکائو، ناحیهٔ ویژهٔ حکومتی چین');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'جزایر ماریانای شمالی');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'مارتینیک');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'مونت‌سرات');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'موریس');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'مالدیو');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'مالاوی');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'نامیبیا');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'کالدونیای جدید');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'نیجر');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'جزیرهٔ نورفولک');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'نائورو');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'نیوئه');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'عمان');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'پلی‌نزی فرانسه');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'فیلیپین');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'پاکستان');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'سنت پیر و میکلون');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'پیتکایرن');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'پورتو ریکو');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'فلسطین');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'پالائو');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'قطر');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'ریونیون');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'صربستان');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'روسیه');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'عربستان سعودی');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'سیشل');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'سودان');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'سنت هلن');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'اسوالبارد و جان ماین');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'سان مارینو');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'سورینام');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'سوریه');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'سوازیلند');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'جزایر ترک و کایکوس');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'چاد');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'مستعمره‌های جنوبی فرانسه');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'توگو');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'تایلند');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'توکلائو');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'تیمور شرقی');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'ترکمنستان');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'تونس');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'تونگا');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'ترکیه');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'ترینیداد و توباگو');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'تووالو');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'تایوان');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'تانزانیا');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'اوگاندا');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'جزایر کوچک دورافتادهٔ ایالات متحده');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'ازبکستان');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'واتیکان');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'جزایر ویرجین بریتانیا');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'جزایر ویرجین ایالات متحده');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'ویتنام');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'وانواتو');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'والیس و فیوتونا');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'یمن');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'مایوت');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'افریقای جنوبی');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'زامبیا');
INSERT INTO [country] ([id], [name]) VALUES ('ZZ', 'ناحیهٔ نامشخص یا نامعتبر');
