CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ZZ', '- Jääjend onbikannt -');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afjaanistahn');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Ajjentiinije');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albaanije');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Alljeerije');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Ammerikaanesch Sammoha');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andorra');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anggwilla');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angjoola');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigwa un Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Arrmeenije');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Asserbaidschahn');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Austraalije');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'Aßension');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bachrain');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladesch');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belize');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Bellje');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Birma');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolliivije');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Bozwaana');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Boßnije un Herzegovina');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brasilije');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Brettesche Besezunge em indesche Oozejahn');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brunei');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Bukkinna-Faase');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulljaarije');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Buttaan');
INSERT INTO "country" ("id", "name") VALUES ('CW', 'Curaçao');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominnika');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Doütschland');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Dschibutti');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Dänemark');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Fillipiine');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finnland');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Frankrisch');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Franzüüsesch Jujaana');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Franzüüsesch Pollineesije');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Franzüüsesche Södsee-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Ha\'itti');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduras');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Hongkong');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Indije');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indoneesije');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Irak');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Irrland');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Itaalije');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Ißland');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Ißraäl');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Jaana');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Jabuhn');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Jambija');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jammaika');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japan');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Jeorrjije');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Jibralltaa');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Jinneha');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Jinneha_Bißau');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jordaanije');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Jrenaada');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Jriescheland');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Jruußbrettannije');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Jröhnland');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Juadelupp');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Juham');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Jujaana');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Juwatemaala');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Jämme');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Jöönsei');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Jööseh');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kambodscha');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kammeruhn');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kassakstahn');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Kataa');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Keenija');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirrjiisije');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolumbije');
INSERT INTO "country" ("id", "name") VALUES ('XK', 'Kosovo');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kostarika');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Krowazije');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kuba');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kuweit');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'La\'os');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Lebbannon');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesooto');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libbije');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Libeerija');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Lischteschtein');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Littaue');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luxembursch');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Lätland');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Maali');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Machtinik');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Maddajaska');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Majott');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Makau');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malaisije');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malawi');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Mallediive');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Marokko');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Maurizijus');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mautitaanije');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Mazedoonije');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikroneesije');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldaavije');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monakko');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongjolei');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Mongßerrat');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mosambik');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mäxiko');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namiibije');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepall');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Neuschottland');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Neuseeland');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Nijer');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nikaraagua');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikaraaguwa');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Nood-Koreja');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Noodsudahn');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Norrweeje');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Oman');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Oß-Timor');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakistahn');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Pallau');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palästina');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Pannama');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papuwa Neujineeja');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Parraguwai');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Perruh');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Persije');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Pochtojall');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Pochtoriko');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Pole');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Rehunjohn');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Romäänije');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ruanda');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Rußland');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Sambija');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Sammoha');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'San-Marino');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Saudi Arraabije');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Schiile');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Schiina');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Schpaanije');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Schweede');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Simbabwe');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singjapuur');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Sjärra Lejone');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somaalije');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Särbije');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'Söd-Jeorjie un de södlijje Botteramms-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Söd-Koreja');
INSERT INTO "country" ("id", "name") VALUES ('SS', 'Södsudahn');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Sürije');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Sürinamm');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tadschikistahn');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Tailand');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taiwan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tansanija');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tongga');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Toojo');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad un Tobääjo');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'Tristan da Cunja');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tuneesije');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turkmenistahn');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Ujanda');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Unjann');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Urrujwai');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Ußbeekistahn');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezuela');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Vereinschte Arrabesche Emmirate');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vijätnamm');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis un Futuna');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Wießrußland');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Wäß-Sahara');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'Ze\'uta un Meliija');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Zint Kitts un Nevis');
INSERT INTO "country" ("id", "name") VALUES ('SX', 'Zint Maarten');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Zint Pjäär un Mikelong');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Zint Tommeh un Printschipe');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Zint Vinzänz un de Jrenadines-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Züppere');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'de Bahamas');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'de Bermudas');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'de Buvee-Ensel');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'de Diego-Garcia-Ensel');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'de Dommenekaanesche Reppublik');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'de Ensel Barbados');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'de Ensel Män');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'de Ensel Zint Hellena');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'de Ensel Zint-Lutscha');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'de Enselle Svalbard un Jan Mayen');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'de Enselle Turks un Kaikos');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'de Falkland-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'de Fidschi-Endelle');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'de Färrör-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'de Heart Ensel un de McDonald-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'de Kaiman-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'de Kannaresche Enselle');
INSERT INTO "country" ("id", "name") VALUES ('CP', 'de Klipperton-Ensel');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'de Kokkos-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'de Kommoore');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'de Kuuk-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'de Machschall-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'de Nederläng');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'de Nederlängsche Antille');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'de Noofok-Ensel');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'de Ohland-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'de Pitkärn-Ensel');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'de Republik Södaffrika');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'de Schweiz');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'de Seischälle');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'de Solomone-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'de Tschäschei');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'de Törkei');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'de Ukra\'iine');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'de Vereineschte Schtaate vun Amärrika ier ußerhallef jelääje Enselsche');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'de Weihnaachs-Ensel');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'de Zint Battälmi-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'de Zint-Määtes-Ensel');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'de Zäntraalaffrikaanesche Republik');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'de ammärrikahnesche Juffer-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'de brettesche Juffer-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'de kapvärdesche Enselle');
INSERT INTO "country" ("id", "name") VALUES ('BQ', 'de karribbesche Nederläng');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'de nöödlijje Marijanne-Enselle');
INSERT INTO "country" ("id", "name") VALUES ('US', 'de vereineschte Schtaate vun Ammärrika');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'der Sennejall');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'der Södpol');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'der Tschadd');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'der Vattikahn');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'dä Benin');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'dä Konggo (Brassavill)');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'dä Konggo (Kinschasa)');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'et Monteneejro');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Äjüpte');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Äkwador');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Äl Slavadoor');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Älfebeijn-Köß');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Äquatorial Jineeja');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Äritreja');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Ättijoopije');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Äßland');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Öösterisch');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'ẞlovakei');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'ẞloveenije');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'ẞwaasiland');
