CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Австралия');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Австрия');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Азербайджан');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Аландские о-ва');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Албания');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Алжир');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Американское Самоа');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Ангилья');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Ангола');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Андорра');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Антарктида');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Антигуа и Барбуда');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Аргентина');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Армения');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Аруба');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Афганистан');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Багамские о-ва');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Бангладеш');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Барбадос');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Бахрейн');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Беларусь');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Белиз');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Бельгия');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Бенин');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Бермудские о-ва');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Болгария');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Боливия');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Босния и Герцеговина');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Ботсвана');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Бразилия');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Британская территория в Индийском океане');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Британские Виргинские о-ва');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Бруней Даруссалам');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Буркина Фасо');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Бурунди');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Бутан');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Вануату');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Ватикан');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Великобритания');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Венгрия');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Венесуэла');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Виргинские о-ва (США)');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Внешние малые острова (США)');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'Внешняя Океания');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Восточный Тимор');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Вьетнам');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Габон');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Гаити');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Гайана');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Гамбия');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Гана');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Гваделупа');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Гватемала');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Гвинея');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Гвинея-Бисау');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Германия');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Гернси');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Гибралтар');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Гондурас');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Гонконг (особый район)');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Гренада');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Гренландия');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Греция');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Грузия');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Гуам');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Дания');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Демократическая Республика Конго');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Джерси');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Джибути');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Диего-Гарсия');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Доминика');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Доминиканская Республика');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'Европейский союз');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Египет');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Замбия');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Западная Сахара');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Зимбабве');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Израиль');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Индия');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Индонезия');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Иордания');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Ирак');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Иран');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Ирландия');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Исландия');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Испания');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Италия');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Йемен');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Казахстан');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Каймановы острова');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Камбоджа');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Камерун');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Канада');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Канарские о-ва');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Катар');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Кения');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Кипр');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Киргизия');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Кирибати');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Китай');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Кокосовые о-ва');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Колумбия');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Коморские о-ва');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Конго');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Коста-Рика');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Кот д’Ивуар');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Куба');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Кувейт');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Лаос');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Латвия');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Лесото');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Либерия');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Ливан');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Ливия');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Литва');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Лихтенштейн');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Люксембург');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Маврикий');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Мавритания');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Мадагаскар');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Майотта');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Макао (особый район)');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Македония');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Малави');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Малайзия');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Мали');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Мальдивские о-ва');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Мальта');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Марокко');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Мартиника');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Маршалловы о-ва');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Мексика');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Мозамбик');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Молдова');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Монако');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Монголия');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Монтсеррат');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Мьянма');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Намибия');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Науру');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Непал');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Нигер');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Нигерия');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Нидерландские Антильские о-ва');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Нидерланды');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Никарагуа');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Ниуе');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Новая Зеландия');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Новая Каледония');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Норвегия');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'ОАЭ');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Оман');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Остров Буве');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Остров Вознесения');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'Остров Клиппертон');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Остров Мэн');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Остров Норфолк');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Остров Рождества');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Остров Святого Бартоломея');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Остров Святого Мартина');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Остров Святой Елены');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Острова Зеленого Мыса');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Острова Кука');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Острова Тёркс и Кайкос');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'Острова Херд и Макдональд');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Пакистан');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Палау');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Палестинские территории');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Панама');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Папуа – Новая Гвинея');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Парагвай');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Перу');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Питкэрн');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Польша');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Португалия');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Пуэрто-Рико');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Республика Корея');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Реюньон');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Россия');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Руанда');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Румыния');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Сальвадор');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Самоа');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'Сан-Марино');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Сан-Томе и Принсипи');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Саудовская Аравия');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Свазиленд');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Свальбард и Ян-Майен');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Северная Корея');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Северные Марианские о-ва');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Сейшельские о-ва');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Сен-Пьер и Микелон');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Сенегал');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Сент-Винсент и Гренадины');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Сент-Киттс и Невис');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Сент-Люсия');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Сербия');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Сербия и Черногория');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Сеута и Мелилья');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Сингапур');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Сирия');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Словакия');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Словения');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Соломоновы о-ва');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Сомали');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Судан');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Суринам');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'США');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Сьерра-Леоне');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Таджикистан');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Таиланд');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Тайвань');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Танзания');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Того');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Токелау');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Тонга');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Тринидад и Тобаго');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Тристан-да-Кунья');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Тувалу');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Тунис');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Туркменистан');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Турция');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Уганда');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Узбекистан');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Украина');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Уоллис и Футуна');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Уругвай');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Фарерские о-ва');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Федеративные Штаты Микронезии');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Фиджи');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Филиппины');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Финляндия');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Фолклендские о-ва');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Франция');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Французская Гвиана');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Французская Полинезия');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Французские Южные Территории');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Хорватия');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'ЦАР');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Чад');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Черногория');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Чехия');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Чили');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Швейцария');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Швеция');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Шри-Ланка');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Эквадор');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Экваториальная Гвинея');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Эритрея');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Эстония');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Эфиопия');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'ЮАР');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Южная Джорджия и Южные Сандвичевы Острова');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Ямайка');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Япония');
