CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AF', 'Abganithtan');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Adhe̱rbe̱ja̱n');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Aɛrgentin');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Aɛrmänia');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albänia');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Algeria');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Amerika thamow');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andora');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antiguaa kɛnɛ Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Aŋgola');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Aŋguɛla');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Athɔra̱lia');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Athtɛria');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bämuɔth');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Bäraadhiil');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Bärbadoth');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Ba̱reen');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Be̱lɛruth');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Be̱lgim');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bengeladiec');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Be̱ni̱n');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Be̱rmudaa');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Bilidha');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Bothiwaana');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bothnia kɛnɛ ɣärgobinia');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulga̱a̱ria');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bulibia');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burkinɛ pa̱thu');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Burunɛy');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Burutic dhuɔ̱ɔ̱l be̱rgin');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Burutic ɣe̱ndian oce̱n');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Buta̱n');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Ca̱d');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Cayna');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Cɛntrɔl aprika repuɔblic');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Cili̱');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Känɛda');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Kaymɛn ɣa̱ylɛn');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kɛmɛrun');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Kɛp bedi ɣa̱ylɛn');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Kodibo̱o̱');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolombia');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kombodia');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komruth');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Korwaatia');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kothtirika');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kɔŋgɔ');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Kuk ɣa̱ylɛn');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudan');
