CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AO', 'ಅಂಗೋಲಾ');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'ಅಂಟಾರ್ಟಿಕಾ');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'ಅಂಡೋರಾ');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'ಅಜರ್ಬೈಜಾನ್');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'ಅಫಘಾನಿಸ್ಥಾನ್');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'ಅಮೇರಿಕನ್ ಸಮೋವಾ');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'ಅಮೇರಿಕಾ ಸಂಯುಕ್ತ ಸಂಸ್ಥಾನ');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'ಅರುಬಾ');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'ಅರ್ಜೆಂಟೈನಾ');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'ಅರ್ಮೇನಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'ಅಲ್ಗೇರಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'ಅಲ್ಬೇನಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'ಅಸೆನ್ಶನ್ ದ್ವೀಪ');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'ಆಂಗುಯಿಲ್ಲಾ');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'ಆಂಟಿಗುವಾ ಮತ್ತು ಬರ್ಬುಡಾ');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'ಆಲ್ಯಾಂಡ್ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'ಆಸ್ಟ್ರಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'ಆಸ್ಟ್ರೇಲಿಯ');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'ಇಂಡೋನೇಶಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'ಇಟಲಿ');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'ಇಥಿಯೋಪಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'ಇರಾಕ್');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'ಇರಾನ್');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'ಇಸ್ರೇಲ್');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'ಈಕ್ವೆಟೋರಿಯಲ್ ಗಿನಿ');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'ಈಕ್ವೆಡಾರ್');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'ಈಜಿಪ್ಟ್');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'ಉಕ್ರೈನ್');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'ಉಗಾಂಡಾ');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'ಉಜ್ಬೇಕಿಸ್ಥಾನ್');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'ಉತ್ತರ ಕೋರಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'ಉತ್ತರ ಮರಿಯಾನಾ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'ಉರುಗ್ವೇ');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'ಎಲ್ ಸಾಲ್ವೇಡಾರ್');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'ಎಸ್ತೊನಿಯ');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'ಏರಿಟ್ರಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'ಐರ್ಲೆಂಡ್');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'ಐಲ್ ಆಫ್ ಮ್ಯಾನ್');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'ಐವರಿ ಕೋಸ್ಟ್');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'ಐಸ್‌ಲ್ಯಾಂಡ್');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'ಓಮನ್');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'ಔಟ್‌ಲೈಯಿಂಗ್ ಓಶಿಯಾನಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'ಕಝಾಕಿಸ್ಥಾನ್');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'ಕತಾರ್');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'ಕಾಂಗೋ - ಕಿನ್ಶಾಸಾ');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'ಕಾಂಗೋ - ಬ್ರಾಜಾವಿಲ್ಲೇ');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'ಕಾಂಬೋಡಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'ಕಿರಿಬಾತಿ');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'ಕಿರ್ಗಿಸ್ಥಾನ್');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'ಕೀನ್ಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'ಕುಕ್ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'ಕುವೈತ್');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'ಕೆನಡಾ');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'ಕೇಪ್ ವರ್ಡೆ');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'ಕೇಮನ್ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'ಕೊಕೊಸ್ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'ಕೊಮೊರೊಸ್');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'ಕೊಲಂಬಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'ಕೊಸ್ಟಾ ರಿಕಾ');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'ಕ್ಯಾನರಿ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'ಕ್ಯಾಮರೋನ್');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'ಕ್ಯೂಬಾ');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'ಕ್ರಿಸ್‌ಮಸ್ ದ್ವೀಪ');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'ಕ್ರೋಯೇಶಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'ಕ್ಲಿಪರ್ಟನ್‌ ಐಲ್ಯಾಂಡ್‌');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'ಗಯಾನಾ');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'ಗಿನಿ');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'ಗಿನಿ-ಬಿಸ್ಸಾವ್');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'ಗಿಬ್ರಾಲ್ಟರ್');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'ಗುಡೆಲೋಪ್');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'ಗುಯಾಮ್');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'ಗುರ್ನಜೀ');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'ಗೆಬೊನ್');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'ಗ್ಯಾಂಬಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'ಗ್ರೀನ್‌ಲ್ಯಾಂಡ್');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'ಗ್ರೀಸ್');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'ಗ್ರೆನೆಡಾ');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'ಗ್ವಾಟೆಮಾಲಾ');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'ಘಾನಾ');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'ಚಾಡ್');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'ಚಿಲಿ');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'ಚೀನ');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'ಚೆಕ್ ರಿಪಬ್ಲಿಕ್');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'ಜಪಾನ್');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'ಜಮೈಕಾ');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'ಜರ್ಮನಿ');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'ಜಾರ್ಜಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'ಜಿಂಬಾಬ್ವೆ');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'ಜಿಬೋಟಿ');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'ಜೆರ್ಸಿ');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'ಜೋರ್ಡಾನ್');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'ಝಾಂಬಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'ಟರ್ಕಿ');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'ಟರ್ಕ್ಸ್ ಮತ್ತು ಕೈಕೋಸ್ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'ಟಾಂಜಾನಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'ಟುನಿಶಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'ಟುವಾಲು');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'ಟೊಂಗ');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'ಟೊಕೆಲಾವ್');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'ಟೋಗೋ');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'ಟ್ರಿನಿಡಾಡ್ ಮತ್ತು ಟೊಬ್ಯಾಗೊ');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'ಡೆನ್ಮಾರ್ಕ್');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'ಡೈಗೋ ಗಾರ್ಸಿಯ');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'ಡೊಮಿನಿಕಾ');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'ಡೊಮೆನಿಕ್ ರಿಪಬ್ಲಿಕ್');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'ತಜಾಕಿಸ್ಥಾನ್');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'ತುರ್ಕಮೆನಿಸ್ಥಾನ್');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'ತ್ರಿಸ್ತಾನ್‌ ದ ಕುನ್ಹಾ');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'ಥೈಲ್ಯಾಂಡ್');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'ಥೈವಾನ್');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'ದಕ್ಷಿಣ ಆಫ್ರಿಕಾ');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'ದಕ್ಷಿಣ ಕೋರಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'ದಕ್ಷಿಣ ಜಾರ್ಜಿಯಾ ಮತ್ತು ದಕ್ಷಿಣ ಸ್ಯಾಂಡ್‌ವಿಚ್ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'ನಮೀಬಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'ನಾರ್‌ಫೋಕ್ ದ್ವೀಪ');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'ನಾರ್ವೇ');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'ನಿಕಾರಾಗುವಾ');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'ನಿಯು');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'ನೆದರ್‌ಲ್ಯಾಂಡ್');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'ನೆದರ್‌ಲ್ಯಾಂಡ್ಸ್');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'ನೇಪಾಳ');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'ನೈಜರ್');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'ನೈಜೀರಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'ನೌರು');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'ನ್ಯೂ ಕ್ಯಾಲಿಡೋನಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'ನ್ಯೂಜಿಲೆಂಡ್');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'ಪನಾಮಾ');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'ಪಪುವಾ ನ್ಯೂಗೀನಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'ಪರಾಗ್ವೇ');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'ಪಲಾವು');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'ಪಶ್ಚಿಮ ಸಹಾರಾ');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'ಪಾಕಿಸ್ತಾನ');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'ಪಿಟ್‌ಕೈರ್ನ್');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'ಪೂರ್ವ ತಿಮೋರ್');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'ಪೆರು');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'ಪೋರ್ಚುಗಲ್');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'ಪೋಲ್ಯಾಂಡ್');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'ಪ್ಯಾಲಿಸ್ಟೇನಿಯನ್ ಪ್ರದೇಶ');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'ಪ್ಯೂರ್ಟೋ ರಿಕೊ');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'ಫರೋ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'ಫಿಜಿ');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'ಫಿನ್‌ಲ್ಯಾಂಡ್');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'ಫಿಲಿಫೈನ್ಸ್');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'ಫ್ರಾನ್ಸ್');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'ಫ್ರೆಂಚ್ ಗಯಾನಾ');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'ಫ್ರೆಂಚ್ ದಕ್ಷಿಣ ಪ್ರದೇಶಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'ಫ್ರೆಂಚ್ ಪೋಲಿನೇಶಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'ಫ್ಹಾಕ್‌ಲ್ಯಾಂಡ್ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'ಬರ್ಮುಡಾ');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'ಬಲ್ಗೇರಿಯನ್');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'ಬಲ್ಗೇರಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'ಬಹರೈನ್');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'ಬಹಾಮಾಸ್');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'ಬಾಂಗ್ಲಾದೇಶ್');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'ಬಾರ್ಬಡೋಸ್');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'ಬುರುಂಡಿ');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'ಬುರ್ಕಿನಾ ಫಾಸೋ');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'ಬೆನಿನ್');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'ಬೆಲಿಜ್');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'ಬೆಲ್ಜಿಯಮ್');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'ಬೊಲಿವಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'ಬೋಟ್ಸ್‌ವಾನಾ');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'ಬೋವೆಟ್ ದ್ವೀಪ');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'ಬೋಸ್ನಿಯಾ ಮತ್ತು ಹರ್ಜೆಗೋವಿನಾ');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'ಬ್ರಿಟನ್/ಇಂಗ್ಲೆಂಡ್');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'ಬ್ರಿಟಿಷ್ ವರ್ಜಿನ್ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'ಬ್ರಿಟೀಶ್ ಇಂಡಿಯನ್ ಮಹಾಸಾಗರ ಪ್ರದೇಶ');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'ಬ್ರೂನಿ');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'ಬ್ರೆಜಿಲ್');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'ಭಾರತ');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'ಭೂತಾನ್');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'ಮಡಗಾಸ್ಕರ್');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'ಮಧ್ಯ ಆಫ್ರಿಕಾ ಗಣರಾಜ್ಯ');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'ಮಯನ್ಮಾರ್');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'ಮಯೊಟ್ಟೆ');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'ಮಲಾವಿ');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'ಮಲೇಶಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'ಮಾರಿಟಾನಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'ಮಾರಿಶಿಯಸ್');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'ಮಾರ್ಟಿನಿಕ್');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'ಮಾರ್ಶಲ್ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'ಮಾಲಿ');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'ಮಾಲ್ಟಾ');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'ಮಾಲ್ಡಿವ್ಸ್');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'ಮೆಕ್ವಾ SAR ಚೀನಾ');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'ಮೆಕ್ಸಿಕೊ');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'ಮೈಕ್ರೋನೇಶಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'ಮೊಂಗೋಲಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'ಮೊಂಟೆನೆಗ್ರೋ');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'ಮೊಜಾಂಬಿಕ್');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'ಮೊನಾಕೊ');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'ಮೊರಾಕ್ಕೊ');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'ಮೊಲ್ಡೋವಾ');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'ಮೋಂಟ್‌ಸೆರೆಟ್');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'ಮ್ಯಾಸಿಡೋನಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'ಯು.ಎಸ್. ವರ್ಜಿನ್ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'ಯುರೋಪಿಯನ್ ಯೂನಿಯನ್');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'ಯೆಮನ್');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'ರಶಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'ರೀಯೂನಿಯನ್');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'ರುವಾಂಡಾ');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'ರೊಮ್ಯಾನಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'ಲಕ್ಸಂಬರ್ಗ್');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'ಲಾಟ್ವಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'ಲಾವೋಸ್');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'ಲಿಚೆನ್‌ಸ್ಟೈನ್');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'ಲಿಥುವೇನಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'ಲಿಬಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'ಲಿಬೇರಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'ಲೆಥೋಸೊ');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'ಲೆಬನಾನ್');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'ವನೌಟು');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'ವಾಲಿಸ್ ಮತ್ತು ಫುಟುನಾ');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'ವಿಯೇಟ್ನಾಮ್');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'ವೆನೆಜುವೆಲಾ');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'ವ್ಯಾಟಿಕನ್');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'ಶ್ರೀಲಂಕಾ');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'ಸಂಯುಕ್ತ ಅರಬ್ ಎಮಿರೇಟಸ್');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'ಸಂಯುಕ್ತ ಸಂಸ್ಥಾನ ಮೈನರ್ ಔಟ್‌ಲೈಯಿಂಗ್ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'ಸಮೋವಾ');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'ಸಾವೋ ಟೋಮ್ ಮತ್ತು ಪ್ರಿನ್ಸಿಪೆ');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'ಸಿಂಗಪುರ');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'ಸಿಯೆರ್ರಾ ಲಿಯೋನ್');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'ಸಿರಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'ಸೀಶೆಲ್ಲೆಸ್');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'ಸುರಿನಾಮ');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'ಸೂಡಾನ್');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'ಸೆನೆಗಲ್');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'ಸೆಯುಟಾ ಹಾಗೂ ಮೆಲಿಲ್ಲಾ');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'ಸೆರ್ಬಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'ಸೆರ್ಬಿಯಾ ಮತ್ತು ಮೊಂಟೊನೆಗ್ರೋ');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'ಸೇಂಟ್ ಕಿಟ್ಸ್ ಮತ್ತು ನೆವಿಸ್');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'ಸೇಂಟ್ ಪಿಯರೆ ಮತ್ತು ಮಿಕೆಲನ್');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'ಸೇಂಟ್ ಬಾರ್ಥೆಲೆಮಿ');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'ಸೇಂಟ್ ಮಾರ್ಟಿನ್');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'ಸೇಂಟ್ ಲೂಸಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'ಸೇಂಟ್ ವಿನ್ಸೆಂಟ್ ಮತ್ತು ಗ್ರೆನೆಡೈನ್ಸ್');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'ಸೇಂಟ್ ಹೆಲೆನಾ');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'ಸೈಪ್ರಸ್');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'ಸೊಮಾಲಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'ಸೊಲೊಮನ್ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'ಸೌದಿ ಅರೇಬಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'ಸ್ಪೈನ್');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'ಸ್ಯಾನ್ ಮೆರಿನೋ');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'ಸ್ಲೋವಾಕಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'ಸ್ಲೋವೇನಿಯಾ');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'ಸ್ವಾಜಿಲ್ಯಾಂಡ್');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'ಸ್ವಾಲ್ಬಾರ್ಡ್ ಮತ್ತು ಜಾನ್ ಮಾಯೆನ್');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'ಸ್ವಿಡ್ಜರ್‌ಲ್ಯಾಂಡ್');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'ಸ್ವೀಡನ್');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'ಹಂಗೇರಿ');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'ಹರ್ಡ್ ದ್ವೀಪ ಮತ್ತು ಮಾಕ್‌ಡೊನಾಲ್ಡ್ ದ್ವೀಪಗಳು');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'ಹಾಂಗ್‌ ಕಾಂಗ್‌ SAR ಚೀನಾ');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'ಹೈಟಿ');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'ಹೊಂಡುರಾಸ್');
