CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('SH', 'Αγία Ελένη');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Αγία Λουκία');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'Άγιος Βαρθολομαίος');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Άγιος Βικέντιος και Γρεναδίνες');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'Άγιος Μαρίνος');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'Άγιος Μαρτίνος');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Αζερμπαϊτζάν');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Αίγυπτος');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Αιθιοπία');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Αϊτή');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Ακτή Ελεφαντοστού');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Αλβανία');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Αλγερία');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Αμερικανικές Παρθένοι Νήσοι');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Αμερικανική Σαμόα');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Ανατολικό Τιμόρ');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Ανγκόλα');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Ανγκουίλα');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Ανδόρα');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Ανταρκτική');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Αντίγκουα και Μπαρμπούντα');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'Απομακρυσμένες Νησίδες Η.Π.Α.');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Αργεντινή');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Αρμενία');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Αρούμπα');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Αυστραλία');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Αυστρία');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Αφγανιστάν');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Βανουάτου');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Βατικανό');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Βέλγιο');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Βενεζουέλα');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Βερμούδες');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Βιετνάμ');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Βολιβία');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Βόρεια Κορέα');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Βόρειες Μαριάνες Νήσοι');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Βοσνία - Ερζεγοβίνη');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Βουλγαρία');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Βραζιλία');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Βρετανικά Εδάφη Ινδικού Ωκεανού');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Βρετανικές Παρθένοι Νήσοι');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Γαλλία');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Γαλλικά Νότια Εδάφη');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Γαλλική Γουιάνα');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Γαλλική Πολυνησία');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Γερμανία');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Γεωργία');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Γιβραλτάρ');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Γκάμπια');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Γκαμπόν');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Γκάνα');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Γκερνσέι');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Γκουάμ');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Γουαδελούπη');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Γουατεμάλα');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Γουιάνα');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Γουινέα');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Γουινέα-Μπισάου');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Γρενάδα');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Γροιλανδία');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Δανία');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Δομινικανή Δημοκρατία');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Δυτική Σαχάρα');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Εκουαδόρ');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Ελ Σαλβαδόρ');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Ελβετία');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Ελλάδα');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Ερυθραία');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Εσθονία');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'Ευρωπαϊκή Ένωση');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Ζάμπια');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Ζιμπάμπουε');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Ζουαζηλάνδη');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Ηνωμένα Αραβικά Εμιράτα');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Ηνωμένες Πολιτείες της Αμερικής');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Ηνωμένο Βασίλειο');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'Θεούτα και Μελίλα');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Ιαπωνία');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Ινδία');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Ινδονησία');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Ιορδανία');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Ιράκ');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Ιράν');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Ιρλανδία');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Ισημερινή Γουινέα');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Ισλανδία');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Ισπανία');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Ισραήλ');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Ιταλία');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Καζακστάν');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Καμερούν');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Καμπότζη');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Καναδάς');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'Κανάριοι Νήσοι');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Κατάρ');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Κεντροαφρικανική Δημοκρατία');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Κένυα');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Κίνα');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Κιργιστάν');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Κιριμπάτι');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Κολομβία');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Κομόρος');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Κονγκό - Κινσάσα');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Κονγκό - Μπραζαβίλ');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Κόστα Ρίκα');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Κούβα');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Κουβέιτ');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Κροατία');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Κύπρος');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Λάος');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Λεσότο');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Λετονία');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Λευκορωσία');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Λίβανος');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Λιβερία');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Λιβύη');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Λιθουανία');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Λιχτενστάιν');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Λουξεμβούργο');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Μαγιότ');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Μαδαγασκάρη');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Μακάο ΕΔΠ Κίνας');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Μαλαισία');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Μαλάουι');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Μαλδίβες');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Μάλι');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Μάλτα');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Μαρόκο');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Μαρτινίκα');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Μαυρίκιος');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Μαυριτανία');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Μαυροβούνιο');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Μεξικό');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Μιανμάρ');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Μικρονησία');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Μογγολία');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Μοζαμβίκη');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Μολδαβία');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Μονακό');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Μονσεράτ');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Μπανγκλαντές');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Μπαρμπάντος');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Μπαχάμες');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Μπαχρέιν');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Μπελίσε');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Μπενίν');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Μποτσουάνα');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Μπουρκίνα Φάσο');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Μπουρούντι');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Μπουτάν');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Μπρουνέι');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Ναμίμπια');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Ναούρου');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Νέα Ζηλανδία');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Νέα Καληδονία');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Νεπάλ');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Νήσοι Άλαντ');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Νήσοι Κέιμαν');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Νήσοι Κόκος');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Νήσοι Κουκ');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Νήσοι Μάρσαλ');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Νήσοι Ουαλλίς και Φουτουνά');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Νήσοι Σολομώντος');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Νήσοι Τερκς και Κάικος');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Νήσοι Φερόε');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Νήσοι Φώκλαντ');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Νήσοι Χερντ και Μακντόναλντ');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'Νήσος Ασενσιόν');
INSERT INTO "country" ("id", "name") VALUES ('CP', 'Νήσος Κλίπερτον');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Νήσος Μαν');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Νήσος Μπουβέ');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Νήσος Νόρφολκ');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Νήσος Χριστουγέννων');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Νίγηρας');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Νιγηρία');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Νικαράγουα');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Νιούε');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Νορβηγία');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Νότια Αφρική');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'Νότια Γεωργία και Νότιες Νήσοι Σάντουιτς');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Νότια Κορέα');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'Ντιέγκο Γκαρσία');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Ντομίνικα');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Ολλανδία');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Ολλανδικές Αντίλλες');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Ομάν');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Ονδούρα');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Ουγγαρία');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Ουγκάντα');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Ουζμπεκιστάν');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ουκρανία');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Ουρουγουάη');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Πακιστάν');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Παλαιστινιακά Εδάφη');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Παλάου');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Παναμάς');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Παπούα Νέα Γουινέα');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Παραγουάη');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'ΠΓΔΜ');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'Περιφερειακή Ωκεανία');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Περού');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Πίτκερν');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Πολωνία');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Πορτογαλία');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Πουέρτο Ρίκο');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Πράσινο Ακρωτήριο');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Ρεϋνιόν');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ρουάντα');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Ρουμανία');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Ρωσία');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Σαιντ Κιτς και Νέβις');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Σαιντ Πιέρ και Μικελόν');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Σαμόα');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Σάο Τομέ και Πρίνσιπε');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Σαουδική Αραβία');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Σβάλμπαρντ και Νήσοι Γιάν Μέϋεν');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Σενεγάλη');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Σερβία');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Σερβία και Μαυροβούνιο');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Σεϋχέλλες');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Σιγκαπούρη');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Σιέρα Λεόνε');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Σλοβακία');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Σλοβενία');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Σομαλία');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Σουδάν');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Σουηδία');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Σουρινάμ');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Σρι Λάνκα');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Συρία');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Ταϊβάν');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Ταϊλάνδη');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Τανζανία');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Τατζικιστάν');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Τζαμάικα');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Τζιμπουτί');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Τόγκο');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Τοκελάου');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Τόνγκα');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Τουβαλού');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Τουρκία');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Τουρκμενιστάν');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Τρινιντάντ και Τομπάγκο');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'Τριστάν ντα Κούνια');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Τσαντ');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Τσεχία');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Τυνησία');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Υεμένη');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Υερσέη');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Φιλιππίνες');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Φινλανδία');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Φίτζι');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Χιλή');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Χονγκ Κονγκ ΕΔΠ Κίνας');
