CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afganistáni');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Albania');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Aljeria');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Alémani');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andora');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angóla');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigua mpé Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Argentina');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Bielorusia');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnia na Erzegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswana');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Bresíli');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgaria');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Butáni');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bángaladɛ́si');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Bɛ́ljika');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Djibuti');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Ejipti');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Espania');
INSERT INTO [country] ([id], [name]) VALUES ('ZZ', 'Esíká eyébámí tɛ́');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Etazíni');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiopya');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Falansia');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finilanda');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambia');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ghana');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Gibraltar');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Gine');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Gine-Bisau');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Gresi');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Holanda');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indoneziá');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Ingɛlɛ́tɛlɛ');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Irlandí');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Islandi');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Italia');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'KI');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kamerun');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanadá');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazakstáni');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenya');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kirghizistáni');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongó-Brazzaville');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Kongó-Kinsásá');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Kore ya Nola');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Kore ya Sidi');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Kroasia');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Letoni');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Liban');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberia');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libíya');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Litwani');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Luksamburg');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Madívi');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Makau');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Masedoni');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongolí');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambíki');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibia');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepáli');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nijeria');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Nijé');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norvej');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistáni');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Poloni');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Pulutugal');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Republiki Sheki');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Rumania');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rusí');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Rwanda');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Sahara ya límbe');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Santrafríka');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Santu Helena');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'Santu Marino');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Sidafríka');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Sirí');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somalia');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudani');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Swisi');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Swési');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Sína');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Sǎo Tomé na Principe');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwan');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tazikistáni');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidad mpé Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunizia');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turkmenistáni');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Turkí');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Ungri');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Uzbekistáni');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatikáni');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietnami');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Yapan');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yeméni');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambia');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabwe');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Zordaní');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Ɛndɛ');
