CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afganistán');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Åland Islands');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albania');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Alemania');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andorra');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anguilla');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Antarctica');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua & Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Arabia Saudí');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Argelia');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Argentina');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armenia');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'Ascension Island');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Australia');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Austria');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azerbaiyán');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahamas');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahréin');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladesh');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbados');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Belarús');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Bélgica');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belize');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benín');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermuda');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolivia');
INSERT INTO "country" ("id", "name") VALUES ('BQ', 'Bonaire');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosnia & Herzegovina');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botsuana');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brasil');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'British Virgin Islands');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brunéi');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulgaria');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burkina Faso');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Bután');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Camboya');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Camerún');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Canada');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'Canary Islands');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Cape Verde');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Cayman Islands');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Central African Republic');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'Ceuta & Melilla');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Chad');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Chile');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'China');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Chipre');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Colombia');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Comoras');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Congo');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Congo (RDC)');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Cook Islands');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Corea del Norte');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Corea del Sur');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Costa Rica');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Côte dʼIvoire');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Croacia');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Cuba');
INSERT INTO "country" ("id", "name") VALUES ('CW', 'Curazao');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Czech Republic');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'Diego Garcia');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Dinamarca');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominica');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Dominican Republic');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ecuador');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'EE.UU. Islas Vírgenes');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Egipto');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'El Salvador');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritrea');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'ERY Macedonia');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Eslovaquia');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Eslovenia');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'España');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Estados Unidos');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Estonia');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Etiopía');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Falkland Islands');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Faroe Islands');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filipinas');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finlandia');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fiyi');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Francia');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'French Guiana');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabón');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambia');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Georgia');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Ghana');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Gibraltar');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Grecia');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Greenland');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenada');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadeloupe');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatemala');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Guernsey');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Guinea');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Guinea Ecuatorial');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Guinea-Bissau');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guyana');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haití');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduras');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Hong Kong (RAE)');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Hungary');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'India');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indonesia');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Irán');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Iraq');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Ireland');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Isla Christmas');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Isla Norfolk');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Islandia');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Islas Cocos');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Islas Marianas del Norte');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Islas Marshall');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'Islas menores alejadas de los EE.UU.');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Islas Pitcairn');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Isle of Man');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Israel');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Italia');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamaica');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japan');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Jersey');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jordania');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazajistan');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenia');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirguistán');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('XK', 'Kosovo');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kuwait');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laos');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesoto');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Letonia');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Líbano');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberia');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libya');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Liechtenstein');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Lituania');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luxemburgo');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Macao RAE');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagascar');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malawi');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malaysia');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldivas');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Malí');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Marruecos');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martinique');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Mauricio');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mauritania');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayotte');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'México');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Micronesia');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldova');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Mónaco');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongolia');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Montserrat');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mozambique');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Myanmar');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibia');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepal');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'New Zealand');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nicaragua');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Níger');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nigeria');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Noruega');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Nueva Caledonia');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Omán');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Países Bajos');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakistán');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palaos');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palestina Kamachikuq');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panamá');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papúa Nueva Guinea');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguay');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Perú');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Polinesia Francesa');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Polonia');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portugal');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Puerto Rico');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Qatar');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Reino Unido');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Réunion');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Romania');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ruanda');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Rusia');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samoa');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Samoa Americana');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'San Cristóbal y Nieves');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'San Marino');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'San Martín');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'San Pedro y Miquelón');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Santa Sede (Ciudad del Vaticano)');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Santo Tomé y Príncipe');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegal');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Serbia');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Seychelles');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Sierra Leona');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapur');
INSERT INTO "country" ("id", "name") VALUES ('SX', 'Sint Maarten');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Siria');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Solomon Islands');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somalia');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'South Georgia & South Sandwich Islands');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'St. Barthélemy');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'St. Helena');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'St. Lucia');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'St. Vincent & Grenadines');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Suazilandia');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Sudáfrica');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudán');
INSERT INTO "country" ("id", "name") VALUES ('SS', 'Sudán del Sur');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Suecia');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Suiza');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Surinam');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Svalbard & Jan Mayen');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Tailandia');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taiwan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzania');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tayikistán');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Tierras Australes y Antárticas Francesas');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Timor-Leste');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad y Tobago');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'Tristan da Cunha');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Túnez');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turkmenistan');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Turks & Caicos Islands');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Turquía');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uganda');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukraine');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'United Arab Emirates');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruguay');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Uzbekistán');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezuela');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vietnam');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis, Futuna');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Western Sahara');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Yemen');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Yibuti');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambia');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabue');
