CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afganistan');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albanía');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Alsír');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andorra');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angóla');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Angvilla');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antígva og Barbúda');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Argentína');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armenía');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Arúba');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'Ascension-eyja');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Aserbaídsjan');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Austur-Kongó');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Austur-Tímor');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Austurríki');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Álandseyjar');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Ástralía');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahamaeyjar');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Bandaríkin');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Bandaríska Samóa');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Bandarísku Jómfrúaeyjar');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladess');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbados');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Barein');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Belgía');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belís');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benín');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermúdaeyjar');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosnía og Hersegóvína');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botsvana');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Bouveteyja');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bólivía');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brasilía');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Bresku Indlandshafseyjar');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Bresku Jómfrúaeyjar');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Bretland');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brúnei');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Búlgaría');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Búrkína Fasó');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Búrúndí');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Bútan');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Caymaneyjar');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'Ceuta og Melilla');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Chíle');
INSERT INTO "country" ("id", "name") VALUES ('CP', 'Clipperton-eyja');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Cookseyjar');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Danmörk');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'Diego Garcia');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Djíbútí');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dóminíka');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Dóminíska lýðveldið');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Egyptaland');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Eistland');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekvador');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'El Salvador');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Erítrea');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'Evrópusambandið');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Eþíópía');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Falklandseyjar');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filippseyjar');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finnland');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fídjieyjar');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Fílabeinsströndin');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Frakkland');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Franska Gvæjana');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Franska Pólýnesía');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Frönsku suðlægu landsvæðin');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Færeyjar');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabon');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambía');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Gana');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Georgía');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Gíbraltar');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Gínea');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Gínea-Bissá');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenada');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Grikkland');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Grænhöfðaeyjar');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Grænland');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Guernsey');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Gvadelúpeyjar');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Gvam');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Gvatemala');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Gvæjana');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haítí');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Heard og McDonaldseyjar');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Hollensku Antillur');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Hondúras');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Hong Kong');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Hvíta-Rússland');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Indland');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indónesía');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Írak');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Íran');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Írland');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Ísland');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Ísrael');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Ítalía');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamaíka');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japan');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Jemen');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Jersey');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Jólaey');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jórdanía');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kambódía');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamerún');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'Kanaríeyjar');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kasakstan');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Katar');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenía');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirgisistan');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Kína');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kíribatí');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kostaríka');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Kókoseyjar');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kólumbía');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Kómoreyjar');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Króatía');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kúba');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kúveit');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Kýpur');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laos');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesótó');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Lettland');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Liechtenstein');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Litháen');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Líbanon');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Líbería');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Líbía');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Lúxemborg');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagaskar');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Makaó');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Makedónía');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malasía');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malaví');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldíveyjar');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Malí');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Marokkó');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Marshalleyjar');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martiník');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayotte');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Máritanía');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Máritíus');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mexíkó');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Mið-Afríkulýðveldið');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Miðbaugs-Gínea');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikrónesía');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Mjanmar');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldóva');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongólía');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Montserrat');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Mónakó');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mósambík');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Mön');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibía');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nárú');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepal');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Niðurlönd');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Níger');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nígería');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Níkaragva');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Norður-Kórea');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Norður-Maríanaeyjar');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Noregur');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Norfolkeyja');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Nýja-Kaledónía');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Nýja-Sjáland');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Óman');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakistan');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palá');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palestína');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papúa Nýja-Gínea');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paragvæ');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Páfagarður');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Perú');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitcairn');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portúgal');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Pólland');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Púertó Ríkó');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Réunion');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Rúanda');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Rúmenía');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Rússland');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'Saint Barthélemy');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'Saint Martin');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Salómonseyjar');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Sambía');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Sameinuðu arabísku furstadæmin');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samóa');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'San Marínó');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Sankti Helena');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Sankti Kristófer og Nevis');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Sankti Lúsía');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Sankti Pierre og Miquelon');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Sankti Vinsent og Grenadíneyjar');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Saó Tóme og Prinsípe');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Sádi-Arabía');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegal');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Serbía');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Serbía og Svartfjallaland');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Seychelleseyjar');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Simbabve');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapúr');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Síerra Leóne');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slóvakía');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Slóvenía');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'Smáeyjar Bandaríkjanna');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Sómalía');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Spánn');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Srí Lanka');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Suður-Afríka');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'Suður-Georgía og Suður-Sandvíkureyjar');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Suður-Kórea');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Suðurskautslandið');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Súdan');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Súrínam');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Svalbarði og Jan Mayen');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Svartfjallaland');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Svasíland');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Sviss');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Svíþjóð');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Sýrland');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tadsjikistan');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Taíland');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taívan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tansanía');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Tékkland');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Tógó');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tókelá');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'Tristan da Cunha');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trínidad og Tóbagó');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Tsjad');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Turks- og Caicoseyjar');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Túnis');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Túrkmenistan');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Túvalú');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Tyrkland');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Ungverjaland');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Úganda');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Úkraína');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Úrúgvæ');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Úsbekistan');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanúatú');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venesúela');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Vestur-Kongó');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Vestur-Sahara');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Víetnam');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis- og Fútúnaeyjar');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'Ytri Eyjaálfa');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Þýskaland');
