CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('SA', 'Abari Saudi');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afganistan');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albani');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Almaañ');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Alseri');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andorra');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Angiiya');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua di Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armeni');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Arsantin');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Aserbaysan');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Ayti');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahama');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahrayn');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Banglades');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbad');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Belarus');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Beliis');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Belsik');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Bene');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermud');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Boliivi');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosni di Hersegovin');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Boswana');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Bresil');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulgari');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burukiina Faso');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Buruney');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Butan');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Cad');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Cili');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Danmark');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominika');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Ecoopi');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekuador');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'End');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Endonesi');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritree');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Esípt');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Espaañ');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Estoni');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fiji');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finland');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Frans');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Gaana');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabon');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambi');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Giné');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Giné Bisaau');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Giyan');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Greenland');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenada');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Gres');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatemala');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guwadalup');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Iisland');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Irak');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Iran');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Irland');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Israel');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Itali');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Jibuti');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kamboj');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamerun');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Kap Ver');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Keniya');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Koddiwar');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolombi');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komor');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kosta Rika');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Kroasi');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kuba');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberia');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagaskaar');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Mofam demokratik mati Kongo');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Mofam mati Cek');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Mofam mati Dominik');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Onduras');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Oŋri');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Ostraalia');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Otris');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Salvadoor');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Samaik');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Samoa yati Amerik');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'San Marin');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Sapoŋ');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegal');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Seorsi');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Serra Leon');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Siin');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Siipr');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapur');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Sipraltaar');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Siri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slovaki');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Sloveni');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somali');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudan');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Tailand');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Tansani');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
