CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afghanistan');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Africa dal Sid');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albania');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Algeria');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andorra');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguilla');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Antarctica');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigua e Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Antillas Ollandaisas');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Arabia Saudita');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Argentinia');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armenia');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Aserbaidschan');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Australia');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Austria');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamas');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahrain');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladesch');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbados');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Belgia');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belize');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benin');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermudas');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Bhutan');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Bielorussia');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolivia');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnia ed Erzegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswana');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brasila');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunei');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgaria');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Cambodscha');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Camerun');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Canada');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Cap Verd');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Chile');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'China');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Cipra');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Citad dal Vatican');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Columbia');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Comoras');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Congo');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Corea dal Nord');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Corea dal Sid');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Costa d''Ivur');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Costa Rica');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Croazia');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Cuba');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Danemarc');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominica');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Dschibuti');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ecuador');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Egipta');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'El Salvador');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Emirats Arabs Unids');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritrea');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estonia');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiopia');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fidschi');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filippinas');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finlanda');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Frantscha');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabun');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambia');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Georgia');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Georgia dal Sid e las Inslas Sandwich dal Sid');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Germania');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ghana');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Giamaica');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Giapun');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Gibraltar');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grenada');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Grezia');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Grönlanda');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Guadeloupe');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guam');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Guatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Guernsey');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Guinea Equatoriala');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyana');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Guyana Franzosa');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haiti');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Honduras');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'India');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonesia');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Insla Bouvet');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Insla da Christmas');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Insla da Man');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Insla Norfolk');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Inslas Aland');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Inslas Cayman');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Inslas Cocos');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Inslas Cook');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'Inslas da Heard e da McDonlad');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Inslas da Marshall');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Inslas dal Falkland');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Inslas Feroe');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Inslas Mariannas dal Nord');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Inslas pitschnas perifericas dals Stadis Unids da l''America');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Inslas Turks e Caicos');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Inslas Verginas Americanas');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Inslas Verginas Britannicas');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Irac');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Iran');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Irlanda');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Islanda');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Israel');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Italia');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Jemen');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Jersey');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Jordania');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kasachstan');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Katar');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenia');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kirghisistan');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuwait');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laos');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesotho');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Lettonia');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Libanon');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberia');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libia');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Liechtenstein');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lituania');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Luxemburg');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Macedonia');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagascar');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malaisia');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawi');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maldivas');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Maroc');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martinique');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mauretania');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Mauritius');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayotte');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mexico');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Micronesia');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Moldavia');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monaco');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongolia');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Montenegro');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montserrat');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mosambic');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myanmar');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibia');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nauru');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepal');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nicaragua');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Niger');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nigeria');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niue');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norvegia');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Nova Caledonia');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Nova Zelanda');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'Oceania Periferica');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Oman');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Pajais Bass');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistan');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papua Nova Guinea');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguai');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peru');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitcairn');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Polinesia Franzosa');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Pologna');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portugal');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Puerto Rico');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Reginavel Unì');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Regiun d''administraziun speziala da Hongkong, China');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Regiun d''administraziun speziala Macao, China');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Republica Centralafricana');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Republica Democratica dal Congo');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Republica Dominicana');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Republica Tscheca');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Réunion');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Ruanda');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Rumenia');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Russia');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Sahara Occidentala');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Saint Kitts e Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Saint Lucia');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Saint Martin');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Saint Pierre e Miquelon');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Saint Vincent e las Grenadinas');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Salomonas');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Sambia');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samoa Americana');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marino');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'São Tomé e Principe');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegal');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Serbia');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Serbia e Montenegro');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seychellas');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sierra Leone');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Simbabwe');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapur');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Siria');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovachia');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slovenia');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somalia');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Son Barthélemy');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Sontg''Elena');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Spagna');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Stadis Unids da l''America');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudan');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinam');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Svalbard e Jan Mayen');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Svezia');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Svizra');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Swaziland');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tadschikistan');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Tailanda');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwan');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tansania');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Territori Britannic en l''Ocean Indic');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Territori Palestinais');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Territoris Franzos Meridiunals');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timor da l''Ost');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Tirchia');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidad e Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Tschad');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunesia');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turkmenistan');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ucraina');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Ungaria');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'Uniun europeica');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruguay');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Usbekistan');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuela');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietnam');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wallis e Futuna');
