CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Afrika Kusini');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afuganistani');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Aislandi');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Ajentina');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albania');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Aljeria');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Amerika');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andora');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Anguilla');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigua na Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Antili za Uholanzi');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armenia');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Australia');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Austria');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Ayalandi');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azabajani');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Babadosi');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahama');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahareni');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladeshi');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Belarusi');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benini');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolivia');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosnia na Hezegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brazili');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Bukinafaso');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Bukini');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgaria');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Butani');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Caina');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Chadi');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Chile');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Denmaki');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominika');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ekwado');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Elsavado');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Eneo la Uingereza katika Bahari Hindi');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritrea');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estonia');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Falme za Kiarabu');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fiji');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filipino');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gaboni');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Gine');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Ginebisau');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Ginekweta');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Grinlandi');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Gwadelupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Gwam');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Gwatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Gwiyana ya Ufaransa');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Hispania');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Hondurasi');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Hungaria');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'India');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonesia');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Iraki');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Israeli');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italia');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaika');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Jamhuri ya Afrika ya Kati');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Jamhuri ya Cheki');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Jamhuri ya Dominika');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Jamhuri ya Kidemokrasia ya Kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Jibralta');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Jibuti');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Jojia');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambodia');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kameruni');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Katari');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazakistani');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Kepuvede');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirigizistani');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Kisiwa cha Norfok');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kiumba');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Kodivaa');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolombia');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Komoro');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Korasia');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Korea Kaskazini');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Korea Kusini');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Kostarika');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Kuprosi');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuwaiti');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laosi');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Lasembagi');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Lativia');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Lebanoni');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesoto');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberia');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libya');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Lishenteni');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Litwania');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malesia');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martiniki');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Masedonia');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayotte');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Mburundi');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Meksiko');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikronesia');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Misri');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Modivu');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldova');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monako');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongolia');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrati');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Morisi');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Moritania');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Moroko');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Msumbiji');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Myama');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nainjeria');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namimbia');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepali');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ngana');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Ngeretha');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Nijeri');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikaragwa');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Njabani');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Njeremani');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Njorondani');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norwe');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Nyukaledonia');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Nyuzilandi');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Omani');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistani');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papua');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paragwai');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitkairni');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Polandi');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Polinesia ya Ufaransa');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Pwetoriko');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Riyunioni');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romania');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Rwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'Samarino');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Samoa ya Marekani');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Santahelena');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Santakitzi na Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Santalusia');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Santapieri na Mikeloni');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Santavisenti na Grenadini');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Sao Tome na Principe');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Saudi');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegali');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Serbia na Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Shelisheli');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Siera Leoni');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapoo');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Siria');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sirilanka');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Slovakia');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Slovenia');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somaria');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudani');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Surinamu');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Tailandi');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwani');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tajikistani');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzania');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Timori ya Mashariki');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad na Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunisia');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turukimenistani');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Uajemi');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Ubaranja');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Ubelgiji');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Ufini');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Ugiriki');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Uhabeshi');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Uholanzi');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Ukingo wa Magharibi na Ukanda wa Gaza wa Palestina');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukraini');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Ureno');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Urugwai');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Urusi');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Uswazi');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Uswidi');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Uswisi');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Uturuki');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzibekistani');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatikani');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vietinamu');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Visiwa vya Cook');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Visiwa vya Falkland');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Visiwa vya Kayman');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Visiwa vya Mariana vya Kaskazini');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Visiwa vya Marshal');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Visiwa vya Solomon');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Visiwa vya Turki na Kaiko');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Visiwa vya Virgin vya Marekani');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Visiwa vya Virgin vya Uingereza');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Walis na Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Yemeni');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambia');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
