CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Австралия');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Австрия');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'АҚШ Вирджиния ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'АҚШ ёндош ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Аланд ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Албания');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Америка Самоаси');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Ангила');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Ангола');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Андорра');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Антарктика');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Антигуа ва Барбадос');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Аргентина');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Арманистон');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Аруба');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Афғонистон');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Багама ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Бангладеш');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Барбадос');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Баҳрайн');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Белиз');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Белорусия');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Бельгия');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Бенин');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Бермуда');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Бирлашган Араб Амирликлари');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Бирлашган Қироллик');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Болгария');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Боливия');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Босния ва Герцеговина');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Ботсванна');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Бразилия');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Британия Вирджиния ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Британия Ҳинд океани ҳудуди');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Бруней');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Буркина-Фасо');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Бурунди');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Бутан');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Вануату');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Ватикан');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Венгрия');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Венесуэла');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Вознесение ороли');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Вьетнам');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Габон');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Гаити');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Гамбия');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Гана');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Гаяна');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Гваделупе');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Гватемала');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Гвинея');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Гвинея-Бисау');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Гернси');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Гибралтар');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Гондурас');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'Гонконг Хитой ММҲ');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Гренада');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Гренландия');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Греция');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Грузия');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Гуам');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Ғарбий Саҳрои Кабир');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Дания');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Джерси');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Джибути');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Диего Гарсия');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Доминика');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Доминикан Республикаси');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Жазоир');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Жанубий Африка');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Жанубий Джорджия ва Жанубий Сендвич ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Жанубий Корея');
INSERT INTO [country] ([id], [name]) VALUES ('SS', 'Жанубий Судан');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Замбия');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Зимбабве');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Индонезия');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Иордания');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Ирландия');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Ироқ');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Исландия');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Испания');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Исроил');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Италия');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Кабо-Верде');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Кайман ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Камбоджа');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Камерун');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Канада');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Канар ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('BQ', 'Кариб Нидерландияси');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Кения');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Кипр');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Кирибати');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Кокос (Килинг) ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Колумбия');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Комор ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Конго Браззавиль');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Конго-Киншаса');
INSERT INTO [country] ([id], [name]) VALUES ('XK', 'Косово');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Коста-Рика');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Кот-д-Ивуар');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Куба');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Кувайт');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Кук ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('CW', 'Курасао');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Қатар');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Қирғизистон');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Қозоғистон');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Қўшма Штатлар');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Лаос');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Латвия');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Лесото');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Либерия');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Ливан');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Ливия');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Литва');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Лихтенштейн');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Люксембург');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Маврикий');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Мавритания');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Мадагаскар');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Майотта');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'Макао Хитой ММҲ');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Македония');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Малави');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Малайзия');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Мали');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Мальдив ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Мальта');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Марказий Африка Республикаси');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Марокаш');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Мартиника');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Маршал ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Мексика');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Микронезия');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Миср');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Мозамбик');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Молдова');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Монако');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Монтсеррат');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Муғулистон');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Муқаддас Варфаломей');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Муқаддас Елена ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Мьянма (Бирма)');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Мэн ороли');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Намибия');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Науру');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Непал');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Нигер');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Нигерия');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Нидерландия');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Никарагуа');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Ниуе');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Норвегия');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Норфолк ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Озарбайжон');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Олмония');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Палау');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Панама');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Папуа Янги Гвинея');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Парагвай');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Перу');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Питкарин ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Покистон');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Польша');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Португалия');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Пуэрто-Рико');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Реюньон');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Рождество ороли');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Россия');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Руанда');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Руминия');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Савльбард ва Жан Маен');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Самоа');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'Сан-Марино');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Сан-Томе ва Принсипи');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Саудия Арабистони');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Свазиленд');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Сейта ва Мелилла');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Сейшел ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Сенегал');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Сент-Винсент ва Гренадин');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Сент-Китс ва Невис');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Сент-Люсия');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Сент-Мартин');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Сент-Пьер ва Микелон');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Сербия');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Сингапур');
INSERT INTO [country] ([id], [name]) VALUES ('SX', 'Синт-Маартен');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Словакия');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Словения');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Соломон ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Сомали');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Судан');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Суринам');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Сурия');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Сьерра-Леоне');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Тайван');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Тайланд');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Танзания');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Того');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Тожикистон');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Токелау');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Тонга');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Тринидад ва Тобаго');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Тристан де Куна');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Тувалу');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Тунис');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Туркия');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Туркманистон');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Туркс ва Кайкос ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Уганда');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Украина');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Уммон');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Уругвай');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Уэллис ва Футуна');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Ўзбекистон');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Фаластин ҳудуди');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Фарер ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Фижи ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Филиппин');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Финляндия');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Фолькленд ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Франция');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Франция жанубий худудлари');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Француз Гвианаси');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Француз Полинезияси');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Хитой');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Хорватия');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Ҳиндистон');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Чад');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Черногория');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Чехия Республикаси');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Чили');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Шарқий-Тимор');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Швейцария');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Швеция');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Шимолий Корея');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Шимолий Марианна ороллари');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Шри-Ланка');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Эквадор');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Экваториал Гвинея');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Эль-Сальвадор');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Эритрея');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Эрон');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Эстония');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Эфиопия');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Ямайка');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Яман');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Янги Зеландия');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Янги Каледония');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Япония');
