CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afganistan');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Africa de Sud');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albania');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Algeria');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andorra');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguilla');
INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'Antarctica');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigua și Barbuda');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Antilele Olandeze');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Arabia Saudită');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Argentina');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armenia');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Australia');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Austria');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azerbaidjan');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamas');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahrain');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladesh');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbados');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Belgia');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Belize');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benin');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bermuda');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Bhutan');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Bielorusia');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolivia');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnia și Herțegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswana');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brazilia');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunei');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgaria');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Cambodgia');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Camerun');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Canada');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Capul Verde');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'Ceuta şi Melilla');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Chile');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'China');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Ciad');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Cipru');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Coasta de Fildeș');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Columbia');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Comore');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Congo');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Coreea de Nord');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Coreea de Sud');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Costa Rica');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Croația');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Cuba');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Danemarca');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'Diego Garcia');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Djibouti');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominica');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ecuador');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Egipt');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'El Salvador');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Elveția');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Emiratele Arabe Unite');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Eritreea');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Estonia');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiopia');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fiji');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipine');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finlanda');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Franța');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabon');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambia');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Georgia');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'Georgia de Sud şi Insulele Sandwich de Sud');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Germania');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ghana');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Gibraltar');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Grecia');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grenada');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Groenlanda');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Guadelupa');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guam');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Guatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'Guernsey');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Guineea');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Guineea Ecuatorială');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Guineea-Bissau');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyana');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Guyana Franceză');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haiti');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Honduras');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'India');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonezia');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'Insula Ascension');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'Insula Bouvet');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'Insula Christmas');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'Insula Clipperton');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'Insula Heard și Insulele McDonald');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'Insula Man');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'Insulele Aland');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'Insulele Canare');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Insulele Cayman');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'Insulele Cocos');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Insulele Cook');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Insulele Falkland');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'Insulele Feroe');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Insulele Mariane de Nord');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Insulele Marshall');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'Insulele Minore Îndepărtate ale Statelor Unite ale Americii');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Insulele Norfolk');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Insulele Solomon');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Insulele Turks și Caicos');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Insulele Virgine Britanice');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Insulele Virgine S.U.A.');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Iordania');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Irak');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Iran');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Irlanda');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Islanda');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Israel');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Italia');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jamaica');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Japonia');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'Jersey');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazahstan');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kârgâzstan');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kenya');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuweit');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laos');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesotho');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Letonia');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Liban');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberia');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libia');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Liechtenstein');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lituania');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Luxemburg');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Macedonia');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagascar');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malaezia');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawi');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maldive');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Marea Britanie');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Maroc');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martinica');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mauritania');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Mauritius');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayotte');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mexic');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Micronezia');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monaco');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mongolia');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Montserrat');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambic');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'Muntenegru');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myanmar');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibia');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Nauru');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepal');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nicaragua');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Niger');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nigeria');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niue');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Norvegia');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Noua Caledonie');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Noua Zeelandă');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'Oceania Periferică');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Olanda');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Oman');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistan');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papua Noua Guinee');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguay');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peru');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitcairn');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Polinezia Franceză');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Polonia');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Porto Rico');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Portugalia');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Qatar');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'R.A.S. Hong Kong a Chinei');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'R.A.S. Macao a Chinei');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Republica Cehă');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Republica Centrafricană');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Republica Democrată Congo');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Republica Dominicană');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Republica Moldova');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Reunion');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'România');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rusia');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Rwanda');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'Sahara Occidentală');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samoa Americană');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marino');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Sao Tome și Principe');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegal');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'Serbia');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Serbia și Muntenegru');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seychelles');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Sfânta Elena');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Sfânta Lucia');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'Sfântul Bartolomeu');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Sfântul Kitts și Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'Sfântul Martin');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Sfântul Pierre și Miquelon');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Sfântul Vincent și Grenadine');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sierra Leone');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapore');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Siria');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovacia');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slovenia');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somalia');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Spania');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Statele Unite ale Americii');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudan');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Suedia');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinam');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'Svalbard și Jan Mayen');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Swaziland');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tadjikistan');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwan');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzania');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'Teritoriile Australe și Antarctice Franceze');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Teritoriul Britanic din Oceanul Indian');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Teritoriul Palestinian');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Thailanda');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timorul de Est');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidad-Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunisia');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Turcia');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turkmenistan');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ucraina');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Ungaria');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'Uniunea Europeană');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruguay');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Uzbekistan');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatican');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuela');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Vietnam');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wallis și Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yemen');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambia');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabwe');
