CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afiganistaŋ');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Alibani');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Alimaɲi');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Alizeri');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Ameriki');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Ameriki ka Sungurunnin Gun');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andɔr');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Angilɛ ka ɛndu dugukolo');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Angilɛ ka Sungurunnin Gun');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Angilɛtɛri');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Angiya');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antiga-ni-Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Arabiya Sawudiya');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Arabu mara kafoli');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Arimeni');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Arizantin');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Ayiti');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azɛrbayjaŋ');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahamasi');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Bama Gun');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbadi');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bareyini');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Belarusi');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belizi');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benɛn');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Berezili');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermudi');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Bɛliziki');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bɛngiladɛsi');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolivi');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bozni-Ɛrizigovini');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Bɔtisiwana');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Buligari');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Burinɛyi');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burukina Faso');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Butaŋ');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Cadi');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Capivɛrdi');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Ceki republiki');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Cipri');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Danemarki');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Dɔmimiki republiki');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dɔminiki');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekwatɔr');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritere');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Esetoni');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Esipaɲi');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Etiopi');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Eziputi');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Ɛlɛni Senu');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Ɛndonezi');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Ɛndujamana');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Faransi');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Faransi ka gwiyani');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Faransi ka polinezi');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fiji');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filipini');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finilandi');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabɔŋ');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Gana');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Ganbi');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Gɛrɛsi');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Gine');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Gine Bisawo');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Gine ekwatɔri');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Gɔrɔhenelandi');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Granadi');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Gwadelup');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Gwam');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Gwatemala');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Gwiyana');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Hɔndirasi');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Hɔngri');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Iraki');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Iraŋ');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Irilandi');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Irisi');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Isilandi');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Isirayeli');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Itali');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Jibuti');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Kaledoni Koura');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kamboji');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kameruni');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Katari');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazakistaŋ');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Keniya');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Kɛɲɛka Kore');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Kɛɲɛka Mariyani Gun');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirigizisitaŋ');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Kodiwari');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolombi');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komɔri');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongo');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Kongo ka republiki demɔkratiki');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kowɛti');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Kɔrɔn Timɔr');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kɔsitarika');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Kristɔfo-Senu-ni-Ɲevɛs');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Kroasi');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kuba');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Kuki Gun');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Layosi');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesoto');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Letoni');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Libaŋ');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Liberiya');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libi');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Likisanburu');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Lisɛnsitayini');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Lituyani');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Lusi-Senu');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Macedɔni');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagasikari');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malawi');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldivi');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malɛzi');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malti');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Maluwini Gun');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'Marini-Senu');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Marisali Gun');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Maritiniki');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Marɔku');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayoti');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Meksiki');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikironesi');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Molidavi');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monako');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Moŋoli');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Moŋsera');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Morisi');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mozanbiki');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mɔritani');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Myanimari');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibi');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nawuru');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepali');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikaragwa');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nizeriya');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Nizɛri');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Nɔriwɛzi');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Nɔrofoliki Gun');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Nyuwe');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Omaŋ');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Ositirali');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Otirisi');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakisitaŋ');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palawu');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palesitini');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papuwasi-Gine-Koura');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguwayi');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Peru');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Peyiba');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Peyiba ka Antiyi');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitikarini');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Piyɛri-Senu-ni-Mikelɔŋ');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Poloɲi');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Pɔritigali');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Pɔrotoriko');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Reyuɲɔŋ');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Rumani');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ruwanda');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Salivadɔr');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Salomo Gun');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samowa');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Samowa amerikani');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Santarafiriki');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sawo Tome-ni-Prinicipe');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegali');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Serbi-ni-Mɔntenegro');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Sesɛli');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Sɛngapuri');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Sili');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Siniwajamana');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Siri');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sirilanka');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Siyera Lewɔni');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Sloveni');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slowaki');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somali');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudaŋ');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Surinami');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Suwɛdi');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Suwisi');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Swazilandi');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tajikisitani');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzani');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Tayilandi');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Tayiwani');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelo');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinite-ni-Tobago');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunizi');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Turiki');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Turiki Gun ni Kayiki');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turikimenisitani');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uganda');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukɛrɛni');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Urugwayi');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Uzebekisitani');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuwatu');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikaŋ');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezuwela');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Vinisɛn-Senu-ni-Grenadini');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Walisi-ni-Futuna');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Wiyɛtinamu');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Worodugu Afriki');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Worodugu Kore');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Yemɛni');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Zamayiki');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zanbi');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Zapɔn');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Zelandi Koura');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Zeyɔrzi');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Zibralitari');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabuwe');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Zɔrdani');
