CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AX', 'Åland Islands');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Algeria');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'American Samoa');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anguilla');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'Ascension Island');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azerbaijan');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahrain');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'British Virgin Islands');
INSERT INTO "country" ("id", "name") VALUES ('BQ', 'Caribbean Netherlands');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'Ceuta & Melilla');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Christmas Island');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Congo - Brazzaville');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Cyprus');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'Diego Garcia');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'French Southern Territories');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Hong Kong SAR China');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Iraq');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Isle of Man');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jordan');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazakhstan');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kuwait');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kyrgyzstan');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Macau SAR China');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'North Korea');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Oman');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palestinian Territories');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Saudi Arabia');
INSERT INTO "country" ("id", "name") VALUES ('SX', 'Sint Maarten');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'South Georgia & South Sandwich Islands');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'South Korea');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'St. Barthélemy');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'St. Kitts & Nevis');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'St. Lucia');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'St. Martin');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'St. Pierre & Miquelon');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'St. Vincent & Grenadines');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Svalbard & Jan Mayen');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taiwan');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tajikistan');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Timor-Leste');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'Tristan da Cunha');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Turks & Caicos Islands');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'U.S. Outlying Islands');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'U.S. Virgin Islands');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'United Arab Emirates');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Uzbekistan');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis & Futuna');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Western Sahara');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'אוגאַנדע');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'אויסטראַליע');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'אונגערן');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'אוקראַינע');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'אורוגוויי');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'איטאַליע');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'אינדאנעזיע');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'אינדיע');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'איסלאַנד');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'איראַן');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'אירלאַנד');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'אַלבאַניע');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'אַנגאלע');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'אַנדארע');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'אַנטאַרקטיקע');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'אַנטיגוע און באַרבודע');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'אַפֿגהאַניסטאַן');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'אַרגענטינע');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'אַרובאַ');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'אַרמעניע');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'באַהאַמאַס');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'באליוויע');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'באַנגלאַדעש');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'באסניע הערצעגאווינע');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'באצוואַנע');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'באַרבאַדאס');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'בהוטאַן');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'בולגאַריע');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'בורונדי');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'בורקינע פֿאַסא');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'בעלאַרוס');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'בעלגיע');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'בעליז');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'בענין');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'בערמודע');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'בראַזיל');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'ברוניי');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'גאַבאן');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'גאַמביע');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'גהאַנע');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'גוואַדעלופ');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'גוואַטעמאַלע');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'גוואַם');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'גויאַנע');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'גיבראַלטאַר');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'גינע');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'גינע־ביסאַו');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'גערנזי');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'גרוזיע');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'גריכנלאַנד');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'גרינלאַנד');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'גרענאַדאַ');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'דאמיניקאַנישע רעפּובליק');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'דאמיניקע');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'דזשאַמייקע');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'דזשיבוטי');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'דזשערזי');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'דייטשלאַנד');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'דענמאַרק');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'דרום־אַפֿריקע');
INSERT INTO "country" ("id", "name") VALUES ('SS', 'דרום־סודאַן');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'האַיטי');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'האלאַנד');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'האנדוראַס');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'העלפֿאַ נדביין בארטן');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'וואַטיקאַן שטאָט');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'וואַנואַטו');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'וויעטנאַם');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'ווענעזועלע');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'זאַמביע');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'זימבאַבווע');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'טאגא');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'טאנגאַ');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'טאַנזאַניע');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'טואוואַלו');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'טוניסיע');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'טורקמעניסטאַן');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'טיילאַנד');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'טערקיי');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'טרינידאַד און טאבאַגא');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'טשאַד');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'טשילע');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'טשעכיי');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'יאַפּאַן');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'ישראל');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'כינע');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'לאַאס');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'לבנון');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'לוקסעמבורג');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'ליביע');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'ליבעריע');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'ליטע');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'ליכטנשטיין');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'לעטלאַנד');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'לעסאטא');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'מאַדאַגאַסקאַר');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'מאזאַמביק');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'מאַיאט');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'מאַלאַווי');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'מאלדאווע');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'מאַלדיוון');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'מאַלטאַ');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'מאַלי');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'מאַלייזיע');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'מאנאַקא');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'מאנגאליי');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'מאנטסעראַט');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'מאנטענעגרא');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'מאַקעדאניע');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'מאַראקא');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'מאַרטיניק');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'מאַריטאַניע');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'מאריציוס');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'מאַרשאַל אינזלען');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'מיאַנמאַר');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'מיקראנעזיע');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'מעקסיקע');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'נאַמיביע');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'נארוועגיע');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'נארפֿאלק אינזל');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'ניגעריע');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'ניו זילאַנד');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'ניזשער');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'נײַ קאַלעדאניע');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'ניקאַראַגוע');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'נעפּאַל');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'סאַא טאמע און פּרינסיפּע');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'סאלאמאן אינזלען');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'סאַמאאַ');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'סאמאַליע');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'סאַן מאַרינא');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'סודאַן');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'סוואַזילאַנד');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'סורינאַם');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'סט העלענע');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'סיישעל');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'סינגאַפּור');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'סיערע לעאנע');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'סיריע');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'סלאוואַקיי');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'סלאוועניע');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'סענעגאַל');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'סערביע');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'סרי־לאַנקאַ');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'עגיפּטן');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'עטיאפּיע');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'על סאַלוואַדאר');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'עסטלאַנד');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'עסטרייך');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'עקוואַדאר');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'עקוואַטארישע גינע');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'עריטרעע');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'פֿאַלקלאַנד אינזלען');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'פּאַנאַמאַ');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'פּאַפּואַ נײַ גינע');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'פּאַקיסטאַן');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'פֿאַרא אינזלען');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'פּאַראַגווײַ');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'פֿאַראייניגטע קעניגרייך');
INSERT INTO "country" ("id", "name") VALUES ('US', 'פֿאַראייניגטע שטאַטן');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'פּארטא־ריקא');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'פּארטוגאַל');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'פּוילן');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'פֿידזשי');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'פּיטקערן אינזלען');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'פֿיליפּינען');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'פֿינלאַנד');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'פּערו');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'פֿראַנצויזישע גויאַנע');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'פֿראַנצויזישע פּאלינעזיע');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'פֿראַנקרייך');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'צענטראַל־אַפֿריקאַנישע רעפּובליק');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'קאַטאַר');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'קאלאמביע');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'קאמאראס');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'קאַמבאדיע');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'קאַמערון');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'קאַנאַדע');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'קאַנאַרישע אינזלען');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'קאנגא־קינשאַזע');
INSERT INTO "country" ("id", "name") VALUES ('XK', 'קאסאווא');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'קאסטאַ ריקאַ');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'קאַפּווערדישע אינזלען');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'קובאַ');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'קוק אינזלען');
INSERT INTO "country" ("id", "name") VALUES ('CW', 'קוראַסאַא');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'קיימאַן אינזלען');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'קיריבאַטי');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'קעניע');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'קראאַטיע');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'רוואַנדע');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'רומעניע');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'רוסלאַנד');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'רעאוניאן');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'שווייץ');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'שוועדן');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'שפּאַניע');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'תימן');
