CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afghanistan');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albanie');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Alzerie');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andorra');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Anguilla');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Antartic');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigua e Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Antilis olandesis');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Arabie Saudide');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argjentine');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armenie');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Australie');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Austrie');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azerbaigian');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamas');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrain');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladesh');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbados');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belgjiche');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benin');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Bhutan');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Bielorussie');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Birmanie');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolivie');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosnie e Ercegovine');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brasîl');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgarie');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Camboze');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Camerun');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Canade');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Cile');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Cine');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Cipri');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Cjâf vert');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Colombie');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Comoris');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Congo');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Coree dal nord');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Coree dal sud');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Costa Rica');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Cravuazie');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Cuba');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Cueste di Avoli');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Danimarcje');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominiche');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ecuador');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Egjit');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'El Salvador');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Emirâts araps unîts');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritree');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estonie');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Etiopie');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filipinis');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finlandie');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fizi');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'France');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabon');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'Georgia dal Sud e Isulis Sandwich dal Sud');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ghana');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Gibuti');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Gjamaiche');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Gjapon');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Gjeorgjie');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Gjermanie');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Gjibraltar');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Gnove Caledonie');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Gnove Zelande');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Grecie');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Groenlande');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Guadalupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guam');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Guatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Guiana francês');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Guinee');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Guinee ecuatoriâl');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'India');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonesie');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iran');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Iraq');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irlande');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Islande');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Isole Norfolk');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Israêl');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'Isule Bouvet');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Isule Christmas');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'Isule Heard e Isulis McDonald');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'Isule di Man');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Isulis Aland');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Isulis Cayman');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'Isulis Cocos');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Isulis Cook');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Isulis Falkland');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Isulis Faroe');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Isulis Mariana dal Nord');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Isulis Marshall');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Isulis Salomon');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Isulis Turks e Caicos');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'Isulis periferichis minôrs dai Stâts Unîts');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Isulis vergjinis americanis');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Isulis vergjinis britanichis');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italie');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordanie');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazachistan');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirghizstan');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuwait');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laos');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Letonie');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Liban');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberie');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libie');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Liechtenstein');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Lituanie');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Lussemburc');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Macedonie');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagascar');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malaysia');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldivis');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Maroc');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martiniche');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauritanie');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Maurizi');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayotte');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Messic');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Micronesie');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldavie');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monaco');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongolie');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambic');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibie');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepal');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nicaragua');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Niger');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigerie');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norvegje');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Ongjarie');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panamà');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papue Gnove Guinee');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paraguay');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Paîs bas');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Perù');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitcairn');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Polinesie francês');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Polonie');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Porto Rico');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portugal');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Qatar');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Ream unît');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'Regjon aministrative speciâl de Cine di Hong Kong');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Regjon aministrative speciâl de Cine di Macao');
INSERT INTO `country` (`id`, `name`) VALUES ('ZZ', 'Regjon no cognossude o no valide');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Republiche Democratiche dal Congo');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Republiche ceche');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Republiche centri africane');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Republiche dominicane');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Reunion');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Romanie');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Ruande');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Russie');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Sahara ocidentâl');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Samoa merecanis');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'San Kitts e Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San Marin');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'San Pierre e Miquelon');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'San Vincent e lis Grenadinis');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'Sant Barthélemy');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'Sant Martin');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Sante Eline');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Sante Lusie');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Sao Tomè e Principe');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegal');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Serbia e Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Serbie');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seychelles');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sierra Leone');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapore');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Sirie');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Slovachie');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Slovenie');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somalie');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Spagne');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Stâts Unîts');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Sud Afriche');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Suriname');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Svalbard e Jan Mayen');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Svezie');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Svuizare');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Swaziland');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Tailandie');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzanie');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tazikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Teritori britanic dal Ocean Indian');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Teritori palestinês');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'Teritoris meridionâi francês');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Timor orientâl');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad e Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunisie');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Turchie');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ucraine');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Uruguay');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzbechistan');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatican');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vietnam');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis e Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Yemen');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambia');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Çad');
