CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afgaanistaan');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angoola');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Armeeniya');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Awstraaliya');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Ayrlaanda');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Baarbadoos');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Bakistaan');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangaala-Deesh');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Baxrayn');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Beljiyam');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Beniin');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Booland');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Boosniya Heersigoviina');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Bortuqaal');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Braasiil');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Ciraaq');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Cumaan');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Danmaark');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Faatikaan');
INSERT INTO [country] ([id], [name]) VALUES ('ZZ', 'Far aan la aqoon amase aan saxnayn');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Faransiis');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Fenisuweela');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Fiinlaand');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filibiin');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Fiyetnaam');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Gini');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Giriigga');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Giriinaada');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Hangeri');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'Hindiya');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Iiraan');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Iislaand');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ikwadoor');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Imaaraadka Carabta ee Midoobay');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indoneesiya');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Isbeyn');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Israaʼiil');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Iswidhan');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Itoobiya');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Jaad');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Jabbaan');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Jabuuti');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jameyka');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Jarmal');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Jekoslafaakiya');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Jili');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kamboodiya');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kameruun');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanada');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kasaakhistaan');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kiiniya');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Koonfur Afrika');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Korweeshiya');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kuuba');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Kuuriyada Koonfureed');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Kuuriyada Waqooyi');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuwayt');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Laatfiya');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Laybeeriya');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Liibiya');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Losooto');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Lubnaan');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Luksemboorg');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Maalda');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maaldiqeen');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Maali');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Makadooniya');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malaawi');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Marooko');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Masar');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Meksiko');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Moonako');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Muritaaniya');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Musambiig');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namiibiya');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nayjeeriya');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Neyuusilaand');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikaraaguwa');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Noorweey');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Osteeriya');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Qadar');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Qaramada Midoobey ee Maraykanka');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Rumaaniya');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Ruush');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Saambiya');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Sacuudi Carabiya');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Shiinaha');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Siirilaanka');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Simbaabwe');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Siraaliyoon');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Soomaaliya');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudaan');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Suuriya');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Swiiserlaand');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Talyaani');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tansaaniya');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Taylaand');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Toogo');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tuniisiya');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Turki');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Ugaanda');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'United Kingdom');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Urdun');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yaman');
