CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('GH', '가나');
INSERT INTO "country" ("id", "name") VALUES ('GA', '가봉');
INSERT INTO "country" ("id", "name") VALUES ('GY', '가이아나');
INSERT INTO "country" ("id", "name") VALUES ('GM', '감비아');
INSERT INTO "country" ("id", "name") VALUES ('GG', '건지');
INSERT INTO "country" ("id", "name") VALUES ('GP', '과들루프');
INSERT INTO "country" ("id", "name") VALUES ('GT', '과테말라');
INSERT INTO "country" ("id", "name") VALUES ('GU', '괌');
INSERT INTO "country" ("id", "name") VALUES ('GD', '그레나다');
INSERT INTO "country" ("id", "name") VALUES ('GE', '그루지야');
INSERT INTO "country" ("id", "name") VALUES ('GR', '그리스');
INSERT INTO "country" ("id", "name") VALUES ('GL', '그린란드');
INSERT INTO "country" ("id", "name") VALUES ('GW', '기네비쏘');
INSERT INTO "country" ("id", "name") VALUES ('GN', '기니');
INSERT INTO "country" ("id", "name") VALUES ('CV', '까뽀베르데');
INSERT INTO "country" ("id", "name") VALUES ('NA', '나미비아');
INSERT INTO "country" ("id", "name") VALUES ('NR', '나우루');
INSERT INTO "country" ("id", "name") VALUES ('NG', '나이지리아');
INSERT INTO "country" ("id", "name") VALUES ('AQ', '남극 대륙');
INSERT INTO "country" ("id", "name") VALUES ('ZA', '남아프리카');
INSERT INTO "country" ("id", "name") VALUES ('NL', '네덜란드');
INSERT INTO "country" ("id", "name") VALUES ('AN', '네덜란드령 안틸레스');
INSERT INTO "country" ("id", "name") VALUES ('NP', '네팔');
INSERT INTO "country" ("id", "name") VALUES ('NO', '노르웨이');
INSERT INTO "country" ("id", "name") VALUES ('NF', '노퍽섬');
INSERT INTO "country" ("id", "name") VALUES ('NC', '뉴 칼레도니아');
INSERT INTO "country" ("id", "name") VALUES ('NZ', '뉴질랜드');
INSERT INTO "country" ("id", "name") VALUES ('NU', '니우에');
INSERT INTO "country" ("id", "name") VALUES ('NE', '니제르');
INSERT INTO "country" ("id", "name") VALUES ('NI', '니카라과');
INSERT INTO "country" ("id", "name") VALUES ('TW', '대만');
INSERT INTO "country" ("id", "name") VALUES ('KR', '대한민국');
INSERT INTO "country" ("id", "name") VALUES ('DK', '덴마크');
INSERT INTO "country" ("id", "name") VALUES ('DM', '도미니카');
INSERT INTO "country" ("id", "name") VALUES ('DO', '도미니카 공화국');
INSERT INTO "country" ("id", "name") VALUES ('DE', '독일');
INSERT INTO "country" ("id", "name") VALUES ('TL', '동티모르');
INSERT INTO "country" ("id", "name") VALUES ('DG', '디에고 가르시아');
INSERT INTO "country" ("id", "name") VALUES ('LA', '라오스');
INSERT INTO "country" ("id", "name") VALUES ('LR', '라이베리아');
INSERT INTO "country" ("id", "name") VALUES ('LV', '라트비아');
INSERT INTO "country" ("id", "name") VALUES ('RU', '러시아');
INSERT INTO "country" ("id", "name") VALUES ('LB', '레바논');
INSERT INTO "country" ("id", "name") VALUES ('LS', '레소토');
INSERT INTO "country" ("id", "name") VALUES ('RO', '루마니아');
INSERT INTO "country" ("id", "name") VALUES ('LU', '룩셈부르크');
INSERT INTO "country" ("id", "name") VALUES ('RW', '르완다');
INSERT INTO "country" ("id", "name") VALUES ('LY', '리비아');
INSERT INTO "country" ("id", "name") VALUES ('RE', '리유니온');
INSERT INTO "country" ("id", "name") VALUES ('LT', '리투아니아');
INSERT INTO "country" ("id", "name") VALUES ('LI', '리히텐슈타인');
INSERT INTO "country" ("id", "name") VALUES ('MG', '마다가스카르');
INSERT INTO "country" ("id", "name") VALUES ('MH', '마샬 군도');
INSERT INTO "country" ("id", "name") VALUES ('YT', '마요티');
INSERT INTO "country" ("id", "name") VALUES ('MO', '마카오, 중국 특별행정구');
INSERT INTO "country" ("id", "name") VALUES ('MK', '마케도니아');
INSERT INTO "country" ("id", "name") VALUES ('MW', '말라위');
INSERT INTO "country" ("id", "name") VALUES ('MY', '말레이시아');
INSERT INTO "country" ("id", "name") VALUES ('ML', '말리');
INSERT INTO "country" ("id", "name") VALUES ('MQ', '말티니크');
INSERT INTO "country" ("id", "name") VALUES ('IM', '맨 섬');
INSERT INTO "country" ("id", "name") VALUES ('MX', '멕시코');
INSERT INTO "country" ("id", "name") VALUES ('MC', '모나코');
INSERT INTO "country" ("id", "name") VALUES ('MA', '모로코');
INSERT INTO "country" ("id", "name") VALUES ('MU', '모리셔스');
INSERT INTO "country" ("id", "name") VALUES ('MR', '모리타니');
INSERT INTO "country" ("id", "name") VALUES ('MZ', '모잠비크');
INSERT INTO "country" ("id", "name") VALUES ('ME', '몬테네그로');
INSERT INTO "country" ("id", "name") VALUES ('MS', '몬트세라트');
INSERT INTO "country" ("id", "name") VALUES ('MD', '몰도바');
INSERT INTO "country" ("id", "name") VALUES ('MV', '몰디브');
INSERT INTO "country" ("id", "name") VALUES ('MT', '몰타');
INSERT INTO "country" ("id", "name") VALUES ('MN', '몽골');
INSERT INTO "country" ("id", "name") VALUES ('US', '미국');
INSERT INTO "country" ("id", "name") VALUES ('VI', '미국령 버진 아일랜드');
INSERT INTO "country" ("id", "name") VALUES ('UM', '미국령 해외 제도');
INSERT INTO "country" ("id", "name") VALUES ('MM', '미얀마');
INSERT INTO "country" ("id", "name") VALUES ('FM', '미크로네시아');
INSERT INTO "country" ("id", "name") VALUES ('VU', '바누아투');
INSERT INTO "country" ("id", "name") VALUES ('BH', '바레인');
INSERT INTO "country" ("id", "name") VALUES ('BB', '바베이도스');
INSERT INTO "country" ("id", "name") VALUES ('VA', '바티칸');
INSERT INTO "country" ("id", "name") VALUES ('BS', '바하마');
INSERT INTO "country" ("id", "name") VALUES ('BD', '방글라데시');
INSERT INTO "country" ("id", "name") VALUES ('BM', '버뮤다');
INSERT INTO "country" ("id", "name") VALUES ('BJ', '베냉');
INSERT INTO "country" ("id", "name") VALUES ('VE', '베네수엘라');
INSERT INTO "country" ("id", "name") VALUES ('VN', '베트남');
INSERT INTO "country" ("id", "name") VALUES ('BE', '벨기에');
INSERT INTO "country" ("id", "name") VALUES ('BY', '벨라루스');
INSERT INTO "country" ("id", "name") VALUES ('BZ', '벨리즈');
INSERT INTO "country" ("id", "name") VALUES ('BA', '보스니아 헤르체고비나');
INSERT INTO "country" ("id", "name") VALUES ('BW', '보츠와나');
INSERT INTO "country" ("id", "name") VALUES ('BO', '볼리비아');
INSERT INTO "country" ("id", "name") VALUES ('BI', '부룬디');
INSERT INTO "country" ("id", "name") VALUES ('BF', '부르키나파소');
INSERT INTO "country" ("id", "name") VALUES ('BV', '부베');
INSERT INTO "country" ("id", "name") VALUES ('BT', '부탄');
INSERT INTO "country" ("id", "name") VALUES ('MP', '북마리아나제도');
INSERT INTO "country" ("id", "name") VALUES ('BG', '불가리아');
INSERT INTO "country" ("id", "name") VALUES ('BR', '브라질');
INSERT INTO "country" ("id", "name") VALUES ('BN', '브루나이');
INSERT INTO "country" ("id", "name") VALUES ('WS', '사모아');
INSERT INTO "country" ("id", "name") VALUES ('SA', '사우디아라비아');
INSERT INTO "country" ("id", "name") VALUES ('GS', '사우스조지아 사우스샌드위치 제도');
INSERT INTO "country" ("id", "name") VALUES ('CY', '사이프러스');
INSERT INTO "country" ("id", "name") VALUES ('SM', '산마리노');
INSERT INTO "country" ("id", "name") VALUES ('ST', '상투메 프린시페');
INSERT INTO "country" ("id", "name") VALUES ('MF', '생 마르탱');
INSERT INTO "country" ("id", "name") VALUES ('BL', '생 바르텔르미');
INSERT INTO "country" ("id", "name") VALUES ('EH', '서사하라');
INSERT INTO "country" ("id", "name") VALUES ('SN', '세네갈');
INSERT INTO "country" ("id", "name") VALUES ('RS', '세르비아');
INSERT INTO "country" ("id", "name") VALUES ('CS', '세르비아 및 몬테네그로');
INSERT INTO "country" ("id", "name") VALUES ('EA', '세우타 및 멜리야');
INSERT INTO "country" ("id", "name") VALUES ('LC', '세인트루시아');
INSERT INTO "country" ("id", "name") VALUES ('VC', '세인트빈센트그레나딘');
INSERT INTO "country" ("id", "name") VALUES ('KN', '세인트크리스토퍼 네비스');
INSERT INTO "country" ("id", "name") VALUES ('PM', '세인트피에르-미케롱');
INSERT INTO "country" ("id", "name") VALUES ('SH', '세인트헬레나');
INSERT INTO "country" ("id", "name") VALUES ('SO', '소말리아');
INSERT INTO "country" ("id", "name") VALUES ('SB', '솔로몬 제도');
INSERT INTO "country" ("id", "name") VALUES ('SD', '수단');
INSERT INTO "country" ("id", "name") VALUES ('SR', '수리남');
INSERT INTO "country" ("id", "name") VALUES ('SC', '쉐이쉘');
INSERT INTO "country" ("id", "name") VALUES ('LK', '스리랑카');
INSERT INTO "country" ("id", "name") VALUES ('SJ', '스발바르제도-얀마웬섬');
INSERT INTO "country" ("id", "name") VALUES ('SZ', '스와질랜드');
INSERT INTO "country" ("id", "name") VALUES ('SE', '스웨덴');
INSERT INTO "country" ("id", "name") VALUES ('CH', '스위스');
INSERT INTO "country" ("id", "name") VALUES ('ES', '스페인');
INSERT INTO "country" ("id", "name") VALUES ('SK', '슬로바키아');
INSERT INTO "country" ("id", "name") VALUES ('SI', '슬로베니아');
INSERT INTO "country" ("id", "name") VALUES ('SY', '시리아');
INSERT INTO "country" ("id", "name") VALUES ('SL', '시에라리온');
INSERT INTO "country" ("id", "name") VALUES ('SG', '싱가포르');
INSERT INTO "country" ("id", "name") VALUES ('AE', '아랍에미리트 연합');
INSERT INTO "country" ("id", "name") VALUES ('AW', '아루바');
INSERT INTO "country" ("id", "name") VALUES ('AM', '아르메니아');
INSERT INTO "country" ("id", "name") VALUES ('AR', '아르헨티나');
INSERT INTO "country" ("id", "name") VALUES ('AS', '아메리칸 사모아');
INSERT INTO "country" ("id", "name") VALUES ('IS', '아이슬란드');
INSERT INTO "country" ("id", "name") VALUES ('HT', '아이티');
INSERT INTO "country" ("id", "name") VALUES ('IE', '아일랜드');
INSERT INTO "country" ("id", "name") VALUES ('AZ', '아제르바이잔');
INSERT INTO "country" ("id", "name") VALUES ('AF', '아프가니스탄');
INSERT INTO "country" ("id", "name") VALUES ('AI', '안길라');
INSERT INTO "country" ("id", "name") VALUES ('AD', '안도라');
INSERT INTO "country" ("id", "name") VALUES ('AL', '알바니아');
INSERT INTO "country" ("id", "name") VALUES ('DZ', '알제리');
INSERT INTO "country" ("id", "name") VALUES ('AO', '앙골라');
INSERT INTO "country" ("id", "name") VALUES ('AG', '앤티가 바부다');
INSERT INTO "country" ("id", "name") VALUES ('AC', '어센션 섬');
INSERT INTO "country" ("id", "name") VALUES ('ER', '에리트리아');
INSERT INTO "country" ("id", "name") VALUES ('EE', '에스토니아');
INSERT INTO "country" ("id", "name") VALUES ('EC', '에콰도르');
INSERT INTO "country" ("id", "name") VALUES ('SV', '엘살바도르');
INSERT INTO "country" ("id", "name") VALUES ('GB', '영국');
INSERT INTO "country" ("id", "name") VALUES ('VG', '영국령 버진 아일랜드');
INSERT INTO "country" ("id", "name") VALUES ('IO', '영국령인도양식민지');
INSERT INTO "country" ("id", "name") VALUES ('YE', '예멘');
INSERT INTO "country" ("id", "name") VALUES ('OM', '오만');
INSERT INTO "country" ("id", "name") VALUES ('QO', '오세아니아 외곽');
INSERT INTO "country" ("id", "name") VALUES ('AU', '오스트레일리아');
INSERT INTO "country" ("id", "name") VALUES ('AT', '오스트리아');
INSERT INTO "country" ("id", "name") VALUES ('HN', '온두라스');
INSERT INTO "country" ("id", "name") VALUES ('AX', '올란드 제도');
INSERT INTO "country" ("id", "name") VALUES ('WF', '왈리스-푸투나 제도');
INSERT INTO "country" ("id", "name") VALUES ('JO', '요르단');
INSERT INTO "country" ("id", "name") VALUES ('UG', '우간다');
INSERT INTO "country" ("id", "name") VALUES ('UY', '우루과이');
INSERT INTO "country" ("id", "name") VALUES ('UZ', '우즈베키스탄');
INSERT INTO "country" ("id", "name") VALUES ('UA', '우크라이나');
INSERT INTO "country" ("id", "name") VALUES ('EU', '유럽 연합');
INSERT INTO "country" ("id", "name") VALUES ('ET', '이디오피아');
INSERT INTO "country" ("id", "name") VALUES ('IQ', '이라크');
INSERT INTO "country" ("id", "name") VALUES ('IR', '이란');
INSERT INTO "country" ("id", "name") VALUES ('IL', '이스라엘');
INSERT INTO "country" ("id", "name") VALUES ('EG', '이집트');
INSERT INTO "country" ("id", "name") VALUES ('IT', '이탈리아');
INSERT INTO "country" ("id", "name") VALUES ('IN', '인도');
INSERT INTO "country" ("id", "name") VALUES ('ID', '인도네시아');
INSERT INTO "country" ("id", "name") VALUES ('JP', '일본');
INSERT INTO "country" ("id", "name") VALUES ('JM', '자메이카');
INSERT INTO "country" ("id", "name") VALUES ('ZM', '잠비아');
INSERT INTO "country" ("id", "name") VALUES ('JE', '저지');
INSERT INTO "country" ("id", "name") VALUES ('GQ', '적도 기니');
INSERT INTO "country" ("id", "name") VALUES ('KP', '조선 민주주의 인민 공화국');
INSERT INTO "country" ("id", "name") VALUES ('CN', '중국');
INSERT INTO "country" ("id", "name") VALUES ('CF', '중앙 아프리카 공화국');
INSERT INTO "country" ("id", "name") VALUES ('DJ', '지부티');
INSERT INTO "country" ("id", "name") VALUES ('GI', '지브롤터');
INSERT INTO "country" ("id", "name") VALUES ('ZW', '짐바브웨');
INSERT INTO "country" ("id", "name") VALUES ('TD', '차드');
INSERT INTO "country" ("id", "name") VALUES ('CZ', '체코');
INSERT INTO "country" ("id", "name") VALUES ('CL', '칠레');
INSERT INTO "country" ("id", "name") VALUES ('IC', '카나리아 제도');
INSERT INTO "country" ("id", "name") VALUES ('CM', '카메룬');
INSERT INTO "country" ("id", "name") VALUES ('KZ', '카자흐스탄');
INSERT INTO "country" ("id", "name") VALUES ('QA', '카타르');
INSERT INTO "country" ("id", "name") VALUES ('KH', '캄보디아');
INSERT INTO "country" ("id", "name") VALUES ('CA', '캐나다');
INSERT INTO "country" ("id", "name") VALUES ('KE', '케냐');
INSERT INTO "country" ("id", "name") VALUES ('KY', '케이맨제도');
INSERT INTO "country" ("id", "name") VALUES ('KM', '코모로스');
INSERT INTO "country" ("id", "name") VALUES ('CR', '코스타리카');
INSERT INTO "country" ("id", "name") VALUES ('CC', '코코스제도');
INSERT INTO "country" ("id", "name") VALUES ('CI', '코트디부아르');
INSERT INTO "country" ("id", "name") VALUES ('CO', '콜롬비아');
INSERT INTO "country" ("id", "name") VALUES ('CG', '콩고');
INSERT INTO "country" ("id", "name") VALUES ('CD', '콩고-킨샤사');
INSERT INTO "country" ("id", "name") VALUES ('CU', '쿠바');
INSERT INTO "country" ("id", "name") VALUES ('KW', '쿠웨이트');
INSERT INTO "country" ("id", "name") VALUES ('CK', '쿡제도');
INSERT INTO "country" ("id", "name") VALUES ('HR', '크로아티아');
INSERT INTO "country" ("id", "name") VALUES ('CX', '크리스마스섬');
INSERT INTO "country" ("id", "name") VALUES ('CP', '클립퍼튼 섬');
INSERT INTO "country" ("id", "name") VALUES ('KG', '키르기스스탄');
INSERT INTO "country" ("id", "name") VALUES ('KI', '키리바시');
INSERT INTO "country" ("id", "name") VALUES ('TJ', '타지키스탄');
INSERT INTO "country" ("id", "name") VALUES ('TZ', '탄자니아');
INSERT INTO "country" ("id", "name") VALUES ('TH', '태국');
INSERT INTO "country" ("id", "name") VALUES ('TC', '터크스케이커스제도');
INSERT INTO "country" ("id", "name") VALUES ('TR', '터키');
INSERT INTO "country" ("id", "name") VALUES ('TG', '토고');
INSERT INTO "country" ("id", "name") VALUES ('TK', '토켈라우');
INSERT INTO "country" ("id", "name") VALUES ('TO', '통가');
INSERT INTO "country" ("id", "name") VALUES ('TM', '투르크메니스탄');
INSERT INTO "country" ("id", "name") VALUES ('TV', '투발루');
INSERT INTO "country" ("id", "name") VALUES ('TN', '튀니지');
INSERT INTO "country" ("id", "name") VALUES ('TT', '트리니다드 토바고');
INSERT INTO "country" ("id", "name") VALUES ('TA', '트리스탄다쿠나');
INSERT INTO "country" ("id", "name") VALUES ('PA', '파나마');
INSERT INTO "country" ("id", "name") VALUES ('PY', '파라과이');
INSERT INTO "country" ("id", "name") VALUES ('PK', '파키스탄');
INSERT INTO "country" ("id", "name") VALUES ('PG', '파푸아뉴기니');
INSERT INTO "country" ("id", "name") VALUES ('PW', '팔라우');
INSERT INTO "country" ("id", "name") VALUES ('PS', '팔레스타인 지구');
INSERT INTO "country" ("id", "name") VALUES ('FO', '페로제도');
INSERT INTO "country" ("id", "name") VALUES ('PE', '페루');
INSERT INTO "country" ("id", "name") VALUES ('PT', '포르투갈');
INSERT INTO "country" ("id", "name") VALUES ('FK', '포클랜드 제도');
INSERT INTO "country" ("id", "name") VALUES ('PL', '폴란드');
INSERT INTO "country" ("id", "name") VALUES ('PR', '푸에르토리코');
INSERT INTO "country" ("id", "name") VALUES ('FR', '프랑스');
INSERT INTO "country" ("id", "name") VALUES ('TF', '프랑스 남부 지방');
INSERT INTO "country" ("id", "name") VALUES ('GF', '프랑스령 기아나');
INSERT INTO "country" ("id", "name") VALUES ('PF', '프랑스령 폴리네시아');
INSERT INTO "country" ("id", "name") VALUES ('FJ', '피지');
INSERT INTO "country" ("id", "name") VALUES ('FI', '핀란드');
INSERT INTO "country" ("id", "name") VALUES ('PH', '필리핀');
INSERT INTO "country" ("id", "name") VALUES ('PN', '핏케언섬');
INSERT INTO "country" ("id", "name") VALUES ('HM', '허드섬-맥도널드제도');
INSERT INTO "country" ("id", "name") VALUES ('HU', '헝가리');
INSERT INTO "country" ("id", "name") VALUES ('HK', '홍콩, 중국 특별행정구');
