CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Huandola');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Hufalme dza Hihalabu');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Huafuganistani');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Huantigua na Hubarubuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Huanguila');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Hualbania');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Huamenia');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Huantili dza Huuholanzi');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Huangola');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Huajendina');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Husamoa ya Humalekani');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Huastlia');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Huaustlalia');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Hualuba');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Huazabajani');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Hubosinia na Huhezegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Hubabadosi');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Hubangaladeshi');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Huubelgiji');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Hubukinafaso');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Hubulgaria');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Hubahaleni');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Huburundi');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Hubenini');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Hubelmuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Hubrunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Hubolivia');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Hublazili');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Hubahama');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Hubutani');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Hubotiswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Hubelalusi');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Hubelize');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Hukanada');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Ijamhuri ya Hidemokrasi ya Hukongo');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Ijamhuri ya Afrika ya Pagati');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Hukongo');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Huuswisi');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Hukodivaa');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Ifisima fya Kook');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Huchile');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Hukameruni');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Huchina');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Hukolombia');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Hukostarika');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Huselbia na Humonteneglo');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Hukuba');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Hukepuvede');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Hukuprosi');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Ijamhuri ya Cheki');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Huujerumani');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Hujibuti');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Hudenmaki');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Hudominika');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Ijamhuri ya Hudominika');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Hualjelia');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Huekwado');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Huestonia');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Humisri');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Hueritrea');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Huhispania');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Huuhabeshi');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Huufini');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Hufiji');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Ifisima fya Falkland');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Humikronesia');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Huufaransa');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Hugaboni');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Huuingereza');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Hugrenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Hujojia');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Hugwiyana ya Huufaransa');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Hughana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Hujiblalta');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Hujinlandi');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Hugambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Hujine');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Hugwadelupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Huginekweta');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Huugiliki');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Hugwatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Hugwam');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Huginebisau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Huguyana');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Huhondulasi');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Hukorasia');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Huhaiti');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Huhungalia');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Huindonesia');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Huayalandi');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Huislaheli');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Huindia');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Ulubali lwa Hubahari ya Hindi lwa Huingereza');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Huilaki');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Huuajemi');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Huaislandi');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Huitalia');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Hujamaika');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Huyolodani');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Hujapani');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Hukenya');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Hukiligizistani');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Hukambodia');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Hukilibati');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Hukomoro');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Husantakitzi na Hunevis');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Hukolea Kaskazini');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Hukolea Kusini');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Hukuwaiti');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Ifisima fya Kayman');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Hukazakistani');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Hulaosi');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Hulebanoni');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Husantalusia');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Hulishenteni');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Husirilanka');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Hulibelia');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Hulesoto');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Hulitwania');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Hulasembagi');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Hulativia');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Hulibiya');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Humoloko');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Humonako');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Humoldova');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Hubukini');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Ifisima fya Marshal');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Humasedonia');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Humali');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Humyama');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Humongolia');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Ifisima fya Mariana fya Hukaskazini');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Humartiniki');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Humolitania');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Humontserrati');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Humalta');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Humolisi');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Humodivu');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Humalawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Humeksiko');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Humalesia');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Humusumbiji');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Hunamibia');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Hunyukaledonia');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Hunijeli');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Ihisima sha Norfok');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Hunijelia');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Hunikaragwa');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Huuholanzi');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Hunolwe');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Hunepali');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Hunauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Huniue');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Hunyuzilandi');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Huomani');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Hupanama');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Hupelu');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Hupolinesia ya Huufaransa');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Hupapua');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Hufilipino');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Hupakistani');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Hupolandi');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Husantapieri na Humikeloni');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Hupitkaini');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Hupwetoriko');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Ulubali lwa Magharibi nu Gaza wa Hupalestina');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Huuleno');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Hupalau');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Hupalagwai');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Hukatali');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Huliyunioni');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Hulomania');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Huulusi');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Hulwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Husaudi');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Ifisima fya Solomon');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Hushelisheli');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Husudani');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Huuswidi');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Husingapoo');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Husantahelena');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Huslovenia');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Huslovakia');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Husiela Lioni');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'Husamalino');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Husenegali');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Husomalia');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Husurinamu');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Husaotome na Huprinsipe');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Huelsavado');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Husilia');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Huuswazi');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Ifisima fya Turki na Kaiko');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Huchadi');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Hutogo');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Hutailandi');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Hutajikistani');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Hutokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Hutimori ya Mashariki');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Huuturukimenistani');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Hutunisia');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Hutonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Huuturuki');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Hutrinad na Hutobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Hutuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Hutaiwani');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Hutanzania');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Huukraini');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Huuganda');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Humalekani');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Huulugwai');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Huuzibekistani');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Huvatikani');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Husantavisenti na Hugrenadini');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Huvenezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Ifisima fya Virgin fya Huingereza');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Ifisima fya Virgin fya Humelekani');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Huvietinamu');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Huvanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Huwalis na Hufutuna');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Husamoa');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Huyemeni');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Humayotte');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Huafrika iya Hukusini');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Huzambia');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Huzimbabwe');
