CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afganistan');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Ahvenamaa');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albaania');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Alžeeria');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Ameerika Samoa');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Ameerika Ühendriigid');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andorra');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anguilla');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Antarktis');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua ja Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Aomen - Hiina erihalduspiirkond');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Araabia Ühendemiraadid');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Argentina');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Armeenia');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'Ascensioni saar');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Aserbaidžaan');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Austraalia');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Austria');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahama');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahrein');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladesh');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbados');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Belau');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Belgia');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belize');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Benin');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermuda');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Bhutan');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Boliivia');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosnia ja Hertsegoviina');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botswana');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Bouvet’ saar');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brasiilia');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Briti India ookeani ala');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Briti Neitsisaared');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brunei');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulgaaria');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burkina Faso');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'Ceuta ja Melilla');
INSERT INTO "country" ("id", "name") VALUES ('CP', 'Clippertoni saar');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Colombia');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Cooki saared');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Costa Rica');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Côte d\'Ivoire');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'Diego Garcia');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Djibouti');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominica');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Dominikaani Vabariik');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ecuador');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Eesti');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Egiptus');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Ekvatoriaal-Guinea');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'El Salvador');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Eritrea');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Etioopia');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'Euroopa Liit');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Falklandi saared');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fidži');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filipiinid');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Fääri saared');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabon');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambia');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Ghana');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Gibraltar');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenada');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Gruusia');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Gröönimaa');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadeloupe');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatemala');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Guernsey');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Guinea');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Guinea-Bissau');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guyana');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haiti');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Heard ja McDonald saared');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Hiina');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Hispaania');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Holland');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Hollandi Antillid');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduras');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Hongkong - Hiina erihalduspiirkond');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Horvaatia');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Ida-Timor');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Iirimaa');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Iisrael');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'India');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indoneesia');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Iraak');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Iraan');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Island');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Itaalia');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Jaapan');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamaica');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Jeemen');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Jersey');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jordaania');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Jõulusaar');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Kaimanisaared');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Kambodža');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamerun');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'Kanaari saared');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanada');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kasahstan');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Katar');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenya');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Kesk-Aafrika Vabariik');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komoorid');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Kongo DV');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongo-Brazzaville');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Kookossaared');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Kreeka');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kuuba');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kuveit');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kõrgõzstan');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Küpros');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laos');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Leedu');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesotho');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Libeeria');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Liechtenstein');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Liibanon');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Liibüa');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luksemburg');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Lõuna-Aafrika Vabariik');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'Lõuna-Georgia ja Lõuna-Sandwichi saared');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Lõuna-Korea');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Läti');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Lääne-Sahara');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagaskar');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Makedoonia');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malaisia');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malawi');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldiivid');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malta');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Mani saar');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Maroko');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Marshalli saared');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martinique');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mauritaania');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Mauritius');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayotte');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mehhiko');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikroneesia Liiduriigid');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldova');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monaco');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongoolia');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Montserrat');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mosambiik');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Myanmar');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namiibia');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepal');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nicaragua');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nigeeria');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Niger');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Norfolk');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Norra');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'Okeaania hajasaared');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Omaan');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Paapua Uus-Guinea');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakistan');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Palestiina ala');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguay');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Peruu');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitcairn');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Poola');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portugal');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Prantsuse Guajaana');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Prantsuse Lõunaalad');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Prantsuse Polüneesia');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Prantsusmaa');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Puerto Rico');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Põhja-Korea');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Põhja-Mariaanid');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Réunion');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Roheneemesaared');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Rootsi');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Rumeenia');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Rwanda');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Saalomoni Saared');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'Saint Barthélemy');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Saint Helena');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Saint Kitts ja Nevis');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Saint Lucia');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'Saint Martin');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Saint Pierre ja Miquelon');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Saint Vincent ja Grenadiinid');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Saksamaa');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Sambia');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samoa');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'San Marino');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'São Tomé ja Príncipe');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Saudi Araabia');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Seišellid');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegal');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Serbia');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Serbia ja Montenegro');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Sierra Leone');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapur');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slovakkia');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Sloveenia');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somaalia');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Soome');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudaan');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Suriname');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Suurbritannia');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Svaasimaa');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Svalbard ja Jan Mayen');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Süüria');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Šveits');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabwe');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Taani');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tadžikistan');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Tai');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taiwan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tansaania');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinidad ja Tobago');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'Tristan da Cunha');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Tšaad');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Tšehhi');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Tšiili');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tuneesia');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Turks ja Caicos');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Türgi');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Türkmenistan');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uganda');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukraina');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Ungari');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruguay');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'USA Neitsisaared');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Usbekistan');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Uus-Kaledoonia');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Uus-Meremaa');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Valgevene');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis ja Futuna');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Vatikan');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Venemaa');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezuela');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vietnam');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'Ühendriikide hajasaared');
