CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afǝganisǝtán');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Afiríka yá Súd');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Aití');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Alǝbánia');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Alǝyéria');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andór');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Anǝtíyǝ Nɛdǝlánia');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Angíyǝ');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angolá');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antígwa ai Barǝbúda');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Arabí Saudí');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Arǝhenǝtína');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Arǝménia');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Arúba');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azɛrǝbaidzáŋ');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahámas');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahǝrɛ́n');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangaladɛ́s');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barǝbád');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Bemirá yá Arábǝ uní');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Bǝlarús');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Bǝlazíl');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Bǝlís');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Bǝníŋ');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Bǝsamóa yá Amǝ́rǝka');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Bɛlǝhíg');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bɛrǝmúd');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolívia');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosǝní ai ɛrǝzegovín');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswaná');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulǝgarí');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Bulǝkiná Fasó');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Buluné');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundí');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Butáŋ');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Danǝmárǝg');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dómǝnika');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Dzibutí');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Ehíbǝtɛn');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ekwatór');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Elitǝlé');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Esetoní');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Etiopí');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'ɛ́ndǝ');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'ɛndonésia');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fidzí');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipín');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finǝlán');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'fólis');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'fɔrǝtugɛ́s');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Fulɛnsí');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabóŋ');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambí');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Ganá');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Gǝlǝnádǝ');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Gǝlɛ́s');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Giné');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Giné Bisaó');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Giné Ekwató');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Goelán');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Guadǝlúb');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guám');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Guatemalá');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyán');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Guyán yá Fulɛnsí');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Hamaíka');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Hapɔ́n');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Horǝdaní');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Horǝ́yia');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Irág');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Irán');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Irǝlándǝ');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Isǝlándǝ');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Isǝraɛ́l');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Itáliɛn');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'kambodía');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kamǝrún');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'kanadá');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Katár');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazakǝtáŋ');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Keniá');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Kǝlowásia');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribatí');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kirigisǝtán');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Kód Divɔ́r');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolɔmbí');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Komɔ́r');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongó');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Koré yá Nór');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Koré yá Súd');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kosta Ríka');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kowɛ́d');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Kpǝnyá');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kubá');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laós');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lǝsotó');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Lǝtoní');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Libáŋ');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Libéria');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libí');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Lísǝ́sǝ́táin');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lituaní');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Lukǝzambúd');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagasǝkárǝ');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawí');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Malǝdívǝ');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Málǝtǝ');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malɛ́zia');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Malí');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Marǝtiníg');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Marɔ́g');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Masedónia');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayɔ́d');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mɛkǝsíg');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Mianǝmár');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikoronésia');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Minlán Mi Amɛrǝkǝ');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Minlán Mi Fólǝkǝlan');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Minlán Mí Káb Vɛr');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Minlán Mí Kalimáŋ');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Minlán Mí kúg');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Minlán Mí Maresál');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Minlán Mi Marián yá Nór');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Minlán Mí Solomɔ́n');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Minlán Mí túrǝ́g-ai-Kaíg');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Minlán Nɔrǝfɔ́lǝkǝ');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Molǝdaví');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Morís');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Moritaní');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambíg');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Mɔnakó');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mɔngɔ́lia');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Mɔ́ntserád');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibí');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Naurú');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Ndzáman');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepál');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'Ǹfúfúb Maríno');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Ǹfúfúb-Ɛlɛ́na');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Ǹfúfúb-Kilisǝtóv-ai-Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Ǹfúfúb-Lúsia');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Ǹfúfúb-Píɛr-ai-Mikǝlɔ́ŋ');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Ǹfúfúb-Vɛngǝsáŋ-ai-Bǝ Gǝlǝnadín');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nihéria');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Nihɛ́r');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikarágua');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niué');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Ǹkpámɛn Kaledónia');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Ǹkpámɛn Zeláŋ');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Ǹnam Amɛrǝkǝ');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Ǹnam Engǝlis');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'ǹnam ɛngǝlís yá Máŋ mǝ́ ɛ́ndǝ');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'ǹnam Kongó Demokǝlatíg');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'ńnam Minlán ɛ́ngǝlís');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Ǹnam Palɛsǝtín');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Ǹnam Tsɛ́g');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Ǹnam Vatikán');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'ǹnam Zǎŋ Afiriká');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Nɔrǝvɛ́s');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Omán');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Ondurás');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Ongirí');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Osǝtǝlalí');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Osǝtǝlía');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakisǝtán');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panamá');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papwazi yá Ǹkpámɛ́n Giné');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paragué');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Perú');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Pɛíbá');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pítǝ́kɛ́rɛnǝ');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Polinesí yá Fulɛnsí');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Pwɛrǝto Ríko');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'République dominicaine');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Reuniɔ́ŋ');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Rumaní');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rúsian');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Ruwandá');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Salǝvadór');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoá');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Saó Tomé ai Pǝlinǝsípe');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegál');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Sǝlovakí');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Sǝlovénia');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sǝri Laŋká');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Sɛrǝbí-ai-Mɔntenégǝlo');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Sɛsɛ́l');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sierá-leónǝ');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapúr');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Sipǝlús');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Sirí');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somália');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudáŋ');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Suís');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinám');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Suwɛ́d');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Swazilándǝ');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tadzikisǝtáŋ');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Tailán');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwán');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Taŋǝzaní');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Tǝlinité-ai-Tobágo');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timôr');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togó');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokeló');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tɔngá');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Tsád');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Tsáina');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Tsilí');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunisí');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turǝkǝmǝnisǝtáŋ');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Turǝkí');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalú');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Ugandá');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukǝrɛ́n');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Urugué');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Uzubekisǝtán');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuátu');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuéla');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Viɛdǝnám');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Walís-ai-Futúna');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yemɛ́n');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Yilǝbalatár');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambí');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabwé');
