CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Aamenia');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Aereland');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Aesland');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afganistan');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Afrika Anaafo');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Afrika Finimfin Man');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Agyɛntina');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Ahendiman Nkabom');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albenia');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Amɛrika');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Amɛrika Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Amɛrika Virgin Islands');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Anaafo Koria');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andora');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguila');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antigua ne Baabuda');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Aruba');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azebaegyan');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Baabados');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahama');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bangladɛhye');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Baren');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Beliz');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Bɛlarus');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Bɛlgyium');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bɛmuda');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Bɛnin');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolivia');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnia ne Hɛzegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Bɔkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bɔlgeria');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Bɔtswana');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brazil');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Britainfo Virgin Islands');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Britenfo Hɔn Man Wɔ India Po No Mu');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunae');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Butan');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Dɛnmak');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dɔmeneka');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Dɔmeneka Kurokɛse');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Etifi Koria');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Ɛl Salvadɔ');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Ɛritrea');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Ɛstonia');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Figyi');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finland');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Fɔlkman Aeland');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Frɛnkye Gayana');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Frɛnkye Pɔlenehyia');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Frɛnkyeman');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Gaana');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabɔn');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambia');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Gayana');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Gini');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Gini Bisaw');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Gini Ikuweta');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Greekman');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Greenman');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grenada');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guam');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Guwadelup');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Guwatemala');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Gyaaman');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Gyameka');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Gyapan');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Gyebralta');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Gyibuti');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Gyɔdan');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Gyɔgyea');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Hangari');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Heiti');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Hɔnduras');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ikuwadɔ');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'India');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indɔnehyia');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Irak');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Iran');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Israel');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Itali');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Ithiopia');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Kaledonia Foforo');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kambodia');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kamɛrun');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanada');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Kata');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazakstan');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Kemanfo Islands');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Kepvɛdfo Islands');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kɛɛgestan');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kɛnya');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kolombia');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongo');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Kongo (Zair)');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Kook Nsupɔw');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Kɔmɔrɔs');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kɔsta Rika');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Krowehyia');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kuba');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kuwete');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Kyad');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Kyaena');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Kyɛk Kurokɛse');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Kyili');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'La Côte d''Ivoire');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Laeberia');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Laksembɛg');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laos');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Latvia');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Lektenstaen');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Lɛbanɔn');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lɛsutu');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libya');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lituwenia');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagaska');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Maekronehyia');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawi');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maldives');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malehyia');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Mantserat');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Marshall Islands');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Masedonia');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Matinik');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayɔte');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mɛksiko');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Miyanma');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Moroko');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambik');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Mɔldova');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Mɔlta');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Mɔnako');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mɔngolia');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Mɔrehyeɔs');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Mɔretenia');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Naegyeria');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibia');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Naworu');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nekaraguwa');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Nɛdɛland');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'Nɛdɛland Antelez');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nɛpɔl');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Nigyɛ');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Nisrim');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niyu');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Nɔfolk Aeland');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Nɔɔwe');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Oman');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Ɔlgyeria');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Ɔstrelia');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Ɔstria');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistan');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palau');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Palestaen West Bank ne Gaza');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Papua Guinea Foforo');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguay');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peru');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Philippines');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitcairn');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Poland');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Pɔtugal');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Puɛto Riko');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Reyuniɔn');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Romenia');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Rɔhyea');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Rwanda');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Saeprɔs');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Saint Helena');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Saint Kitts ne Nɛves');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Saint Lucia');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Saint Pierre ne Miquelon');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Saint Vincent ne Grenadines');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marino');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'São Tomé and Príncipe');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Saudi Arabia');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegal');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seyhyɛl');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Sɛɛbea ne Mɔntenɛgro');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sierra Leone');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapɔ');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Siria');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovakia');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slovinia');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Solomon Islands');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somalia');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Spain');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudan');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Suriname');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Swaziland');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Sweden');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Swetzaland');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Taeland');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taiwan');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tajikistan');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzania');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Tɛɛki');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Tɛkmɛnistan');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timɔ Boka');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelau');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tonga');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidad ne Tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunihyia');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Turks ne Caicos Islands');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalu');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukren');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'United Arab Emirates');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Uzbɛkistan');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatican Man');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Venezuela');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Viɛtnam');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wallis ne Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yɛmen');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Yurugwae');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambia');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zembabwe');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Ziland Foforo');
