CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Afiríka yá Súd');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afəganisətán');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Aití');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Aləbánia');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Aləyéria');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andór');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angolá');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Angíyə');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antígwa ai Barəbúda');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Anətíyə Nɛdəlánia');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Arabí Saudí');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Arúba');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Arəhenətína');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Arəménia');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azɛrəbaidzáŋ');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahámas');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahərɛ́n');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangaladɛ́s');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barəbád');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Bemirá yá Arábə uní');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolívia');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosəní ai ɛrəzegovín');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botswaná');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Buluné');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Buləgarí');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Buləkiná Fasó');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundí');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Butáŋ');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Bəlarús');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Bəlazíl');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Bəlís');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Bəníŋ');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Bəsamóa yá Amə́rəka');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Bɛləhíg');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bɛrəmúd');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Danəmárəg');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Dzibutí');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dómənika');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Ehíbətɛn');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ekwatór');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Elitəlé');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Esetoní');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Etiopí');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fidzí');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Filipín');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finəlán');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Fulɛnsí');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabóŋ');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambí');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Ganá');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Giné');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Giné Bisaó');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Giné Ekwató');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Goelán');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadəlúb');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatemalá');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guyán');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Guyán yá Fulɛnsí');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guám');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Gələnádə');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Gəlɛ́s');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Hamaíka');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Hapɔ́n');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Horədaní');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Horə́yia');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Irág');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Irán');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Irəlándə');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Isəlándə');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Isəraɛ́l');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Itáliɛn');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamərún');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Katár');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazakətáŋ');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Keniá');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribatí');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirigisətán');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kolɔmbí');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Komɔ́r');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kongó');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Koré yá Nór');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Koré yá Súd');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Kosta Ríka');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Kowɛ́d');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Kpənyá');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kubá');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Kód Divɔ́r');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Kəlowásia');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laós');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Libáŋ');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Libéria');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libí');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Lituaní');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Lukəzambúd');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Lísə́sə́táin');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Ləsotó');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Lətoní');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagasəkárə');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malawí');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Malí');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Malədívə');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malɛ́zia');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Marɔ́g');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Marətiníg');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Masedónia');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayɔ́d');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Mianəmár');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Mikoronésia');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Minlán Mi Amɛrəkə');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Minlán Mi Fóləkəlan');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Minlán Mi Marián yá Nór');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Minlán Mí Kalimáŋ');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Minlán Mí Káb Vɛr');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Minlán Mí Maresál');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Minlán Mí Solomɔ́n');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Minlán Mí kúg');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Minlán Mí túrə́g-ai-Kaíg');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Minlán Nɔrəfɔ́ləkə');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Molədaví');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Moritaní');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Morís');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mozambíg');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Málətə');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Mɔnakó');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mɔngɔ́lia');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Mɔ́ntserád');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mɛkəsíg');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibí');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Naurú');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Ndzáman');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Nepál');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nihéria');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Nihɛ́r');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nikarágua');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niué');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Nɔrəvɛ́s');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Omán');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Ondurás');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Ongirí');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Osətəlalí');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Osətəlía');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakisətán');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panamá');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papwazi yá Ǹkpámɛ́n Giné');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paragué');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Perú');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Polinesí yá Fulɛnsí');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Pwɛrəto Ríko');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pítə́kɛ́rɛnə');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Pɛíbá');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Reuniɔ́ŋ');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Rumaní');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ruwandá');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'République dominicaine');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Rúsian');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Saləvadór');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samoá');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Saó Tomé ai Pəlinəsípe');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Senegál');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Sierá-leónə');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapúr');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Sipəlús');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Sirí');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somália');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sudáŋ');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Surinám');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Suwɛ́d');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Suís');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Swazilándə');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Səlovakí');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Səlovénia');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Səri Laŋká');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Sɛsɛ́l');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tadzikisətáŋ');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Tailán');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taiwán');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Taŋəzaní');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Timôr');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togó');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokeló');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Tsilí');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Tsád');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Tsáina');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunisí');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Turəkí');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turəkəmənisətáŋ');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalú');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tɔngá');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Təlinité-ai-Tobágo');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Ugandá');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukərɛ́n');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Urugué');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Uzubekisətán');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuátu');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezuéla');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Viɛdənám');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Walís-ai-Futúna');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Yemɛ́n');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Yiləbalatár');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambí');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabwé');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'fólis');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'fɔrətugɛ́s');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'kambodía');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'kanadá');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'ńnam Minlán ɛ́ngəlís');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'Ǹfúfúb Maríno');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Ǹfúfúb-Kilisətóv-ai-Nevis');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Ǹfúfúb-Lúsia');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Ǹfúfúb-Píɛr-ai-Mikəlɔ́ŋ');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Ǹfúfúb-Vɛngəsáŋ-ai-Bə Gələnadín');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Ǹfúfúb-Ɛlɛ́na');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Ǹkpámɛn Kaledónia');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Ǹkpámɛn Zeláŋ');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Ǹnam Amɛrəkə');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Ǹnam Engəlis');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Ǹnam Palɛsətín');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Ǹnam Tsɛ́g');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Ǹnam Vatikán');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'ǹnam Kongó Demokəlatíg');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'ǹnam Zǎŋ Afiriká');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'ǹnam ɛngəlís yá Máŋ mə́ ɛ́ndə');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'ɛndonésia');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'ɛ́ndə');
