CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'afganistáŋ');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'afrik anǝ a sud');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'albaní');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'aljɛrí');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'amɛrika');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'andɔrǝ');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'angiya');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'angóla');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'antiga ri barbúda');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'antíyǝ nɛlandé');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'arabí saodí');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'arjǝntín');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'armɛní');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'aruba');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'ayiti');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'azabecán');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'baabaadǝ');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'baamás');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'baŋladɛ́c');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'barǝ́n');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'bǝlɔŋ bǝ kaksa bɛ táatáaŋzǝn');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'bɛɛmúdǝ');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'bɛlaris');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'bɛliz');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'bɛljík');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'bɛnǝ́n');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'botswana');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'bɔɔlíví');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'bɔsnyɛ ri hɛrsǝgɔvín');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'brɛsíl');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'brunǝ́');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'bukína fǝ́ asɔ');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'bulgarí');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'burundí');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'bután');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'caád');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'cɛ́k');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'cíli');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'cín');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'cíprɛ');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'danmak');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'djɛrman');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'dɔminik');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'dɔminik rɛpublík');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'dyibutí');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'ɛjípt');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'ɛkwatɛǝ́');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'ɛritrɛ́');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'ɛstoní');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'ɛtyɔpí');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'fíji');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'filipǝ́n');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'fínlan');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'gabɔŋ');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'gambí');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'gána');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'ginɛ́');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'ginɛ́ bisɔ́');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'ginɛ́ ɛkwatɔrial');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'grɛ́k');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'grɛnadǝ');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'grínlan');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'guyán');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'guyán i pɛrɛsǝ́');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'gwadɛlúp');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'gwám');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'gwátǝmala');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'ilán');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'indí');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'indonɛsí');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'irák');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'iráŋ');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'israɛ́l');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'italí');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'jamaík');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'japɔ́ŋ');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'jibraltá');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'jɔrdán');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'jɔrjí');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'kalɛdoní anyɔ́n');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'kambodj');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'kamɛrún');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'kanada');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'kapvɛr');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'katá');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'kazakstáŋ');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'kǝlɔŋ kǝ ázǝ');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'kǝlɔŋ kǝ kǝtáatáaŋzǝn');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'kɛnya');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'kigistáŋ');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'kiribáti');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'kolɔmbí');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'komɔr');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'korɛanɔ́r');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'korɛasud');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'kɔngó');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'kɔngó anyɔ́n');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'kɔstaríka');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'kɔtiwuár');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'kpanyá');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'krwasí');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'kuba');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'kuwɛit');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'laɔs');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'lǝsóto');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'lɛtoní');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'libáŋ');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'libɛrya');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'libí');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'lictɛnstɛ́n');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'litwaní');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'luksɛmbúr');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'madagaska');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'malawi');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'maldivǝ');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'malɛsí');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'mali');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'maltǝ');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'marɔk');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'másǝdwán');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'matiník');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'mayɔ́t');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'mɛksík');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'mikronɛ́si');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'monako');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'mosambík');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'mɔldaví');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'mɔnsɛrat');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'mɔŋolí');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'mwarís');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'mwaritaní');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'myanmár');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'namibí');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'nɛpal');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'nijɛ́r');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'nijɛ́rya');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'níkarágwa');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'niwɛ́');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'nɔrvɛjǝ');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'nwarú');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'oman');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'otric');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'ɔnduras');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'ɔngrí');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'ɔstralí');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'pakistáŋ');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'palwa');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'panama');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'papwazí ginɛ́ anyɔ́n');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'paragwɛ́');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'pɛrɛsǝ́');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'pɛrú');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'pitkɛ́n');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'polɔ́n');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'portugál');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'pɔlinɛsí a pɛrɛsǝ́');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'pɔtoríko');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'rɛunyɔŋ');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'risí');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'rɔmaní');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'rwanda');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'salvadɔr');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'samɔa');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'samɔa a amɛrika');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'santrafrík');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'saotomɛ́ ri priŋsib');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'sɛcɛl');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'sɛnɛgal');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'sɛnkrǝstɔ́f ri nyɛ́vǝ');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'sɛnmarǝn');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'sɛnpyɛr ri mikɛlɔŋ');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'sɛntɛ́len');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'sɛntlísí');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'sɛnvǝnsǝŋ ri grɛnadín');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'sɛrbí ri mɔntǝnɛgro');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'siŋapó');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'sirí');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'slovakí');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'slovɛní');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'somalí');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'srílaŋka');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'sudan');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'surinam');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'swazilan');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'swɛdǝ');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'swís');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'syɛraleon');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'tadjikistaŋ');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'tanzaní');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'tɛlan');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'tɛrinitɛ ri tobago');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'tɛwán');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'timor anǝ á ɛst');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'tirkí');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'tirkmɛnistaŋ');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'tokǝlao');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'tɔŋa');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'tunɛsí');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'tuwalu');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'uganda');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'ukrain');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'urugwɛ́');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'usbɛkistaŋ');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'walis ri futuna');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'wanwatu');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'watikáŋ');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'wɛnǝzwɛla');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'wyɛtnám');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'yɛmɛn');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'zambí');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'zǝ bɛ gɔn inɛ á amɛrika');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'zǝ bɛ gɔn inɛ a ingɛrís');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'zǝ i gan');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'zǝ i glás');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'zǝ i marcál');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'zǝ ingɛrís ncɔ́m wa indi');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'zǝ maalwín');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'zǝ maryánnɔ́r');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'zǝ palɛstínǝ');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'zǝ salomɔ́n');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'zǝ tirk ri kakɔs');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'zɛ i kúk');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'zɛ nɔ́fɔlk');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'zɛlan anyɔ́n');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'zimbabwɛ́');
