CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AE', 'Аб\'яднаныя Арабскія Эміраты');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Азербайджан');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Аландскія астравы');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Албанія');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Алжыр');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Аман');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Амерыканскае Самоа');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Ангола');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Ангуілля');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Андора');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Антарктыка');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Антыгуа і Барбуда');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Аргенціна');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Арменія');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Аруба');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Аўстралія');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Аўстрыя');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Афганістан');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Багамскія Астравы');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Балгарыя');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Балівія');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Бангладэш');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Барбадас');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Батсвана');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Бахрэйн');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Беларусь');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Беліз');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Бельгія');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Бенін');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Бермудскія астравы');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Боснія і Герцагавіна');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Бразілія');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Бруней-Дарусалам');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Брытанская тэрыторыя Індыйскага акіяну');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Бувэ востраў');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Буркіна-Фасо');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Бурундзі');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Бутан');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'В\'етнам');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Вануату');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Ватыкан');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Велікабрытанія');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Венгрыя');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Венесуэла');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Віргінскія астравы');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Віргінскія астравы, ЗША');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'Вонкавая Акіянія');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Габон');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Гаіці');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Гамбія');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Гана');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Гандурас');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Гаяна');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Гвадэлупа');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Гватэмала');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Гвінея');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Гвінея-Бісаў');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Германія');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Гібралтар');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'Гон-Конг, Кітай (САР)');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Грузія');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Грэнада');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Грэнландыя');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Грэцыя');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Гэрда востраў і МакДоналда астравы');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Дамініка');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Дамініканская Рэспубліка');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Данія');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Джыбуці');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Егіпет');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Емен');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'Еўрапейскі Звяз');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Замбія');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Заходняя Сахара');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Зімбабвэ');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Злучаныя Штаты');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Іарданія');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Ізраіль');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Інданезія');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Індыя');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Ірак');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Іран, Ісламская Рэспубліка');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Ірландыя');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Ісландыя');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Іспанія');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Італія');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Каба-Вердэ');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Казахстан');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Кайманавы астравы');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Какосавыя астравы');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Калумбія');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Калядаў востраў');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Камбоджа');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Камерун');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Каморскія Астравы');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Канада');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Катар');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Кенія');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Кіпр');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Кірыбаці');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Кітай');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Конга');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Конга, Дэмакратычная Рэспубліка');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Коста-Рыка');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Куба');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Кувейт');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Кука астравы');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Кыргызстан');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Лаоская Народна-Дэмакратычная Рэспубліка');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Латвія');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Лесота');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Ліберыя');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Ліван');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Лівійская Арабская Джамахірыя');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Літва');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Ліхтэнштэйн');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Люксембург');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'М\'янма');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Мадагаскар');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Мазамбік');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'Макао, Кітай (САР)');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Македонія, БЮР');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Малаві');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Малайзія');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Малдова');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Малі');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Мальдыўскія Астравы');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Мальта');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Манака');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Манголія');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Марока');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Марцініка');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Маршалавы Астравы');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Маўрыкій');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Маўрытанія');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Мексіка');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Мікранезія');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Монсэрат');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Намібія');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Нарвегія');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Науру');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Непал');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Нігер');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Нігерыя');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Нідэрландскія Антылы');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Нідэрланды');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Нікарагуа');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Ніуэ');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Новая Зеландыя');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Новая Каледонія');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Норфалкскія астравы');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Пакістан');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Палаў');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Палестынскія тэрыторыі');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Панама');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Папуа-Новая Гвінея');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Парагвай');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Партугалія');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Паўднёва-Афрыканская Рэспубліка');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'Паўднёвая Джорджыя і Паўднёвыя Сандвічавы астравы');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Паўднёвая Карэя');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Паўночная Карэя');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Паўночныя Марыянскія астравы');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Перу');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Польшча');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Расія');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Руанда');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Румынія');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Рэюньён');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Саламонавы Астравы');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Сальвадор');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Самалі');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Самоа (Заходняе)');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Сан-Томэ і Прынсіпі');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Саудаўская Аравія');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Свазіленд');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Свальбард (Паўночна-Усходняя Зямля) і Ян-Маен');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Святой Алены, Востраў');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Сейшэльскія Астравы');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Сенегал');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Сербія');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Сінгапур');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Сірыйская Арабская Рэспубліка');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Славакія');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Славенія');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Судан');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Сурынам');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Сьера-Леонэ');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Сэнт-Вінсэнт і Грэнадыны');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Сэнт-Кітс і Нэвіс');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Сэнт-Люсія');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Таджыкістан');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Тайвань');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Тайланд');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Такелаў');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Тангійская');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Танзанія, Аб\'яднаная Рэспубліка');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Тога');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Трынідад і Табага');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Тувалу');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Туніс');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Туркменістан');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Турцыя');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Тэркс і Кайкас астравы');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Уганда');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Узбекістан');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Украіна');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Уоліс і Футуна');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Уругвай');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Усходні Тымор');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Фіджы');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Філіпіны');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Фінляндыя');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Фолклэндскія астравы');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Франузская Палінэзія');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Французская Гвіяна');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Французскія Паўднёвыя тэрыторыі');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Францыя');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Харватыя');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Цэнтральна-Афрыканская Рэспубліка');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Чад');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Чарнагорыя');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Чылі');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Чэхія');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Швейцарыя');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Швецыя');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Шры-Ланка');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Эквадор');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Экватарыяльная Гвінея');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Эрытрэя');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Эстонія');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Эфіопія');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Ямайка');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Японія');
