CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afganistan');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Antarktis');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigua og Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Aserbajdsjan');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Avstralia');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladesj');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belgia');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belis');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosnia-Hersegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botsvana');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brasilia');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Butan');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Danmørk');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Domingo lýðveldið');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominika');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Egyptaland');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ekvador');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Ekvator Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estland');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Etiopia');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Eysturríki');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Fílabeinsstrondin');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filipsoyggjar');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finnland');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Frakland');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Føroyar');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Grikkaland');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Grønhøvdaoyggjarnar');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Guinea Bissau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Gujana');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Hvítarussland');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'India');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Irak');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Írland');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Ísland');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Ísrael');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italia');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jameika');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japan');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Jemen');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambodja');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kamerun');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kasakstan');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Katar');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Kekkia');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenja');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Kili');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Kina');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirgisia');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Kjad');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolombia');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Komorooyggjarnar');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongo');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Kosta Rika');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Kroatia');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kuba');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuvait');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Kýpros');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesoto');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Lettland');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libanon');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Liktenstein');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Litava');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Luksemborg');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagaskar');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Makedónia');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malavi');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldivuoyggjarnar');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Maleisia');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Marokko');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Marshalloyggjarnar');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Meksiko');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Miðafrikalýðveldið');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikronesia');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monako');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Móritania');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Móritius');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mosambik');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Niðurlond');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikaragua');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Norður-Korea');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Noreg');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Ný Sæland');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papua Nýguinea');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paraguei');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Perú');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Pólland');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Ruanda');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Rumenia');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Russland');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Saint Kitts og Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Saint Lusia');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Saint Vinsent og Grenadinoyggjar');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Sálomonoyggjarnar');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Sambandsríki Amerika');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Sambia');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Sameindu Emirríkini');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Sámoa');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Sao Tome og Prinsipi');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Saudi-Arábia');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seyskelloyggjarnar');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Simbabvi');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapor');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Spania');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Suður-Korea');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Suðurafrika');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Surinam');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Svasiland');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Sveis');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Svøríki');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tadsjikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tansania');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Teivan');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad og Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunesia');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Turkaland');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Týskland');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukreina');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Ungarn');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Uruguei');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Usbekistan');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatikan');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venesuela');
