CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AR', 'Ajɛntîn');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Aljɛlî');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Aŋgɔ́la');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Cât');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Cíllɛ');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Fɛlánci');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Ilâk');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Islayɛ̂l');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Italî');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japɔ̂n');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Kamɛlûn');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Kanadâ');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Kúba');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Kɔllɔmbî');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Kɔmɔ́lɔshi');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Kɔ́t Ndivwâ');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Kɔ́ŋgɔ-Kinshása');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Kɔ́ŋgɔ-Mbɛlazavîl');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kɛ́nya');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libî');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Libɛrî');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Lusî');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Luwánda');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lɛsɔ́tɔ');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Lɛ́uniyɔ̂n');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Maláwi');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Malî');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayɔ̂t');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Mbulukína Fásɔ');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Mbulundí');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Mbɔlivî');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Mbɔtswána');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Mbɛlazîl');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Mbɛnɛ̂ŋ');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Mándaŋgasɛkâ');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mɔlitanî');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Mɔlɔ̂k');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mɔzambîk');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mɛksîk');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namimbî');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Nijɛ̂');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Ninjɛliyâ');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Njimbúti');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Njáman');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Nɔlɛvɛ́jɛ');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Pɛlû');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Pɛsɛ́shɛl');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Shîn');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Siyɛ́la Lɛɔ̂n');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Sundân');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Swazilân');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sáwɔŋ Tɔmɛ́ nɛ́ Pɛlínsipɛ');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Sɔmalî');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Sɛlɛbî');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Sɛnɛgâl');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Sẅísɛ');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzanî');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunizî');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Tɔ́ŋgɔ');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Uŋgánda');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Vɛnɛzwɛ́la');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambî');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbámbwɛ');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Ándɛ');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Ŋgabɔ̂ŋ');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Ŋgambî');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Ŋginɛ̂');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Ŋginɛ̂ Mbisáwu');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Ŋginɛ̂ Ɛkwatɔliyâl');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Ŋgána');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Ŋgɛlɛ̂k');
INSERT INTO "country" ("id", "name") VALUES ('ZZ', 'ŋgɔŋ yi pɛ́ ká kɛ́ jʉɔ');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Ɛjíptɛ');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Ɛkwandɔ̂');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Ɛlitɛlɛ́ya');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Ɛspániya');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Ɛtiyɔpî');
