CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AQ', 'അന്‍റാര്‍ട്ടിക്ക');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'അന്‍റോറ');
INSERT INTO [country] ([id], [name]) VALUES ('AF', 'അഫ്ഗാനിസ്ഥാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'അമേരിക്കന്‍ ഐക്യനാടുകള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'അമേരിക്കന്‍ സാമോവ');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'അംഗോള');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'അയര്‍ലാന്‍ഡ്');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'അര്‍ജന്‍റീന');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'അര്‍മേനിയ');
INSERT INTO [country] ([id], [name]) VALUES ('AX', 'അലന്‍ഡ് ദ്വീപുകള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'അല്‍ബേനിയ');
INSERT INTO [country] ([id], [name]) VALUES ('AC', 'അസന്‍ഷന്‍ ദ്വീപ്');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'അസര്‍ബൈജാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'അള്‍ജീരിയ');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'അറുബ');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'ആന്‍ഗ്വില്ല');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'ആന്‍റിഗ്വയും ബര്‍ബുഡയും');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'ഇക്വഡോര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'ഇക്വിറ്റോറിയല്‍ ഗ്വിനിയ');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'ഇന്‍ഡോനേഷ്യ');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'ഇന്ത്യ');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'ഇസ്രായേല്‍');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'ഇറാക്ക്');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'ഇറാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'ഇറ്റലി');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'ഈജിപ്ത്');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'ഉക്രൈന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'ഉഗാണ്ട');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'ഉത്തര മറിയാനാ ദ്വീപുകള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'ഉത്തരകൊറിയ');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'ഉസ്ബെക്കിസ്ഥാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'ഉറുഗ്വേ');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'എത്യോപ്യ');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'എല്‍ സാല്‍വദോര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'എസ്റ്റോണിയ‍');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'എറിത്രിയ');
INSERT INTO [country] ([id], [name]) VALUES ('IM', 'ഐല്‍ ഓഫ് മാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'ഐവറി കോസ്റ്റ്');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'ഐസ്‌ലാന്റ്');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'ഒമാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'ഓസ്ട്രിയ');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'ഓസ്ട്രേലിയ');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'കംബോഡിയ');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'കസാഖിസ്ഥാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'കാനഡ');
INSERT INTO [country] ([id], [name]) VALUES ('IC', 'കാനറി ദ്വീപുകള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'കാമറൂണ്‍');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'കിരിബാത്തി');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'കിര്‍ഗിസ്ഥാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'കിഴക്കന്‍ തിമൂര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'കുവൈറ്റ്');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'കൂക്ക് ദ്വീപുകള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'കെനിയ');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'കേപ്പ് വെര്‍ഡെ');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'കേയ്മാന്‍ ദ്വീപുകള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'കൊളംബിയ');
INSERT INTO [country] ([id], [name]) VALUES ('CC', 'കോക്കസ്');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'കോമറോസ്');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'കോംഗോ - കിന്‍ഷാസ');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'കോംഗോ - ബ്രാസാവില്‍');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'കോസ്റ്ററിക്ക');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'ക്യൂബ');
INSERT INTO [country] ([id], [name]) VALUES ('CX', 'ക്രിസ്മസ് ദ്വീപ്');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'ക്രൊയേഷ്യ');
INSERT INTO [country] ([id], [name]) VALUES ('CP', 'ക്ലിപ്പെര്‍ട്ടന്‍ ദ്വീപ്');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'ഖത്തര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'ഗയാന');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'ഗാബോണ്‍');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'ഗാംബിയ');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'ഗിനി-ബിസോ');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'ഗുവാഡെലോപ്');
INSERT INTO [country] ([id], [name]) VALUES ('GG', 'ഗേണ്‍സി');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'ഗ്രനേഡ');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'ഗ്രീന്‍ലാന്‍റ്');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'ഗ്രീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'ഗ്വാട്ടിമാലാ');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'ഗ്വാം');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'ഗ്വിനിയ');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'ഘാന');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'ചാഡ്');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'ചിലി');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'ചെക്ക് റിപ്പബ്ലിക്');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'ചൈന');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'ജപ്പാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'ജമൈക്ക');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'ജര്‍മനി');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'ജിബൂട്ടി');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'ജിബ്രാള്‍ട്ടര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('JE', 'ജേഴ്സി');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'ജോര്‍ജിയ');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'ജോര്‍ദ്ദാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'ടര്‍ക്ക്സും കൈക്കോ ദ്വീപുകളും');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'ടാന്‍സാനിയ');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'ടുണീഷ്യ');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'ടൊകെലാവു');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'ടോഗോ');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'ടോംഗ');
INSERT INTO [country] ([id], [name]) VALUES ('TA', 'ട്രസ്റ്റന്‍ ഡ കൂന');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'ട്രിനിഡാഡും റ്റൊബാഗോയും');
INSERT INTO [country] ([id], [name]) VALUES ('DG', 'ഡീഗോ ഗ്രാഷ്യ');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'ഡെന്‍മാര്‍ക്ക്');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'ഡൊമിനിക്ക');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'ഡൊമിനിക്കന്‍ റിപ്പബ്ലിക്');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'താജിക്കിസ്ഥാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'തായ്‌ലാന്‍ഡ്');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'തായ്‌വാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'തുര്‍ക്കി');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'തുര്‍ക്ക്മെനിസ്ഥാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'തുവാലു');
INSERT INTO [country] ([id], [name]) VALUES ('GS', 'ദക്ഷിണ ജോര്‍ജ്ജിയയും ദക്ഷിണ സാന്‍ഡ്‌വിച്ച് ദ്വീപുകളും');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'ദക്ഷിണകൊറിയ');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'ദക്ഷിണാഫ്രിക്ക');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'നമീബിയ');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'നിക്കാരഗ്വ');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'നെതര്‍ലന്‍ഡ്സ്');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'നെതര്‍ലന്‍ഡ്സ് ആന്‍റിലിസ്');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'നേപ്പാള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'നൈജര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'നൈജീരിയ');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'നോര്‍ഫോക് ദ്വീപ്');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'നോര്‍വെ');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'നൗറൂ');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'ന്യൂവേ');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'ന്യൂസിലാന്‍റ്');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'പനാമ');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'പപ്പുവ ന്യൂ ഗ്വിനി');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'പരാഗ്വേ');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'പലാവു');
INSERT INTO [country] ([id], [name]) VALUES ('EH', 'പശ്ചിമ സഹാറ');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'പാക്കിസ്ഥാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'പാലസ്തീന്‍ പ്രദേശങ്ങള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'പിറ്റ്കെയ്ന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'പുതിയ കാലിഡോണിയ');
INSERT INTO [country] ([id], [name]) VALUES ('QO', 'പുറംദ്വീപുകള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'പെറു');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'പോര്‍ച്ചുഗല്‍');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'പോര്‍ട്ടോ റിക്കോ');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'പോളണ്ട്');
INSERT INTO [country] ([id], [name]) VALUES ('FO', 'ഫറോയി ദ്വീപുകള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'ഫാക്ക്‌ലാന്റ് ഐലന്റ്');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'ഫിജി');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'ഫിന്‍ലാന്‍ഡ്');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'ഫിലിപ്പൈന്‍സ്');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'ഫ്രഞ്ച് ഗയാന');
INSERT INTO [country] ([id], [name]) VALUES ('TF', 'ഫ്രഞ്ച് ദക്ഷിണ ഭൂപ്രദേശം');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'ഫ്രഞ്ച് പോളിനേഷ്യ');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'ഫ്രാന്‍സ്');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'ബംഗ്ലാദേശ്');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'ബര്‍മുഡ');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'ബഹാമാസ്');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'ബഹ്റൈന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'ബള്‍ഗേറിയ');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'ബാര്‍ബഡോസ്');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'ബുര്‍ക്കിനാ ഫാസോ');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'ബുറുണ്ടി');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'ബെനിന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'ബെലറൂസ്');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'ബെലീസ്');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'ബെല്‍ജിയം');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'ബൊളീവിയ');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'ബോട്സ്വാന');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'ബോസ്നിയയും ഹെര്‍സഗോവിനയും');
INSERT INTO [country] ([id], [name]) VALUES ('BV', 'ബൗവെറ്റ് ദ്വീപ്');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'ബ്രസീല്‍');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'ബ്രിട്ടന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'ബ്രിട്ടീഷ് ഇന്ത്യന്‍ മഹാസമുദ്ര പ്രദേശം');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'ബ്രിട്ടീഷ് വിര്‍ജിന്‍ ദ്വീപുകള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'ബ്രൂണൈ');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'ഭൂട്ടാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('MO', 'മക്കാവോ SAR ചൈന');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'മഡഗാസ്കര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'മംഗോളിയ');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'മയോട്ട്');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'മലാവി');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'മലേഷ്യ');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'മള്‍ഡോവ');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'മാര്‍ട്ടീനിക്');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'മാര്‍ഷല്‍‍‍ ദ്വീപുകള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'മാലി');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'മാലിദ്വീപ്');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'മാസിഡോണിയ');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'മാള്‍ട്ട');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'മെക്സിക്കോ');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'മൈക്രോനേഷ്യ');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'മൊണോക്കൊ');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'മൊസാംബിക്ക്');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'മൊറോക്കൊ');
INSERT INTO [country] ([id], [name]) VALUES ('ME', 'മോണ്ടേനേഗ്രോ');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'മോണ്ട്സെറാറ്റ്');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'മൗറിറ്റാനിയ');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'മൗറീഷ്യസ്');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'മ്യാന്‍മാര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'യമന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'യു.എസ്. വെര്‍ജിന്‍ ദ്വീപുകള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('UM', 'യുണൈറ്റഡ് സ്റ്റേറ്റ്സും ചെറിയ പുറംദ്വീപുകളും');
INSERT INTO [country] ([id], [name]) VALUES ('EU', 'യൂറോപ്യന്‍ യൂണിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'ലക്സംബര്‍ഗ്');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'ലബനോണ്‍');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'ലാത്വിയ');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'ലാവോസ്');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'ലിത്വാനിയ');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'ലിബിയ');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'ലെസോത്തോ');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'ലൈച്ടെസ്റ്റിന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'ലൈബീരിയ');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'വത്തിക്കാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'വന്വാത്തു');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'വാലിസ് ആന്‍ഡ് ഫ്യുചൂന');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'വിയറ്റ്നാം');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'വെനിസ്വേല');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'ശ്രീലങ്ക');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'സംയുക്ത അറബ് രാഷ്ട്രം');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'സാന്‍ മറിനോ');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'സാമോവ');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'സാംബിയ');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'സാവോ റ്റമെ ആന്‍ഡ് പ്രിന്‍സിപ്പി');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'സിംഗപ്പുര്‍');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'സിംബാബ്വേ');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'സിയേറാ ലിയോണ്‍');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'സിറിയ');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'സുഡാന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'സുറിനാം');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'സെനഗല്‍');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'സെന്‍ട്രല്‍ ആഫ്രിക്കന്‍ റിപ്പബ്ലിക്');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'സെന്‍റ് പിറേയും മിക്വലണും');
INSERT INTO [country] ([id], [name]) VALUES ('BL', 'സെന്‍റ് ബാര്‍ത്തെല്‍മി');
INSERT INTO [country] ([id], [name]) VALUES ('MF', 'സെന്‍റ് മാര്‍ട്ടിന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'സെന്‍റ് ലൂസിയ');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'സെന്‍റ് വിന്‍സന്‍റും ഗ്രനഡൈന്‍സും');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'സെന്‍റ് ഹെലീന');
INSERT INTO [country] ([id], [name]) VALUES ('EA', 'സെയൂത്ത ആന്‍ഡ് മെലിയ');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'സെയ്ന്‍റ് കിറ്റ്സും നെവിസും');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'സെയ്ഷെല്‍സ്');
INSERT INTO [country] ([id], [name]) VALUES ('RS', 'സെര്‍ബിയ');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'സെര്‍ബിയയും മോണ്ടനേഗ്രോയും');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'സൈപ്രസ്സ്');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'സോമാലിയ');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'സോളമന്‍‍ ദ്വീപുകള്‍');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'സൗദി അറേബ്യ');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'സ്പെയിന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'സ്ലോവാക്യ');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'സ്ലോവേനിയ');
INSERT INTO [country] ([id], [name]) VALUES ('SJ', 'സ്വാല്‍ബാഡും ജാന്‍ മായേനും');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'സ്വാസിലാന്‍റ്');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'സ്വിറ്റ്സര്‍ലാന്‍ഡ്');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'സ്വീഡന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'ഹംഗറി');
INSERT INTO [country] ([id], [name]) VALUES ('HM', 'ഹിയേര്‍ഡ് ദ്വീപും മക്ഡൊണാള്ഡ് ദ്വീപുകളും');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'ഹെയ്തി');
INSERT INTO [country] ([id], [name]) VALUES ('HK', 'ഹോങ് കോങ് എസ്.ഏ.ആര്‍. ചൈന');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'ഹോണ്ടുറാസ്');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'റഷ്യ');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'റീയൂണിയന്‍');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'റുമേനിയ');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'റുവാണ്ട');
