CREATE TABLE country (id NVARCHAR(2) NOT NULL, name NVARCHAR(64) NOT NULL, PRIMARY KEY (id));

INSERT INTO [country] ([id], [name]) VALUES ('AF', 'Afganistaŋ');
INSERT INTO [country] ([id], [name]) VALUES ('ZA', 'Afríka yí sí');
INSERT INTO [country] ([id], [name]) VALUES ('EG', 'Ägyptɛn');
INSERT INTO [country] ([id], [name]) VALUES ('AL', 'Albania');
INSERT INTO [country] ([id], [name]) VALUES ('DZ', 'Algeria');
INSERT INTO [country] ([id], [name]) VALUES ('US', 'Amɛŕka');
INSERT INTO [country] ([id], [name]) VALUES ('AD', 'Andɔ́ra');
INSERT INTO [country] ([id], [name]) VALUES ('AO', 'Angola');
INSERT INTO [country] ([id], [name]) VALUES ('AI', 'Anguílla');
INSERT INTO [country] ([id], [name]) VALUES ('AG', 'Antíga bá Barbúda');
INSERT INTO [country] ([id], [name]) VALUES ('AR', 'Argentína');
INSERT INTO [country] ([id], [name]) VALUES ('AM', 'Arménia');
INSERT INTO [country] ([id], [name]) VALUES ('AW', 'Árúba');
INSERT INTO [country] ([id], [name]) VALUES ('IL', 'Äsrɛl');
INSERT INTO [country] ([id], [name]) VALUES ('AZ', 'Azerbaïjaŋ');
INSERT INTO [country] ([id], [name]) VALUES ('AN', 'B''Antilles bó Nedɛrland');
INSERT INTO [country] ([id], [name]) VALUES ('BS', 'Bahamas');
INSERT INTO [country] ([id], [name]) VALUES ('BH', 'Bahrain');
INSERT INTO [country] ([id], [name]) VALUES ('BB', 'Barbado');
INSERT INTO [country] ([id], [name]) VALUES ('BY', 'Belarus');
INSERT INTO [country] ([id], [name]) VALUES ('BJ', 'Benin');
INSERT INTO [country] ([id], [name]) VALUES ('BE', 'Bɛlgik');
INSERT INTO [country] ([id], [name]) VALUES ('BZ', 'Bɛliz');
INSERT INTO [country] ([id], [name]) VALUES ('BD', 'Bɛŋgladɛsh');
INSERT INTO [country] ([id], [name]) VALUES ('BM', 'Bɛrmuda');
INSERT INTO [country] ([id], [name]) VALUES ('BO', 'Bolivia');
INSERT INTO [country] ([id], [name]) VALUES ('BA', 'Bosnia na Ɛrzegovina');
INSERT INTO [country] ([id], [name]) VALUES ('BW', 'Botswana');
INSERT INTO [country] ([id], [name]) VALUES ('BR', 'Brésil');
INSERT INTO [country] ([id], [name]) VALUES ('BN', 'Brunɛi');
INSERT INTO [country] ([id], [name]) VALUES ('BG', 'Bulgaria');
INSERT INTO [country] ([id], [name]) VALUES ('BF', 'Burkina Faso');
INSERT INTO [country] ([id], [name]) VALUES ('BI', 'Burundi');
INSERT INTO [country] ([id], [name]) VALUES ('BT', 'Butaŋ');
INSERT INTO [country] ([id], [name]) VALUES ('DK', 'Danemark');
INSERT INTO [country] ([id], [name]) VALUES ('DM', 'Dominíka');
INSERT INTO [country] ([id], [name]) VALUES ('EC', 'Ekuateur');
INSERT INTO [country] ([id], [name]) VALUES ('ER', 'Erytrea');
INSERT INTO [country] ([id], [name]) VALUES ('ET', 'Ethiopiá');
INSERT INTO [country] ([id], [name]) VALUES ('EE', 'Ɛstonia');
INSERT INTO [country] ([id], [name]) VALUES ('FR', 'Fala');
INSERT INTO [country] ([id], [name]) VALUES ('FJ', 'Fijiá');
INSERT INTO [country] ([id], [name]) VALUES ('PH', 'Filipin');
INSERT INTO [country] ([id], [name]) VALUES ('FI', 'Finlande');
INSERT INTO [country] ([id], [name]) VALUES ('GA', 'Gabɔŋ');
INSERT INTO [country] ([id], [name]) VALUES ('GM', 'Gambia');
INSERT INTO [country] ([id], [name]) VALUES ('GH', 'Gána');
INSERT INTO [country] ([id], [name]) VALUES ('GI', 'Gilbratar');
INSERT INTO [country] ([id], [name]) VALUES ('GL', 'Greenland');
INSERT INTO [country] ([id], [name]) VALUES ('GD', 'Grenada');
INSERT INTO [country] ([id], [name]) VALUES ('GR', 'Grɛce');
INSERT INTO [country] ([id], [name]) VALUES ('GP', 'Guadeloup');
INSERT INTO [country] ([id], [name]) VALUES ('GU', 'Guam');
INSERT INTO [country] ([id], [name]) VALUES ('GT', 'Guatemala');
INSERT INTO [country] ([id], [name]) VALUES ('GN', 'Guine');
INSERT INTO [country] ([id], [name]) VALUES ('GW', 'Guine Bisso');
INSERT INTO [country] ([id], [name]) VALUES ('GQ', 'Guine Ekuatorial');
INSERT INTO [country] ([id], [name]) VALUES ('PG', 'Guine Papuasi');
INSERT INTO [country] ([id], [name]) VALUES ('GY', 'Guyana');
INSERT INTO [country] ([id], [name]) VALUES ('GF', 'Guyane Fala');
INSERT INTO [country] ([id], [name]) VALUES ('HT', 'Haïti');
INSERT INTO [country] ([id], [name]) VALUES ('IN', 'India');
INSERT INTO [country] ([id], [name]) VALUES ('ID', 'Indonesia');
INSERT INTO [country] ([id], [name]) VALUES ('IQ', 'Irak');
INSERT INTO [country] ([id], [name]) VALUES ('IR', 'Iran');
INSERT INTO [country] ([id], [name]) VALUES ('IE', 'Irland');
INSERT INTO [country] ([id], [name]) VALUES ('IS', 'Island');
INSERT INTO [country] ([id], [name]) VALUES ('IT', 'Italia');
INSERT INTO [country] ([id], [name]) VALUES ('JM', 'Jamaika');
INSERT INTO [country] ([id], [name]) VALUES ('DE', 'Jaman');
INSERT INTO [country] ([id], [name]) VALUES ('JP', 'Japɔn');
INSERT INTO [country] ([id], [name]) VALUES ('DJ', 'Jibúti');
INSERT INTO [country] ([id], [name]) VALUES ('JO', 'Jɔrdania');
INSERT INTO [country] ([id], [name]) VALUES ('GE', 'Jɔrgia');
INSERT INTO [country] ([id], [name]) VALUES ('NC', 'Kaledoni nwanah');
INSERT INTO [country] ([id], [name]) VALUES ('KH', 'Kambodia');
INSERT INTO [country] ([id], [name]) VALUES ('CM', 'Kamerun');
INSERT INTO [country] ([id], [name]) VALUES ('CA', 'Kanada');
INSERT INTO [country] ([id], [name]) VALUES ('QA', 'Katar');
INSERT INTO [country] ([id], [name]) VALUES ('KZ', 'Kazakstaŋ');
INSERT INTO [country] ([id], [name]) VALUES ('KE', 'Kɛnya');
INSERT INTO [country] ([id], [name]) VALUES ('KI', 'Kiribati');
INSERT INTO [country] ([id], [name]) VALUES ('CG', 'Kongo');
INSERT INTO [country] ([id], [name]) VALUES ('CD', 'Kongó Zaïre');
INSERT INTO [country] ([id], [name]) VALUES ('KP', 'Koré yí bvuɔ');
INSERT INTO [country] ([id], [name]) VALUES ('KR', 'Koré yí sí');
INSERT INTO [country] ([id], [name]) VALUES ('CR', 'Kosta Ríka');
INSERT INTO [country] ([id], [name]) VALUES ('CI', 'Kote d´Ivoire');
INSERT INTO [country] ([id], [name]) VALUES ('KW', 'Kowɛit');
INSERT INTO [country] ([id], [name]) VALUES ('CO', 'Kɔlɔ́mbia');
INSERT INTO [country] ([id], [name]) VALUES ('KM', 'Kɔmɔr');
INSERT INTO [country] ([id], [name]) VALUES ('HR', 'Kroasia');
INSERT INTO [country] ([id], [name]) VALUES ('CU', 'Kuba');
INSERT INTO [country] ([id], [name]) VALUES ('KG', 'Kyrgystaŋ');
INSERT INTO [country] ([id], [name]) VALUES ('LA', 'Laos');
INSERT INTO [country] ([id], [name]) VALUES ('LV', 'Latvia');
INSERT INTO [country] ([id], [name]) VALUES ('LS', 'Lesoto');
INSERT INTO [country] ([id], [name]) VALUES ('LB', 'Libaŋ');
INSERT INTO [country] ([id], [name]) VALUES ('LR', 'Liberia');
INSERT INTO [country] ([id], [name]) VALUES ('LY', 'Libya');
INSERT INTO [country] ([id], [name]) VALUES ('LI', 'Lishenstein');
INSERT INTO [country] ([id], [name]) VALUES ('LT', 'Lituaniá');
INSERT INTO [country] ([id], [name]) VALUES ('LU', 'Luxembourg');
INSERT INTO [country] ([id], [name]) VALUES ('MK', 'Macedonia');
INSERT INTO [country] ([id], [name]) VALUES ('MG', 'Madagaskar');
INSERT INTO [country] ([id], [name]) VALUES ('MW', 'Malawi');
INSERT INTO [country] ([id], [name]) VALUES ('MY', 'Malaysia');
INSERT INTO [country] ([id], [name]) VALUES ('MV', 'Maldivia');
INSERT INTO [country] ([id], [name]) VALUES ('ML', 'Mali');
INSERT INTO [country] ([id], [name]) VALUES ('MT', 'Malta');
INSERT INTO [country] ([id], [name]) VALUES ('FK', 'Maŋ má Falkland');
INSERT INTO [country] ([id], [name]) VALUES ('CV', 'Maŋ́ má Kapvɛr');
INSERT INTO [country] ([id], [name]) VALUES ('CK', 'Maŋ́ má Kook');
INSERT INTO [country] ([id], [name]) VALUES ('KY', 'Maŋ́ má kumbi');
INSERT INTO [country] ([id], [name]) VALUES ('MH', 'Maŋ́ má Marshall');
INSERT INTO [country] ([id], [name]) VALUES ('NF', 'Maŋ́ má Nɔrfɔrk');
INSERT INTO [country] ([id], [name]) VALUES ('SB', 'Maŋ́ má Salomɔn');
INSERT INTO [country] ([id], [name]) VALUES ('TC', 'Maŋ́ má Turk na Kaiko');
INSERT INTO [country] ([id], [name]) VALUES ('MP', 'Maŋ́ Mariá');
INSERT INTO [country] ([id], [name]) VALUES ('MA', 'Marɔk');
INSERT INTO [country] ([id], [name]) VALUES ('MQ', 'Martinika');
INSERT INTO [country] ([id], [name]) VALUES ('YT', 'Mayɔt');
INSERT INTO [country] ([id], [name]) VALUES ('MX', 'Mɛxik');
INSERT INTO [country] ([id], [name]) VALUES ('FM', 'Mikronesia');
INSERT INTO [country] ([id], [name]) VALUES ('AE', 'Minlambɔ́ Nsaŋ́nsa mí Arabia');
INSERT INTO [country] ([id], [name]) VALUES ('VI', 'Minsilɛ mí maŋ́ m´Amɛrka');
INSERT INTO [country] ([id], [name]) VALUES ('VG', 'Minsilɛ́ mímaŋ mí ngɛ̄lɛ̄n');
INSERT INTO [country] ([id], [name]) VALUES ('MC', 'Monako');
INSERT INTO [country] ([id], [name]) VALUES ('MU', 'Morisse');
INSERT INTO [country] ([id], [name]) VALUES ('MR', 'Moritania');
INSERT INTO [country] ([id], [name]) VALUES ('MZ', 'Mozambik');
INSERT INTO [country] ([id], [name]) VALUES ('MD', 'Mɔldavia');
INSERT INTO [country] ([id], [name]) VALUES ('MN', 'Mɔngolia');
INSERT INTO [country] ([id], [name]) VALUES ('MS', 'Mɔnserrat');
INSERT INTO [country] ([id], [name]) VALUES ('MM', 'Myanmar');
INSERT INTO [country] ([id], [name]) VALUES ('NA', 'Namibia');
INSERT INTO [country] ([id], [name]) VALUES ('NL', 'Nedɛrland');
INSERT INTO [country] ([id], [name]) VALUES ('NP', 'Nepal');
INSERT INTO [country] ([id], [name]) VALUES ('NE', 'Niger');
INSERT INTO [country] ([id], [name]) VALUES ('NG', 'Nigeria');
INSERT INTO [country] ([id], [name]) VALUES ('NI', 'Nikaragua');
INSERT INTO [country] ([id], [name]) VALUES ('NU', 'Niuɛ');
INSERT INTO [country] ([id], [name]) VALUES ('CZ', 'Nlambɔ́ bó tschɛk');
INSERT INTO [country] ([id], [name]) VALUES ('DO', 'Nlambɔ́ Dominíka');
INSERT INTO [country] ([id], [name]) VALUES ('GB', 'Nlambɔ́ Ngɛlɛn');
INSERT INTO [country] ([id], [name]) VALUES ('IO', 'Nlambɔ́ ngɛlɛn ma yí maŋ ntsiɛh');
INSERT INTO [country] ([id], [name]) VALUES ('NR', 'Noru');
INSERT INTO [country] ([id], [name]) VALUES ('NO', 'Nɔrvɛg');
INSERT INTO [country] ([id], [name]) VALUES ('OM', 'Oman');
INSERT INTO [country] ([id], [name]) VALUES ('AU', 'Östraliá');
INSERT INTO [country] ([id], [name]) VALUES ('AT', 'Ötrish');
INSERT INTO [country] ([id], [name]) VALUES ('HN', 'Ɔndúras');
INSERT INTO [country] ([id], [name]) VALUES ('HU', 'Ɔngría');
INSERT INTO [country] ([id], [name]) VALUES ('PK', 'Pakistan');
INSERT INTO [country] ([id], [name]) VALUES ('PS', 'Palɛstin');
INSERT INTO [country] ([id], [name]) VALUES ('PW', 'Palo');
INSERT INTO [country] ([id], [name]) VALUES ('PA', 'Panama');
INSERT INTO [country] ([id], [name]) VALUES ('ES', 'Paŋá');
INSERT INTO [country] ([id], [name]) VALUES ('PY', 'Paraguay');
INSERT INTO [country] ([id], [name]) VALUES ('PE', 'Peru');
INSERT INTO [country] ([id], [name]) VALUES ('PN', 'Pitkairn');
INSERT INTO [country] ([id], [name]) VALUES ('PF', 'Polynesia Fala');
INSERT INTO [country] ([id], [name]) VALUES ('PL', 'Pɔlɔŋ');
INSERT INTO [country] ([id], [name]) VALUES ('PT', 'Pɔrtugal');
INSERT INTO [country] ([id], [name]) VALUES ('PR', 'Puɛrto Riko');
INSERT INTO [country] ([id], [name]) VALUES ('RE', 'Réuniɔn');
INSERT INTO [country] ([id], [name]) VALUES ('RO', 'Roumania');
INSERT INTO [country] ([id], [name]) VALUES ('RU', 'Russi');
INSERT INTO [country] ([id], [name]) VALUES ('RW', 'Rwanda');
INSERT INTO [country] ([id], [name]) VALUES ('KN', 'Saint Kitts na Nevis');
INSERT INTO [country] ([id], [name]) VALUES ('SH', 'Saint Lina');
INSERT INTO [country] ([id], [name]) VALUES ('LC', 'Saint Lucia');
INSERT INTO [country] ([id], [name]) VALUES ('PM', 'Saint Peter ba Mikelɔn');
INSERT INTO [country] ([id], [name]) VALUES ('VC', 'Saint Vincent ba Grenadines');
INSERT INTO [country] ([id], [name]) VALUES ('SV', 'Salvadɔr');
INSERT INTO [country] ([id], [name]) VALUES ('WS', 'Samoa');
INSERT INTO [country] ([id], [name]) VALUES ('AS', 'Samoa m ́Amɛ́rka');
INSERT INTO [country] ([id], [name]) VALUES ('SM', 'San Marino');
INSERT INTO [country] ([id], [name]) VALUES ('ST', 'Sao Tomé ba Prinship');
INSERT INTO [country] ([id], [name]) VALUES ('SA', 'Saudi Arabia');
INSERT INTO [country] ([id], [name]) VALUES ('SN', 'Senegal');
INSERT INTO [country] ([id], [name]) VALUES ('CF', 'Sentrafríka');
INSERT INTO [country] ([id], [name]) VALUES ('SC', 'Seychɛlle');
INSERT INTO [country] ([id], [name]) VALUES ('CS', 'Sɛrbia ba Mɔntenegro');
INSERT INTO [country] ([id], [name]) VALUES ('CN', 'Shine');
INSERT INTO [country] ([id], [name]) VALUES ('SL', 'Sierra Leɔn');
INSERT INTO [country] ([id], [name]) VALUES ('SG', 'Singapur');
INSERT INTO [country] ([id], [name]) VALUES ('CY', 'Sipria');
INSERT INTO [country] ([id], [name]) VALUES ('SK', 'Slovakia');
INSERT INTO [country] ([id], [name]) VALUES ('SI', 'Slovenia');
INSERT INTO [country] ([id], [name]) VALUES ('SO', 'Somália');
INSERT INTO [country] ([id], [name]) VALUES ('LK', 'Sri Lanka');
INSERT INTO [country] ([id], [name]) VALUES ('SD', 'Sudaŋ');
INSERT INTO [country] ([id], [name]) VALUES ('SE', 'Suɛd');
INSERT INTO [country] ([id], [name]) VALUES ('SR', 'Surinam');
INSERT INTO [country] ([id], [name]) VALUES ('SZ', 'Swaziland');
INSERT INTO [country] ([id], [name]) VALUES ('CH', 'Switzɛrland');
INSERT INTO [country] ([id], [name]) VALUES ('SY', 'Syria');
INSERT INTO [country] ([id], [name]) VALUES ('TH', 'Taïland');
INSERT INTO [country] ([id], [name]) VALUES ('TW', 'Taïwan');
INSERT INTO [country] ([id], [name]) VALUES ('TJ', 'Tajikistaŋ');
INSERT INTO [country] ([id], [name]) VALUES ('TZ', 'Tanzánía');
INSERT INTO [country] ([id], [name]) VALUES ('TL', 'Timɔr tsindikēh');
INSERT INTO [country] ([id], [name]) VALUES ('TG', 'Togo');
INSERT INTO [country] ([id], [name]) VALUES ('TK', 'Tokelo');
INSERT INTO [country] ([id], [name]) VALUES ('TO', 'Tɔnga');
INSERT INTO [country] ([id], [name]) VALUES ('TT', 'Trinidad ba Tobágó');
INSERT INTO [country] ([id], [name]) VALUES ('TD', 'Tshad');
INSERT INTO [country] ([id], [name]) VALUES ('CL', 'Tshili');
INSERT INTO [country] ([id], [name]) VALUES ('TN', 'Tunisiá');
INSERT INTO [country] ([id], [name]) VALUES ('TR', 'Turki');
INSERT INTO [country] ([id], [name]) VALUES ('TM', 'Turkmɛnistaŋ');
INSERT INTO [country] ([id], [name]) VALUES ('TV', 'Tuvalú');
INSERT INTO [country] ([id], [name]) VALUES ('UG', 'Uganda');
INSERT INTO [country] ([id], [name]) VALUES ('UA', 'Ukrɛn');
INSERT INTO [country] ([id], [name]) VALUES ('UY', 'Uruguay');
INSERT INTO [country] ([id], [name]) VALUES ('UZ', 'Usbǝkistaŋ');
INSERT INTO [country] ([id], [name]) VALUES ('VU', 'Vanuatu');
INSERT INTO [country] ([id], [name]) VALUES ('VA', 'Vatikaŋ');
INSERT INTO [country] ([id], [name]) VALUES ('VE', 'Vǝnǝzuela');
INSERT INTO [country] ([id], [name]) VALUES ('VN', 'Viɛtnam');
INSERT INTO [country] ([id], [name]) VALUES ('WF', 'Wallis ba Futuna');
INSERT INTO [country] ([id], [name]) VALUES ('YE', 'Yǝmɛn');
INSERT INTO [country] ([id], [name]) VALUES ('ZM', 'Zambia');
INSERT INTO [country] ([id], [name]) VALUES ('NZ', 'Zeland nwanah');
INSERT INTO [country] ([id], [name]) VALUES ('ZW', 'Zimbabwǝ');
