CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Ադրբեջան');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Ալբանիա');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Ալժիր');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Ամէրիկայի Միացյալ Նահանգնէր');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Անգոլա');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Անդորա');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Անտիգուա-Բարբուդա');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Ավստրալիա');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Ավստրիա');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Արգենտինա');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Արեվմտյան Սահարա');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'Աֆղանստան');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Բահամներ');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Բահրեյն');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Բանգլադեշ');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Բարբադոս');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Բելգիա');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Բելիզ');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Բելոռուս');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Բենին');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Բոլիվիա');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Բոսնիա-Հերցեգովինա');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Բոտսվանա');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Բուլղարիա');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Բուտան');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Բուրկինա Ֆասո');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Բուրունդի');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Բրազիլիա');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Բրունեյ');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Գաբոն');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Գամբիա');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Գայանա');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Գանա');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Գերմանիա');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Գվատեմալա');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Գվինեա');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Գվինեա-Բիսաու');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Գրենադա');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Դանիա');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Դոմինիկա');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'Դոմինիկյան Հանրապետություն');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Եգիպտոս');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Եթովպիա');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Եմեն');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Զամբիա');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Զիմբաբվե');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Էկվադոր');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Էստոնիա');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Էրիտրեա');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Թաիլանդ');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Թայվան');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Թունիս');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Թուրքիա');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Թուրքմենստան');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Ինդոնեզիա');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Իռլանդիա');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Իսլանդիա');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Իսպանիա');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Իսրայել');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Իտալիա');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Իրան');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Իրաք');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Լաոս');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Լատվիա');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Լեհաստան');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Լեսոտո');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Լիբանան');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Լիբերիա');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Լիբիա');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Լիխտենշտեյն');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Լիտվա');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Լյուքսեմբուրգ');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Կաբո-Վերդե');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Կամբոջա');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Կամերուն');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Կանադա');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Կատար');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Կենտրոնական Աֆրիկյան Հանրապետություն');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Կիպրոս');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Կիրգիզստան');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Կիրիբատի');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Կոլումբիա');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Կոմորոս');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Կոնգո');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Կոստա-Ռիկա');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Կուբա');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Հաիթի');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Հայաստանի Հանրապետութիւն');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Հասարակածային Գվինեա');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Հարավային Աֆրիկա');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Հարավային Կորեա');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Հյուսիսային Կորեա');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Հնդկաստան');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Հոնդուրաս');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Հորդանան');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Հորվաթիա');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Հունաստան');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Հունգարիա');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Ղազախստան');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Ճապոնիա');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Մադագասկար');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Մալայզիա');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Մալավի');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Մալդիվներ');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Մալթա');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Մալի');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Մակեդոնիա');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Մավրիտանիա');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Մավրիտոս');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Մարշալյան կղզիներ');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Մարոկո');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Մեծ Բրիտանիա');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Մեքսիկա');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Միացյալ Արաբական Էմիրաթներ');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'Միկրոնեզիա');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Մյանմա');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Մոզամբիկ');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Մոլդովա');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Մոնակո');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Մոնղոլիա');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Նամիբիա');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Նաուրու');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Նեպալ');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Նիգեր');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Նիգերիա');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Նիդերլանդեր');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Նիկարագուա');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Նոր Զելանդիա');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Նորվեգիա');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Շվեդիա');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Շվեյցարիա');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Շրի Լանկա');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Ուգանդա');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Ուզբեկստան');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ուկրաինա');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Ուրուգվայ');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Չադ');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Չեխիայի Հանրապետություն');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Չիլի');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Չինաստան');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Պալաու');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Պակիստան');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Պանամա');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Պապուա Նոր Գվինեա');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Պարագվայ');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Պերու');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Պորտուգալիա');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Ջամայկա');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Ջիբուտի');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ռուանդա');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Ռումինիա');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Ռուսաստան');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'Սալվադոր');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Սամոա');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'Սան Մարինո');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Սան-Թոմե-Փրինսիպի');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Սանտա Լուչիա');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Սաուդիան Արաբիա');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Սեյշելներ');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Սենեգալ');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Սենտ Կիտս-Նեվիս');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Սենտ Վիսենտ-Գրենադիններ');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Սինգապուր');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Սիրիա');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Սլովակիա');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Սլովենիա');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Սյերա-Լեոնե');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Սոլոմոնյան կղզիներ');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Սոմալի');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Սուդան');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Սուրինամ');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Սվազիլենդ');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Վանուատու');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'Վատիկան');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Վենեսուելա');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Վիետնամ');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Վրաստան');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Տաճիկստան');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Տանզանիա');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Տոգո');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Տոնգա');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Տուվալու');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Տրինիդադ-Տոբագո');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Փղոսկրի Ափ');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Քենիա');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Քուվեյթ');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Օման');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Ֆիլիպիններ');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Ֆինլանդիա');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Ֆիջի');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'Ֆրանսիա');
