CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afganistāna');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albānija');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Alžīrija');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Amerikāņu Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Amerikas Savienotās Valstis');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andora');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Angilja');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Antarktika');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigva un Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Apvienotie Arābu Emirāti');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argentīna');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armēnija');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'ASV Mazās Aizjūras salas');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'ASV Virdžīnas');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Austrālija');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Austrija');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Austrumtimora');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azerbaidžāna');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamu salas');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahreina');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Baltkrievija');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladeša');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbadosa');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Beliza');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Beļģija');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Benina');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermudu salas');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolīvija');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosnija un Hercegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botsvāna');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brazīlija');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Britu Virdžīnas');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Bruneja');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgārija');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkinafaso');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Butāna');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'Buvē sala');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Centrālāfrikas Republika');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Čada');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Čehija');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Čīle');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Dānija');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'Debesbraukšanas sala');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Dienvidāfrikas Republika');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'Dienviddžordžija un Dienvidsendviču salas');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Dienvidkoreja');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'Djego Garsijas atols');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominika');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Dominikānas Republika');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'Džērsija');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Džibutija');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Ēģipte');
INSERT INTO `country` (`id`, `name`) VALUES ('EU', 'Eiropas Savienība');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ekvadora');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Ekvatoriālā Gvineja');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritreja');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Etiopija');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Fēru Salas');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fidži');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filipīnas');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Folklenda salas');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Francija');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'Franču dienvidu teritorijas');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Franču Gviāna');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Franču Polinēzija');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabona');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Gajāna');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambija');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Gana');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'Gērnsija');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Gibraltārs');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenāda');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Grenlande');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Grieķija');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Gruzija');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guama');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Gvadelupa');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Gvatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Gvineja');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Gvineja-Bisava');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'Hērda un Makdonalda salas');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Hondurasa');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Horvātija');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Igaunija');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Indija');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Indijas okeāna Britu teritorija');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonēzija');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Irāka');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Irāna');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Īrija');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Īslande');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Itālija');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Izraēla');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaika');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japāna');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Jaunkaledonija');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Jaunzēlande');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Jemena');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordānija');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Kaboverde');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Kaimanu salas');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambodža');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kamerūna');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanāda');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'Kanāriju salas');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Katara');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazahstāna');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenija');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Kipra');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirgīzija');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('CP', 'Klipertona sala');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'Kokosu jeb Kīlinga salas');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolumbija');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Komoru salas');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongo - Brazavila');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Kongo-Kinšasa');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Kostarika');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Kotdivuāra');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Krievija');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kuba');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Kuka salas');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuveita');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Ķīna');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'Ķīnas īpašās pārvaldes apgabals Honkonga');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Ķīnas īpašās pārvaldes apgabals Makao');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laosa');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Latvija');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesoto');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libāna');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Libērija');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Lībija');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Lielbritānija');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Lietuva');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Lihtenšteina');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Luksemburga');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagaskara');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Majota');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Maķedonija');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malaizija');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malāvija');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldīvija');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Maroka');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Māršala salas');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinika');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Maurīcija');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauritānija');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Meksika');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Melnkalne');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'Mena');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikronēzija');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Mjanma [Birma]');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldova');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monako');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongolija');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrata');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambika');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namībija');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepāla');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Nīderlande');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Nīderlandes Antiļas');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Nigēra');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigērija');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikaragva');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Norfolkas sala');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norvēģija');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'Okeānijas attālās salas');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Olandes salas');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Omāna');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistāna');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Palestīna');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papua-Jaungvineja');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paragvaja');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitkērna');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Polija');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portugāle');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Puertoriko');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Reinjona');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Rietumsahāra');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Ruanda');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Rumānija');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Salvadora');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'Sanmarīno');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'Santome un Prinsipi');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Saūda Arābija');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seišeļu salas');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'Senbartelmī');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegāla');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'Senmartēna');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Senpjēra un Mikelona');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Sentkitsa un Nevisa');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Sentlūsija');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Sentvinsenta un Grenadīnas');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Serbija');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Serbija un Melnkalne');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'Seūta un Meliļa');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapūra');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Sīrija');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sjerraleone');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Slovākija');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Slovēnija');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somālija');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Somija');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Spānija');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudāna');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Surinama');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Sv. Helēnas sala');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Svalbāra un Jana Majena sala');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Svazilenda');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Šrilanka');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Šveice');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tadžikistāna');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taivāna');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Taizeme');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzānija');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Tērksas un Kaikosas salas');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidāda un Tobāgo');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'Tristana da Kuņas salas');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunisija');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Turcija');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenistāna');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukraina');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Ungārija');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Urugvaja');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzbekistāna');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Vācija');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatikāns');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venecuēla');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vjetnama');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Volisa un Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Zālamana salas');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambija');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Ziemeļkoreja');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Ziemeļu Marianas salas');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Ziemsvētku sala');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabve');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Zviedrija');
