CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('001', 'silarsuaq');
INSERT INTO `country` (`id`, `name`) VALUES ('002', 'Afrika');
INSERT INTO `country` (`id`, `name`) VALUES ('003', 'Amerika Avannarleq');
INSERT INTO `country` (`id`, `name`) VALUES ('005', 'Amerika Kujalleq');
INSERT INTO `country` (`id`, `name`) VALUES ('009', 'Oceania');
INSERT INTO `country` (`id`, `name`) VALUES ('011', 'Afrika Killiit');
INSERT INTO `country` (`id`, `name`) VALUES ('013', 'America Qitiusumik');
INSERT INTO `country` (`id`, `name`) VALUES ('014', 'Afrika Kangilliit');
INSERT INTO `country` (`id`, `name`) VALUES ('015', 'Afrika Avannarleq');
INSERT INTO `country` (`id`, `name`) VALUES ('017', 'Afrika Qitiusumik');
INSERT INTO `country` (`id`, `name`) VALUES ('019', 'Amerika');
INSERT INTO `country` (`id`, `name`) VALUES ('030', 'Asia Kangilliit');
INSERT INTO `country` (`id`, `name`) VALUES ('034', 'Asia Kujalleq');
INSERT INTO `country` (`id`, `name`) VALUES ('039', 'Europa Kujalleq');
INSERT INTO `country` (`id`, `name`) VALUES ('053', 'Australia aamma Nutaaq Zeeland');
INSERT INTO `country` (`id`, `name`) VALUES ('054', 'Melanesia');
INSERT INTO `country` (`id`, `name`) VALUES ('061', 'Polynesia');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andorra');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afghanistan');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigua aamma Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albania');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armenia');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Qalasersuaq Kujalleq');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argentina');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Østrigi');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Australia');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Ålandi');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosnia aamma Herzegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbados');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belgia');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Faso');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgaria');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahrain');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunei');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolivia');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brasilien');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamas');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botswana');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Hvideruslandi');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Canada');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Kongo-Kinshasa');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongo-Brazzaville');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Schweizi');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Kina');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Colombia');
INSERT INTO `country` (`id`, `name`) VALUES ('CP', 'Clipperton qeqertaq');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Costa Rica');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kuba');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Cap Verde');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Jul-qeqertaq');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Tjekkia');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Tysklandi');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'Diego Garcia');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Djibouti');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Danmarki');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominica');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Algeriet');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'Ceuta aamma Melilla');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ecuador');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estlandi');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Egypten');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Sahara Killiit');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritrea');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Spania');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Ethiopia');
INSERT INTO `country` (`id`, `name`) VALUES ('EU', 'Europami nunat kattusimaffiat');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Finlandi');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fiji');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Falklandi qeqertaq');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Micronesia');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Savalimmiut');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Frankrigi');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabon');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Tuluit Nunaat');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Georgia');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'Guernsey');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Ghana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Gibraltar');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Kalaallit Nunaat');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambia');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Guadeloupe');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Grækenlandi');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Guatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guam');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'Hongkong');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Honduras');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Ungarni');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'Kanaria qeqertaq');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonesia');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Irlandi');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Israel');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'India');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Irak');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iran');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Islandi');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italia');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'Jersey');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaica');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japani');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenya');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambodia');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Saint Kitts aamma Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Korea Avannarleq');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Korea Kujalleq');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuwait');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kasakhstani');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laos');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libanon');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Saint Lucia');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Liechtenstein');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Sri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberia');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesotho');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Litaueni');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Luxembourg');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Letlandi');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libya');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Marocko');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monaco');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldavia');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Montenegro');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'Saint Martin');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagaskar');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Makedonia');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Burma');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Macao');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinique');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauritania');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserrat');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Mauritius');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Mexiko');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malaysia');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Moçambique');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibia');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Nutaaq Caledonia');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Niger');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigeria');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nicaragua');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Hollandi');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norge');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepal');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Nutaaq Zeeland');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papua Nutaaq Guinea');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistan');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Poleni');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Saint Pierre aamma Miquelon');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Puerto Rico');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portugali');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paraguay');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Quatar');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Réunion');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Rumænia');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Serbia');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Ruslandi');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Rwanda');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Saudi Arabia');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudan');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Sverige');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapore');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Saint Helena');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Slovenia');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Svalbard aamma Jan Mayen');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Slovakia');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Sierra Leone');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San Marino');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegal');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somalia');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Suriname');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'São Tomé aamma Príncipe');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'El Salvador');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Syria');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Swazilandi');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Chad');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Thailandi');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tajikistan');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Timor Kangilliit');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmenistani');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunisia');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Tyrkia');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidad aamma Tobago');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taiwan');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzania');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukraina');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Naalagaaffeqatigiit');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Uruguay');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzbekistani');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatikani');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venezuela');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vietnam');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallis aamma Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Jemen');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayotte');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambia');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabwe');
INSERT INTO `country` (`id`, `name`) VALUES ('ZZ', 'atorsinnaanngitsoq sinerissap ilaa aalajangersimasoq');
INSERT INTO `country` (`id`, `name`) VALUES ('142', 'Asia');
INSERT INTO `country` (`id`, `name`) VALUES ('143', 'Asia Qitiusumik');
INSERT INTO `country` (`id`, `name`) VALUES ('145', 'Asia Killiit');
INSERT INTO `country` (`id`, `name`) VALUES ('150', 'Europa');
INSERT INTO `country` (`id`, `name`) VALUES ('151', 'Europa Kangilliit');
INSERT INTO `country` (`id`, `name`) VALUES ('154', 'Europa Avannarleq');
INSERT INTO `country` (`id`, `name`) VALUES ('155', 'Europa Killiit');
INSERT INTO `country` (`id`, `name`) VALUES ('419', 'America Latin aamma Karibia');
