CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AF', 'Afghanistan');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'Afrique du Sud');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'Albanie');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'Algérie');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'Allemagne');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andorre');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angola');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anguilla');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'Antarctique');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'Antigua-et-Barbuda');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Antilles néerlandaises');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'Arabie saoudite');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'Argentine');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'Arménie');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Aruba');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'Australie');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'Autriche');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'Azerbaïdjan');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Bahamas');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bahreïn');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'Bangladesh');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbade');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'Bélarus');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'Belgique');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'Belize');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Bénin');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Bermudes');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'Bhoutan');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'Bolivie');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'Bosnie-Herzégovine');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'Botswana');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'Brésil');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brunéi Darussalam');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'Bulgarie');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Burkina Faso');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'Burundi');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'Cambodge');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Cameroun');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Canada');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'Cap-Vert');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'Ceuta et Melilla');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'Chili');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'Chine');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'Chypre');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'Colombie');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Comores');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'Congo-Brazzaville');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'Corée du Nord');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'Corée du Sud');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Costa Rica');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'Côte d’Ivoire');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'Croatie');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Cuba');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'Danemark');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'Diego Garcia');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Djibouti');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Dominique');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'Égypte');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'El Salvador');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Émirats arabes unis');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Équateur');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'Érythrée');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'Espagne');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'Estonie');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'État de la Cité du Vatican');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'États fédérés de Micronésie');
INSERT INTO "country" ("id", "name") VALUES ('US', 'États-Unis');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'Éthiopie');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fidji');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'Finlande');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'France');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'Gabon');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'Gambie');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'Géorgie');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'Géorgie du Sud et les îles Sandwich du Sud');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Ghana');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Gibraltar');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'Grèce');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenade');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'Groenland');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadeloupe');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatemala');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Guernesey');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'Guinée');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'Guinée équatoriale');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'Guinée-Bissau');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'Guyana');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'Guyane française');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Haïti');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Honduras');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'Hongrie');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Île Bouvet');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Île Christmas');
INSERT INTO "country" ("id", "name") VALUES ('CP', 'Île Clipperton');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'Île de l\'Ascension');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Île de Man');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Île Norfolk');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Îles Åland');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Îles Caïmans');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'Îles Canaries');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Îles Cocos - Keeling');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Îles Cook');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Îles Féroé');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Îles Heard et MacDonald');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Îles Malouines');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Îles Mariannes du Nord');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Îles Marshall');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'Îles Mineures Éloignées des États-Unis');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Îles Salomon');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Îles Turks et Caïques');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Îles Vierges britanniques');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Îles Vierges des États-Unis');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'Inde');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'Indonésie');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'Irak');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'Iran');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Irlande');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'Islande');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Israël');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'Italie');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Jamaïque');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'Japon');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Jersey');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'Jordanie');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'Kazakhstan');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'Kenya');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'Kirghizistan');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Kiribati');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Koweït');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laos');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Lesotho');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'Lettonie');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'Liban');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'Libéria');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'Libye');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Liechtenstein');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'Lituanie');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Luxembourg');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'Macédoine');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagascar');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'Malaisie');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'Malawi');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Maldives');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mali');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Malte');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Maroc');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martinique');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Maurice');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'Mauritanie');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayotte');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Mexique');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'Moldavie');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monaco');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'Mongolie');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Monténégro');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Montserrat');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mozambique');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Myanmar');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'Namibie');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nauru');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Népal');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nicaragua');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'Niger');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'Nigéria');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Niue');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'Norvège');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'Nouvelle-Calédonie');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'Nouvelle-Zélande');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Oman');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Ouganda');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Ouzbékistan');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'Pakistan');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palaos');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Papouasie-Nouvelle-Guinée');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paraguay');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'Pays-Bas');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Pérou');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Philippines');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitcairn');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'Pologne');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'Polynésie française');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Porto Rico');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'Portugal');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Qatar');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'R.A.S. chinoise de Hong Kong');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'R.A.S. chinoise de Macao');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'régions éloignées de l’Océanie');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'République centrafricaine');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'République démocratique du Congo');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'République dominicaine');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'République tchèque');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Réunion');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'Roumanie');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'Royaume-Uni');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Russie');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Rwanda');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'Sahara occidental');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'Saint-Barthélémy');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Saint-Kitts-et-Nevis');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'Saint-Marin');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'Saint-Martin');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Saint-Pierre-et-Miquelon');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Saint-Vincent-et-les Grenadines');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'Sainte-Hélène');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'Sainte-Lucie');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samoa');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Samoa américaines');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sao Tomé-et-Principe');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'Sénégal');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'Serbie');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'Serbie-et-Monténégro');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Seychelles');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Sierra Leone');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singapour');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'Slovaquie');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'Slovénie');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'Somalie');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'Soudan');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Sri Lanka');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'Suède');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'Suisse');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Suriname');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Svalbard et Île Jan Mayen');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'Swaziland');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'Syrie');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'Tadjikistan');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'Taïwan');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'Tanzanie');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Tchad');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Terres australes françaises');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Territoire britannique de l\'océan Indien');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Territoire palestinien');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'Thaïlande');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Timor oriental');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Togo');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tokelau');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Trinité-et-Tobago');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'Tristan da Cunha');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'Tunisie');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'Turkménistan');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'Turquie');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Tuvalu');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'Ukraine');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'Union européenne');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Uruguay');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatu');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Venezuela');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Viêt Nam');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Wallis-et-Futuna');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Yémen');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'Zambie');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'Zimbabwe');
