CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('CA', 'ကနေဒါ');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'ကာဇက်စတန်');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'ကာတာ');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'ကူဝိတ်');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'ကေမန် ကျွန်းစု');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'ကော့စ်တာရီကာ');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'ကိုကိုး ကျွန်းစု');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'ကိုလံဘီယာ');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'ကင်ညာ');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'ကင်မရွန်း');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'ကမ္ဘောဒီးယား');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'ကျူးဘား');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'ကွတ် ကျွန်းစု');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'ခရိုအေးရှား');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'ခရစ်စမတ် ကျွန်း');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'ချီလီ');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'ချက် ပြည်ထောင်စု');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'ချဒ်');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'ဂရိ');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'ဂရင်းလန်း');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'ဂါနာ');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'ဂီရာနာ');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'ဂူအမ်');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'ဂန်ဘီရာ');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'ဂျပန်');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'ဂျမေနီကာ');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'ဂျာစီ');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'ဂျာမဏီ');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'ဂျီဘရော်လ်တာ');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'ဂျော်ဂျီယာ');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'ဂျော်ဒန်');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'ဂွာတီမာလာ');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'စပိန်');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'စလိုဗေးကီးယား');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'စလိုဗေးနီးယား');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'စင်္ကာပူ');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'စိန့်မာတင်');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'ဆားဘီးယား');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'ဆီနီဂေါ');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'ဆီးရီးယား');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'ဆူဒန်');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'ဆော်ဒီအာရေးဗီးယား');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'ဆော်လမွန်ကျွန်းစု');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'ဆိုမာလီယာ');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'ဆိုက်ပရက်စ်');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'ဆွီဒင်');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'ဆွစ်ဇလန်');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'ဇင်ဘာဘွေ');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'ဇမ်ဘီယာ');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'တရုတ်');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'တရုတ်၏ အထူးအုပ်ချုပ်ခွင့်ရ မကာအို');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'တရုတ်၏ အထူးအုပ်ချုပ်ခွင့်ရ ဟောင်ကောင်');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'တာဂျီကစ္စတန်');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'တူနီးရှား');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'တူရကီ');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'တောင်ကိုရီးယား');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'တောင်အာဖရိက');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'တန်ဇန်နီးယား');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'တွန်ဂါ');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'ထိုင်ဝမ်');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'ထိုင်း');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'ဒိုမီနီကာ');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'ဒိုမီနီကန်');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'ဒိန်းမတ်');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'နယူး ကယ်လီဒိုနီးယား');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'နယူးဇီလန်');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'နီကာရာဂွာ');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'နီပေါ');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'နော်ဝေ');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'နိုင်ဂျာ');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'နိုင်ဂျီးရီးယား');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'နမ်မီးဘီးယား');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'နယ်သာလန်');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'ပနားမား');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'ပါကစ္စတန်');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'ပါပူရာနယူးဂီနီ');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'ပါရာဂွေး');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'ပါလက်စတိုင်း ပိုင်နက်');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'ပီရူး');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'ပေါ်တူဂီ');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'ပေါ်တူရီကို');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'ပိုလန်');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'ပြင်သစ်');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'ပြင်သစ် ဂီယာနာ');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'ပြင်သစ် တောင်ပိုင်း ပိုင်နက်များ');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'ပြင်သစ် ပေါ်လီနေးရှား');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'ဖာရိုး ကျွန်းစုများ');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'ဖိလစ်ပိုင်');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'ဖီဂျီ');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'ဖောက်ကလန် ကျွန်းစု');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'ဖင်လန်');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'ဗာတီကန်');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'ဗီယက်နမ်');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'ဗင်နီဇွဲလား');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'ဗြိတိသျှ ဗာဂျင်း ကျွန်းစု');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'ဗြိတိသျှ အိန္ဒြိယ သမုဒ္ဒရာ ပိုင်နက်');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'ဘရာဇီး');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'ဘရူနိုင်း');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'ဘဟားမား');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'ဘာမူဒါ');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'ဘာရိန်း');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'ဘီလာရုစ်');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'ဘူဂေးရီးယား');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'ဘူတန်');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'ဘေလီဇ်');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'ဘော့စနီးယား နှင့် ဟာဇီဂိုဘီးနား');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'ဘော့စ်ဝါနာ');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'ဘိုလီးဘီးယား');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'ဘင်္ဂလားဒေ့ရှ်');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'ဘယ်လ်ဂျီယမ်');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'မဒဂတ်စကာ');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'မလေးရှား');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'မာစီဒိုးနီးယား');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'မာရှယ် ကျွန်းစု');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'မာလာဝီ');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'မာလီ');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'မော်ရိုကို');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'မော်လဒိုက်');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'မိုဇန်ဘစ်');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'မိုနကို');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'မက္ကဆီကို');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'မြောက်ကိုရီးယား');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'မြန်မာ');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'မွန်ဂိုးလီးယား');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'မွန်တီနိဂရိုး');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'ယီမင်');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'ယူကရိန်း');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'ယူဂန္ဒာ');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'ယူနိုက်တက်ကင်းဒမ်း');
INSERT INTO "country" ("id", "name") VALUES ('US', 'ယူနိုက်တက်စတိတ်');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'ယူနိုက်တက်စတိတ် အပြင်ထွက် နေသည့် သေးငယ်သောကျွန်းများ');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'ယူအေအီး');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'ယူအက်စ် ဗာဂျင်း ကျွန်းစု');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'ရဝန်ဒါ');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'ရုရှ');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'ရိုမေးနီးယား');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'လာအို');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'လူဇင်ဘတ်');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'လက်ဘနွန်');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'လိုင်ဘေးရီးယား');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'လစ်သူယေးနီးယား');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'လတ်ဗီးယား');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'သီရိလင်္ကာ');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'ဟေတီ');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'ဟန်ဂေရီ');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'ဟွန်ဒူးရပ်စ်');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'အဇာဘိုင်ဂျန်');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'အနောက်ပိုင်း ဆာဟာရ');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'အမေရိကန် စမိုအ');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'အရှေ့တီမော');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'အလယ်ပိုင်း အာဖရိက ပြည်ထောင်စု');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'အာဂျင်တီးနား');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'အာဖဂန်နစ္စတန်');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'အာမေနီးယား');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'အီကွေတာ ဂီရာနာ');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'အီကွေဒေါ');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'အီဂျစ်');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'အီတလီ');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'အီရတ်');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'အီရန်');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'အီသီယိုးပီးယား');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'ဥဘက်ကစ္စတန်');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'ဥရုဂွေး');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'ဥရောပသမဂ္ဂ');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'ဩစတြီးယား');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'ဩစတြေးလျှား');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'အိုမန်');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'အက်စတိုးနီးယား');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'အိုက်စလန်');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'အင်ဂိုလာ');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'အင်ဒိုနီးရှား');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'အိုင်ဗရီကိုစ့်');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'အိုင်ယာလန်');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'အစ္စရေး');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'အန်ကွီလာ');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'အန္တာတိက');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'အိန္ဒိယ');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'အယ်လ်ဂျီးရီးယား');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'အယ်လ်ဆာဗေးဒိုး');
