CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'ئارگېنتىنا');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'ئارۇبا');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'ئاسسېنسىيون ئارىلى');
INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'ئافغانىستان');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'ئالاند ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'ئالبانىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'ئالجىرىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'ئامېرىكا تەۋەلىكىدىكى ساموئا');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'ئامېرىكا تەۋەلىكىدىكى سىرتقى كىچىك ئاراللار');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'ئامېرىكا تەۋەلىكىدىكى ۋىرجىن تاقىم ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'ئامېرىكا قوشما شتاتلىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'ئانتاركتىكا');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'ئانتىگۋا ۋە باربۇدا');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'ئاندوررا');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'ئانگولا');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'ئانگۋىللا');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'ئاۋسترالىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'ئاۋسترىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'ئاۋمېن ئالاھىدە مەمۇرىي رايونى (جۇڭگو)');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'ئەرمېنىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'ئەرەب بىرلەشمە خەلىپىلىكى');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'ئەزەربەيجان');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'ئەل سالۋادور');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'ئەنگلىيە پادىشاھلىقى');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'ئەنگلىيەگە قاراشلىق ۋىرجىن ئارىلى');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'ئەنگلىيەنىڭ ھىندى ئوكياندىكى تەۋەلىكى');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'ئوتتۇرا ئافرىقا جۇمھۇرىيىتى');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'ئومان');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'ئۆزبېكىستان');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'ئۇرۇگۋاي');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'ئۇكرائىنا');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'ئۇگاندا');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'ئىتالىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'ئىراق');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'ئىران');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'ئىرېلاندىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'ئىسپانىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'ئىسرائىلىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'ئىسلاندىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'ئىيوردانىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'ئېرىترېيە');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'ئېستونىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'ئېفىيوپىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'ئېكۋاتور گىۋىنېيەسى');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'ئېكۋادور');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'باربادوس');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'باڭلادىش');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'باھاما');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'بەھرەين');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'بوتسۋانا');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'بوسنىيە-گېرتسېگوۋىنا');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'بولىۋىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'بۇتان');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'بۇركىنا-فاسو');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'بۇرۇندى');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'بۇلغارىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'بىرازىلىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'بىرما');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'بىرۇنېي');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'بېرمۇدا');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'بېلارۇسىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'بېلگىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'بېلىز');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'بېنىن');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'پاپۇئا يېڭى گىۋىنېيەسى');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'پاراگۋاي');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'پاكىستان');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'پالاۋ');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'پاناما');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'پەلەستىن زېمىنى');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'پورتۇگالىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'پولشا');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'پۇئېرتو-رىكو');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'پىتكاير ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'پېرۇ');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'تاجىكىستان');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'تانزانىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'تايلاند');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'ترىستان داكۇنھا');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'تەيۋەن');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'توكېلاۋ');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'توگو');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'تونگا');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'تۇركس ۋە كايكوس ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'تۇنىس');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'تۇۋالۇ');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'تۈركمەنىستان');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'تۈركىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'تىرىنىداد ۋە توباگو');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'جەبىلتارىق');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'جەنۇبىي ئافرىقا');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'جەنۇبىي جورجىيە ۋە جەنۇبىي ساندىۋىچ ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('SS', 'جەنۇبىي سۇدان');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'جەنۇبىي كورىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'جۇڭگو');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'جىبۇتى');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'جېرسېي');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'چاد');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'چىلى');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'چېخ جۇمھۇرىيىتى');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'دانىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'دومىنىكا');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'دومىنىكا جۇمھۇرىيىتى');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'دېگو-گارشىيا');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'روژدېستۋو ئارىلى');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'رۇسىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'رۇمىنىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'رىۋاندا');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'رېئونىيون');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'زامبىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'زىمبابۋې');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'ساموئا');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'سان تومې ۋە پرىنسىپې');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'سان-مارىنو');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'ساينىت ھېلېنا');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'ساينىت-بارتھېلەمي ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'ساينىت-پىئېر ۋە مىكېلون ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'ساينىت-كىرىستوفېر ۋە نېۋىس');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'ساينىت-لۇسىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'ساينىت-مارتېن');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'ساينىت-ۋىنسېنت ۋە گىرېنادىنېس');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'سەئۇدى ئەرەبىستان');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'سولومون ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'سومالى');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'سۇدان');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'سۇرىنام');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'سۈرىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'سىپرۇس');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'سىرىلانكا');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'سىلوۋاكىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'سىلوۋېنىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('SX', 'سىنت مارتېن');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'سىنگاپور');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'سىۋالبارد ۋە يان-مايېن ئارىلى');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'سىۋېزىلاند');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'سېربىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'سېررالېئون');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'سېنېگال');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'سېيتا ۋە مېلىلا');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'سېيشېل');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'شەرقىي تىمور');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'شىمالىي كورىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'شىمالىي مارىيانا ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'شىۋىتسارىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'شىۋېتسىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'شياڭگاڭ ئالاھىدە مەمۇرىي رايونى (جۇڭگو)');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'غەربىي ساخارا');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'فائېرو ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'فالكلاند ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'فىجى');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'فىرانسىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'فىرانسىيەگە قاراشلىق پولىنېزىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'فىرانسىيەگە قاراشلىق جەنۇبتىكى زېمىنلىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'فىرانسىيەگە قاراشلىق گىۋىيانا');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'فىلىپپىن');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'فىنلاندىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'قاتار');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'قازاقىستان');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'قىرغىزىستان');
INSERT INTO `country` (`id`, `name`) VALUES ('BQ', 'كارىب دېڭىزى گوللاندىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'كامبودژا');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'كامېرون');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'كانادا');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'كانارى ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'كايمان ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'كەئەلىڭ كوكۇس ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'كوتې دې ئىۋوئىر');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'كوستارىكا');
INSERT INTO `country` (`id`, `name`) VALUES ('XK', 'كوسوۋو');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'كولومبىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'كومورو');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'كونگو - بىراززاۋىل');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'كونگو - كىنشاسا');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'كۇبا');
INSERT INTO `country` (`id`, `name`) VALUES ('CW', 'كۇراسو');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'كۇك ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'كۇۋەيت');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'كىرودىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'كىرىباتى');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'كېنىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'گابون');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'گامبىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'گانا');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'گوللاندىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'گۇئام');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'گىروزىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'گىرېتسىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'گىرېنادا');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'گىرېنلاند');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'گىۋاتېمالا');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'گىۋادېلۇپ');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'گىۋىنېيە');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'گىۋىنېيە-بىسسائۇ');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'گىۋىيانا');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'گېرمانىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'گېرىنسى');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'لائوس');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'لاتۋىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'لىبېرىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'لىتۋانىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'لىچتېنشتېين بەگلىكى');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'لىۋان');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'لىۋىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'لىيۇكسېمبۇرگ');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'لېسوتو');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'ماداغاسقار');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'ماراكەش');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'مارتىنىكا');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'مارشال ئاراللىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'ماكېدونىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'مالاۋى');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'مالايشىيا');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'مالتا');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'مالدىۋې');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'مالى');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'ماۋرىتانىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'ماۋرىتىئۇس');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'مايوتتې');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'موزامبىك');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'موڭغۇلىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'مولدوۋا');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'موناكو');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'مونتسېررات');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'مونتېنېگرو');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'مىسىر');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'مىكرونېزىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'مېكسىكا');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'مېن ئارىلى');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'نامىبىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'ناۋرۇ');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'نورفولك ئارىلى');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'نورۋېگىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'نىكاراگۇئا');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'نىگېرىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'نىيۇئې');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'نېپال');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'نېگىر');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'ھايتى');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'ھوندۇراس');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'ھىندونېزىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'ھىندىستان');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'ۋاتىكان شەھىرى');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'ۋالىس ۋە فۇتۇنا');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'ۋانۇئاتۇ');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'ۋىيېتنام');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'ۋېنگىرىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'ۋېنېزۇئېلا');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'ياپونىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'يامايكا');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'يەمەن');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'يېشىل تۇمشۇق');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'يېڭى زېلاندىيە');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'يېڭى كالېدونىيە');
