CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

INSERT INTO `country` (`id`, `name`) VALUES ('AF', 'Afganistanas');
INSERT INTO `country` (`id`, `name`) VALUES ('IE', 'Airija');
INSERT INTO `country` (`id`, `name`) VALUES ('AX', 'Alandų salos');
INSERT INTO `country` (`id`, `name`) VALUES ('AL', 'Albanija');
INSERT INTO `country` (`id`, `name`) VALUES ('DZ', 'Alžyras');
INSERT INTO `country` (`id`, `name`) VALUES ('AS', 'Amerikos Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('AD', 'Andora');
INSERT INTO `country` (`id`, `name`) VALUES ('AI', 'Angilija');
INSERT INTO `country` (`id`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`id`, `name`) VALUES ('AQ', 'Antarktis');
INSERT INTO `country` (`id`, `name`) VALUES ('AG', 'Antigva ir Barbuda');
INSERT INTO `country` (`id`, `name`) VALUES ('AR', 'Argentina');
INSERT INTO `country` (`id`, `name`) VALUES ('AM', 'Armėnija');
INSERT INTO `country` (`id`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`id`, `name`) VALUES ('AC', 'Ascension sala');
INSERT INTO `country` (`id`, `name`) VALUES ('AU', 'Australija');
INSERT INTO `country` (`id`, `name`) VALUES ('AT', 'Austrija');
INSERT INTO `country` (`id`, `name`) VALUES ('AZ', 'Azerbaidžanas');
INSERT INTO `country` (`id`, `name`) VALUES ('BS', 'Bahamos');
INSERT INTO `country` (`id`, `name`) VALUES ('BH', 'Bahreinas');
INSERT INTO `country` (`id`, `name`) VALUES ('BY', 'Baltarusija');
INSERT INTO `country` (`id`, `name`) VALUES ('BD', 'Bangladešas');
INSERT INTO `country` (`id`, `name`) VALUES ('BB', 'Barbadosas');
INSERT INTO `country` (`id`, `name`) VALUES ('BE', 'Belgija');
INSERT INTO `country` (`id`, `name`) VALUES ('BZ', 'Belizas');
INSERT INTO `country` (`id`, `name`) VALUES ('BJ', 'Beninas');
INSERT INTO `country` (`id`, `name`) VALUES ('BM', 'Bermuda');
INSERT INTO `country` (`id`, `name`) VALUES ('GW', 'Bisau Gvinėja');
INSERT INTO `country` (`id`, `name`) VALUES ('BO', 'Bolivija');
INSERT INTO `country` (`id`, `name`) VALUES ('BA', 'Bosnija ir Hercegovina');
INSERT INTO `country` (`id`, `name`) VALUES ('BW', 'Botsvana');
INSERT INTO `country` (`id`, `name`) VALUES ('BV', 'Bouvet sala');
INSERT INTO `country` (`id`, `name`) VALUES ('BR', 'Brazilija');
INSERT INTO `country` (`id`, `name`) VALUES ('BN', 'Brunėjus');
INSERT INTO `country` (`id`, `name`) VALUES ('BG', 'Bulgarija');
INSERT INTO `country` (`id`, `name`) VALUES ('BF', 'Burkina Fasas');
INSERT INTO `country` (`id`, `name`) VALUES ('BI', 'Burundis');
INSERT INTO `country` (`id`, `name`) VALUES ('BT', 'Butanas');
INSERT INTO `country` (`id`, `name`) VALUES ('CF', 'Centrinės Afrikos Respublika');
INSERT INTO `country` (`id`, `name`) VALUES ('EA', 'Ceuta ir Melilla');
INSERT INTO `country` (`id`, `name`) VALUES ('CP', 'Clipperton sala');
INSERT INTO `country` (`id`, `name`) VALUES ('TD', 'Čadas');
INSERT INTO `country` (`id`, `name`) VALUES ('CZ', 'Čekija');
INSERT INTO `country` (`id`, `name`) VALUES ('CL', 'Čilė');
INSERT INTO `country` (`id`, `name`) VALUES ('DK', 'Danija');
INSERT INTO `country` (`id`, `name`) VALUES ('GB', 'Didžioji Britanija');
INSERT INTO `country` (`id`, `name`) VALUES ('VG', 'Didžiosios Britanijos Mergelių salos');
INSERT INTO `country` (`id`, `name`) VALUES ('DG', 'Diego Garcia');
INSERT INTO `country` (`id`, `name`) VALUES ('DM', 'Dominika');
INSERT INTO `country` (`id`, `name`) VALUES ('DO', 'Dominikos Respublika');
INSERT INTO `country` (`id`, `name`) VALUES ('CI', 'Dramblio Kaulo Krantas');
INSERT INTO `country` (`id`, `name`) VALUES ('JE', 'Džersis');
INSERT INTO `country` (`id`, `name`) VALUES ('DJ', 'Džibutis');
INSERT INTO `country` (`id`, `name`) VALUES ('EG', 'Egiptas');
INSERT INTO `country` (`id`, `name`) VALUES ('EC', 'Ekvadoras');
INSERT INTO `country` (`id`, `name`) VALUES ('ER', 'Eritrėja');
INSERT INTO `country` (`id`, `name`) VALUES ('EE', 'Estija');
INSERT INTO `country` (`id`, `name`) VALUES ('ET', 'Etiopija');
INSERT INTO `country` (`id`, `name`) VALUES ('EU', 'Europos Sąjunga');
INSERT INTO `country` (`id`, `name`) VALUES ('FK', 'Falklando salos');
INSERT INTO `country` (`id`, `name`) VALUES ('FO', 'Farerų salos');
INSERT INTO `country` (`id`, `name`) VALUES ('FJ', 'Fidžis');
INSERT INTO `country` (`id`, `name`) VALUES ('PH', 'Filipinai');
INSERT INTO `country` (`id`, `name`) VALUES ('GA', 'Gabonas');
INSERT INTO `country` (`id`, `name`) VALUES ('GY', 'Gajana');
INSERT INTO `country` (`id`, `name`) VALUES ('GM', 'Gambija');
INSERT INTO `country` (`id`, `name`) VALUES ('GH', 'Gana');
INSERT INTO `country` (`id`, `name`) VALUES ('GI', 'Gibraltaras');
INSERT INTO `country` (`id`, `name`) VALUES ('GR', 'Graikija');
INSERT INTO `country` (`id`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`id`, `name`) VALUES ('GL', 'Grenlandija');
INSERT INTO `country` (`id`, `name`) VALUES ('GE', 'Gruzija');
INSERT INTO `country` (`id`, `name`) VALUES ('GU', 'Guamas');
INSERT INTO `country` (`id`, `name`) VALUES ('GG', 'Guernsis');
INSERT INTO `country` (`id`, `name`) VALUES ('GP', 'Gvadelupė');
INSERT INTO `country` (`id`, `name`) VALUES ('GT', 'Gvatemala');
INSERT INTO `country` (`id`, `name`) VALUES ('GN', 'Gvinėja');
INSERT INTO `country` (`id`, `name`) VALUES ('HT', 'Haitis');
INSERT INTO `country` (`id`, `name`) VALUES ('HM', 'Heardo ir McDonaldo Salų Sritis');
INSERT INTO `country` (`id`, `name`) VALUES ('HN', 'Hondūras');
INSERT INTO `country` (`id`, `name`) VALUES ('IN', 'Indija');
INSERT INTO `country` (`id`, `name`) VALUES ('IO', 'Indijos vandenyno britų sritis');
INSERT INTO `country` (`id`, `name`) VALUES ('ID', 'Indonezija');
INSERT INTO `country` (`id`, `name`) VALUES ('IQ', 'Irakas');
INSERT INTO `country` (`id`, `name`) VALUES ('IR', 'Iranas');
INSERT INTO `country` (`id`, `name`) VALUES ('IS', 'Islandija');
INSERT INTO `country` (`id`, `name`) VALUES ('ES', 'Ispanija');
INSERT INTO `country` (`id`, `name`) VALUES ('IT', 'Italija');
INSERT INTO `country` (`id`, `name`) VALUES ('IL', 'Izraelis');
INSERT INTO `country` (`id`, `name`) VALUES ('JM', 'Jamaika');
INSERT INTO `country` (`id`, `name`) VALUES ('JP', 'Japonija');
INSERT INTO `country` (`id`, `name`) VALUES ('YE', 'Jemenas');
INSERT INTO `country` (`id`, `name`) VALUES ('JO', 'Jordanija');
INSERT INTO `country` (`id`, `name`) VALUES ('US', 'Jungtinės Valstijos');
INSERT INTO `country` (`id`, `name`) VALUES ('AE', 'Jungtiniai Arabų Emyratai');
INSERT INTO `country` (`id`, `name`) VALUES ('UM', 'Jungtinių Valstijų mažosios aplinkinės salos');
INSERT INTO `country` (`id`, `name`) VALUES ('ME', 'Juodkalnija');
INSERT INTO `country` (`id`, `name`) VALUES ('KY', 'Kaimanų salos');
INSERT INTO `country` (`id`, `name`) VALUES ('CX', 'Kalėdų sala');
INSERT INTO `country` (`id`, `name`) VALUES ('KH', 'Kambodža');
INSERT INTO `country` (`id`, `name`) VALUES ('CM', 'Kamerūnas');
INSERT INTO `country` (`id`, `name`) VALUES ('CA', 'Kanada');
INSERT INTO `country` (`id`, `name`) VALUES ('IC', 'Kanarų salos');
INSERT INTO `country` (`id`, `name`) VALUES ('QA', 'Kataras');
INSERT INTO `country` (`id`, `name`) VALUES ('KZ', 'Kazachstanas');
INSERT INTO `country` (`id`, `name`) VALUES ('KE', 'Kenija');
INSERT INTO `country` (`id`, `name`) VALUES ('CN', 'Kinija');
INSERT INTO `country` (`id`, `name`) VALUES ('HK', 'Kinijos S. A. R. Honkongas');
INSERT INTO `country` (`id`, `name`) VALUES ('CY', 'Kipras');
INSERT INTO `country` (`id`, `name`) VALUES ('KG', 'Kirgiztanas');
INSERT INTO `country` (`id`, `name`) VALUES ('KI', 'Kiribatis');
INSERT INTO `country` (`id`, `name`) VALUES ('CC', 'Kokosų salos');
INSERT INTO `country` (`id`, `name`) VALUES ('CO', 'Kolumbija');
INSERT INTO `country` (`id`, `name`) VALUES ('KM', 'Komorai');
INSERT INTO `country` (`id`, `name`) VALUES ('CG', 'Kongas');
INSERT INTO `country` (`id`, `name`) VALUES ('CD', 'Kongo Demokratinė Respublika');
INSERT INTO `country` (`id`, `name`) VALUES ('CR', 'Kosta Rika');
INSERT INTO `country` (`id`, `name`) VALUES ('HR', 'Kroatija');
INSERT INTO `country` (`id`, `name`) VALUES ('CU', 'Kuba');
INSERT INTO `country` (`id`, `name`) VALUES ('CK', 'Kuko salos');
INSERT INTO `country` (`id`, `name`) VALUES ('KW', 'Kuveitas');
INSERT INTO `country` (`id`, `name`) VALUES ('LA', 'Laosas');
INSERT INTO `country` (`id`, `name`) VALUES ('LV', 'Latvija');
INSERT INTO `country` (`id`, `name`) VALUES ('PL', 'Lenkija');
INSERT INTO `country` (`id`, `name`) VALUES ('LS', 'Lesotas');
INSERT INTO `country` (`id`, `name`) VALUES ('LB', 'Libanas');
INSERT INTO `country` (`id`, `name`) VALUES ('LR', 'Liberija');
INSERT INTO `country` (`id`, `name`) VALUES ('LY', 'Libija');
INSERT INTO `country` (`id`, `name`) VALUES ('LI', 'Lichtenšteinas');
INSERT INTO `country` (`id`, `name`) VALUES ('LT', 'Lietuva');
INSERT INTO `country` (`id`, `name`) VALUES ('LU', 'Liuksemburgas');
INSERT INTO `country` (`id`, `name`) VALUES ('MO', 'Macao');
INSERT INTO `country` (`id`, `name`) VALUES ('MG', 'Madagaskaras');
INSERT INTO `country` (`id`, `name`) VALUES ('YT', 'Mayotte’as');
INSERT INTO `country` (`id`, `name`) VALUES ('MK', 'Makedonija');
INSERT INTO `country` (`id`, `name`) VALUES ('MY', 'Malaizija');
INSERT INTO `country` (`id`, `name`) VALUES ('MW', 'Malavis');
INSERT INTO `country` (`id`, `name`) VALUES ('MV', 'Maldivai');
INSERT INTO `country` (`id`, `name`) VALUES ('ML', 'Malis');
INSERT INTO `country` (`id`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`id`, `name`) VALUES ('MP', 'Marianos šiaurinės salos');
INSERT INTO `country` (`id`, `name`) VALUES ('MA', 'Marokas');
INSERT INTO `country` (`id`, `name`) VALUES ('MH', 'Maršalo Salos');
INSERT INTO `country` (`id`, `name`) VALUES ('MQ', 'Martinika');
INSERT INTO `country` (`id`, `name`) VALUES ('MU', 'Mauricijus');
INSERT INTO `country` (`id`, `name`) VALUES ('MR', 'Mauritanija');
INSERT INTO `country` (`id`, `name`) VALUES ('IM', 'Meino sala');
INSERT INTO `country` (`id`, `name`) VALUES ('MX', 'Meksika');
INSERT INTO `country` (`id`, `name`) VALUES ('VI', 'Mergelių salos (JAV)');
INSERT INTO `country` (`id`, `name`) VALUES ('MM', 'Mianmaras');
INSERT INTO `country` (`id`, `name`) VALUES ('FM', 'Mikronezija');
INSERT INTO `country` (`id`, `name`) VALUES ('MD', 'Moldova');
INSERT INTO `country` (`id`, `name`) VALUES ('MC', 'Monakas');
INSERT INTO `country` (`id`, `name`) VALUES ('MN', 'Mongolija');
INSERT INTO `country` (`id`, `name`) VALUES ('MS', 'Montserratas');
INSERT INTO `country` (`id`, `name`) VALUES ('MZ', 'Mozambikas');
INSERT INTO `country` (`id`, `name`) VALUES ('NA', 'Namibija');
INSERT INTO `country` (`id`, `name`) VALUES ('NC', 'Naujoji Kaledonija');
INSERT INTO `country` (`id`, `name`) VALUES ('NZ', 'Naujoji Zelandija');
INSERT INTO `country` (`id`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`id`, `name`) VALUES ('NP', 'Nepalas');
INSERT INTO `country` (`id`, `name`) VALUES ('NL', 'Nyderlandai');
INSERT INTO `country` (`id`, `name`) VALUES ('NG', 'Nigerija');
INSERT INTO `country` (`id`, `name`) VALUES ('NE', 'Nigeris');
INSERT INTO `country` (`id`, `name`) VALUES ('NI', 'Nikaragva');
INSERT INTO `country` (`id`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`id`, `name`) VALUES ('NF', 'Norfolko sala');
INSERT INTO `country` (`id`, `name`) VALUES ('NO', 'Norvegija');
INSERT INTO `country` (`id`, `name`) VALUES ('QO', 'Nuošali Okeanija');
INSERT INTO `country` (`id`, `name`) VALUES ('AN', 'Olandijos Antilai');
INSERT INTO `country` (`id`, `name`) VALUES ('OM', 'Omanas');
INSERT INTO `country` (`id`, `name`) VALUES ('PK', 'Pakistanas');
INSERT INTO `country` (`id`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`id`, `name`) VALUES ('PS', 'Palestinos teritorija');
INSERT INTO `country` (`id`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`id`, `name`) VALUES ('PG', 'Papua Naujoji Gvinėja');
INSERT INTO `country` (`id`, `name`) VALUES ('PY', 'Paragvajus');
INSERT INTO `country` (`id`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`id`, `name`) VALUES ('ZA', 'Pietų Afrika');
INSERT INTO `country` (`id`, `name`) VALUES ('GS', 'Pietų Džordžija ir Pietų Sandvičo salos');
INSERT INTO `country` (`id`, `name`) VALUES ('KR', 'Pietų Korėja');
INSERT INTO `country` (`id`, `name`) VALUES ('PN', 'Pitkernas');
INSERT INTO `country` (`id`, `name`) VALUES ('PT', 'Portugalija');
INSERT INTO `country` (`id`, `name`) VALUES ('FR', 'Prancūzija');
INSERT INTO `country` (`id`, `name`) VALUES ('GF', 'Prancūzijos Gviana');
INSERT INTO `country` (`id`, `name`) VALUES ('TF', 'Prancūzijos Pietų sritys');
INSERT INTO `country` (`id`, `name`) VALUES ('PF', 'Prancūzų Polinezija');
INSERT INTO `country` (`id`, `name`) VALUES ('PR', 'Puerto Rikas');
INSERT INTO `country` (`id`, `name`) VALUES ('GQ', 'Pusiaujo Gvinėja');
INSERT INTO `country` (`id`, `name`) VALUES ('RE', 'Reunionas');
INSERT INTO `country` (`id`, `name`) VALUES ('TL', 'Rytų Timoras');
INSERT INTO `country` (`id`, `name`) VALUES ('RW', 'Ruanda');
INSERT INTO `country` (`id`, `name`) VALUES ('RO', 'Rumunija');
INSERT INTO `country` (`id`, `name`) VALUES ('RU', 'Rusijos Federacija');
INSERT INTO `country` (`id`, `name`) VALUES ('MF', 'Saint-Martin');
INSERT INTO `country` (`id`, `name`) VALUES ('SB', 'Saliamono salos');
INSERT INTO `country` (`id`, `name`) VALUES ('SV', 'Salvadoras');
INSERT INTO `country` (`id`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`id`, `name`) VALUES ('SM', 'San Marinas');
INSERT INTO `country` (`id`, `name`) VALUES ('ST', 'San Tomė ir Principė');
INSERT INTO `country` (`id`, `name`) VALUES ('SA', 'Saudo Arabija');
INSERT INTO `country` (`id`, `name`) VALUES ('SC', 'Seišeliai');
INSERT INTO `country` (`id`, `name`) VALUES ('PM', 'Sen Pjeras ir Mikelonas');
INSERT INTO `country` (`id`, `name`) VALUES ('SN', 'Senegalas');
INSERT INTO `country` (`id`, `name`) VALUES ('KN', 'Sent Kitsas ir Nevis');
INSERT INTO `country` (`id`, `name`) VALUES ('RS', 'Serbija');
INSERT INTO `country` (`id`, `name`) VALUES ('CS', 'Serbija ir Juodkalnija');
INSERT INTO `country` (`id`, `name`) VALUES ('SL', 'Siera Leonė');
INSERT INTO `country` (`id`, `name`) VALUES ('SG', 'Singapūras');
INSERT INTO `country` (`id`, `name`) VALUES ('SY', 'Sirija');
INSERT INTO `country` (`id`, `name`) VALUES ('SK', 'Slovakija');
INSERT INTO `country` (`id`, `name`) VALUES ('SI', 'Slovėnija');
INSERT INTO `country` (`id`, `name`) VALUES ('SO', 'Somalis');
INSERT INTO `country` (`id`, `name`) VALUES ('SD', 'Sudanas');
INSERT INTO `country` (`id`, `name`) VALUES ('FI', 'Suomija');
INSERT INTO `country` (`id`, `name`) VALUES ('SR', 'Surinamas');
INSERT INTO `country` (`id`, `name`) VALUES ('SJ', 'Svalbardo ir Jan Majen salos');
INSERT INTO `country` (`id`, `name`) VALUES ('SZ', 'Svazilendas');
INSERT INTO `country` (`id`, `name`) VALUES ('KP', 'Šiaurės Korėja');
INSERT INTO `country` (`id`, `name`) VALUES ('LK', 'Šri Lanka');
INSERT INTO `country` (`id`, `name`) VALUES ('SE', 'Švedija');
INSERT INTO `country` (`id`, `name`) VALUES ('CH', 'Šveicarija');
INSERT INTO `country` (`id`, `name`) VALUES ('VC', 'Šventasis Vincentas ir Grenadinai');
INSERT INTO `country` (`id`, `name`) VALUES ('BL', 'Švento Baltramiejaus sala');
INSERT INTO `country` (`id`, `name`) VALUES ('SH', 'Šventoji Elena');
INSERT INTO `country` (`id`, `name`) VALUES ('LC', 'Šventoji Liucija');
INSERT INTO `country` (`id`, `name`) VALUES ('TJ', 'Tadžikistanas');
INSERT INTO `country` (`id`, `name`) VALUES ('TH', 'Tailandas');
INSERT INTO `country` (`id`, `name`) VALUES ('TW', 'Taivanas');
INSERT INTO `country` (`id`, `name`) VALUES ('TZ', 'Tanzanija');
INSERT INTO `country` (`id`, `name`) VALUES ('TG', 'Togas');
INSERT INTO `country` (`id`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`id`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`id`, `name`) VALUES ('TT', 'Trinidadas ir Tobagas');
INSERT INTO `country` (`id`, `name`) VALUES ('TA', 'Tristan da Cunha');
INSERT INTO `country` (`id`, `name`) VALUES ('TN', 'Tunisas');
INSERT INTO `country` (`id`, `name`) VALUES ('TR', 'Turkija');
INSERT INTO `country` (`id`, `name`) VALUES ('TM', 'Turkmėnistanas');
INSERT INTO `country` (`id`, `name`) VALUES ('TC', 'Turkso ir Caicoso salos');
INSERT INTO `country` (`id`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`id`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`id`, `name`) VALUES ('UA', 'Ukraina');
INSERT INTO `country` (`id`, `name`) VALUES ('UY', 'Urugvajus');
INSERT INTO `country` (`id`, `name`) VALUES ('UZ', 'Uzbekistanas');
INSERT INTO `country` (`id`, `name`) VALUES ('EH', 'Vakarų Sachara');
INSERT INTO `country` (`id`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`id`, `name`) VALUES ('VA', 'Vatikanas');
INSERT INTO `country` (`id`, `name`) VALUES ('VE', 'Venesuela');
INSERT INTO `country` (`id`, `name`) VALUES ('HU', 'Vengrija');
INSERT INTO `country` (`id`, `name`) VALUES ('VN', 'Vietnamas');
INSERT INTO `country` (`id`, `name`) VALUES ('DE', 'Vokietija');
INSERT INTO `country` (`id`, `name`) VALUES ('WF', 'Wallisas ir Futuna');
INSERT INTO `country` (`id`, `name`) VALUES ('ZM', 'Zambija');
INSERT INTO `country` (`id`, `name`) VALUES ('ZW', 'Zimbabvė');
INSERT INTO `country` (`id`, `name`) VALUES ('CV', 'Žaliasis Kyšulys');
