CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AI', 'அங்குய்லா');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'அங்கோலா');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'அண்டார்டிகா');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'அமெரிக்க சமோவா');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'அயர்லாந்து');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'அர்ஜென்டினா');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'அரூபா');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'அல்பேனியா');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'அல்ஜீரியா');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'அன்டோரா');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'அஜர்பைஜான்');
INSERT INTO "country" ("id", "name") VALUES ('AC', 'அஷன்ஷியன் தீவு');
INSERT INTO "country" ("id", "name") VALUES ('AG', 'ஆண்டிகுவா மற்றும் பார்புடா');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'ஆப்கானிஸ்தான்');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'ஆர்மேனியா');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'ஆலந்து தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'ஆஸ்திரியா');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'ஆஸ்திரேலியா');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'இத்தாலி');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'இந்தியா');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'இந்தோனேஷியா');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'இராக்');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'இலங்கை');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'இஸ்ரேல்');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'ஈக்குவாடோரியல் கினி');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'ஈக்வடார்');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'ஈரான்');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'உக்ரைன்');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'உகாண்டா');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'உருகுவே');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'உஸ்பெகிஸ்தான்');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'எகிப்து');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'எதியோப்பியா');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'எரிட்ரியா');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'எல் சால்வடார்');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'எஸ்டோனியா');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'ஏமன்');
INSERT INTO "country" ("id", "name") VALUES ('US', 'ஐக்கிய அமெரிக்க குடியரசு');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'ஐக்கிய அரபு கூட்டாட்சி');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'ஐரோப்பியன் யூனியன்');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'ஐல் ஆஃப் மேன்');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'ஐவரி கோஸ்ட்');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'ஐஸ்லாந்து');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'ஓமன்');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'ஔட்லையிங் ஓசானியா');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'ஃப்ரென்ச் கயானா');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'ஃப்ரென்ச் தெற்கு மாஹாணங்கள்');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'ஃப்ரென்ச் பாலினேஷியா');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'ஃபாக்லாந்து தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'ஃபிஜி');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'ஃபெரௌ தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'க்வாதேலோப்');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'கதார்');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'கம்போடியா');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'கயானா');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'கனடா');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'கஸகஸ்தான்');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'காகோஸ் தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'காங்கோ - கின்ஷாசா');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'காங்கோ - ப்ராஸாவில்லே');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'காம்பியா');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'கானா');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'கியூபா');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'கிர்கிஸ்தான்');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'கிரனெடா');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'கிரிபடி');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'கிரீன்லாந்து');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'கிரீஸ்');
INSERT INTO "country" ("id", "name") VALUES ('CP', 'கிலிப்பர்டன் தீவு');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'கிழக்கு தைமூர்');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'கிறிஸ்துமஸ் தீவு');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'கினி-பிஸ்ஸாவ்');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'கினியா');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'குக் தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'குரோசியா');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'குவாத்தாமாலா');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'குவாம்');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'குவைத்து');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'கெர்ன்சி');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'கென்யா');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'கேப் வெர்டே');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'கேபான்');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'கேமரூன்');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'கேமென் தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('IC', 'கேனரி தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'கொலம்பியா');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'கோமரோஸ்');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'கோஸ்டாரிகா');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'சமோவா');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'சவூதி அரேபியா');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'சாட்');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'சாம்பியா');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'சாலமன் தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'சாவ் தோம் மற்றும் ப்ரின்சிபி');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'சான் மெரினோ');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'சிங்கப்பூர்');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'சியர்ரா லியோன்');
INSERT INTO "country" ("id", "name") VALUES ('EA', 'சியூடா மற்றும் மெலில்லா');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'சிரியா');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'சிலி');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'சீனா');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'சூடான்');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'சூரினாம்');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'செக் குடியரசு');
INSERT INTO "country" ("id", "name") VALUES ('MF', 'செயின் மார்டீன்');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'செயின் வின்சன்ட் மற்றும் கிரெனடைன்ஸ்');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'செயின்ட் கிட்ஸ் மற்றும் நெவிஸ்');
INSERT INTO "country" ("id", "name") VALUES ('BL', 'செயின்ட் பார்தேலெமி');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'செயின்ட் பியர் மற்றும் மிக்வேலான்');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'செயின்ட் லூசியா');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'செயின்ட் ஹெலெனா');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'செர்பியா');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'செர்பியா மற்றும் மான்டேநெக்ரோ');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'செனெகல்');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'சைப்ரஸ்');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'சொமாலியா');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'ட்ரினிடாட் மற்றும் டுபாகோ');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'டர்க்ஸ் மற்றும் கைகோஸ் தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'டான்சானியா');
INSERT INTO "country" ("id", "name") VALUES ('DG', 'டியகோ கார்ஷியா');
INSERT INTO "country" ("id", "name") VALUES ('TA', 'டிரிஸ்டன் டா குன்ஹா');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'டுனிசியா');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'டென்மார்க்');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'டொமினிகன் குடியரசு');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'டொமினிகா');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'டோகேலோ');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'டோகோ');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'டோங்கா');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'தாய்லாந்து');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'தாஜிகிஸ்தான்');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'துர்க்மெனிஸ்தான்');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'துருக்கி');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'துவாலூ');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'தென் ஆப்பிரிக்கா');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'தென் கொரியா');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'தென் ஜியார்ஜியா மற்றும் தென் சான்ட்விச் தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'தைவான்');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'நமீபியா');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'நார்ஃபாக் தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'நார்வே');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'நிகாரகுவா');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'நியூ');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'நியூ கேலிடோனியா');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'நியூசிலாந்து');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'நெதர்லாந்து');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'நெதர்லாந்து ஆண்டில்லெஸ்');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'நேபாளம்');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'நைஜர்');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'நைஜீரியா');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'நௌரு');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'பங்களாதேஷ்');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'பல்கேரியா');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'பனாமா');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'பஹ்ரைன்');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'பஹாமாஸ்');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'பாகிஸ்தான்');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'பாப்புவா நியூ கினி');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'பார்படோஸ்');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'பாரகுவே');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'பாலஸ்தீனியன் மாஹாணங்கள்');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'பாலோ');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'பிட்கெய்ர்ன்');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'பியூர்டோ ரிகோ');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'பிரான்ஸ்');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'பிரிட்டிஷ் இந்தியப் பெருங்கடல் பகுதி');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'பிரிட்டீஷ் கன்னித் தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'பிரிடிஷ் கூட்டரசு');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'பிரேஸில்');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'பிலிப்பைன்ஸ்');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'பின்லாந்து');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'புர்கினா ஃபாஸோ');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'புருண்டி');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'புரூனேய்');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'பூடான்');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'பெர்முடா');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'பெரு');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'பெல்ஜியம்');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'பெலாரூஸ்');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'பெலிஸ்');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'பெனின்');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'பொலிவியா');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'பொவேட் தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'போட்ஸ்வானா');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'போர்ச்சுக்கல்');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'போலந்து');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'போஸ்னியா மற்றும் ஹெர்ஸிகோவினா');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'மகாவோ சார் சீனா');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'மங்கோலியா');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'மடகாஸ்கர்');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'மத்திய ஆப்ரிக்கக் குடியரசு');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'மயோத்');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'மலேஷியா');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'மாசிடோனியா');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'மார்டினிக்');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'மார்ஷல் தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'மால்டா');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'மால்டோவா');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'மாலத்தீவு');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'மாலவி');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'மாலீ');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'மான்டேனெக்ரோ');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'மியான்மார் [பர்மா]');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'மெக்சிகோ');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'மேற்கு சஹாரா');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'மைக்ரோனேஷியா');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'மொசாம்பிக்');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'மொராக்கோ');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'மொரிசியஸ்');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'மொனாக்கோ');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'மௌரிடானியா');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'மௌன்ட்செராட்');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'யுனைட்டட் ஸ்டேட்ஸும் சிறிய அவுட்லைன் தீவுகளும்');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'யூ.எஸ் கன்னித் தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'ரஷ்யா');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'ரீயூனியன்');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'ருமேனியா');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'ருவான்டா');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'லக்ஸ்சம்பர்க்');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'லாட்வியா');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'லாவோஸ்');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'லிச்செண்ஸ்டெய்ன்');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'லிதுவேனியா');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'லிபியா');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'லெசோதோ');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'லெபனான்');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'லைபீரியா');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'வட கொரியா');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'வடக்கு மரியானா தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'வனுவாட்டு');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'வாடிகன்');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'வாலிஸ் மற்றும் ஃபுடுனா தீவுகள்');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'வியட்நாம்');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'வெனஜுவேலா');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'ஜப்பான்');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'ஜமைகா');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'ஜார்ஜியா');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'ஜிப்ரால்டர்');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'ஜிபௌட்டி');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'ஜிம்பாப்வே');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'ஜெர்சி');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'ஜெர்மன்');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'ஜொர்டான்');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'ஸ்பெயின்');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'ஸ்லோவாகியா');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'ஸ்லோவேனியா');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'ஸ்வல்பார்டு மற்றும் ஜான் மேயன்');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'ஸ்வாஸிலாண்ட்');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'ஸ்விட்சர்லாந்து');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'ஸ்வீடன்');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'ஸேசேல்ஸ்');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'ஹங்கேரி');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'ஹாங்காங் சார் சீனா');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'ஹாண்டுராஸ்');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'ஹெய்தி');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'ஹேர்ட் மற்றும் மெக்டொனால்டு');
