CREATE TABLE country (id VARCHAR(2) NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id));

INSERT INTO "country" ("id", "name") VALUES ('AG', 'Aintíge agus Barbúda');
INSERT INTO "country" ("id", "name") VALUES ('ET', 'An Aetóip');
INSERT INTO "country" ("id", "name") VALUES ('AF', 'An Afganastáin');
INSERT INTO "country" ("id", "name") VALUES ('ZA', 'An Afraic Theas');
INSERT INTO "country" ("id", "name") VALUES ('QO', 'An Aigéine Imeallach');
INSERT INTO "country" ("id", "name") VALUES ('DZ', 'An Ailgéir');
INSERT INTO "country" ("id", "name") VALUES ('AR', 'An Airgintín');
INSERT INTO "country" ("id", "name") VALUES ('AM', 'An Airméin');
INSERT INTO "country" ("id", "name") VALUES ('AL', 'An Albáin');
INSERT INTO "country" ("id", "name") VALUES ('AQ', 'An Antartaice');
INSERT INTO "country" ("id", "name") VALUES ('SA', 'An Araib Shádach');
INSERT INTO "country" ("id", "name") VALUES ('AZ', 'An Asarbaiseáin');
INSERT INTO "country" ("id", "name") VALUES ('AU', 'An Astráil');
INSERT INTO "country" ("id", "name") VALUES ('BD', 'An Bhanglaidéis');
INSERT INTO "country" ("id", "name") VALUES ('BY', 'An Bhealarúis');
INSERT INTO "country" ("id", "name") VALUES ('BE', 'An Bheilg');
INSERT INTO "country" ("id", "name") VALUES ('BZ', 'An Bheilís');
INSERT INTO "country" ("id", "name") VALUES ('BA', 'An Bhoisnia agus Heirseagóvéin');
INSERT INTO "country" ("id", "name") VALUES ('BO', 'An Bholaiv');
INSERT INTO "country" ("id", "name") VALUES ('BW', 'An Bhotsuáin');
INSERT INTO "country" ("id", "name") VALUES ('BR', 'An Bhrasaíl');
INSERT INTO "country" ("id", "name") VALUES ('BG', 'An Bhulgáir');
INSERT INTO "country" ("id", "name") VALUES ('BI', 'An Bhurúin');
INSERT INTO "country" ("id", "name") VALUES ('BT', 'An Bhútáin');
INSERT INTO "country" ("id", "name") VALUES ('KH', 'An Chambóid');
INSERT INTO "country" ("id", "name") VALUES ('KZ', 'An Chasacstáin');
INSERT INTO "country" ("id", "name") VALUES ('KE', 'An Chéinia');
INSERT INTO "country" ("id", "name") VALUES ('CY', 'An Chipir');
INSERT INTO "country" ("id", "name") VALUES ('KG', 'An Chirgeastáin');
INSERT INTO "country" ("id", "name") VALUES ('KR', 'An Chóiré Theas');
INSERT INTO "country" ("id", "name") VALUES ('KP', 'An Chóiré Thuaidh');
INSERT INTO "country" ("id", "name") VALUES ('CO', 'An Cholóim');
INSERT INTO "country" ("id", "name") VALUES ('HR', 'An Chróit');
INSERT INTO "country" ("id", "name") VALUES ('CG', 'An Congó');
INSERT INTO "country" ("id", "name") VALUES ('CI', 'An Cósta Eabhair');
INSERT INTO "country" ("id", "name") VALUES ('DK', 'An Danmhairg');
INSERT INTO "country" ("id", "name") VALUES ('EE', 'An Eastóin');
INSERT INTO "country" ("id", "name") VALUES ('EG', 'An Éigipt');
INSERT INTO "country" ("id", "name") VALUES ('CH', 'An Eilvéis');
INSERT INTO "country" ("id", "name") VALUES ('ER', 'An Eiritré');
INSERT INTO "country" ("id", "name") VALUES ('FI', 'An Fhionlainn');
INSERT INTO "country" ("id", "name") VALUES ('FR', 'An Fhrainc');
INSERT INTO "country" ("id", "name") VALUES ('GA', 'An Ghabúin');
INSERT INTO "country" ("id", "name") VALUES ('GM', 'An Ghaimbia');
INSERT INTO "country" ("id", "name") VALUES ('DE', 'An Ghearmáin');
INSERT INTO "country" ("id", "name") VALUES ('GL', 'An Ghraonlainn');
INSERT INTO "country" ("id", "name") VALUES ('GR', 'An Ghréig');
INSERT INTO "country" ("id", "name") VALUES ('GY', 'An Ghuáin');
INSERT INTO "country" ("id", "name") VALUES ('GF', 'An Ghuáin Fhrancach');
INSERT INTO "country" ("id", "name") VALUES ('GN', 'An Ghuine');
INSERT INTO "country" ("id", "name") VALUES ('GQ', 'An Ghuine Mheánchriosach');
INSERT INTO "country" ("id", "name") VALUES ('GW', 'An Ghuine-Bhissau');
INSERT INTO "country" ("id", "name") VALUES ('IQ', 'An Iaráic');
INSERT INTO "country" ("id", "name") VALUES ('IR', 'An Iaráin');
INSERT INTO "country" ("id", "name") VALUES ('IN', 'An India');
INSERT INTO "country" ("id", "name") VALUES ('ID', 'An Indinéis');
INSERT INTO "country" ("id", "name") VALUES ('IT', 'An Iodáil');
INSERT INTO "country" ("id", "name") VALUES ('JO', 'An Iordáin');
INSERT INTO "country" ("id", "name") VALUES ('NO', 'An Iorua');
INSERT INTO "country" ("id", "name") VALUES ('IS', 'An Íoslainn');
INSERT INTO "country" ("id", "name") VALUES ('NL', 'An Ísiltír');
INSERT INTO "country" ("id", "name") VALUES ('LV', 'An Laitvia');
INSERT INTO "country" ("id", "name") VALUES ('LR', 'An Libéir');
INSERT INTO "country" ("id", "name") VALUES ('LY', 'An Libia');
INSERT INTO "country" ("id", "name") VALUES ('LB', 'An Liobáin');
INSERT INTO "country" ("id", "name") VALUES ('LT', 'An Liotuáin');
INSERT INTO "country" ("id", "name") VALUES ('MK', 'An Mhacadóin');
INSERT INTO "country" ("id", "name") VALUES ('MY', 'An Mhalaeisia');
INSERT INTO "country" ("id", "name") VALUES ('MW', 'An Mhaláiv');
INSERT INTO "country" ("id", "name") VALUES ('MR', 'An Mharatáin');
INSERT INTO "country" ("id", "name") VALUES ('FM', 'An Mhicrinéis');
INSERT INTO "country" ("id", "name") VALUES ('MD', 'An Mholdóiv');
INSERT INTO "country" ("id", "name") VALUES ('MN', 'An Mhongóil');
INSERT INTO "country" ("id", "name") VALUES ('NA', 'An Namaib');
INSERT INTO "country" ("id", "name") VALUES ('NG', 'An Nigéir');
INSERT INTO "country" ("id", "name") VALUES ('NE', 'An Nígir');
INSERT INTO "country" ("id", "name") VALUES ('NC', 'An Nua-Chaladóin');
INSERT INTO "country" ("id", "name") VALUES ('NZ', 'An Nua-Shéalainn');
INSERT INTO "country" ("id", "name") VALUES ('AT', 'An Ostair');
INSERT INTO "country" ("id", "name") VALUES ('PK', 'An Phacastáin');
INSERT INTO "country" ("id", "name") VALUES ('DO', 'An Phoblacht Dhoiminiceach');
INSERT INTO "country" ("id", "name") VALUES ('PF', 'An Pholainéis Fhrancach');
INSERT INTO "country" ("id", "name") VALUES ('PL', 'An Pholainn');
INSERT INTO "country" ("id", "name") VALUES ('PT', 'An Phortaingéil');
INSERT INTO "country" ("id", "name") VALUES ('CV', 'An Rinn Ghlas');
INSERT INTO "country" ("id", "name") VALUES ('GB', 'An Ríocht Aontaithe');
INSERT INTO "country" ("id", "name") VALUES ('RO', 'An Rómáin');
INSERT INTO "country" ("id", "name") VALUES ('EH', 'An Sahára Thiar');
INSERT INTO "country" ("id", "name") VALUES ('ES', 'An Spáinn');
INSERT INTO "country" ("id", "name") VALUES ('TJ', 'An Táidsíceastáin');
INSERT INTO "country" ("id", "name") VALUES ('TZ', 'An Tansáin');
INSERT INTO "country" ("id", "name") VALUES ('EU', 'An tAontas Eorpach');
INSERT INTO "country" ("id", "name") VALUES ('TH', 'An Téalainn');
INSERT INTO "country" ("id", "name") VALUES ('TW', 'An Téaváin');
INSERT INTO "country" ("id", "name") VALUES ('ZM', 'An tSaimbia');
INSERT INTO "country" ("id", "name") VALUES ('SV', 'An tSalvadóir');
INSERT INTO "country" ("id", "name") VALUES ('JP', 'An tSeapáin');
INSERT INTO "country" ("id", "name") VALUES ('SN', 'An tSeineagáil');
INSERT INTO "country" ("id", "name") VALUES ('RS', 'An tSeirbia');
INSERT INTO "country" ("id", "name") VALUES ('CS', 'An tSeirbia agus Montainéagró');
INSERT INTO "country" ("id", "name") VALUES ('GE', 'An tSeoirsia');
INSERT INTO "country" ("id", "name") VALUES ('GS', 'An tSeoirsia Theas agus Oileáin Sandwich Theas');
INSERT INTO "country" ("id", "name") VALUES ('CL', 'An tSile');
INSERT INTO "country" ("id", "name") VALUES ('CN', 'An tSín');
INSERT INTO "country" ("id", "name") VALUES ('ZW', 'An tSiombáib');
INSERT INTO "country" ("id", "name") VALUES ('SY', 'An tSiria');
INSERT INTO "country" ("id", "name") VALUES ('SK', 'An tSlóvaic');
INSERT INTO "country" ("id", "name") VALUES ('SI', 'An tSlóvéin');
INSERT INTO "country" ("id", "name") VALUES ('SO', 'An tSomáil');
INSERT INTO "country" ("id", "name") VALUES ('SE', 'An tSualainn');
INSERT INTO "country" ("id", "name") VALUES ('SZ', 'An tSuasalainn');
INSERT INTO "country" ("id", "name") VALUES ('SD', 'An tSúdáin');
INSERT INTO "country" ("id", "name") VALUES ('TN', 'An Túinéis');
INSERT INTO "country" ("id", "name") VALUES ('TR', 'An Tuirc');
INSERT INTO "country" ("id", "name") VALUES ('TM', 'An Tuircméanastáin');
INSERT INTO "country" ("id", "name") VALUES ('UA', 'An Úcráin');
INSERT INTO "country" ("id", "name") VALUES ('HU', 'An Ungáir');
INSERT INTO "country" ("id", "name") VALUES ('VA', 'An Vatacáin');
INSERT INTO "country" ("id", "name") VALUES ('AD', 'Andóra');
INSERT INTO "country" ("id", "name") VALUES ('AO', 'Angóla');
INSERT INTO "country" ("id", "name") VALUES ('AI', 'Anguilla');
INSERT INTO "country" ("id", "name") VALUES ('AN', 'Antillí na hÍsiltíre');
INSERT INTO "country" ("id", "name") VALUES ('AE', 'Aontas na nÉimíríochtaí Arabacha');
INSERT INTO "country" ("id", "name") VALUES ('AW', 'Arúba');
INSERT INTO "country" ("id", "name") VALUES ('BH', 'Bairéin');
INSERT INTO "country" ("id", "name") VALUES ('BB', 'Barbadós');
INSERT INTO "country" ("id", "name") VALUES ('BJ', 'Beinin');
INSERT INTO "country" ("id", "name") VALUES ('BM', 'Beirmiúda');
INSERT INTO "country" ("id", "name") VALUES ('BN', 'Brúiné');
INSERT INTO "country" ("id", "name") VALUES ('BF', 'Buircíne Fasó');
INSERT INTO "country" ("id", "name") VALUES ('CM', 'Camarún');
INSERT INTO "country" ("id", "name") VALUES ('QA', 'Catar');
INSERT INTO "country" ("id", "name") VALUES ('CA', 'Ceanada');
INSERT INTO "country" ("id", "name") VALUES ('KI', 'Ciribeas');
INSERT INTO "country" ("id", "name") VALUES ('RU', 'Cónaidhm na Rúise');
INSERT INTO "country" ("id", "name") VALUES ('CR', 'Cósta Ríce');
INSERT INTO "country" ("id", "name") VALUES ('IO', 'Críocha Briotanacha an Aigéin Indiagh');
INSERT INTO "country" ("id", "name") VALUES ('TF', 'Críocha Deisceartacha na Fraince');
INSERT INTO "country" ("id", "name") VALUES ('KW', 'Cuáit');
INSERT INTO "country" ("id", "name") VALUES ('CU', 'Cúba');
INSERT INTO "country" ("id", "name") VALUES ('DJ', 'Djibouti');
INSERT INTO "country" ("id", "name") VALUES ('DM', 'Doiminice');
INSERT INTO "country" ("id", "name") VALUES ('EC', 'Eacuadór');
INSERT INTO "country" ("id", "name") VALUES ('YE', 'Éimin');
INSERT INTO "country" ("id", "name") VALUES ('IE', 'Éire');
INSERT INTO "country" ("id", "name") VALUES ('FJ', 'Fidsí');
INSERT INTO "country" ("id", "name") VALUES ('GH', 'Gána');
INSERT INTO "country" ("id", "name") VALUES ('GG', 'Geansaí');
INSERT INTO "country" ("id", "name") VALUES ('JE', 'Geirsí');
INSERT INTO "country" ("id", "name") VALUES ('GI', 'Giobráltar');
INSERT INTO "country" ("id", "name") VALUES ('GD', 'Grenada');
INSERT INTO "country" ("id", "name") VALUES ('GP', 'Guadalúip');
INSERT INTO "country" ("id", "name") VALUES ('GU', 'Guam');
INSERT INTO "country" ("id", "name") VALUES ('GT', 'Guatamala');
INSERT INTO "country" ("id", "name") VALUES ('HT', 'Háití');
INSERT INTO "country" ("id", "name") VALUES ('HN', 'Hondúras');
INSERT INTO "country" ("id", "name") VALUES ('JM', 'Iamáice');
INSERT INTO "country" ("id", "name") VALUES ('IL', 'Iosrael');
INSERT INTO "country" ("id", "name") VALUES ('LA', 'Laos');
INSERT INTO "country" ("id", "name") VALUES ('LS', 'Leosóta');
INSERT INTO "country" ("id", "name") VALUES ('LI', 'Lichtinstéin');
INSERT INTO "country" ("id", "name") VALUES ('LU', 'Lucsamburg');
INSERT INTO "country" ("id", "name") VALUES ('MG', 'Madagascar');
INSERT INTO "country" ("id", "name") VALUES ('MM', 'Maenmar');
INSERT INTO "country" ("id", "name") VALUES ('ML', 'Mailí');
INSERT INTO "country" ("id", "name") VALUES ('MT', 'Málta');
INSERT INTO "country" ("id", "name") VALUES ('MA', 'Maracó');
INSERT INTO "country" ("id", "name") VALUES ('MQ', 'Martainíc');
INSERT INTO "country" ("id", "name") VALUES ('YT', 'Mayotte');
INSERT INTO "country" ("id", "name") VALUES ('MX', 'Meicsiceo');
INSERT INTO "country" ("id", "name") VALUES ('UM', 'Mion-Oileáin Imeallacha S.A.M.');
INSERT INTO "country" ("id", "name") VALUES ('MC', 'Monacó');
INSERT INTO "country" ("id", "name") VALUES ('ME', 'Montainéagró');
INSERT INTO "country" ("id", "name") VALUES ('MS', 'Montsarat');
INSERT INTO "country" ("id", "name") VALUES ('MZ', 'Mósaimbíc');
INSERT INTO "country" ("id", "name") VALUES ('BS', 'Na Bahámaí');
INSERT INTO "country" ("id", "name") VALUES ('PS', 'Na Críocha Pailistíneacha');
INSERT INTO "country" ("id", "name") VALUES ('PH', 'Na hOileáin Fhilipíneacha');
INSERT INTO "country" ("id", "name") VALUES ('MV', 'Na Maildiví');
INSERT INTO "country" ("id", "name") VALUES ('SC', 'Na Séiséil');
INSERT INTO "country" ("id", "name") VALUES ('NR', 'Nárú');
INSERT INTO "country" ("id", "name") VALUES ('NP', 'Neipeal');
INSERT INTO "country" ("id", "name") VALUES ('NI', 'Nicearagua');
INSERT INTO "country" ("id", "name") VALUES ('NU', 'Nívé');
INSERT INTO "country" ("id", "name") VALUES ('PG', 'Nua-Ghuine Phapua');
INSERT INTO "country" ("id", "name") VALUES ('AX', 'Oileáin Alaind');
INSERT INTO "country" ("id", "name") VALUES ('VG', 'Oileáin Bhriotanacha na Maighdean');
INSERT INTO "country" ("id", "name") VALUES ('KM', 'Oileáin Chomóra');
INSERT INTO "country" ("id", "name") VALUES ('CK', 'Oileáin Cook');
INSERT INTO "country" ("id", "name") VALUES ('FK', 'Oileáin Fháclainne');
INSERT INTO "country" ("id", "name") VALUES ('FO', 'Oileáin Fharó');
INSERT INTO "country" ("id", "name") VALUES ('MP', 'Oileáin Mariana Thuaidh');
INSERT INTO "country" ("id", "name") VALUES ('MH', 'Oileáin Marshall');
INSERT INTO "country" ("id", "name") VALUES ('KY', 'Oileáin na gCadhman');
INSERT INTO "country" ("id", "name") VALUES ('CC', 'Oileáin na gCócónna');
INSERT INTO "country" ("id", "name") VALUES ('VI', 'Oileáin na Maighdean S.A.M.');
INSERT INTO "country" ("id", "name") VALUES ('TT', 'Oileáin na Tríonóide agus Tobága');
INSERT INTO "country" ("id", "name") VALUES ('SB', 'Oileáin Sholaimh');
INSERT INTO "country" ("id", "name") VALUES ('TC', 'Oileáin Turks agus Caicos');
INSERT INTO "country" ("id", "name") VALUES ('WF', 'Oileáin Vailís agus Futúna');
INSERT INTO "country" ("id", "name") VALUES ('BV', 'Oileán Bouvet');
INSERT INTO "country" ("id", "name") VALUES ('HM', 'Oileán Heard agus Oileáin McDonald');
INSERT INTO "country" ("id", "name") VALUES ('IM', 'Oileán Mhanann');
INSERT INTO "country" ("id", "name") VALUES ('MU', 'Oileán Mhuirís');
INSERT INTO "country" ("id", "name") VALUES ('CX', 'Oileán na Nollag');
INSERT INTO "country" ("id", "name") VALUES ('NF', 'Oileán Norfolk');
INSERT INTO "country" ("id", "name") VALUES ('OM', 'Óman');
INSERT INTO "country" ("id", "name") VALUES ('PW', 'Palau');
INSERT INTO "country" ("id", "name") VALUES ('PA', 'Panama');
INSERT INTO "country" ("id", "name") VALUES ('PY', 'Paragua');
INSERT INTO "country" ("id", "name") VALUES ('PE', 'Peiriú');
INSERT INTO "country" ("id", "name") VALUES ('PN', 'Pitcairn');
INSERT INTO "country" ("id", "name") VALUES ('CD', 'Poblacht Dhaonlathach an Chongó');
INSERT INTO "country" ("id", "name") VALUES ('CF', 'Poblacht na hAfraice Láir');
INSERT INTO "country" ("id", "name") VALUES ('CZ', 'Poblacht na Seice');
INSERT INTO "country" ("id", "name") VALUES ('PR', 'Portó Ríce');
INSERT INTO "country" ("id", "name") VALUES ('HK', 'R.R.S. na Síne Hong Cong');
INSERT INTO "country" ("id", "name") VALUES ('MO', 'R.R.S. na Síne Macáó');
INSERT INTO "country" ("id", "name") VALUES ('RE', 'Réunion');
INSERT INTO "country" ("id", "name") VALUES ('RW', 'Ruanda');
INSERT INTO "country" ("id", "name") VALUES ('KN', 'Saint Kitts agus Nevis');
INSERT INTO "country" ("id", "name") VALUES ('PM', 'Saint Pierre agus Miquelon');
INSERT INTO "country" ("id", "name") VALUES ('VC', 'Saint Vincent agus na Grenadines');
INSERT INTO "country" ("id", "name") VALUES ('WS', 'Samó');
INSERT INTO "country" ("id", "name") VALUES ('AS', 'Samó Meiriceánach');
INSERT INTO "country" ("id", "name") VALUES ('SH', 'San Héilin');
INSERT INTO "country" ("id", "name") VALUES ('LC', 'San Lúisia');
INSERT INTO "country" ("id", "name") VALUES ('SM', 'San Mairíne');
INSERT INTO "country" ("id", "name") VALUES ('ST', 'Sao Tome agus Principe');
INSERT INTO "country" ("id", "name") VALUES ('TD', 'Sead');
INSERT INTO "country" ("id", "name") VALUES ('SL', 'Siarra Leon');
INSERT INTO "country" ("id", "name") VALUES ('SG', 'Singeapór');
INSERT INTO "country" ("id", "name") VALUES ('LK', 'Srí Lanca');
INSERT INTO "country" ("id", "name") VALUES ('US', 'Stáit Aontaithe Mheiriceá');
INSERT INTO "country" ("id", "name") VALUES ('SR', 'Suranam');
INSERT INTO "country" ("id", "name") VALUES ('SJ', 'Svalbard agus Jan Mayen');
INSERT INTO "country" ("id", "name") VALUES ('TL', 'Tíomór Thoir');
INSERT INTO "country" ("id", "name") VALUES ('TK', 'Tócalá');
INSERT INTO "country" ("id", "name") VALUES ('TG', 'Tóga');
INSERT INTO "country" ("id", "name") VALUES ('TO', 'Tonga');
INSERT INTO "country" ("id", "name") VALUES ('TV', 'Túválú');
INSERT INTO "country" ("id", "name") VALUES ('UG', 'Úganda');
INSERT INTO "country" ("id", "name") VALUES ('UZ', 'Úisbéiceastáin');
INSERT INTO "country" ("id", "name") VALUES ('UY', 'Urugua');
INSERT INTO "country" ("id", "name") VALUES ('VU', 'Vanuatú');
INSERT INTO "country" ("id", "name") VALUES ('VE', 'Veiniséala');
INSERT INTO "country" ("id", "name") VALUES ('VN', 'Vít Neam');
